### ISSUE TITLE
No response body when using Try It

### ISSUE THREAD

**Issue by asanka88** [swagger-api/swagger-core#1003]
Hi Devs,
I am a newbie to swagger. Pardon me if my question is not very well descriptive . 

My Swagger application and web server that send info to swagger are hosted in two different domains. In the beginning, I couldn't get any information since I hadn't enabled CORS in the web server. After I added following headers to the response swagger started to show all the information.

headersMap.put("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT, PATCH, OPTIONS");
            headersMap.put("Access-Control-Allow-Origin", "*");
            headersMap.put("Access-Control-Allow-Headers", "accept, appid, appname, authorization, content-type");

 But when I perform try it.. it doesn't give me a response. All I can see it 
{"error":"No Response from server"}

I read in some places , it is related to request-headers and allow headers. But I made sure those are the same . 

But still no luck.
I would be extremely grateful , If someone could shed some light in this.

Cheers,
Asanka

**Comment by webron** [comment]
Can you run `curl -I <url of a REST API>` and paste the result here?

**Comment by asanka88** [comment]
Hi @webron ,
Please find the response below.

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Accept: */*
Access-Control-Allow-Headers: accept, appid, appname, authorization, content-type
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
Access-Control-Allow-Origin: *
Host: myhost..com:11243
Date: Wed, 22 Apr 2015 15:46:25 GMT
Transfer-Encoding: chunked


Thanks,
Asanka

**Comment by webron** [comment]
Any chance your API is public?

**Comment by asanka88** [comment]
:( No. That is not public. Can you spot any issue with the information I provided?

**Comment by webron** [comment]
I'm not sure the error you're seeing is from the UI itself. Please open the network tab of your browser's web console and see which operation(s) are being called when you click on the try it now button.

**Comment by webron** [comment]
@asanka88 - any update?

**Comment by fehguy** [comment]
Please reopen if still an issue.

**Comment by arjun2691** [comment]
Hello, I am getting response in the network console..but it is displaying no response in the response body.. Please reply

**Comment by anubhav143** [comment]
Hi @webron I am facing the same issue and getting a 302 Found on curl -I. Can u help ?
