### ISSUE TITLE
Wrong location of default and enum nodes for array parameter.

### ISSUE THREAD

**Issue by iushankin** [swagger-api/swagger-core#1004]
Wrong location of the 'default' and the 'enum' nodes for the status parameter of the findPetsByStatus method. According to the spec it should be located inside to the 'items' node.
Spec: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameterObject
Sample from http://petstore.swagger.io/v2/swagger.json:
```
   "parameters":[
      {
         "name":"status",
         "in":"query",
         "description":"Status values that need to be considered for filter",
         "required":false,
         "type":"array",
         "items":{
            "type":"string"
         },
         "collectionFormat":"multi",
         "default":"available",
         "enum":[
            "available",
            "pending",
            "sold"
         ]
      }
   ]
```

**Comment by webron** [comment]
Fixed in develop_2.0.
