### ISSUE TITLE
Question: What is the correct format for listing multiple protocols?

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-core#1005]
Currently, the `@ApiOperation#protocols` parameter accepts a string.  How are multiple protocols represented? Is it `protocols = "http,https"` ?

**Comment by iushankin** [comment]
Yes, it should work on the develop_2.0 branch
You can look at https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java#L191-L201

**Comment by iushankin** [comment]
This issue is related to #1005
