### ISSUE TITLE
Acceptable packages not recursive anymore (version 1.5.1-M2)

### ISSUE THREAD

**Issue by gedl** [swagger-api/swagger-core#1011]
When configuring the resource package in the BeanConfig, for scanning, sub-packages are not scanned anymore.

Furthermore, requesting /swagger.json throws a NPE.

Context:
BeanConfig config = new BeanConfig();
config.setTitle(serviceName);
config.setResourcePackage("a.b.c");

(what I am trying to do is to setup swagger to generate a specs file for all classes annotated with Api.class below package a.b.c and all its sub-packages)

Expected (as per previous versions, for example 1.5.2-M1):  class a.b.c.Clazz is found by the scanner
Reality: class a.b.c.Clazz is not found by the scanner

More info:
The class is actually found in BeanConfig.java, line 194 but then filtered out in line 197.

I believe the NPE is another problem (or maybe not even a problem depending on an empty spec being a valid spec or not), but here's the stacktrace:
https://gist.github.com/gedl/7904b77055f0aac54620

**Comment by ctoestreich** [comment]
:+1:

**Comment by fehguy** [comment]
confirmed bug, also, empty package specifier does not scan _all_ packages, per #1098
