### ISSUE TITLE
Request Body Field Displays by Default

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-core#1013]
On both my GETS and POSTs the Body Request field displays and I don't need it. How do I get rid of it? Here is a sample:

```java
@POST
@Path("/geolocation")
@Produces({"application/xml"})
@Consumes({"application/x-www-form-urlencoded"})
@ApiOperation(value = "Lookup user geolocation", notes = "No Parameters", response = Geolocation.class)
@ApiImplicitParams(value = {
@ApiImplicitParam(name = "type", value = "geo lookup type", required = true, dataType = "String", paramType = "form"),
})
@ApiResponses(value = {
@ApiResponse(code = 400, message = "Invalid IP detected"),
@ApiResponse(code = 404, message = "Geolocation not found")
})
public Geolocation getGeo(MultivaluedMap values){
return getGeoProcess(values, false);
```

Thanks,

johnh

**Comment by fehguy** [comment]
what version of swagger-core?  In 1.5.x it shouldn't render them.

**Comment by jharter** [comment]
You can close this now. The offending APIs have been removed and that eliminated the appearance of the Body field. Never figured out what was causing it. I am running a current version of the core.

**Comment by jharter** [comment]
Hi.

Apparently there was a parent pom.xml, and the version of jax-rs (in apache cfx) is 2.2.3.

Does that help?

Thanks.

**Comment by webron** [comment]
@jharter- did you mean to comment on #1059 instead?

**Comment by jharter** [comment]
Yes, Sorry. Will add it to 1059.

**Comment by webron** [comment]
Does this mean we can close this issue again?

**Comment by jharter** [comment]
yes
