### ISSUE TITLE
Support of FormDataParam in Jersey 2

### ISSUE THREAD

**Issue by GuiSim** [swagger-api/swagger-core#1015]
I am unable to get swagger-jersey2-jaxrs to detect parameters of type @FormDataParam as a file param.

My dependency:
```
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.5.3-M1</version>
        </dependency>
```
My resource:
```
    @PUT
    @Path("{thing}")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @ApiOperation("Register thing")
    public Response putThing(@PathParam("thing") String thingId,
                             @ApiParam @FormDataParam("f") InputStream stream) 
```
I would have expected to see the @FormDataParam annotation mentioned SwaggerJersey2Jaxrs.java (https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/SwaggerJersey2Jaxrs.java)

It seems that this was once supported, back when @FormDataParam was part of com.sun.jersey.multipart. However it is now defined in org.glassfish.jersey.media.multipart.

Is this a regression?

**Comment by webron** [comment]
To an extent. It's supported in swagger-jersey-jaxrs.

@fehguy - Shouldn't https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/pom.xml#L74 point at swagger-jersey-jaxrs instead?

**Comment by GuiSim** [comment]
I don't think swagger-jersey-jaxrs supports org.glassfish.jersey.media.multipart.FormDataParam

If anyone else has the same issue, here's my workaround:

```

import java.lang.annotation.Annotation;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import org.glassfish.jersey.media.multipart.FormDataParam;

import com.wordnik.swagger.jaxrs.ext.AbstractSwaggerExtension;
import com.wordnik.swagger.jaxrs.ext.SwaggerExtension;
import com.wordnik.swagger.models.parameters.FormParameter;
import com.wordnik.swagger.models.parameters.Parameter;

public class FormDataParamSwaggerExtension extends AbstractSwaggerExtension implements SwaggerExtension
{
    @Override
    public List<Parameter> extractParameters(Annotation[] annotations,
                                             Class<?> cls,
                                             boolean isArray,
                                             Set<Class<?>> classesToSkip,
                                             Iterator<SwaggerExtension> chain)
    {
        List<Parameter> output = new ArrayList<>();

        if (this.shouldIgnoreClass(cls))
            return new ArrayList<>();

        for (Annotation annotation : annotations) {
            if (annotation instanceof FormDataParam) {
                FormDataParam fd = (FormDataParam) annotation;
                if (java.io.InputStream.class.equals(cls)) {
                    Parameter param = new FormParameter().type("file").name(fd.value());
                    output.add(param);
                    return output;
                }
            }
        }
        if (chain.hasNext()) {
            return chain.next().extractParameters(annotations, cls, isArray, classesToSkip, chain);
        }
        return null;
    }
}
```

And then somewhere before you create your BeanConfig, call 
```
        SwaggerExtensions.getExtensions().add(0, new FormDataParamSwaggerExtension());
```

**Comment by webron** [comment]
Right, forgot they changed the package signature, so it is indeed missing.

Also, that's not a workaround, that's a solution :)

**Comment by GuiSim** [comment]
I'd rather not have to use my own solution ;) but yeah, it works for the time being.

**Comment by webron** [comment]
It's like one step before submitting a PR to add it to https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/SwaggerJersey2Jaxrs.java (in the develop_2.0 branch of course) ;)

**Comment by GuiSim** [comment]
I wasn't sure if that's where it belonged.

I'll submit a pull request for this, thanks for the help @webron

**Comment by webron** [comment]
Fixed in develop_2.0. Thanks for the PR!

**Comment by GuiSim** [comment]
@webron for my information, when is the next released scheduled for?

**Comment by webron** [comment]
We hope to make a point release in the next few days.
