### ISSUE TITLE
Enums in BeanParam as PathParam or QueryParam 1.5.1-M2

### ISSUE THREAD

**Issue by swarupe04** [swagger-api/swagger-core#1019]
In 1.5.1-M2, enum parameters in BeanParam as PathParam or QueryParam are not showing the drop down list on the swagger ui. Looking at the swagger.json, I don't see the enum values listed which seems to be issue on core side.

As a workaround, I've been using the @ApiParam with allowableValues.

Sample: field in BeanParam object:

```java
 @ApiParam(required = true, value = "type of summary report",
            allowableValues = "summary,summary-jp,summary-uk",
            defaultValue = "summary")
    @PathParam("report_type")
    @DefaultValue("summary")
    @JsonProperty("report_type")
    private ReportType reportType = ReportType.REP_AOP_CORE_METRICS;
```

**Comment by kungfoo** [comment]
I;ve noticed this too but figured it was supposed to be this way.

**Comment by kungfoo** [comment]
I think this is a bug in the UI because it seems the spec returned is correct. In the sample I just created, the enum `Action` is returned as:

```json
"Pet" : {
      "properties" : {
        "kind" : {
          "type" : "string",
          "enum" : [ "DOG", "CAT", "UNKNOWN" ]
        },
      }
```
