### ISSUE TITLE
Support for Subresource Locators

### ISSUE THREAD

**Issue by dekmetzi** [swagger-api/swagger-core#102]
Swagger does not currently support Subresource locators, as per jax-rs 1.1: 

http://jsr311.java.net/nonav/releases/1.1/spec/spec3.html#x3-310003.4.1

I propose a new annotation to handle the definition of a sub resource, similar to how resources are currently defined. 

``` java
@Api(value = "/some-resource", description = "Info about some resource")
public class SomeResource {

    @Path("/{resourceId}/some-sub-resource")
    @ApiResource(value = "/{resourceId}/some-sub-resource" resourceClass="com.foo.SomeSubResource")
    public SomeSubResource getSubResource(@PathParam("resourceId") String resourceId) {
        return new SomeSubResource(resourceId)
    }
}
```

The current ApiReader (com.wordnik.swagger.core.ApiReader.scala:213) disregards any method which does not define an ApiOperation (as it should), and as a result does not show any information about sub resources. 

I use sub resources for a variety of things, generally providing a sort of filter on a main resource. Lets say you have a customer resource, and an order resource 

GET /customers 
GET /customers/{customerId}
GET /orders 
GET /orders/{orderId}

A sub resource locator is then used to return a customer resource which only relates to those customers attached to a particular order, like such : 

GET /orders/{orderId}/customers 

Which then provides access to the customer resource methods, like: 

GET /orders/{orderId}/customers/{customerId}

This is incredibly useful and I've used this to simplify our jax-rs implemention fairly significantly. 

Keen to hear thoughts on how this would / should work, and will spend some time on a potential implementation this am. 

Cheers

Mike

**Comment by jmarreroc** [comment]
Hello! 

I'm trying to adjust my resources hierarchy (who describes a tree morphology) as related on Subresource locators support for jax-rs 1.1 (as [mdekmetzian](https://github.com/mdekmetzian) mentioned) :
http://jsr311.java.net/nonav/releases/1.1/spec/spec3.html#x3-310003.4.1

So, i have a Resource:
```javascript

@Path("resource")
@Produces("application/json")
@Api(value="resource")
public class Resource {
        
	@GET
	@ApiOperation( ... )
	public Resource get() {
		return this;
	}

	@Path("/{subresource}")
	public SubResource get(@PathParam("subresource") String subresource) {		
		return new SubResource(subresource);		
	}
}
```
And a set of subresources describing a tree form (as showns this simple example), with no '@Path' class annotation defined as mentioned in http://jsr311.java.net/nonav/releases/1.1/spec/spec3.html#x3-310003.4.1 subresource specification (in the WidgetResource definition):
```javascript
@Produces("application/json")
//@Api <-- tried but doesn't work
public class SubResource {
        
	@GET
	@ApiOperation( ... ) //???
	public SubResource get() {
		return this;
	}

	@Path("/items")
	public OtherResource items() {		
		return new OtherResource(subresource);		
	}
}
```
I read all posts and see the examples attached but... finally i can say that i didn't understand how to document my resource hierarchy with swagger, (or if it's now supported) and nobody talks at this respect. All I see in the example provided (https://github.com/mdekmetzian/subresource_example) is that both resources '/pet' and '/owner' have their own @Path definition, so both are considered as resorurces who hang from root '/' and that isn't my scenario. So if I annotate all my resource classes whith @Path, i loose the resource exploration support dinamically provided by Jax-rs. What i'm doing wrong?! I just type directly in the browser the URIS and can navigate perfectly all resources hierarchy but cannot provide correctly the documentation to swagger.

Thank you for your time!

**Comment by jmarreroc** [comment]
Also tried to include the @ApiOperation as mentioned [fehguy](https://github.com/fehguy) over the subresource construction method but finally I get in the UI : "SwaggerOperation " + nickname + " is missing method"

```javascript

@Path("resource")
@Produces("application/json")
@Api(value="resource")
public class Resource {
        
	@GET
	@ApiOperation( ... )
	public Resource get() {
		return this;
	}

	@ApiOperation( ... )
	@Path("/{subresource}")
	public SubResource get(@PathParam("subresource") String subresource) {		
		return new SubResource(subresource);		
	}
}
```
```javascript
@Produces("application/json")
@Api(value="subresource") // tried but doesn't work
public class SubResource {
        
	@GET
	@ApiOperation( ... ) //???
	public SubResource get() {
		return this;
	}

	@Path("/items")
	public OtherResource items(...) {		
		return new OtherResource(...);		
	}
}
```
I'm using Swagger 2.11 : (bundle version 1.3.10)
