### ISSUE TITLE
Add getOperations() method to Path model class that returns a Map<String, Operation>

### ISSUE THREAD

**Issue by Helmsdown** [swagger-api/swagger-core#1022]
Currently the Path model POJO allows you get access to it's operations in two ways:

1. Get a List<Operations>
2. Call a named function like getPost() and getDelete().

Both of these are useful, but sometimes when you are iterating over the operations for a Path you want all defined operations AND their http method. 

Can we get a function that looks like this:

```java
public Map<String, Operation> getOperations() {
    //if operation is defined put it in the map keyed by its http method name
}
```

**Comment by lugaru1234** [comment]
I would suggest to add enum for http methods and use it as a key instead of strings.
`public Map<HttpMethod, Operation> getOperations()`
What do you think?

**Comment by webron** [comment]
@Helmsdown - Any input regarding @lugaru1234's suggestion?

**Comment by Helmsdown** [comment]
@webron I think it makes perfect sense. I ended up including a proposed change into pull request #1271.

#TwoBirdsOneStone :-)
