### ISSUE TITLE
JAX-RS Rest Model not discovered on different Jar

### ISSUE THREAD

**Issue by fenoloco** [swagger-api/swagger-core#1026]
Hello
I have all the model classes on a different project, then I use it as a dependency of the project that expose the services.

The problem is that Swagger don't get the information about model classes, and the $ref are not been resolved.

I can test whatever you need to identify the problem, I also can help to solve it if someone guides me.

More info:

To add Swagger to my project I did

```java

    public JaxRsActivator() {
        super();
        //Swagger documentation generator.
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion(BuildInfoProperties.INSTANCE.getStringProperty(EBuildInfoProperties.VERSION));
        beanConfig.setBasePath(RESOURCE_BASE_URL_SWAGGER);
        beanConfig.setTitle(BuildInfoProperties.INSTANCE.getStringProperty(EBuildInfoProperties.GROUP_ID));
        beanConfig.setResourcePackage(RESOURCE_PACKAGE);
        beanConfig.setScan(true);
    }

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiListingResource.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.class);      
        return resources;
    }

```

An example of the raw json output.

```json
{  
   "apiVersion":"1.1-SNAPSHOT",
   "swaggerVersion":"1.2",
   "basePath":"/xxxxx/rest",
   "resourcePath":"/applicationinfo",
   "apis":[  
      {  
         "path":"/applicationinfo/xxx",
         "operations":[  
            {  
               "method":"GET",
               "summary":"Show application info(xxx)",
               "notes":"Show application info(xxxx)",
               "items":{  
                  "$ref":"com.XXXX.XXX.rest.models.ApplicationInfoXXX"
               },
               "nickname":"showInfoXXX",
               "produces":[  
                  "application/json"
               ],
               "parameters":[  

               ]
            }
         ]
      }
   ]
}

```

**Comment by webron** [comment]
Is this a new integration or an old project?

**Comment by fenoloco** [comment]
An old one, I realized that the model were not working just after moving the models to the other Jar.
I'm not hundred percent sure if this is or not the problem. Can I turn debug mode or something like that to get more information?

**Comment by webron** [comment]
Moving it to a different jar shouldn't be a problem unless it's loaded by a different classloader (like in an OSGi environment and such). Which version of swagger-core do you use?

**Comment by fenoloco** [comment]
I'm using

**Comment by webron** [comment]
It's `provided`? :)

Can you try upgrading to 1.3.12? I don't think it would help, but worth a shot.

**Comment by fenoloco** [comment]
Yes,I use provided dependency because I added it to my custom JBoss module.
I Already tried with version 1.3.12 and removing the provided attribute and the same happens.

**Comment by webron** [comment]
Perhaps @fehguy would have an idea, but this may take a while to investigate. As an alternative, I'd recommend migrating to the 1.5 version which has quite a few enhancements and would be easier for us to provide support.

**Comment by fenoloco** [comment]
Ok, I will try to update, is there a guide like this one :https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-RESTEasy-2.X-Project-Setup#hooking-up-swagger-core-in-your-application 
For the 1.5 version?

**Comment by webron** [comment]
Yup. The link is in the wiki's sidebar.

**Comment by fehguy** [comment]
Being in a separate jar should be no problem at all, and most deployments do this.  Please try 1.5.x and report back--you can reopen this issue if it continues.
