### ISSUE TITLE
"access" param handling for model properties

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-core#1027]
using swagger-core-1.5.1-M2.

I am trying to filter parameters/properties based on the access param.

`@ApiParam`/`@ApiImplicitParam` and swagger-models `Parameter` work just fine. There, both sides support the property and it can be mapped (e.g. in swagger-jaxrs `ParameterProcessor`).

However, `@ApiModelProperty`s access flag/param is not mapped to swagger-models `Property`. `AbstractProperty`/`Property` are lacking a corresponding access property, I think?

Not having the access param available in swagger-models `Property` makes it hard, if not impossible, to filter model properties based on the access param with a `SwaggerSpecFilter`. At least I did not find a clean way.

related: https://github.com/swagger-api/swagger-core/issues/996

thanks, zyro

**Comment by fehguy** [comment]
yes, there should be some private value to map these too in the properties.

**Comment by fehguy** [comment]
This has been added back.
