### ISSUE TITLE
@Api description ignored in 1.5.1-M2

### ISSUE THREAD

**Issue by m-radzikowski** [swagger-api/swagger-core#1028]
REST resource with annotation:
```java
@Api(value = "/sample", description = "my sample resource")
```
is converted to json:
```
"tags": [
{
"name": "sample"
}
]
```
but based on petstore demo should be:
```
"tags": [
{
"name": "sample",
"description": "my sample resource"
}
]
```
Currently description is completly gone.

I'm using swagger-jaxrs 1.5.1-M2.

**Comment by webron** [comment]
@m-radzikowski - due to a change in the spec, we had to rework how tags are generated. While `/sample` would indeed be converted to `sample` as a tag, it will not take its description due to possible conflicts.

The way to configure the description now is different. You can take a look at the sample to see how it works - https://github.com/swagger-api/swagger-core/blob/master/samples/java-jaxrs/src/main/java/com/wordnik/swagger/sample/Bootstrap.java#L35-L45.

**Comment by m-radzikowski** [comment]
It's sad it cannot be done by annotations any more. Isn't it doubling the "tags" - in `@API` annotations and by `Swagger#tag()`?

So isn't now `description` in `@Api` redundant? Or leaved only by backwards compatibility reasons? At lease javadoc should be updated.

**Comment by webron** [comment]
When moving from 1.3 to 1.5, we left the annotations as-is besides adding a few new fields. This was done to be as backwards-compatible as possible.

To keep a similar behavior to previous versions, the `@Api#value()` is converted to a tag, but we indeed added `@Api#tags()`. This allows you to set multiple tags, and will override the `value()` if one is provided.

The `description` is indeed redundant now. Still WIP, but I'm updating the javadocs as you can see here - https://github.com/webron/swagger-core/blob/annotation_docs/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/Api.java#L60-L66.

**Comment by m-radzikowski** [comment]
Ok, that's the way we will probably do this. Thank you for the detailed info.

**Comment by okigan** [comment]
this seems utterly weird, why description of API endpoint is now forced to be placed bootstrap code, is not the whole point of @Api annotation (or any other annotation) to place relevant information near the class/interface?

**Comment by webron** [comment]
@okigan - that's a fair question. The change is derived from the difference in Swagger 2.0's grouping method. With it, `@Api` can now affect multiple groups (aka, tags). In fact, there could be multiple `@Api`s with the same tags, and conflicting descriptions.

One way would be to apply the description to all the tags, allow the last-read to override whatever was found before, but that may very well lead to confusion when hitting unexpected results.

**Comment by okigan** [comment]
Looks like swagger already creates a default tag by @Api annotation, then consider following behavior: if only default tag is present show the default description, if custom tag is provided do not show default tag/description and display according to custom tag with tag's description.


Much easier transition path, and no ambiguity which description is applied. 

	default_tagA defaultA_description
	   method A1
	   method A2

	default_tagB defaultB_description
	   method B1
	   method B2

	custom_tag custom_description
	   method A1
	   method A2
	   method B1
	   method B2

**Comment by webron** [comment]
There's still ambiguity. You can still have two `@Api`s with the same `value()` and a different `description()`. Also, documenting the suggested behavior in a way people would be able to follow is quite challenging.
