### ISSUE TITLE
Petstore sample's updatePetWithForm does not change pet data

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-core#1029]
As in the [java-jaxrs sample source code](https://github.com/swagger-api/swagger-core/blob/master/samples/java-jaxrs/src/main/java/com/wordnik/swagger/sample/resource/PetResource.java#L135), the changes are not saved actually, is it expected?

(migrated from swagger-api/swagger-codegen#656)

**Comment by wing328** [comment]
@fehguy FYI. I tested http://petstore.swagger.io/#!/pet/updatePetWithForm but still the update failed. My guess is that the server has not picked up the latest change.

**Comment by webron** [comment]
@wing328 - it's not deployed yet. will be deployed with an official release.

**Comment by wing328** [comment]
@webron ok understood.

**Comment by fehguy** [comment]
@wing328 I've pushed the updated petstore now, it should work.  There was a delay, we merged a PR and caused a spec problem.

**Comment by wing328** [comment]
@fehguy I performed a test via http://petstore.swagger.io/#!/pet/updatePetWithForm and confirm updatePetWithForm now works fine :smile:
