### ISSUE TITLE
Swagger UI Hangs with a response type of application/javascript

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-core#1030]
HI,

I have asked this question before and I believe this was a "resolved question" in the past. I use the Swagger UI to send a GET and there is a http 200 response, as can be seen in the browser's debugger. The response seems to be a json file, although that content type returns http 406. So, I do get the correct response, but the Swagger UI hangs. The thinking dots keep running and the response section of the page never displays.

Sorry, I have asked this question before and researched it copiously and can't figure it out. Does this sound like something about the endpoint I am hitting or is it Swagger.  How can I debug this?

Thanks,

John Harter

**Comment by webron** [comment]
The question is a bit unclear.

First, while not impossible, returning `application/javascript` is a bit odd.

Second, what kind of GET operation? On one hand you say there's a 200 response, and on the other you say it's 406, so which is it? What exactly do you experience?

**Comment by jharter** [comment]
Sorry for the confusion. I am unaccustomed to seeing application/javascript responses, too. I am just documenting this API. Unless I specify a Response type of application/javascript, I receive a 406. But, if I annotate @Produces({ "application/javascript"}), I get a http 200 response with the response body displaying in the Browser debugger. But, Swagger hangs. I don't see the response in the Swagger UI. I am really not saying that the bug is in Swagger. I just want to eliminate Swagger as the culprit. 

Is that clearer?

Thanks,

johnh

**Comment by webron** [comment]
Do you actually return a javascript file from the operation? Or is it JSON? Or something else?

**Comment by jharter** [comment]
Here is a sample return, from the Network tab of IE's Developer Tool. It looks like json to me, but only application/javascript will give me any return at all. 

{"ver":"2020","device":"011","brand":"001","xmlns":"http://abc.go.com/vp2/ws/xmlns","affiliates":{"affiliate":[{"name":"KGTV","dma":"SAN DIEGO","rank":"28","id":"KGTV","event":{"url":{"callback":"event_flat_file","value":"http://liveeventsfeed.abc.go.com/kgtv.json"},"refresh":{"unit":"second","value":"300"}}}],"count":1},"server":{"time":"Mon, 4 May 2015 15:54:52 +0000"}}

**Comment by webron** [comment]
Really? Have you tried setting it to `application/json`?

**Comment by jharter** [comment]
I am sure that was the case, but if I just used application/json and there is a correct response in the Response Body in IE's debugger tool. However, the response header says 406. It must be that if Swagger sees a 406 in the header, it means no content and so don't display. I think the API must be sending back the wrong header. Does that sound right to you?

**Comment by fehguy** [comment]
I believe this is a swagger-ui question, and probably more specific to the framework you're using.  Can you please open a ticket in swagger-ui, or in the respective framework that you're using?
