### ISSUE TITLE
swagger-jersey2-jaxrs dependencies

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1031]
If you're looking to use Resteasy 3.x with the jersey2 artifact, you'll get a dependency error for `FormDataParam`.  See https://github.com/swagger-api/swagger-core/pull/1010

**Comment by tomtit** [comment]
@fehguy could you clarify what should be done here? The project's [pom.xml](https://github.com/swagger-api/swagger-core/blob/377ad2c8e5ffe0ab7903bd4d8d46ac5acda2e98b/modules/swagger-jersey2-jaxrs/pom.xml#L84-93) contains two dependencies from Jersey2. Do we need to remove them?

**Comment by webron** [comment]
Keep in mind the module name is.... jersey2.

**Comment by webron** [comment]
Perhaps we should resolve it as part of #1244.
