### ISSUE TITLE
@ResponseHeader#responseContainer() should not support "Map"

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#1032]
Only "List" and "Set" are valid.

**Comment by fehguy** [comment]
Not sure if you want to do that.  See examples:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/test/scala/resources/ResourceWithApiResponseResponseContainer.java#L13-L21

We support "Map" where keys are strings.

**Comment by webron** [comment]
For `@ApiOperation` and `@ApiResponse` it's okay to have map. This is specifically for `@ResponseHeader`.

**Comment by fehguy** [comment]
@lugaru1234 if @webron wants to remove support of `map` in the response headers (to support the spec properly), please remove it from the sample `ResourceWithApiResponseResponseContainer.java`.  @webron merge when you're happy with this.
