### ISSUE TITLE
@ExternalDocs currently not in use

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#1035]
There's an `ExternalDocs` class and an `@ExternalDocs` annotation. The former is used, the latter isn't. 

We need to consider if/how to use the `@ExternalDocs`, based on the spec.

**Comment by fehguy** [comment]
can you send a PR to remove the old one?

**Comment by webron** [comment]
Should we remove it or keep it until we implement the usage for it? There's no way, for example, to set `externalDocs` for an operation, as far as I can tell.

**Comment by webron** [comment]
This is now used by `@Tag`, no reason to remove.
