### ISSUE TITLE
Annotation on Interface Java

### ISSUE THREAD

**Issue by carlosthe19916** [swagger-api/swagger-core#1037]
The annotation on interfaces classes is no available, it exposes a exception when i do it

**Comment by webron** [comment]
What kind of exception? It should work fine and is used by some of our samples.

**Comment by carlosthe19916** [comment]
i'm sorry. I've resolve the problem. That was not a problem of Swagger, My code was bad. Thank you very much.

**Comment by webron** [comment]
Thanks for the update.
