### ISSUE TITLE
swagger plugin for play 2.1 includes EntityBeanIntercept member

### ISSUE THREAD

**Issue by timidri** [swagger-api/swagger-core#104]
I am using EBean as the ORM framework for my model. Swagger documents the following in all entities:

``` json
"_ebean_intercept":{"type":"EntityBeanIntercept"}
```

I have created a plugin which is loaded before swagger plugin like so:

``` java
package plugins;

import play.*;

public class BootstrapPlugin extends Plugin {

    public BootstrapPlugin(Application application) {
        // nothing; the constructor should be there
    }

    @Override
    public void onStart() {
        Logger.info("BootstrapPlugin.onStart");
        com.wordnik.swagger.core.util.TypeUtil.addAllowablePackage("models");
    }
}
```

The code is executed but does not prevent _ebean_intercept from being included.

**Comment by lcamilo15** [comment]
This is answered in the following http://stackoverflow.com/questions/24458575/swagger-is-showing-ebean-intercept-with-everymodel-in-my-play-application

Add the following class as explained in the following link [swagger ebean][1]

    import com.wordnik.swagger.converter.SwaggerSchemaConverter

    class IgnoreConverter extends SwaggerSchemaConverter{
      override def skippedClasses: Set[String] = Set("com.avaje.ebean.bean.EntityBeanIntercept")
      override def ignoredClasses: Set[String] = Set("com.avaje.ebean.bean.EntityBeanIntercept")
      override def ignoredPackages: Set[String] = Set("com.avaje.ebean")
    }

You can now follow the step explained by Luis, 

    public class Global  extends GlobalSettings {
        @Override
        public void beforeStart(Application app) {
            Logger.info("Registering custom converter");
            ModelConverters.addConverter(new IgnoreConverter(), true);
        }
    }


  [1]: http://www.tagwith.com/question_1242768_swagger-is-showing-ebean-intercept-with-everymodel-in-my-play-application
