### ISSUE TITLE
uploading file to petstore server is not working

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-core#1043]
I tried uploading a JPG file here: http://petstore.swagger.io/#!/pet/uploadFile
and got this error:

``` json
{
  "code": 400,
  "type": "unknown",
  "message": "org.jvnet.mimepull.MIMEParsingException: java.io.IOException: No space left on device"
}
```

**Comment by webron** [comment]
Heh, that's awesome. Not really related to swagger-core, but I get why you opened it here.

@olensmar - can you look at that please?

**Comment by webron** [comment]
All better now, thanks for reporting.

**Comment by xhh** [comment]
verified it, thanks
