### ISSUE TITLE
XMLGregorianCalendar and Calendar model creation

### ISSUE THREAD

**Issue by mayuranchalia** [swagger-api/swagger-core#1047]
Hi I am using Swagger Core 2.10,
In my restservice I am returning XMLGregorianCalendar  and Calendar.
But the model which is getting created is not what is expected.

Model of XMLGregorianCalendar  
```js
{
  "valid": false,
  "month": 0,
  "year": 0,
  "day": 0,
  "second": 0,
  "minute": 0,
  "eon": {
    "bitCount": 0,
    "bitLength": 0,
    "lowestSetBit": 0,
    "signum": 0
  },
  "hour": 0,
  "timezone": 0,
  "eonAndYear": {
    "bitCount": 0,
    "bitLength": 0,
    "lowestSetBit": 0,
    "signum": 0
  },
  "fractionalSecond": 0,
  "millisecond": 0,
  "xMLSchemaType": {
    "namespaceURI": "",
    "localPart": "",
    "prefix": ""
  }
}
```

Model of Calendar
```js
{
  "lenient": false,
  "firstDayOfWeek": 0,
  "minimalDaysInFirstWeek": 0,
  "time": "",
  "timeZone": {
    "displayName": "",
    "iD": "",
    "dSTSavings": 0,
    "rawOffset": 0
  },
  "weekYear": 0,
  "weekDateSupported": false,
  "timeInMillis": 0,
  "weeksInWeekYear": 0
}
```
I want only a String for the both java returntype. Please help me in this regards.

**Comment by fehguy** [comment]
can you please upgrade to 1.5.x?

**Comment by mayuranchalia** [comment]
Hi fehguy,
Is this not supported in previous version?.

**Comment by fehguy** [comment]
It is, but as we're not developing that version anymore, it would be wise to upgrade if possible.  If not, we can hunt it down but you may be stuck patching a fork rather than getting it from the mainline.

**Comment by mayuranchalia** [comment]
It would be nice of you fehguy, If you help me with this version I have added lots of code already...
I am trying this patch,,, but it didn't help ...
  TypeConverter typeConverter = new TypeConverter();
	    typeConverter.add("Calendar", "string");
	    typeConverter.add("XMLGregorianCalendar", "string");
	    ModelConverters.addConverter(typeConverter, true);
Am I making any mistake?

**Comment by mayuranchalia** [comment]
There is one class called JodaDateTimeConverter,
In this I saw there is already a mapping  Map("datetime" -> "Date", "localdatetime" -> "Date", "xmlgregoriancalendar" -> "Date")..but I am not sure why this is not getting picked.

**Comment by fehguy** [comment]
sure thing.  Can you share your pojo?

**Comment by mayuranchalia** [comment]
Its not a Pojo ...I am directly returning Calendar and XMLGregorianCalendar from a Jersey service which is calling some other api .
I will share a snippet.

 @GET
 @Produces({"application/json"})
 public javax.xml.datatype.XMLGregorianCalendar helloWorld() throws SoapserviceTestCfcCFCInvocationException_Exception    { 
        	LOG.info("Executing operation helloWorld");
            javax.xml.datatype.XMLGregorianCalendar _helloWorld__return = port.helloWorld();
            return _helloWorld__return ;
}

**Comment by mayuranchalia** [comment]
Other Snippet

 @Path("getTime")
    @ApiOperation("getTime")
    @GET
    @Produces({"application/json"})
    public java.util.Calendar getTime() throws java.rmi.RemoteException, {
    LOG.info("Executing operation getTime");
        return binding.getTime();
    }

**Comment by fehguy** [comment]
ok that's very different then.  the model converters will not be triggered in this scenario.

I suggest adding the response class to the `@ApiOperation`, that should solve it:

```
@Path("getTime")
@ApiOperation(value = "getTime", response = String.class)
@GET
@Produces({"application/json"})
public java.util.Calendar getTime() throws java.rmi.RemoteException, {
  LOG.info("Executing operation getTime");
  return binding.getTime();
}
```

Right now, you're relying on the parsing of the method return type to specify the response model.  You can do this in the annotation instead.

**Comment by mayuranchalia** [comment]
Thanks a lot fehguy for the solution, I will try this out.
But one more question, 
In a scenario where calendar or XMLGregorianCalendar is passed as body or formparam. In that case will the model be generated by ModelConvertor.

@Path("setTime")
@POST
@Consumes({"application/json"})
public void setTime(java.util.Calendar cal) throws java.rmi.RemoteException, {
  LOG.info("Executing operation setTime");
  binding.setTime(cal);
}

**Comment by fehguy** [comment]
I believe that's correct.

**Comment by mayuranchalia** [comment]
Hi Fehguy,
I wrote a sample service..
	@POST
	@Produces({"application/json"})
	@Consumes({"application/json"})
    @ApiOperation(value = "setDate",response = String.class)
    @Path("time")
	public Calendar setDate(Calendar date){
		System.out.println(date.get(Calendar.DAY_OF_WEEK));
		return date;
	}

and registered 
            TypeConverter typeConverter = new TypeConverter();
	    typeConverter.add("Calendar", "string");
	    //typeConverter.add("XMLGregorianCalendar", "string");
	    ModelConverters.addConverter(typeConverter, true);

But in Swagger model for the body is 
{
  "lenient": false,
  "firstDayOfWeek": 0,
  "minimalDaysInFirstWeek": 0,
  "time": "",
  "timeZone": {
    "displayName": "",
    "iD": "",
    "rawOffset": 0,
    "dSTSavings": 0
  },
  "timeInMillis": 0,
  "weekYear": 0,
  "weeksInWeekYear": 0,
  "weekDateSupported": false
}

**Comment by mayuranchalia** [comment]
I did also follow below link and solution posted bu you.
https://groups.google.com/forum/#!topic/swagger-swaggersocket/nutGhUbOwvM

**Comment by mayuranchalia** [comment]
Hi,
Was going through the swagger doc -- Api Listing doc 
parameters: [
{
name: "body",
required: false,
type: "XMLGregorianCalendar",
paramType: "body",
allowMultiple: false
}
]
this is referring to the model generated in api doc.
While analyzing the source code of swagger core got the code which is doing this
SwaggerSerializers.scala file has method toJsonSchema which is creating parameter level doc.
If we add something similar to "date" will resolve the issue 
 case "Date"       => (name -> "string")  ~ ("format" -> "date-time")
I am not sure though this is the right way of doing ,just sharing my thoughts.

**Comment by webron** [comment]
@mayuranchalia - was this resolved for you?

**Comment by mayuranchalia** [comment]
Yes it was working for me.

**Comment by webron** [comment]
Great, thanks for the update.

**Comment by mayuranchalia** [comment]
Will you ubdate in main line/branch or I need to fork.

**Comment by webron** [comment]
We're not developing the 1.3 branch anymore. If you upgrade to 1.5 and experience the same issue, we'd be happy to resolve it there.
