### ISSUE TITLE
Swagger2 breaks manual positioning

### ISSUE THREAD

**Issue by chadjaros** [swagger-api/swagger-core#1050]
I'd like to preserve manual positioning after the transition from 1.2 to 2. The Swagger object seems to allow [order preserving insertion](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/com/wordnik/swagger/models/Swagger.java#L80-L83) for paths, but then it does a [manual sort](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/com/wordnik/swagger/models/Swagger.java#L189-L201) prior to retrieval. 

I feel like the position parameter on the @ApiOperation and @Api annotation either needs to be deprecated, or the Swagger 2.0 model should honor that ordering. I'd prefer the latter.

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiOperation.java#L94-L98 
https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/Api.java#L76-L82

They *are* deprecated. Unfortunately the javadocs were not updated in previous released but will be in the next one.

**Comment by chadjaros** [comment]
Cool. Thanks for the info.

**Comment by exstan** [comment]
So how should I order my methods when the 'position' attribute is deprecated? 
As I'm using swagger-maven-plugin and I want a custom order of my methods in the swagger.json.

**Comment by webron** [comment]
It's not an array, so you can't really guarantee order.

**Comment by exstan** [comment]
So, it was possible with the 'position' attribute but now it is not :) perfect

**Comment by webron** [comment]
In Swagger 1.2 operations were an array. In 2.0 they're not.

**Comment by chadjaros** [comment]
Sets and maps both have order-preserving implementations in Java. See [LinkedHashSet](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashSet.html) and [LinkedHashMap](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashMap.html)

**Comment by webron** [comment]
They do. In JSON parsing, order of object's properties order is not guaranteed.

**Comment by exstan** [comment]
But if the 'position' attribute is also exported in the JSON, the order will be guaranteed again.

**Comment by webron** [comment]
Yes, but there's no `position` attribute in the spec, so it can't be exported.

**Comment by webron** [comment]
Closing for now, Please reopen as needed.

**Comment by sschwell** [comment]
+1 on this as a important loss of functionality.
If the spec needs to change, then so be it. Its really important to be able to specify an order for Resources and Operations.

**Comment by webron** [comment]
@sschwell - the spec is not going to change any time soon to support it. The order of resources *can* be controlled based on the order of the tags as you declare them. The order of the operations can't.

**Comment by Chinna-SHS** [comment]
Is there any option to set the order of API methods @ApiOperation annotation?

**Comment by webron** [comment]
As said, not during generation. You can potentially change the order in display if the tools allow it.

**Comment by kniveshhhh** [comment]
Sounds like some BS, removed important feature with no care to fix.
