### ISSUE TITLE
Invalid YAML in petstore

### ISSUE THREAD

**Issue by earth2marsh** [swagger-api/swagger-core#1052]
It looks like line breaks in longer descriptions aren't being handled properly. In order to use multiple lines in YAML, you must use a `|` and then indent the subsequently consistently. The petstore example uses JS-style `\` to continue across lines!

See: petstore.swagger.io/v2/swagger.yaml

**Comment by webron** [comment]
I think the problem is slightly different. The description itself is set in the code as a single line (no line breaks) and as such should be represented as either a single line or a folded block (`>`). 

Not really sure why Jackson/SnakeYaml output it that way.

**Comment by earth2marsh** [comment]
Me either, but the end result is broken YAML, which isn't a great thing in the standard app's spec. If I had any Java skill, I'd dig in to see for myself! :)

**Comment by webron** [comment]
So far I haven't been able to find any configuration or reason for it to happen. I'll try catching Jackon's author online later.

**Comment by webron** [comment]
@earth2marsh - I'm definitely not an expert in YAML, but it seems to be a valid format, at least in YAML 1.1/1.2. Take a look at Example 7.5 under http://www.yaml.org/spec/1.2/spec.html#id2787109.

While some tools seem to be unable to process it properly, the following tools suggest it is just fine:
http://www.yamllint.com/
http://www.json2yaml.com/
http://nodeca.github.io/js-yaml/

So... I don't think there's much we need to do here.

**Comment by earth2marsh** [comment]
@webron interesting… my guess is that a swagger-tools dependency has a flaw then, so I will chase it down there. Thanks for the excellent sleuthing!

**Comment by webron** [comment]
@earth2marsh - I'm just glad it gave me the opportunity to dive into YAML a bit more. I should probably go through its whole spec so learn how we can benefit more of it.
