### ISSUE TITLE
Getting HTTP 405 "HTTP method GET is not supported by this URL" Error

### ISSUE THREAD

**Issue by dalegaspi** [swagger-api/swagger-core#1053]
I have this app using embedded Jetty with Jersey 2.x and Swagger 1.5.x and I'm trying to map swagger to /api-docs ... when i run the app the /api-docs path seems to be getting mapped correctly (in the logs) but when i load http://localhost:1339/api-docs i get an HTTP 405 with "HTTP method GET is not supported by this URL" error.  

I also tried creating servlet (programmatically, not using web.xml) as described [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#using-swaggers-beanconfig) but I'm getting the same HTTP 405 error...

I'm sure I'm close but I'm missing something...below is my code snippet...any help is appreciated!

```java

public static final String BASE_URI = "http://localhost:1339/";

...

final ResourceConfig rc = new ResourceConfig().packages(
  "com.siriusxm.sequencer.services.jersey",
  "com.wordnik.swagger.jaxrs.listing")
    .register(JacksonFeature.class) // enable Jackson
    .register(ResponseCorsFilter.class) // enable CORS
    .register(ApiListingResource.class)
    .register(SwaggerSerializers.class);


// use Jetty
ServletContextHandler context = 
  new ServletContextHandler(ServletContextHandler.SESSIONS);

context.setContextPath("/");
Server jettyServer = new Server(1339);
jettyServer.setHandler(context);
ServletHolder jerseyServlet = new ServletHolder(new 
  org.glassfish.jersey.servlet.ServletContainer(rc));

jerseyServlet.setInitOrder(0);

context.addServlet(jerseyServlet, "/*");

// swagger
ServletHolder swagger = new ServletHolder(new JerseyJaxrsConfig());
swagger.setName("Jersey2Config");
swagger.setInitParameter("swagger.api.basepath", BASE_URI);
swagger.setInitParameter("api.version", "1.0.0");
swagger.setInitOrder(2);

context.addServlet(swagger, "/api-docs");

jettyServer.start();
```

**Comment by webron** [comment]
Well, the reason is simple. JerseyJaxrsConfig doesn't really serve anything and it shouldn't be mapped to any URL.

The Swagger definition would be exposed by the `ApiListingResource` and will be available at `swagger.json` directly under your context root.

**Comment by dalegaspi** [comment]
Wow...OK so it was working all along...I was just using the wrong URL to test...going to `http://localhost:1339/swagger.json` does output the swagger JSON as expected (I should read the manual more carefully lol) ...so i suppose the line

```java
context.addServlet(swagger, "/api-docs");
```

the second parameter is ignored?  for now I just replaced it with `""` and it still works.

thanks!

**Comment by webron** [comment]
I wouldn't use the JerseyJaxrsConfig at all, but rather the BeanConfig (as described in the tutorial). It allows for better definitions and you can set it right after the ResourceConfig initialization.

Glad it worked out though, I'll close the issue now.
