### ISSUE TITLE
Implement additional format: byte

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-core#1055]
Currently, byte (format) is treated as "string" and there's a TODO in StringProperty to implement additional formats.

https://github.com/swagger-api/swagger-core/blob/ee0b6398e98254ed4625ba47e173253466e8fe2b/modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/StringProperty.java#L88

If no concern from anyone, I'll update the code to support byte as a property.

**Comment by webron** [comment]
@wing328 - not really sure what's missing.. `byte` is treated as a valid format there.

**Comment by wing328** [comment]
@webron If you look at the folder containing the StringProperty.java, it has "DateTimeProperty.java" but no "ByteProperty.java" (both have type set to `string`)

https://github.com/swagger-api/swagger-core/blob/ee0b6398e98254ed4625ba47e173253466e8fe2b/modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/StringProperty.java#L90

The above line checks `type` and `format` to determine if a property is a `string`. I think the TODO refers to implementing `byte` as a property itself (instead of treating `byte` as `string`)

In swagger-codegen, a response (type: string, format: byte) will always map to `string`. Ideally one can map it manually to something else (e.g. byte[]) using typeMapping.

**Comment by webron** [comment]
Fair enough. However, as mentioned in one of the codegen comments, `byte` format is intended to be a Base64 encoded string, hence the string type. I'm not sure that would solve the issue that led you here.

**Comment by wing328** [comment]
I would recommend updating the comment section on [Swagger Spec 2.0 Data Types](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) to mention about Base64-encoded string for `byte`

**Comment by webron** [comment]
@wing328 - can you open an issue about it on swagger-spec? I want to make sure that this was indeed the intent.

**Comment by webron** [comment]
@wing328 - sure. That issue was originally opened for 1.2, but it applies to 2.0 just as well.

**Comment by fehguy** [comment]
I'm closing this out as it's a spec issue, and has a corresponding issue in that repo.

**Comment by wing328** [comment]
Totally agree.
