### ISSUE TITLE
XMLGregorianCalendar and Calendar model creation in Body

### ISSUE THREAD

**Issue by mayuranchalia** [swagger-api/swagger-core#1056]
Hi ,

I tried using TypeConverter  to convert the model of Calendar class, but its not working some how.
My use case is that I am passing Calendar as input to my service as body.
	
	@POST
	@Produces({"application/json"})
	@Consumes({"application/json"})
        @ApiOperation(value = "setDate",response = String.class)
        @Path("time")
	public Calendar setDate(Calendar date){
		System.out.println(date);
		return date;
	}
	
       Below is the type converter used.
      TypeConverter typeConverter = new TypeConverter();
      typeConverter.add(Calendar.class.getName(), String.class.getName());
      ModelConverters.addConverter(typeConverter, true);

      Still the model looks like this...
      {
  "lenient": false,
  "firstDayOfWeek": 0,
  "minimalDaysInFirstWeek": 0,
  "time": "",
  "timeZone": {
    "displayName": "",
    "iD": "",
    "rawOffset": 0,
    "dSTSavings": 0
  },
  "timeInMillis": 0,
  "weeksInWeekYear": 0,
  "weekDateSupported": false,
  "weekYear": 0
}

I expect my model to be just a string. As it happens for date class. 
Please help me in this regard....

**Comment by webron** [comment]
Please refrain from opening new tickets on an issue you're already opened and is still open.
