### ISSUE TITLE
POST Body Field Not working

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-core#1059]
The following code does not let the user enter name-value pairs into the request body. The request is sent without any name-value pairs. Also, when you click on the Model Schema, the model does not display in the body field.

I am working with java code.

```java
@POST
    @Path("/video/geolocation")
    @Produces({"application/json"})
    @Consumes("application/x-www-form-urlencoded")
    @ApiOperation(value = "Lookup Basic Geolocation", notes = "", response = Geolocation.class)
    @ApiImplicitParams(value = {
            @ApiImplicitParam(name = "body", value = "Enter name-value pairs.", required = true, dataType = "string", paramType = "body")
            })
    @ApiResponses(value = {
            @ApiResponse(code = 400, message = "Invalid IP detected"),
            @ApiResponse(code = 404, message = "Geolocation not found")
    })
    public Geolocation getGeoSOLR(MultivaluedMap<String,String> values){
        return getGeoProcess(values, true);
```
Is there an example I can view?

Thanks,

johnh

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by jharter** [comment]
<dependency>
			<groupId>com.wordnik</groupId>
			<artifactId>swagger-jaxrs_2.10</artifactId>
		</dependency>

**Comment by jharter** [comment]
swagger-jaxrs_2.10-3.10.jar in Maven /lib.

**Comment by webron** [comment]
Swagger-core 1.3.X (which is the one you use) doesn't support Maps.

I see you assume this is to take form parameters and not really a body parameter. In that case, you'd have to describe each form parameter separately. If you require arbitrary input, you cannot do that with swagger-core 1.3.X. In 1.5 you can, if this is a body parameter, but not if it is form parameters.

**Comment by jharter** [comment]
Perhaps it is the version of the core I am using, but ... Let's say I just provide form parameters instead of arbitrary input. I tried doing that but the body field continues to show up in the UI. It is not needed with specific form params. It is confusing. How can I get rid of it?

**Comment by webron** [comment]
I assume it shows up because your method accepts a parameter which is automatically treated as a body parameter. You'd have to filter it out.

**Comment by jharter** [comment]
Hmmm. Is there some swagger annotation that allows me to filter it out? or must I do the filtering in the API java?

**Comment by webron** [comment]
No annotation. You need to use a SwaggerSpecFilter for it.

**Comment by webron** [comment]
@jharter - My bad, completely forgot. You can set `@ApiParam(hidden=true)` on it and it should hide it.

**Comment by jharter** [comment]
Seems that "@ApiParam(hidden=true) is not supported in my version of the core. I suspect. IntelliJ marks it red, can 't resolve method. As you pointed out, I am using Swagger-core 1.3.X. I need to update, I guess, but don't know what to update to. I am using plain vanilla Java and using Maven for building. I put the Swagger jar file in the Maven lib directory and register it. Plus change my pom.xml file to point to the Swagger file. Could you point me to the correct Swagger download?

Thanks. johnh

**Comment by webron** [comment]
Well, the problem is I don't know exactly which version you use as the version is not specified in the dependency snippet. If you don't want to upgrade to 1.5, then the latest version of 1.3 is 1.3.12.

**Comment by jharter** [comment]
I see no reason not to upgrade to 1.5, unless you see an issue. Where can I download it?

**Comment by webron** [comment]
Maven :) Which jax-rs implementation do you use?

**Comment by jharter** [comment]
Hmmm. I don't know where to find that information. I am awaiting an email from the folks who set up the project. I know: JAVA_VERSION="1.8.0_40". Maven Version = 3.2.5. That's probably not helpful. Sorry, but I need to await an email from a colleague.

**Comment by webron** [comment]
I just want to refer you to the correct guide, that should help you integrate 1.5 easily with your code. So let's see what the response to the JAX-RS implementation would be.

**Comment by jharter** [comment]
I think the answer is 2.4.1, but here is the Maven dependency:tree response.

org.codehaus.jackson:jackson-jaxrs:jar:1.9.11:compile
com.wordnik:swagger-jaxrs_2.10:jar:1.3.12:compile
com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.4.1:compile
com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.4.1:compile

Thanks.

**Comment by jharter** [comment]
I am really hoping that a new version of the core with @ApiParam(hidden=true) works because now the body field is displaying in my GET methods. It used to only display in the POST.

**Comment by webron** [comment]
None of these are related to the JAX-RS implementation. It'd be difficult to offer more support without that information.

**Comment by jharter** [comment]
Hi.

Apparently there was a parent pom.xml, and the version of jax-rs (in apache cfx) is 2.2.3.

Does that help?

Thanks.

**Comment by webron** [comment]
Yes, it most certainly does. Unfortunately, we don't have a guide ready for CXF integration.

However, we released today a general migration guide from 1.3 to 1.5 that may be enough (and it would be great to get some feedback). 

The guide is located here - https://github.com/swagger-api/swagger-core/wiki/1.3--1.5-Migration.

For the guide, you should know that the dependency name you need to use is `swagger-jaxrs` and the version is `1.5.1-M2`. 

Can you give it a shot?

**Comment by jharter** [comment]
Yes, I will give it a shot. Thanks so much.

**Comment by jharter** [comment]
Is there a jar file for this? Where would I find it? I need to add it to Maven.

**Comment by webron** [comment]
That's the dependency. Right now you probably have:
```xml
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jaxrs_2.10</artifactId>
        </dependency>
```

So you need to replace that with:
```xml
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jaxrs</artifactId>
            <version>1.5.1-M2</version>
        </dependency>
```

**Comment by jharter** [comment]
Thanks for your help. My first attempts at using this were unsuccessful. Unfortunately I need to push my project with this one bug due to time constraints. I will work with this new version in a week or so and give you any feedback I have. Thanks for all  your help.
