### ISSUE TITLE
Support for case classes without @BeanProperty

### ISSUE THREAD

**Issue by jsw** [swagger-api/swagger-core#1060]
I generate swagger specs via the [swagger-maven-plugin] (https://github.com/kongchen/swagger-maven-plugin). The plugin recently switched to using a newer version of swagger, and now my case class fields don't get documented unless they are annotated with @BeanProperty. The plugin author suggested this might be because the older version of swagger-core's reader was in Scala, and now it's in Java. Is there a better workaround for documenting case classes? I'd rather not be required to add @BeanProperty annotations everywhere, which also consequently modify the public interface.

**Comment by fehguy** [comment]
The plugin will need to add the swagger-scala-module for this.

**Comment by fehguy** [comment]
I'm closing this out as it's an implementation issue in the swagger-maven-plugin
