### ISSUE TITLE
public/swagger/swagger-ui.js does not do a null check

### ISSUE THREAD

**Issue by kktiwa** [swagger-api/swagger-core#1064]
There should be null check for 'definitions' without which the Swagger UI fails to load.

Line number 3468
Existing Code:

if (definitions[ref]) {
return new Model(ref, definitions[ref], this.models);

Code changed as fix:

if (definitions && definitions[ref]) {
return new Model(ref, definitions[ref], this.models, this.parent.modelPropertyMacro);

**Comment by webron** [comment]
That belongs in swagger-ui, not here.
