### ISSUE TITLE
Move the samples to a separate repository

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#1066]
That would make the release of swagger-core easier, and allow us to make changes to the samples independently of swagger-core versions.

**Comment by ctoestreich** [comment]
+1, the grails sample is lacking docs on how to access the api-docs and it isn't setup correctly as far as I can tell since there is NO docs that give the actual end point to hit for the json spec and /api-docs/swagger.json and /swagger.json both don't seem to work.

**Comment by fehguy** [comment]
@webron let's just do this then.  What do you want the samples repo to be called?

I see a number of languages & frameworks need samples.  The swagger-core samples were really swagger java samples.  This may be the right time to make a samples repo for all samples, not separated by language or framework.  Post your feedback and we'll get it done.

**Comment by webron** [comment]
We can just call it `swagger-samples` then. If this is going to be a multi-language repository, the only catch is possibly the build process. However, that's probably not a big deal.

**Comment by webron** [comment]
We'll also need to update the links in the wiki to the samples.

**Comment by fehguy** [comment]
Do you want me to move them?

https://github.com/swagger-api/swagger-samples

**Comment by webron** [comment]
Yeah, but it's better to move the samples in develop_2.0. If we're going to have multiple language samples there, maybe split it to language directories.

**Comment by fehguy** [comment]
@webron please merge https://github.com/swagger-api/swagger-core/pull/1083 when docs, links, etc. are update do support this.

**Comment by webron** [comment]
This is done.
