### ISSUE TITLE
Inherited annotations not observed

### ISSUE THREAD

**Issue by okigan** [swagger-api/swagger-core#1072]
Same as issue  #400 (see for more context), but occurring in latest version 1.5m2: 

I'm using com.wordnik:swagger-jaxrs_2.10:1.3.1 and I'm observing that @Api... annotations in parent objects are not observed.

I would like to use @Api... annotations on both my Java interface as well as on an (abstract) base class to be observed when the API documentation for my actual resource class is generated.

**Comment by okigan** [comment]
Particularly painful as cannot define interfaces separately and reuse that with automatic client generation (ex. using https://github.com/Netflix/feign)

**Comment by webron** [comment]
Fixed in develop_2.0, using #1122.
