### ISSUE TITLE
deletePet is using PATCH

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-core#1084]
as in [Swagger UI](http://petstore.swagger.io/#!/pet/deletePet) and [source code](https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jaxrs/src/main/java/com/wordnik/swagger/sample/resource/PetResource.java#L95), is that expected?

the test case in Ruby petstore sample of the swagger-codegen project is using DELETE for deletePet, which fails with 405:

```
DELETE /v2/pet/10002 HTTP/1.1
Host: petstore.swagger.io

HTTP/1.1 405 Method Not Allowed
```

**Comment by fehguy** [comment]
no, I've just updated that.
