### ISSUE TITLE
Why do we need ApiParam.allowMultiple?

### ISSUE THREAD

**Issue by tomtit** [swagger-api/swagger-core#1086]
Let we have a resource:
```
@Api
@Path("/whatever")
public class Resource {

  @POST
  @Path("/test")
  public void test(@HeaderParam("input") @ApiParam(allowMultiple = true) String input) {
  }
}
```
Does it make sense to send `input` as a collection if JAX-RS has to treat it as a scalar to pass it into the method?

**Comment by fehguy** [comment]
it's for back-compatibility support only.

**Comment by tomtit** [comment]
Does it make sense to declare it as deprecated?

**Comment by tomtit** [comment]
What is the correct JSON for the mentioned resource? Do we still has to report that parameter as array?

**Comment by fehguy** [comment]
It should be a string array
