### ISSUE TITLE
@ApiOperation not detected on overridden method

### ISSUE THREAD

**Issue by okigan** [swagger-api/swagger-core#1091]
Re-openning https://github.com/swagger-api/swagger-core/pull/1074 as an issue. 

Effectively derived methods do not show up in swagger documentation, here is full example:
https://github.com/okigan/swagger-core/tree/base-resource-swagger/samples/java-jersey-jaxrs

the core of the issue: 

	@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
	public abstract class PetResourceBase {
	  @GET
	  @Path("/{petId}")
	  @ApiOperation(value = "Find pet by ID",
		notes = "Returns a single pet",
		response = Pet.class,
		authorizations = @Authorization(value = "api_key", type = "api_key")
	  )
	  @ApiResponses(value = { @ApiResponse(code = 400, message = "Invalid ID supplied"),
		@ApiResponse(code = 404, message = "Pet not found") })
	  public Response getPetById(
		  @ApiParam(value = "ID of pet to return") @PathParam("petId") Long petId)
		  throws NotFoundException {
		  ....
	  }
	}

	@Path("/pet")
	@Api(value = "/pet", authorizations = {
	  @Authorization(value = "petstore_auth", type = "oauth2",
	  scopes = {
		@AuthorizationScope(scope = "write:pets", description = "modify pets in your account"),
		@AuthorizationScope(scope = "read:pets", description = "read your pets")
	  })
	}, tags = "pet")
	public class PetResource extends PetResourceBase {
	  @Override
	  public Response getPetById(@ApiParam(value = "ID of pet to return") Long petId) throws NotFoundException {
		return super.getPetById(petId);
	  }
	} 

note the GET method on /pet does not show up:
![be8d89e6-fc0b-11e4-8bfd-319ad45392ab](https://cloud.githubusercontent.com/assets/478302/7752829/934dbcd6-ff96-11e4-8c93-d3bec5943d07.png)

**Comment by okigan** [comment]
hmm, odd, github did not notify about above changes -- but awesome to see this, i'll check it out shortly

**Comment by webron** [comment]
@okigan - any update? We're very close to making a release so any input would be useful.

**Comment by okigan** [comment]
looks like samples got removed in develop_2.0 branch, so i'd need to
re-bootstrap my test

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-samples/tree/develop_2.0/java

**Comment by okigan** [comment]
So i went back to original fix commit that still has samples in same code base (https://github.com/swagger-api/swagger-core/commit/f9ce1e36f0886af5e847566013c7b137570025dc) and modified that, looks good: 

![screen shot 2015-06-05 at 4 01 29 pm](https://cloud.githubusercontent.com/assets/478302/8016750/8f8e3da2-0b9c-11e5-97dc-74ec8431d135.png)

**Comment by webron** [comment]
Okay, so we're good to close?

**Comment by okigan** [comment]
green light from me

**Comment by webron** [comment]
Great, thanks for verifying.
