### ISSUE TITLE
Swagger doesn't work with nested resources in different classes (Jersey)

### ISSUE THREAD

**Issue by santiagopoli** [swagger-api/swagger-core#1092]
Suppose I have these two classes:

```java
@Path("/conversations")
@Api("/conversations")
public class ConversationsResource {

      @POST
      @ApiOperation("Create conversation")
      public Conversation createConversation(){ ... }

}

@Path("/conversations/{conversationId}")
@Api("/conversations/{conversationId}")
public class ConversationResource {

      @GET
      @ApiOperation("Get conversation")
      public Conversation getConversation(){ ... }

}
```

Swagger doesn't detect that **/conversations/{conversationId}** is nested with **/conversations**
I've tried setting the BaseUrl with "/conversations" in ConversationResource but didn't work as well.

I know I can easily wrap all the methods from ConversationResource inside ConversationsResource but I don't like it (also it violates my company standards. We strictly use one class per path).

Is there a way to fix this?

Thanks!

**Comment by santiagopoli** [comment]
I think I managed to fix it using tags!

**Comment by webron** [comment]
Swagger-core will indeed use the value of the `@Api` to group the operations, and you can use tags to override it. An alternative would be to simply provide the `@Api` with the same value.
