### ISSUE TITLE
required is not honored for body param (not a path param)

### ISSUE THREAD

**Issue by hongxingli** [swagger-api/swagger-core#1093]
code snippet for jax-rs2.0

public void registerAccount(@Suspended final AsyncResponse asyncResponse,
            @ApiParam(value = "Account registration information", required = true) AccountRegistration accountRegistration) {

generated .json

parameters: [
{
  in: "body",
  name: "body",
  description: "Account registration information",
  required: false,
    schema: {
      $ref: "#/definitions/AccountRegistration"
    }
  }
],

**Comment by webron** [comment]
Which version of Swagger-core do you use?

**Comment by iushankin** [comment]
It was been fixed on the develop_2.0 (can you look at #971)
Also it was been merged to the 1.5.2-M2

**Comment by hongxingli** [comment]
Thanks, please close it, it's the same issue. But I tired 1.5.2-M2, it seems not merged, how can I confirm if the fix has been merged or not?

**Comment by hongxingli** [comment]
I'm was on 1.5.1-M1
