### ISSUE TITLE
NPE exception on /swagger.json service

### ISSUE THREAD

**Issue by fenoloco** [swagger-api/swagger-core#1099]
If RESOURCE_PACKAGE list not match any of the package classes discovered.  A NPE is fired when I request the resource on.../swagger.json

**Comment by fehguy** [comment]
Which scanner are you using?  web.xml, BeanConfig, etc?

**Comment by fenoloco** [comment]
I'm using BeanConfig.

2015-05-23 17:45 GMT-03:00 Tony Tam <notifications@github.com>:

**Comment by fehguy** [comment]
OK please try develop_2.0, which is available on 1.5.3-M2-SNAPSHOT via sonatype oss.  I've added a unit test and this is not giving an error

**Comment by webron** [comment]
@fenoloco - have you had a chance to test it?

**Comment by fenoloco** [comment]
Not yet, I will try it asap. Fell free to close the ticket and I will open
if doesn't work on that version.
