### ISSUE TITLE
POST with response entity status code

### ISSUE THREAD

**Issue by thegreatdao** [swagger-api/swagger-core#1100]
Hi,

I'm using swagger-jersey-jaxrs_2.10 vresion 1.3.12. My POST endpoints have response entities. Swagger ui display response class along with status 200, Is there a way to change status code to 201?

Thanks.

**Comment by webron** [comment]
@thegreatdao - the easiest to resolve it would be to upgrade to 1.5. There's a migration guide in the wiki, and also a full integration guide if you need it.

**Comment by webron** [comment]
@thegreatdao - have you had a chance to look into it?

**Comment by thegreatdao** [comment]
Hi, w are staying with 1.3 for now will migrate 1.5 later.

You can close the issue.

Thanks,
