### ISSUE TITLE
Is Play2 still supported by Swagger ?

### ISSUE THREAD

**Issue by pycloux** [swagger-api/swagger-core#1101]
The https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-play does not exists anymore.
It is not clear what is to be done to activate swagger with play.

Please can you advise ?

**Comment by pycloux** [comment]
For info read in https://github.com/swagger-api/swagger-core/wiki/1.3--1.5-Migration :
Since swagger-core 1.5 contains implementation for JAX-RS only, this guide covers the migration for that alone. Play integration would be handled at a later date. 

Is there any news about this ?

**Comment by webron** [comment]
#918

**Comment by webron** [comment]
Please follow that issue.

**Comment by pycloux** [comment]
Thanks webron.
Just a last comment : the issue seems to be focused on scala while play is also "Java" (which actually we are using currently our project - using the existing annotations).
Just in case if you need some hands for the Play2 java support, we can help.

**Comment by webron** [comment]
@pycloux - that may be great. Please comment on that issue and @fehguy may reach out. I believe the support should be language-agnostic (within what's relevant).
