### ISSUE TITLE
@ApiModel - the given "value" is ignored in the generated json and html

### ISSUE THREAD

**Issue by mhshams** [swagger-api/swagger-core#1104]
According to the JavaDoc, one should be able to rename the model name: 
```Java
public @interface ApiModel {
  /**
   * Provide an alternative name for the model.
   * <p>
   * By default, the class name is used.
   */
  String value() default "";
```
But the given value is ignored in the generated json file.

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by mhshams** [comment]
I tried: 
- 1.3.7 
- 1.3.12
- 1.5.2-M2.  

All of them have the same issue.

**Comment by webron** [comment]
Okay, this should have been fixed with #964 but if you say you experience it, then we need to check it again.

Can you share your model code and a sample operation that uses it that would exhibit the problem?

**Comment by mhshams** [comment]
apparently my mistake again. in 1.5.2-M2 is NOT reproducible anymore. I will close the ticket. 
sorry for any inconvenience caused.

**Comment by webron** [comment]
No worries, thanks for the update.
