### ISSUE TITLE
Automatically hide subresources

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#1106]
Right now, subresources are scanned and added to the `swagger.json` as if they're hosted at the root of the application. The workaround for now is to add `@Api#hidden() = true`. The better behavior would be to scan only add it as a resource to the containing resource and not treat it as a first-class resource.

**Comment by fehguy** [comment]
This could be tricky to support in the tree, when scanning to find a parent reference.  Every resource *may* live on it's own, so if you don't want it to be picked up, I don't see how you can avoid marking it as `hidden` at the `@Api` annotation.

**Comment by webron** [comment]
Why would it need the `@Api` annotation in the first place if it's not live on its own?

**Comment by Helmsdown** [comment]
@webron The subresource would want an @Api annotation so you can tag it and have it show up in swagger-ui in its own expander.

**Comment by webron** [comment]
@Helmsdown - the amount of dust I needed to clean in order to remember what this was even about is insane, and I can't still can see clearly. This came from a specific use case, and perhaps that's the key. I believe this relates to sub-resources that are not annotated with `@Path` at the class level.

**Comment by Helmsdown** [comment]
I currently have that use case

On Thursday, January 21, 2016, Ron <notifications@github.com> wrote:

> @Helmsdown <https://github.com/Helmsdown> - the amount of dust I needed
> to clean in order to remember what this was even about is insane, and I
> can't still can see clearly. This came from a specific use case, and
> perhaps that's the key. I believe this relates to sub-resources that are
> not annotated with @Path at the class level.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1106#issuecomment-173776156>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Helmsdown** [comment]
We have a discussion going in #1614 about how to solve this (if at all).

**Comment by webron** [comment]
Yeah, I actually get aaaaaaaaaall notifications ;)

**Comment by Helmsdown** [comment]
oh

**Comment by Helmsdown** [comment]
really

**Comment by Helmsdown** [comment]
:-)

**Comment by frantuma** [comment]
fixed in #1646
