### ISSUE TITLE
Ability to have duplicated *code* in @ApiResponse 

### ISSUE THREAD

**Issue by mhshams** [swagger-api/swagger-core#1108]
Sometimes a http status code, specially the errors, may have more than one cause.  
It would be nice if one can use the same status code with different messages: 
```Java
@ApiResponses(value = {
     @ApiResponse(code = 400, message = "The first cause of bad request"),
     @ApiResponse(code = 400, message = "Another cause of bad request")
})
```
currently, code is used as key in the generated json object, thus it's not possible to use one key with different messages.

**Comment by webron** [comment]
It's not possible because the spec doesn't allow it. We can't implement things that are not supported by the spec.
