### ISSUE TITLE
java.lang.VerifyError on Weblogic 12c with Swagger 1.5.1 M2

### ISSUE THREAD

**Issue by BigSocial** [swagger-api/swagger-core#1116]
Loading a web app that includes swagger-jersey2-jaxrs 1.5.1-M2 causes the error `java.lang.VerifyError: Cannot inherit from final class` in Weblogic 12c. This is due to a dependency on Guava 15 which has a problem with Weblogic documented here https://code.google.com/p/guava-libraries/issues/detail?id=1433. Specifically including Guava 18 in the app's pom.xml resolves the issue. This is more an FYI than an issue.

**Comment by webron** [comment]
@fehguy - any reason not to upgrade?

**Comment by fehguy** [comment]
not that i know of.  we can upgrade it.
