### ISSUE TITLE
Where is api-docs json

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-core#1117]
Hi, 

I can't seem to  hit the api-docs endpoint. I can't see my error. Is there a way to discover where the endpoint actually is? There are no errors but 404, can't find it.

Thanks,

johnh

**Comment by webron** [comment]
You'd need to provide more information. Which version of swagger-core do you use? How did you configure it?

**Comment by jharter** [comment]
I am using core 1.3 (swagger-jaxrs_2.10).

beans.xml looks like this:
<property name="resourcePackage" value="com.disney.datg.videoplatforms.ws.entitlement"/>
<property name="basePath" value="http://localhost:8080/api-entitlement"/>

java file looks like this:
package com.disney.datg.videoplatforms.ws.entitlement.v2016.services;
@Path("/entitlement")
@Api(value = "/v2016/services/entitlement", description = "Entitlement Lookup WebService")

Thanks. johnh

**Comment by jharter** [comment]
Let me repeat that something is missing.

I am using core 1.3 (swagger-jaxrs_2.10).

beans.xml looks like this:
*property name="resourcePackage" value="com.disney.datg.videoplatforms.ws.entitlement"/*
*property name="basePath" value="http://localhost:8080/api-entitlement"/*
java file looks like this:
package com.disney.datg.videoplatforms.ws.entitlement.v2016.services;
@Path("/entitlement")
@Api(value = "/v2016/services/entitlement", description = "Entitlement Lookup WebService")

I replace the delimiters with *
Thanks. johnh

**Comment by webron** [comment]
@jharter - thanks for the additional details.

Still missing a few details. Which JAX-RS implementation do you use?
Did you configure the JAX-RS resources provided by swagger-core in your application? If so, how?
Is this a new integration? If so, will you be able to use the 1.5 branch instead?

**Comment by jharter** [comment]
Ron,

Thanks for helping.

jax-rs (in apache cfx) is 2.2.3.

I could move to the 1.5 branch, but the guide suggests that it is not all that easy for cxf. 

Swagger is configured in beans.xml:
*jaxrs:providers*
      *ref bean="jsonpProvider" /*
      *ref bean="resourceWriter" /*
      *ref bean="apiWriter" /*
      *ref bean="jsonpProviderV2" /*
*/jaxrs:providers*

*bean id="swaggerResourceJSON" class="com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON" /*

*bean id="swaggerConfig" class="com.wordnik.swagger.jaxrs.config.BeanConfig"*
    *property name="resourcePackage" value="com.disney.datg.videoplatforms.ws.entitlement"/*
    *property name="version" value="1.0.0"/*
    *property name="basePath" value="http://localhost:8080/api-entitlement"/*
    *property name="title" value="ABC EIA Entitlement APP"/*
    *property name="description" value="Collection of API Web Services built by ABC and The Walt Disney Company technologies for WATCH ABC, Partners of Disney or ABC and related Video On Demand Presentation Integrations. These APIs are used by applications integrating with the Service."/*
    *property name="contact" value="EIA"/*
    *property name="license" value="Apache 2.0 License"/*
    *property name="licenseUrl" value="http://www.apache.org/licenses/LICENSE-2.0.html"/*
    *property name="scan" value="true"/*
  */bean*

Hope this helps. thanks

**Comment by webron** [comment]
The only problem with CXF is that we don't have a guide for it ;) I should get around to it, so much to do, so little time. We do have a sample with cxf with 1.5 - https://github.com/swagger-api/swagger-core/tree/master/samples/java-jaxrs-cxf. The migration guide in the wiki may also help. I would *strongly* recommend moving to 1.5 as that's the maintained version. 

The `/api-docs` (for 1.3) or `/swagger.json` (for 1.5) would be simply available at the context root of your application, as we pretty much expose a JAX-RS resource like any of your own. So if your context root url is `http://localhost:8080/myapp`, simply attach the resource as mentioned in this paragraph at the end and it should be done (of course, assuming you hooked our resource properly, that being the ApiListingResource).

**Comment by jharter** [comment]
Thanks for all your help Ron. I believe that I have my resource hooked up properly. (Tried every permutation). This is the second set of APIs I am working for the same application. Each are in different projects. I got the first one working and based the second one's configuration on the first one. But, it clearly does not work. I guess it is time to upgrade to Swagger-core 1.5. I am hoping it works with the version of CFX I am using (2.2.3.). Thanks. johnh
