### ISSUE TITLE
Example values for a list type in Java-jaxrs not working

### ISSUE THREAD

**Issue by mahmed0715** [swagger-api/swagger-core#1118]
Hello,
We are using swagger-core, jaxrs. everything works good, @example for string works fine , issues seems to be for defining example of a model property that is a list type.

```java
 @ApiModelProperty(required=true, value="Limit to spend without confirmation", example="1000000") 
private Long limit;
```
produces 
```js
{
example : "100000"
}
```
Thats fine as this is a string.

But for
```java
@ApiModelProperty(required=true, value = "xpubs should be account keys", example = "['1','2']")
private List<String> xpubs;
```
procuces
```js
{
example : "['1','2']"
}
```
Thats a mess. 

This can be fixed as overloading the example method I guess.
Waiting this to be fixed.

**Comment by webron** [comment]
@mahmed0715 - not really sure how we can resolve this one easily. If you have any concrete suggestions, feel free to provide them.

**Comment by webron** [comment]
Closing this one in favor of the more generic feature request - https://github.com/swagger-api/swagger-core/issues/1118.

**Comment by webron** [comment]
That was meant to be https://github.com/swagger-api/swagger-core/issues/1318.

**Comment by dklotz** [comment]
@webron So #1318 is closed, but examples still don't work for array/list types right? Should this be re-opened or should I open a new issue?

**Comment by webron** [comment]
I believe #1699 should address that.

**Comment by vinayshankar** [comment]
@webron , @mahmed0715 What exactly is the fix and what do I need to do to use the fix? 
Declaring the example value as `example = "[\"1\",\"2\"]")` does not help. The back slash is present in the documentation. Should I be declaring the value as example = "['1','2']") ? Will this display as 
`
{
example : [ "1" , "2" ]
}
`
