### ISSUE TITLE
Confusing Request Response

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-core#1123]
Hi,

I have one annotated java source file and when I try to load the api-docs the "fetching" message displays and yet the browser dev tool tells me that 3 requests were made: 1 to api-doc, 1 to api-docs/ and 1 to api-docs/2016/services. All return 200s but the final one has this for response content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><HTML><HEAD><LINK type="text/css" rel="stylesheet" href="/api-entitlement/api-docs/2016/services/?stylesheet=1"><meta http-equiv=content-type content="text/html; charset=UTF-8"><title>CXF - Service list</title></head><body><span class="heading">Available SOAP services:</span><br/><table cellpadding="1" cellspacing="1" border="1" width="100%"></table><br/><br/><span class="heading">Available RESTful services:</span><br/><table cellpadding="1" cellspacing="1" border="1" width="100%"><tr><td><span class="field">Endpoint address:</span> <span class="value">http://localhost:8080/api-entitlement/</span><br/><span class="field">WADL :</span> <a href="http://localhost:8080/api-entitlement/?_wadl&_type=xml">http://localhost:8080/api-entitlement/?_wadl&type=xml</a></td></tr><tr><td><span class="field">Endpoint address:</span> <span class="value">http://localhost:8080/api-entitlement/2020</span><br/><span class="field">WADL :</span> <a href="http://localhost:8080/api-entitlement/2020?_wadl&_type=xml">http://localhost:8080/api-entitlement/2020?_wadl&type=xml</a></td></tr></table></body></html>

Seems to be a generic web service response and not my annotated code.

Is my source not annotated correctly?

Thanks,

John Harter

**Comment by webron** [comment]
@jharter - not really sure how you got to this point. How did you configure swagger-core in the first place? I'd highly recommend following the guides in the wiki for integration.

If you provide me with more details on your environment (such as the JAX-RS implementation), I can point you to the specific guide.

**Comment by jharter** [comment]
Thanks for your reply Ron. I was hoping that off the top of your head you had seen some similar behavior. We should probably close this issue until I have a better understanding of the problem and can ask intelligent questions, not waste your time. Thanks, johnh
