### ISSUE TITLE
Swagger 1.2 and 2.0

### ISSUE THREAD

**Issue by jharter** [swagger-api/swagger-core#1125]
I am confused about the documentation. When you say Swagger 1.2 and Swagger 2.0, are you talking about Swagger-Core?

Thanks,

johnh

**Comment by webron** [comment]
Hi,

For general support questions, please use our [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) in the future. Just makes it a bit easier for us.

As for the versioning - Swagger itself is the specification, not a specific library. Please check out http://swagger.io.

swagger-core is a library that exposes a Swagger specification. Now for the versions -

swagger-core 1.3 produces Swagger 1.2 specification.
swagger-core 1.5 produces Swagger 2.0 specification.

**Comment by jharter** [comment]
Thanks. Sorry about not using Google Group.

**Comment by webron** [comment]
No harm done, it's better to ask than not ask at all.
