### ISSUE TITLE
Xml object always outputs certain properties

### ISSUE THREAD

**Issue by jahlborn** [swagger-api/swagger-core#1132]
The Xml object always generates output for the "attribute" and "wrapped" properties, even when their value is set to "false" (which is the default).  while this isn't a bug, per se, it's just a lot of extra visual noise.  would be nice to not output properties if they just have their default value.

**Comment by webron** [comment]
@jahlborn - testing with 1.5.0 I don't see that behavior. Have you tried with that version? If so, can you share a class that reproduces it?

**Comment by webron** [comment]
@jahlborn - did you get a chance to look into it?

**Comment by fehguy** [comment]
This should be fixed in 1.5.1 and later releases.

**Comment by jahlborn** [comment]
Sorry for the delayed response.  we haven't been working with our swagger code recently, so have not had a chance to look into that.
