### ISSUE TITLE
Swagger object missing some features

### ISSUE THREAD

**Issue by jahlborn** [swagger-api/swagger-core#1133]
You can define common responses at the top-level of a swagger document (for reference in the various operations).  The Swagger object should support this.  Also, i believe the security section is currently missing.

**Comment by webron** [comment]
I assume you're looking for it as a general Swagger models support and not specific for JAX-RS generation?

**Comment by jahlborn** [comment]
yes, we generate our model info on the fly from internal product configuration.

**Comment by webron** [comment]
Fair enough.

**Comment by fehguy** [comment]
This was added in https://github.com/swagger-api/swagger-core/commit/5928abd2668448d29bf29ce6147d83ec1200eb59
