### ISSUE TITLE
No way to define nested complex models in schemas

### ISSUE THREAD

**Issue by jahlborn** [swagger-api/swagger-core#1135]
The schema models only seem to support simple properties.  there is no way to define properties which are in turn complex models (other than using a ref to another top-level model)..

**Comment by webron** [comment]
Need more info here.

**Comment by jahlborn** [comment]
When trying to define a model in a swagger document, you start with a Model, which has a map of Property's.  now, i want to define one of the properties in the Model to have complex content (i.e. nested properties).  there is no Property implementation which contains a map of Properties.  MapProperty seems like what you would want, but it only contains a single nested property.

**Comment by fehguy** [comment]
There is something called a RefProperty which supports this.  Please try that and reopen if needed.
