### ISSUE TITLE
API Performance Metrics

### ISSUE THREAD

**Issue by vishakMetric** [swagger-api/swagger-core#1140]
Hi Swagger Team,

     Is there any tool by Swagger or any possibilities to get the performance metrics for the each REST endpoint. An UI available for the same that can be shown.
Expecting something like this https://dev.twitter.com/overview/status . Please let me know if there is any such possibilities.

Regards
Vishak.V

**Comment by webron** [comment]
Since this is a general question and is not directly related to swagger-core, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) to ask it and you may get answers from other people from the community as well.
