### ISSUE TITLE
NPE in SpecFilter.filterDefinitions()

### ISSUE THREAD

**Issue by csuich2** [swagger-api/swagger-core#1141]
When attempting to upgrade to 1.5.0-M2, I found that some of our models were causing a NPE to be thrown in SpecFilter.filterDefinitions. The culprit models were those that have no properties added to the ModelImpl. A simple example of this is a model which has an int[][] as a field which in turn has its own ModelImpl created.

It appears that SpecFilter.filterDefinitions() either:
1. Has an assumed precondition that all models have a non-null property list
2. Simply fails to check for non-null before attempting to retrieve the property iterator.

Since the rest of the library works just fine with models that have no properties, I believe a non-null check is simply missing. I have a pull request incoming shortly that I believe addresses the issue.

**Comment by webron** [comment]
Fixed in develop_2.0.
