### ISSUE TITLE
The Api paths are becomes empty after couple of days of deployment

### ISSUE THREAD

**Issue by SrinivasMonocept** [swagger-api/swagger-core#1147]
We noticed that the API paths stored in the Swagger 5.x are being lost after couple of days. Our application is deployed on to the Azure on 443 port. We have four different deployments namely (dev, QA, Preview and Prod) and works fine for certian time(couple of days).All of a sudden, Without any change in the code/deployment/configuration, the issue of swagger not displaying the list of API's after a couple of days has been noticed on all the environments.

**Comment by webron** [comment]
@SrinivasMonocept - that's an issue for [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle). Please reopen the issue there.
