### ISSUE TITLE
Dropwizard 0.8.1, Swagger 1.5, instantiationError: com.wordnik.swagger.config.SwaggerConfig

### ISSUE THREAD

**Issue by chriskessel** [swagger-api/swagger-core#1148]
BeanConfig swaggerConfig = new BeanConfig();
        swaggerConfig.setVersion("2.0"); // This is the swagger version?
        swaggerConfig.setResourcePackage("com.kessel");
        swaggerConfig.setScan(true);
        swaggerConfig.setBasePath(".." + environment.getApplicationContext().getContextPath());

Results in this stack trace:

        Exception in thread "main" java.lang.InstantiationError: com.wordnik.swagger.config.SwaggerConfig
	at com.wordnik.swagger.config.ConfigFactory$.<init>(ConfigFactory.scala:7)
	at com.wordnik.swagger.config.ConfigFactory$.<clinit>(ConfigFactory.scala)
	at com.wordnik.swagger.jaxrs.config.BeanConfig.<init>(BeanConfig.scala:26)

I've got the following two dependencies in gradle. That should be sufficient, yes?

    compile group: "com.wordnik", name: "swagger-jersey-jaxrs_2.10", version: "1.3.12"
    compile group: "com.wordnik", name: "swagger-core", version: "1.5.3-M1"

**Comment by webron** [comment]
You're mixing swagger-core 1.3 and 1.5. If you have the swagger-jersey-jaxrs dependency, you don't need the swagger-core one.

We just released an official version of 1.5.0 which you should use instead. It requires a few more code changes but should be easy enough to follow.

**Comment by chriskessel** [comment]
How do I get 1.5 with jaxrs? I don't see a 1.5 available in maven central anywhere. We were using this (stolen from a gradle file I inherited). I was trying to move to the latest, but I'm not sure what that means as far as a gradle dependency.

    compile group: "com.wordnik", name: "swagger-jaxrs_2.9.1", version: "1.0.1"
    compile group: "com.wordnik", name: "swagger-core_2.9.1", version: "1.0.1"

**Comment by webron** [comment]
We've repackaged the project under io.swagger - http://search.maven.org/#artifactdetails|io.swagger|swagger-jersey-jaxrs|1.5.0|jar

**Comment by chriskessel** [comment]
Ah, ok. The repackaged bit got me. My eyes flew right over that change.

**Comment by olensmar** [comment]
Just checking @chriskessel - are you good to go? Can we close the issue?

**Comment by chriskessel** [comment]
Yea, sorry.
