### ISSUE TITLE
ApiImplicitParam dataType does produce a model schema, just a string name of the class

### ISSUE THREAD

**Issue by phillro** [swagger-api/swagger-core#1149]
I've annotated the ApiModel and set the data type to the class name:
https://gist.github.com/phillro/55dcda77906dab7ea04e

And the outputted type is:
"type":"UserData" rather then the case classes schema.

However if I modify the @ApiOperation response to be the same as the ImplicitParam dataType, the outputted "type" of the param is the schema...

**Comment by webron** [comment]
@phillro - which version of swagger-core do you use?

**Comment by phillro** [comment]
1.3.12

**Comment by webron** [comment]
@phillro - sorry for the delayed reply here. I'm not sure I follow the problem to the fullest. Can you share both use cases' code snippets and output (full output) so that the problem is clearer?

Keep in mind that if this is an issue with 1.3.12, we will not be able to provide a fix for it.

**Comment by webron** [comment]
@phillro - any update?

**Comment by fehguy** [comment]
Hi, please re-open if you're having an issue with 1.5.x.  As @webron said, you should consider updating to 1.5.x.
