### ISSUE TITLE
1.5.0 - problem with jaxrs Reader (implicit) body parameter handling

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-core#1150]
hi,
i am seeing the following:
when an `@ApiImplicitParam` is used with `paramType = "body"`, the jaxrs `Reader` parses the whole api class (i.e. `@Api` annotated resource) as a model and puts it into the schema. this causes highly unpredictable behavior. in my case, i get an NPE trying to filter the resulting swagger with a `SpecFilter`.

i think the offending call is here:
https://github.com/swagger-api/swagger-core/blob/v1.5.0/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L399
does it really make sense to supply `method.getDeclaringClass()` there or shouldnt that rather be sth. like `Class.forName(param.dataType())` (or similar, if dataType is a simple type and not a fqcn)?

the issue only occurs when using an implicit body param because then we arrive here:
https://github.com/swagger-api/swagger-core/blob/v1.5.0/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java#L119
if it is not a body param (i.e. an instance of `AbstractSerializableParameter`), the class/type is not used at all..

hope that makes some sense. thanks, zyro

**Comment by webron** [comment]
Fixed in develop_2.0.

**Comment by Syzygy24** [comment]
Is there a version we can use that has this fix? 1.5.1-SNAPSHOT maybe?

**Comment by webron** [comment]
Yeah, it should be in 1.5.1-SNAPSHOT, feel free to try it and let us know how it goes.

**Comment by Syzygy24** [comment]
I tried, but it's still giving me version 1.5.0. I attempted to just change the version in the dependency here. Am I misunderstanding how to change the version?
```
         <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-jersey-jaxrs</artifactId>
                <version>1.5.1-SNAPSHOT</version>
            </dependency>
```

**Comment by webron** [comment]
If you're still getting 1.5.0, you may have another dependency in it.
Also, make sure you have the sonatype repository defined for snapshots because snapshots are not available at maven central.

**Comment by Syzygy24** [comment]
I got it running on the latest version, but my swagger.json page is giving a 500 error now.
```
"javax.servlet.ServletException: java.lang.NoSuchMethodError: io.swagger.annotations.ApiParam.hidden()Z"
```
Looks like there's a trailing Z?

**Comment by webron** [comment]
@Syzygy24 - thanks for the feedback, much appreciated.
