### ISSUE TITLE
Jaxrs pathparam with regex generates incorrect swagger json

### ISSUE THREAD

**Issue by chriskessel** [swagger-api/swagger-core#1153]
For example, take this complicated regex which should result in a path like "/api/{itemId}".

    @Path("/{itemId: [0-9]{4}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{3}/[A-Za-z0-9]+}")

Instead, the json created ends up interpretting this as a long path:

    "/api/{itemId}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{2}/[0-9]{3}/[A-Za-z0-9]+}": { "get": { ...

So, instead of the swagger-ui showing something like: /"api/{itemId}", it ends up showing "/api/{itemId}/a/bunch/of/path/items/that/are/really/itemid/regex"

Hopefully that makes sense. Poking around in the code, I think it's an assumption that the first close brace it finds closes the parameter opening brace, but that's not true when the regex is there:
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L262

**Comment by webron** [comment]
Resolved in develop_2.0.

**Comment by chriskessel** [comment]
Damn, that's some impressively gnarly cases to have to parse! Great unit test coverage! 

:+1: Awesome :)

**Comment by webron** [comment]
@lugaru1234 takes care of the fine details :)
