### ISSUE TITLE
Optional<String> causes error in jax-rs parsing

### ISSUE THREAD

**Issue by ashley-taylor** [swagger-api/swagger-core#1157]
getting the following error

Unrecognized Type: [null]

using swagger through the 
com.github.kongchen:swagger-maven-plugin 
maven plugin

which is compiled against swagger-core 1.5.1-M2

Cheers,
Ashley

**Comment by webron** [comment]
@ashley-taylor time to upgrade to the latest version and try!

**Comment by ashley-taylor** [comment]
change to the latest io.swagger version and it now works

Cheers,
Ashley
