### ISSUE TITLE
ModelConverter can't set a property to read-only

### ISSUE THREAD

**Issue by diagonal-e** [swagger-api/swagger-core#1161]
In `ModelResolver.resolve`, _after_ getting a Property from the available ModelResolver(s), it does this:

    property.setReadOnly(_findReadOnly(member));

The `_findReadOnly` method looks for a `readOnly` attribute in an `@ApiModelProperty` annotation; if there isn't any, it returns null. The problem with this is that if you have a ModelConverter that has some other mechanism for determining that some property is read-only (e.g. based on its type... or some custom annotation you've created as a shortcut for setting several `@ApiModelProperty` attributes at once), and your ModelConverter calls `setReadOnly(true)` on the Property before returning it, that flag will be overwritten with null.

I think the correct behavior would be: pass the return value of `_findReadOnly` to `property.setReadOnly` only if it is non-null.

**Comment by who** [comment]
I am seeing the same issue in reverse; I cannot remove a `"readOnly" : true` setting from the properties by adding the `readOnly=true` parameter to my `ApiModelProperty` annotation.

I dug into the swagger-core code and found this:

https://github.com/swagger-api/swagger-core/blob/9c67549cc4e30db916dac0165f0549485a6eb4c7/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L276-L280

Apparently, if a field has a getter and a setter, it is not read only.  If it only has a getter, and no setter, then it's read only.

I was able to work around this by adding a private setter method inside my model classes.

@diagonal-e , what happens in your case, if you remove your setter methods?

**Comment by diagonal-e** [comment]
@who - I'm using the Scala module, which (though I'm not sure how) seems to circumvent the getter/setter logic in ModelResolver (since in Scala it's common to use immutable case classes for everything, so the presence of a setter isn't really related to whether a REST client is allowed to modify the property).
However, I'm not sure why the code would behave the way you say it's behaving. On lines 380-384, it looks like it does override the readOnly flag based on the getter/setter situation, but only if property.getReadOnly() is still null at that point... and if you had `readOnly=false` in your annotation, then it should have already set readOnly to false, rather than null, on line 378. So I'm not sure what's going on there.

**Comment by diagonal-e** [comment]
(As you can see, I'm "not sure" about a lot of things...)

**Comment by diagonal-e** [comment]
I can't say I even understand the intended behavior for Java code. I mean, just because a Java bean property has a setter is not evidence that a REST client is supposed to be able to edit it; nor is the contrary true, since Java programmers can use immutable classes for the same reasons Scala programmers do. It's inappropriately assuming a direct correspondence between how the class is used internally in your code and how it's used via REST.

**Comment by who** [comment]
@diagonal-e Agreed. Having the read-only attribute automatically adjust depending on getters and setters is, in my opinion, too prescriptive. Also, I did indeed try readOnly=false to over-ride the automatic setting, but it doesn't work.  For now, I'll just stick to keeping that dummy setter.

**Comment by fehguy** [comment]
Thanks all--this is fixed in master now and will go out in the next release.

**Comment by viktorgunnarson** [comment]
This seems to be broken when using `@JsonProperty`.

This model:
```java
@ApiModel
public class TestModel {

    @ApiModelProperty(value = "Prop", readOnly = false)
    @JsonProperty
    private String prop;

    public TestModel() {
    }

    public TestModel(String prop) {
        this.prop = prop;
    }

    public String getProp() {
        return prop;
    }
}
```

Results in:
```javascript
TestModel:
  type: "object"
  properties:
    prop:
      type: "string"
      description: "Prop"
      readOnly: true
```

If `@JsonProperty` is removed the readOnly row disappears in the swagger spec.

**Comment by sergeijakovlev** [comment]
This does seem to be broken in my case as well. The behavior I see currently using Jackson annotations:

1. private field, getter, no annotations - not read only (OK)
2. private field, getter, setter, no annotations - not read only (OK)
3. private field, getter, @JsonProperty - read only (in my opinion NOK)
4. private field, getter, @JsonProperty with access=READ_WRITE - read only (NOK)
5. private field, getter, @JsonProperty with access=READ_WRITE and @ApiModelProperty with readOnly=false - read only (very much NOK)
6. private field, getter, @ApiModelProperty with readOnly=false, constructor with @JsonCreator with an argument marked @JsonProperty with name="fieldName" and access=READ_WRITE - read only (NOK)

This makes it very inconvenient to  use immutable objects with Swagger Core. A simplified example of a class that we would like to use:

    public class SomeDTO implements Serializable {
        private final String value;
        
        public String getValue() {
            return this.Value;
        }
        
        @JsonCreator
        public SomeDTO(@JsonProperty(value = "value", required = true) String name) {
            this.value = value;
        }
    }

Unfortunately, the generated Swagger definition is the following:

    SomeDTO:
      type: "object"
      required:
      - "value"
      properties:
        value:
          type: "string"
          readOnly: true # <- NOK
