### ISSUE TITLE
Position information in the generated swagger model.

### ISSUE THREAD

**Issue by guptasu** [swagger-api/swagger-core#1164]
Hi,

I am using swagger parser to create Swagger Object. I would like to do some analysis on the Swagger Object and then report the error and warnings. Right now there is no way for me to point user to the location where the error is. 

Is there some think I can use to get the line and column position of a property/parameter/items/type inside a Swagger Object ?
Any alternate suggestions if this feature is not present and will not be implemented in the near feature.

**Comment by fehguy** [comment]
There is no "permalink" to a section of the swagger spec.  I think you can create something of your own, that follows the general hierarchal structure of the swagger object, though.
