### ISSUE TITLE
ModelResolver shouldn't try to guess readOnly status based on getter/setter

### ISSUE THREAD

**Issue by diagonal-e** [swagger-api/swagger-core#1165]
For model properties that don't have an annotation with a `readOnly` attribute, ModelResolver has some logic (lines 263-280 and 380-384, in 1.5.0) that marks the property as read-only if there is a getter method for it and no setter method.

I think this is inappropriately conflating internal implementation details, related to how the class is used within your code, with usage semantics in the external API. That is, it's very possible (and, I think, even common) to have your REST representation be an immutable Java class that is always created via a constructor or factory method and has _no_ setter methods, and still allow a REST client to set the properties of that representation in a PUT or POST. Conversely, a bean class might have setter methods for every property because that's convenient for your own internal purposes, but the external client might not be allowed to set those properties. There's really no logical connection between those two things, so Swagger shouldn't be trying to guess one based on the other, even if you're allowing that guess to be overridden by an annotation.

**Comment by who** [comment]
:+1:  Agreed. The auto-magic read-only determination is too prescriptive.

**Comment by greenreign** [comment]
I just stumbled over this trying to use swagger for the first time.

**Comment by fehguy** [comment]
This has been addressed by #1161
