### ISSUE TITLE
Throwable subclasses inevitably inherit its property suppressed. Exclude Throwable from model by default

### ISSUE THREAD

**Issue by andi-livn** [swagger-api/swagger-core#1168]
We have several classes in our API model that are more or less directly extending java.lang.Throwable. Unfortunately Throwable includes the final method Throwable[] getSuppressed(), which far as I can see, makes it very hard to hide or suppress swagger from including Throwable (and subsequently StackTraceElement) from the model.

My current solution is to register a custom model converter that explicitly resolves Throwable (wihtout its subclasses) to a plain generic JSON object.

``` java
public class CustomModelConverter implements ModelConverter {

    @Override
    public Property resolveProperty(Type type, ModelConverterContext context, Annotation[] annotations, Iterator<ModelConverter> chain) {
JavaType _type = Json.mapper().constructType(type);
if (_type != null) {
Class<?> cls = _type.getRawClass();
if (org.joda.time.DateTime.class.isAssignableFrom(cls)) {
return new DateTimeProperty();
}
//...
if(Throwable.class.equals(cls)) {
return new ObjectProperty();
}
}
if (chain.hasNext()) {
return chain.next().resolveProperty(type, context, annotations, chain);
} else {
return null;
}
}
```

Would it make sense to exclude Throwable from the model by default?

**Comment by webron** [comment]
It probably would, but out of curiosity, how do you end up having a model that extends Throwable?

**Comment by andi-livn** [comment]
```java
//...
@ApiOperation(value = "Modifies the passenger record.", response = Pax.class)
@ApiResponses(value = {
			@ApiResponse(code = 400, message = "Submitted data contains errors (e.g. fields exceed max length).", response=ApiException.class), //...
	})
	public Pax customisePax(
			@ApiParam(value="Pax including the API user custom strings 1-4.") Pax pax
			) {
//... we validate data client wishes to modify

if(!validationErrors.isEmpty()) {
			ApiException ex = new ApiException(ApiExceptionReason.INVALID_DATA);
			ex.setDetails(validationErrors);
			throw new MappableContainerException(ex);
		}

```

If the submitted data doesn't validate, say an email address is malformed, the MappableContainerException is resolved by

```java

@Provider
public class ApiExceptionMapper implements ExceptionMapper<ApiException> {

	@Context
	protected HttpHeaders hh;

    @Override
	public Response toResponse(ApiException e) {

    	return Response
    		.status(e.getStatus())
    		.entity(e)
    		.type(this.hh.getMediaType())
    		.build();
    }
}

```
ApiException itself extends RuntimException, but is also annotated to double up as an API type (hiding all but the details we wish to share with the client)
I suppose we should just let the API return a plain purpose-built type and map our exceptions to that.

**Comment by webron** [comment]
Okay, fair enough, thanks for the details.

**Comment by lugaru1234** [comment]
I have tested the mechanism on jersey jax-rs implementation (version 1.13) and here is serialized exception thrown by an operation:
````
{
   "stackTrace":[
      {
         "methodName":"getPetById",
         "fileName":"PetResource.java",
         "lineNumber":61,
         "className":"io.swagger.sample.resource.PetResource",
         "nativeMethod":false
      },
      {
         "methodName":"invoke0",
         "fileName":"NativeMethodAccessorImpl.java",
         "lineNumber":-2,
         "className":"sun.reflect.NativeMethodAccessorImpl",
         "nativeMethod":true
      }     
...
      {
         "methodName":"run",
         "fileName":"Thread.java",
         "lineNumber":745,
         "className":"java.lang.Thread",
         "nativeMethod":false
      }
   ],
   "message":"test exception",
   "localizedMessage":"test exception",
   "suppressed":[]
}
````
and it would make sense in that case that the same information would be available in the model itself.

**Comment by webron** [comment]
@andi-livn - can you provide more details regarding your use case? As it is now, it seems to behave as you would expect it to.

**Comment by andi-livn** [comment]
The use case is as described above in my post from 16 Jun. When we run into problems executing a request, we return a non-code-200 code along with a descriptive entity by throwing an exception. In the example API method, our users can modify a record for a passenger, i.e. Pax. If the submitted data is valid and we can modify our database we return an OK 200 along with the Pax entity (we omit the 200 case from the documented @ApiResponses. Is it better to include?) If however the submitted Pax data is invalid, e.g. email is null or "i.am.not.an.email.address", we throw an ApiException, which in turn is mapped to respond with a code 400 Bad Request and the exception itself as message body. For this purpose ApiException is part of our API model:

@XmlRootElement(name="apiException")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso(ApiAuthenticationException.class)
@JsonRootName("apiException")
@ApiModel
public class ApiException extends TransientRuntimeException {....}

and

@XmlTransient
@XmlAccessorType(XmlAccessType.FIELD)
@JsonIgnoreProperties({"detailMessage","cause","stackTrace"})
@JsonRootName("exception")
@ApiModel
public abstract class TransientRuntimeException extends RuntimeException {

	private static final long serialVersionUID = 201212191451L;

	@Override
	@ApiModelProperty(hidden=true)
	public StackTraceElement[] getStackTrace() {
		return super.getStackTrace();
	}

	@Override
	@ApiModelProperty(hidden=true)
	public synchronized Throwable getCause() {
		return super.getCause();
	}

	@Override
	@ApiModelProperty(hidden=true)
	public String getLocalizedMessage() {
		return super.getLocalizedMessage();
	}

	@Override
	@ApiModelProperty(hidden=true)
	public String getMessage() {
		return super.getMessage();
	}
}

As TransientRuntimeException extends RuntimException extends Throwable, our swagger model contains information on model types for Throwable and StackTraceElement, even though we never include them in our response. We wish to give our users more details about what was wrong with their requests, but we do not wish to give them a full stack trace ;)

As I see it we have two options, we can either separate exceptions and API types, i.e. map the actual Throwable subtypes, say {app}.api.exceptions.ApiException to separate API model types, e.g. {app}.api.model.exceptions.ApiException, that do not include inherited baggage.
Or we can instruct swagger, via a custom ModelConverter, to simply dismiss Throwable as a generic ObjectProperty without including further details.

**Comment by webron** [comment]
Thanks for the details, @andi-livn. The issue here is not how to support it, but how to reproduce it. When we write a simple example, the exceptions are serialized and sent to the use with that extra metadata, so it makes sense that this metadata is described in Swagger as well. However. you mention that "we never include them in our response" which suggests you do some additional processing. The question we're trying to raise is where do you do that additional processing? There could be several places this is taken care of, and perhaps our solution should be hooked into that method.

**Comment by andi-livn** [comment]
I see. We tell Jersey to omit the field inherited from Throwable using various annotations in TransientRuntimeException (which all our exceptions that also serve as API model types entend)

See above we use @XmlTransient, @JsonIgnoreProperties (I think this one might not be required) and even instruct Swagger itself to hide them using @ApiModelProperty(hidden=true). Subsequently our API users don't see the full stack trace, which as you say, would otherwise be serialized (Thread and StackTraceElement being Serializable)

So I'm guessing swagger would have to observe @XmlTransient and ignore types that are thus annotated not to be included in API response/request entities

**Comment by webron** [comment]
Right, that's the information we were looking for, thanks. We can continue investigating from here.

However, which version have you tested it with?

**Comment by andi-livn** [comment]
Excellent. We've only been using 1.5.0 (io.swagger:swagger-jersey-jaxrs and its dependencies) so far. As I see it there is no newer release in the new io.swagger group, just in the old com.wordnik

**Comment by webron** [comment]
We haven't announced it yet, but we released 1.5.1 yesterday with a minor possibly related change. Mind just testing it to make sure it's still an issue?

**Comment by andi-livn** [comment]
Cool. I've just tried 1.5.1, but the Throwable and StackTraceElement types are still in swagger.json:

```json
Throwable": {

    "type": "object",
    "properties": 

{

    "cause": 

{

    "$ref": "#/definitions/Throwable"

},
"stackTrace": 
{

    "type": "array",
    "items": 

    {
        "$ref": "#/definitions/StackTraceElement"
    }

},
"message": 
{

    "type": "string"

},
"localizedMessage": 
{

    "type": "string"

},
"suppressed": 
{

    "type": "array",
    "items": 

            {
                "$ref": "#/definitions/Throwable"
            }
        }
    }

}
```

and

```json
StackTraceElement": {

    "type": "object",
    "properties": 

{

    "methodName": 

{

    "type": "string"

},
"fileName": 
{

    "type": "string"

},
"lineNumber": 
{

    "type": "integer",
    "format": "int32"

},
"className": 
{

    "type": "string"

},
"nativeMethod": 

        {
            "type": "boolean",
            "default": false
        }
    }

}
```

I need to leave my Throwable->ObjectProperty hack in our CustomModelConverter, then our exceptions include

```json
suppressed": {

    "type": "array",
    "items": 

    {
        "type": "object"
    }

}
```

...but no Throwable and STE
Thanks for looking into this. Swagger really rocks ;)

**Comment by webron** [comment]
Yes. It's because Swagger rocks so much that we end up doing the work.

**Comment by frantuma** [comment]
@andi-livn I am not sure if I get correctly your use case, and you want to have Throwable "completely out of the way", you can mark `TransientRuntimeException` with

`@JsonIgnoreProperties({"detailMessage","cause","stackTrace", "suppressed"})`

so basically adding suppressed to JsonIgnore

**Comment by andi-livn** [comment]
@frantuma Thanks for the suggestion. I just tried it, but both Throwable and StackTraceElement are included in the generated swagger.json.

**Comment by frantuma** [comment]
@andi-livn mmh strange actually, it seems to work alright with similar code as in https://gist.github.com/frantuma/3a563b8576a5e75f141a.

Are you using latest version of swagger?

**Comment by webron** [comment]
@andi-livn any update?

**Comment by andi-livn** [comment]
Sorry, have been flat out at work lately. I've only tried the above suggestion using v1.5.4.
I can update to the latest stable 1.5.8 and report back if that makes a difference.
