### ISSUE TITLE
It would be great if setting an example value in a custom type ModelConverter could be reflected in the generated JSON

### ISSUE THREAD

**Issue by andi-livn** [swagger-api/swagger-core#1174]
Example: we are using a JAXB XmlAdapter in our API that de-/serializes java.util.Currency from/to the corresponding ISO currency code String.

In order to get swagger to define Currency properties as JSON data type string we register a custom ModelConverter, which amongst others contains the instruction to map the class Currency to this Property:

``` java
public class CurrencyProperty extends io.swagger.models.properties.AbstractProperty {
    public CurrencyProperty() {
        this.setType("string");
        this.setExample("USD"); //ISO 4217 currency code
    }
}
```

The resulting JSON works as far as our Currency fields come out as string (rather than a `$ref":"#/definitions/Currency` and a complex data type that includes currencyCode, defaultFractionDigits, symbol ...). There is not, however, any mention of the type example anywhere.
We need to manually annotate all Currency fields with `@ApiModelProperty(example="USD")`

Would it be possible for the example set in a ModelConverter to be used as default across all occurrences of that type?

**Comment by fehguy** [comment]
Yes, using `string` as an example really doesn't work here.  Will try to get this addressed in an update to the swagger-core and swagger-models.

**Comment by fehguy** [comment]
Follow #1107
