### ISSUE TITLE
Change logging level to DEBUG for some messages in PropertyBuilder

### ISSUE THREAD

**Issue by tomtit** [swagger-api/swagger-core#1175]
Change logging level for [this](https://github.com/swagger-api/swagger-core/blob/400662d7253c0c2efb14316f8948ddc61a60069e/modules/swagger-models/src/main/java/io/swagger/models/properties/PropertyBuilder.java#L569) message to DEBUG as these messages look confusing for [codegen](https://github.com/swagger-api/swagger-codegen) users (https://github.com/swagger-api/swagger-parser/issues/60).

**Comment by webron** [comment]
Fixed in develop_2.0.
