### ISSUE TITLE
DefaultJaxrsScanner in Dropwizard

### ISSUE THREAD

**Issue by skjegg** [swagger-api/swagger-core#1177]
Although it's possible to use the BeanConfig method with Dropwizard, it's problematic (for us) because it loads all the @Api annotated classes in the classpath, even though you may not have actually added them to the runtime, say through some configuration flag. 

So, I tried using the DefaultJaxrsScanner, and through some debugging, found this chunk: 
<code>
                  if (o instanceof Class) {
                        output.add((Class) o);
                  }
</code>
I created our own Scanner implementation that does: 
              <code> output.add(o.getClass()); </code>
instead. That appears to solve our problem, and things are great (for us). 

I can submit a PR for this, but I don't know if this is a case where Dropwizard is doing the wrong thing (full instances of the various Objects returned by app.getSingletons() ), or if this is something others have run into as well. Reading the javax.ws.rs.core.Application JavaDocs, I suspect that DefaultJaxrsScanner is broken, and shouldn't check if the Singleton object is an instance of Class

**Comment by fehguy** [comment]
@skjegg apologies for the delay.  You are indeed correct, the `getSingletons()` method will not return `class` objects.  Your fix makes sense--if you can submit a PR to the develop_2.0 branch, that'd be great.

**Comment by skjegg** [comment]
@lugaru1234 -- Thank you for fixing this. I was working on a testcase for it, and got sidetracked.

**Comment by webron** [comment]
Resolved in develop_2.0.
