### ISSUE TITLE
Lack of support to change value of 'collectionFormat' for an endpoint parameter

### ISSUE THREAD

**Issue by ipeluffo** [swagger-api/swagger-core#1180]
Hi everyone,

I've been searching for a way to change the value of the `collectionFormat` property of a parameter (ideally using the `@ApiParam` annotation) I found that it's not possible now.

Also, I asked in Google Groups for this to get a confirmation for my findings:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/BqvTNRPRp-U

It would be nice to be able to configure this value for each multi-valued parameter.

Thanks in advance.
Ignacio

**Comment by webron** [comment]
@ipeluffo, thanks for opening the issue. I preferred going into the discussion here rather than in the group as to not lose information. This is something we can definitely implement, but I'm curious to know your use case. 

When we wrote the spec, we tried covering common uses within common libraries. JAX-RS specifically use `multi` by default for multiple values. Are you looking to set it to any other kind? Do you parse it internally as part of your app?

**Comment by ipeluffo** [comment]
@webron , actually I found this issue because the default value is `csv` as reported in the issue #1160 .
In my case, I need to configure the `collectionFormat` property as `multi`, so fixing the issue #1160 should be enough for me.

However, I believe that adding the this feature is a more general solution that any developer can modify according to their particular implementation, like it was mention in #478 .

Anyway, feel free to close this issue if you think it'll be resolved fixing #1160 

Thanks again.

**Comment by webron** [comment]
@ipeluffo - okay, if #1160 is indeed the issue (and we will change it), then let's keep this one open as a general feature request, we may just not prioritize it high for now.

**Comment by nikhilw** [comment]
Would like to suggest that the same functionality should also be available in `@ApiImplicitParam`.

**Comment by fehguy** [comment]
Added to the annotations in 1.5.11.

**Comment by vsvetoslavov** [comment]
"Added to the annotations in 1.5.11."
I am using swagger-core 2.0.0 and I see nothing like this there. Where has this been added?

**Comment by vsvetoslavov** [comment]
@webron Thanks
