### ISSUE TITLE
JAX-RS: honor `@Deprecated` annotation

### ISSUE THREAD

**Issue by t1** [swagger-api/swagger-core#1183]
When a jax-rs method is annotated as `@Deprecated`, it should be honored by setting the `deprecated` flag of the [operationObject](http://swagger.io/specification/#operationObject)

Thankfully, the `@Deprecated` annotation has the `RetentionPolicy.RUNTIME`.

**Comment by webron** [comment]
Which version have you tried it with?

**Comment by t1** [comment]
tried it with 1.5.0

**Comment by webron** [comment]
It's a bug then, just looked again.

We read it, but don't set it - https://github.com/swagger-api/swagger-core/blob/9c67549cc4e30db916dac0165f0549485a6eb4c7/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L828-L832.

**Comment by t1** [comment]
I'd love to contribute a patch, but I'm not getting it to build OOTB. Maven complains that it can't resolve the Felix build extension: `Plugin org.apache.felix:maven-bundle-plugin:0.8.0-incubator or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.felix:maven-bundle-plugin:jar:0.8.0-incubator -> biz.aQute:bnd:jar:0.0.106`

Maybe I'm missing something?

**Comment by webron** [comment]
Just tried running it, and it builds fine here. It does give warnings on the felix plugin but doesn't break anything.

**Comment by t1** [comment]
Retrying with a clean `~/.m2/repository` helped. Sorry for bothering.

**Comment by webron** [comment]
Resolved in develop_2.0.

**Comment by t1** [comment]
I was too slow ;-)
