### ISSUE TITLE
Add @ApiParam#hidden()

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#1188]
Was sure we had this one, but it doesn't seem to be the case. We should add `boolean hidden()` to `@ApiParam`, with the default value `false`. If set to `true`, that parameter should be dropped from the parameter list of the operation.

This would have helped #1187 and  #1173 (possibly making it obsolete).

**Comment by t1** [comment]
I'd like to work on a patch for this issue.

**Comment by who** [comment]
+1

**Comment by t1** [comment]
I've created [pull request 1192](https://github.com/swagger-api/swagger-core/pull/1192)

**Comment by t1** [comment]
I've updated [pull#1192](https://github.com/swagger-api/swagger-core/pull/1192) as requested. Can I improve anything else on it?

**Comment by webron** [comment]
Fixed in develop_2.0. Thanks @t1!

**Comment by who** [comment]
Thank you, @t1 !
