### ISSUE TITLE
@Path("") and @Path("/") produce an empty path

### ISSUE THREAD

**Issue by crehn** [swagger-api/swagger-core#1189]
A jax-rs resource which is annotated with `@Path("")` or  `@Path("/")` is perfectly valid and specifies a root resource. Accodring to the spec, fields in the [paths object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#pathsObject) must begin with a slash, tough. For that reason swagger-core should produce a paths object like this one:
```
"paths": {
        "/": {
    }
}
```
But instead it produces this:
```
"paths": {
        "": {
    }
}
```
This violates the spec and is not accepted by swagger-ui and the validator.

Affected Version: swagger-jaxrs 1.5.0

**Comment by webron** [comment]
Fixed in develop_2.0.
