### ISSUE TITLE
BasePath not added to swagger.json in java-resteasy sample

### ISSUE THREAD

**Issue by Isnogud77** [swagger-api/swagger-core#1194]
I've created a REST Api running on JBoss EAP 6 with RESTEasy which is based on the java-resteasy sample. I noticed in my application that basePath isn't added to the swagger.json even though I've declared that in the Bootstrap class. All other information seem to be added correctly.

I then tried to reproduce the issue by running the sample and it's exactly the same behaviour. The basePath is missing there as well. So, this sample could be used to debug/reproduce the issue. 

This leads to the situation that I can examine the API in the UI but can't execute interactive requests.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-samples#9
