### ISSUE TITLE
Explicit control of "format" model property

### ISSUE THREAD

**Issue by tsandall** [swagger-api/swagger-core#1197]
Per discussion in https://github.com/swagger-api/swagger-core/issues/517 the "format" value for model properties can be inferred for a few common types. Currently it covers types like DateTime, UUID, etc.

At the same time, Swagger 2.0 allows format values which are not defined in the specification. This is nice because API developers can use values defined in new authoritative sources such as RFCs.

swagger-core can continue to infer the format values for common types however it will always lag behind new authoritative sources. In these cases, the API developer should be able to explicitly set the format value on model properties.

Whether this is supported via the `@ApiModelProperty` annotation or some other mechanism is less important as long as it's possible. It would be nice if the solution could be used easily with Scala case classes.

**Comment by webron** [comment]
This is related to #993.

**Comment by fehguy** [comment]
Yes, as it stands, the `PropertyBuilder` is not forgiving when there isn't a matching format.  We should have a fallback to `string` with custom formats if not matched with `string` + any of the known formats.

**Comment by fehguy** [comment]
We have created fallbacks in PropertyBuilder so the `type` can have an implementation when `format` is not matched.
