### ISSUE TITLE
Migrate tests from the Scala to the plain Java

### ISSUE THREAD

**Issue by iushankin** [swagger-api/swagger-core#1203]
Rework all test to the Java with the TestNG framework

- [x] add required dependencies to the pom.xml files
- [ ] swagger-core #1206 
- [x] swagger-jaxrs #1207 
- [x] swagger-jersey2-jaxrs #1208 
- [ ] swagger-hibernate-validations #1209

**Comment by webron** [comment]
Related to #804.

**Comment by webron** [comment]
This is not complete yet.
