### ISSUE TITLE
Consider updating to Jackson 2.5

### ISSUE THREAD

**Issue by gitblit** [swagger-api/swagger-core#1205]
Jackson 2.5 changed/removed some method signatures which causes runtime errors when trying to squeeze swagger-core into other projects.  It would be nice to avoid downgrading to 2.4.

**Comment by webron** [comment]
I guess that's a regular problem. We have users who depend on Jackson 2.2 and 2.3 and in a way they are forced to upgrade to 2.4(.2) when using swagger-core. Not sure there's a right answer here.

**Comment by gitblit** [comment]
I agree although *my* needs are obviously more important. :stuck_out_tongue_winking_eye: 

I can live with 2.4 but Jackson already has 2.6 RCs so at some point this will come up again. Thanks for considering the request.

**Comment by webron** [comment]
Closing this one for now. The real reason to upgrade to 2.5/2.6 would be if the new version includes something that affects swagger-core. 2.6 *may* include a fix to some issue and then it would become relevant.
