### ISSUE TITLE
Upgrade to JAX-RS 2.0

### ISSUE THREAD

**Issue by juergenzimmermann** [swagger-api/swagger-core#1210]
The current dependency javax.ws.rs:jsr311-api:1.1.1 addresses JAX-RS 1.1.
To address JAX-RS 2.0 you should include the dependency javax.ws.rs:javax.ws.rs-api:2.0.1

**Comment by webron** [comment]
This is not really an issue. The jaxrs module which represents JAX-RS 1 depends on it and the Jersey2 module which represents JAX-RS 2 depends on the other. We do need to clean out the dependencies a bit, but there's no need to upgrade anything.

**Comment by juergenzimmermann** [comment]
@webron I don't agree, because there is also RESTEasy, not only Jersey.
When you are using RESTEasy standalone or JBoss or WildFly, then you cannot use the Jersey module. When using the JAX-RS module then you have to exclude the JAX-RS 1.1 dependency. That's really cumbersome.

**Comment by webron** [comment]
That depends on the RESTEasy version you use. If you're using one that supports JAX-RS 1, you should use the swagger-jaxrs module. If you're using the one that supports JAX-RS 2, then you should use the swagger-jersey2-jaxrs module (yes, jersey2). The reason for this is historical and while it is not the most convenient solution, it's the one we currently offer. None of the other modules will provide support for `@BeanParam`s. 

What we don't support with RESTEasy (or anything other than Jersey) is file uploads. We need to restructure the modules a bit for easier seamless integration, but this is the current situation. There's still no room to 'upgrade' the swagger-jaxrs dependency to JAX-RS 2.0 as it is intended to support 1.0/1.1.

**Comment by juergenzimmermann** [comment]
@webron OK, got it. I successfully changed the WildFly module: the maven exclusion stuff is gone and everything works fine. Thank you!

**Comment by webron** [comment]
Thanks for the update. For reference, I just created https://github.com/swagger-api/swagger-core/issues/1244 so we won't forget to handle it.
