### ISSUE TITLE
Parameter annotations are not inherited [swagger-core 1.5.0, jaxrs 2.0]

### ISSUE THREAD

**Issue by jacob-meacham** [swagger-api/swagger-core#1211]
If I have an interface with jaxrs annotations (for instance, if I expose an API for Feign) and then an implementation of that interface with Swagger annotations, the parameters do not get built correctly. I believe this is due to line 845 of io.swagger.jaxrs.Reader, which only gets the annotations for the method, and does not check the superclass.

Repro:
```java
@Path("/")
interface MyInterface {
    @GET
    @Path("test/{var}")
    @Produces(MediaType.APPLICATION_JSON)
    boolean get(@HeaderParam("myheader") String header,
                               @PathParam("var") String var);
}

@Api
class MyClass implements MyInterface {
    boolean get(@ApiParam(value = "...") String header, @ApiParam(value = "...") String var) { ... }
}
```

This will result in 2 body fields being added to the Swagger output because the @HeaderParam and @PathParam annotations aren't found.

**Comment by webron** [comment]
Will need to investigate it further, but have you tried putting the swagger-core annotations on the interface alongside the jax-rs annotations?

**Comment by jacob-meacham** [comment]
Yeah, putting the swagger-core annotations on the interface works as expected. The reason that this isn't as desirable for me is that I publish an API jar which is (by design) very lightweight -- it's only dependencies are the jax-rs annotations, and jackson annotations. I'd prefer not pulling swagger into this jar as well. If I'm able to separate the swagger and jax-rs annotations, then my server impl can take the swagger dependency and my consumers don't have to worry about it

**Comment by webron** [comment]
I see. This would make the processing that much complicated, and can't say it end up being high in the priorities we have right now, unfortunately.

Not wanting to include swagger-core as a dependency is understandable, but FWIW, you can include only the swagger-annotations dependency in the public API jar which is very lightweight (about 14k).

**Comment by fehguy** [comment]
As @webron said, you can include just the swagger annotations for lightweight support.
