### ISSUE TITLE
@Deprecated is not inherited from the superclass [swagger-core 1.5.0, jaxrs 2.0]

### ISSUE THREAD

**Issue by jacob-meacham** [swagger-api/swagger-core#1212]
io.swagger.jaxrs.Reader contains

```java
boolean isDeprecated = false;
annotation = method.getAnnotation(Deprecated.class);
if (annotation != null) {
    isDeprecated = true;
}
```

Instead of using the helper function getAnnotation(method, Deprecated.class), which would correctly search up the class hierarchy.

**Comment by webron** [comment]
Care to submit a PR (including a test)?

**Comment by jacob-meacham** [comment]
Yes, will do!

**Comment by webron** [comment]
Fixed in develop_2.0.
