### ISSUE TITLE
Definition object does not support primitives type schema object fully (e.g. string minLength)

### ISSUE THREAD

**Issue by danieljsun** [swagger-api/swagger-core#1213]
According to this (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#definitionsObject), i should be abel to specify a primitive type.
For example, if I want to share the following string type (with validation on maxLength) within a few different operation params, I have to repetitively declare them inline instead of using one "Definition".
```json
"shortName": {
        "type": "string",
        "maxLength": 25
}
```

**Comment by webron** [comment]
It's supported when using [JSR303](https://www.jcp.org/en/jsr/detail?id=303).

**Comment by webron** [comment]
@danieljsun - have you tried it?

**Comment by webron** [comment]
Closing this one due to lack of activity. Please reopen if needed.
