### ISSUE TITLE
@JsonIgnor'ed getter causes write operations to also hide the property

### ISSUE THREAD

**Issue by greenreign** [swagger-api/swagger-core#1214]
```java
@JsonIgnore
public String getPassword() {
    return password;
}

@JsonProperty
public void setPassword(String password) {
    this.password = password;
}
```

I would expect that the password property is shown for POST/PUT and hidden for GET.  However the password property is hidden for both.  Making what I assume is a fairly common configuration inaccurate.

**Comment by webron** [comment]
This is a bit challenging because it means we need to generate two separate models, but we have only one model name. We could suffix the models with `Read` and `Write` though some may not like it.

**Comment by greenreign** [comment]
It seems a bit arbitrary to use the getter annotation and ignore the setter annotation.  This problem, and perhaps others, would not be a big issue If the ApiModelProperty annotation took precedence.  The documentation would at least be usable if I could:
```
@JsonIgnore
@ApiModelProperty(notes="POST/PUT only")
public String getPassword() {
    return password;
}

@JsonProperty
public void setPassword(String password) {
    this.password = password;
}
```
@ApiModelProperty should take precedence over implied getter/setter parsing.  I've experienced a similar problem being unable to have a property marked readonly through the ApiModelProperty because a setter exists.

**Comment by webron** [comment]
Had we ignored the setter annotation and use the setter annotation, that would have also been arbitrary. There's no doubt there's an issue here, I'm just not sure what the proper solution would be. Eventually, it's a matter of a naming convention and as you know, `"There are only two hard things in Computer Science: cache invalidation and naming things."`.

**Comment by greenreign** [comment]
That's true.  I do think upgrading the importance of the ApiModelProperty annotation to override any implicit logic would be a suitable workaround for this issue.  Perhaps not that simple

**Comment by webron** [comment]
Even if `@ApiModelProperty` takes precedence (and it should), it would not really solve the problem you bring up.

**Comment by greenreign** [comment]
Correct, it would not technically solve the problem however it would be an improvement and in my situation enough for my documentation to get by.   Should I open a separate issue with respect to the ApiModelProperty?  It seems like that could be accomplished without the complication of introducing a second model.

**Comment by webron** [comment]
Are you referring to just adding a note to the specific property?

**Comment by greenreign** [comment]
For me, that's an improvement.  If I could simply force the property to show up in the model then I could add a note that specifies when it's applicable.

**Comment by webron** [comment]
Yeah, looking at the code it looks like `@JsonIgnore` takes precedence over `@ApiModelProperty`. We'll have to look into it.

**Comment by fehguy** [comment]
@webron I think the intention has always been that `@Api**` annotations win.  We can update to support that if you agree

**Comment by webron** [comment]
Sounds good.

**Comment by fehguy** [comment]
OK so in this scenario, just the presence of `@ApiModelProperty` will cause the `@JsonIgnore` to be overridden, because the default value for `hidden()` is true.

**Comment by webron** [comment]
:+1:

**Comment by fehguy** [comment]
OK turns out this is buried deep in Jackson.  I don't think that overriding the `@JsonIgnore` is very feasible.  The annotation introspector allows an introspection pair--however, the default introspector will "win" if it sees an ignore annotation.  Since we don't want to remove the default introspector, it's going to be hidden even if you have the `@ApiModelProperty(hidden=false)`.  See:

https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.4.5/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotationIntrospectorPair.java#L275

**Comment by fehguy** [comment]
Since this is a behavior in Jackson, I don't think it can be resolved.  You'll have to perform some other Jackson magic to support this.
