### ISSUE TITLE
com.wordnik.swagger.jaxrs.json override with jersey entity filter

### ISSUE THREAD

**Issue by tongda** [swagger-api/swagger-core#1233]
Hi,

I am working on a project based on Jersey 2.x. We use Jersey's EntityFiltering feature to provide different view in different situation. It worked well until we integrate swagger into it.

I found that if we put "com.wordnik.swagger.jaxrs.json" into init param list of "jersey.config.server.provider.packages" in servlet settings, the EntityFiltering feature will fail to work. But if we remove "com.wordnik.swagger.jaxrs.json", all works good.

I am wondering that what is the package "com.wordnik.swagger.jaxrs.json" doing here and why EntityFiltering will not if this package present.

Thanks.

**Comment by iushankin** [comment]
Hi, which version of the Swagger do you use?
We changed base package from `com.wordnik.swagger` to `io.swagger` month ago. Please try to use `io.swagger.jaxrs.json` instead `com.wordnik.swagger.jaxrs.json`.

**Comment by tongda** [comment]
Hi, thanks for your reply.
I found that we are using 1.3.12. And I totally followed [this post](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-JAX-RS-Project-Setup) to set up swagger in our project.

I hope to update to the latest version. But I did not find any documents talking about it. Is there any configuration difference between the latest version (I found 1.5.0) and 1.3.12?

**Comment by tongda** [comment]
Hi, I have just found [this post](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5) and configured my project accordingly. It looks good so far.

BTW, I have encountered another issue. I have added an annotation marking the API response including a header like this:
```java
@ApiResponses(value = {
        @ApiResponse(code = 201, message = "Successfully created.",
                     responseHeaders = @ResponseHeader(name = "location",
                                                       description = "The created template url.",
                                                       response = String.class))
    })
```

And I found that the `http://**/swagger.json` contains a node like this:

```json
        "responses": {
          "201": {
            "description": "Successfully created.",
            "headers": {
              "location": {
                "type": "string",
                "description": "The created template url."
              }
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          }
        }
```

But in swagger ui, this row of response only have the http code and description, without presenting the headers information. Do you have any idea of this?

**Comment by webron** [comment]
It's an unimplemented feature - https://github.com/swagger-api/swagger-ui/issues/1117.

**Comment by tongda** [comment]
Got it! Thanks!
