### ISSUE TITLE
Problem with content-type and DELETE

### ISSUE THREAD

**Issue by stianl** [swagger-api/swagger-core#124]
It'd be great if it was possible to excercise some more control over the content-type header being sent from Swagger UI. When defining a API operation with HTTP method DELETE the content-type always seems to be "application/json". This causes Play2 to invoke a special body parser that tries to parse the body as JSON content, but this of course fails since the body is empty. I tried adding an annotation like     @Consumes(MediaType.APPLICATION_FORM_URLENCODED) to my method, but this does not seem to change the API JSON being generated (and thus not affecting the UI).

Could this annotation, or a similar parameter be used to control the content-type sent from swagger-ui?

**Comment by psinghsp** [comment]
I have a node/express server. Swagger-UI 2.0 always sets the Content-type header to "application/json" for DELETE operation. In my case, the body is empty - so Express body parser just chokes on it. I tried setting the "consumes" to "text/html" in the Swagger API specification - but Swagger-UI insists on sendting Content-type  as "application/json". Is it possible to get a fix for it?

**Comment by webron** [comment]
@psinghsp - this is really not the right place for the question. Sounds like you're looking for [swagger-node-express](https://github.com/swagger-api/swagger-node-express).

**Comment by psinghsp** [comment]
That is right. Let me post it on swagger-ui. The bug is in swagger-ui - not swagger-core. Sorry about that.
