### ISSUE TITLE
swagger-core fails to build with Java 8

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-core#1240]
With JAVA_HOME pointing to a JDK 1.8.0_45, building swagger-core fails because Java 8 is stricter
about Javadoc

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:03 min
[INFO] Finished at: 2015-07-06T08:58:46-05:00
[INFO] Final Memory: 53M/192M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.7:jar (attach-javadocs) on project swagger-jaxrs: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - swagger-core/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java:168: warning: no @param for cls
[... warnings removed ...]
[ERROR] swagger-core/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java:104: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^

```

The <p/> element is the problem.

Builds find if JAVA_HOME points to a JDK 1.7

I'll see if I can create a pull request....

**Comment by webron** [comment]
Which branch did you test?

**Comment by DavidBiesack** [comment]
master

**Comment by webron** [comment]
It's odd because I tried making sure the build works with Java 8 before publishing. Just ran `mvn clean package` on master and it worked fine...

**Comment by webron** [comment]
Aha, I do see the problematic line, but we don't normally build javadocs for that module. How do you run the build?

**Comment by DavidBiesack** [comment]
`mvn install`

runs javadoc so that it can install the -javadoc.jar

`mvn package`

does run cleanly.

**Comment by webron** [comment]
Thanks for checking. We should still clean those errors (they could be in multiple modules). If you can submit a PR that'd be great - it's a simple fix.

**Comment by DavidBiesack** [comment]
PR: https://github.com/swagger-api/swagger-core/pull/1241

**Comment by webron** [comment]
Fixed in develop_2.0, thanks for the PR.
