### ISSUE TITLE
Classes annotated with @SwaggerDefinition should be scanned first

### ISSUE THREAD

**Issue by MadMatt04** [swagger-api/swagger-core#1243]
Because when they're not, it can produce a bug with tag descriptions - if a tag (specified by the tag attribute of the @Api annotation) is scanned first, then it will already exist once the @SwaggerDefinition gets round to parsing its tag definitions - so a new tag object will not be added or old one modified - leaving the tag without description.

Example:
```java
// This is scanned first
@Api(tags = "composition")
public class CompositionResource {
}

// This is scanned second, but because the tag named composition
//  already exists, its description is not updated
@SwaggerDefinition(
        tags = {
                @Tag(name = "composition", description = "OpenEHR compositions."),                
        }
)
@Api
public interface SwaggerApiConfig {
}
```

The offending piece of code is in Swagger.addTag, which checks if the tag already exists by name, then ignores the add if it does:

```java
public void addTag(Tag tag) {
        if (this.tags == null) {
            this.tags = new ArrayList<Tag>();
        }
        if (tag != null && tag.getName() != null) {
            boolean found = false;
            for (Tag existing : this.tags) {
                if (existing.getName().equals(tag.getName())) {
                    found = true;
                }
            }
            if (!found) {
                this.tags.add(tag);
            }
        }
    }
```

**Comment by olensmar** [comment]
Hi! Why don't we just improve the addTag method to complement the existing tag with the metadata found in the SwaggerDefinition annotation?

**Comment by MadMatt04** [comment]
Sounds great to me.

**Comment by MadMatt04** [comment]
Actually now that I've put further thought into it, I again think my original suggestion is better. The reason for this is that if @SwaggerDefinition is parsed first, the order of the tags on the Swagger object will be the same as the order specified in @SwaggerDefinition, which makes it a simple way to enforce a particular tag order.

**Comment by olensmar** [comment]
ok - I'll consider that as well.. thanks

**Comment by olensmar** [comment]
https://github.com/swagger-api/swagger-core/pull/1264

**Comment by MadMatt04** [comment]
Yeah, it works. I tried it with Swagger built from the swagger-definition-scan-order-issue_1243 branch, and the descriptions are always there and the tags element in swagger.json is has elements in the same order as the annotations in @SwaggerDefinition.

The only thing I noticed is that swagger-ui reorders the tags alphabetically anyway, regardless of their order in swagger.json. Does anyone know anything about that? Everything on the swagger-core side seems to work fine, though.

Is this fix making it into 1.5.1?

**Comment by olensmar** [comment]
great - thanks for checking so quickly! @webron - can we get this into 1.5.1?

**Comment by webron** [comment]
I'll review the PR shortly.

**Comment by webron** [comment]
Fixed in develop_2.0.
