### ISSUE TITLE
Does swagger support annotations on interfaces? 

### ISSUE THREAD

**Issue by wasifshikder** [swagger-api/swagger-core#1247]
I have some interfaces for which I need to generate swagger documentation. Does swagger support 
annotations on interfaces? Can I generate documentation for annotations on interfaces?

**Comment by webron** [comment]
Yes.

**Comment by wasifshikder** [comment]
If I have a class that implements an interface. What is the syntax I have to establish a relationship between the interface and the class that implements the interface?

**Comment by webron** [comment]
I don't really know what that means.

**Comment by wasifshikder** [comment]
Does swagger automatically recognize that a particular class implements an interface?

**Comment by webron** [comment]
It should.

**Comment by wasifshikder** [comment]
What versions of swagger support annotations on interfaces?

**Comment by webron** [comment]
Most of them, but you should use the latest, 1.5.0.
