### ISSUE TITLE
What are the steps to set up a ReflectiveJaxrsScanner for Swagger in RESTEASY? 

### ISSUE THREAD

**Issue by wasifshikder** [swagger-api/swagger-core#1248]
The parameters for my methods in a class that implements an interface are called body. 
The actual name of the parameters are not seen. I am wondering why that is happening.
I feel like my ReflectiveJaxrsScanner is not working properly. So I am looking for some 
help on how to set it up.

**Comment by webron** [comment]
Which version do you use?

**Comment by webron** [comment]
@wasifshikder ?

**Comment by webron** [comment]
Closing the issue due to lack of response. Please reopen if needed.
