### ISSUE TITLE
@Api description overwritten by @ApiOperation notes

### ISSUE THREAD

**Issue by greenreign** [swagger-api/swagger-core#1251]
swagger-core: 1.5.1-M2

When annotating my resource I enter an @Api(descrption...) but it doesn't show up.  However the first operation's @ApiOperation(notes...) show up where I would expect the Api(descrption)

Resource

```
package com.swagger.test.resources;

import javax.ws.rs.POST;
import javax.ws.rs.Path;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

@Path("showadescripton")
@Api(value="This is the @Api#value", description="This is the @Api#description")
public class DescriptionResource {
    
    @POST
    @ApiOperation(value="This is the @ApiOperation#value", notes="This is the @ApiOperation#notes")
    public String post() {
        return "hello";
    }
  
}

```

Result:

![image](https://cloud.githubusercontent.com/assets/3790315/8580881/239ba81a-258b-11e5-9281-50a1d1ac32af.png)

**Comment by greenreign** [comment]
Looks like description has been marked deprecated in a future version.  Still the result for this version can't be correct.  

What way may I describe my resource in the future?

**Comment by webron** [comment]
First, upgrade to the latest version to see if the issue persists.

The description is now controlled via tags - https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs/src/main/java/io/swagger/sample/Bootstrap.java#L35-L45.

**Comment by webron** [comment]
@greenreign - any update?

**Comment by greenreign** [comment]
@webron Sorry for the delay.  I've had to shelf the documentation for a while.  The tags look like they will do the trick.  My dependency is from dropwizard-swagger 0.7 so I'm hoping that framework upgrades the swagger version so I can test it then.

**Comment by webron** [comment]
That solution should be available in 1.5.1-M2 too, iirc.

**Comment by greenreign** [comment]
Looks like @Tag was introduced in 1.5.2-M1

**Comment by webron** [comment]
Yes, but setting the Tags via the Swagger object directly as done in the Bootstrap sample shared above has existed since the first release.

**Comment by greenreign** [comment]
We are purely using annotations.  While the Swagger object may be a potential work around I think we'll wait until we have some time to either create a PR to upgrade dropwizard-swagger or dump that framework and use the latest swagger directly.  

@webron thanks for your time on this and the framework as well.  I think we can mark this one closed since so much has changed in the later versions.   Up to you I guess

**Comment by webron** [comment]
No problem. Feel free to reopen if needed.
