### ISSUE TITLE
io.swagger.jaxrs.Reader adds Definitions for non-annotated functions

### ISSUE THREAD

**Issue by tcuje** [swagger-api/swagger-core#1252]
Consider a class like this

    @Api
    @SwaggerDefinition(
        info = @Info(
                title = "Annotated Frontend Class",
                version = "0.1"))
    public class FrontendClass extends ParentClass {
        @GET
        @Path("/testGET")
        @Produces(MediaType.TEXT_PLAIN)
        @ApiOperation(value = "Test Function",
                notes = "Just returns a test string."))
        public String testGET() {
            return "test";
        }
        
        public MyClass1 getMyClass(MyClass2 arg) {
            return null;
        }
    }

When one reads this class using

    Swagger swagger = new Reader(new Swagger()).read(FrontendClass.class);

It will add Definitions for MyClass1 and MyClass2 as well.

This is caused by Reader.getParameters calling ParameterProcessor.applyAnnotations considering getMyClass as method with body parameter and adding definitions. Later on the method is ignored, because it's missing a required HTTP method annotation. Nevertheless the definitions stay inside the swagger object.

To solve this issue, I suggest to check the methods annotations BEFORE parsing anything of it's signature. Somewhere at about line 285 in io.swagger.jaxrs.Reader after extracting the operation method

    String httpMethod = extractOperationMethod(apiOperation, method, SwaggerExtensions.chain());
    // add the following check to skip not annotated classes
    if (httpMethod == null) { continue; }

**Comment by zyro23** [comment]
#1150 ?

**Comment by webron** [comment]
@tcuje - following @zyro23's comment (thanks!) can you try the 1.5.1-SNAPSHOT version to see if it solves your issue?

**Comment by tcuje** [comment]
@webron Where can I get this snapshot? I checked http://mvnrepository.com/artifact/io.swagger/swagger-jaxrs but there is only release 1.5.0

**Comment by webron** [comment]
@tcuje - Central doesn't allow for snapshots, and so they're available at sonatype - https://oss.sonatype.org/content/repositories/snapshots/io/swagger.

**Comment by tcuje** [comment]
Didn't work with 1.51 either. Output still contains the definitions for ParentClass and any parent class of ParentClass event though they're not annotated in any way.

**Comment by titiu7** [comment]
@webron assuming v1.5.4 will have the fix, when is the release expected?
Thanks

**Comment by webron** [comment]
@titiu7 - no idea, sorry, we don't really have a roadmap for releases (at least now). This issue will be closed automatically once the PR solving it is merged. If you need to test it, just add a comment and I'll publish a SNAPSHOT containing it.

**Comment by CSchulz** [comment]
@tcuje In 1.5.3 #1343 is fixed. Did it work for you now too?

**Comment by fehguy** [comment]
closing as fixed in 1.5.3

**Comment by tcuje** [comment]
Thank you all. I just tested it with 1.5.4 and it works perfectly! Thanks again!
