### ISSUE TITLE
1.5.0 / jaxrs - ArrayIndexOutOfBoundsException in ReflectionUtils.findMethod

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-core#1253]
given an interface like this
```
public interface Foo {
    public void bar(String one, String two);
    public void bar(String one);
}
```
https://github.com/swagger-api/swagger-core/blob/v1.5.0/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/utils/ReflectionUtils.java#L93
may fail with an `ArrayIndexOutOfBoundsException` because it tries to access the latter methods parameter types (`Type[]`, length 1) with the indices from the former methods parameter types (`Type[]`, length 2 (!)).

i think whats missing is maybe a check if the (generic) parameter type arrays have an equal length before comparing the parameter types (or else its not the same method anyway i guess)?

change looks like it was introduced by https://github.com/swagger-api/swagger-core/commit/f9ce1e36f0886af5e847566013c7b137570025dc#diff-026f230e26201caa6c55621d1f1862ccR78

thanks, zyro

**Comment by webron** [comment]
Fixed in develop_2.0.
