### ISSUE TITLE
Annotation for Authentication?

### ISSUE THREAD

**Issue by riaqn** [swagger-api/swagger-core#1257]
Is there any annotation I can use to specify the Authentication types(basic/api_key/oauth2) of an API?
It's documented in the `swagger-spec`, but not found in `swagger-core`.

**Comment by webron** [comment]
For general declaration, there are no annotations. You would go about it in a way similar to https://github.com/swagger-api/swagger-samples/blob/master/java/java-jersey-jaxrs/src/main/java/io/swagger/sample/Bootstrap.java#L31-L35.

For operation-specific declarations, you have https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#authorization-authorizationscope.

**Comment by riaqn** [comment]
@webron 
I guess I need to define an authentication method first? 
The problem is that I 'm using springfox to generate swagger spec, rather than hand-writing it. So how can I configure the swagger instance?

**Comment by webron** [comment]
That has nothing to do with swagger-core then. You'd have to consult with springfox's documentation regarding the authentication definition.

**Comment by riaqn** [comment]
thanks. I 've found the link on springfox, for future references I post here:
https://github.com/springfox/springfox/issues/821

**Comment by Michael-crazyman** [comment]
My web service need to authorize but swagger did not have a header blank to input header parameters.So my request is 401,how to solve it?
