### ISSUE TITLE
SecurityRequirements: Mismatch between model & spec

### ISSUE THREAD

**Issue by FossiFoo** [swagger-api/swagger-core#1258]
The spec defines "security" as [SecurityRequirement] and those as a Map of names and scopes, so effectively a List<Map<String,List<String>>>. 

Swagger.java however contains a protected List<SecurityRequirement> securityRequirements; with those being just a name and list of scopes, missing one level of the structure.

I would propose to add a "Requirements" object which contains a map of the existing SecurityRequirements.

While this is touched anyway, i also noticed, that the Method to add these is called "addSecurityDefinitions(SecurityRequirements)" instead of "addSecurityRequirements" and a plain "securityRequirements" Helper is missing.

**Comment by hgwood** [comment]
It is mentioned in #1271 that the fix for this requires a breaking change that will only be considered for the next major version. Is there any idea of the when of said major version?

**Comment by webron** [comment]
@hgwood - not yet.

**Comment by fehguy** [comment]
The helper `security` was added (not `securityRequirement` per your request) as it follows the JSON representation of attribute names.  There is als a `securityDefinition` helper for building a swagger with the SecurityDefinition object.  I'm not quite sure what the need is for a `Requirement` object though.

**Comment by cbornet** [comment]
The field is still serialized as "securityRequirement". Do you know if it works with swagger-codegen and swagger-ui ?

**Comment by cbornet** [comment]
Also I think the ```@JsonIgnore``` that was set on setSecurity() should be removed so that swagger-core can deserialize both security and securityRequirement but only serializes as securityRequirement. That would help for transitionning.

**Comment by boillodmanuel** [comment]
Any news on this topic? The generated swagger is not valid due to 'security' attribute that's named 'securityRequirement'. Do you have an ETA for this issue?

I noticed that there were breaking changes in 1.5.8. Could the fix of this issue be included in 1.5.9?

Best regards

**Comment by fehguy** [comment]
@boillodmanuel How are you getting `securityRequirement`?  The SwaggerSerializers for jackson should address this.  Perhaps you're not using them?  They are required.

**Comment by boillodmanuel** [comment]
I'm not. I' e looked at the unit test and they are using ObjectMapper.
Thanks for pointing this out.

**Comment by fehguy** [comment]
Ok, please report back if you're having troubles with this.  You can use the `Json.mapper()` for convenience.

**Comment by boillodmanuel** [comment]
I wrote a simple test:

```java
    @Test
    public void testSwaggerExport() throws Exception {
        Swagger swagger = new Swagger();
        swagger.setSecurity(Arrays.asList(new SecurityRequirement().scope("user").scope("movie")));
        System.out.println(SwaggerMappers.JSON.writeValueAsString(swagger));
    }
```
which produces the following json
```
{"swagger":"2.0","securityRequirement":[{"scopes":["user","movie"]}]}
```

which is invalid because the attribute `securityRequirement` does not exist is spec. It should be `security`.

I'm doing something wrong?

**Comment by cbornet** [comment]
To me, this is still not fixed : https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Swagger.java#L316

**Comment by boillodmanuel** [comment]
Is it planned to be fixed soon ? We have to live with a fork only because of this issue which is not ideal.

Thank you

**Comment by boillodmanuel** [comment]
Hello there,
I've open a pull-request to fix this issue: https://github.com/swagger-api/swagger-core/pull/1783
Hope this helps.

**Comment by naab** [comment]
I want to bump up this issue, because the latest swagger-ui can't handle "securityRequirement" field generated by this for the authentication feature. (it expects a "security" field, like it should be !)

as per swagger-codegen, its security definitions only work for the "securityRequirement" field, not "security" as it is based on this code (removing the @JsonIgnore on the setters could fix this tho...)

This is a major issue that should be integrated before everyone forks it to fix it... It shouldn't be discussed about for 1 year... 
And yes, all swaggers are broken.

The previous PR was closed.
Maybe will you aggree if I do another PR compatible with the existing version but add a security field too (one of them will be ignored depending on the reader) ? or maybe at least remove the @JsonIgnore on setSecurity  (to be able to use swagger-codegen with Spec compliant json...) ?

**Comment by fehguy** [comment]
This was fixed by https://github.com/swagger-api/swagger-core/pull/1783

**Comment by fehguy** [comment]
It should be in 1.5.9.  Can you please check and report back?

https://github.com/swagger-api/swagger-core/commit/d24904f9bf36f00a6fad0f66f09eb0472c4bd551

**Comment by boillodmanuel** [comment]
I confirm that it was not in 1.5.9.
I did a manual test and check the sources too.
Moreover Github commit d24904f says it was only on `master`, but rebase could create a new sha1. 
![image](https://cloud.githubusercontent.com/assets/621455/17592471/b68d84da-5fe2-11e6-9b9f-5d58c2acdbcd.png)

regards

**Comment by webron** [comment]
There are a few more PRs I'd like to merge in before pushing 1.5.10 out - hoping to get it all done next week. In the meantime, you can check out 1.5.10-SNAPSHOT.

**Comment by boillodmanuel** [comment]
I can wait. Thanks for the update.

**Comment by webron** [comment]
@boillodmanuel - it's pushed.

**Comment by boillodmanuel** [comment]
Thanks a lot.
