### ISSUE TITLE
Multiple security requirements with annotations

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-core#1261]
According to the spec, it should be possible to declare multiple requirements with AND logic on a Map but this doesn't seem to be possible from the annotations (only the OR list is available)

When using the authorizations={@Authorizations...} in an operation, the following code is called
```java
public void addSecurity(String name, List<String> scopes) {
        if (this.security == null) {
            this.security = new ArrayList<Map<String, List<String>>>();
        }
        Map<String, List<String>> req = new HashMap<String, List<String>>();
        if (scopes == null) {
            scopes = new ArrayList<String>();
        }
        req.put(name, scopes);
        this.security.add(req);
    }
```
so the authorization is put in a single element map  which is then added to the list.
Could it be possible to have support for the "AND" logic in the annotations ?

**Comment by cbornet** [comment]
Related to #1258 ?

**Comment by webron** [comment]
Yup, it depends on it.

**Comment by frantuma** [comment]
seems to be resolved by https://github.com/swagger-api/swagger-core/pull/1271
