### ISSUE TITLE
@ApiModelProperty annotation refuses to work in my model classes

### ISSUE THREAD

**Issue by ZMoose94** [swagger-api/swagger-core#1263]
I am trying to hide certain variable from documentation generation and also set some example values using the @ApiModelProperty annotation. I have integrated swagger 2 with a springfox implementation. Has anyone else had trouble with or know of any fixes? I have attached some sample code I have.

![code](https://cloud.githubusercontent.com/assets/12880171/8671095/ee8c38ac-2a2a-11e5-95ae-4deb9bcd6652.PNG)

As you can see I have also tried using the JsonIgnore annotation as well. I am just trying everything.

Thanks for the help!

**Comment by webron** [comment]
Since you're using springfox, you need to open the issue on their repository.
