### ISSUE TITLE
ModelConverters.getInstance().addPackageToSkip should exclude dependent packages (Feature)

### ISSUE THREAD

**Issue by mtraynham** [swagger-api/swagger-core#1265]
Posted in the Google Group about this issue a month or so ago, and Ron suggested I open a feature request:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/FKrog_4J2v8

> I sort of resolved my issue.  One of the POST body parameters in our Rest API is a Avro generated model.  Avro model's have a method called `getSchema():org.apache.avro.Schema`, and the Schema class has `getDefaultValue():org.codehaus.jackson.JsonNode`.  So Swagger interprets these and adds them to the model.  Unfortunately, those two classes are badly formed POJOs and this makes the Swagger UI blow up.
> The resolution was to ignore the class path for the object, using: `ModelConverters.getInstance().addPackageToSkip("com.my.avro.model");`
> **You can only skip classes that are used from the Rest interface.  You can't skip dependent/property packages...**  Also, there is a way to write a ModelConverter for the specific class to ignore the "schema" property, but that is just asking for bloated JSON configuration...

So the feature request here is changing `addPackageToSkip` to handle properties of Rest API classes and not just the class themselves.  Maybe the same thing could be done with `addClassToSkip`.

**Comment by tommymcglynn** [comment]
:+1: 

We're having the same issue.

**Comment by fehguy** [comment]
I think you'd have to implement this and send a PR.  What do you want to do when a property is skipped?  Ignore it?
