### ISSUE TITLE
Add info (metadata) in play module

### ISSUE THREAD

**Issue by zcsongor** [swagger-api/swagger-core#1272]
We can set an api's details and authorization via annotations, but it'd be great if one could fill out the info object (title, description, contact, license, etc) as well.

**Comment by olensmar** [comment]
Hi! 

You can do that with the new @SwaggerDefinition annotation - have a look at the https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/test/scala/resources/ResourceWithConfigAndExtensions.java class used by https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/test/scala/ConfigAndExtensionScannerTest.scala

Good Luck

**Comment by zcsongor** [comment]
Hi!

Thanks, but I'm not sure how can I use this annotation with swagger-play2(1.3.12), where swagger-core 1.5 is not yet supported.

**Comment by zcsongor** [comment]
Hi!

Oh, thanks, but how can I use it with the latest swagger-play2 module (1.3.12)?

**Comment by webron** [comment]
Right now, it's not possible. I've added the request to issue #918, please follow it for progress.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-play#4
