### ISSUE TITLE
@PathParam Annotation not interpreted correctly

### ISSUE THREAD

**Issue by marcelalburg** [swagger-api/swagger-core#1273]
Hello,

i found a little bug in the @PathParam Annotation.

If i write @PathParm("testParam"), the generated swagger.json is not valid and cannot read by swagger ui (i get an error: TypeError: undefined is not an object (evaluating 'property.$ref') in model.js:176

But if i write @PathParam(value="testParam") everything is correct.

IMHO both variants are correct.

Thanks

Marcel

**Comment by webron** [comment]
@marcelalburg - considering that Java-wise, those two are equivalent, it's unlikely that's the cause of the issue you're experiencing. Do you see any difference in the swagger.json produced by both variants?

**Comment by webron** [comment]
@marcelalburg?

**Comment by marcelalburg** [comment]
Sorry, but i cannot reproduce it in my project anymore. Maybe it's not the problem of the PathParam. 

Marcel

**Comment by marcelalburg** [comment]
Hello,

i found something and have more information about that.

If i run my project into eclipse, it works, but if i run it in the console with "java -jar" not.

i compare the genereaded swagger.json and see one difference:

working version:
```
      "Category":{
         "type":"object",
         "properties":{
            "id":{
               "type":"integer",
               "format":"int32"
            },
            "name":{
               "type":"string"
            },
            "parentId":{
               "type":"integer",
               "format":"int32"
            },
            "urlPath":{
               "type":"object",
               "additionalProperties":{
                  "type":"string"
               }
            },
            "sortOrder":{
               "type":"integer",
               "format":"int32"
            },
            "categories":{
               "type":"array",
               "items":{
                  "$ref":"#/definitions/Category"
               }
            }
         }
      },
```

not working version:
```
"Category":{
         "type":"object",
         "properties":{
            "id":{
               "type":"integer",
               "format":"int32"
            },
            "name":{
               "type":"string"
            },
            "parentId":{
               "type":"integer",
               "format":"int32"
            },
            "urlPath":{
               "type":"object",
               "additionalProperties":{
                  "type":"string"
               }
            },
            "sortOrder":{
               "type":"integer",
               "format":"int32"
            },
            "categories":{
               "type":"array"
            }
         }
      },
```

in the swagger ui, i get the same error like before..

Thanks Marcel

**Comment by webron** [comment]
That's an entirely different issue than the original one.
The difference is output is due to a difference in versions. I don't know how you manage your dependencies, but something is messed up there if you get different results in different environments. Make sure you use 15.2.

**Comment by marcelalburg** [comment]
Hello,

your're right. With Version 1.5.0 it's not working, but with 1.5.2 it works. 

Thanks
Marcel

**Comment by epugh** [comment]
Same issue got me with 1.5.0, and upgrading worked.  Thank you!
