### ISSUE TITLE
Documentation of a model property with custom (de)-serialization?

### ISSUE THREAD

**Issue by x2b** [swagger-api/swagger-core#1274]
I have a model which has some getters / setters for fields of the type `LocalDateTime`. I do my own (de)-serialization in that case using `JsonSerializer<?>` / `JsonDeserializer<?>`. Essentially I want the API to tell the world that these fields are plain strings following [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). However, in the resulting JSON looks like this:

```
"LocalDateTime" : {
  "type" : "object",
  "properties" : {
    "dayOfMonth" : {
      "type" : "integer",
      "format" : "int32"
    },
    "dayOfWeek" : {
      "type" : "string",
      "enum" : [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
    },
    "dayOfYear" : {
      "type" : "integer",
      "format" : "int32"
    },
    "monthValue" : {
      "type" : "integer",
      "format" : "int32"
    },
    "hour" : {
      "type" : "integer",
      "format" : "int32"
    },
    "minute" : {
      "type" : "integer",
      "format" : "int32"
    },
    "second" : {
      "type" : "integer",
      "format" : "int32"
    },
    "nano" : {
      "type" : "integer",
      "format" : "int32"
    },
    "year" : {
      "type" : "integer",
      "format" : "int32"
    },
    "month" : {
      "type" : "string",
      "enum" : [ "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" ]
    },
    "chronology" : {
      "$ref" : "#/definitions/Chronology"
    }
  }
}
```

This is clearly not what I want. Is there any way to tell swagger (using annotations) about the representation?

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by x2b** [comment]
1.5.0 I guess:

    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      <version>1.5.0</version>
    </dependency>

**Comment by webron** [comment]
Which LocalDateTime is that? Joda or Java 8?
I assume you use Gson for custom serialization and not Jackson?

**Comment by x2b** [comment]
It is `java.time.LocalDateTime`. I use these annotations:

    import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
    import com.fasterxml.jackson.databind.annotation.JsonSerialize;

and these classes for (de)-serialization: 

    import com.fasterxml.jackson.databind.JsonDeserializer;
    import com.fasterxml.jackson.databind.JsonSerializer;

**Comment by webron** [comment]
How do you currently register your custom (de)serializer?

**Comment by x2b** [comment]
Well, I have some `LocalDateTime` data field and I use annotations like this: 

    @ApiModelProperty(value = "The departure time", required = false)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime departureTime;

The deserializer looks like this:

    public class LocalDateTimeDeserializer extends JsonDeserializer<LocalDateTime>{

        @Override
        public LocalDateTime deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            return LocalDateTime.parse(jp.getText());
        }

    }

**Comment by dansim** [comment]
I also face a similar problem, where I want for consumers of the api to expect strings while I internally want to use LocalDate/Time objects. Is there any solution in Swagger for this?

**Comment by fehguy** [comment]
So, the swagger introspection logic does _not_ look into custom deserializers.  Those do the *work* but not expose the structure that they will expose.  So:

* Do not expect the `@JsonDeserialize` to be considered for producing the `swagger.json`
* Do not expect the `@JsonSerialize` to be considered for producing the `swagger.json`

You can easily configure a different handling for `LocalDateTime` by configuring the ModelConverters though.  Please look at this test for an example:

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/model/override/GericModelConverter.java

Just implement the `resolveProperty` to check for the type that you're interested in applying a special conversion to.

**Comment by dansim** [comment]
Nice answer @fehguy this is probably the way to go. But I managed to find a easy solution that fitted my needs:

<code>
Docket docket = ...; 
docket.directModelSubstitute(LocalDate.class, String.class); 
docket.directModelSubstitute(LocalDateTime.class, String.class);
</code>

The problem with this solution though is that when you have costume objects and need to have a mapping to some other data format. And maybe different types of mappings of the same origin datatype. This solution will override all controller methods returning dates and convert them to strings.

**Comment by Mowee** [comment]
@fehguy Can you give me an example on how I can register such an CustomConverter. I created my own CustomConvert by implementing the ModelConvert. But I'm stuck because I don't now how I can register it so it will be used.

**Comment by fehguy** [comment]
@Mowee if you look here in the tests:

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/model/override/ModelPropertyOverrideTest.java#L15

You should see how to add your converter.  Please open a new issue if you still have trouble.

**Comment by krosenvold** [comment]
If google brought you here and another google search led you to the https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/ModelPropertyOverrideTest.java and then class https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/SamplePropertyConverter.java

Note that the if test at line https://github.com/swagger-api/swagger-core/blob/2b7a4f8f058dfbe321f5646b45d04ae5b8917abd/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/SamplePropertyConverter.java#L21 needs to be removed for this to work for path parameters.
