### ISSUE TITLE
ComposedModel without implementation of clone method

### ISSUE THREAD

**Issue by rojeda-desp-lp** [swagger-api/swagger-core#1277]
What is the cause? Is it a bug?

**Comment by webron** [comment]
What?

**Comment by rojeda-desp-lp** [comment]
Sorry for my poor description.

I want use the clone method of all Swagger Models that implement "Model" interface. But i saw that the object "ComposedModel" doesn't implement this method. 
The "AbstractModel" returns null in this case. 

For this reason, I want know if there is a bug.

I am using the clone method for merging of more than one swagger document.

**Comment by webron** [comment]
Fair enough. Feel free to submit a PR for it.

**Comment by despegargcampelo** [comment]
Looks more like a bug than a feature...
+1

**Comment by arosenber** [comment]
+1 and submitting this solution as it removes a bug that's impairing me.

**Comment by webron** [comment]
Solution merged in master, thanks @arosenber.
