### ISSUE TITLE
Is it possible to filter model properties independently for each api?

### ISSUE THREAD

**Issue by Syzygy24** [swagger-api/swagger-core#1279]
I'm running into issues where our POST API functions are formatted something like this
```
@POST
	@Path("/create")
    @ApiOperation(value = "Operation to create a user profile")
    @ApiImplicitParams(@ApiImplicitParam(dataType = "services.profile.integration.models_v1.request.RESTRequestProfile", name = "user", paramType = "body", required=true))
	@Consumes({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
	@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
	public Response createProfile(@Context final HttpContext requestContext, @QueryParam(RequestParameterSet.PARAM_DEBUG) @DefaultValue(RequestParameterSet.PARAM_DEBUG_DEFAULT) final String debug, @Context final UriInfo uriInfo) {
         ...
    }
```
This API function requires a json/xml body to be passed in, but as you can see, there is no actual object in the function definition that I can annotate, so I used an ApiImplicitParam to get around this. Unfortunately, every class associated with profiles has way more fields/variables than are required or permitted by the API.

Swagger is picking up the @xmlelement tags for all of them, and I was wondering if there is a way to filter them on a per-api basis. I initially considered overriding the class, but apart from being confused as to how to do that, I think that would override the class definition whenever I wanted to use it, not just for the create profile API correct? That's problematic because there are APIs that use some of the parameters I want to ignore in createProfile.

I am looking for something that doesn't require me to write my own dummy classes that would be used only to document each POST function with this problem, as I am operating under the constraint that I can't alter the codebase very much. If the best solution is to simply use another tool like the editor at this point then that's fine but I just wanted to know if there's anything I have overlooked in the core.

Thank you

**Comment by webron** [comment]
I'm afraid this is a hard problem, and we currently don't offer a solution for it in swagger-core.

One of the reasons for it is that each model needs a unique name, and even if there was some complicated way of saying 'use this property for that operation', we'd need to generate multiple models, assigning each one its own name, and generating the proper reference (okay, this is the easier part).
We *do* have some model-name manipulation in some cases, but this is somewhat more complicated than those.

**Comment by Syzygy24** [comment]
All right, well thank you for the quick response! I'll try to figure something else out.

**Comment by webron** [comment]
No problem. For future reference, it may be better to ask general questions in the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
