### ISSUE TITLE
docs: quick start still mentions @Api(description…)

### ISSUE THREAD

**Issue by srl295** [swagger-api/swagger-core#1281]
though #1251 explains why the `description` parameter to `@Api()` was deprecated, it's still used in the [quickstart](https://github.com/swagger-api/swagger-core/wiki/Java-JAXRS-Quickstart#annotate-your-resources).

     @Api(value = "/pet", description = "Operations about pets")

**Comment by srl295** [comment]
Looks like the way to set tag descriptions is as per #945

**Comment by webron** [comment]
Thanks, deleted that page. It's no longer relevant.

**Comment by srl295** [comment]
@webron sure. The [page](https://github.com/swagger-api/swagger-core/wiki/Java-JAXRS-Quickstart#annotate-your-resources) says "test" now, though.

**Comment by webron** [comment]
Yes, that's because someone re-created it. Unfortunately, I can't do much about it.
