### ISSUE TITLE
Swagger 1.2 subtypes issue in composition

### ISSUE THREAD

**Issue by sunaina-ishi** [swagger-api/swagger-core#1283]
Hi,

I am using swagger 1.2 spec as we need subTypes information in docs. In my API ,I am able to see all subtype model information when using the superclass as input request. But When I try to wrap the superclass inside another class , then the model definitions of subtypes are missing. For Example,

```java
SuperClass
@ApiModel (discriminator="type" , subtypes = {Cat.class})
Animal{
}
```
Sub class
```java
Cat extends Animal{
}
```
If my REST Api is 

```java
@ApiOperation
public void test (Animal animal){
}
```
then the api docs displays 

```
models :{
Animal :{
subtypes = {Cat}
}

Cat:{
}
}
````
But if suppose I need a wrapper class around Animal ,Say Carnivores class
````
Carnivores{
Animal animal;
}
```
and now my rest API is 
```java
public void test (Carnivores carnivores){
}
```
Now the JSON docs displays only model definition of Animal not Cat.
```
models :{
Animal :{
subtypes = {Cat}
}
}
```
Help will be really appreciated.

**Comment by webron** [comment]
Are you able to upgrade to the latest version of swagger-core?

**Comment by webron** [comment]
Closing due to lack of response. Please reopen if needed.
