### ISSUE TITLE
ApiListingResource initialized field should not be static

### ISSUE THREAD

**Issue by blop** [swagger-api/swagger-core#1286]
Hello,

I'm on a project in which I have multiple instance of ApiListingResource (for multiple ServletContext).

The fact that the initialized field is declared static cause an issue where the second instance is not initialized (and context swagger attribute is still null) but thinks it is. It only works for the first of course.

Could you remove that "static" modifier ?
It's not coherent with the non-static context field.
And there is nothing else static in that class anyway.

Thank you.
Regards.

**Comment by fehguy** [comment]
No need for static.  Thank you.

**Comment by blop** [comment]
Reopened, same issue : https://github.com/swagger-api/swagger-core/issues/1724
