### ISSUE TITLE
Specify "file" return type in jax-rs

### ISSUE THREAD

**Issue by pike1212** [swagger-api/swagger-core#1290]
The Swagger 2.0 spec states that "file" can be used as a primitive return type. For example...

```
responses:
  "200":
    description: Success
      schema:
        type: file
```

However, there is no way to add annotations to a jax-rs service to get a schema with type of "file" to be generated as part of the swagger documentation. 

Ultimately, I want to be able to use the "Try It" function of the swagger-ui to let users download a file. My method currently adds the files byte array to the jax-rs response object, which works when I use curl on the endpoint. I was able to manually add a "Content-Disposition" header to my response and get a Download File link on the UI, but the file is corrupt when I try to open it.

**Comment by webron** [comment]
Can you show what your method signature would look like?

**Comment by pike1212** [comment]
public Response getFile(@ApiParam(value = "id of file to return", required = true) @PathParam(value = "id") int id);

**Comment by webron** [comment]
Okay, I was being optimistic. How do you build the Response?

**Comment by pike1212** [comment]
byte[] file = getFile();
return Response.ok(file).build();

**Comment by okigan** [comment]
+1 also see the same issue, any workaround to specify return type on ApiOperation?

**Comment by IgnasD** [comment]
Has anyone found the solution?

**Comment by fehguy** [comment]
To download a file, set the type to be `byte.class` and set the appropriate `@Produces` annotation such as `application/octet-stream` or the specific media type of the file.  Swagger-ui will handle it correctly.

**Comment by abelsromero** [comment]
I guess this has not been addressed in any way.
Regardless of the client behavior, here swagger is clearly taking a decision on behalf of the developer forcing to use a type when the spec offers different options. For me using `byte` is not viable for the reasons exposed by @IgnasD and it's extremely frustrating there seems to be no way to set the type/format of the return.
