### ISSUE TITLE
Multiple parameters for an http reuqest body

### ISSUE THREAD

**Issue by bstoyanov123** [swagger-api/swagger-core#1300]
I'd like to have my POST request's data sent as a body but only one body is allowed per HTTP request. Is it possible to have multiple parameters that get sent as one body for a request?

**Comment by fehguy** [comment]
You should consider posting a JSON or XML payload--that way you can send as much data as needed.

HTTP does not allow multiple BODY entities in a single post.  It does, though, allow complex POST bodies.

**Comment by bstoyanov123** [comment]
Yes I do have an JSON payload set up.
{
  "BrokerId": 0,
  "Inventories": [
    {
      "ProductionID": "string",
      "Section": "string",
      "Row": "string",
      "StartSeat": "string",
      "EndSeat": "string",
      "InHandDate": "string",
      "IsPDFAvailable": true,
      "IsAllowSplit": true,
      "IsSpeculation": true,
      "Quantity": 0,
      "Barcodes": "string",
      "Cost": 0,
      "Face": 0,
      "Description": "string",
      "InventoryStatus": "string",
      "SupplierTIcketID": 0
    }
  ]
}

However I would like for each field in Inventory array to enter it as its own separate parameter (as if it was a query) instead of directly into the JSON on the body field.

**Comment by webron** [comment]
You can describe the payload, you can't make our tools consider it as separate parameters.
