### ISSUE TITLE
Incorrect int value with exponent prevents parsing

### ISSUE THREAD

**Issue by koh-osug** [swagger-api/swagger-core#1302]
I'm using swagger to generate the REST API form JAX-RS. The generator produces this fragment:

    iccid:
        type: "integer"
        format: "int64"
        minimum: 1.0E18

When I change minimum to 100000000000000000 the validator continues and detects the next error. I'm using the online validator http://online.swagger.io/validator/debug?url= for the verification.

**Comment by webron** [comment]
This is unclear.

You never mention what the error is. It would also help to know what code produces that output.

**Comment by koh-osug** [comment]
I don't know what code is producing it. I'm using the ApiListingResource and see the generated yaml as part of a larger proprietary output when opening a web browser. When this is send to the validator, the validation fails. So, I think there is a unmarshaller producing the YAML output. The string serialization for large numbers seems to have a bug. A short look into the code reveals that Jackson is used. Maybe this problem is related to Jackson. To reproduce this bug a model with a large long value as test data can be used.

**Comment by webron** [comment]
Yes, but what do you mean 'the validation fails'? What error does it give you?

Also, I meant for you to share the code that *you* wrote that translates to that definition.

**Comment by koh-osug** [comment]
Well, there are other issues also with matrix parameters. But I think they are not related to this. The code is proprietary, but I can give a stripped down version:

	@Entity
	public class Profile extends BaseEntity<Profile> {

		@Column(nullable = false, unique = true, updatable = false)
		@DecimalMin(value = "1000000000000000000")
		@Digits(integer = 20, fraction = 0)
		private BigInteger iccid;

		/**
		 * Get the ICCID identifying the profile.
		 *
		 * @return the ICCID identifying the profile.
		 */
		public BigInteger getIccid() {
			return iccid;
		}

		/**
		 * Set the ICCID identifying the profile.
		 *
		 * @param iccid The ICCID identifying the profile.
		 */
		public void setIccid(BigInteger iccid) {
			this.iccid = iccid;
		}

	}

When this is retrieved by a GET REST call in a service the error is produced when Swagger is building the description.

**Comment by webron** [comment]
So a few things.

You're using `BigInteger` which unfortunately gets mistranslated to 'long' in the current version. https://github.com/swagger-api/swagger-core/pull/1171 fixes that and will be part of the upcoming release.

Otherwise, the output you provided is valid. Since you're not saying what the actual validation error you get with it, I can't help you more.

And last, matrix parameters are not supported by Swagger and as such not supported by swagger-core.

**Comment by koh-osug** [comment]
Thanks for the quick response. The validation error is:

[{"level":"error","domain":"validation","keyword":"type","message":"instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"])","schema":{"loadingURI":"http://json-schema.org/draft-04/schema#","pointer":"/properties/minimum"},"instance":{"pointer":"/definitions/Profile/properties/iccid/minimum"}}]

**Comment by webron** [comment]
Okay, that looks like a bug with the validator but we may be able to work around it here.

**Comment by webron** [comment]
Should have added the implementation note - while the `1.0E18` notation is probably valid, we should see if we can enforce Jackson to serialize it as the full number.

**Comment by fehguy** [comment]
this should be addressed in the validator code.  Please open an issue in that project if you're having issues with it still.
