### ISSUE TITLE
Reponse's schema is a property?

### ISSUE THREAD

**Issue by hgwood** [swagger-api/swagger-core#1306]
According to [the Swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#response-object), the Response Object (`io.swagger.models.Response`) has a `schema` property that contains a Schema Object (`io.swagger.models.Model`). However, in swagger-core, `Response#getSchema()` returns a `Property`, not a `Model`. Is that intended or is the implementation incomplete?

**Comment by fehguy** [comment]
It's an oddity in the models that could technically go away.  You can use something called a `RefProperty` which can point to a model, which is how the Response object works.  We'll probably clean this up, but it'll be a breaking change in the models and require a major release.

**Comment by hgwood** [comment]
So if I want to get to the `Model`, I should check that `Response.getSchema() instanceof RefProperty`, then cast it, then get the `ref` and then what? 

Here's the fragment from the [Swagger Pet Store definition](http://petstore.swagger.io/v2/swagger.json) I'm trying to work with:

```json
"responses": {  
  "200": {  
    "description": "successful operation",
    "schema": {  
      "type":"object",
      "additionalProperties": {  
        "type":"integer",
        "format":"int32"
      }
    }
  }
}
```

**Comment by bchazalet** [comment]
to me this is related to #1202 and both together means `getSchema` can return an ObjectProperty which is useless to continue descending the tree as the children are lost.

How does one parse the definition into models at all?

**Comment by bchazalet** [comment]
@hgwood I think you're then supposed to look it up from `swagger.getDefinitions`, i.e. `swagger.getDefinitions(ref.getSimpleRef)` which will get you a `ModelImpl` on which you can call `ModelImpl#getProperties`.

What I still don't understand is whether it works at all with 'object'?

**Comment by hgwood** [comment]
I'm afraid there's nothing that corresponds in `swagger.getDefinitions`. It only contains what's really in the JSON.

Am I to understand that this project doesn't support inline schemas in responses? If so, the README you should definitely mention it, and more generally how much of the spec is supported.

Isn't the fix for this issue as simple as changing the type of `Response.getSchema` from `Property` to `Model`?

**Comment by bchazalet** [comment]
@hgwood I am not sure changing `getSchema` to `Model` is enough because `Model` is defined in terms of `Property` see `Model#Map<String, Property> getProperties();` so at some point you will reach a place where you will find a `ObjectProperty` and run into #1202.

But my understanding of swagger-core and parser is very limited so I might be wrong.

**Comment by hgwood** [comment]
Yes I would soon run into #1202 but I would be able to read top-level properties.

**Comment by fehguy** [comment]
This will change with the 3.0 specification, as parameters, models, and properties will essentially be the same.
