### ISSUE TITLE
SpecFilter throws NPE when processing 'ComposedModel' definitions

### ISSUE THREAD

**Issue by owagould** [swagger-api/swagger-core#1311]
In swagger-core 1.5.0,   I'm getting an NPE when trying to implement my own SwaggerSpecFilter:

```
java.lang.NullPointerException: null
	at io.swagger.core.filter.SpecFilter.filterDefinitions(SpecFilter.java:69) ~[swagger-core-1.5.0.jar:1.5.0]
	at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:54) ~[swagger-core-1.5.0.jar:1.5.0]
	at io.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:98) ~[swagger-jaxrs-1.5.0.jar:1.5.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
```

_io.swagger.core.filter.SpecFilter (line 69)
```
...
67            Model definition = definitions.get(key);
68            Map<String, Property> clonedProperties = new LinkedHashMap<String, Property>();
69            for (String propName : definition.getProperties().keySet()) {
70                Property property = definition.getProperties().get(propName);
...
```

It's happening when the type of  'definition' is 'ComposedModel', which  appears to be  hard-coded to return null on getProperties().  The model being inspected is a sub-classed model.

**Comment by Pallepilla** [comment]
+1

**Comment by lmprice** [comment]
+1

**Comment by fehguy** [comment]
I've verified that this is supported in 1.5.2.  Adding a test to confirm that null definitions don't cause the NPE.

**Comment by mattcarrier** [comment]
I'm still seeing this in 1.5.3-M1.

**Comment by webron** [comment]
1.5.3-M1 is a fairly old version (and unlike what you'd think, it's older than 1.5.2). Give 1.5.3 a try.

**Comment by mattcarrier** [comment]
Confirmed, when I switched from 1.5.3-M1 to 1.5.3 this issue no longer exists.

**Comment by webron** [comment]
Thanks for the confirmtion, @mattcarrier.
