### ISSUE TITLE
Swagger 1.5 skips path parameters which defined in Base resource class.

### ISSUE THREAD

**Issue by C0rWin** [swagger-api/swagger-core#1317]
I have following resources in my project (simplified real case):

First one is the base class which has common property for all REST resources in the project.

```java
public class BaseResource {

    @ApiParam("The Idendifier of entity")
    @PathParam("id")
    private String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
```

1. The Book resource.
```java
@Api(value = "Books", description = "Book management")
@Path("/{id}/v1/books/")
public class BookResource extends BaseResource {

    @GET
    @Path("{name}")
    @Produces("text/plain")
    @ApiOperation(value = "Returns book id and name")
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "Completed Successfully", response = String.class)})
    public String getIt(@ApiParam("The books name") @PathParam("name") final String name) {
        return "Hi there " + name + ", id " + getId();
    }
}
```
1. The Users resource
```java
@Api(value = "Users", description = "Users management")
@Path("/{id}/v1/users/")
public class UserResource extends BaseResource {

    @GET
    @Path("{name}")
    @ApiOperation(value = "Returns user id and name")
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Completed Successfully", response = String.class)})
    public String getName(@ApiParam("User name") @PathParam("name") final String name) {
        return "Hello user " + name + ", id " + getId();
    }

}
```

I would expect to see the {id} parameter in Swagger-UI, while it skipped and not presented, as well there is no such parameter in generated swagger.json. In previous versions of Swagger 1.2 and 1.1 it worked as expected.

This is how it looks like:

<img width="984" alt="screen shot 2015-08-03 at 2 51 01 pm" src="https://cloud.githubusercontent.com/assets/3093578/9036963/2b427e36-39ef-11e5-9055-bb990e7f1ba0.png">

Swagger version I'm using is:
```xml
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jersey-jaxrs</artifactId>
            <version>1.5.3-M1</version>
        </dependency>
```

**Comment by webron** [comment]
Can you test it with the current version? The version is 1.5.1 and the groupId has changed to io.swagger.

**Comment by C0rWin** [comment]
Nope, just tried and got same result.

**Comment by dustin-johnson** [comment]
This issue (or rather #1339) is blocking our upgrade to swagger 1.5.x. How can I aid in a resolution to this issue for the next release?

**Comment by webron** [comment]
@dustin-johnson - you can test if #1360 solves it for you and provide the feedback, that would help.
