### ISSUE TITLE
Feature request: @ApiModelProperty example support number type

### ISSUE THREAD

**Issue by ShijunK** [swagger-api/swagger-core#1318]
I'd like to request a feature which will allow example field of ApiModelProperty support number type. 

For latest release version (1.5.0), if you use example like this:
````
        @ApiModelProperty(dataType = "double", required = true, example = "1234")
	private Double numberField;
````

The generated swagger spec looks like:
````
 "numberField" : {
          "type" : "number",
          "format" : "double",
          "example" : "1349"
        }
````

Which I believe should be:
````
 "numberField" : {
          "type" : "number",
          "format" : "double",
          "example" : 1349
        }
````

**Comment by OscarF** [comment]
Support for booleans would also be nice.

**Comment by rowanhill** [comment]
I think this is a general problem: I would expect the value you put in the example string to be treated as raw JSON, rather than encoded as a string in the swagger.json. It's not type safe, but it would allow numbers, booleans, arrays, even complex objects; strings would be fine, too, but they'd need quotes adding explicitly within the Java string, e.g.:

```java
@ApiModelProperty(example = "\"foo\"")
```

Is that possible?

**Comment by fehguy** [comment]
unfortunately annotations don't support this type of behavior.  We are a bit stuck with the current JLS, unless we decided to put a "meta syntax" in the example field like @rowanhill is proposing.  That could be quite messy to maintain though.

**Comment by rowanhill** [comment]
For what it's worth, [swagger-maven-plugin](http://kongchen.github.io/swagger-maven-plugin/) had [a similar problem](https://github.com/kongchen/swagger-maven-plugin/issues/233) and ended up [allowing raw JSON](https://github.com/kongchen/swagger-maven-plugin/pull/237) like I suggested above.

I'm not quite sure what else you could do. Maybe example could take an Object, which gets JSON serialized to form the example? I imagine that would be a bit cumbersome to use, though.

**Comment by etyrrill** [comment]
I have this problem as well, and I took a stab at fixing it.  I left @ApiModelProperty.example a string, but I changed Property.example to an Object, and wrote custom setters for number and boolean properties.  This relatively minor change fixed the problem for me, and has the benefit of not changing how the annotation is used.

**Comment by frantuma** [comment]
Closing this issue because @etyrrill solution in last comment has been applied in https://github.com/swagger-api/swagger-core/pull/1640; related issues are handled in #1118 and #1681

**Comment by vinayshankar** [comment]
@etyrrill Can you explain how you used Property.example to format the @ApiModelProperty example value? I have the annotation on the property of the class.
`class ClassName {
@ApiModelProperty(name = "name", value = "value", example = "[\"v1\", \"v2\"]")
  private List<String> values;
}`
Now what do I have to do with Property.class and Property.example ?

**Comment by etyrrill** [comment]
Hi @vinayshankar, I don't think you're not going to be able to give an example with a List type field.

**Comment by sheinbergon** [comment]
@etyrrill  so we can't give an example of compound types like Lists,Sets or Map ? 
Not sure if you're one of the maintainers or not , but does anybody have a plan for fixing this or changing the example annotation to an object as well?
Too many issues/prs to keep track of that

**Comment by etyrrill** [comment]
I'm just a user of this library like you. It is an open source project, and you can clone the repo, make enhancements, and make a pull request like I did.

**Comment by JessieGit** [comment]
Seems nobody fixes the @ApiModelProperty example support problem here. Just curious how everybody gets the workaround if it only supports string type?

**Comment by elrob** [comment]
It worked for me once I fully qualified the class. For me:
`dataType = "java.lang.Long", example = "12345678"`
This then renders correctly in Swagger as JSON integer type rather than a string.
I'm using springfox: http://springfox.github.io/springfox/docs/current/#overriding-property-datatypes

**Comment by manjambo** [comment]
I think this is a similar issue:

```
@ApiModelProperty(required = true, example = "2020", dataType = "java.lang.String")
    private final String year;
```
gives me 
```
...
"year": 2020
...
```
but I'd like
```
...
"year": "2020"
...
```
