### ISSUE TITLE
Integrating Swagger with jersey jaxrs sample project

### ISSUE THREAD

**Issue by catchaag** [swagger-api/swagger-core#1320]
Hi,

I have written a sample application(1 simple Rest Api) using jersey jaxrs. I am trying to integrate swagger with this application. I have followed all the steps given in the swagger guide. But i dont seem to get the swagger.json or swagger.yaml file. Here is my web.xml looks like

![image](https://cloud.githubusercontent.com/assets/13641784/9059896/e3a59e40-3acb-11e5-94d8-796ea7b32800.png)

I have deployed my application on tomcat server and tomcat logs does not show any errors.It seems to be starting up clean.

Any help is appreciated.

**Comment by webron** [comment]
In the future, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) for general support questions.

Which URL did you try using for the swagger.json?

**Comment by catchaag** [comment]
Okay..sorry i did not know that.. I tried my application URL http://localhost:8080/RestJersey/rest/hello

**Comment by webron** [comment]
Have you tried http://localhost:8080/RestJersey/rest/swagger.json?

**Comment by catchaag** [comment]
Thanks a lot webron.. This worked... 
I needed 1 more help.. 
My requirement is to get swagger.json and swagger.yaml file as part of my build process.
Can you guide me on how I can get these swagger files as part of the build process.

**Comment by webron** [comment]
You'd have to use a third party tool like [swagger-maven-plugin](https://github.com/kongchen/swagger-maven-plugin).

**Comment by catchaag** [comment]
thanks a lot! I will try this...
