### ISSUE TITLE
Can swagger load api documentation from configuration/properties?

### ISSUE THREAD

**Issue by catchaag** [swagger-api/swagger-core#1336]
Hi,

I am working on builiding rest apis using jersey jax-rs. I have integrated swagger to get well defined documentation for these apis.

I have seen it from the guide that we need to write all api docs in the annotation (ApiOperation,ApiResponses,@ApiResponse). Is there a way in swagger to load these documentation things (like apiresponse,apioperation etc) from a configuration/properties file?

Please advise.

Quick help is much appreciated.

Thanks

**Comment by webron** [comment]
You asked the same question in the google group and got an answer there.
