### ISSUE TITLE
Not Scanning Base Class Parameters

### ISSUE THREAD

**Issue by lemoncolly** [swagger-api/swagger-core#1339]
I am having an issue, where Swagger is not picking up parameters on a Java base class.

I have a simple REST resource:

	package lemon.resources;

	import io.swagger.annotations.Api;
	import io.swagger.annotations.ApiOperation;
	import io.swagger.annotations.ApiParam;
	import io.swagger.annotations.ApiResponse;
	import io.swagger.annotations.ApiResponses;

	import java.net.HttpURLConnection;

	import javax.ws.rs.GET;
	import javax.ws.rs.Path;
	import javax.ws.rs.Produces;
	import javax.ws.rs.QueryParam;
	import javax.ws.rs.core.MediaType;
	import javax.ws.rs.core.Response;

	import lemon.model.Model;

	@Path("lemon")
	@Api(value = "lemon")
	@Produces(MediaType.APPLICATION_JSON)
	public class LemonResource extends BaseResource
	{

		@GET
		@ApiOperation(value = "Get Lemon", notes = "Lemon Information.", response = String.class)
		@ApiResponses(value = {
			@ApiResponse(code = HttpURLConnection.HTTP_OK, message = "Lemon Success"),
			@ApiResponse(code = HttpURLConnection.HTTP_INTERNAL_ERROR, message = "Bad Lemon") })
		public Response getLemon(
			@ApiParam(value = "Lemon") @QueryParam(value = "lemon") String lemon)
		{
			Model model = new Model();
			model.setKey("1234567890");
			model.setValue("Testing");

			// Map back the response
			return Response.ok(model).build();
		}
	}

This class extends a 'Base Resource', which simply contains a number of common query parameters. The idea here is that they can be applied to all endpoints in our code (this example is a simplified example to test out). I also tried making the parameters public:

	package lemon.resources;

	import io.swagger.annotations.Api;
	import io.swagger.annotations.ApiParam;

	import javax.ws.rs.QueryParam;

	public class BaseResource
	{
		/**
		 * Global query parameter for requesting mock data.
		 */
		@ApiParam(value = "Test Query Param")
		@QueryParam("test")
		protected boolean test;

		/**
		 * Global query parameter for requesting save of service response data.
		 */
		@ApiParam(value = "Save Query Param")
		@QueryParam("save")
		protected boolean save;
	}

However, Swagger does not pick up the parameters. The parameters work fine in the JAX-RS setup though. The swagger.json looks as follows:

	{
	   "swagger":"2.0",
	   "info":{
		  "version":"@BUILD_VERSION@"
	   },
	   "basePath":"/Lemonade/resources",
	   "tags":[
		  {
			 "name":"lemon"
		  }
	   ],
	   "paths":{
		  "/lemon":{
			 "get":{
				"tags":[
				   "lemon"
				],
				"summary":"Get Lemon",
				"description":"Lemon Information.",
				"operationId":"getLemon",
				"produces":[
				   "application/json"
				],
				"parameters":[
				   {
					  "name":"lemon",
					  "in":"query",
					  "description":"Lemon",
					  "required":false,
					  "type":"string"
				   }
				],
				"responses":{
				   "200":{
					  "description":"Lemon Success"
				   },
				   "500":{
					  "description":"Bad Lemon"
				   }
				}
			 }
		  }
	   }
	}

Swagger Version: io.swagger » swagger-jaxrs » 1.5.2
(Also tried with 1.5.0 and 1.5.1)

**Comment by lemoncolly** [comment]
I realize this issue is very similar to #1317.

**Comment by fehguy** [comment]
if you could, please send a PR with a test in it that exhibits the problem.

**Comment by lemoncolly** [comment]
Let me check up on how to do a PR (haven't done one before).
And sorry for the delay (new child arrival has knocked me off track).

**Comment by webron** [comment]
@lemoncolly - congrats on the new child!

Can you test the latest snapshot first (1.5.4-SNAPSHOT)?

**Comment by lemoncolly** [comment]
I am getting a missing POM exception for the snapshot, when building.
Am I missing something?

**Comment by lemoncolly** [comment]
Got it, and re-tested.
Looks like the issue is now resolved with the latest snapshot.

**Comment by webron** [comment]
Closing as resolved in the snapshot.
