### ISSUE TITLE
Only one operation is allowed for given path and http method.

### ISSUE THREAD

**Issue by buri17** [swagger-api/swagger-core#1341]
JAX-RS spec 2.0 allows you to define more than one method for a combination of path and http method.

For example, we can define one method to handle multipart/form-data and
another method to handle application/json for same path as follows:

```java

@Path("example")
public class ExampleResource {
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public SomeResponse methodA(
            @FormDataParam("paraemter") SomeParameter parameter,
            @FormDataParam("data") InputStream in) {
        ...
    }

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public SomeResponse methodA(SomeParameter parameter) {
       ...
    }

```

However, the io.swagger.models.Path class can remember only one operation
for the specified http method.

**Comment by webron** [comment]
That's one of the restrictions of the Swagger specification. You can't have multiple operations on a single path+verb combination.

**Comment by fehguy** [comment]
As @webron said, this is by design.  Please look at the swagger-spec and file any enhancements you are looking for in that project.
