### ISSUE TITLE
Not scanning model with Generic Type

### ISSUE THREAD

**Issue by kiennguyen** [swagger-api/swagger-core#1344]
Hi, please look at my sample:
I have an abstract class with type variable: T
```java
public abstract class ApiCrudRoute<T extends AbstractEntity, R extends ApiResponse> {
    protected ApiCrudService<T> service;

    @POST
    @ApiOperation(value = "Create")
    public Response doCreate(
            @ApiParam(value = "Create object", required = true) T entity) throws Exception {
        T newEntity = service.create(entity);
        return getResponse(getApiContext().getRequestId(), Status.CREATED, newEntity).build();
    }    
}

//Inherited class:
@Path("/api/users")
@Api(value = "/users")
@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
public class UserApiRoute extends ApiCrudRoute<User, UserApiResponse> {
}

//The model inherited from Abstract Model:
@XmlRootElement
@ApiModel(value = "User")
@XmlAccessorType(XmlAccessType.FIELD)
public class User extends AbstractEntity {
    public String name;
}

public abstract class AbstractEntity implements Serializable {
    public String id;
}
```

We want to have Swagger API "POST /api/users" with model:
{"id":"","name":""}

But we got the empty model {}

**Comment by webron** [comment]
Which version of swgger-core have you tried?

**Comment by kiennguyen** [comment]
I am using the version 1.5.0: https://github.com/swagger-api/swagger-core/commits/v1.5.0.
Did you have the fix in other versions?

**Comment by webron** [comment]
We've made a change but I'm not sure which version it got into. Can you try 1.5.2?

**Comment by kiennguyen** [comment]
I tried the 1.5.2: https://github.com/swagger-api/swagger-core/tree/v1.5.2 and got the same error.
Do you remember the commit ID or do I need to configure more things?

**Comment by webron** [comment]
Oh, I definitely don't remember commit IDs. For *anything*. The PR may have not resolved this specific issue. Guess we'll have to look into it.

**Comment by johnpaul2** [comment]
I can confirm this issue. 
In our case the following commit in our fork fixed it: https://github.com/synapplix/swagger-core/commit/88243a085677f63299e277ec36f30c8fef859de4
I will not send a pull request as I guess there must be an nicer solution for the problem...

**Comment by kiennguyen** [comment]
I cherry-picked your commit and it worked for me. Thank Lugaru1234
