### ISSUE TITLE
ObjectProperty lacks additionalProperties

### ISSUE THREAD

**Issue by 2rs2ts** [swagger-api/swagger-core#1349]
And yet, the petstore example has an operation with a response as an `ObjectProperty` with `additionalProperties` defined on it.

```json
"/store/inventory": {
    "get": {
        "tags": ["store"],
        "summary": "Returns pet inventories by status",
        "description": "Returns a map of status codes to quantities",
        "operationId": "getInventory",
        "produces": ["application/json"],
        "parameters": [],
        "responses": {
            "200": {
                "description": "successful operation",
                "schema": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            }
        },
        "security": [{
            "api_key": []
        }]
    }
}
```

Shouldn't this be added to the `ObjectProperty`?

**Comment by fehguy** [comment]
I will add some tests around this, but as-is, it should deserialize this into a map with key type `string` and value `java.lang.Integer`

**Comment by fehguy** [comment]
The deserializer handles addtional properties, see tests.

**Comment by 2rs2ts** [comment]
Oh, so it deserializes to a `MapProperty`, not an `ObjectProperty`. Got it.

**Comment by dolmen** [comment]
`additionalProperties` can be either an object or a boolean value.
Boolean do not seem to be handled correctly => #1437

**Comment by ahl** [comment]
sorry to dredge up this old thread, but @fehguy can I ask why this is the right behavior? It seems like it's legal to have swagger like this:

```
"schema": {
    "type": "object",
    "properties": { 
        "foo" {
            "type": "string"
        }
    },
    "additionalProperties": {
        "type": "integer",
        "format": "int32"
    }
}
```

If that is in fact legal, it would be useful to have additionalProperties on the ObjectProperty.

And forgive me if this is answered elsewhere, but what is the purpose of the MapProperty and/or how does it relate to the Swagger 2.0 spec? Thanks.
