### ISSUE TITLE
Make 1.5.x swagger-core and swagger-jarxs OSGi-enabled

### ISSUE THREAD

**Issue by elakito** [swagger-api/swagger-core#1361]
As discussed in this following thread, I am attaching a PR to this issue ticket shortly.
https://groups.google.com/forum/#!topic/swagger-swaggersocket/6w-xuHmTzvQ

**Comment by webron** [comment]
Where's the PR? ;)

**Comment by elakito** [comment]
Just wanted to create the issue number to prepare for a commit ;-)
I wanted to think about one thing before submitting a PR. That is about the lower range for the guava dep.

Because of the current situation between SMX's org.reflections-0.9.9 bundle and guava-18.0 bundle not playing each other on OSGi (the problem that I mentioned in the thread), I am thinking of building swagger-core and swagger-jaxrs with guava 18.0 but explicitly setting the allowed lower range of guava down to 15.0 so that when using the out-of-the box org.reflections-0.9.9 bundle, everyone can wire to guava 15.0. This can be switched back to 18.0 once a newer version of org.reflection bundle becomes available.

Alternatively, if we keep guava's lower range at 18.0, we will need a version of org.reflections-0.9.9 that can be wired to guava-18.0, This can be either done dynamically by using karaf's special wrap installer to set/overwrite its imports manually or by physically creating a new version of org.reflections-0.9.9 bundle. I'll ping the SMX guy tomorrow, as I haven't got any reply to my message posted on their ML.

How do you think? We can decide it by tomorrow.

thanks.
regards, aki

**Comment by elakito** [comment]
Hi Ron,
The SMX guys have just patched their org.reflections bundles. So, the next release versions 0.9.9_2 and 0.9.10_2 will work with guava-18.0. So, we can keep the lower range of swagger-core/jaxrs to the current default 18.0.
regards, aki

**Comment by webron** [comment]
Cool, thanks for the update.

**Comment by elakito** [comment]
Hi Ron,
could you merge the above PR?
So that we can use the OSGI-enabled version from the snapshot repo?
thanks.
regards, aki

**Comment by webron** [comment]
Done, give it a try.

**Comment by elakito** [comment]
Hi Ron,
great. It's working nicely. ;-)
I added a working demo sample in cxf's samples distro
https://github.com/apache/cxf/tree/master/distribution/src/main/release/samples/jax_rs/description_swagger2_osgi

Before closing this ticket, I have a questions (my PR mentioned this briefly).

Currently, I included the swagger's OSGi deployment descriptors in a temporary features.xml file in the demo project itself to make the installation of swagger bundles simple. This file looks like this

https://github.com/apache/cxf/blob/master/distribution/src/main/release/samples/jax_rs/description_swagger2_osgi/src/test/features/features.xml

The first two feature entries demo-swagger-core and demo-swagger-jaxrs install the swagger bundles and the necessary bundles. I think it would be practical to have these descriptors defined in a sub project of the swagger-core project so that everyone can use them from there and does not need to define them on their own as done in the above features.xml.

How do you think? If that sound okay, I can open a new ticket to work on it.

I can also add a non-cxf sample in swagger-samples.

thanks.
regards, aki
p.s. I could close this ticket but opted to keep it open until you have a chance to read my message above.

**Comment by webron** [comment]
Isn't that karaf-specific though? How would that affect other OSGi implementations?

My main concern with it is maintenance. We really have no experience or knowledge in OSGi, and we need to understand what/how to maintain.

**Comment by elakito** [comment]
Hi Ron,
Yes. It is an XML descriptor used by Karaf.

I will discuss this with the ServiceMix/Karaf people. We have a general need for other features as well. So, it would be an option to define them somewhere in the ServiceMix/Karaf domains instead (some common features are defined there).

I'm closing this ticket.

Thanks.
regards, aki
