### ISSUE TITLE
Vendor Extensions for Parameters

### ISSUE THREAD

**Issue by mar612** [swagger-api/swagger-core#1365]
I am looking to add a vendor extension to a parameter, 
i.e. @ApiParam( ... extensions = {@Extension(... properties = {@ExtensionProperty(...)})})

I have read the Swagger spec, and it would seem to indicate that it is possible, but from what I can tell, @ApiParam lacks the functionality.  Have I misunderstood the spec?  Or has it simply not been implemented yet?  Or is it implemented, and I'm not doing it properly?  Thanks.

**Comment by mar612** [comment]
Any ideas?

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#extension - the wiki says it's not supported yet.
