### ISSUE TITLE
Wrong default value is generated for boolean

### ISSUE THREAD

**Issue by fennekit** [swagger-api/swagger-core#1368]
In the snippet below the yaml and json generated by swagger-core is not correct according to the editor.swagger.io. The default value for the booleans are generated as "false" instead of false. The error that is given is "Not a valid boolean: false"

```java
	@GET
	@ManagedAsync
	@ApiOperation(value = "Get ships in area",
    	notes = "Get ships",
    	response = ShipInfo.class,
    	responseContainer = "List")
	@ApiResponses(value = { 
			  @ApiResponse(code = 404, message = "No ships found") })
	public void allShipsInBoundingbox(
			@ApiParam(value = "Maximum Latitude", required = false) @QueryParam("topLeftLat") Double topLeftLat,
			@ApiParam(value = "Minimum Longitude", required = false) @QueryParam("topLeftLon") Double topLeftLon,
			@ApiParam(value = "Minimum Latitude", required = false) @QueryParam("bottomRightLat") Double bottomRightLat,
			@ApiParam(value = "Maximum Longitude", required = false) @QueryParam("bottomRightLon") Double bottomRightLon,
			@DefaultValue("false") @QueryParam("optin") Boolean optIn,
			@DefaultValue("false") @QueryParam("showAged") Boolean showAged,
			@Suspended final AsyncResponse response) {
```
```
  /ship:
    get:
      summary: "Get ships in area"
      description: "Get ships"
      operationId: "allShipsInBoundingbox"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "topLeftLat"
        in: "query"
        description: "Maximum Latitude"
        required: false
        type: "number"
        format: "double"
      - name: "topLeftLon"
        in: "query"
        description: "Minimum Longitude"
        required: false
        type: "number"
        format: "double"
      - name: "bottomRightLat"
        in: "query"
        description: "Minimum Latitude"
        required: false
        type: "number"
        format: "double"
      - name: "bottomRightLon"
        in: "query"
        description: "Maximum Longitude"
        required: false
        type: "number"
        format: "double"
      - name: "optin"
        in: "query"
        required: false
        type: "boolean"
        default: "false"
      - name: "showAged"
        in: "query"
        required: false
        type: "boolean"
        default: "false"
      responses:
        404:
          description: "No ships found"
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ShipInfo"
```

**Comment by webron** [comment]
Yup, that's indeed a bug. Which version of swagger-core have you tried it with?

**Comment by fennekit** [comment]
I am using 1.5.0

**Comment by webron** [comment]
While I seriously doubt it's been resolved, can you give 1.5.3 a try?

**Comment by fennekit** [comment]
Am trying right now. Namespace have changed....

**Comment by webron** [comment]
Not from 1.5.0 - unless you meant one of the Milestone versions (M1, M2, M3). 1.5.0 (final) already has a namespace change. In any case, if you're on any of the milestones, I'd highly recommend upgrading. Thanks for giving it a try.

**Comment by fennekit** [comment]
Is there a mvn package for 1.5.3?

**Comment by webron** [comment]
yup, just change the `groupId` from `com.wordnik` to `io.swagger`.

**Comment by fennekit** [comment]
Tried the 1.5.3. Same issue

**Comment by webron** [comment]
Okay, thanks for the confirmation. We'll have to look into it.

**Comment by wsalembi** [comment]
Please look into the other primitive types too. Too bad JAX-RS @DefaultValue only uses strings, so conversions are needed.

```
 @QueryParam("page") @DefaultValue("1") @ApiParam(value = "Page to be returned") Integer page
```
generates 
```
      parameters:
        - name: page
          in: query
          description: 'Page to be returned'
          type: integer
          default: '1'
          format: int32
```

the default should be without quotes.

**Comment by asicignano** [comment]
This issue appears to have been fixed for Boolean types in the latest version. However, (unless I am mistaken) the issue still exists for other types, such as integer, as reported by @wsalembi.

Can you confirm that this issue still exists?

**Comment by webron** [comment]
@wsalembi, @asicignano - if the issue indeed exists for other types as well, please open a new ticket for it. The PR dealt with the issue as it was reported, and at least for the sake of documentation, I'd rather we resolve other types in a new ticket rather than opening this one. It should work for at least some other types, even if not all.

**Comment by asicignano** [comment]
Thank you for the response. I can appreciate the desire to keep the PRs
clean for the sake of documentation.

I have created a new ticket (
https://github.com/swagger-api/swagger-core/issues/1472) to look into the
issue with integers specifically.

Thank you,
Anthony Sicignano
