### ISSUE TITLE
Add path property to @ApiOperation

### ISSUE THREAD

**Issue by rspuler73** [swagger-api/swagger-core#1370]
I'm implementing a REST API which does not use a JAX-RS implementation.

There are annotations like @ApiImplicitParam which are intended to use swagger for non JAX-RS services. (as documented here https://github.com/swagger-api/swagger-core/wiki/Annotations#apiimplicitparam-apiimplicitparams)

It would be nice if we also had the possiblity to omit the  javax.ws.rs.Path annotation for a service method and provide the path instead as a property of the @ApiOperation annotation.

**Comment by webron** [comment]
Do you use any existing REST framework or did you write one of your own?

**Comment by rspuler73** [comment]
We use wicket as web framework and the wicket REST extension which is not a JAX-RS implementation.
Looks to me that the dependency on the @Path annotation is the only obstacle that swagger-core can not be used in my case.

**Comment by webron** [comment]
Well, no, it's not the only obstacle. In any case, I don't think we're going to add it to `@ApiOperation`, and it would require more work in general with a specific Reader (much like the one we're creating for generic servlets). It's unlikely there's going to be an out-of-the-box solution here. You can create your own annotation and produce your own Reader if needed.

**Comment by rspuler73** [comment]
Ok. Thanks anyway. Does this reader for generic servlets already exist? The only Reader I can find in the source code is `io.swagger.jaxrs.Reader` which obviously relies on JAX-RS annotations.

**Comment by webron** [comment]
We're in the process of migrating it.

**Comment by webron** [comment]
At the moment, we're not looking to add support for additional frameworks. The support for servlets as it's been before is included in 1.5.4.
