### ISSUE TITLE
Swagger file generation issue with empty paths

### ISSUE THREAD

**Issue by wsalembi** [swagger-api/swagger-core#1375]
JAX-RS to Swagger generates a swagger.json file not valid according to the specification.

```
@Path("/")
@Api
public class MyResource {

    @GET
    @ApiOperation("List all possible links in my API")
    public Response links() {
        return Response.ok("...").build();
    }
}
```
generates the following Swagger fragment

```
  "paths" : {
    "" : {
      "get" : {
        "summary" : "List all possible links in my API",
        "description" : "",
        "operationId" : "links",
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
```

The path should start with a slash. See http://swagger.io/specification/#pathsObject

**Comment by webron** [comment]
This is related to #1189. Make sure you use 1.5.1 or above.

**Comment by webron** [comment]
@wsalembi - did you try upgrading?

**Comment by wsalembi** [comment]
Yes, I tried 1.5.3 but it didn't resolve the issue. Forgot to mention I use com.github.kongchen:swagger-maven-plugin. I traced the error down to some code in the plugin, so I'll open the issue there.
