### ISSUE TITLE
Update javadocs

### ISSUE THREAD

**Issue by wsalembi** [swagger-api/swagger-core#1376]
The javadoc publised an the swagger documentation site seems outdated
http://docs.swagger.io/swagger-core/apidocs/

**Comment by webron** [comment]
http://docs.swagger.io/swagger-core/v1.5.0/apidocs/

**Comment by webron** [comment]
Current javadocs will always be deployed at http://docs.swagger.io/swagger-core/current/apidocs/ from now on.

**Comment by wsalembi** [comment]
Can you remove the old link http://docs.swagger.io/swagger-core/apidocs/ so it gets removed from Google's indexes?

**Comment by webron** [comment]
Unfortunately there are dependencies on it, so I can't.

**Comment by wsalembi** [comment]
Nothing that URL redirection could resolve?

301 Moved Permanently -> http://docs.swagger.io/swagger-core/current/apidocs/
