### ISSUE TITLE
Support javax.ws.rs.core.Link

### ISSUE THREAD

**Issue by wsalembi** [swagger-api/swagger-core#1380]
When the javax.ws.rs.core.Link class is used as a response header, Swagger generates a Schema object for that class interpreted as a simple POJO. Instead it should use a string type with a specific format, e.g link (RFC 5988)

Use of Link class

```
@ApiOperation(value = "List API links", code = 200, response = Link.class, responseHeaders = {
        @ResponseHeader(name = "Link", response = Link.class)
})
```

Schema object generated

```
    "Link" : {
      "type" : "object",
      "properties" : {
        "uri" : {
          "type" : "string",
          "format" : "uri"
        },
        "uriBuilder" : {
          "$ref" : "#/definitions/UriBuilder"
        },
        "rel" : {
          "type" : "string"
        },
        "rels" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "type" : {
          "type" : "string"
        },
        "title" : {
          "type" : "string"
        },
        "params" : {
          "type" : "object",
          "additionalProperties" : {
            "type" : "string"
          }
        }
      }
    },
    "UriBuilder" : {
      "type" : "object"
    }
```

**Comment by driverpt** [comment]
+1

**Comment by driverpt** [comment]
Do we have any ETA on this ?

**Comment by webron** [comment]
There is none. Please consider submitting a PR to add support.

**Comment by driverpt** [comment]
@webron , got any suggestions for me where to start? I already have a Custom Jackson JsonSerializer for Link, how do i include it in the swagger-maven-plugin ?

**Comment by fehguy** [comment]
In the 3.0 spec, this will become first class.

**Comment by driverpt** [comment]
@fehguy , what's the ETA on 3.0 Spec ?

**Comment by fehguy** [comment]
Timing depends on the whole OAI technical group, not just me.  I suggest following [OpenAPI Spec](https://twitter.com/OpenApiSpec) on Twitter for timing announcements.
