### ISSUE TITLE
run two swaggers in one tomcat context

### ISSUE THREAD

**Issue by crazySocket** [swagger-api/swagger-core#1384]
I have REST service big enough to distinguish admin and user parts. My administrator wants to have them separate. You can do that by deploying application two times with differently configured web.xml. Unfortunately, this solution is disliked.

So, I have one context on tomcat. I configure web.xml like this (necessary details only)
```
<servlet>
    <servlet-name>restServiceAdmin</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
        <init-param>
            <param-name>jersey.config.server.provider.packages</param-name>
            <param-value>some.package.admin</param-value>
        </init-param>
</servlet>

<servlet>
    <servlet-name>restServiceUser</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
        <init-param>
            <param-name>jersey.config.server.provider.packages</param-name>
            <param-value>some.package.user</param-value>
        </init-param>
</servlet>

<servlet-mapping>
    <servlet-name>restServiceAdmin</servlet-name>
    <url-pattern>/rest/admin/*</url-pattern>
</servlet-mapping>

<servlet-mapping>
    <servlet-name>restServiceUser</servlet-name>
    <url-pattern>/rest/user/*</url-pattern>
</servlet-mapping>

<servlet>
    <servlet-name>SwaggerBootstrapAdmin</servlet-name>
    <servlet-class>io.swagger.api.util.BootstrapAdmin</servlet-class>
    <load-on-startup>1</load-on-startup>
</servlet>
<servlet>
    <servlet-name>SwaggerBootstrapUser</servlet-name>
    <servlet-class>io.swagger.api.util.BootstrapUser</servlet-class>
    <load-on-startup>2</load-on-startup>
</servlet>
```

Although, boostrap servlets have appropriate base paths and package resources set, when I download swagger.json I get definition configured in BootstrapUser. The last SwaggerBootstrap to start is the one to set contents of swagger.json regardless of how I obtain it (via /rest/admin/swagger.json or /rest/user/swagger.json).

I would like /rest/admin/swagger.json or /rest/user/swagger.json to return definitions of resources some.package.admin, some.package.user accordingly. My question is: is it possible to achieve the result I intend in swagger at all?

**Comment by webron** [comment]
As it is written right now it *may* be possible, but it's not trivial. @fehguy may have more info on that.

**Comment by crazySocket** [comment]
I have created pull request #1397 with changes that solve above issue.

**Comment by fehguy** [comment]
fixed by https://github.com/swagger-api/swagger-core/commit/8031d514f2487e26f73b080a339c993b1964ec61
