### ISSUE TITLE
add multipart form upload file, swagger generate json error

### ISSUE THREAD

**Issue by wangzilong** [swagger-api/swagger-core#1387]
Hi all:
 I use this example https://github.com/swagger-api/swagger-core/tree/v1.3.12/samples/java-jersey2-guice,
add this method in PetResource.java: 
```java
    @POST
    @Path("/{petId}/uploadImage")
    @Consumes({MediaType.MULTIPART_FORM_DATA})
    @Produces({MediaType.APPLICATION_JSON})
    @ApiOperation(value = "uploads an image")
    public Response uploadFile(
            @ApiParam(value = "ID of pet to update", required = true) @PathParam("petId") Long petId,
            @ApiParam(value = "Additional data to pass to server") @FormDataParam("additionalMetadata") String testString,
            @ApiParam(value = "file to upload") @FormDataParam("file") InputStream inputStream,
            @ApiParam(value = "file detail") @FormDataParam("file") FormDataContentDisposition fileDetail) {
        return Response.status(200).entity("true").build();
    }
```
but the scanner generate json is :
```json
...
{
    "path": "/pet/{petId}/uploadImage",
    "operations": [
        {
            "method": "POST",
            "summary": "uploads an image",
            "notes": "",
            "type": "void",
            "nickname": "uploadFile",
            "produces": [
                "application/json"
            ],
            "consumes": [
                "multipart/form-data"
            ],
            "parameters": [
                {
                    "name": "petId",
                    "description": "ID of pet to update",
                    "required": true,
                    "type": "integer",
                    "format": "int64",
                    "paramType": "path",
                    "allowMultiple": false
                },
                {
                    "name": "body",
                    "description": "file detail",
                    "required": false,
                    "type": "FormDataContentDisposition",
                    "paramType": "body",
                    "allowMultiple": false
                }
            ]
        }
    ]
}
...
```
some thing not work, and miss some parameters.
please help me.

**Comment by webron** [comment]
Any reason you're using 1.3.12?

**Comment by wangzilong** [comment]
Yes, I am using com.wordnik:swagger-jersey2-jaxrs_2.10:1.3.12

**Comment by webron** [comment]
Yes, but why do you use that version and not the latest?

**Comment by wangzilong** [comment]
I'm sorry. I will try the latest right now.

**Comment by webron** [comment]
Thanks, please keep us posted.

**Comment by wangzilong** [comment]
I can not find the example of swagger-jersey2-guice in the latest version, can you give it to me. Thank you

**Comment by webron** [comment]
Samples have migrated - https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey2-guice

**Comment by wangzilong** [comment]
I have try this project last week.
When I add the same method in PetResource.java.
it will return JSON is : 
...
{
    "post": {
        "tags": [
            "pet"
        ],
        "summary": "uploads an image",
        "description": "",
        "operationId": "uploadFile",
        "consumes": [
            "multipart/form-data"
        ],
        "produces": [
            "application/json"
        ],
        "parameters": [
            {
                "name": "petId",
                "in": "path",
                "description": "ID of pet to update",
                "required": true,
                "type": "integer",
                "format": "int64"
            },
            {
                "in": "body",
                "name": "body",
                "description": "Additional data to pass to server",
                "required": false,
                "schema": {
                    "type": "string"
                }
            },
            {
                "name": "file",
                "in": "formData",
                "description": "file to upload",
                "required": false,
                "type": "file"
            },
            {
                "in": "body",
                "name": "body",
                "description": "file detail",
                "required": false,
                "schema": {
                    "$ref": "#/definitions/FormDataContentDisposition"
                }
            }
        ],
        "responses": {
            "default": {
                "description": "successful operation"
            }
        }
    }
}
...
But the FormDataContentDisposition be generated in JSON. 
Can you teach me how to deal with it?

**Comment by webron** [comment]
Did you update to the latest version?

**Comment by wangzilong** [comment]
Yes, I download this example project, then add those code and run it.

**Comment by webron** [comment]
The samples are not updated with the latest version. Make sure to update the dependency version, as there was a related bug that was solved in a recent version.

**Comment by wangzilong** [comment]
OK, thanks

**Comment by wangzilong** [comment]
Hi webron:
it does not work, the FormDataContentDisposition still in  JSON.
I only add register(MultiPartFeature.class). in Application.java
Need I add other configuration？

**Comment by webron** [comment]
You're using Jersey 2, right?

**Comment by wangzilong** [comment]
Yes， Jersey's version is 2.21

**Comment by webron** [comment]
Okay, we'll have to look into it.

**Comment by wangzilong** [comment]
Thank you very much.

**Comment by fehguy** [comment]
Can you share your dependencies?

**Comment by wangzilong** [comment]
I have push the code to https://github.com/wangzilong/java-jersey2-guice.git
pom.xml : https://github.com/wangzilong/java-jersey2-guice/blob/master/pom.xml

**Comment by wangzilong** [comment]
Thanks for fixing this bug so quickly.
I am a git newer, can you tell me which branch can get the new code?

**Comment by agusgr** [comment]
Hi @wangzilong, I think that the changes are still not integrated.

By the way, we are dealing with a similar situation in our solution (we are using Apache CXF but I think is similar) and our solution is to use @ApiImplicitParam to generate the swagger docs and "hide" the @ApiParam by using a custom SwaggerSpecFilter. Here [1] you can find an example (is scala but I think is easy to understand).

Hope this can help you,

[1] http://stackoverflow.com/questions/22812365/how-to-hide-a-parameter-in-swagger

**Comment by webron** [comment]
@agusgr - by the way, in general, if you're looking to hide a parameter entirely, you can now use `@ApiParam#hidden()` to set it.

**Comment by oussemamzoughi** [comment]
can someone post here a json file with an upload-file that i can use in swagger-codegen ?
Thanks
