### ISSUE TITLE
Remove legacy docs, or make it clear that they're old

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1399]
https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup

Seems to be picked up a lot by google indexes.  It's not clear _in_ the page, though that it's for the older version of swagger.

**Comment by webron** [comment]
Unfortunately, due to some obligations we cannot remove the legacy docs.

I've added a reference at the top of each page to the equivalent new version of it... in a way that's kind of hard to miss.

**Comment by fehguy** [comment]
Just modify hem so it's clear. A banner at the top, etc, but right now, this is causing problems for prospective users as Google has it indexed higher than the current docs.

**Comment by webron** [comment]
That's exactly what I did for all the relevant pages (as mentioned in the previous comment):

<img width="687" alt="screenshot 2015-09-08 17 07 22" src="https://cloud.githubusercontent.com/assets/241629/9736812/18fe08de-564c-11e5-9095-226ac80d9fc7.png">

What's missing?
