### ISSUE TITLE
Property defaultValue is missing on SerializableParameter 

### ISSUE THREAD

**Issue by dilipkrish** [swagger-api/swagger-core#1402]
Is there a reason why the default value property on [AbstractSerializableParameter.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java#L137-L143) is not present on the [SerializableParameter interface](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/parameters/SerializableParameter.java)

Is this an oversight? It seems like we need to downcast to AbstractSerializableParameter in order to set the value :-(

**Comment by fehguy** [comment]
I believe that was to support `array` types.
