### ISSUE TITLE
Swagger-core does not provide example annotation

### ISSUE THREAD

**Issue by j-m-baker** [swagger-api/swagger-core#1404]
Hello

Someone has made a start on implementing the 'example' definition:

io.swagger.models.ModelImpl:

    public Object getExample() {
        if (example == null) {
            // TODO: will add logic to construct examples based on payload here
        }

        return example;
    }

Are there any plans to extend this in some way? Ideally, it would be nice to annotate a service with a list of examples specified as JSON strings, or as a pre-populated object.

John

**Comment by webron** [comment]
This should be resolved as part of https://github.com/swagger-api/swagger-core/issues/1500.
