### ISSUE TITLE
Bug or feature in BeanConfig?

### ISSUE THREAD

**Issue by whisperwing** [swagger-api/swagger-core#1410]
Currently in BeanConfig class, setScan() will call updateInfoFromConfig() which overrides this.info if user previously sets it with setInfo().

I can workaround this by calling setInfo() AFTER setScan(), but that wouldn't be consistent with how other set*() functions work.

I need to use setInfo() to set some extension property that doesn't have a convenience set function.

**Comment by fehguy** [comment]
Per design.
