### ISSUE TITLE
Support @XmlValue

### ISSUE THREAD

**Issue by karlvr** [swagger-api/swagger-core#1411]
It is possible to use @XmlValue annotation on a property in a class in order to have that property represent the object in the output (XML or JSON). There are also @JsonValue and @JsonCreator annotations in Jackson JSON to do the same.

Using this you can have a class to wrap a value (such as a list), and provide additional functions on that object, such as adding and removing objects from the list, or finding them in the list.

However in the JSON output you just want it to be the property value, say a list of objects.

I think ideally swagger-jaxrs could see that annotation and simply defer to the given property for outputting the schema. Perhaps it should be an additional property on the @ApiModel annotation to activate this feature?

If you're interested, I am happy to attempt to contribute an enhancement patch.

**Comment by webron** [comment]
Try following https://github.com/swagger-api/swagger-core/issues/960.

**Comment by karlvr** [comment]
@webron thanks, I have now tried that out and it didn't have any impact. 

I added the following after the creation of my `BeanConfig` in a class that is constructed when my app server starts, and before the Swagger `ApiListingResource` is created or run.

```
Json.mapper().registerModule(new JaxbAnnotationModule());
Yaml.mapper().registerModule(new JaxbAnnotationModule());
```

I have @JsonValue on a method in the class in question. I have tried adding @XmlValue additionally. That also didn't work. I've tried investigating a bit further to see what is happening inside the `JaxbAnnotationIntrospector` but I didn't get very far!

What do you recommend as a course of action? I saw some explicit handling of Jackson annotations (e.g. `JsonTypeInfo`) in `ModelResolver`, but perhaps from #960 it appears that you don't want to add more support for these annotations in there?

**Comment by webron** [comment]
Apologies for the delayed reply.

What sort of impact do you expect `@XmlValue` to have? Can't really follow the usage.

**Comment by karlvr** [comment]
@webron No problem, here is our particular use-case below in code. We have a class `Links` which wraps a list of `Link` objects. When serialised to JSON we use `@JsonValue` so that rather than the JSON including the `Links` object with an array of `Link`s, the `Links` object isn't represented in the JSON at all.

The `@JsonCreator` annotation is to support deserialisation from that JSON.

So basically what we want Swagger to do is to pretend that the property of type `Links` in `Bean` is in fact `List<Link>`.

```java
public class Bean {

	private Links links;

	public Links getLinks() {
		return links;
	}
	public void setLinks(Links links) {
		this.links = links;
	}
}
```

```java
public class Links implements Iterable<Link> {

	private List<Link> links = new ArrayList<>();

	public Links() {
		super();
	}

	@JsonCreator
	public Links(List<Link> links) {
		super();
		this.links = links;
	}
	
	public Links(Link link) {
	    super();
	    this.links = new ArrayList<>();
	    this.add(link);
	}

	@JsonValue
	public List<Link> getJsonValue() {
		return links;
	}
	
	public List<Link> getLinks() {
		return links;
	}

	public void setLinks(List<Link> links) {
		this.links = links;
	}
	
	public void add(Link link) {
		this.links.add(link);
	}
	
	public Link linkWithType(LinkType type) {
		for (Link link : links) {
			if (type == link.getType()) {
				return link;
			}
		}
		
		return null;
	}

	@Override
	public Iterator<Link> iterator() {
		return links.iterator();
	}
	
}
```

**Comment by webron** [comment]
That's a great explanation, thanks, but where does `@XmlValue` come in? :) Or is that just the equivalent for XML?

**Comment by karlvr** [comment]
Doh, sorry! `@XmlValue` is indeed the JAXB corresponding annotation to `@JsonValue`. Given that swagger-core is tightly integrated with Jackson, maybe it's fine just to support the Jackson annotation. However I think some JAXB annotations are already supported? In which case perhaps support both.

**Comment by webron** [comment]
Yeah, it is tightly integrated with Jackson. There's some basic manual processing of JAXB annotations but those are rare. The full integration with JAXB should be using Jackson JAXB module, but it looks like it doesn't work for you, which makes me wonder what would be the cause of it. Do you use it to represent an XML structure or a JSON structure (or both)?

**Comment by karlvr** [comment]
Just a JSON structure at the moment.

**Comment by fehguy** [comment]
I believe this can be closed

**Comment by christophercolumbusdog** [comment]
Why was this closed, if there was never a solution? I'm encountering a very similar problem that I haven't been able to resolve.
