### ISSUE TITLE
Adding @Api to a provider adds objects in non-operation methods to the definitions

### ISSUE THREAD

**Issue by karlvr** [swagger-api/swagger-core#1421]
I have a provider class from CXF (`AccessTokenService`), which I'm extending so I can add Swagger annotations to it. I add the `@Api` annotation to the class, and override the `handleTokenRequest` method and add `@ApiOperations` etc annotations to it. All works great.

However the superclass includes some getter/setter methods for customising the service / provider, and the classes in the parameter list of these methods are now included in the definitions in the Swagger output.

I can resolve this by overriding the methods in question, and adding `@ApiOperation(value = "", hidden = true)`... however it's a bit frustrating and error prone.

It seems to me the these methods shouldn't be inspected. They are not annotated with `@GET` or `@POST` etc, they're only intended and exposed for internal use. Is this a fault in swagger-core?

**Comment by webron** [comment]
Yeah, I think it's a known issue. However, which version of swagger-core are you using?

**Comment by karlvr** [comment]
@webron my sincere apologies! I was using 1.5.0. I have upgraded to 1.5.3 and it is resolved as per your release notes.
