### ISSUE TITLE
Process JAX-RS annotations on interfaces

### ISSUE THREAD

**Issue by fritzrichter** [swagger-api/swagger-core#1427]
In our project, we have jax-rs (jersey) interfaces and implementations. As the interfaces are shared, I do not want to put any annotation to the actual interfaces which are not jax-rs specific. I added swagger annoations like @Api or @ApiOperation on the impl and let the jax-rs specific stuff like @Path, @PathParam etc. on the interface.

```
@Bean
	public BeanConfig getConfig() {
		
		BeanConfig config = new BeanConfig();
		config.setVersion(apiVersion);
		config.setSchemes(swaggerSchemes);
		config.setResourcePackage("com.ads.userservice.client,com.ads.userservice.api");
		config.setHost(swaggerHost);
		config.setBasePath(swaggerBasePath);
		config.setScan(true);
		 ReflectiveJaxrsScanner scanner = new ReflectiveJaxrsScanner();
        scanner.setResourcePackage("com.adsquare.userservice.client,com.adsquare.userservice.api");
        ScannerFactory.setScanner(scanner);
		
		return config;
	}
```

I tried different things, including the ReflectiveJaxrsScanner, but nothing worked out.

**Comment by webron** [comment]
Which version of swagger-core do you use?

>         config.setResourcePackage("com.ads.userservice.client,com.ads.userservice.api");

Is that the interfaces package or the implementations package?

**Comment by fritzrichter** [comment]
I use swagger-core 1.5.3. The classes are in different packages, as the interface is a shared library (separate jar) for clients and the server just adds the implementation.

**Comment by webron** [comment]
Try pointing he package to the actual implementation then.

**Comment by fritzrichter** [comment]
I did that, problem here was, that the jax-ws annotations were not read, so for example I was not able to see that a certain parameter must be provided as path-param...

My current temp solution is to just annotate the interface, thus adding the swagger-annotations.jar as a dependency to the client/shared lib.

**Comment by webron** [comment]
Can you share a sample interface method and implementation method, with all the annotations?

**Comment by fritzrichter** [comment]
Of course, here the interface:
```
package com.ads.userservice.client;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import com.ads.userservice.client.models.User;

@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Path("/v1/users")
public interface UserServiceApi {

	@GET
	@Path("/{id}")
	User findById(@PathParam("id") String id);

}
```
and the impl:
```
package com.ads.userservice.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

import java.util.List;
import java.util.stream.Collectors;

import javax.ws.rs.PathParam;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.ads.userservice.client.UserServiceApi;
import com.ads.userservice.client.models.User;
import com.ads.userservice.models.UserServiceBean;
import com.ads.userservice.models.UserServiceBean.ToUser;
import com.ads.userservice.service.UserService;

@Component
@Api(value = "/v1/users", tags = "userServiceApi")
public class UserServiceApiImpl implements UserServiceApi {

	@Autowired
	private UserService userService;

	@Override
	@ApiOperation(value = "Load by userId")
	
	public User findById(String id) {
		return new ToUser().apply(userService.findOne(id));
	}

}
```

**Comment by fritzrichter** [comment]
any feedback on that?

**Comment by webron** [comment]
Apologies for the delay. In general it should work, but we'll have to investigate it further. We're just a bit swamped right now. I believe someone could have a look at it next week.

**Comment by fritzrichter** [comment]
haha, of course... thanks for the quick reply... this is still an open source project, so I am thankful that someone is taking care of it :)

**Comment by webron** [comment]
Thanks for the feedback. We normally try to handle issues like this one more promptly, it really is just a bit of a chaotic time for us and not everyone is available. Thanks for checking in and for your patience.
