### ISSUE TITLE
Trouble using equals on a deserialized and a generated Swagger

### ISSUE THREAD

**Issue by quilicicf** [swagger-api/swagger-core#1428]
### Use case

I am translating RAML definitions into Swagger and writing non-regression tests. 
I would like to use the method `Swagger#equals` as follows: 

``` java
Swagger reference = Json.mapper().readValue(referenceFile, Swagger.class);

Raml raml = new RamlDocumentBuilder().build(ramlLocation);
Swagger translated = Translator.raml2swagger(raml);

assertEquals(reference, translated);
```

Unfortunately, the test always fails even though serializing both Swaggers gives the exact same result.
### Analysis

I spotted at least two issues.
1. The names of the objects contained in maps are not filled in during de-serialization. Ex:
   
   ``` js
   {
   "definitions": {
     "pet": {
       ...
     }
   },
   ...
   }
   ```
   
   The `ModelImpl` generated for "pet" by a de-serialization of the JSON definition above has no name set even though it is in the definition and is checked in the `equals` method. This issue I believe is replicated wherever a map is used in the spec.
2. The field `ModelImpl#required` is set by the deserializer but not updated via the method `ModelImpl#addRequired` which is used to set the property `ModelImpl#required` during the translation. The equals method being based on the variable (`if (!required.equals(other.required)) { return false;}`), it always returns false. I see two ways to fix it but don't know which one you would prefer.
   1.  Update the instance variable when using `ModelImpl#addRequired`
   2. Use `ModelImpl#getRequired` instead of `ModelImpl#required` in `ModelImpl#equals`

Hope this is clear enough, BTW for the moment I switched to tweaking an ObjectMapper and comparing the JSON generated from the Swagger definitions which works for me (in case someone else is stuck).

``` java
ObjectMapper mapper = Json.mapper();
mapper..configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);

URL referencedSwaggerPath = getClass().getResource("referenceSwagger.json");
Swagger referenceSwagger = Swagger2Utils.fromUrl(referencedSwaggerPath);
String referenceSwaggerAsJson = mapper.writeValueAsString(referenceSwagger);

URL referencedRamlPath = getClass().getResource("test.raml");
Raml raml = new RamlDocumentBuilder().build(referencedRamlPath);
Swagger translatedSwagger = Translator.raml2Swagger2(raml);
String translatedSwaggerAsJson = mapper.writeValueAsString(translatedSwagger);

assertEquals(referenceSwaggerAsJson, translatedSwaggerAsJson);
```

**Comment by fehguy** [comment]
This would be for swagger-parser, if still valid.
