### ISSUE TITLE
Add support for @DefaultValue annotation inside of parameter aggregator

### ISSUE THREAD

**Issue by meshuga** [swagger-api/swagger-core#1430]
When using `@BeanParam` annotation, no `@javax.ws.rs.DefaultValue` value is extracted into the resulting JSON.

Example:
```java
public class FindParams {
    @QueryParam("limit")
    @DefaultValue("10")
    private Integer limit;

    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }
}
```

Test controller:
```java
    @GET
    void getContainerItems(@Valid @BeanParam FindParams findParams) {
        ...
    }
```

**Comment by iushankin** [comment]
It should work on the Swagger 1.5
This feature was implemented, please look at: https://github.com/swagger-api/swagger-core/pull/1095

JSON for your example:

```json
{
  "swagger" : "2.0",
  "tags" : [ {
    "name" : "basic"
  } ],
  "paths" : {

    "/getContainerItems" : {
      "get" : {
        "tags" : [ "basic" ],
        "operationId" : "getContainerItems",
        "parameters" : [ {
          "name" : "limit",
          "in" : "query",
          "required" : false,
          "type" : "integer",
          "default" : 10, <--
          "format" : "int32"
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    },

  }
}
```

Which version of the Swagger do you use?

**Comment by webron** [comment]
@iushankin - are you sure it works for `@BeanParam`? I know it works for 'regular' ones.

**Comment by iushankin** [comment]
@webron it works for `@BeanParam`
Also we have tests for it:
model - [TestBeanParam.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/models/TestBeanParam.java)
resource - [ResourceWithBeanParams.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/resources/ResourceWithBeanParams.java)
test - [ScannerTest.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/test/java/io/swagger/ScannerTest.java#L47-L70)

**Comment by webron** [comment]
Oh look, there's even a test for it!

**Comment by iushankin** [comment]
@webron sure, I wrote tests for `@DefaultValue` and for `@ApiParam(defaultValue = ...)` annotations in `@BeanParam`

**Comment by iushankin** [comment]
Hi, @meshuga. Did you have a chance to check the swagger version? Can we close the issue?

**Comment by fehguy** [comment]
Please reopen if you're still having an issue.
