### ISSUE TITLE
Swagger-Core does not support values restricted path using regex

### ISSUE THREAD

**Issue by robert-wang** [swagger-api/swagger-core#1433]
We are using @Path annotation in regex on our class, @Path("/{a:metaconfig/|}v1/clients/") 
the usage of this annotation is that it can indicate 2 api paths
1. /metaconfig/v1/clients
2./v1/clients

``` java
@Api(value = "Accountmgmt")
@Path("/{a:metaconfig/|}v1/clients/") 
public interface IAccountMgmtClientPortType 
{
    @GET
    @Path("{clientKey}")
    @Produces({ MediaType.APPLICATION_JSON })
    @Alias("Client")
        @ApiOperation(value = "get Client details", notes = "get Client details.")
    Client getClient(@PathParam ("clientKey") String clientKey)...
```

the json file generated by using Swagger-core 1.5.3 is

``` json
 "paths" : {
    "/{a}/|}v1/client/{clientKey}}" : {..
```

It cannot recognize the regex correctly.
for this kind of annotation, we expect that the path in the json can be copied to 2 times divided by '|', one should be /metaconfig/v1/client/{clientKey} and the other should be /v1/client/{clientKey} which is the same behavior as the purpose of such kind of path annotation. because this annotation is on the class not method, we can not pass the value by @PathParam. Please let me know if this analyzing can be added to the Swagger-Core. Thanks

**Comment by genthalili** [comment]
+1
same issue, I'm using ``@Path("{var: client | _Client }")``

the json file generated by Swagger-core 1.5.3 is :

````"paths" : {
    "/{var}" : {..````

A solution of this could be to let setting (overwrite) manually the path with `@ApiOperation` annotation, i.e `path()` and/or `paths()`

**Comment by fehguy** [comment]
Not supported in the spec.
