### ISSUE TITLE
swagger-models: add a responses property in the swagger object

### ISSUE THREAD

**Issue by ePaul** [swagger-api/swagger-core#1436]
The [spec says](http://swagger.io/specification/#responsesDefinitionsObject):

> RESPONSES DEFINITIONS OBJECT
>
> An object to hold responses to be reused across operations. Response definitions can be referenced to the ones defined here.
>
> This does not define global operation responses.

This is contained directly in the root [swagger object](http://swagger.io/specification/#swaggerObject):

> * `responses`
> * Responses Definitions Object
> * An object to hold responses that can be used across operations. This property *does not* define global responses for all operations.

When trying to implement the `$ref: #/responses/...` references for #1388 (with [#89 in swagger-parser](https://github.com/swagger-api/swagger-parser/issues/89), I noted that actually there is no method `Swagger.getResponses()` (analogously to `getPaths()`, `getDefinitions()`, `getParameters()`.

Obviously this is blocking any reference creation to them.

This property would be a `Map<String, Response>`.

**Comment by fehguy** [comment]
This was added via https://github.com/swagger-api/swagger-core/commit/305811ef71fe35725512d7450631175785dc55fa and will release in 1.5.4
