### ISSUE TITLE
support headers in response declaration

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#144]
See if response headers can be supported in declaration

**Comment by shinijaQB** [comment]
My swaggervel integartion results in response body 
{"result_code":500,"result_title":"Server Unreachable","result_string":"The server didn't respond. Please try again."}
why this happen? please give me a solution.

**Comment by webron** [comment]
@shinijaQB - swaggervel has nothing to do with this project. If you have an issue with it, please open a ticket on the right repository.

**Comment by shinijaQB** [comment]
How to i write annotations. Now i written in controller apis. Is it a good
way?

**Comment by shinijaQB** [comment]
My swaggervel parameters are like this,

  @SWG\Parameter(
     *             name="body",
     *             description="users details",
     *             paramType="body",
     *              required=true,
     *              allowMultiple=false,
     *              type="string",
     *          ),
and i created a model schema for it. But when i click on scema datas are
not displaying in body. what to do for it?

**Comment by shinijaQB** [comment]
My swaggervel integration for my one controller function work as well.But
when i add swagger resource in next controller it turns to page error What
is the right method?

**Comment by shinijaQB** [comment]
How can upload image in swaggervel?
