### ISSUE TITLE
Configuring the internal ObjectMapper doesn't seem to work (LocalDate issue)

### ISSUE THREAD

**Issue by andersaa** [swagger-api/swagger-core#1444]
We have a custom ObjectMapper that maps LocalDate to a string. The ObjectMapper is configured like this:

```java
ObjectMapper mapper = new ObjectMapper();
mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
mapper.registerModule(new JavaTimeModule());
```

This results in LocalDates being serialized as "2015-12-31". We are trying to configure Swagger to use the same mapping, and from what I have read (for instance here: https://github.com/swagger-api/swagger-core/issues/960#issuecomment-100484695) it should be possible to get a hold of the Swagger's internal ObjectMapper and apply the same configuration there. So I have tried to do this in our SwaggerConfigServlet:

```java
public class SwaggerConfigServlet extends HttpServlet
{
  @Override
  public void init(ServletConfig config) throws ServletException
  {
    super.init(config);

    BeanConfig beanConfig = new BeanConfig();
    beanConfig.setBasePath("/myapp/rest");
    beanConfig.setResourcePackage("pa.api.resource");
    beanConfig.setScan(true);

    Info info = new Info();
    info.setTitle("MYAPP REST API");
    info.setVersion("0.0.1");
    beanConfig.setInfo(info);

    Json.mapper().configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    Json.mapper().registerModule(new JavaTimeModule());
    Yaml.mapper().configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    Yaml.mapper().registerModule(new JavaTimeModule());
  }
}
```
But no matter what I do, our response model will have LocalDate objects in the mapping, like this:
```
ClaimEvent {
  eventId (string, optional),
  eventDate (LocalDate, optional),
  eventNumber (integer, optional),
  superEvent (string, optional),
  mainEvent (string, optional),
  description (string, optional)
}
```
We are using Swagger 1.5.3. Is this supposed to work? Any idea what I am doing wrong?

Keep up the good work guys!

-Anders

**Comment by buremba** [comment]
It seems that currently only a few date related classes are supported by Swagger. (See [PrimitiveTypes](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java#L204))  #1445 might be a solution for this issue.

**Comment by webron** [comment]
@andersaa - haven't had the chance to test it myself... busy times... but can you try configuring the `Json` and `Yaml` mappers *before* setting the `BeanConfig`?

**Comment by andersaa** [comment]
@webron I just tried that and it is no different.

@buremba Ok I see. But with #1445, should LocalDates be serialized to strings without modifying the ObjectMapper? is the ObjectMapper a workaround that we can use until that task is implemented. Just to be clear, I am using Java 8 LocalDate. 

Thanks for helping!

**Comment by buremba** [comment]
@andersaa ObjectMapper doesn't actually directly related with this issue. Swagger uses Jackson inspector in order to analyze classes but Jackson doesn't actually know whether it's a bean class or a primitive type. For example, JSR310Module for Jackson serialize LocalDate as string but doesn't actually tell Jackson that it's a string AFAIK.

EXTERNAL_CLASSES in Swagger PrimitiveType is used for this purpose in order to determine whether the class is actually a primitive type or not and if it's, Swagger doesn't use Jackson inspector.

As a workaround, you can use the following code:
```
private void setExternalTypes(Map<Class, PrimitiveType> externalTypes) {
        // ugly hack until swagger supports adding external classes as primitive types
        try {
            Field externalTypesField = PrimitiveType.class.getDeclaredField("EXTERNAL_CLASSES");
            Field modifiersField = Field.class.getDeclaredField("modifiers");

            modifiersField.setAccessible(true);
            externalTypesField.setAccessible(true);
            modifiersField.set(externalTypesField, externalTypesField.getModifiers() & ~Modifier.FINAL);

            Map<String, PrimitiveType> externalTypesInternal = externalTypes.entrySet().stream()
                    .collect(Collectors.toMap(e -> e.getKey().getName(), e -> e.getValue()));
            externalTypesField.set(null, externalTypesInternal);
        } catch (NoSuchFieldException|IllegalAccessException e) {
            LOGGER.warn("Couldn't set external types", e);
        }
}

setExternalTypes(ImmutableMap.<Class, PrimitiveType>builder()
                .put(LocalDate.class, PrimitiveType.DATE)
                .build())
```

**Comment by andersaa** [comment]
Awesome, works like a charm!

Closing this issue since it is covered by #1445.

**Comment by andersaa** [comment]
For some strange reason, this workaround does not work after a hot redeployment in Tomcat 8. If I stop and start the server everything is fine, but after the next redeployment it looks like the fix isn't applied.
