### ISSUE TITLE
Support for mapping external classes to primitive types

### ISSUE THREAD

**Issue by buremba** [swagger-api/swagger-core#1445]
Currently, [io.swagger.util.PrimitiveType](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java) maps some Joda classes to date-related primitive types (stored in EXTERNAL_CLASSES field) but there are much more classes (ex. Java 8 Date API) that should be supported. It would be nice to add public static method to [io.swagger.util.PrimitiveType](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/util/PrimitiveType.java) that maps external classes to primitive types.

**Comment by webron** [comment]
FWIW, support for some Java 8 Date API has been added in 1.5.4.

**Comment by buremba** [comment]
@webron I'm actually using java.time.Duration and java.time.Instant and they're still missing. However, in general, I still think that you should allow people to register their external classes as primitive types since there are many third party libraries and use cases.
The workaround that I suggested in #1444 is not reliable, EXTERNAL_CLASSES field is marked as final and It seems that Java recovers the initial value of field in hot swapping phase.

**Comment by ayzenquwe** [comment]
And what about Duration?

**Comment by soberich** [comment]
@frantuma @webron 
Duration, Period, ZoneId ?  
Why those not been added while others was. For consistent support of the whole `java.time.*` package shouldn't all those be added as well as some (maybe ALL) rest from that package. 
All use-cases in java world with those types when talking about REST APIs are just representing them as strings.
