### ISSUE TITLE
Not parsing @Consumes and @Produces when using JAX-RS

### ISSUE THREAD

**Issue by HenrikHL** [swagger-api/swagger-core#1448]
In JAX-RS - @Consumes and @Produces can be defined both by having a String[] and a comma separated String:

@Consumes( {"application/json", "application/xml", "text/csv"} )
and
@Consumes( "application/json, application/xml, text/csv" )

Are both valid JAX-RS @Consume annotations. Swagger-core doesn't parse the String-version. Swagger-core sees the comma separated list as one MediaType (instead of 3 in the example above). This is very visible when displayed in Swagger-UI as the dropdown lists for Consumes/Produces is wrong

**Comment by veitmichael** [comment]
Same issue applies to the procuces (and also consumes?) property of the ApiOperation annotation:
I am using a comma-separated list of mime-types, and it gets displayed as comma-separated list in Swagger-UI.
I am not participating in development of Swagger, but looking at the fix above looks like just changing
modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java to split the string for api.produces() and api.consumes():
             if (!api.produces().isEmpty()) {
                 produces = new String[]{api.produces()};
             }

Btw., I am just trying to use this property as I am not able to control the sort order of mime types. From Consumes JAX-RS annotation, sort order is not preserved  (most probably lost already in JAX-RS implementation...). Is there any other mechanism to define the sort order, or at least the default value of the "Response Content Type", as I don't like duplicating information?

**Comment by fehguy** [comment]
Seems like this is valid @veitmichael.  Could you please open a new issue for this and we can get it fixed?

**Comment by veitmichael** [comment]
Done, see https://github.com/swagger-api/swagger-core/issues/1546
