### ISSUE TITLE
1.5.4-SNAPSHOT has dependency on missing class

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-core#1452]
1.5.4-SNAPSHOT has dependency on missing class.

```
java.lang.NoClassDefFoundError: io/swagger/config/ScannerFactory
	at io.swagger.jaxrs.config.WebXMLReader.<init>(WebXMLReader.java:22)
	at io.swagger.jaxrs.config.DefaultJaxrsConfig.init(DefaultJaxrsConfig.java:11)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
```

Constructor of `WebXMLReader` calls `ScannerFactory.setScanner(scanner);`

**Comment by webron** [comment]
Tried it with the wink sample, works well. Can't reproduce it.

**Comment by cppexpert** [comment]
Well, that's pretty much default answer from you, based on 6 months experience communicating here.

Download this file
https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-core/1.5.4-SNAPSHOT/swagger-core-1.5.4-20150909.202041-9-sources.jar

It has no `ScannerFactory.java`

**Comment by cppexpert** [comment]
@fehguy Let me add Tony here. He was pretty responsive usually.

**Comment by webron** [comment]
It doesn't have the ScannerFactory as that was moved as part of https://github.com/swagger-api/swagger-core/pull/1412, which is included in the *latest* snapshot (https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-core/1.5.4-SNAPSHOT/swagger-core-1.5.4-20150921.134406-10-sources.jar). Had you provided the full details in the first place, I could have given you the answer right away. I can't guess what you're doing or experiencing.

**Comment by cppexpert** [comment]
What's your role on the project then if I babysit lead engineer to to line level of what's wrong ? You're always triggerhappy to close bugs without even trying to solve the problem as if it was performance indicator of your work in the company.

I frankly think open source software development it's not something you enjoy and honestly don't understand why you still on the project which is already close to the state of "broken beyond repair".

**Comment by webron** [comment]
Ruslan, if you have concerns with the service you're getting from me, you're more than welcome to raise them, though I feel there are better venues.

I'm going to refrain from replying to the points here though as this is not the place for such a discussion.

If pulling the latest snapshot solves the issue, please close it. If not, let me know and we'll investigate further.

**Comment by cppexpert** [comment]
Getting latest snapshot fixed the issue. Broken snapshot should be removed from the repo since it's been reported that it's broken.

As per your services I'll let @fehguy to decide what to do. I can discuss the matter outside of GitHub issue but my personal opinion is that you're not interested in this project, you've been damaging it for at last last 8 months and it should stop.

Thanks.
