### ISSUE TITLE
Need a good solution for 'GET all' API documentation

### ISSUE THREAD

**Issue by ndhar-1** [swagger-api/swagger-core#1456]
I have used Swagger Annotations since a while now, have researched and tried many options to implement GET all. I am not using Spring Framework. I am using:
 <artifactId>swagger-core</artifactId>
 <version>1.5.1-M2</version>

Following are my observations-

* Annotation @ApiResponse cannot have ‘responseContainer’ attribute- limitation for GET all.
* The only way to get Model Schema for GET all on Swagger UI is to remove @ApiResponse(code = 200, message =“OK”) and have @ApiOperation with ‘responseContainer’. In this case the 200 OK response class doesn’t show up on UI.

Can we have a good solution which would let us see Model Schema as well as 200 OK response on the Swagger UI ?

**Comment by webron** [comment]
The response not showing in the UI is a bug in the UI (there's an open ticket). It will indeed only show for 200.

There is a `responseContainer` attribute in `@ApiResponse` but you'd need to update to the latest version of swagger-core to use it.

**Comment by ndhar-1** [comment]
Ok thanks ! I ll try the new Swagger Core version

**Comment by webron** [comment]
@ndhar-1 - any update?

**Comment by ndhar-1** [comment]
Yes, GET all works well for me now. I did not have to use responseContainer attribute in @ApiResponse, instead just upgrading swagger core version solved the problem.

**Comment by webron** [comment]
Awesome, thanks for the update!
