### ISSUE TITLE
A good solution to reuse parameter-definitions

### ISSUE THREAD

**Issue by HenrikHL** [swagger-api/swagger-core#1457]
I am aware that it is possible to add (query)parameters in the swagger-object:

```java
QueryParameter download = new QueryParameter();
download.name("download").description("Triggers the browser to set the download flag. The parameter is the filename");
swagger.addParameter("download", download);
```

It would be really nice if it was possible to refer to these parameters when defining the @ApiOperation annotation (or a new @ApiReferParameter) on the endPoints so they could be reused. A am aware that it is possible to use @ApiImplicitParams - but this doesn't allow for reuse :-(

An even better solution would be to group a bunch of parameters and refer to the group as many of my endPoints have the same QueryParameters (eg. it is possible to sort all endPoints returning a Collection by defining a "&sort=name" query parameter, on all endPoints a download trigger can be activated, etc...)

**Comment by webron** [comment]
Regarding your second option, isn't that exactly what BeanParam covers?

**Comment by HenrikHL** [comment]
Actually I wasn't aware of this - thank you for pointing me in that direction.

After experimenting a little with @BeanParam - swagger-core doesn't seem to parse it the way I was expecting. When annotating fields with @QueryParam:

    public class CollectionParameters {
        @QueryParam(value="sort")
        public String sort;

        @QueryParam(value="excluded")
        public String excluded;

        @QueryParam(value="included")
        public String included;
    }

I was kind of hoping that Swagger would render the above 3 query parameters as QueryParameters. It seems like it is rendering it as a class...?
![image](https://cloud.githubusercontent.com/assets/3489388/10071640/aa2f0c56-62bb-11e5-8933-c592205b9bc1.png)

Am I doing something wrong?

Here is how I use the CollectionParameters class:

    @GET
    @ApiOperation(
            value="Gets a collection of Feedbacks",
            response = Feedback.class,
            responseContainer = "List"
    )
    public Response getFeedbacks(@BeanParam CollectionParameters collectionParameters, ...) {
        ...
    }

Is this a bug or is it supposed to be this way?

**Comment by HenrikHL** [comment]
Actually this is how I was expecting the QueryParameters would turn up in the UI:
![image](https://cloud.githubusercontent.com/assets/3489388/10071769/b201b856-62bc-11e5-9620-17723938e255.png)

(This is programmed using @ApiImplicitParams )

**Comment by webron** [comment]
@HenrikHL - if you're getting that, then it looks like a bug. It should definitely render as it does in your second screenshot. Which version of swagger-core did you test it with?

**Comment by HenrikHL** [comment]
I am using latest version 1.5.3

**Comment by webron** [comment]
@lugaru1234 - can you check it please? There's a test with a `@BeanParam` that includes a body parameter as well. It may fail if a body parameter is not included.

**Comment by HenrikHL** [comment]
It is version 1.5.3

The code is as above. I am only using 3 QueryParam annotations in the CollectionParameters class above. I am not using neither PathParams or BodyParams...

**Comment by webron** [comment]
That's where the bug may occur. The parameter is treated as a body parameter mistakenly.

**Comment by HenrikHL** [comment]
I can try tomorrow to add a @BodyParam (or a @PathParam) and let you know if anything changes...

**Comment by HenrikHL** [comment]
It doesn't matter what kind of Params I insert - every time it produces a "double"-body in the documentation. Code example:
    public class CollectionParameters {
        @QueryParam(value="sort")
        public String sort;

        @QueryParam(value="excluded")
        public String excluded;

        @QueryParam(value="included")
        public String included;

        @HeaderParam(value="xxx")
        public String xxx;

        @FormParam(value="yyy")
        public String yyy;

        @MatrixParam(value="zzz")
        public List<String> stringList;
    }

An example of the use:

    @GET
    @ApiOperation(
            value="Gets a collection of figures",
            notes = "Gets all Figures.",
            response = Figure.class,
            responseContainer = "List"
    )
    public Response getFigure(@BeanParam CollectionParameters collectionParameters, ...) {
        ...
    }

...and the result from the Swagger-UI:
![image](https://cloud.githubusercontent.com/assets/3489388/10095074/32608180-6367-11e5-9cbc-db3652a530e5.png)

**Comment by lugaru1234** [comment]
Hi, @HenrikHL. I have tested your sample. What jersey version do you use? It should work for jersey2 as you expected. Please look at the https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey2

**Comment by HenrikHL** [comment]
I am pretty sure I am using Jersey2 - otherwise the project wouldn't compile (@BeanParam was added in version 2.0 as far as I can see...)
I will check the code again on Monday - maybe I can find a reason as to what is wrong...?

**Comment by lugaru1234** [comment]
@HenrikHL, Sure, sorry. I forget about this fact. I have added your code to the test and it works fine, also I have added the same code to the swagger-jersey2-sample-app and it works as you expected too.
Here is CollectionParameters https://github.com/lugaru1234/swagger-samples/blob/beanParam/java/java-jersey2/src/main/java/io/swagger/sample/model/CollectionParameters.java, and its use https://github.com/lugaru1234/swagger-samples/blob/beanParam/java/java-jersey2/src/main/java/io/swagger/sample/resource/PetResource.java#L101
And the result from the Swagger-UI:
![3](https://cloud.githubusercontent.com/assets/11853296/10131374/89ed3060-65d8-11e5-8d87-4b3e3af1be1a.png)
Please check the swagger dependency. It should include swagger-jersey2-jaxrs:
```
<dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      <scope>compile</scope>
      <version>${swagger-version}</version>
</dependency>
```
If it doesn't help I'll look for another reason

**Comment by HenrikHL** [comment]
I am totally mystified as to why this doesn't work in my project. I have copied the code from your example and made a simple class:

    import io.swagger.annotations.*;
    import javax.ws.rs.*;
    import javax.ws.rs.core.*;

    @Path("/figures")
    @Api(tags = {"pet"})
    @Produces({"application/json", "application/xml"})
    public class FiguresService {
        @GET
        @ApiOperation(
                value="Gets a collection of figures",
                responseContainer = "List"
        )
        public Response getFigure(@BeanParam EntityParameters entityParameters) {
            return Response.ok().build();
        }
    }

This is what swagger.json produces:

    "/figures" : {
      "get" : {
        "tags" : [ "pet" ],
        "summary" : "Gets a collection of figures",
        "description" : "",
        "operationId" : "getFigure",
        "produces" : [ "application/xml", "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/EntityParameters"
          }
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    },

The "schema" is referring to EntityParameters - is it supposed to? The EntityParameters look like this (it is a little modified compared to your example):

    "EntityParameters" : {
      "type" : "object",
      "properties" : {
        "excluded" : {
          "type" : "string",
          "description" : "Comma separated list of fields that should be excluded from the result"
        },
        "included" : {
          "type" : "string",
          "description" : "Comma separated list of fields that should be included in the result"
        },
        "print" : {
          "type" : "string",
          "description" : "PrettyPrint (print=pretty) the result or don't send anything back in the payload (print=silent)",
          "enum" : [ "pretty", "silent" ]
        }
      }
    },

In another place in my swagger.json I code the parameters myself (using @ApiImplicitParam) - then swagger.json looks like this:

    "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/InputStream"
          }
        }, {
          "name" : "included",
          "in" : "query",
          "description" : "Comma separated list of fields that should be included in the result",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "excluded",
          "in" : "query",
          "description" : "Surround the result with additional information",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "page",
          "in" : "query",
          "description" : "Get a specific page in the result",
          "required" : false,
          "type" : "integer"
          },

Notice here that the parameters are defined outside the schema scope (or outside the *"in" : "body"*)?!?
Can you please verify that the swagger.json above looks ok?

And my result: :-(
![image](https://cloud.githubusercontent.com/assets/3489388/10136753/5bc9fb78-65f6-11e5-8099-e9d2718899ea.png)

**Comment by HenrikHL** [comment]
I am so sorry @lugaru1234 - I didn't read all of your message:
"...Please check the swagger dependency. It should include swagger-jersey2-jaxrs:..."

I was missing the swagger-jersey2-jaxrs-1.5.3.jar library. After adding this everything is working. Thank you so much for your help - it is much easier now to reuse parameters :-)

It might though be easier to find the bug if Swagger displayed an error when the jersey2 jar was missing...

**Comment by lugaru1234** [comment]
@HenrikHL , you're welcome)

**Comment by webron** [comment]
@HenrikHL - are we good to close this issue?

**Comment by HenrikHL** [comment]
Yes - you can close the case. The reason it didn't work was because I forgot to include the swagger-jersey2-jaxrs-1.5.3.jar. My only concern was that I think it should have produced an error instead of wrong output...?
