### ISSUE TITLE
Swagger JAX-RS Module BeanConfig Prepends / To Base Path

### ISSUE THREAD

**Issue by saadmufti** [swagger-api/swagger-core#1469]
I am using BeanConfig class to set the basePath as follows in my application:

config.setBasePath("http://mycompany.com/myapp");

The problem is that the BeanConfig.setBasePath method has code to prepend a "/" if the base path does not already start with "/", making it "/http://mycompany.com/myapp". This prevents the Swagger UI from making a request to the right server as it does not treat it as a full URL, it insists on prepending the base domain from which the UI itself is being served, thus causing the "Try it out" button to make a request to "http://apiui.mycompany.com/http://mycompany.com/myapp" which of course doesn't work at all.

**Comment by webron** [comment]
Right, the `basePath` is only the context root of your application so the value should be `/myapp`. You should set the host to `http://mycompany.com`.

**Comment by saadmufti** [comment]
@webron Thanks, I totally missed that while upgrading from 1.3.x to the latest, doh.
