### ISSUE TITLE
Registering two servlet config, to have 2 swagger instances, one capturing packages version1, second capturing packages version2

### ISSUE THREAD

**Issue by to-kra** [swagger-api/swagger-core#1471]
i have registered 2 sevlets everyone having different config:
    @Override
	public void init(ServletConfig config) throws ServletException {
		super.init(config);
		BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("0.0.0");
        beanConfig.setBasePath(getServletContext().getContextPath() + "/api");
        beanConfig.setResourcePackage("sk.tokra.api.v0");
        beanConfig.setScan(true);
	}

second:
    @Override
	public void init(ServletConfig config) throws ServletException {
		super.init(config);
		BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.0");
        beanConfig.setBasePath(getServletContext().getContextPath() + "/v1");
        beanConfig.setResourcePackage("sk.tokra.api.v1");
        beanConfig.setScan(true);
	}

i have 2 Application, 1st with @ApplicationPath("/api") second with @ApplicationPath("/v1")

i have two swagger UIs, 1st leading to ../api/swagger.json 2nd ../v1/swagger.json

I have also created 2 listings: 1st V0Listing extending io.swagger.jaxrs.listing.ApiListingResource this is registered in /api application. 2nd V1Listing extending also io.swagger.jaxrs.listing.ApiListingResource but registered in /v1 application.

However both swagger-uis having same results showing results of 2nd servlet config & /v1 application

How to setup 2 swagger instances everyone scaning own packages ?

**Comment by to-kra** [comment]
I already fixed this to setting up different attribute in ServletContext, and handling it in my own ApiListingResource (to get that specific attribute -> instance of specific swagger)

**Comment by dherik** [comment]
Can you provide more details about how resolve the problem?

**Comment by dherik** [comment]
Detailing my solution.

Did you try to set the ConfidId and Scanner Id in the BeanConfig?

I have the same issue, but I was using web.xml and add this parameters for my Application:

        
	<init-param>
		<param-name>swagger.scanner.id</param-name>
		<param-value>api</param-value>
	</init-param>
	<init-param>
		<param-name>swagger.config.id</param-name>
		<param-value>api</param-value>
	</init-param>
	<init-param>
		<param-name>swagger.use.path.based.config</param-name>
		<param-value>true</param-value>
	</init-param>

        
	<init-param>
		<param-name>swagger.scanner.id</param-name>
		<param-value>v1</param-value>
	</init-param>
	<init-param>
		<param-name>swagger.config.id</param-name>
		<param-value>v1</param-value>
	</init-param>
	<init-param>
		<param-name>swagger.use.path.based.config</param-name>
		<param-value>true</param-value>
	</init-param>

This works because the `BaseApiListingResource`  class can verify in a static `Map` if the scan was initialized or not (it's a static attribute) by the configId and scannerId. If this parameters are not setted, the Swagger uses the unique static attribute called `initialized`.

**Comment by to-kra** [comment]
@dherik I did registering multiple instances of swagger in our app, using swagger 1.5.3. If i have a time i can push it to my github. However my approach is not working anymore with current swagger version, as they had changed it a lot. I might refactor code also to work with current version. I will inform you. Thx

**Comment by malinverno** [comment]
Hi

I tried the dherik solution, but seems that the BeanConfig lost parameters like BASEPATH, it'sgenerate a swagger json with not correct url

**Comment by trein** [comment]
This issue appears to be relevant still. Can we reopen it? I'm trying to register multiple instances of `Swagger` and it seems there's no easy solution yet.

**Comment by frantuma** [comment]
Please check also the following samples demonstrating multi swagger contexts:

* [java-jersey-jaxrs-multi-simple-webxml](https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey-jaxrs-multi-simple-webxml)
* [java-jersey-jaxrs-multi-simple-servlet](https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey-jaxrs-multi-simple-servlet)
* [java-jersey-jaxrs-multi-use-basepath](https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey-jaxrs-multi-use-basepath)

**Comment by trein** [comment]
Thanks, @francisdb. However, I was looking for a programmatic way to do that (i.e. without the need of xml files). Your examples gave me a nice insight on how to do this though.

**Comment by francisdb** [comment]
@trein I think you got the wrong username in your reply

**Comment by trein** [comment]
@francisdb Sorry about that. Just edited my previous reply.

**Comment by mat-ale** [comment]
Hi,
@frantuma is it possible to do the same from you samples using CXF?
Thanks

**Comment by TwinHits** [comment]
@trein Did you find a way to do this programmatic ally without xml files?

**Comment by trein** [comment]
Hi @TwinHits,

I'm not sure if this is the optimal approach. I ended up creating a new Servlet that dynamically register Swagger instances according to my needs. Something along the lines:

```
@RequiredArgsConstructor
public class SwaggerBootstrapServlet extends HttpServlet {

    private final Collection<String> apiIds;

    @Override
    public void init(ServletConfig config) throws ServletException {
        apiIds.forEach(apiId -> new SwaggerContextService()
            .withServletConfig(config)
            .withConfigId(apiId)
            .updateSwagger(createSwagger(apiId))
        );
    }
}
```

Then, I extended `BaseApiListingResource` to selectively return the swagger instance that has been previously configured.

```
@Path("/{apiId}/swagger.json")
public class SwaggerApiListingResource extends BaseApiListingResource {

    @Setter
    @Context
    private ServletContext context;

    @GET
    @Produces({ MediaType.APPLICATION_JSON })
    @ApiOperation(value = "The swagger definition in JSON ", hidden = true)
    public Response getListing(@Context ServletConfig config, @PathParam("apiId") String apiId) {
        Swagger swagger = new SwaggerContextService()
            .withServletConfig(config)
            .withConfigId(apiId)
            .getSwagger();

        if (swagger != null) {
            return Response.ok().entity(swagger).build();
        }
        return Response.status(404).build();
    }
}
```
