### ISSUE TITLE
Help Needed: How to generate swagger.json from gradle task?

### ISSUE THREAD

**Issue by velmuruganvelayutham** [swagger-api/swagger-core#1473]
I have integrated swagger-core with my project and I am able to access the swagger.json response successfully. However I was asked to generate the swagger.json as part of gradle task. I do not want to specify any swagger related servlets in the web.xml. 
ApiListingResource -  is responsible for producing swagger.json and swagger.yaml responses.
Is there any gradle plugin which does this work?. If so , Can you give me an reference to it?

 Thanks...

**Comment by webron** [comment]
Right now, there's the [swagger-maven-plugin](https://github.com/kongchen/swagger-maven-plugin) that you may be able to use. You'd have to read its docs to see how it works.

**Comment by velmuruganvelayutham** [comment]
Thanks webron. Is there a way to execute maven goals from gradle Tasks ?. 
Otherwise , I will start converting the above maven-plugin  to gradle-plugin.

**Comment by webron** [comment]
Never really used gradle. I'm sure a quick search would give you the answer.

**Comment by fehguy** [comment]
Hi, I'm closing this out--if you create a gradle plug-in and OSS it, feel free to send a PR to the [swagger.io](https://github.com/swagger-api/swagger.io) repository and we'll add it there.  Lots of people are using gradle now, and it'd be a welcomed addition to the tooling.

**Comment by aniruddhadas9** [comment]
I also need the same and does not find anything
