### ISSUE TITLE
URL string not reflected in the api sub-title properly when given as api value annotation

### ISSUE THREAD

**Issue by shashi0905** [swagger-api/swagger-core#1485]
With swagger annotation @Api (value=" "), when I try to insert an URL string, swagger UI skips all the forward slashes (/) while display.

Annotation being used :

@Api(value="shoplocator- http://api.meteor.com/v2/shops", description="some description...")
public class SomeClass {

What I'm getting at swagger UI :
shoplocator- http:api.meteor.comv2shops

What I'm expecting :
shoplocator- http://api.meteor.com/v2/shops

I tried using escaspe sequences and other ways to handle special characters, but nothing worked, like : shoplocator- http:\//api.meteor.com\/v2\/shops or shoplocator- http:&#47;&#47;api.meteor.com&#47;v2&#47;shops
But nothing worked.
How can I get the proper URL string in the api sub title value?

**Comment by webron** [comment]
So you basically can't (at least not right now) and that's the expected behavior due to the change from 1.3 to 1.5. However, given the problem you're trying to solve, I think the solution should come from swagger-ui with the external docs and that's what should be fixed.

**Comment by shashi0905** [comment]
Yes, and also as per our discussion with the API team following the current scenario, we have decided that our API Publishing tool can handle the task to automatically add the required link at the bottom of the HTML rendering of the SWAGGER documentation loaded.
But yes the issue related to external-docs should be looked into.
We can close this for now.
