### ISSUE TITLE
How to valid input data type on swagger-ui

### ISSUE THREAD

**Issue by zonorion** [swagger-api/swagger-core#1486]
Hi all,
My model schema:
{
  "wareHouseID": 0,
  "parentID": 0,
  "name": "string",
  "fullname": "string",
  "company": "string",
  "address": "string"
}

Now i want to catch error if input wareHouseID and parentID are "String".  
Tell me what should i do? Thanks

**Comment by webron** [comment]
That's out of scope for swagger-core, the project does Swagger specification generation, not validation.

**Comment by zonorion** [comment]
Thanks @webron.

**Comment by zonorion** [comment]
{
  "id": String,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

When input id is String
pet store swagger result: 
{
  "code": 400,
  "type": "unknown",
  "message": "bad input"
}

How can i catch same this.

**Comment by webron** [comment]
That's just regular code, again, not specific to swagger-core. You can check the source code for the pet store here - https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey-jaxrs.

**Comment by fehguy** [comment]
Hi, the JSON above is actually not valid--`"id":String` is missing quotes.  Please reopen an issue in swagger-ui if you think there's a problem still.
