### ISSUE TITLE
@BeanParam support for CXF?

### ISSUE THREAD

**Issue by andrewtyt** [swagger-api/swagger-core#1493]
Accordingly to https://github.com/swagger-api/swagger-core/wiki/Changelog @BeanParam is now supported by Jersey only. Are there any plans about CXF? Went through https://github.com/swagger-api/swagger-core/issues/446 topic, tried all the workarounds mentioned there, but none of them are working. Swagger treats @BeanParam as "body" and CXF doesn't seem to be able to parse this request. Same services work fine on Jersey.

**Comment by webron** [comment]
Have you tried using the swagger-jersey2-jaxrs module? It *will* pull in jersey2, but it shouldn't affect your application.

**Comment by andrewtyt** [comment]
Finally got it working! swagger-jersey2-jaxrs solves the issue. Thanks a lot!

**Comment by webron** [comment]
Thanks for the update.
