### ISSUE TITLE
@Pattern annotation not supported in ModelResolver

### ISSUE THREAD

**Issue by rwfaulkner** [swagger-api/swagger-core#1494]
Currently  "javax.validation.constraints.Pattern" allows for regex validation on a String and a Swagger String property also has a pattern (regex) that could be set from this annotation. However jackson.ModelResolver ignores the @Pattern annotation. 

Work around was to define a cushion ModelConverter class to add support for this annotation.

**Comment by rwfaulkner** [comment]
Pretty easy to add this feature. I can create a PR for this if it helps.

**Comment by fehguy** [comment]
That would be great!

**Comment by rwfaulkner** [comment]
Looks like it was already fixed for 1.5.4. https://github.com/swagger-api/swagger-core/pull/1439
