### ISSUE TITLE
Partial documentation support

### ISSUE THREAD

**Issue by fritzrichter** [swagger-api/swagger-core#1497]
I have many different API endpoints (JAX-RS Classes) which will produce a swagger.json configuration of about 25 different APIs. 

Some of the methods are private and used internally for admin purposes. About 10 APIs are marked as public and interesting for our customers.

Is there a way to basically generate two different swagger.json files, one just for public purposes and the other one, which include all methods?

A manual process would look like this: 
1. Generate the complete swagger.json
2. Extract the relevant APIs and models
3. Create new new derived subset swagger.json

What is the best approach for such a scenario?

**Comment by fehguy** [comment]
Yes!  There is first class support via the SwaggerFilter interface. Take a look there and post back any questions. Essentially you have the option to filter methods, parameters, and model properties on a per-request basis, which can use headers, etc to tell the filter "what to do"

**Comment by fritzrichter** [comment]
I see... thanks for that help... will close the ticket then
