### ISSUE TITLE
How do you override models with swagger-core 1.5.3?

### ISSUE THREAD

**Issue by jayree05** [swagger-api/swagger-core#1499]
Hi -

I'm trying to upgrade to swagger-core 1.5.3 and I've discovered that the OverrideConverter class has been removed.  However, the documentation on the wiki still refers to this class.  What should I be using in the new version to achieve the same functionality?

**Comment by webron** [comment]
So yeah, it has changed and not documented yet (sorry about that).

In the meantime, you can have a look at the test - https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/model/override/CustomConverterTest.java - and we'll do our best to answer any follow up questions you may have.

**Comment by jayree05** [comment]
Thank you very much!  I used that example along with this: https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/model/override/SamplePropertyConverter.java to figure out how to create a property (that example you linked me to just returns null).

I think I have everything set up.  But now I'm wondering, where do I put this code. The old way was to put it in the constructor of a servlet class.  Newer documentation puts a lot of startup type code in the the init function of a servlet class, which is what I did.  But it doesn't appear to be working.  I'm wondering if it's because you have to create a local instance of the ModelConverters class instead of using it statically.  I hope that question makes sense...

**Comment by jayree05** [comment]
Never mind!  I figured it out.  I needed to use the ModelConverters.getInstance() method.  Thanks again for your help!

**Comment by webron** [comment]
Glad it worked out. Can we close this issue?

**Comment by Download** [comment]
It is still not documented though  :(
