### ISSUE TITLE
@XmlElement not working correctly on Fields if the xsd defined the name with first letter in uppercase

### ISSUE THREAD

**Issue by Jerrrrrrry** [swagger-api/swagger-core#1502]
The pet.xsd defined Pet schema, please note that two fields Name and Address are both defined with first letter in uppercase.
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://github.com/mytest/pet" targetNamespace="http://github.com/mytest/pet"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="Pet">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="1" ref="tns:Name" />
				<xs:element maxOccurs="1" minOccurs="0" ref="tns:Address" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		<xs:simpleType>
			<xs:annotation>
				<xs:documentation xml:lang="en">
					define the pet's name
				</xs:documentation>
			</xs:annotation>
			<xs:restriction base="xs:string">
				<xs:minLength value="1" />
				<xs:maxLength value="20" />
				<xs:pattern value="([a-zA-Z0-9])*" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="Address">
		<xs:simpleType>
			<xs:annotation>
				<xs:documentation xml:lang="en">
					define the pet's location
				</xs:documentation>
			</xs:annotation>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
</xs:schema>
```
add jaxb stuff in pom.xml

	<groupId>org.jvnet.jaxb2.maven2</groupId>
	<artifactId>maven-jaxb2-plugin</artifactId>
	<executions>
		<execution>
			<id>xjc</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<schemaDirectory>pet.xsd</schemaDirectory>
		<generateDirectory>generated</generateDirectory>
		<forceRegenerate>true</forceRegenerate>
	</configuration>

the jaxb plugin will compile the above xsd file to java class Pet.java:
```
@XmlRootElement(name = "Pet")
public class Pet {
	@XmlElement(name = "Name")
	protected String name;

	@XmlElement(name = "Address")
	protected String address;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
}
```
so far, everything seems good: see below rest service definition 
```
@Path("/pet")
@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@Api(value = "/pet", consumes = "application/json, application/xml", produces = "application/json, application/xml")

public class PetController {

	@Autowired
	private PetService petService;

	@POST
	@Path("/savePet")

	@ApiOperation(value = "save a pet with name and address", response = PetResponse.class)
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Success", response = PetResponse.class) })
	public Response savePet(Pet request) {
		return petService.savePet(request);
	}
}
```
in the api doc, swagger.yaml, I am expecting the Parameters of body like below:
▼Pet {
Name: string *       
Address:string
} 

but actually I get 
▼Pet {
name: string *       
address:string
} 

and this is really causing my swagger test could not run, as the request is sending parameters "name" instead of "Name", "address" instead of "Address", the rest service could not get the proper value. if I manually set the request from name to Name, address to Address then the rest service works good.

**Comment by fehguy** [comment]
OK for the naming, the annotation processor is Jackson, which is not--by default--using the JaxB annotation processor.  You can easily enable it, which should cause the desired effect:

```java
ObjectMapper mapper = Json.mapper();
AnnotationIntrospector primary = new JacksonAnnotationIntrospector();
AnnotationIntrospector secondary = new JaxbAnnotationIntrospector();
AnnotationIntrospector pair = new AnnotationIntrospector.Pair(primaryIntrospector, secondaryIntropsector);
```

The reason why this is an optional step is that we're trying to avoid adding too many jackson dependencies to core unless needed.  This should address your issue, please reopen if you don't have luck with it.

**Comment by Jerrrrrrry** [comment]
Where I can add those code ? the swagger support are all configured. or how to implemented the mapper setting to use jaxb annotation by adding configuration instead of adding code?

<init-param>
	<param-name>jersey.config.server.provider.packages</param-name>
	<param-value>io.swagger.jaxrs.listing</param-value>
</init-param>

<servlet>
        <servlet-name>Jersey2Config</servlet-name>
        <servlet-class>io.swagger.jersey.config.JerseyJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <load-on-startup>3</load-on-startup>
</servlet>

**Comment by webron** [comment]
@Jerrrrrrry - you can add the code at any place in your code that runs when your application starts up. If you don't have such a code, you can create a simple bootstrap servlet to handle it.
