### ISSUE TITLE
How to use @QueryParam annotation to build a correct URI

### ISSUE THREAD

**Issue by catchaag** [swagger-api/swagger-core#1503]
I am composing an api using jersey and swagger. I am using @QueryParam annotation in my api and once the swagger file is generated. It shows the below entry for my queryparam

``` json
 {
          "name" : "statecode",
          "in" : "query",
          "required" : false,
          "type" : "string"

        } 
```

But uri produced for this shows: /resource/api?statecode

I want it to show like /resource/api?statecode=<code>

What should i do in order to get such URI. Please help.

**Comment by webron** [comment]
This is the uri produced when doing what?

**Comment by catchaag** [comment]
This is url produce after importing swagger file to APIM

**Comment by webron** [comment]
That sounds like more of an issue with APIM than it is with swagger-core.
