### ISSUE TITLE
SpecFilter should allow full Swagger document manipulation

### ISSUE THREAD

**Issue by testn** [swagger-api/swagger-core#1507]
A good use case is that a JAX-RS server is running behind a load balancer. If we have JAX-RS service running, we could use it to extract host information (i.e. load balancer address) and return the correct host information instead of the local host address.

**Comment by fehguy** [comment]
Sure, but suggest that is done by overriding the `ApiListingResource` which lets you mutate the whole spec.  Wouldn't that do for this type of case?

**Comment by testn** [comment]
That is probably fair enough.

**Comment by testn** [comment]
Interestingly, process method (which should be protected) already accepts UriInfo. It could then potentially override host/basepath information if it's not provided by @SwaggerDefinition.

**Comment by webron** [comment]
Out of curiosity, in this case, why add the host at all?

**Comment by testn** [comment]
right now... just because Swagger UI does not really work correctly without basePath/host when running on port other than port 80. Also you might want it such that the host information is always what the user is used to access the machine. Load balancer is a good example.

**Comment by fehguy** [comment]
Please see https://github.com/swagger-api/swagger-ui/issues/1689#issuecomment-149791854

**Comment by fehguy** [comment]
OK I am going to close this--the spec filter isn't supposed to allow manipulation of the spec--it's just a filter.  There are other techniques to get a handle on the swagger object.  It shouldn't be done here.
