### ISSUE TITLE
ApiListingResource should be declared as @Singleton

### ISSUE THREAD

**Issue by testn** [swagger-api/swagger-core#1509]
If not, "initialized" flag will not really work since it will always be false as the new instance is created every time.

**Comment by webron** [comment]
Which `@Singleton` are you referring to?

**Comment by testn** [comment]
@javax.inject.Singleton. By specifying it, you make sure that ApiListingResource is not instantiated every time it is accessed.

**Comment by webron** [comment]
Fair point. My only concern (which is not saying we won't do it) is that it would require adding another dependency as that's not part of the jdk libraries (and correct me if I'm wrong).

Of course an alternative is to set it as a Singleton in the jax-rs configuration, but that's up to the user (which we can also suggest in the documentation).

**Comment by fehguy** [comment]
Closing as optional with work-around.
