### ISSUE TITLE
Angular typescript: basePath always https

### ISSUE THREAD

**Issue by markvdkerkhof** [swagger-api/swagger-core#1516]
the basePath is always set to https: "basePath = 'https://localhost:62300/api';"
is it possible to force that is is http,

**Comment by webron** [comment]
Again, this looks like the wrong project.

**Comment by markvdkerkhof** [comment]
Is it? Because this is the generated swagger output when is choosen for output for 'Angular typescript:'

**Comment by webron** [comment]
This project is the language integration for java that allows producing Swagger specs from the Java code.

You're looking for [swagger-codegen](https://github.com/swagger-api/swagger-codegen).

**Comment by markvdkerkhof** [comment]
Ok, I've moved it to swagger-codegen.
Angular typescript: basePath always https #1538

**Comment by webron** [comment]
Thanks for moving the issue.
