### ISSUE TITLE
Angular typescript question: $httpParamSerializer

### ISSUE THREAD

**Issue by markvdkerkhof** [swagger-api/swagger-core#1517]
the constructor of the generated api looks like:
        constructor(private $http: ng.IHttpService, basePath?: string, private $httpParamSerializer?: (any) => any) {
But I get runtime errors because of the code expects the second parameter is $httpParamSerializer. So now I have to adapt manualy the generated file.

**Comment by webron** [comment]
I believe you got the wrong project... Not sure which one you need, otherwise would refer you.

**Comment by markvdkerkhof** [comment]
My issue is about the generated "Angular typescript" code from the Swagger yaml-file

**Comment by webron** [comment]
This relates to [swagger-codegen](https://github.com/swagger-api/swagger-core/) then, not this project.

**Comment by markvdkerkhof** [comment]
Oke tnx, I've moved it to the  swagger-codegen project.
Angular typescript question: $httpParamSerializer #1536

**Comment by webron** [comment]
Closing as issue moved.
