### ISSUE TITLE
Default headertext

### ISSUE THREAD

**Issue by markvdkerkhof** [swagger-api/swagger-core#1518]
All of our codefiles start with default headertext. It would be nice if text can be added to the yaml file, so this text will be inserted at the beginning.
"This is a generated file"

**Comment by fehguy** [comment]
Hi, can you please explain more?  Do you mean for generated code?  Or for the swagger definition?

**Comment by markvdkerkhof** [comment]
I mean to put in the swaggerdefinition some text, which the will put at all generated files at the beginning as comment. Purpose is that developers see that these files are generated so they should not try to adpat them.

**Comment by fehguy** [comment]
I really don't understand, @markvdkerkhof.  It seems like you're talking about swagger-codegen, right?  So generating a server or client from swagger definition?

**Comment by markvdkerkhof** [comment]
I will move this to the swagger-codegen project

**Comment by webron** [comment]
Closing as issue moved.
