### ISSUE TITLE
swagger java clinet complex json object

### ISSUE THREAD

**Issue by F191919** [swagger-api/swagger-core#1521]
I'm trying to use Swagger to describe web-api I'm building. The problem is that I can't understand how to describe complex json object?

For example, how to describe this objects:

{
name: "Jhon",
address: [
{
type: "home",
line1: "1st street"
},
{
type: "office",
line1: "2nd street"
}
]
}

**Comment by fehguy** [comment]
Answered your question in the google group:

https://groups.google.com/forum/#!topic/swagger-swaggersocket/n1M0pabWf24

Hi, I suggest you use http://editor.swagger.io to model your API.  It'll guide you through the process.  But for your specific question:

in JSON:
```json
{
  "definitions": {
    "User": {
      "properties": {
        "addresses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Address"
          }
        }
      }
    },
    "Address": {
      "properties": {
        "type": {
          "description": "the type of address",
          "type": "string",
          "enum": [
            "home",
            "office"
          ]
        },
        "line1": {
          "description": "blah blah",
          "type": "string"
        }
      }
    }
  }
}
```

And you can paste this in the editor:

```yaml
  User: 
    properties: 
      addresses: 
        type: "array"
        items: 
          $ref: "#/definitions/Address"
  Address: 
    properties: 
      type: 
        description: "the type of address"
        type: "string"
        enum: 
          - "home"
          - "office"
      line1: 
        description: "blah blah"
        type: "string"
```
