### ISSUE TITLE
Support for JSR-303 (Java Bean Validation)

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-core#1522]
Hi is there any support for JSR-303 (Java Bean Validation) ?

Given

A controller method

```java
import javax.validation.Valid;
@RequestMapping(method = RequestMethod.PUT)
public void create( @RequestBody @Valid MyDTO myDTO) {
    // do something with myDTO
}
```

A command object
```java
import javax.validation.constraints.NotNull;
public class MyDTO {

    @NotNull
    private Long myId;

    @NotNull
    private String myValue;
}
```

Swagger produces
```
MyDTO {
   myId (integer, optional),
   myValue (string, optional)
}
```

But should be required.
I could add swagger annotations to MyDTO's fields, but then the NotNull/required logic would be duplicated and potentially leads to documentation inconsistence.
I use http://mvnrepository.com/artifact/com.mangofactory/swagger-springmvc/1.0.2
Thanks.

**Comment by webron** [comment]
@raderio - you're using an old version of a project that's now called [springfox](https://github.com/springfox/springfox). While springfox uses some parts of swagger-core, it does its own processing there. I'd suggest upgrading to the latest version and if the bean validation doesn't work as expected for you, open a ticket on that project.
