### ISSUE TITLE
Example Value overwrites Parameter's DataType

### ISSUE THREAD

**Issue by phosn** [swagger-api/swagger-core#1526]
Hi,

I encountered the following unexpected behavior. When specifying an example value in a `@ApiImplicitParam` annotation the parameter's dataType will be set to the example value.

For instance annotation

```java
@ApiImplicitParam(name="id", paramType="path", dataType="string", example="123456")
```
will lead to JSON
```json
"parameters":
[{"name":"id",
  "in":"path",
  "type":"123456",
  "x-example":"123456"}]
```
This behavior was observed on swagger 1.5.4.

Cause is the `ParameterProcessor.applyAnnotations()` method. The following code found in the method overwrites the parameter's dataType:
```java
  if (StringUtils.isNotEmpty(param.getExample())) {
        p.setType(param.getExample());
  }
```
I am not really sure about the original intention of the code but it does not look right to me. The code was introduced by commit 62c100f33a54d7688e859cd011abb89a907e02ef "added example support for non-body params, implicits".

Best regards,

phosn

**Comment by fehguy** [comment]
Yep, this is a copy/paste bug.
