### ISSUE TITLE
How to avoid the filter execution when getting the api doc

### ISSUE THREAD

**Issue by Jerrrrrrry** [swagger-api/swagger-core#1527]
When consumer make a call to my rest webservice, the filters in service side will run to validate the http headers to make sure the request is valid and safe before invoke the actual service. 
but I am expecting those filters should not run if the request is coming for generating the api doc.

see my web.xml
```
<servlet>
      <servlet-name>jersey</servlet-name>
      <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
      <init-param>
        <param-name>jersey.config.server.provider.packages</param-name>
        <param-value>
            io.swagger.jaxrs.listing;
            com.my.rest.ws; <!--include all my rest services-->
            com.my.rest.filters <!--include oauth filter and http header filter-->
        </param-value>
      </init-param>
      <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>jersey</servlet-name>
        <url-pattern>/api/*</url-pattern>
    </servlet-mapping>
```
When consumer try to call the service via http://localhost:8080/myservice/api/v1/getdata, the filters will run to check oauth token and caller name in http header, if those two elements not present in http header then request will be rejected.

But for swagger api doc generating, when I tried to open http://localhost:8080/myservice/api/swagger.json I am expecting oauth filter and caller name filter should not be executed as the request is for api doc but not for calling the actual service.

Can swagger achieve this requirement?

**Comment by webron** [comment]
That depends on how you configure the filter. It's been a while, but if you can't filter out resources from the filter in its declaration, you'd have to filter those out in the filter's code.

**Comment by fehguy** [comment]
As @webron said, this is really part of your filter config. Can't be done with swagger.
