### ISSUE TITLE
swagger-core JSON not compliant with Swagger 2.0 spec

### ISSUE THREAD

**Issue by davidvc** [swagger-api/swagger-core#1533]
Hello.  I was very excitet to use swagger-diff (http://swagger.io/using-swagger-to-detect-breaking-api-changes/) to detect breaking changes to our APIs.

However, I was very sad to see it fail:

/Users/dvancouvering/.rvm/gems/ruby-2.1.2/gems/hashie-3.3.2/lib/hashie/extensions/coercion.rb:46:in `rescue in set_value_with_coercion': Cannot coerce property "info" from Hash to Swagger::V2::Info: The property 'vendorExtensions' is not defined for Swagger::V2::Info. (Hashie::CoercionError)

Research shows that it is using the swagger-rb gem to parse the JSON being returned from a swagger source.  In this case the source is a JAX-RS endpoint where I am using the annotations from swagger-api/swagger-annotations.

The JSON schema they are using is the Swagger 2.0 JSON schema at https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json

If you look there are a number of inconsistencies between what this JSON schema defines and what is returned by your tool.   Please see below for some examples.

Are you aware of this?  Is there work ongoing to resolve this?  I am tempted to go into your source and try and fix it to be compliant but if this is already being done no need for me to duplicate effort.

== Some detailed examples ===

From the JSON delivered by swagger-api:

info: {
version: "1.0.0",
title: "",
vendorExtensions: { }
},

In the Swagger 2.0 JSON Schema: 

"info": {
      "type": "object",
      "description": "General information about the API.",
      "required": [
        "version",
        "title"
      ],

vendorExtensions is present in the swagger-api JSON, but is not defined in the schema.

In the output from swagger-api, this is an example pathItem:

/chroniccondition: {
get: {...},
vendorExtensions: {... },
empty: false,
operations: [...]

In the Swagger 2.0 JSON Schema definition for paths

   "pathItem": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^x-": {
          "$ref": "#/definitions/vendorExtension"
        }
      },
      "properties": {
        "$ref": {
          "type": "string"
        },
        "get": {
          "$ref": "#/definitions/operation"
        },
        "put": {
          "$ref": "#/definitions/operation"
        },
        "post": {
          "$ref": "#/definitions/operation"
        },
        "delete": {
          "$ref": "#/definitions/operation"
        },
        "options": {
          "$ref": "#/definitions/operation"
        },
        "head": {
          "$ref": "#/definitions/operation"
        },
        "patch": {
          "$ref": "#/definitions/operation"
        },
        "parameters": {
          "$ref": "#/definitions/parametersList"
        }
      }
    }

Note, no reference to "empty" or to the "operations" array, both of which are present in the swagger-api output.

Thanks,

David

**Comment by fehguy** [comment]
Well I'm quite sure that we are generating valid swagger in our projects.  From what your posting, it looks to me like you may be using the Swagger POJOs from the swagger-models project, but not the SwaggerSerializer class?  That's a requirement to turn them into JSON.  Please post back here if I'm misreading your intent.

**Comment by davidvc** [comment]
I am not sure which one we are using.  We are basically installing a
servlet that delivers the Swagger JSON as a separate endpoint on a Tomcat
web application, using JerseyJaxrsConfig.  We annotate all of our REST
endpoints using annotations like @ApiParam and @ApiOperation, and magic
happens when we invoke the JerseyJaxrs endpoint below...

Is there a different way we should be doing this?

<servlet>
    <servlet-name>Jersey2Config</servlet-name>
    <servlet-class>com.wordnik.swagger.jersey.config.JerseyJaxrsConfig</servlet-class>
    <init-param>
        <param-name>api.version</param-name>
        <param-value>1.0.0</param-value>
    </init-param>
    <init-param>
        <param-name>swagger.api.basepath</param-name>
        <param-value>${planservice_url}</param-value>
    </init-param>
    <load-on-startup>2</load-on-startup>
</servlet>

**Comment by davidvc** [comment]
I do see that we have the swagger-models jar in the classpath.  How would we go about using SwaggerSerializer with our servlet?

**Comment by davidvc** [comment]
We are following the instructions here:

https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5

And it is generating the output I described above. 

This sure seems like a bug because the page above specifically says it is generating Swagger 2.0 output, but in the output from the /swagger.json endpoint, there are fields being added that are not part of the Swagger 2.0 JSON schema.

Sorry if I'm missing something

**Comment by davidvc** [comment]
Here in the Swagger 2.0 spec referred to from

https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5

It has the Info object like this:

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#infoObject

Note there is no field called vendorExtensions, but that is included in the output from the /swagger.json endpoint

And here is the pathItem object

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#pathItemObject

And there is no reference to the "empty" or "operations" fields which show up in the output from the /swagger.json endpoint

**Comment by davidvc** [comment]
OK, so this is very strange.  I just pulled down the jersey-jaxrs sample from here

https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey2

Built it and ran it, and it is producing what appears to be compliant json.

Sadly, swagger-diff *still* fails with a stupid error

"Swagger version swagger is not currently supported"

But now I need to figure out why your example generates different JSON than ours, when the configuration looks to be exactly the same and we are just using the standard annotations...  Clearly some digging is necessary.

**Comment by fehguy** [comment]
I'm happy to help, but (a) `swagger-diff` is _not_ the official way to validate swagger compliance and (b) you're not following those instructions.

First off, the dependency listed here:

https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#concrete-class-selection

Is quite different from what you're using.  `com.wordnik` was deprecated over a year ago.  Please use this as your dependency:

```xml
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jersey2-jaxrs</artifactId>
  <version>1.5.4</version>
</dependency>
```

This is the latest release version of swagger-core.

Next, your web.xml here:

```
<servlet-class>com.wordnik.swagger.jersey.config.JerseyJaxrsConfig</servlet-class>
```

Is pointing to the older version of swagger (note the `com.wordnik`).  Use the proper package, which is shown here:

https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#package-scanning--concrete-class-selection

Finally, there are samples that do all this for you, which you'll probably have an easier time following.  For jersey2:

https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey2

I know it can be frustrating getting things working, but if our own tools couldn't validate against our own specification, something would really be wrong.

**Comment by davidvc** [comment]
Yes, thanks, I saw those com.wordnik references just 20 minutes ago and
fixed them and was sure that would do it, and sadly *still* got the weird
results, even though your sample doesn't generate them.  I have peered
closely at the sample code and XML files compared it with my own and can
find no difference.  But clearly a difference exists or I wouldn't get
different output.

I agree swagger-diff is not an official compliance tester.  But I want to
use it :( and so far have been unable to because of the JSON output I'm
getting.

I'll report back any findings

**Comment by fehguy** [comment]
You need to ensure that the SwaggerSerializers are enabled.  They are what turn the POJOs into the swagger objects correctly.

**Comment by davidvc** [comment]
Well, I gave it another try after carefully making sure that the two XML files looked the same.  So this time I had success!  

swagger-diff is still barfing but I think that's a bug in swagger-diff.  Your JSON looks great now.

Thanks for your help (and patience :)).

**Comment by webron** [comment]
Closing for now. Please reopen if needed.

**Comment by davidvc** [comment]
Just so you know, the root cause of the bug was a subtle difference you
probably want to document in your migration guide:

In the old Swagger you included com.wordnik.swagger.jersey.listing

In the new 1.5.4 version of Swagger, you need to include
io.swagger.jaxrs.listing

Note the switch from "jersey" to "jaxrs"

That made all the difference.

Also, as a note, when a libraries has an incompatible change so that
existing compiled code will no longer work (such as changing the package
names), that should be considered a major version change, not a patch
version change (e.g. from 1.5.3 to 1.5.4).

See http://semver.org:

*Given a version number MAJOR.MINOR.PATCH, increment the:*

   1. *MAJOR version when you make incompatible API changes,*
   2. *MINOR version when you add functionality in a backwards-compatible
   manner, and*
   3. *PATCH version when you make backwards-compatible bug fixes.*


Thanks!

David

**Comment by webron** [comment]
Thanks for the feedback. I believe what you mentioned here is covered by https://github.com/swagger-api/swagger-core/wiki/1.3--1.5-Migration#jax-rs-providers.

As for the versioning, that change was introduced in 1.5.0 not 1.5.4, a major version.

**Comment by davidvc** [comment]
Thanks.  I must have missed that, sorry aboutthat.

It's weird we were using 1.5.3 with the wordnik package and it was working
fine :(

1.5.0 is a minor version.  2.0 would be a major version.

**Comment by webron** [comment]
Not in our book ;) We don't really follow semver officially.

**Comment by fehguy** [comment]
We probably could have done better with the versioning for 1.5.x but as ron said, this change is history.

**Comment by davidvc** [comment]
LOL yes spilt milk.  As a user though it would reduce surprises.  Thanks
for all you do!!
