### ISSUE TITLE
@Path("/") not rendered at all

### ISSUE THREAD

**Issue by bojanantonovic** [swagger-api/swagger-core#1534]
When annotating a Java class with @Path("/"), then the slash ( / ), doesn't appear at all. In any other cases, like @Path("/abc"), the path "/abc" is rendered.

As our code runs, we would like to see the Swagger generated documentation handling it too.

I've tested this one with swagger-maven-plugin 3.0.0, 3.0.1 and 3.1.0, and couldn't find a reference for it elsewhere.

(This is a replacement of https://github.com/swagger-api/swagger-ui/issues/1720.)

**Comment by who** [comment]
@bojanantonovic 

This looks like a known issue over in swagger-maven-plugin. Please add any useful information to https://github.com/kongchen/swagger-maven-plugin/issues/217

I can investigate this over the next few days.

**Comment by who** [comment]
@bojanantonovic 

I've fixed this in swagger-maven-plugin 3.1.1-SNAPSHOT. Could you please pull source and verify ?

@webron This issue is probably safe to close; we can move discussion over to kongchen/swagger-maven-plugin#217

**Comment by webron** [comment]
Thanks, @who.

**Comment by bojanantonovic** [comment]
Can confirm: problem is now fixed. Thanks!
