### ISSUE TITLE
Swagger-Servlet with embedded Jetty

### ISSUE THREAD

**Issue by adcoolguy** [swagger-api/swagger-core#1539]
In our environment, we can not run Swagger with our app server, thus we use embedded Jetty. This is the class but it does not scan our annotated servlet. Could you advise on what we are missing? Thanks a  million!

package com.test;

import io.swagger.sample.util.ApiOriginFilter;
import io.swagger.servlet.config.DefaultServletConfig;
import io.swagger.servlet.listing.ApiDeclarationServlet;

import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.DefaultHandler;
import org.eclipse.jetty.server.handler.HandlerList;
import org.eclipse.jetty.server.handler.ResourceHandler;
import org.eclipse.jetty.server.nio.SelectChannelConnector;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.util.log.StdErrLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import app.controller.CrudService;

public class Starter {
    private static final Logger logger = LoggerFactory.getLogger(Starter.class);

```
public static void main(String[] args) throws Exception {
    StdErrLog lg = new StdErrLog();
    lg.setDebugEnabled(true);
    org.eclipse.jetty.util.log.Log.setLog(lg);
    Server server = new Server();
    SelectChannelConnector connector = new SelectChannelConnector();
    connector.setPort(8002);
    server.addConnector(connector);

    // Setup web handler
    final ResourceHandler webResourceHandler = new ResourceHandler();
    webResourceHandler.setDirectoriesListed(false);
    webResourceHandler.setWelcomeFiles(new String[] { "index.html" });

    // Create servlet context
    final ServletContextHandler servletContext = new ServletContextHandler(ServletContextHandler.SESSIONS);
    servletContext.setContextPath("/");
    servletContext.addServlet(CrudService.class, "/ws/crud");
    servletContext.addFilter(ApiOriginFilter.class, "/", null);

    // Setup Swagger handlers
    servletContext.addServlet(CrudService.class, "/ws/crud/*");

    servletContext.addServlet(DefaultServletConfig.class, "/");
    servletContext.setInitParameter("swagger.resource.package", "io.swagger.sample.servlet");
    servletContext.setInitParameter("swagger.api.basepath", "http://localhost:8002");
    servletContext.setInitParameter("api.version", "1.0.0");
    servletContext.addServlet(ApiDeclarationServlet.class, "/api/*");

    final HandlerList handlers = new HandlerList();
    handlers.setHandlers(new Handler[] { webResourceHandler, // Web handler
            servletContext, // Servlet handler
            new DefaultHandler() }); // Default handler returns 404 (NOT
                                        // FOUND) for anything else

    server.setHandler(handlers);
    server.start();
    server.join();
}
```

}

We hit http://localhost:8002/api/ and the screen is blank. The log says:

2015-11-08 20:24:04.350:DBUG:oejs.Server:RESPONSE /api/ws/  404 handled=true
...

**Comment by fehguy** [comment]
You need to enable scanning with `BeanConfig`.  Take a look here for an example:

https://github.com/swagger-api/swagger-samples/blob/5809a49e3b7184da7194cdfb818fee7151750cf8/java/java-jersey2-guice/src/main/java/io/swagger/sample/SwaggerExampleGuiceContextListener.java#L32-L45

**Comment by adcoolguy** [comment]
We do not use Maven and (thus) we got these errors:

        props.put("javax.ws.rs.Application", Application.class.getName());
        props.put("jersey.config.server.wadl.disableWadl", "true");
        serve("/api/*").with(ServletContainer.class, props);

Which jar can we find Application.class and ServletContainer.class ?

Thanks for the prompt response!

**Comment by fehguy** [comment]
that's a long road to go down.  Is there a reason why you can't use a dependency manager?  There are a lot of dependencies for jaxrs.

**Comment by adcoolguy** [comment]
Google App engine legacy project, they were never meant to used with Maven. Created dinosaur age back. But we fixed those two. Left with Bootstrap.class. Is it io.swagger.api.util.Bootstrap? Could you do a Ctrl + Shift + T, enter the class and let us know what jar file is it supposed to be from! :)

We owe you once. LOL

**Comment by fehguy** [comment]
That class is application-specific and you can probably remove it.

**Comment by adcoolguy** [comment]
Alright. Same response even with BeanConfig. The following is the latest codes of the embedded Jetty. Still returning blank via /api. Anything we miss? :)

package com.appspot.cloudserviceapi;

import io.swagger.jaxrs.config.BeanConfig;
import io.swagger.sample.util.ApiOriginFilter;
import io.swagger.servlet.config.DefaultServletConfig;
import io.swagger.servlet.listing.ApiDeclarationServlet;

import javax.ws.rs.core.Application;

import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.DefaultHandler;
import org.eclipse.jetty.server.handler.HandlerList;
import org.eclipse.jetty.server.handler.ResourceHandler;
import org.eclipse.jetty.server.nio.SelectChannelConnector;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.util.log.StdErrLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import app.controller.CrudService;

public class Starter {
//  private static final Logger log = Logger.getLogger(Starter.class);
    private static final Logger logger = LoggerFactory.getLogger(Starter.class);

	public static void main(String[] args) throws Exception {
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.0");
        beanConfig.setSchemes(new String[]{"http"});
        beanConfig.setDescription("This is a app.");
        beanConfig.setTitle("Swagger Petstore");
        beanConfig.setHost("localhost:8002");
        beanConfig.setBasePath("/api");
        beanConfig.setFilterClass("io.swagger.sample.util.ApiAuthorizationFilterImpl");
        beanConfig.setResourcePackage("io.swagger.sample.resource");
        beanConfig.setContact("apiteam@swagger.io");
        beanConfig.setLicense("Apache 2.0");
        beanConfig.setLicenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html");
        beanConfig.setScan(true);

		StdErrLog lg = new StdErrLog();
		lg.setDebugEnabled(true);
		org.eclipse.jetty.util.log.Log.setLog(lg);
		Server server = new Server();
		SelectChannelConnector connector = new SelectChannelConnector();
		connector.setPort(8002);
		server.addConnector(connector);

		// Setup web handler
		final ResourceHandler webResourceHandler = new ResourceHandler();
		webResourceHandler.setDirectoriesListed(false);
		webResourceHandler.setWelcomeFiles(new String[] { "index.html" });
	    
		// Create servlet context
		final ServletContextHandler servletContext = new ServletContextHandler(ServletContextHandler.SESSIONS);
		servletContext.setContextPath("/");
		servletContext.addServlet(CrudService.class, "/ws/crud");
		servletContext.addFilter(ApiOriginFilter.class, "/*", null);
		
		// Setup Swagger handlers
		servletContext.addServlet(CrudService.class, "/ws/crud/*");

		servletContext.addServlet(DefaultServletConfig.class, "/");
	    servletContext.setInitParameter("swagger.resource.package", "io.swagger.sample.servlet");
	    servletContext.setInitParameter("swagger.api.basepath", "http://localhost:8002");
	    servletContext.setInitParameter("api.version", "1.0.0");
		servletContext.addServlet(ApiDeclarationServlet.class, "/api/*");
	    servletContext.setInitParameter("javax.ws.rs.Application", Application.class.getName());
	    servletContext.setInitParameter("jersey.config.server.wadl.disableWadl", "true");

		final HandlerList handlers = new HandlerList();
		handlers.setHandlers(new Handler[] { webResourceHandler, // Web handler
				servletContext, // Servlet handler
				new DefaultHandler() }); // Default handler returns 404 (NOT
											// FOUND) for anything else        

		server.setHandler(handlers);
		server.start();
		server.join();
	}
}

**Comment by adcoolguy** [comment]
While waiting for your reply, bumped into this http://www.sep.com/sep-blog/2015/11/05/adventures-in-documentation/.

Is the document valid? Do we need to do all those?
