### ISSUE TITLE
Swagger introspection adds models that are referenced by the resource annotated by @Api

### ISSUE THREAD

**Issue by titiu7** [swagger-api/swagger-core#1541]
There are two questions related to this that I would like to ask:

1. I'm working on a REST project that uses Jersey. Only the interfaces are annotated with Swagger annotations and those interfaces are implemented by the Jersey resource classes. The interfaces and the resource classes are in separate packages and Swagger is configured to scan the packages that contain the interfaces. During introspection, is Swagger supposed to include models referenced by the classes that implement the annotated interfaces or just the interfaces?

2. If a resource, annotated with Swagger annotations, depends on a class that has overloaded setter methods, Swagger fails to serialize that class when generating models. What if you can't make changes to that class, is there a way to plugin a different JSON parser that supports overloaded setter methods?

 I'm not sure why I didn't see this issue with Swagger-Core version 1.3.12 instead it came up when I upgraded to Swagger-core 1.5.4

Any guidance would be appreciated!
Thanks,

**Comment by fehguy** [comment]
Hi @titiu7, a couple answers for you.

For #1, yes, it should detect and add any models which are referenced as either inputs or outputs to operations.  Typically it'll scan the class or interface referenced and not all possible permutations of classes which implement the interface.  So add the interface in the annotations and it should show the correct model schemal

For #2, I would need to see some examples.  Can you share a definition or test case to show what you're talking about?

**Comment by titiu7** [comment]
Thanks for your reply @fehguy 
I have a class that looks like: 
```Java
@XmlAccessorType(XmlAccessType.FIELD)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonSerialize(include = Inclusion.NON_NULL)
@JsonAutoDetect(fieldVisibility = Visibility.ANY, getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
Public Class AttributeValue {
   private String attributeValue;
   private AttributeTypeEnum attributeType;
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue;
    }
    public void setAttributeValue(ValueType attributeValue) {
        this.attributeValue = attributeValue.toString();
        this.attributeType = attributeValue.getAttributeType();
    }
}
```
this class belongs to a library that is used in my project as a maven dependency, so it can't be changed. One of the resource methods, annotated with Swagger, deals with an object that uses the AttributeValue class shown above. When Swagger parses models that will be included in the swagger json file, io.swagger.jaxrs.Reader throws an exception on AttributeValue: 
```
java.lang.IllegalArgumentException: Conflicting setter definitions for property "attributeValue": com.mycompany.AttributeValue#setAttributeValue(1 params) vs com.mycompany.AttributeValue#setAttributeValue(1 params)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:303)
```
My assumption is that the FasterXml Json parser doesn't support overloaded setter methods. The only solution to this kind of problem that I know of is to use @JsonIgnore.  Since the class AttributeValue can't be changed, that option is ruled out. So, I'm wondering if there is a way to use a different library that supports parsing overloaded methods. 
Thanks

**Comment by fehguy** [comment]
Hi @titiu7, you'd simply have to create a custom model converter to process these types.  You can then define exactly what you want to expose, and the overloaded setter method won't be an issue.

Honestly this is the first time I've heard of this one so it's possible that there's a fix in Jackson somewhere.
