### ISSUE TITLE
swagger.json is not build with jersery-jaxrs 

### ISSUE THREAD

**Issue by LingLong** [swagger-api/swagger-core#1544]
Hello Swagger-Team,

i use Swagger to display the resources of my jersey-jaxrs application.
I prepend that everything worked fine for me with Swagger 1.3 !
Recently I try to upgrade Swagger to 1.5 an now it seems that swagger.json is not build anymore.

Got Error: Cannot read swagger.json from ... (with statuscode 404)

This is my dependency 
![pom](https://cloud.githubusercontent.com/assets/3339561/11145747/bf8d5fe8-8a08-11e5-9ce9-a86f4158c7c4.PNG)

I do not have a web.xml so I use the SwaggerBeanConfig like this:
![swaggerbeanconfig](https://cloud.githubusercontent.com/assets/3339561/11145764/d8b8e5dc-8a08-11e5-8228-7f7a69f903a1.PNG)

I think there is a Versionproblem
(I use Swagger-UI-2.1.1)
Thanks for help/fix!

Greetings

**Comment by webron** [comment]
Which URL do you use to open your swagger.json?
Which application server do you use to run your application? If it is tomcat or tomcat-based, what is the application context that you use?

**Comment by LingLong** [comment]
I use a Grizzly-Server, url= http://localhost/simulation/api-docs
<http://localhost/simulation/api-docs>
also http://localhost:8080/simulation <http://localhost:8080/simulation> 
/api-docs/swagger.json and so on, does not work.
 
-----Original-Nachricht-----
Betreff: Re: [swagger-core] swagger.json is not build with jersery-jaxrs 
(#1544)
Datum: 2015-11-13T21:00:30+0100
Von: "Ron" <notifications@github.com>
An: "swagger-api/swagger-core" <swagger-core@noreply.github.com>
 
 
 
Which URL do you use to open your swagger.json?
Which application server do you use to run your application? If it is 
tomcat or tomcat-based, what is the application context that you use?
—
Reply to this email directly or view it on GitHub
<https://github.com/swagger-api/swagger-core/issues/1544#issuecomment-156542262> 
.

**Comment by webron** [comment]
swagger-core 1.5 doesn't support Grizzly at the moment. Please follow https://github.com/swagger-api/swagger-core/issues/1103.
