### ISSUE TITLE
Error when remove @PathParam

### ISSUE THREAD

**Issue by zonorion** [swagger-api/swagger-core#1545]
hi all,
i have problem when i remove @PathParam, my code
```java
@GET
	@Path(Constants.LOGIN)
	@ApiOperation(value = "Login", notes = "Login")
	@ApiResponses(value = { 
			@ApiResponse(code = 400, message = "Invalid username or password supplied"),
			@ApiResponse(code = 404, message = "User not found") })
	public Response adminLogin(
			@ApiParam(value = "Username of user", required = true) String username,
			@ApiParam(value = "Password of user", required = true) String password)
					throws WebApplicationException {
}
```
Because i don't want api link same: api/login/{param}/{param}
Could you tell me how to resolve. Thanks all

**Comment by fehguy** [comment]
Well what id username and password?  Are they form params?  You have to designate how the values will be sent to the system somehow, either via path, body, query, header, form, etc.

**Comment by zonorion** [comment]
I want my api link as: api/login not api/login/{usn}/{password}
I try more anotation @PathParam, @Query, @Header, @Form but not work :(

**Comment by fehguy** [comment]
yea, it's really not clear what you're after.  Seems like API design vs. usage of this library.  Consider posting in the [swagger google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) for design questions.
