### ISSUE TITLE
when get swagger.json, backend will scan resources every time. Is there a solution to improve efficiency?

### ISSUE THREAD

**Issue by wangzilong** [swagger-api/swagger-core#1548]
I am using swagger-ui to provide nice documentation for REST APIs to our clients. when open swagger-ui in browser, it will get http://i-digi-sign.appspot.com/rest/swagger.json

I find that when get /api/swagger.json, backend will scan annotations of resources every time. it will cost much time。

Is there a solution to improve efficiency?

**Comment by fehguy** [comment]
annotations don't work that way--it's all cached.

**Comment by wangzilong** [comment]
does it cache swgger.json? or cache all annotations?

**Comment by wangzilong** [comment]
When I debug in local dev server, I find that swagger always run into io.swagger.jaxrs.Reader.read() method to analyse annotations

**Comment by wangzilong** [comment]
![image](https://cloud.githubusercontent.com/assets/4329939/11277100/edc923fa-8edc-11e5-9ea8-93046547c4a3.png)
there is the log in appengine
it is cost much time to generate swagger.json

**Comment by tzvatot** [comment]
Any resolution for this?

**Comment by wangzilong** [comment]
Add a new filter in my web project, and this filter cache swagger.json in memory
When this interface is called repeatedly, the filter will return swagger.json directly.

**Comment by webron** [comment]
It's not configured to scan the annotations every time. What makes you think it does?

**Comment by wangzilong** [comment]
Sorry for "scan annotations of resources every time", I did not found this code.
All I want to express is
is there any resolution to cache swagger.json instead of rebuild it.

**Comment by fehguy** [comment]
I think you'll need to implement a cache-dump on your own.  If it's generalized, please send a PR and others can take advantage of it.

**Comment by xinmeng1** [comment]
+1
