### ISSUE TITLE
Definitions using polymorphism seem incorrect

### ISSUE THREAD

**Issue by rdiehl** [swagger-api/swagger-core#1549]
I'm not sure whether this belongs here, or in the swagger-parser project, or in the swagger2markup project https://swagger2markup.readme.io/, but I'll start here.  We have a number of models that use polymorphism, some of them extend multiple levels.  We're using Java annotations and the JAX-RS integration to create our Swagger definition at runtime.  I'm running into issues running our spec through the swagger2markup tool, and I'm trying to figure out whether the issue is something we have defined incorrectly, or a bug in one of the 3 projects.  Here's our Java classes with the swagger annotations.

``` java
@ApiModel(description = "The representation of a Chart-like object.", discriminator = "_class",
        subTypes = { TextChartDTO.class, ChartDTO.class, TableChartDTO.class })
public abstract class BaseChartDTO implements Serializable {
    private String id;
    private String name;
    public String getId() { return id;}
    public void setId(final String id) {this.id = id;}
    public String getName() { return name;}
    public void setName(final String name) {this.name = name};
    // Various other properties
}

@ApiModel(description = "A parent class for all charts.", parent = BaseChartDTO.class, discriminator = "_class",
        subTypes = { PieChartDTO.class, BarChartDTO.class, AreaChartDTO.class, LineChartDTO.class,
            MixedChartDTO.class, GaugeChartDTO.class })
public abstract class ChartDTO extends BaseChartDTO implements Serializable {
    private ChartType chartType;
    public ChartType getChartType() {return chartType;}
    public void setChartType(final ChartType type) {this.chartType = type;}
    // various other properties
}

@ApiModel(description = "An area chart.", parent = ChartDTO.class)
public class AreaChartDTO extends ChartDTO implements Serializable {
    // various properties
}
```

When our swagger definition is generated, the definition for AreaChartDTO looks like this:

``` json
"AreaChartDTO": {
"allOf": [
{
"$ref": "#/definitions/ChartDTO"
},
{
"type": "object",
"properties": {
  "id": {
    "type": "string"
  },
  "name": {
    "type": "string"
  },
},
.... more stuff
```

Note the existence of "allOf", referencing the ChartDTO definition, and then individual properties like "id" and "name".  The definition for ChartDTO looks like this:

``` json
"ChartDTO": {
"allOf": [
{
"$ref": "#/definitions/BaseChartDTO"
},
{
"type": "object",
"properties": {
  "id": {
    "type": "string"
  },
  "name": {
    "type": "string"
  },
.... more stuff
```

Again note that id and name are defined here.  The definition for BaseChartDTO has them as well.  In effect what we're seeing is that properties from the base classes are being duplicated for each concrete class.

When the swagger definition goes through the swagger-parser, it parses successfully, but if you look in definitions, the id and name fields are duplicated 3 times through existence of multiple ComposedModel and RefModel objects.  When I send the Swagger object that comes back from the parser into the Swagger2markup tool, it throws an exception about having multiple entries with the same key: "id".  

Is this something that we are configuring incorrectly in our ApiModel annotations?  If not, does this issue belong in swagger-core, swagger-parser, or the 3rd party swagger2markup project?

**Comment by fehguy** [comment]
hmm, to be honest, this sounds like a swagger2markup issue.  If you could, please open a ticket there.  I don't think this belongs in swagger-core, as the spec you're showing looks accurate.

**Comment by RobWin** [comment]
My question is: Why do all definitions (ChartDTO, AreaChartDTO and ChartableDTO) need a id and name property, if it would be sufficient to have them in the ChartableDTO definition? It looks like a bug in the generator which generates the Swagger JSON? What do you think?

**Comment by fehguy** [comment]
It is legal to have them all contain shared properties, JSON schema does say that *which* one is used is indeterminate.

If the parser is creating multiple parameters with the same name--well that's a bug of the parser.  I do believe internally that it's using linked hash maps, which means it's technically impossible.

If we can create a sample test then I can get it figured out pretty quickly.  @rdiehl do you think you can send a PR with a test that shows the problem?

**Comment by jagruti29** [comment]
Not able to see polymorphism definitions in documentation
Model is 


@ApiModel(value = "MovieBean" ,discriminator = "type", description = "Prototype for creating movies", parent = EntertainmentBean.class , subTypes = {DocumentaryMovieBean.class , DramaBean.class})
public class MovieBean extends EntertainmentBean {
	@ApiModelProperty(value = "movie Id" , position = 1 , required = true)
	private int movieId;
	@ApiModelProperty(value = "Name of a Movie",  position = 2)
	private String name;
	@ApiModelProperty(value = "Movie Rating",  position = 3 , allowableValues = "1,2,3,4,5")
	private int rating;
	@ApiModelProperty(value = "language", position = 4)
	private String language;
	@ApiModelProperty(value = "type", position = 5 , required = true )
	private String type;





}

and generated doc is 

definitions":{"MovieBean":{"type":"object","properties":{"language":{"type":"string","description":"language"},"movieId":{"type":"integer","format":"int32","description":"movie Id"},"name":{"type":"string","description":"Name of a Movie"},"rating":{"type":"integer","format":"int32","description":"Movie Rating"}},"description":"Prototype for creating movies"}}}

 I am using swagger 2.4.0. Please advise.

**Comment by webron** [comment]
There's no swagger 2.4.0.

**Comment by jagruti29** [comment]
apologies Let me correct myself.
springfox-swagger2 version 2.4.0 and swagger version 2.0

**Comment by webron** [comment]
@jagruti29 then you need to open a ticket on springfox.

**Comment by jagruti29** [comment]
Ok thanks .I will raise a ticket.
