### ISSUE TITLE
Duplicate Rest URL Path : swagger with spring

### ISSUE THREAD

**Issue by sanjibpramanick** [swagger-api/swagger-core#1550]
This is my Spring Swagger configuration:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

         import org.springframework.beans.factory.annotation.Autowired;
        import org.springframework.context.annotation.Bean;
        import org.springframework.web.servlet.config.annotation.EnableWebMvc;

    import com.mangofactory.swagger.configuration.SpringSwaggerConfig;
    import com.mangofactory.swagger.models.dto.ApiInfo;
    import com.mangofactory.swagger.plugin.EnableSwagger;
    import com.mangofactory.swagger.plugin.SwaggerSpringMvcPlugin;

    @EnableWebMvc
    @EnableSwagger
    public class SwaggerConfig {
	    private SpringSwaggerConfig springSwaggerConfig;

	@Autowired
	public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
		this.springSwaggerConfig = springSwaggerConfig;
	}

	@Bean
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(apiInfo()).includePatterns(".*");
	}

	private ApiInfo apiInfo() {
		ApiInfo apiInfo = new ApiInfo("SaurzCode API", "API for Saurzcode", "Saurzcode API terms of service",
				"abcd@gmail.com", "Saurzcode API Licence Type", "Saurzcode API License URL");
		return apiInfo;
	}
    }
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Here are the maven dependencies :

		<dependency>
			<groupId>com.mangofactory</groupId>
			<artifactId>swagger-springmvc</artifactId>
			<version>1.0.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>swagger-ui</artifactId>
			<version>2.0.24</version>
		</dependency>
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

is there anything wrong , I'm getting duplicate urls when I'm accessing swagger api

**Comment by sanjibpramanick** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/12508077/11368458/f3c441f2-92df-11e5-8baf-b436af9d6ca2.png)

**Comment by webron** [comment]
Please open the issue on [springfox](https://github.com/springfox/springfox).
