### ISSUE TITLE
Do we have swagger annotation for path at method level?

### ISSUE THREAD

**Issue by catchaag** [swagger-api/swagger-core#1551]
Hi,

I am working on project with jersey and swagger. We use swagger.json to compose apis on APIM.
We have number of get apis which has the same path but it differs on query param.
But jersey resolves the resource only using the path. Hence we are forced to merge our api into one api which will have same path.

To solve this, I thought we can have unique uris for all our get apis but when swagger file is generated, swagger reads only the unique ones so that it will be easy for us to compose apis on APIM and it will avoid any manual step.

Is there any way in swagger using which we can tell swagger to include this path in swagger.json rather than using jersey path annotation

Appreciate your quick response.

Thanks

**Comment by webron** [comment]
If I follow your flow, it means you eventually want to differentiate between operations using query parameters. With the current version of Swagger, a unique identifier is a combination of the HTTP verb and the path - the query parameters cannot be used to uniquely identify an operation.

**Comment by catchaag** [comment]
oh... so there is no way to achieve this??

**Comment by webron** [comment]
I'm afraid not.
