### ISSUE TITLE
Way to map json properties at method level

### ISSUE THREAD

**Issue by gustavolira** [swagger-api/swagger-core#1554]
Would be nice if was possible to define the json properties at method level with annotation (without use a bean class). For example I have a service that receive a abritrary json using @RequestBody with HashMap like this:

``` javascript
public ResponseEntity<?> trocarSenha(@RequestBody HashMap<String, String> json)
```

I would like to define that json will be for example:

```
{
"login" : "",
"password": ""
}
```

**Comment by fehguy** [comment]
Hi, not exactly sure what you mean.  Are you talking about the schema?  The server default value?  Or perhaps an example?  And are you talking about spring-mvc or jaxrs?

**Comment by gustavolira** [comment]
Sorry for my explanation missing details.
I'm talking about schema Model Schema, in this case I'm not using bean class at my Service to receive the json from the cliente, I'm using a HashMap that is receiving the json from the client, but would be nice if there's some way to define how is the json that I'm expect for this service.
I'm using spring-mvc (spring boot to be precise)
Thank you very much for your attention

**Comment by webron** [comment]
@gustavolira - as with the previous issue, this seems like a [Springfox](https://github.com/springfox/springfox) integration and you should open the issue in their repo.
