### ISSUE TITLE
Define a custom json for a specific service

### ISSUE THREAD

**Issue by gustavolira** [swagger-api/swagger-core#1555]
Hi,

I'm using a service that has @RequestBody MyEntity entity. But this entity is really huge and has a lot of properties that for this specific service will be populate automatic but for other services I need to receive all properties.
Would be nice if exists some way to define the JSON that we expect to receive for a specific service.

**Comment by fehguy** [comment]
more details, please?

**Comment by gustavolira** [comment]
Imagine that we have a huge Entity that is used for a lot of services in one application.
At service A we need only a few properties of this entity, in other words the customer will send only a few properties of this entity. But in my Swagger documentation at mode schema is showing all the properties of the Entity, a lot of information that is not used for this service. Use @ApiModelProperty or @JsonProperty to hidden some attributes is not a option because or another service I will use this same entity but now receiving another properties.

How to tell swagger that I'm using this Entity but my model schema will be 'x' and on another service I will use this same entity but my model schema will be 'y' ?

**Comment by webron** [comment]
Any chance you're using Springfox and not swagger-core?

**Comment by gustavolira** [comment]
Hi,

Sorry for my miss information. Yes I'm using Springfox as wrapper of swagger

**Comment by fehguy** [comment]
If you were using pure swagger-core / swagger-jaxrs, you would simply define the interface of what you want to expose, and set that as the `responseClass`.  For Springfox, please open an issue in that repository, I'm sure they have this support in the framework.
