### ISSUE TITLE
After filtering swagger.json also remove no longer needed references

### ISSUE THREAD

**Issue by trallus** [swagger-api/swagger-core#1557]
Hi, I have two swagger.json files from which I only take parts and merge these to one file. 

For filtering I use a class that extends the AbstractSpecFilter, which works very well except that no longer needed references are still inside the merged json. At the moment i scan the parameters/responses of the operation in the isOperationAllowed method to find the ones that are still needed. At the moment this is based on a lot of casting and class filtering.

So I wanted to ask if it is possible to remove all no longer needed references in an easier way or if it would be possible to add a method to get all References for an Operation directly?

**Comment by webron** [comment]
You have references that are no longer needed or models that are no longer referenced? Not sure how the first one is happening - if it does, would appreciate an example to understand better.

**Comment by trallus** [comment]
Hi, thanks for your fast reply, it's the second case i have models that are no longer referenced and for me these are "no longer needed" inside the json, so I want to get rid of them.

**Comment by webron** [comment]
That sounds like a bug, I'm afraid as those should be filtered automatically. We try to filter out what's not needed (for example, tags are being filtered if they have no operations).

**Comment by webron** [comment]
Resolved in master.

**Comment by trallus** [comment]
Hello, I'm sorry to bother you again with this topic but after testing the new "isRemovingUnreferencedDefinitions" method i found two problems:

1. I have two responses that are just an array of objects, for which the reference is still there but the definition is removed e.g `[ Entry{...} ]` becomes `[ undefined ]`
2. Definitions of Models are not removed when they are inside other models, even if these are removed e.g. `MyUserDetails{ User {...} }` "MyUserDetails" is removed but "User" is not

**Comment by webron** [comment]
@trallus - would you mind opening a new ticket for those?
