### ISSUE TITLE
swagger ignores boolean fields in definitions

### ISSUE THREAD

**Issue by hstaudacher** [swagger-api/swagger-core#1561]
Here is my model class:

```java
public class Data {

  private final String foo;
  private final String bar;
  private final boolean foobar;
}
```

The definition swagger generates is:
```js
"Data": {
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "string"
    }
  },
  "type": "object"
}
```
I'm using swagger together with Jersey (JAX-RS) and swagger version 1.5.4.

I have not tested if this works for other primitives.

**Comment by webron** [comment]
Do you have any setters/getters at all? Because if not, to me `foo` and `bar` appearing there is a bug, not the other way around.

**Comment by hstaudacher** [comment]
moaw, thanks for the hint. The get method for the boolean didn't start with "is". Will close this issue.
