### ISSUE TITLE
nested object does not display correctly in model schema

### ISSUE THREAD

**Issue by JoeShi** [swagger-api/swagger-core#1567]
The nested object does not show in model schema (swagger UI), but correct in swagger editor.

Model schema is not correct
<img width="378" alt="screen shot 2015-12-14 at 5 38 14 pm" src="https://cloud.githubusercontent.com/assets/2173635/11777452/9a007190-a289-11e5-98e4-57be7e5852cf.png">

Model is correct
<img width="408" alt="screen shot 2015-12-14 at 5 38 18 pm" src="https://cloud.githubusercontent.com/assets/2173635/11777455/9e5775cc-a289-11e5-8945-0a645bc96e0e.png">

swagger editor is correct

<img width="842" alt="screen shot 2015-12-14 at 5 37 50 pm" src="https://cloud.githubusercontent.com/assets/2173635/11777470/ac93271c-a289-11e5-8118-c7d4daa6d395.png">

The following is my object definition.

```
NewEvent:
  type: object
  required:
    - summary
    - start
  properties:
    summary:
      type: string
      description: title of the event
    description:
      type: string
      description: detailed description of this event
    location:
      type: string
      description: location information
    start:
      $ref: "#/definitions/Time"
    end:
      $ref: "#/definitions/Time"
    recurrence:
      type: string
      enum:
        - none
        - daily
        - weekly
        - monthly
        - yearly
      default: none
```

**Comment by fehguy** [comment]
Please open that on swagger-ui
