### ISSUE TITLE
Swagger overrides custom Jersey ObjectMapper

### ISSUE THREAD

**Issue by m-radzikowski** [swagger-api/swagger-core#1569]
Hi,
I came across problem with using own `ObjectMapper` in JEE app. Normally when using Jersey we can define our own Mapper and inform app about it using `@Provider` annotation:

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import java.text.SimpleDateFormat;
import javax.ws.rs.ext.ContextResolver;
import javax.ws.rs.ext.Provider;

@Provider
public class ObjectMapperContextResolver implements ContextResolver<ObjectMapper> {
	private final ObjectMapper mapper;

	public ObjectMapperContextResolver() {
		mapper = new ObjectMapper();
		mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss"));
	}

	@Override
	public ObjectMapper getContext(Class<?> type) {
		return mapper;
	}
}
```

With this class in project Jersey serializes  `Date` using given custom format. Very simple example.

But when we add Swagger as maven dependency (just add, without even using it!) our `ObjectMapper` is no longer used and Swagger's one is used instead.

This problem seems to be known: https://groups.google.com/forum/#!topic/swagger-swaggersocket/dVavewJqiXc

Workaround is pretty simple - we have to modify Swagger's `ObjectMapper` instead of defining our own:

```java
@ApplicationPath("/")
public class RestApplication {
    public RestApplication() {
        Json.mapper().setDateFormat(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss"));
    }
}
```

But I think that overriding global REST configuration that have nothing to do with Swagger just by adding dependency is not the best thing. This way our REST is dependent on Swagger - removing Swagger from project accidently causes changing our API format. And the other way - adding Swagger to existing project may cause it's API break, altough it shouldn't change REST, only show it nicely (which is doing great! :smiley:).

Very simple project to illustrate this issue: https://github.com/m-radzikowski/SwaggerObjectMapperIssue
Just remove Swagger from dependency to see your API change (date format).

Tested on Wildfly 9.0.2 with Jersey 2.

**Comment by fehguy** [comment]
Hmm.  The swagger object mapper is supposed to only trigger on the Swagger object, not your own data.

**Comment by m-radzikowski** [comment]
This seems to not be an issue any more in Swagger 1.5.9 and/or WildFly 10.0. In fact, right now usiong `Json.mapper().setDateFormat()` did nothing I could observe in my API or swagger.json.

It may be closed now I think.

**Comment by webron** [comment]
Thanks for the update @m-radzikowski.
