### ISSUE TITLE
DefaultJaxrsScanner showing endpoints that are not annotated with Swagger annotations

### ISSUE THREAD

**Issue by kevinmic** [swagger-api/swagger-core#1573]
I am attempting to upgrade swagger in our java application. 

Previously endpoint methods that were not annotated with swagger annotations were ignored.   Now I see these rest endpoints showing up in our swagger documentation.

I realize I can annotate those methods with @ApiOperation(hidden=true) but I would rather have them ignored by default.

Example Code
```
// I dont want this to show in the swagger docs
@GET
@Path("/hello_notDocumented")
public String hello_notDocumented() {
   return "HELLO1";
}

@GET
@Path("/hello_documented")
@ApiOperation*(value="Hello should be documented")
public String hello_documented() {
   return "HELLO2";
}
```

**Comment by kevinmic** [comment]
A little more info, I am including in my project the following swagger dependencies

io.swagger:swagger-jaxrs:1.5.4
io.swagger:swagger-annotations:1.5.4

This is my setup code in our Application file.

```
 public MyApplication()
{
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.0");
        beanConfig.setBasePath(url);
        beanConfig.setScan(true);
        ScannerFactory.setScanner(new DefaultJaxrsScanner());
        beanConfig.setResourcePackage("mypath");
}
```

**Comment by webron** [comment]
Can you try not setting the scanner at all?

**Comment by kevinmic** [comment]
In my resources I am doing sub resources and I found that without the scanner it didn't seem to navigate all the way down through all of the sub resources.   With it turned on it does pick up everything (and more).

I can try removing it again and fiddling with the sub resources to see if I can get them to show up.

**Comment by fehguy** [comment]
hi @kevinmic, what version are you upgrading from?

**Comment by kevinmic** [comment]
I am upgrading from com.wordnik:swagger-jaxrs_2.10:1.3.12  and com.wordnik:swagger-annotations:1.3.10

**Comment by kevinmic** [comment]
Part of the reason I am upgrading is I am converting all of our resources from all having fixed @Path("/fixed/location") to instead chain our resources.    So I will only have one @Path annotation in my root resource, and all other resources will be sub resources.    The swagger I was using didn't seem to support sub-resources

**Comment by kevinmic** [comment]
I have tried removing the scanner and noticed that the endpoints that do show up, some of them still contain endpoints that are not annotated.   So my assumption is that removing the scanner won't fix my issue.

**Comment by fehguy** [comment]
You have many options for this, including creating a SwaggerSpecFilter to take away any operations that you don't want to have shown.  Please reopen if you feel that's not sufficient.
