### ISSUE TITLE
Would like multiple api base paths in swagger-ui

### ISSUE THREAD

**Issue by daw3rd** [swagger-api/swagger-core#1576]
This was originally posted to swagger-ui, but I was requested to post here instead.  The symptom begins with the swagger-ui.  However, as requested...

I have two separate sets of services in a single web app (tomcat, java, jersey, etc). The services are exposed as separate servlets in web.xml. As such I have separate base paths. Therein lies the rub I suppose. I have two swagger-ui/dist trees, one for each base path. But once the first access is made to either dist tree, the swagger-ui always presents the swagger.json from the first tree and won't switch to the other. I tried using a single web.xml entry specifying both paths in the basepath parameter, but this did not help. Any help/suggestions, much appreciated.

BTW, I saw a similar post but it was closed as out of scope. Googling shows many people looking for this capability. I hope you'll consider a way to support this sort of thing if it not currently.

**Comment by datalorax** [comment]
+1

**Comment by fehguy** [comment]
Please follow this PR.  It needs testing and feedback, so if you have time to do so it will accelerate things:

https://github.com/swagger-api/swagger-core/pull/1563
