### ISSUE TITLE
Field with @JsonProperty but no getter is being ignored

### ISSUE THREAD

**Issue by davidvc** [swagger-api/swagger-core#1581]
I am a bit mystified by this issue.  When I am getting the Swagger JSON from a Tomcat server using JAX-RS annotations for Swagger, if I have a model object that has a field annotated by @JsonProperty but which does not have a getter method, it is not included in the Swagger JSON.

For example, here is a class returned by an endpoint:

```
public class GetConfigurableContentResponse extends CodedResponseBase {
   @JsonProperty List<ConfigurableContent> content;
   public GetConfigurableContentResponse(List<ConfigurableContent> content) {
      this.content = content;
   }
}
```

And here is the definition for this object in the Swagger JSON

```
    "GetConfigurableContentResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ErrorResult"
          }
        }
      }
```

All these properties are from its superclass.  Note that the property "content" is not present in the Swagger JSON output

But I can't reproduce this in your standalone tests.

Given this class

```
   static class NoGetterClass {
      @JsonProperty
      private String noGetterProperty;
   }
```

I added this test to SimpleGenerationTest

```
    @Test
    public void testNoGetterBean() throws Exception {
       final Model model = context.resolve(NoGetterClass.class);
       final Map<String, Property> props = model.getProperties();
       assertEquals(props.size(), 1);

       final Property prop = props.values().iterator().next();
       assertEquals(prop.getName(), "noGetterProperty");

    }
```

And it works.  I modified the test to create a context using Json>.mapper() like the code does, and it still works

```
    private final ModelResolver modelResolver = new ModelResolver(Json.mapper());
    private final ModelConverterContextImpl context = new ModelConverterContextImpl(modelResolver);
```

Can you provide any guidance as to why things might be behaving differently in the context of a running service compared to your standalone tests?

Thanks,

David

**Comment by webron** [comment]
Apologies for the delayed reply. Have you managed to resolve the issue in the meantime or should we try and investigate it?

**Comment by davidvc** [comment]
Thanks for following up!

I resolved it by providing our own custom ModelResolver.  That part was
easy.  But it meant I had to upgrade our Swagger implementation, and that
part was hard.

While I have your ear, we seem to have a problem where swagger-core does
not accept extensions.  Is that on the roadmap?

Thanks!

David

**Comment by davidvc** [comment]
Sorry, not upgrade Swagger - we had to upgrade Jackson

**Comment by fehguy** [comment]
@davidvc I think we have a pretty good extension model now.  Have you seen how the [validations extension](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-hibernate-validations/src/main/java/io/swagger/validator/BeanValidator.java) works?

**Comment by davidvc** [comment]
Thanks for the quick response!

Perhaps we're talking about the same thing, but I'm not sure.  Sorry if I
wasn't clear.

The Swagger spec supports extensions --
http://swagger.io/specification/#vendorExtensions

But when we tried to add an extension to one of our Swagger-annotated
endpoints, it fails.  Details at
https://github.com/civisanalytics/swagger-diff/issues/20

I can open a new bug if that would help, but just wondering what your
thoughts are first.

Thanks!

David

**Comment by fehguy** [comment]
Got it, that's a totally different project, and unfortunately it's not under our control.  Looks like you'll have to ask them to get it supported.

**Comment by fehguy** [comment]
This should be fixed by https://github.com/swagger-api/swagger-core/commit/5aae81b68c44c7ac20c9177042234775d5e98f6b
