### ISSUE TITLE
RESTEasy JBoss 7.1.1 swagger.json is not generated

### ISSUE THREAD

**Issue by amreladawy** [swagger-api/swagger-core#1582]
I have a RESTEasy service on JBoss 7.1.1 through HTTPS. 

I am tying to generate swagger definition, so I added dependency in pom.xml as 

		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jaxrs</artifactId>
			<version>1.5.5</version>
		</dependency>

Then in my Application class I configured the BeanConfig as following.

```java
 public ApiApp(@Context ServletContext context) {
	WebUtil.loadServerInfoName(context.getServerInfo());
	BeanConfig beanConfig = new BeanConfig();
	beanConfig.setTitle("eigonic API");
	beanConfig.setVersion("1.0.0");
	beanConfig.setSchemes(new String[] { "https" });
	beanConfig.setHost("localhost:443");
	beanConfig.setBasePath("/api");
	beanConfig.setResourcePackage("com.egonic.api.res");
	beanConfig.setScan(true);
	beanConfig.setPrettyPrint(true);
    }
```
Now checking https://localhost/api/swagger.json 
Nothing is there.

**Comment by webron** [comment]
Is the context root of your app `/api`?

**Comment by amreladawy** [comment]
Yes, it is.  
https://localhost/api/v1/customers/1234  is an example of get Customer by ID

**Comment by amreladawy** [comment]
Any idea how can I troubleshoot this. I debugged it and found that my resources were detected by swagger configuration but it continues silently with no generated files

**Comment by webron** [comment]
Sorry for the delay. `https://localhost/api/v1/customers/1234` doesn't indicate that the context root is `/api` because it could be `/` as well. Do you see anything in your logs? Does the application return a 404 for the swagger.json url you try or something else?

**Comment by amreladawy** [comment]
Hi, 
The produced war file has the "/api" as context-root in the jboss-web.xml

I debugged the code, and I figured out that I need to annotate my resources with @Api so they can be picked up by the scanner.

Changing that for one Resource I got some logs like this 


DEBUG (Reader.java:746) - picking up response class from method public java.lang.String c.e.m.r.a.r.Products.outOfService(long)




After that still getting 404 on https://localhost/api/swagger.json
DEBUG (ModelConverterContextImpl.java:74) - resolveProperty class java.lang.String
DEBUG (ModelResolver.java:110) - resolveProperty [simple type, class java.lang.String]
DEBUG (Reader.java:849) - getParameters for [simple type, class long]
DEBUG (Reader.java:852) - trying extension io.swagger.jaxrs.DefaultParameterExtension@4054fcd5
DEBUG (ModelConverterContextImpl.java:74) - resolveProperty [simple type, class long]
DEBUG (ModelResolver.java:86) - Can't check class [simple type, class long], long
DEBUG (ModelResolver.java:110) - resolveProperty [simple type, class long]

**Comment by webron** [comment]
Hmm, do you ever load the swagger-core JAX-RS resources? Can you share your web.xml or the code that configures your resource scanning?

**Comment by amreladawy** [comment]
Hi Ron,
Thanks for the prompt response, here is the web.xml 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://java.sun.com/xml/ns/javaee"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
	version="3.0">
	<display-name>api</display-name>
	<context-param>
		<param-name>resteasy.role.based.security</param-name>
		<param-value>true</param-value>
	</context-param>
	<servlet>
		<servlet-name>RESTEasy JSAPI</servlet-name>
		<servlet-class>org.jboss.resteasy.jsapi.JSAPIServlet</servlet-class>
	</servlet>
	<servlet-mapping>
		<servlet-name>RESTEasy JSAPI</servlet-name>
		<url-pattern>/rest-js</url-pattern>
	</servlet-mapping>
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>Resteasy</web-resource-name>
			<url-pattern>/v1/*</url-pattern>
		</web-resource-collection>
		<user-data-constraint>
			<transport-guarantee>CONFIDENTIAL</transport-guarantee>
		</user-data-constraint>
		<auth-constraint>
			<description>All rolls</description>
			<role-name>*</role-name>
		</auth-constraint>
	</security-constraint>
	<login-config>
		<auth-method>BASIC</auth-method>
		<realm-name>myRealm</realm-name>
	</login-config>
	<security-role>
		<role-name>employee-create</role-name>
	</security-role>
	<security-role>
		<role-name>employee-update</role-name>
	</security-role>
	<security-role>
		<role-name>employee-delete</role-name>
	</security-role>
	<security-role>
		<role-name>employee-view</role-name>
	</security-role>
	<security-role>
		<role-name>login</role-name>
	</security-role>
</web-app>
```

**Comment by webron** [comment]
That's the challenge with having so many implementations - there are so many different ways to initialize things. I'm not really seeing anywhere in the web.xml where you define the resource scanning. Do you do it elsewhere?

**Comment by amreladawy** [comment]
By Resource Scanning, do you refer to RESTEasy Resource Scanning, or Swagger Resource Scanning?

RESTEasy scanning is automatically done due to annotation on the Application Class and resources Classes

```java

@ApplicationPath("/v1")
public class ApiApp extends Application {
```

```java
@Path("products")
@Produces(MediaType.APPLICATION_JSON)
@Formatted
@Api
public class Products {
   ```

For swagger, the scanning is done by 
```javascript
beanConfig.setScan(true);
```

**Comment by webron** [comment]
Yeah, looking for the RESTEasy resource scanning. Can you share your Application class (looks like `ApiApp`)?

But the way, even if the resource scanning is configured correctly, based on what you shared the URL you should be searching is `https://localhost/api/v1/swagger.json` and not what you posted above.

**Comment by amreladawy** [comment]
Hi Ron,

Thanks for your support. The file was generated at https://localhost/api/v1/swagger.json

It required sending Authorization header but worked fine.

No need to annotate the Resources classes with @Api 


Thanks again.

**Comment by webron** [comment]
Thanks for the update. Happy to hear it worked out.

**Comment by webron** [comment]
Thanks for the update. Happy to hear it worked out.

**Comment by amreladawy** [comment]
Hi Ron,
I am working on another project that uses RESTEasy and Undertow. Should I open another incident or do u have some guide for Swagger on Undertow?

**Comment by webron** [comment]
Never even heard of Undertow until a few days ago. But since it is the web server, I don't see why it would be any different than running it on Jetty or Tomcat.

**Comment by srinimaharaj** [comment]
I am getting java.lang.ClassNotFoundException: io.swagger.jaxrs.config.BeanConfig while deploying the war into jboss.

I have below in my pom.xml for swagger and resteasy.
		<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jaxrs</artifactId>
            <version>1.5.0</version>
            <scope>compile</scope>
        </dependency>	

 <dependency>
	        <groupId>org.jboss.resteasy</groupId>
	        <artifactId>resteasy-jaxrs</artifactId>
	        <version>${resteasy.version}</version>
	        <scope>provided</scope>
</dependency>
