### ISSUE TITLE
add host, port, basepath configurations

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1583]
Currently configuration via BeanConfig and web.xml don't allow granular configuration of the host, port or basePath.  We should make them all configurable independently.

**Comment by webron** [comment]
We need to make sure that the functionality of setting `swagger.api.basepath` to a full URL still works for backwards compatibility.

It seems that if `swagger.api.basepath` is used to mention the `basePath` as defined in 2.0, we assume a `scheme` of HTTP which is wrong, so that needs to be fixed as well.

**Comment by suen** [comment]
I ran into same issue. I have several webapps (CXF) running inside Tomcat with ApiListingResource resouce, each configured with different BeanConfig values (configured via spring). I found that every time a new service get deployed during initial deployment, it overwrites the config values for the previously deployed ones. However, if a webapp is redeployed, it does not overwrite config values for the ones already running.

**Comment by fehguy** [comment]
I have confirmed that the `BeanConfig` is already implemented to support this.  For an `appplicationContext.xml`:

```xml
    <property name="schemes">
      <list>
        <value>https</value>
        <value>http</value>
      </list>
    </property>
    <property name="host" value="localhost:8002"/>
    <property name="basePath" value="/api"/>
```

Will correctly set the basePath, host, schemes array.  Likewise via programmatic configuration:

```java
BeanConfig bc = new BeanConfig();
bc.setSchemes(new String[] {"http", "https"});
bc.setHost("petstore.swagger.io");
bc.setBasePath("/api");
```

**Comment by fehguy** [comment]
@suen you're talking about a different issue--please follow #1514
