### ISSUE TITLE
Initiation exception while using swagger with Jersey 1

### ISSUE THREAD

**Issue by raghavendramanandi** [swagger-api/swagger-core#1587]
Hello Swagger team,

I am facing an issue while integrating swagger with my application. Please find the below stack trace.

type Exception report

message Servlet.init() for servlet jersey-servlet threw exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

```
javax.servlet.ServletException: Servlet.init() for servlet jersey-servlet threw exception
    org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    java.lang.Thread.run(Thread.java:745)
```

root cause

```
com.sun.jersey.spi.inject.Errors$ErrorMessagesException
    com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170)
    com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136)
    com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199)
    com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
    com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
    com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
    com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
    com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
    com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
    com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
    com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:577)
    javax.servlet.GenericServlet.init(GenericServlet.java:158)
    org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    java.lang.Thread.run(Thread.java:745)
```

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.65 logs.
Apache Tomcat/7.0.65

I'm using Jersey version 1. I'm following the steps specified in the below wiki
https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup-1.5

Please help me in fixing this issue.
I have made a good amount of research on-line, couldn't find any resolution. Please let me know if this issue has already been addressed. In this case, It would be great if you could give me a reference to the fix details. I apologize if this issue is already been addressed.

Below is the content of my web.xml

``` xml
<web-app id="WebApp_ID" version="2.4"
    xmlns="http://java.sun.com/xml/ns/j2ee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee 
    http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
    <display-name>*********</display-name>

    <context-param> 
        <param-name>contextConfigLocation</param-name>
        <param-value>
            classpath*:/META-INF/PersistenceContext.xml
        </param-value>
    </context-param>

    <listener>
        <listener-class>
            org.springframework.web.context.request.RequestContextListener
        </listener-class>
    </listener>
    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>

    <servlet>
        <servlet-name>jersey-servlet</servlet-name>
            <servlet-class> com.sun.jersey.spi.container.servlet.ServletContainer </servlet-class>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>
                classpath:ApplicationContext.xml
            </param-value>
        </init-param>
        <init-param>
            <param-name>com.sun.jersey.config.property.packages</param-name>
            <param-value>
                 io.swagger.jaxrs.json,
                io.swagger.jaxrs.listing,
                com.**********.rest, com.*************.restcleint
                </param-value>
        </init-param>
        <init-param>
            <param-name>com.sun.jersey.api.json.POJOMappingFeature</param-name>
            <param-value>true</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>


     <servlet>
        <servlet-name>Jersey2Config</servlet-name>
        <servlet-class>io.swagger.jaxrs.config.DefaultJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <init-param>
            <param-name>swagger.api.basepath</param-name>
            <param-value>http://localhost:8080/api</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>jersey-servlet</servlet-name>
        <url-pattern>/api/*</url-pattern>
    </servlet-mapping>

    <filter>
        <filter-name>AuthorizationFilter</filter-name>
        <filter-class>com.***********.******.****.*********Filter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>AuthorizationFilter</filter-name>
        <url-pattern>/api/*</url-pattern>
    </filter-mapping>

</web-app>
```

**Comment by fehguy** [comment]
Hi, it's pretty hard to tell from that stack trace as it's not providing any details on the error.

**Comment by raghavendramanandi** [comment]
Can you let me know what all information you need? I will try to provide them.

**Comment by fehguy** [comment]
Try enabling debug logging and sharing that output.

**Comment by raghavendramanandi** [comment]
Please find my log file content


Jan 06, 2016 1:40:57 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  io.swagger.jaxrs.json
  io.swagger.jaxrs.listing
  com.*******.*******.rest
  com.*******.*******.restcleint
Jan 06, 2016 1:40:57 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class com.*******.*******.rest.service.ResourceRestService
  class io.swagger.jaxrs.listing.ApiListingResource
  class com.*******.*******.rest.service.*******RestService
  class com.*******.*******.rest.service.*******RestService
  class com.*******.*******.rest.service.*******RestService
  class com.*******.*******.rest.service.HealthCheckRestService
Jan 06, 2016 1:40:57 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class io.swagger.jaxrs.json.JacksonJsonProvider
  class com.*******.*******.rest.mapper.AuthorizationExceptionMapper
  class com.*******.*******.rest.mapper.ResourceLockingExceptionMapper
  class com.*******.*******.rest.mapper.*******ExceptionMapper
  class com.*******.*******.rest.mapper.DateTimeParseExceptionMapper
  class com.*******.*******.rest.mapper.BaseExceptionMapper
  class com.*******.*******.rest.mapper.ParamExceptionMapper
  class com.*******.*******.rest.mapper.JsonProcessingExceptionMapper
  class com.*******.*******.rest.mapper.JpaSystemExceptionMapper
  class com.*******.*******.rest.mapper.OptimisticLockingFailureExceptionMapper
  class com.*******.*******.rest.mapper.GeneralSecurityExceptionMapper
  class com.*******.*******.rest.mapper.WebApplicationExceptionMapper
  class com.*******.*******.rest.mapper.EntityNotFoundExceptionMapper
  class com.*******.*******.rest.mapper.IllegalArgumentExceptionMapper
  class com.*******.*******.rest.mapper.*******ExceptionMapper
  class com.*******.*******.rest.mapper.RefundExceptionMapper
  class com.*******.*******.rest.mapper.*******ExceptionMapper
  class io.swagger.jaxrs.listing.SwaggerSerializers
Jan 06, 2016 1:40:57 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
Jan 06, 2016 1:40:57 PM com.sun.jersey.spi.inject.Errors processErrorMessages
SEVERE: The following errors and warnings have been detected with resource and/or provider classes:
  SEVERE: Conflicting URI templates. The URI template / for root resource class com.*******.*******.rest.service.HealthCheckRestService and the URI template / transform to the same regular expression (/.*)?
  WARNING: A HTTP GET method, public javax.ws.rs.core.Response com.*******.*******.rest.service.*******RestService.dryRefund(java.lang.String,com.*******.*******.dto.refund.RefundRequest) throws com.*******.*******.core.exception.RefundException,com.*******.*******.core.exception.*******Exception,com.*******.*******.core.exception.AuthorizationException,java.security.GeneralSecurityException, should not consume any entity.
  WARNING: A sub-resource method, public javax.ws.rs.core.Response com.*******.*******.rest.service.*******RestService.get*******(java.lang.String), with URI template, "", is treated as a resource method

**Comment by fehguy** [comment]
OK the clue is here:

```
Jan 06, 2016 1:40:57 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
Jan 06, 2016 1:40:57 PM com.sun.jersey.spi.inject.Errors processErrorMessages
SEVERE: The following errors and warnings have been detected with resource and/or provider classes:
SEVERE: Conflicting URI templates. The URI template / for root resource class com.*.*.rest.service.HealthCheckRestService and the URI template / transform to the same regular expression (/.)?
WARNING: A HTTP GET method, public javax.ws.rs.core.Response com.**.*.rest.service.*RestService.dryRefund(java.lang.String,com.*.*.dto.refund.RefundRequest) throws com.*.*.core.exception.RefundException,com.*.*.core.exception.*Exception,com.*.*.core.exception.AuthorizationException,java.security.GeneralSecurityException, should not consume any entity.
WARNING: A sub-resource method, public javax.ws.rs.core.Response com.*.*.rest.service.*RestService.get****(java.lang.String), with URI template, "", is treated as a resource method
```

Please remove these:

```
io.swagger.jaxrs.json
io.swagger.jaxrs.listing
```

temporarily from your scanning to see if it starts up fine.  My guess is that you have operations like such:

`/*`

and that the listing for `/swagger.json` is colliding with it.

**Comment by raghavendramanandi** [comment]
My guess was the same. I removed these(Below) two lines and deployed my
application. The application works fine without any issues.

io.swagger.jaxrs.json
io.swagger.jaxrs.listing


On Wed, Jan 6, 2016 at 7:42 PM, Tony Tam <notifications@github.com> wrote:

> OK the clue is here:
>
> Jan 06, 2016 1:40:57 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
> INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
> Jan 06, 2016 1:40:57 PM com.sun.jersey.spi.inject.Errors processErrorMessages
> SEVERE: The following errors and warnings have been detected with resource and/or provider classes:
> SEVERE: Conflicting URI templates. The URI template / for root resource class com.*.*.rest.service.HealthCheckRestService and the URI template / transform to the same regular expression (/.)?
> WARNING: A HTTP GET method, public javax.ws.rs.core.Response com.**.*.rest.service.*RestService.dryRefund(java.lang.String,com.*.*.dto.refund.RefundRequest) throws com.*.*.core.exception.RefundException,com.*.*.core.exception.*Exception,com.*.*.core.exception.AuthorizationException,java.security.GeneralSecurityException, should not consume any entity.
> WARNING: A sub-resource method, public javax.ws.rs.core.Response com.*.*.rest.service.*RestService.get****(java.lang.String), with URI template, "", is treated as a resource method
>
> Please remove these:
>
> io.swagger.jaxrs.json
> io.swagger.jaxrs.listing
>
> temporarily from your scanning to see if it starts up fine. My guess is
> that you have operations like such:
>
> /*
>
> and that the listing for /swagger.json is colliding with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1587#issuecomment-169332252>
> .
>



-- 
Thanks,
Raghavendra
9738212418

**Comment by fehguy** [comment]
OK, it seems like the routing of your application is too greedy to use the listing resource.  You'll need to mount the actual api calls under a subpath or something, or have a different routing strategy.

You can certainly do this:

```
@Path("/{foo : \\d+"}
```

if you are accepting numbers at the root of your app.  But if you have something that uses strings, Jersey is not able to differentiate between `/swagger.json` and `/foo`, hence the fatal error.

**Comment by botchniaque** [comment]
If you don't want to change your application's mapping you can override Swagger's Resource Mapping - see my answer for more details: http://stackoverflow.com/a/33516888/1680826

**Comment by raghavendramanandi** [comment]
Thanks Tony Tam and Szymon Bochniak

On Tue, Jan 12, 2016 at 1:51 PM, Szymon Bochniak <notifications@github.com>
wrote:

> If you don't want to change your application's mapping you can override
> Swagger's Resource Mapping - see my answer for more details:
> http://stackoverflow.com/a/33516888/1680826
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1587#issuecomment-170835110>
> .
>



-- 
Thanks,
Raghavendra
9738212418
