### ISSUE TITLE
Only using @JsonIgnore during serialization, but not deserialization

### ISSUE THREAD

**Issue by AdelineJolie** [swagger-api/swagger-core#1590]
I have come to a point where I need to display a field for the input model but hide it for the output model.

I have tried using @JsonIgnore coupled with @JsonProperty like this:
(http://stackoverflow.com/questions/12505141/only-using-jsonignore-during-serialization-but-not-deserialization)

```
class User{
@JsonIgnore
private String password;

@JsonIgnore
public String getPassword() {
return password;
}

@JsonProperty
public void setPassword(String password) {
this.password = password;
}
}
```

But swagger still shows password for both model. Is the stackoverflow answer (2012) still valid with with the actual version of jackson and swagger? Or is there something else in my project that is causing this not to work ?

I'm using Jackson 2.6.4 and springfox-swagger2 2.2.2

**Comment by fehguy** [comment]
Please use `@ApiModelProperty(hidden=true)` to hide the property

**Comment by AdelineJolie** [comment]
This will hide it from both input and output model as well (even if it is set on the getter or setter)

**Comment by fehguy** [comment]
Apologies.  Yes, that's true--you'll need to have separate models or interfaces defined in your resources.  Each model schema must be consistent across input or output.

**Comment by webron** [comment]
Since the issue is based on the usage of springfox, they may have an different solution as well. Please open the ticket on their repository and they may be able to provide more info.

**Comment by dohoon-oh** [comment]
I have same issue. Did you solve it?

**Comment by mwinkelmann** [comment]
Does anyone solved it in a nice way?
