### ISSUE TITLE
Swagger scans methods on JAX-RS resources not annotated to be Swagger operations

### ISSUE THREAD

**Issue by titiu7** [swagger-api/swagger-core#1593]
This issue is related to issue #1343. The fix that was provided allowed Swagger to skip methods without REST annotations which was just one part of the problem. In Swagger-Core v1.5.4, all the methods annotated to be REST service methods are scanned even if they don't have the annotation @ApiOperation. I believe this shouldn't be the case according to the Swagger documentation. 
As an example, let's assume we have the following method in a REST resource class:

@GET 
@Path("/")
public String getString() {
 String str = "test method";
 return str;
}
Swagger will include that method regardless the fact that it's not annotated with @ApiOperation. 
I had submitted a pull request that included the fix, but the Travis CI build failed, so I decided to create this issue. Can this be fixed in the upcoming versions? 

Thank you,

**Comment by fehguy** [comment]
You can control scanning, see here: https://github.com/swagger-api/swagger-core/releases/tag/v1.5.9
