### ISSUE TITLE
Field with @JsonIgnore is shown in model schema

### ISSUE THREAD

**Issue by jbrazdil** [swagger-api/swagger-core#1595]
I have this class, with ignored field ``ga``, but the field is still shown in the model schema.
```java
@AllArgsConstructor
@EqualsAndHashCode
public class GAV {

    @JsonIgnore
    @NonNull
    private final GA ga;

    @Getter
    @NonNull
    private final String version;

    @JsonCreator
    public GAV(@JsonProperty("groupId") String groupId,
            @JsonProperty("artifactId") String artifactId, @JsonProperty("version") String version) {
        this.ga = new GA(groupId, artifactId);
        this.version = version;
    }

    @JsonIgnore
    public GA getGA() {
        return ga;
    }

    public String getGroupId() {
        return ga.getGroupId();
    }

    public String getArtifactId() {
        return ga.getArtifactId();
    }

    @Override
    public String toString() {
        return getGroupId() + ":" + getArtifactId() + ":" + getVersion();
    }
}
```
```json
{
  "ga": {
    "groupId": "string",
    "artifactId": "string"
  },
  "version": "string",
  "groupId": "string",
  "artifactId": "string"
}
```

**Comment by webron** [comment]
For now you can use `@ApiModelProperty(hidden=true)` as a workaround.

**Comment by jbrazdil** [comment]
I've added ``@ApiModelProperty(hidden=true)`` but the ``ga`` is still shown in the model.

**Comment by webron** [comment]
Odd. Which version of swagger-core do you use?

**Comment by jbrazdil** [comment]
io.swagger:swagger-core:jar:1.5.6:compile

**Comment by jbrazdil** [comment]
I've did some debugging and found that in [ModelResolver#L305](https://github.com/swagger-api/swagger-core/blob/v1.5.6/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L305)
```
ApiModelProperty mp = member.getAnnotation(ApiModelProperty.class);
```
mp is null, even when ``_annotations`` in the member is:
```
_annotations = (com.fasterxml.jackson.databind.introspect.AnnotationMap) {
interface org.codehaus.jackson.annotate.JsonIgnore=@org.codehaus.jackson.annotate.JsonIgnore(value=true),
interface io.swagger.annotations.ApiModelProperty=@io.swagger.annotations.ApiModelProperty(reference=, allowableValues=, notes=, access=, hidden=true, dataType=, name=, readOnly=false, position=0, value=, required=false, example=)
}
```

**Comment by jbrazdil** [comment]
Ok, I have some classloading issues probably. The ApiModelProperty in _annotations was from different module than ApiModelProperty.class.

**Comment by jbrazdil** [comment]
I have resolved the classloading issue: set swagger-annotation dependency in the module where is GAV to provided. But now it see only @JsonIgnore annotation, and not @ApiModelProperty annotation.

(Field) f.getDeclaredAnnotations() on the da field returns orny @JsonIgnore.

**Comment by webron** [comment]
Yeah, that's a known limitation. Please see https://github.com/swagger-api/swagger-core/issues/1214#issuecomment-129709818.
