### ISSUE TITLE
add vendor extensions to ComposedModel

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1596]
They are not present

**Comment by fehguy** [comment]
see https://github.com/swagger-api/swagger-parser/issues/151

**Comment by nbruno** [comment]
@fehguy Is this an issue to add the vendor extensions field to ComposedModel? If so, ComposedModel already inherits it from AbstractModel.

**Comment by fehguy** [comment]
thanks @nbruno
