### ISSUE TITLE
MatrixParam mapping not correct (swagger 2.0 ,v1.5.6)

### ISSUE THREAD

**Issue by tangjwtj** [swagger-api/swagger-core#1597]
When use swagger 2.0 V1.5.6 (use swagger 1.0 v1.3.8 the result is correct) , MatrixParam mapping not correct , in swagger.json ,MatrixParam should be mapped into a matrix actually mapped into a body.

For example ,I define an interface like below:

```java
@GET
	@Path("/{id}")
	@Produces({ MediaType.APPLICATION_JSON })
	@ApiOperation(value = " ")
	public void getByid(@PathParam("id") int tagsId,
			@ApiParam(value = "serviceName") @DefaultValue("run_time") @MatrixParam("sortField") String sortField) {

	}
```
the swagger 2.0 mapping result is :
```json
{
  "get": {
    "tags": [
      "TagsServer"
    ],
    "summary": " ",
    "description": "",
    "operationId": "getByid",
    "produces": [
      "application/json"
    ],
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "required": true,
        "type": "integer",
        "format": "int32"
      },
      {
        "in": "body",
        "name": "body",
        "description": "serviceName",
        "required": false,
        "schema": {
          "type": "string",
          "default": "run_time"
        }
      }
    ],
    "responses": {
      "default": {
        "description": "successful operation"
      }
    }
  }
}
```
MatrixParam's name and type not correct.

**Comment by webron** [comment]
The spec itself doesn't support matrix params and swagger-core follows the spec. Please see https://github.com/OAI/OpenAPI-Specification/issues/69.

**Comment by jontejj** [comment]
Is it time to open this up again as it's now defined in version 3.0 of the Open API spec? https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterObject

**Comment by webron** [comment]
Nope. It would be implemented as part of the OAS3 implementation.

**Comment by jontejj** [comment]
I see that swagger UI is supporting version 3 of the spec? But I don't see any output in my service.json generated by io.swagger.jaxrs.listing.ApiListingResource for my @MatrixParam annotated parameters
