### ISSUE TITLE
ECONNRESET from Swagger servlet (?)

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-core#1598]
This was initially reported here: https://github.com/swagger-api/swagger-js/issues/679
but determined to likely be an issue on the Java side of things.

The short story is:
- I have a client written in node, using swagger-client.
- swagger.json is served up by the swagger java servlet.
- I can see the swagger.json in a browser, and if I download the file, I can load it correctly on the client
- I can NOT load the swagger.json from the localhost url on the node client. I get this error from swagger-client:

> Can't read from server. It may not have the appropriate access-control-origin settings.

And if I try to do the same operation manually using the http or request modules, I get an error like:

> 'Error: read ECONNRESET'
- I _can_ get the swagger.json via curl, and curl shows the appropriate CORS headers.
- I _can_ download e.g. the petstore swagger.json from the swagger-client.
- I am using jetty as the servlet engine, using 'mvn jetty:run'.
- I am using this method for enabling CORS:
  https://github.com/swagger-api/swagger-core/wiki/CORS-Support

**Comment by webron** [comment]
Can you share the output of `curl -I <swagger.json url>`?

**Comment by delenius** [comment]
$ curl -I http://localhost:8080/sfweb/rest/swagger.json
HTTP/1.1 200 OK
Date: Mon, 11 Jan 2016 22:20:42 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, OPTIONS
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
Content-Type: application/json
Content-Length: 0
Server: Jetty(9.3.5.v20151012)

**Comment by webron** [comment]
Thanks. So this is not a CORS issue, it's just the swagger-client lying (it's a known issue). The ECONNRESET is a bit more indicative. A bit. Which version of swagger-core do you use?

**Comment by delenius** [comment]
This one:

```
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      <version>1.5.4</version>
    </dependency>
```

**Comment by webron** [comment]
Well, the problem is unlikely to be with the swagger-core resource as it works in numerous other examples. I can only assume this is related to something in your environment. So you're using jetty - is this embedded jetty or just a webapp deployed on a local jetty? Even if localhost, does the request go through any kind of proxy?

**Comment by delenius** [comment]
Yes, I am using the mvn jetty:run method during development. No proxy.
And I can see the swagger file served up in the browser on the right URL... Is this normal:

> Content-Length: 0

?
I also see it in the CORS example, so I assume it is...

**Comment by webron** [comment]
For `curl -I`? Yes, it's normal.

I'm afraid I'm out of ideas. This doesn't seem to be related to swagger-core directly.
