### ISSUE TITLE
Problems with Swagger docs for APIs in separate WARs on one server

### ISSUE THREAD

**Issue by botchniaque** [swagger-api/swagger-core#1600]
I have 3 JAX-RS (1.0) APIs .war files in a single .ear file deployed on a Glassfish server. 

in version `1.5.4` I was facing some bootstrap problems - I did not get the pattern yet, but sometimes `paths` and `definitions` were not there (probably `BeanConfig.resourcePackage` cached other API's values. 

in version `1.5.6` I get Swagger docs only for the API that was called first. Calling Swagger for other APIs after first one got initialized returns HTTP 404. I have seen the commit making the 'initialized' flag static

**Comment by botchniaque** [comment]
Ok, I got around `1.5.4` issue by not using the `io.swagger.jaxrs.config.BeanConfig` which stores config values as statics - instead I use `io.swagger.jaxrs.config.DefaultJaxrsConfig` configured as servlet in `web.xml`. 

As for `1.5.6` - I get `swagger.json` only for one API (for the one I call first). For others HTTP 404 gets returned. 

I found this commit which declares `initialized` variable static
https://github.com/swagger-api/swagger-core/commit/e96fc248373c22129d79c394b01509918c39ff67

I understand the reasons for making it static - in `1.5.4` swagger description is not cached - it's being recalculated for each request (Jersey seems to create new instance of `io.swagger.jaxrs.listing.ApiListingResource` for each request, therefore `initialized` variable always returns `false`). 
But probably someone did not think of a case where same Swagger code is user for multiple API running in the same JVM.

**Comment by fehguy** [comment]
@botchniaque I suggest following this issue, which we're just about to start on:

https://github.com/swagger-api/swagger-core/issues/1514

I'm going to close this out as #1514 should cover it, please add comments to that one if you see anything missing.
