### ISSUE TITLE
Remove JacksonJsonProvider

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1604]
As reported several times, this class is causing too much trouble for those using server libraries which do not let you control the scanning for `@Provider` classes.  So we should take it out, and give folks a work-around for it (i.e. how to add it back).

**Comment by chaithchey** [comment]
is there any work around for this issue ?

**Comment by sailujanu** [comment]
Team,

Can you please update on this issue. We are kinda block with our swagger integration

**Comment by fehguy** [comment]
Yes, we are going to remove it in the next release.

**Comment by fehguy** [comment]
You can see this in 1.5.7-SNAPSHOT, available on sonatype-oss snapshots.

**Comment by sailujanu** [comment]
Thanks for your help. I will pull the jar and test with it and get back to you

**Comment by sailujanu** [comment]
Thanks Tam. it is working fine. My issue got resolved. When can we expect this jar will be available in mvn repo. I want to put this as dependency.  Currently I added this jar manually into project lib folder.

**Comment by fehguy** [comment]
we have a few tickets to close before releasing.  It won't be long but you should continue with the snapshot.  Reference sonatype snapshots in your pom file and you can build "normally"

**Comment by sailujanu** [comment]
im not using mvn instead using ivy.xml.so not sure how to pull snapshot from sonatype
