### ISSUE TITLE
VIew json through Swagger UI

### ISSUE THREAD

**Issue by Aryadeb** [swagger-api/swagger-core#1606]
Can anyone please tell me If I wish to view the generated Swagger json/yaml into a custom built Swagger UI,how can I integrate the same in this java project?

**Comment by webron** [comment]
Can you give more details? The question is unclear.

**Comment by Aryadeb** [comment]
Sure.I followed the tutorial provided at this link 
https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup-1.5 and have been successful in creating a java project which generates swagger defination for a restful webservice.I get the swagger.json/yaml file at the root context as explained in this tutorial.
However to view the swagger file I need to fo the the swagger.io where they have an online editor and can view them and test the webservices.
Is it possible to have a swagger UI client inbuilt so that if I say view the swagger generated file at a webpage hosted in my local webserver?
ANY HELP WILL BE APPRECIATED

**Comment by webron** [comment]
[swagger-ui](https://github.com/swagger-api/swagger-ui) is just a set of static pages that you can either host on a different web server or pack it up with your application as you would any other web content. Simply clone the repository and copy the contents of the /dist dir to the wherever you'd like to host it and that's mostly it.

**Comment by Aryadeb** [comment]
Thanks..WIll try this out and will revert If I am facing issues.

**Comment by webron** [comment]
Sure thing. I'm closing the ticket for now since it's not really an issue with swagger-core. For general support, please send a note to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
