### ISSUE TITLE
Charset of @Produces Annotation are  ignored in Accept header

### ISSUE THREAD

**Issue by carstenlaengerer** [swagger-api/swagger-core#1609]
REST WS with charset in the Produce annotations result in wrong swagger.json. The charset is simple ignored.

@Produces("text/plain;charset=UTF-8") results to "produces" : [ "text/plain" ] in the swagger.json.

Hence, Calling the the REST WS by swagger result in HTTP 406

**Comment by webron** [comment]
Should be checked with `consumes` as well.

**Comment by frantuma** [comment]
related to #1546, fixed when #1680 is merged.
