### ISSUE TITLE
ApiModel doesn't work with ApiModel#value = "object" or "Object"

### ISSUE THREAD

**Issue by DrSchrumpfi** [swagger-api/swagger-core#1610]
If I use the annotation ApiModel on my resource classes and specify "object" or "Object" as alternative name (via #value), the resulting definition in the Swagger UI is empty.

I am using 'io.springfox:springfox-swagger2:2.3.1'.

**Comment by webron** [comment]
Please open the ticket on [Springfox](https://github.com/springfox/springfox).
