### ISSUE TITLE
Interesting use of JAX-RS and Swagger annotations confuses BeanConfig scanning

### ISSUE THREAD

**Issue by Helmsdown** [swagger-api/swagger-core#1614]
@olensmar @fehguy 

The following will make the most sense if you check out our example project we are using to expose the problem: https://github.com/jithumenon/swagger-karyon. 

Note: The swagger-karyon project README describes how to run the app.

We ran into a problem with BeanConfig's scanning logic in the following scenario:

1. You have a "root" resource class that (in the example I reference below this class is RootResource.java). This class is annotated with JAX-RS's @Path as well as Swagger's @Api.
2. RootResource exposes child resources by an instance method, annotated with an @Path, that returns an instance of a "child" JAX-RS annotated class (for this example the child resource will be called PetResource.java)
3. PetResource.java has a class level @Api annotation and its methods implement the actualy JAX-RS endpoints (methods with a @GET, @POST, etc). 

The current implementation of BeanConfig.java looks for the following:
1. Classes that have an @Api annotation
OR
2. Classes that have a @Path annotation
OR
3. Classes that have a @SwaggerDefinition annotation

With our example, the "root" resource is picked up by BeanConfig's annotation scan (which is good and expected) but the "child" resources are picked up and considered "root" resources as well. The swagger ends up with paths that are not actually in the working API (For example the swagger.json in the aforementioned example contains a /findByStatus when the real path is /api/1.0/pets/findByStatus).

While investigating this issue I modified BeanConfig's scanning logic to completely ignore classes with an @Api and only search for classes annotated (at the class level) with @Path. This fixed the problem for me...but I suspect it might cause problems for others if this were merged in. 

Your thoughts and advice? Have you seen this before? I am willing to submit a PR to make BeanConfig smarter.

Thanks!

**Comment by fehguy** [comment]
@frantuma you've been working on similar code--do you have any ideas on this?

**Comment by frantuma** [comment]
@fehguy issue is also related to the way Reader identifies sub resources; it currently scans for @Api annotated return types in method of root resource; therefore it "correctly" identifies subresource if annotated with @Api and creates correct path/operation including parent, but because subresource is annotated with @Api it processes it again wrongly as root resource;

As @Helmsdown mentioned, if @Api annotated classes are not considered while scanning (in BeanConfig), the issue doesn't occur; I would say that it shouldn't cause bad side-effects, because in a jax-rs environment root resources should anyway be annotated with @Path.

This is possibly easiest option, alternatively anyway above behaviour doesn't seem to fully match jax-rs spec, and we could maybe just update Reader to consider jax-rs subresources locator identifiers while identifying sub resource.

**Comment by fehguy** [comment]
I believe we tackled this before, namely in this sample:

https://github.com/swagger-api/swagger-samples/tree/master/java/java-jaxrs-subresource

The solution--albeit hacky--is to annotate the subresource and set `hidden=true` as shown [here](https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs-subresource/src/main/java/io/swagger/sample/resource/OwnerResource.java#L25).

Now, this sample uses web.xml and not BeanConfig.  I don't think that would cause a difference though.

Am I missing something?

**Comment by Helmsdown** [comment]
I will try first thing tomorrow and confirm this fixes the problem. If so I
will close issue and PR.

On Wednesday, January 20, 2016, Tony Tam <notifications@github.com> wrote:

> I believe we tackled this before, namely in this sample:
>
>
> https://github.com/swagger-api/swagger-samples/tree/master/java/java-jaxrs-subresource
>
> The solution--albeit hacky--is to annotate the subresource and set
> hidden=true as shown here
> <https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs-subresource/src/main/java/io/swagger/sample/resource/OwnerResource.java#L25>
> .
>
> Now, this sample uses web.xml and not BeanConfig. I don't think that would
> cause a difference though.
>
> Am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1614#issuecomment-173449750>
> .
>


-- 
Sent from Gmail Mobile

**Comment by frantuma** [comment]
@fehguy you're right, missed that; with web.xml I guess problem doesn't arise because it uses DefaultJaxrsScanner  (which doesn't scan @Api annotated classes) instead of BeanConfig, but as you say with hidden=true it works as expected also with BeanConfig

**Comment by Helmsdown** [comment]
@fehguy I tried the hidden flag on the subresources and it worked as you said. However, is there any reason not to make the code change though? Having to remember to put the hidden flag on sub-resources is a small perpetual annoyance (#firstworldproblems).

**Comment by frantuma** [comment]
seems related to #1106

**Comment by Helmsdown** [comment]
So it does!

**Comment by Helmsdown** [comment]
Another way of "automatically" hiding sub resources is to have the Scanner ignore them, no?

**Comment by fehguy** [comment]
I don't know a pretty way to do this.

You may have a resource and it's annotated as `@Api`, you don't know whether or not it should be at the root of the api definition or not.

You may have a resource which _is_ annotated with `@Api` AND you don't want to expose a subresource

You may have a resource which is annotated with `@Api` and belongs at both the root and attached as a subresource

I don't see any programmatic way to handle all these cases without saying "don't expose this at root level".

**Comment by Helmsdown** [comment]
I think you kind of lost me there...

Are my assumptions below correct?

1. Root resources should always be annotated with @Path at the class level
2. Purely Child resources should never be annotated with @Path (they are deriving their "parent path" behavior from their parent).
3. If a resource is both a root resource (meaning the class has a class level @Path) AND another root resource exposes it as a child resource then it is accessible by two URLs
4. If a given resource has an @Api annotation where hidden = true, that resource (and any subresources that it exposes) should not show up in the swagger.json (this should hold true regardless of whether the resources is a root or a not)

It all comes down to what BeanConfig is searching for since Reader is the one that actually detects and processes sub-resources.

WDYT?

**Comment by webron** [comment]
Closed following @Helmsdown's request ;)
