### ISSUE TITLE
Swagger not recognizing @XMLElementWrapper annotations

### ISSUE THREAD

**Issue by aymittal** [swagger-api/swagger-core#1615]
Hi,
I am trying to implement swagger in my existing project. But after i added its dependencies the jaxb annotations are ignored. I am configuring swagger as : 

```
      BeanConfig beanConfig = new BeanConfig();
      beanConfig.setTitle("REST API's");
      beanConfig.setVersion("1.0.0");
      beanConfig.setBasePath("/selfsvc/api");
      beanConfig.setResourcePackage("com.vi.rest");
      beanConfig.setScan(true);
```

i tried adding :
        `Json.mapper().registerModule(new JaxbAnnotationModule());`
        `Yaml.mapper().registerModule(new JaxbAnnotationModule());`
before swagger configuration.

**Comment by aymittal** [comment]
Soved the issue. Just exclude the following dependencies from swagger dependency.

`<exclusion>`
`<groupId>com.fasterxml.jackson.jaxrs</groupId>`
`<artifactId>jackson-jaxrs-json-provider</artifactId>`
`</exclusion>`
`<exclusion>`
`<groupId>com.sun.jersey</groupId>`
`<artifactId>jersey-client</artifactId>`
`</exclusion>`
`<exclusion>`
`<groupId>com.sun.jersey</groupId>`
`<artifactId>jersey-core</artifactId>`
`</exclusion>`
`<exclusion>`
`<groupId>com.sun.jersey</groupId>`
`<artifactId>jersey-server</artifactId>`
`</exclusion>`

After excluding these i was able to resolve this issue.

**Comment by fehguy** [comment]
This is fixed in master.
