### ISSUE TITLE
ApiListingResource has a class level @Path("/") which can collide with other JAX-RS resources

### ISSUE THREAD

**Issue by Helmsdown** [swagger-api/swagger-core#1620]
The current ApiListingResource has a class level @Path("/") annotation. This is causing us a minor annoyance in that we have dependencies which also do the same thing and collide. We are currently getting around this by sub-classing ApiListingResource and redefining the the path to @Path("/swagger") (so we access the swagger json via /swagger/swagger.json).

Looking at the endpoints offered by ApiListingResource I see why this was done. You wanted to support the following URLs for grabbing the swagger config:

/swagger (with an Accepts of application/yaml) -> returns yaml
/swagger (with an Accepts of application/json) -> returns json
/swagger.json (returns json)
/swagger.yaml (returns yaml)

With that being said a @Path("/") is a bit "greedy" and sets the ApiListingResource to collide with other "greedy" resources.

I see two possible solutions:
1. Support only /swagger.json & /swagger.yaml in ApiListingResource. This would allow you have a class level  @Path("/swagger.{type:json|yaml}").
2. Move the /swagger endpoints to a different class with a class level @Path("/swagger"). If a swagger user depends on calling /swagger then they would need to make sure that this new resource is registered with the container (if they are registering the "io.swagger.listing" package then this would be done for them already). 

WDYT? I am willing and able to submit a pull request to help resolve this.

Thanks!

**Comment by webron** [comment]
Yeah, it's a known issue.

Personally, I'm okay with solution 1. The support for the `/swagger` endpoint with the accept header was added a few releases ago per some user request (and PR). We probably shouldn't break that functionality, and if there's a workaround provided, it may be enough because I doubt many people rely on it. However, let's hear what @fehguy has to say as well.

**Comment by mikerott** [comment]
Related to issue #1647

**Comment by fehguy** [comment]
@Helmsdown I think that works.  Let's set the path-level path and then the routing should take care of it.  If you can send a PR that'd be great.

**Comment by Helmsdown** [comment]
Do you still want to support the /swagger endpoint?

On Monday, February 8, 2016, Tony Tam <notifications@github.com> wrote:

> @Helmsdown <https://github.com/Helmsdown> I think that works. Let's set
> the path-level path and then the routing should take care of it. If you can
> send a PR that'd be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1620#issuecomment-181717848>
> .
>


-- 
Sent from Gmail Mobile

**Comment by fehguy** [comment]
Yes, but making it less greedy so only matches on `/swagger.json` and `/swagger.yaml` would help a lot.

**Comment by webron** [comment]
We'd need to note in the release notes that it's a breaking change though.

**Comment by fehguy** [comment]
? it's not breaking, that's how it's currently working.  ApiListingResource maps `/swagger.json` to the documentation.  What am I missing?

**Comment by webron** [comment]
It also maps `/swagger`, and if we remove that it's a breaking change for whoever depends on it.

**Comment by Helmsdown** [comment]
So to reiterate:

1) we want to continue supporting /swagger endpoint that hinges off the Accepts header to return either json or yaml. This functionality should be moved to a new resource class with a class level Path annotation. 
2) The current ApiListingResource will have a class level Path annotation that is "/swagger.{type:json|yaml}"
3) Anyone who depends on the /swagger endpoints will need to make sure that their are either scanning io.swagger.listing package or specifically registering the new /swagger Resource class.

**Comment by webron** [comment]
Sounds good.

**Comment by Helmsdown** [comment]
Any suggestions for the /swagger listing class name? AcceptHeaderApiListingResource?

**Comment by webron** [comment]
ApiListingResrource2 ;) Honestly, not too concerned with the name.

**Comment by Helmsdown** [comment]
Ok @webron and @fehguy take a look at #1663 and let me know what you think.
