### ISSUE TITLE
Not able to print query parameters bundled in a rest service

### ISSUE THREAD

**Issue by madhurikorlepara** [swagger-api/swagger-core#1622]
When the path/query parameter is a string/int basic data type, @ApiParam does the job of printing on swagger ui perfectly. But when you bundle them together into a object, which in this instance is CatRequestParam  which contains query parameters for filteration like zip code. dont come up when you git swagger-ui.
I want to display the member variables within CatRequestParam like zipcode  to be displayed on swagger ui as operation's input paramters,  not the class CatRequestParam .

Is there any annotation like @ApiParam(class = CatRequestParam.class) that I can use?
 
@RequestMapping(value = "/cats", method = RequestMethod.GET, produces = "application/json")
@ResponseBody
@ApiOperation(value = "getCats", tags = "pets", notes = "gets all pet cats")
@ApiResponses(value = { @ApiResponse(code = 200, message = "A Basic getcat reponse", response = CatResponse.class), })

public CatResponse get(
			@ApiParam(name = "shelterId", value = "Unique identifier for the shelter", required = true) @PathVariable(value = "shelterId") int shelterId,
			 CatRequestParam requestParams) {

//some logic to return the cats of a particular shelter according to filter queryparams in requestParams object
}
}

**Comment by webron** [comment]
You got the wrong project. This looks like [Springfox](https://github.com/springfox/springfox). Please open the issue there.
