### ISSUE TITLE
Swagger not working with JBoss 5.

### ISSUE THREAD

**Issue by meetvijayat** [swagger-api/swagger-core#1624]
Swagger is not working with Jboss and throwing exception "org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found  [vfszip:xxxx/xxx/xxx"

Swagger is not recognizing vfszip UrlType.

2016-01-24 07:28:10,748 -0800 level=WARN  class=org.reflections.Reflections              could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [vfszip:/Users/xxxxxx/Install/whp/whp-jboss-web-5/server/default/deploy/xxxx/xxxxx.war/WEB-INF/classes/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:109)

**Comment by gbenaderet** [comment]
I have the same problem, anyone can fix it?

**Comment by webron** [comment]
That's a dependency issue. You need to force it to load a newer version of reflections.org.
