### ISSUE TITLE
Cannot see swagger.json (Spring + RestEasy + Tomcat)

### ISSUE THREAD

**Issue by guyh-tointv** [swagger-api/swagger-core#1625]
Hi,

I have a standard Spring application running on Tomcat.
I am using Resteasy to expose REST api, and now, I am trying to use swagger for API documentation.

I have read all about how to configure swagger with spring and resteasy, but, unfortunately, I cannot generate the swagger.json file.

All I have done is add the following lines to the application content xml file:

```
<bean id="apiListingResourceJSON" class="io.swagger.jaxrs.listing.ApiListingResource"/>
<bean id="apiDeclarationProvider" class="io.swagger.jaxrs.listing.SwaggerSerializers"/>

<bean id="beanConfig" class="io.swagger.jaxrs.config.BeanConfig">
	<property name="title" value="Swagger Sample App"/>
	<property name="version" value="1.0.0" />
	<property name="basePath" value="http://localhost:8080/media-web"/>
	<property name="resourcePackage" value="com.company.media.facade.web.rest.interfaces"/>
	<property name="scan" value="true"/>
</bean>
```

And added the following to my pom.xml file
```
<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-jaxrs</artifactId>
    <version>1.5.6</version>
</dependency>
```
 
Since the context root of my application is: http://localhost:8080/media-web, I expect to the see the swagger.json at: http://localhost:8080/media-web/swagger.json

Here is part of my web.xml file:
```
	<context-param>
		<param-name>webAppRootKey</param-name>
		<param-value>media-web</param-value>
	</context-param>
```

When I use my browser and try to navigate to: http://localhost:8080/media-web/swagger.json, i get the following error:
```
WARN  [PageNotFound] - No mapping found for HTTP request with URI [/media-web/swagger.json] in DispatcherServlet with name 'mediamanager'
```

Any help will be highly appreciated. 
Or at least let my know how to I turn on swagger logs, so I will try to see what is going on here.

Thanks
Guy Hudara

**Comment by webron** [comment]
Hi Guy! Erev tov! 

How do you set up the resource scanning of RESTEasy? web.xml configuration? spring configuration? An Application class? Other than the context-param, do you set a default path to your API? What does an example URL for a resource you have look like?

**Comment by guyh-tointv** [comment]
Hi Ron, Erev Toc Gam Lecha :-)

I have the resteasy-servlet.xml file, in which I scan the beans as follows:
```
<context:component-scan base-package="com.company.media.facade.web.rest" />
```

No default path. An example for the URL is:
```
http://localhost:8080/media-web/restful/resouce
```

BTW: I have moved to use Enunciate. Cool tool :-)

Thanks
H Guy

**Comment by webron** [comment]
In that case, do you still want to pursue troubleshooting for this issue?

**Comment by guyh-tointv** [comment]
Not for now, thank you.

H Guy
