### ISSUE TITLE
Swagger 1.5.x doc: little wiki update

### ISSUE THREAD

**Issue by boly38** [swagger-api/swagger-core#1626]
Hi
If someone of the swagger project could append this to this wiki page:
    https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup-1.5

for this feature:
    setFilterClass(Sting)	filterClass	Sets a security filter for Swagger's documentation.

append this information: 
     a class that extends "io.swagger.core.filter.SwaggerSpecFilter"

thanks

**Comment by fehguy** [comment]
sure, done.
