### ISSUE TITLE
SwaggerSpecFilter & API Visibility with Custom Annotations

### ISSUE THREAD

**Issue by mtraynham** [swagger-api/swagger-core#1627]
`@API` & `@APIOperation` both have a "hidden" property you can set, but it's not configurable.  It would be nice if we could add our own Annotations to filter these out, but that would require the `isOperationAllowed` function to be passed the Method reference.

Probably related to:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/LgrU5ecwcoE

Here's the best way I have found filtering Operations out is to add a custom `SwaggerSpecFilter` and use `@APIImplicitParams`.  Also, `@APIImplicitParam` type is required...  Dead simple example:

```
@Path("/pets")
@ApiImplicitParams(@ApiImplicitParam(access = SwaggerPublicApiAccessSpecFilter.PUBLIC, type="header"))
public Pet getAll() {
    return store.getAll();
}
```

```
public class SwaggerPublicApiAccessSpecFilter implements SwaggerSpecFilter {
    public static final String PUBLIC = "public";

    @Override
    public boolean isOperationAllowed(Operation operation, ApiDescription api, Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
        // Return false for operations that don't have the PUBLIC access implicit param
        return operation.getParameters().stream()
                .filter(parameter -> PUBLIC.equals(parameter.getAccess()))
                .findAny()
                .isPresent();
    }

    @Override
    public boolean isParamAllowed(Parameter parameter, Operation operation, ApiDescription api, Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
        // Remove the public access implicit param
        return parameter.getAccess() == null || !parameter.getAccess().equals(PUBLIC);
    }

    @Override
    public boolean isPropertyAllowed(Model model, Property property, String propertyName, Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
        return true;
    }
}
```

**Comment by mtraynham** [comment]
Another bug with any of the above...  Any operation that is not allowed, automatically removes the tag it's contained in.
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java#L62
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java#L74

**Comment by fehguy** [comment]
I really don't understand the suggestion here.  You can't override values in an annotation as they are final.  The swagger spec filter seems to be _the_ solution for dynamic filtering, as you've pointed out.

**Comment by mtraynham** [comment]
Ya know, after reading what I wrote, you're right, I didn't make the suggestion clear.  

It would be nice if there was some way to get annotations from the original method reference in the `isOperationAllowed` function.  As it stands, the method essentially only has access to the Swagger spec properties on the resource.  In some cases, you may want to extend that functionality to other method properties, such as a visibility annotation that is user owned.  For instance, when a user has some particular credentials, we would have a way to filter out the resources they don't have access to.

So changing the signature and adding support for:
`public boolean isOperationAllowed(java.lang.reflect.Method method, Operation operation, ...`

At this point though, you have to hack that kind of functionality in with APIImplicitParams.

**Comment by fehguy** [comment]
Ah, got it, and that makes sense.  The parameters passed in the SwaggerSpecFilter are decoupled from the annotations, and you've pointed out a disconnect in the data that's provided.

I think to do what you want would require passing _all_ annotations to the SwaggerSpecFilter, not just the Swagger annotations.  That is doable but a little ugly.  I'm not sure there's another way to do it, though.

**Comment by asafbennatan** [comment]
any news regarding this?,
as i understood swagger does not respect jsonview /ignore ,i wanted to manually write a filter that would , but that requires getting the annotations of the property or at least the java class so you could do something like :
	Method getter = new MappedPropertyDescriptor(arg1.getName(), c).getMappedReadMethod();
			if(getter.isAnnotationPresent(JsonIgnore.class)){
				return false;
			}

**Comment by nitin02** [comment]
Hello, Is there any update on when this "enhancement" will be added?

**Comment by fehguy** [comment]
No, per comments above, adding the annotations into the filter would be quite ugly.  If you can propose a way to do it, we can consider merging
