### ISSUE TITLE
custom annotation on queryParam is interpreted as "body"

### ISSUE THREAD

**Issue by yuhanz** [swagger-api/swagger-core#1628]
@QueryParam before the method argument works properly. However, we defined custom annotation for parsing string query parameter into a Set<Long>, where this argument is considered as Parameter Type "body" by swagger.

The parameter name can be overridden by the name @ApiParam. Is there a way to override the parameter type?

**Comment by webron** [comment]
`@ApiParam` won't allow you to override the type but `@ApiImplicitParam` will (you'll be redefining the parameter from scratch). If you go with that path, you'd have to hide the original parameter manually (`@ApiParam(hidden=true)`).

**Comment by yuhanz** [comment]
Thanks for the quick response! will try out @ApiImplicitParam.

**Comment by yuhanz** [comment]
worked elegantly. thanks!
