### ISSUE TITLE
@ApiParam  not supported dataType propetry  then how to generate format='date'  in json doc for GET methods

### ISSUE THREAD

**Issue by anand4sn** [swagger-api/swagger-core#1631]
Hi All

I need to generate date format ("format": "date") in swagger json doc for GET parameters. Im using spring rest @RequestParam with @ApiParam() but in @ApiParma we dont have property like dataType then how can i generate format property in json doc . ("format": "date").if someone help on this it will be great help to me. Thanks in advance.

**Comment by webron** [comment]
The data type of the parameter itself should be a Date or something similar. However, you mentioned `@RequestParam` which means you're not actually using swagger-core, but most likely [springfox](https://github.com/springfox/springfox). Please open the ticket on their repo if you have an issue with it. They use our annotations, but the processing is done by them.
