### ISSUE TITLE
Get rid of io.swagger.jaxrs.listing.ApiListingResource or move it in another module

### ISSUE THREAD

**Issue by rmannibucau** [swagger-api/swagger-core#1638]
This endpoint can create issues in the case:

- the application relies on container scanning (which is defined by JAXRS specification) and it gets picked up
- the server uses a JAX-RS implementation where @Path("/") can make the routing win over user classes

Either setting a @Path to something else than root and/or moving this class to another module would solve it

**Comment by webron** [comment]
We can't get rid of it as it would be a breaking change. It being picked up by container scanning is the intended effect, so don't see the issue there. The `@Path("/")` is indeed and issue and is covered by #1620, so I'll be closing this issue in favor of that one.
