### ISSUE TITLE
ApiParam change class type

### ISSUE THREAD

**Issue by kevinmic** [swagger-api/swagger-core#1641]
I need to be able to override the class type on ApiParam but there appears to be no way to do that.   
Is there a way to do this that I am missing?

**Comment by webron** [comment]
Can you describe the use case for that?

**Comment by kevinmic** [comment]
I am implementing Merge Patch using this api -- https://github.com/fge/json-patch .    My endpoint takes the JsonMergePatch which I then use to merge any changes contained therein into the real object.   Here is an example.

```Java
  @PATCH
  @Path("/{id}")
   public Account update(@ApiParam(value = "ID of account", required = true) @PathParam("id") String id, @ApiParam(value = "Account object", required = true) JsonMergePatch patch) {
       ObjectMapper mapper = new ObjectMapper();
        Account account = getCurrentAccount(id);
        JsonNode node = mapper.readTree(mapper.writeValueAsString(account));
        node = patch.apply(node);
        
        Account updatedAccount = mapper.treeToValue(node, Account.class);
        return updateAccount(updatedAccount);
    }
```

So in this case the object I am actually passing in is an Account, but only the pieces of the account that you want to change.   JsonMergePatch captures the pieces passed in and applies it to my model object.   Ultimately I want to override JsonMergePatch with Account.

**Comment by webron** [comment]
Do you have a `MessageBodyReader` implemented or some sort of filter to that would convert the Account object to the JsonMergePatch prior to calling the method?

**Comment by kevinmic** [comment]
Maybe I am missing something but I don't see how the MessageBodyReader solves my problem.    The problem is once the incoming data is converted into my destination object I have lost the details of what the merge contained.   The main issue is null values passed in via JSON vs missing values.   A null value says update this field to null, a missing value says don't change this field.   Once I convert the JSON to a Java object I can't tell the difference between a value passed in as null, and a value not passed in at all.

So say I have this account object
{ name: "Name", number: "123", email: "myemail"}

If I get this merge patch
{ number: null, email: "newemail" }

then my resulting account object should now be
{ name: "Name", number: null, email: "newemail"}

I don't believe that I will be able to read my current object from the database in a MessageBodyReader in order to apply the merge properly.

**Comment by webron** [comment]
Okay. Currently we don't allow setting that explicitly and I'm not sure that we should. You can overcome it currently by hiding this parameter and adding one using `@ApiImplicitParam`.

**Comment by kevinmic** [comment]
I had tried ApiImplicitParam but wasn't able to get it to work.   I will try again.   If that works then it will fill my need.

**Comment by webron** [comment]
If it doesn't work, please share your code so we can suggest a solution.

**Comment by fehguy** [comment]
@kevinmic, @webron is pointing you in the right direction.  If you want to "lie" about the type, just mark the actual param as "hidden" and use an implicit param.  This is better supported than overriding the dataType in the `@ApiParam` annotation.  I do agree that the logic could be merged into one annotation, but suggest you follow this path for now.

**Comment by kevinmic** [comment]
Thanks, ApiImplicitParam did what I wanted.

**Comment by stianlagstad** [comment]
I hope it's ok that I ask about the same problem/use case here. I have this class:
```
import java.util.List;

import com.google.gson.JsonElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "MyClass",
    description = "Description.")
public class MyClass {

  @ApiModelProperty(value = "ID given by the API")
  private Long id;

  @ApiModelProperty(value = "Customizable extra data")
  private JsonElement additionalData;

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public JsonElement getAdditionalData() {
    return additionalData;
  }

  public void setAdditionalData(JsonElement additionalData) {
    this.additionalData = additionalData;
  }
}
```

I have some problems with the resulting swagger.json file because of the `JsonElement`-type I use for `additionalData`, so I would like to make it look like `additionalData` has another type (say `String`). How can I use `@ApiImplicitParam` when it's not on a method, but on a field in my class?

I would like to hide the orignal `additionalData` (as I've managed to do below), and add a new implicit field `additionalData` of type `String`:
```
import java.util.List;

import com.google.gson.JsonElement;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "MyClass",
    description = "Description.")
public class MyClass {

  @ApiModelProperty(value = "ID given by the API")
  private Long id;

  @ApiModelProperty(value = "Customizable extra data", hidden = true)
  private JsonElement additionalData;

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public JsonElement getAdditionalData() {
    return additionalData;
  }

  public void setAdditionalData(JsonElement additionalData) {
    this.additionalData = additionalData;
  }
}
```

**Comment by stianlagstad** [comment]
Never mind. I just had to do this: `@ApiModelProperty(value = "Customizable extra data", dataType = "object")` :)
