### ISSUE TITLE
Add fields for request to @ApiOperation correspond to response

### ISSUE THREAD

**Issue by jiming** [swagger-api/swagger-core#1644]
Some time Restful Api will post Json content to serverside mapping to Class. 

Could you please add the two fileds in ApiOperation?

Class<?> request()
String requestContainer()

Thanks
Jiming

**Comment by webron** [comment]
Wouldn't that be the body parameter?

**Comment by jiming** [comment]
Dear webron,

Do you mean the User in the example code? I guess I can try. Thanks a log

public Response updateUser(
      @ApiParam(value = "name that need to be updated", required = true) @PathParam("username") String username,
      @ApiParam(value = "Updated user object", required = true) User user) {...}
