### ISSUE TITLE
Swagger Annotation doesnt work for same uri same http method but different request params and being lost in swagger spec generation 

### ISSUE THREAD

**Issue by pankajvijay2008** [swagger-api/swagger-core#1645]
Hi 
I have to 2 methods both has same URI same http method GET but passing different request parameter. Both methods has different business logic.when i am putting swagger annotation on both, only one is getting documented in spec generation. Is there any way to document both?
below is the sample code:

1st Method:
```
@ApiOperation(value = "Returns method 1 response, response = MyResponse.class)
@RequestMapping(method = RequestMethod.GET, value = "/bankEbill") 
@ResponseBody
public MyResponse getMyBillsResponse(HttpServletRequest request,
HttpServletResponse response) 
```
2nd Method:			
```
@ApiOperation(value = "Returns method 2 response, response = MyResponse.class)
@RequestMapping(method = RequestMethod.GET, value = "/bankEbill", params = { "billId" })
@ResponseBody
public MyResponse getMyBillResponse(@RequestParam("billId") long billId, 
 HttpServletRequest request,HttpServletResponse response) 
```

**Comment by webron** [comment]
@pankajvijay2008 you're using [Springfox](https://github.com/springfox/springfox) and not swagger-core, so the issue should be opened there and not here. However, the current version uniquely identifies an operation based on the HTTP method and the path - the parameters are not used to identify it. As such, you cannot describe that use case in general.

**Comment by chenlingmin** [comment]
+1
