### ISSUE TITLE
java.lang.IllegalArgumentException: Unrecognized Type: [null] with @BeanParam and extra methods

### ISSUE THREAD

**Issue by lwojtysiak** [swagger-api/swagger-core#1648]
Hi

I have:
- CXF 3.0.7
- swagger-jersey2-jaxrs 1.5.6

and configuration with Swagger2Feature of CXF.

The problem occurs with class annotated with @BeanParam. 
Inside this class I have one property

@HeaderParam
private String Range;

and setter/getter for it.

In this case everything works fine. But....

when I add some extra methods, i.e. 
public String getSomething() {
 return "something";
}

my app is crashing with:
> SEVERE: A child container failed during start
> java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
> 	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1123)
> 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:800)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
> 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:724)
> Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
> 	... 7 more
> Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
> Exception 0 :
> org.apache.cxf.service.factory.ServiceConstructionException
> 	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:219)
> 	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.init(JAXRSServerFactoryBean.java:142)
> 	at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load(JAXRSCdiResourceExtension.java:99)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
> 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
> 	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
> 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
> 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
> 	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
> 	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:133)
> 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:107)
> 	at org.jboss.weld.bootstrap.events.AbstractContainerEvent._fire(AbstractContainerEvent.java:54)
> 	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java)
> 	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
> 	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
> 	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:423)
> 	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
> 	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:149)
> 	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
> 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:724)
> Caused by: java.lang.IllegalArgumentException: Unrecognized Type: [null]
> 	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:406)
> 	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:354)
> 	at io.swagger.jaxrs.ext.AbstractSwaggerExtension.constructType(AbstractSwaggerExtension.java:53)
> 	at io.swagger.jaxrs.ext.AbstractSwaggerExtension.shouldIgnoreType(AbstractSwaggerExtension.java:45)
> 	at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:40)
> 	at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:82)
> 	at io.swagger.jaxrs.Reader.getParameters(Reader.java:854)
> 	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:830)
> 	at io.swagger.jaxrs.Reader.read(Reader.java:275)
> 	at io.swagger.jaxrs.Reader.read(Reader.java:147)
> 	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:172)
> 	at org.apache.cxf.jaxrs.swagger.Swagger2Feature.addSwaggerResource(Swagger2Feature.java:109)
> 	at org.apache.cxf.jaxrs.swagger.AbstractSwaggerFeature.initialize(AbstractSwaggerFeature.java:46)
> 	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.applyFeatures(JAXRSServerFactoryBean.java:252)
> 	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:196)
> 	... 31 more
> 	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
> 	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
> 	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:423)
> 	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
> 	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:149)
> 	at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:62)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5423)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	... 7 more

I have already tested in different configurations ant I'm sure that any extra method (with "getXXX") creates exception. When I changed the same method to "isSomething" - app works fine.

**Comment by fehguy** [comment]
Hi, can you please send a PR with a test case?

**Comment by ajkerr** [comment]
I was able to work around this issue temporarily by adding the com.fasterxml.jackson.annotation.JsonIgnore annotation to my "extra" method.

**Comment by pdjohe** [comment]
This issue seems due to Swagger's 'extractParameters' which locates the type first by field, then by setter. If the parameter has only a getter, the variable 'paramType' is null when sent to 'shouldIgnoreType' which gives the stacktrace the original poster gave.

I would suggest skipping the readonly parameters of BeanParams.

**Comment by fehguy** [comment]
@frantuma can you look at this?

**Comment by pdjohe** [comment]
The above commits still don't fix the error.

Fixed: modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/DefaultParameterExtension.java
Not fixed: modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java

https://github.com/frantuma/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java#L80

Any chance we can get this fixed before the next release?
