### ISSUE TITLE
swagger.json not getting created.

### ISSUE THREAD

**Issue by patrickjamesbarry** [swagger-api/swagger-core#1651]
I am in a spring boot + jersey app, using this version of swagger.

```
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.5.6</version>
        </dependency>
```

I have read the docs, and configured swaggers as so:

```
@Configuration
public class AppConfig {
    @Configuration
    static class JerseyConfig extends ResourceConfig {
        public JerseyConfig() {
            register(MyResource.class);
            register(HealthCheckResource.class);
            configureSwagger();
        }

        private void configureSwagger() {
            register(ApiListingResource.class);
            register(SwaggerSerializers.class);
            BeanConfig beanConfig = new BeanConfig();
            beanConfig.setVersion(1.0);
            beanConfig.setSchemes(new String[]{"http"});
            beanConfig.setHost("localhost:9000");
            beanConfig.setBasePath("/api");
            beanConfig.setResourcePackage("com.my.resources");
            beanConfig.setPrettyPrint(true);
            beanConfig.setScan(true);
        }
    }
}
```

I have added @Api to the resource class, and I see swagger reading my resources in the logs.  However, swagger.json is never created?  Where do I go from here? I don't see any errors.

**Comment by not-null** [comment]
I am also facing same issue. 

Posted here as well [http://stackoverflow.com/questions/35215302/swagger-jersey-grizzly](url)

**Comment by webron** [comment]
@patrickjamesbarry - which URL do you try to use to access the swagger.json? Which URL do you use for any of your APIs, for example?

**Comment by patrickjamesbarry** [comment]
I have tried the following urls:
http://localhost:9000/api
http://localhost:9000/test/api         <- "test" is the context root of my jersey resources.
I don't have any resources that are defined at @Path("/api")

I have also searched on the file system for swagger.json and that file is not found.  
spring-boot-starter-jersey version 1.3.2-Release

**Comment by webron** [comment]
The swagger.json doesn't generate a file on your file system. it's just a resource like any other jax-rs resource you expose via jersey. the basePath doesn't affect where the swagger.json is located, but it is the context root of your application (`/test` according to what you said?).

Based on that info, you should find it at http://localhost:9000/test/swagger.json

**Comment by patrickjamesbarry** [comment]
Thanks webron, that squared me away!

**Comment by webron** [comment]
@patrickjamesbarry are we good to close this ticket?

**Comment by patrickjamesbarry** [comment]
Yes, thank you!

**Comment by KiranShivarchak** [comment]
I deployed swagger in wildfly server i am not able to see documentation. 

Error: not able to read localhost:9090/projectname/swagger-ui.html
