### ISSUE TITLE
ApiModelProperty overrides required from XmlElement

### ISSUE THREAD

**Issue by GoGoris** [swagger-api/swagger-core#1654]
Hi, I don't know whether this is an issue of swagger itself or the maven plugin. When I add @ApiModelProperty without explicitly setting required to true, the documentation says required is false. However when I don't add it, the value of @XmlElement is used.

An example says more than thousand words:

required = true

    @XmlElement(required = true)
    private boolean active = true;
required = false

    @ApiModelProperty()
    @XmlElement(required = true)
    private boolean active = true;
required = true

    @ApiModelProperty(required = true)
    @XmlElement(required = true)
    private boolean active = true;

**Comment by webron** [comment]
Since `required` has a default value of `false`, it makes sense it overrides it.

**Comment by GoGoris** [comment]
Yes, but it doesn't make sense in my opinion if XmlElement is set. I thought that the library was trying to be compliant with the javax annotations, but only for required I have to explicitly set it (again) if I add a description using @ApiModelProperty.

**Comment by webron** [comment]
We have no way of knowing whether you set the value or not, because the annotation has a default value set (`false`). Our annotations will take precedence if you use them, so either don't use them, or you have to override the value.

**Comment by GoGoris** [comment]
Yes but why can't the annoation processor check first that this isn't set in XmlElement ? (swagger-jaxrs I guess?)

**Comment by webron** [comment]
Because by (our) definition, our annotations override JAXB/Jackson annotations to allow changing Swagger-related definitions as needed.

**Comment by GoGoris** [comment]
OK then, good to know this! Thanks for your feedback.
