### ISSUE TITLE
@XmlAttribute(required = true) is ignored

### ISSUE THREAD

**Issue by GlennVanSchil** [swagger-api/swagger-core#1659]
My problem is explained [here](https://stackoverflow.com/questions/35359260/springfox-swagger-make-definition-properties-required-with-xsd-model). 

My Objects are generated using an XSD file which contains @XmlAttribute(required = true) but this doesn't affect the properties in Swagger. When I add @ApiModel and @ApiModelProperty(required = true) It works fine but I don't want to do this manualy for a generated object.

**Comment by webron** [comment]
JAXB annotations are not parsed by default. #960 contains two methods to introduce the parsing. Keep in mind that in Springfox this may not work, and in that case you'd need to ask in their project.
