### ISSUE TITLE
zip-file download with spring controller

### ISSUE THREAD

**Issue by a-dudko** [swagger-api/swagger-core#1662]
Hello. I have a scala controller which puts in response's outputstream a zip file. If I use direct link, file is downloaded without problems. But when I execute request through swagger, file binary content is shown on UI and loading doesn't start.

```
@RequestMapping(value = Array("/get-response"), method = Array(RequestMethod.GET), produces = Array(MediaType.APPLICATION_OCTET_STREAM_VALUE))
@ApiOperation(value = "api-response", notes = "Receive Response Request.", responseContainer = "List", response = classOf[String])
def getResponse(response: HttpServletResponse): Unit = {
    response.setContentType("application/zip")
    response.addHeader("Content-Disposition", "attachment; filename=\"Response.zip\"");
    //writing to output stream
    response.flushBuffer()
  }
```

![swagger](https://cloud.githubusercontent.com/assets/3882333/13051676/9ee6d81c-d40b-11e5-8165-d1d881de1a1a.png)

How can I remove the binary body and get the file downloaded? Thanks

**Comment by AlexElin** [comment]
Hi, @a-dudko. It's  [the bug](https://github.com/swagger-api/swagger-ui/issues/1605)  in swagger-ui.

**Comment by fehguy** [comment]
This is fixed in swagger-ui.

**Comment by harish-nagarro** [comment]
Is this bug fixed. 
If so in which version ?
