### ISSUE TITLE
swagger missing model package

### ISSUE THREAD

**Issue by Gobliins** [swagger-api/swagger-core#1664]
I used the example auth.yaml from http://editor.swagger.io/#/ (just go open exmaple, basic auth) and generated jax-rs server code.

` swagger: '2.0'
info:
  version: "1.0.0"
  title: Basic Auth Example
  description: |
    An example for how to use Basic Auth with Swagger.
    Server code is available [here](https://github.com/mohsen1/basic-auth-server). It's running on Heroku.

**User Name and Password**
- User Name: `user`
- Password: `pass`
  host: basic-auth-server.herokuapp.com
  schemes:
  - http
  - https
    securityDefinitions:
    basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
    paths:
    /:
    get:
      security:
  - basicAuth: []
    responses:
    200:
      description:  Will send `Authenticated` if authentication is succesful, otherwise it will send Unauthorized `

Notice: there are no definitons of models.

I tried to compile the generated source but i get errors:

`error: package ...webservice.jaxrs.model does not exist`

and its true because there is no folder called model inside the jaxrs folder. But the package import comes from the mustache files and seems to be generated anyways.

Is this a bug?

**Comment by fehguy** [comment]
Yes, this is a bug--thanks for filing the issue, we can get this taken care of before the next release.

**Comment by fehguy** [comment]
This has been fixed.
