### ISSUE TITLE
Unable to run authentication process with v1.5.7

### ISSUE THREAD

**Issue by Tony-Proum** [swagger-api/swagger-core#1676]
Hello,

When trying to update swagger version from 1.5.6 to 1.5.7, I'm unable to get authentication process working (The On/Off button that's allow to get my app scope were unavailable in swagger-ui)

When I tried to see where was my mistake, I saws that the securityDefinitions object remains undefined in swagger ui. (Using SwaggerBootstrap exemple and multiple other examples)

The problem disappear when I downgrade to 1.5.6.

**Comment by fehguy** [comment]
This should be fixed now.
