### ISSUE TITLE
Unhandled Jackson @JsonUnwrapped annotation

### ISSUE THREAD

**Issue by scoro** [swagger-api/swagger-core#1682]
Hi,

I have found a functional gap in generating model using Jackson model specification. 
It does not respect @JsonUnwrapped annotation.

It seems that Swagger reads Jackson model as it as. 
Unfortunately Jackson does not expose flatten properties but handles it quite late (during serialization/deserialization), so generated Swagger model is also a tree one despite of @JsonUnwrapped.

Similiar issue has been fixed in other project:
https://github.com/springfox/springfox/issues/192

It would be nice to have this feature working.

**Comment by mapoulin** [comment]
+1

**Comment by frantuma** [comment]
implemented in #1833
