### ISSUE TITLE
Add ability to deprecate properties and parameters

### ISSUE THREAD

**Issue by emirkin** [swagger-api/swagger-core#1684]
It appears that there is no way to deprecate a parameter or property in swagger spec. The `deprecate: true` statement applies only at operation level

**Comment by fehguy** [comment]
This is a spec concern, not swagger-core.  Can you please open an issue on the [OAI Spec Repo](https://github.com/OAI/OpenAPI-Specification/issues)?

**Comment by emirkin** [comment]
Created https://github.com/OAI/OpenAPI-Specification/issues/584

**Comment by fehguy** [comment]
thank you
