### ISSUE TITLE
Configuration doesn't work

### ISSUE THREAD

**Issue by eniniz** [swagger-api/swagger-core#1685]
hi everyone,
I had a sample rest api, and I want to test swagger on it, 
I followed the steps mentioned in the guide [https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-RESTEasy-2.X-Project-Setup-1.5#using-the-application-class](url), but at the ends the documentation doesn't generate and my applications don't work too.(when I remove the configuration the api works)
I'm using rest easy and JBoss 7

**Comment by webron** [comment]
Can't really help without more details. What does your configuration look like? What have you tried doing? What was the result?

**Comment by eniniz** [comment]
thank you for responding; 
my configuration is : 
I'm using resteasy so I followed the configuration :Swagger Core RESTEasy 2.X Project Setup 1.5: 
[https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-RESTEasy-2.X-Project-Setup-1.5](url)

- First,I added the dependency to my project :
 `<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jaxrs</artifactId>
  <version>1.5.0</version>
</dependency>`

- then I Hooked up Swagger-Core in your Application :  using the application class : 
`   public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new HashSet();
        //resources.add(FirstResource.class);
        //resources.add(SecondResource.class);
        //...
        resources.add(io.swagger.jaxrs.listing.ApiListingResource.class);
        resources.add(io.swagger.jaxrs.listing.SwaggerSerializers.class);
        return resources;
    }`

- Finally I Configured and Initialized Swagger Using the Application class:
`    public SampleApplication() {
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.2");
        beanConfig.setSchemes(new String[]{"http"});
        beanConfig.setHost("localhost:8080");
        beanConfig.setBasePath("/api");
        beanConfig.setResourcePackage("io.swagger.resources");
        beanConfig.setScan(true);
    }`

and to run the app, I downloaded Swagger UI, in the dist folder I changed the url in the index.html to my app(localhost:8080/MayApp/api)

**Comment by frantuma** [comment]
Hi @eniniz did you register your Application in web.xml? and can you deploy/run and do your apis work ok, and can you access ../../swagger.json?

**Comment by eniniz** [comment]
> did you register your Application in web.xml?

I  didn't register it in web.xml, because I have done this using the Application class,
I taught that we can choose between theses choices

-  Manual registration using configuration switches
-  Automatic scanning and registration
-  Using the Application class
-  Using Spring

> can you deploy/run and do your apis work ok

nope my application doesn't work any more 

>  and can you access ../../swagger.json?

I dont know how to access it :(

**Comment by frantuma** [comment]
sorry bad wording, I meant `javax.ws.rs.Application` like:

```
    <servlet>
        <servlet-name>resteasy</servlet-name>
        <servlet-class>org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher</servlet-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>io.swagger.sample.PetStoreApplication</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
```

To be able to help we would need to see full config code, please share on  gist.github.com

As mentioned in guide the Swagger definition will be accessible at /swagger.json and /swagger.yaml at the context root of your application.

**Comment by fehguy** [comment]
I believe this can be closed as documentation has been updated.
