### ISSUE TITLE
Server vs Client generation differences on data validation

### ISSUE THREAD

**Issue by zanona** [swagger-api/swagger-core#1693]
I have noticed that most clients that can be generated through Swagger such as javascript will comply to JSON's Schema properties like `enum`, `maxLength`, `minimum`, `required`, etc for request body (i.e: /users/POST [User Model])

However from what I have tested, all generated server codes such as Node.js, Go, etc, will simply skip that information and leave the API wide open for accepting any kind of payload or wrong property format through the requests, differently than API in the wild such as Github's, Twitter, etc where those will probably filter the payload and block any unwanted data format or analyse of all required properties for the body object have been sent.

Is the fact that most generated servers are not analysing this information something that has been discussed before? It would be interesting to know the reason for validations being only made from client-side generated code leaving the API vulnerable?

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#2304
