### ISSUE TITLE
How to discard swagger annotations during run time

### ISSUE THREAD

**Issue by sunandabbytes** [swagger-api/swagger-core#1695]
I am using swagger-maven-plugin and generating swagger.json during build. I wanted this json during build so that I can play around with json later.

But I dont need all swagger annotations after the maven build after generating json. During runtime I dont need annotation to be there. How can I ignore or change retention policy of an annotation to ignore annotation during runtime.

**Comment by RobWin** [comment]
You can't.

**Comment by sunandabbytes** [comment]
I achieved it by putting <scope>provided</scope> for Swagger annotations dependency. Thanks.
