### ISSUE TITLE
Path.getOperationMap should preserve the insertion order

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-core#1696]
The method `Path.getOperationMap` should preserve the insertion order.
The `HashMap` should be replaced by a `LinkedHashMap`.

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Path.java#L170

That way we can render Path Operations in Swagger2Markup as defined in the Swagger file and not randomly.

**Comment by RobWin** [comment]
If you agree to this change, I can create a PR.

**Comment by webron** [comment]
@RobWin can't think of an issue with that. Feel free to submit a PR.

**Comment by RobWin** [comment]
Ok.thx. we have an issue in Swagger2Markup when we want to preserve the order of the user (contract-first design via the editor).

**Comment by webron** [comment]
Sure thing, but in general I advise users to not rely on the order as it is *technically* not preserved. It's represented as a JSON object which by definition does not preserve order. I know some parsers try to preserve it, but in general users shouldn't assume that it's just going to work.

**Comment by fehguy** [comment]
We've changed to use `LinkedHashMap`s
