### ISSUE TITLE
Scan Methods without @ApiOperation Annotation

### ISSUE THREAD

**Issue by TheNitek** [swagger-api/swagger-core#1697]
The doc states "Only methods that are annotated with @ApiOperation will be scanned and added the Swagger definition." However using swagger-jaxrs in version 1.5.7 this doesn't seem to be entirely true: All methods annotated with JAX-RS annotations are listed in the swagger.json file, but unfortunatelly without interpreting most of the annotations contents.

Example:

```
@GET
@Path("/ssl/clientCerts")
@Produces(MediaType.TEXT_PLAIN)
public String sslClientStatus() {}
```

Results in

```
"/monitoring/ssl/clientCerts":
{
 "get":{
  "tags":["monitoring"],
  "operationId":"sslClientStatus",
  "parameters":[],
  "responses":{
   "200":{
    "description":"successful operation",
    "schema":{"type":"string"},
    "headers":{}
}}}}
```

As you can see the content type is missing. Once I add the @ApiOperation, everything is fine.

For me it would be a great improvement to be able to generate a swagger.json without the need to add @ApiOperation to all my methods.

**Comment by fehguy** [comment]
As of 1.5.9, the logic for scanning has been updated:

https://github.com/swagger-api/swagger-core/releases/tag/v1.5.9
