### ISSUE TITLE
Property example serialization

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-core#1699]
Refs #1681 #1107, #1318, #1118, kongchen/swagger-maven-plugin#233

created from PR #1681 
#1681 fix doesn't solve neither #1107 (swagger-ui related, but probably solved by updating core/models) nor #1118 and it doesn't address similar discussion in kongchen/swagger-maven-plugin#233.

The following steps could be taken to cover the whole "area".

1 - Resolving from ApiModelProperty annotation.

similarly to discussion in kongchen/swagger-maven-plugin#233, code could be enhanced to parse example value according to format and property type.

2 - Array type deserialization in PropertyDeserialization.

Code could be enhanced by deserializing additional properties (which should be part of swagger schema if not mistaken) also for array types, e.g. "example".

**Comment by webron** [comment]
@frantuma - can this be closed?

**Comment by frantuma** [comment]
@webron, this is a "new" ticket from discussion in #1681, related to  #1107 and #1118 and targeting similar issue as in kongchen/swagger-maven-plugin#233.

**Comment by webron** [comment]
Ah. I thought #1681 was meant to close it.

**Comment by fehguy** [comment]
see #1107
