### ISSUE TITLE
swagger.json 404 Not found.

### ISSUE THREAD

**Issue by steowens** [swagger-api/swagger-core#1702]
I have done my best to follow the instructions set forth in the wiki, but I get no startup errors and I get a 404 when attempting to access /swagger.json

Here is my spring config:
```
<!-- Swagger -->
<bean id="apiListingResourceJSON" class="io.swagger.jaxrs.listing.ApiListingResource"/>
<bean id="apiDeclarationProvider" class="io.swagger.jaxrs.listing.SwaggerSerializers"/>

<bean id="beanConfig" class="io.swagger.jaxrs.config.BeanConfig">
        <property name="title" value="KMS Service"/>
        <property name="version" value="0.0.1" />
        <property name="schemes" value="http" />
        <property name="host" value="${env.kmsService.baseUrl:http://localhost:9095/api}" />
        <property name="basePath" value="/api"/>
        <property name="resourcePackage" value="com.foo.kms"/>
        <property name="scan" value="true"/>
    </bean>	


    <jaxrs:server id="kmsService" address="/">
		<jaxrs:providers>
			<bean class="com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider"/>
			<bean class="com.foo.kms.exceptions.JsonMappingExceptionMapper"/>	
		</jaxrs:providers>
		<jaxrs:serviceBeans>
			<ref bean="statusServiceBean"/>
			<ref bean="kmsServiceBean"/>
		</jaxrs:serviceBeans>
	</jaxrs:server>
    
```

**Comment by webron** [comment]
Which framework(s) do you use? Which URL have you tried?

**Comment by steowens** [comment]
I use Apache CXF JaxRS.  I have tried http://localhost:9095/swagger.json   and I have tried http://localhost:9095/api/swagger.json.  
I have tried updating my config to:
```<!-- Swagger -->
	<bean id="swaggerResource" class="io.swagger.jaxrs.listing.ApiListingResource"/>
    
    <bean id="beanConfig" class="io.swagger.jaxrs.config.BeanConfig">
        <property name="title" value="Disney Key Management Service"/>
        <property name="version" value="0.0.1" />
        <property name="schemes" value="http" />
        <property name="host" value="${env.kmsService.baseUrl:http://localhost:9095/api}" />
        <property name="basePath" value="/api"/>
        <property name="resourcePackage" value="com.foo.tss.kms"/>
        <property name="scan" value="true"/>
    </bean>	
	<!-- End Swager -->
	
	<bean id="amazonKMSKeystore" class="com.foo.tss.kms.logic.AmazonKMSKeystore"/>
    	
	<bean id="kmsServiceBean" class="com.disney.tss.kms.api.KeysService">
		<constructor-arg index="0" value="${env.authzClientId.attributeName:AUTHZ_CLIENT_ID}"/>
		<constructor-arg index="1" ref="amazonKMSKeystore"/>
	</bean>
	<bean id="statusServiceBean" class="com.foo.tss.kms.api.StatusService"/>
	
	<jaxrs:server id="kmsService" address="/">
		<jaxrs:providers>
			<bean class="com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider"/>
			<bean class="com.foo.tss.kms.exceptions.JsonMappingExceptionMapper"/>	
			<bean class="io.swagger.jaxrs.listing.SwaggerSerializers"/>
		</jaxrs:providers>
		<jaxrs:serviceBeans>
			<ref bean="swaggerResource"/>
			<ref bean="statusServiceBean"/>
			<ref bean="kmsServiceBean"/>
		</jaxrs:serviceBeans>
	</jaxrs:server>
```

The /api/swagger.json gives a no such method found 500 error and the /swagger.json gives 404 not found error.

**Comment by webron** [comment]
Well, the wiki doesn't really cover CXF so there isn't much to follow. I don't know CXF well enough to tell whether that configuration should work or not.

As a first step, I'd ask you to take a look at the [CXF sample](https://github.com/swagger-api/swagger-samples/tree/master/java/java-jaxrs-cxf) and see if you spot any major differences.

**Comment by steowens** [comment]
Already looked at that.  The CXF sample doesn't really follow good idioms in that it does not use the schema appropriate to CXF but uses raw bean definitions instead.

So for example in the sample we have:
```
<bean class="org.apache.cxf.jaxrs.JAXRSServerFactoryBean" init-method="create">
    <property name="address" value="/" />
    <property name="serviceBeans">
      <list>
        <ref bean="userResource" />
        <ref bean="petResource" />
        <ref bean="petStoreResource" />

        <ref bean="swaggerResource" />
      </list>
    </property>
    <property name="providers">
      <list>
        <ref bean="jsonProvider" />
        <ref bean="swaggerWriter" />
        <ref bean="exceptionMapper" />

        <!-- required for writing swagger classes -->
        <!-- <ref bean="resourceWriter" />
        <ref bean="apiWriter" /> -->
      </list>
    </property>
  </bean>
```
My spring config uses the jaxrs:server tag provided by the: http://cxf.apache.org/schemas/jaxrs.xsd schema.  That should not fundamentally change things however.  And as an additional data point all of this sort of worked when I was using the:  com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON in the jaxrs:serviceBeans section and: com.wordnik.swagger.jaxrs.listing.ResourceListingProvider, com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider in the <jaxrs:providers> section.

Migrating to the stuff in this project doesn't seem to enable things to work correctly.

**Comment by steowens** [comment]
I figured it out the magic path is http://localhost:9095/api/swagger

That works.  By the way for some reason Swagger thinks that the HttpServeletRequest is something that it should be placing in the API documentation.  It shouldn't.

**Comment by webron** [comment]
swagger-core just scans your code. If have an operation that accepts HttpServletRequest as an input, you'd need to explicitly tell it to ignore it using `@ApiParam(hidden=true)`.

**Comment by steowens** [comment]
hidden does not seem to be well documented but sure enough, it works, thanks.

**Comment by webron** [comment]
It's documented in the javadocs, but sure. Please reopen if needed.
