### ISSUE TITLE
ApiModelProperty allowableValues attribute ignores first and last values

### ISSUE THREAD

**Issue by X3Cutor** [swagger-api/swagger-core#1703]
`@ApiModelProperty(allowableValues = "[-1, 0, 1, 2]")
    @NotNull
    private Integer some_integer;`

The resulting swagger output (using 1.57):  `"some_integer":{"type":"integer","format":"int32","enum":[0,1]}`

**Comment by frantuma** [comment]
Hi, allowableValues format for a list of value is "1,2,3,4", it is described in http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiModelProperty.html#allowableValues().

Please reopen if it doesn't answer your question

**Comment by X3Cutor** [comment]
Ok, that probably solves it then! I was apparently reading old docs for some reason: http://docs.swagger.io/swagger-core/apidocs/com/wordnik/swagger/annotations/ApiModelProperty.html#allowableValues()

Sorry about reporting a non-issue.
