### ISSUE TITLE
type ApiHelpController is not a member of package controllers

### ISSUE THREAD

**Issue by damianbl** [swagger-api/swagger-core#1704]
When using "io.swagger" %% "swagger-play2" % "1.5.1" I get the strange error:

`type ApiHelpController is not a member of package controllers`

This is how I define it in the routes file:

`GET        /api-docs                   controllers.ApiHelpController.getResources`

I can find the ApiHelpController in the controllers package.

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-play#65
