### ISSUE TITLE
Improved support for JSR-303 (Bean Validation) annotations

### ISSUE THREAD

**Issue by Nogyara** [swagger-api/swagger-core#1705]
It's great to see #1438 implemented, helping devs to avoid duplication for describing REST API params which are already annotated with JSR-303 (Bean Validation) annotations.

Brief testing of the implementation provided in Swagger 1.5.7, however, seems to have some pieces missing. It worked for me for @PathParam-annotated parameters, but Bean Validation annotations were completely ignored for @QueryParam-annotated parameters.

Please finish off the work done for #1438 by implementing the same support for @QueryParam and possibly other types of params where it makes sense (I haven't tested if #1438 is or isn't implemented for @HeaderParam for instance), making the Bean Validation support predictable and pleasant to use.

**Comment by frantuma** [comment]
Hi @Nogyara, 

I am not sure I get fully what you mean; JS3-303 `@Min`, `@Max`, `@NotNull` and `@Size` support have been added in #1618, as you mentioned; this should work for `@QueryParam` and `@PathParam` alike (e.g. in https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/test/java/io/swagger/ReaderTest.java#L252 and https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/test/java/io/swagger/resources/ResourceWithValidation.java)

Can you detail/share your use case if you're still experiencing issues?

Thx

**Comment by queryparam** [comment]
:+1:

**Comment by xaviarias** [comment]
Hi, 

It'd also be interesting to support custom constraints (http://beanvalidation.org/1.1/spec/#constraintsdefinitionimplementation) to recognize the `NotNull`, `Size`, `Min` and `Max` annotations, at least at one level (a custom `Constraint` annotated with one of the standard constraints), e.g.

	@NotNull
	@Documented
	@Retention(RUNTIME)
	@Size(min = Country.SIZE, max = Country.SIZE)
	@Constraint(validatedBy = { Country.Validator.class })
	@Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER })
	public @interface Country {

	 int SIZE = 2;

	 String message() default "{domain.constraints.Country.message}";

	 Class<?>[] groups() default {};

	 Class<? extends Payload>[] payload() default {};

	 class Validator implements ConstraintValidator<Country, String> {

		  @Override
		  public void initialize(Country constraintAnnotation) {
		  }

		  @Override
		  public boolean isValid(String value, ConstraintValidatorContext context) {
				return 0 <= Arrays.binarySearch(Locale.getISOCountries(), value);
		  }

	 }

	 }


Thanks

**Comment by fehguy** [comment]
For custom constraints, there's a mechanism to make a custom module.  Take a look at https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jersey2-jaxrs for an example, it uses SPI for loading.  

@xaviarias if you see issues or need more help, please open a new issue.  I'm closing this because I think the original request has been answered by @frantuma

**Comment by SwingGuy1024** [comment]
The example provided by fehguy is no longer a valid link. I'm actually looking for something in the docs telling me exactly which validations are supported.
