### ISSUE TITLE
NPE in swagger core

### ISSUE THREAD

**Issue by Kvezon** [swagger-api/swagger-core#1707]
Tried to move to 1.5.7 and use filter for unused definitions from #1621and got NPE

> ERROR [2016-03-09 16:12:45,223] io.swagger.inflector.utils.DefaultExceptionMapper: There was an error processing your request. It has been logged (ID: 1a911a12a64bd0b0).
! java.lang.NullPointerException: null
! at io.swagger.core.filter.SpecFilter.locateNestedReferencedDefinitions(SpecFilter.java:173) ~[swagger-core-1.5.7.jar:1.5.7]
! at io.swagger.core.filter.SpecFilter.removeBrokenReferenceDefinitions(SpecFilter.java:163) ~[swagger-core-1.5.7.jar:1.5.7]
! at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:94) ~[swagger-core-1.5.7.jar:1.5.7]
! at io.swagger.inflector.controllers.SwaggerResourceController.apply(SwaggerResourceController.java:53) ~[classes/:na]
! at io.swagger.inflector.controllers.SwaggerResourceController.apply(SwaggerResourceController.java:32) ~[classes/:na]

**Comment by frantuma** [comment]
@Kvezon I guess you had a model without properties or filtered out properties which caused NPE, fixed in #1710 will be part of v1.5.8

**Comment by fehguy** [comment]
@Kvezon please confirm?  We are trying to release tomorrow.

**Comment by Kvezon** [comment]
https://github.com/SmartBear/swaggerhub-registry-api/issues/94#issuecomment-195335852

**Comment by Kvezon** [comment]
NPE was fixed. But the problems is not fixed completely. For example we have definitions 'def1' and 'def2', 'def1' has a link to 'def2' and this two definitions are not used anywhere. 'def1' will be deleted, 'def2' will not because there were links in 'def1'.

**Comment by frantuma** [comment]
@Kvezon you're right, this is fixed in #1711, can you confirm it solves issue you mentioned?

**Comment by Kvezon** [comment]
Looks like fixed
