### ISSUE TITLE
Supporting repeatable annotations in java8

### ISSUE THREAD

**Issue by natros** [swagger-api/swagger-core#1712]
I don't remember all annotations, but for the ApiResponse it can be implemented.

Thank you.

**Comment by fehguy** [comment]
eh, more details are needed.

**Comment by Sineaggi** [comment]
That means instead of
```java
@ApiImplicitParams({
    @ApiImplicitParam(name = "name", value = "User's name"),
    @ApiImplicitParam(name = "email", value = "User's email")
})
```
in java 8 you can stack multiple repeatable annotations onto the same method
```java
@ApiImplicitParam(name = "name", value = "User's name")
@ApiImplicitParam(name = "email", value = "User's email")
```

**Comment by webron** [comment]
Yup, that's the intent in the next major version of swagger-core, which would be Java 8+ (unlike the current which is Java 7+).

**Comment by butwhoareyou** [comment]
Hey guys, 
do you have any plans to make annotations from ` io.swagger.annotations` package repeatable? 

I have some `@ApiImplicitParams` bundles - annotations which groups some params by some context. I want to use some of them (more then 1 at once) on my `@RestController` method. Making annotations repeatable and implementing some handlers will make it possible.

Providing an example:

```
@Repeatable(List.class)
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface ApiImplicitParams {
 
    ApiImplicitParam[] value();

        @Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE, ElementType.TYPE})
	@Retention(RUNTIME)
	@Documented
	@interface List {

		ApiImplicitParams[] value();
	}
}
```
