### ISSUE TITLE
Property description of class datatype is not show.

### ISSUE THREAD

**Issue by jonelee05** [swagger-api/swagger-core#1713]
userinfo class include phonenum class,ApiModelProperty of userinfo class is show,but ApiModelProperty description of PhoneNum class is not show anywhere of the model.only show "type": "PhoneNum" ,the model result:
```json
{
  "description": "",
  "id": "UserInfo",
  "properties": {
    "id": {
      "description": "user id",
      "required": false,
      "format": "int32",
      "type": "integer"
    },
    "name": {
      "description": "user name",
      "required": false,
      "type": "string"
    },
    "age": {
      "description": "user age",
      "required": false,
      "format": "int32",
      "type": "integer"
    },
    "phoneNum": {
      "description": "user phone num",
      "required": false,
      "type": "PhoneNum"//PhoneNum is class type,has Property description,but not show anywhere
    }
  }
}
```
my class:
```java
@RequestMapping(value = "addUser", method = RequestMethod.POST, produces = "application/json; charset=utf-8")
@ApiOperation(value = "add user", httpMethod = "POST", response = BaseResultVo.class ,notes = "add user")
public @ResponseBody String addUser(
       @ApiParam(required = true, name = "userInfo" , value = "json")
       @RequestBody
       UserInfo userInfo)
{
   return "";
}

public class UserInfo
{
    @ApiModelProperty(value = "user id")
    private int id;
    @ApiModelProperty(value = "user name")
    private String name;
    @ApiModelProperty(value = "user age")
    private int age;
    @ApiModelProperty(value = "user phone num")
    private PhoneNum phoneNum;
}

public class PhoneNum{
    @ApiModelProperty(value = "phone num of home")
    private String homeNum;
    @ApiModelProperty(value = "mobile phone num")
    private String mobileNum;
}
```

**Comment by fehguy** [comment]
Please provide more details.  This does not help

**Comment by jonelee05** [comment]
my userinfo class:
@ApiModel(value = "UserInfo",discriminator = "phoneNum")
public class UserInfo// implements Serializable
{
    @ApiModelProperty(value = "user id")
    private int id;
    @ApiModelProperty(value = "user name")
    private String name;
    @ApiModelProperty(value = "user age")
    private int age;
    @ApiModelProperty(value = "user phone num")
    private PhoneNum phoneNum;

    public PhoneNum getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(PhoneNum phoneNum) {
        this.phoneNum.setHomeNum(phoneNum.getHomeNum());
        this.phoneNum.setMobileNum(phoneNum.getMobileNum());
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public UserInfo(int id,String name,int age)
    {
        this.id  =id;
        this.name=name;
        this.age =age;
    }

    public UserInfo()
    {}

    @Override
    public String toString()
    {
        return "UserInfo [id=" + id + ", name=" + name + ", age=" + age + "]";
    }

}

my PhoneNum class:
public class PhoneNum implements Serializable{
    @ApiModelProperty(value = "phone num of home")
    private String homeNum;
    @ApiModelProperty(value = "mobile phone num")
    private String mobileNum;

    public String getHomeNum() {
        return homeNum;
    }

    public void setHomeNum(String homeNum) {
        this.homeNum = homeNum;
    }

    public String getMobileNum() {
        return mobileNum;
    }

    public void setMobileNum(String mobileNum) {
        this.mobileNum = mobileNum;
    }

    public PhoneNum(){}
}

my api class:
@Api(basePath = "/", value = "用户信息管理")
@Controller(value="UserController")
public class UserController extends BaseController
{
    @RequestMapping(value = "addUser", method = RequestMethod.POST, produces = "application/json; charset=utf-8")
    @ApiOperation(value = "添加用户", httpMethod = "POST", response = String ,notes = "添加用户")
    public @ResponseBody String addUser(
            @ApiParam(required = true, name = "userInfo" , value = "用户信息json数据")
            @RequestBody
            UserInfo userInfo)
    {
        return "";
    }
}

sawgger ui api model:
{
  "description": "",
  "id": "UserInfo",
  "properties": {
    "id": {
      "description": "user id",
      "required": false,
      "format": "int32",
      "type": "integer"
    },
    "name": {
      "description": "user name",
      "required": false,
      "type": "string"
    },
    "age": {
      "description": "user age",
      "required": false,
      "format": "int32",
      "type": "integer"
    },
    "phoneNum": {
      "description": "user phone num",
      "required": false,
      "type": "PhoneNum"//PhoneNum is class type,has Property description,but not show anywhere
    }
  }
}

**Comment by fehguy** [comment]
Is this spring mvc?  Seriously, need more info.

**Comment by jonelee05** [comment]
yes,swagger-springmvc 1.0.2

**Comment by jonelee05** [comment]
IE and Chrome get the same web page of swagger ui model.

**Comment by webron** [comment]
swagger-springmvc is separate project that we do not maintain. It's been renamed to [springfox](https://github.com/springfox/springfox) a while back. It looks like you're using a fairly old version of it. I'd suggest you try to upgrade to the latest version and if there are still issues, please file a ticket on springfox directly.

**Comment by jonelee05** [comment]
@webron thks for your answer.
