### ISSUE TITLE
jersey2 listing resource broken

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1714]
1.5.8 seems to have broken the listing resource for jersey2.  Now this class:

```java
package io.swagger.jersey.listing;

/* */
@Path("/")
public class ApiListingResourceJSON
        extends ApiListingResource {
}
```

causes the swagger definition to appear only on `"/"` instead of `"/swagger.{type:json|yaml}"` as defined in the `io.swagger.jaxrs.listing.ApiListingResource` class

The solution is to use `io.swagger.jaxrs.listing.ApiListingResource`, but for previous uses (like swagger-generator), the 1.5.8 changes break the resource.

We should either fix the ApiListingResourceJSON, remove it, or make it clear how to update when going to 1.5.8.

**Comment by fehguy** [comment]
@frantuma can you look at this?

**Comment by webron** [comment]
@fehguy - iirc, we previously discussed getting rid of ApiListingResourceJSON. While not the ideal way, maybe this would be a good opportunity to just do so, but it will affect only 1.5.9.

**Comment by webron** [comment]
@frantuma for 1.5.9, let's just remove the `@Path` from ApiListingResourceJSON but also mark is as `@Deprecated`. That should revert to the old behavior but notify users they shouldn't use it anymore.
