### ISSUE TITLE
Random behavior in Swagger-Core spec

### ISSUE THREAD

**Issue by asteriosm** [swagger-api/swagger-core#1716]
This if from: [Random behavior in Swagger-UI rendering #2032](https://github.com/swagger-api/swagger-ui/issues/2032)

I have a GET rest service (among others).
First of all, when I deploy my application in some cases, the swagger-ui hangs I see this:

![renderingswagger](https://cloud.githubusercontent.com/assets/4466518/13810562/2f765810-eb79-11e5-86f8-0931b76fe1d6.png)

And I see only 2 out of 7 tags (chdconstands and hazmat)

Then I redeploy my application **with no changes in my code** and I see the same thing.
I redeploy many times and in some random time (second, third deploy) **with no changes in my code**
I see this:

![swaggerall](https://cloud.githubusercontent.com/assets/4466518/13810656/9b67f3bc-eb79-11e5-9f38-97bcc421e696.png)

which are all my tags.

Then in some of my rest service the @QueryParam interpreted as **body** by swagger

![hazmatbody](https://cloud.githubusercontent.com/assets/4466518/13810745/fedad3c4-eb79-11e5-81f3-b08410204e4b.png)

Then I redeploy my application **with no changes in my code** and I see the same thing.
I redeploy many times and in some random time (second, third deploy) **with no changes in my code**
I see this:

![hazmatok](https://cloud.githubusercontent.com/assets/4466518/13810758/153e0f46-eb7a-11e5-8e4a-ae6205db9ef0.png)

How is this possible?

```
@ApplicationScoped
@Path(ChdRESTConstants.HAZMAT_ITEM_MODULE)
@Produces(MediaType.APPLICATION_JSON)
@Api(value = "Hazmat")
public class HazmatRestService extends BaseRESTService {

    @Inject
    ChdHazmatManager chdHazmatManager;

    @Inject
    ChdLoggingManager chdLoggingManager;

    @GET
    @Path("{hazmatId}")
    @ApiOperation(value = "Get a Hazmat based on ID", response = HazmatDetailsDTO.class, responseContainer = "")
    @ApiResponses(value = { @ApiResponse(code = 400, message = ApiResponseMessages.INVALID_REQUEST, response = ErrorContainer.class),
            @ApiResponse(code = 500, message = ApiResponseMessages.INTERNAL_SERVER_ERROR, response = ErrorContainer.class),
            @ApiResponse(code = 503, message = ApiResponseMessages.SERVICE_UNAVAILABLE, response = ErrorContainer.class) })
    public Response getHazmat(@PathParam(ChdRESTConstants.HAZMAT_ID) @ApiParam(defaultValue = "IMDG_0001") String hazmatId,
            @QueryParam(SharedRESTConstants.VERSION_TYPE) @ApiParam(defaultValue = "ONLINE", required = true) VersionType versionType) {
        try {
            ValidationUtil.validateEnum(VersionType.class, versionType, false);
            HazmatDetailsDTO hazmatDetailsDTO = chdHazmatManager.getHazmat(hazmatId, versionType);

            return Response.ok().entity(hazmatDetailsDTO).build();
        } catch (HazmatException e) {
            return handleException(e);
        }
    }
```

The swagger dependency:

```
<dependency>
	<groupId>io.swagger</groupId>
	<artifactId>swagger-jersey-jaxrs</artifactId>
	<version>1.5.8</version>
</dependency>
```

**Additional Information**:

I compared the spec of **body** with **correct** interpretation and has differences

![e8171818-eba2-11e5-93e6-912647d731c7](https://cloud.githubusercontent.com/assets/4466518/13842022/c2cb846c-ec34-11e5-9c8a-d59b1a6d6bcf.png)

- I am using swagger ui 2.1.4
- I upgrade from 1.5.6 to 1.5.8
- I am using Oracle WebLogic Server 12c (12.1.3)
- The spec is different (randomly) every time I deploy (copy/paste) the war to the auto-deploy folder

**Comment by webron** [comment]
Did you experience the same problems after upgrading to 1.5.8?

You mentioned the auto-deploy folder. Are you using hot-deployments (i.e. when the WebLogic is still running) or are you restarting the server between deployments?

If you're using hot deployments, what happens if you restart WebLogic (without redeployment) - does it get fixed or is it still broken?

**Comment by asteriosm** [comment]
Yes @webron I experience the same problems after upgrading to 1.5.8.

Yes I am using hot-deployments. If I restart WebLogic (without redeployment) I experience the same randomness. 

Is fixed and get broken or
Is broken and get fixed or
Is fixed and remain fixed or
Is broken and remain broken.
I am not seeing any pattern.

If i forgot to mention, not all the rest service get fixed or broken at the same time (everything, it's seems random).

### An example:

**Deploy or Restart 1:**

- Rest 1: Fixed
- Rest 2: Fixed
- Rest 3: Broken
- Rest 4: Broken

**Deploy or Restart 2:**

- Rest 1: Broken
- Rest 2: Fixed
- Rest 3: Fixed
- Rest 4: Broken

**Deploy or Restart 3:**

- Rest 1: Broken
- Rest 2: Broken
- Rest 3: Broken
- Rest 4: Broken

**Deploy or Restart 4:**

- Rest 1: Fixed
- Rest 2: Fixed
- Rest 3: Fixed
- Rest 4: Fixed

I know, it is a nightmare of determinism!

**Comment by webron** [comment]
The randomness and hot deployments make me think this is more of a WebLogic issue than swagger-core. I'd assume that if this was a real issue with swagger-core, users would have reported it a long time ago.

When you get the broken spec, can you operate your API as it is represented by the 'fixed' Swagger or the broken one?

**Comment by asteriosm** [comment]
Sorry for the delay!

@webron when I get the broken spec I can't operate my API from swagger-ui, although the API is working fine if I call the services from postman.

I also think that this is more of a WebLogic issue. I will try to deploy my app in tomcat and see the behavior there (I believe that is going to be ok and the problem is indeed with weblogic). Also I will try to build some prototype to reproduce the problem with weblogic and swagger.

If I see the same behaviour with tomcat I will come back!
Thanks for the help so far!

**Comment by asteriosm** [comment]
Just an update in this old issue: This was indeed a _WebLogic_ issue than _swagger-core_. With a fresh installation of the _WebLogic_ everything is ok with swagger! Thanks again for the help!

**Comment by webron** [comment]
@asteriosm - thanks for the update.
