### ISSUE TITLE
NPE in swagger-core on DELETE method when ClassResponses are given

### ISSUE THREAD

**Issue by rainerwei** [swagger-api/swagger-core#1717]
Swagger version: 1.5.8
When a class is annotated with @ApiResponses and the class has a DELETE method with no additional @ApiResponses annotation, then a NPE occurs during method parsing:

> 11:21:07,934 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/device-management-services-2.7-SNAPSHOT].[ch.bkw.device.management.DeviceManagementRestApi]] (http-/127.0.0.1:8081-2) JBWEB000235: Allocate exception for servlet ch.bkw.device.management.DeviceManagementRestApi: java.lang.NullPointerException
> 	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:847) [swagger-jaxrs-1.5.8.jar:1.5.8]
> 	at io.swagger.jaxrs.Reader.read(Reader.java:299) [swagger-jaxrs-1.5.8.jar:1.5.8]
> 	at io.swagger.jaxrs.Reader.read(Reader.java:145) [swagger-jaxrs-1.5.8.jar:1.5.8]
> 	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:223) [swagger-jaxrs-1.5.8.jar:1.5.8]
> 	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204) [swagger-jaxrs-1.5.8.jar:1.5.8]
> 	at ch.bkw.device.management.DeviceManagementRestApi.<init>(DeviceManagementRestApi.java:59) [classes:]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_45]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_45]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_45]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_45]
> 	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:132) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
> 	at org.jboss.resteasy.spi.ResteasyDeployment.createFromInjectorFactory(ResteasyDeployment.java:290) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
> 	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:267) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
> 	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:228) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
> 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:67) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
> 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36) [resteasy-jaxrs-2.3.6.Final-redhat-1.jar:2.3.6.Final-redhat-1]
> 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1194) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:950) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:151) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
> 	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
> 	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
> 	at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]

**Comment by frantuma** [comment]
Hi @rainerwei, issue has been just fixed in #1719 and merged into master, and will be part of v1.5.9, can you confirm it solves your issue?

**Comment by rainerwei** [comment]
Hi @frantuma, Yes i think that should do the trick.

**Comment by todd-richmond** [comment]
Just hit this today as I was about to use the new feature to add ApiResponse to my controller base class as my DELETE ops don't have response data. This should fix the problem so I'll wait to merge until 1.5.9 is out
