### ISSUE TITLE
MultivaluedMap can not be parsed in POST body of JAX-RS method

### ISSUE THREAD

**Issue by eyala** [swagger-api/swagger-core#172]
I'm opening this issue based on [this question on StackOverflow](stackoverflow.com/questions/14295279/swagger-api-for-multivaluedmap-jersey-is-it-possible) - I can confirm that it still occurs:

Basically, Swagger doesn't seem to parse javax.ws.rs.core.MultivaluedMaps.

A method like this:

 @POST
@ApiOperation("fake operation")
 @Path("/add")
 public Response addStudentGroup(@ApiParam("fake param") MultivaluedMap<String, String> formParams) {}

will generate the following resource response:

```
{
"path" : "/fake/add",
"description" : "fake description",
"operations" : [ {
  "httpMethod" : "POST",
  "summary" : "fake operation",
  "responseClass" : "void",
  "nickname" : "addStudentGroup",
  "responseTypeInternal" : "void",
  "parameters" : [ {
    "description" : "fake param",
    "paramType" : "body",
    "required" : false,
    "allowMultiple" : false
  } ]
} ]
```

  }

Making "allowMultiple=true" within the @ApiParam doesn't help.

**Comment by jansohn** [comment]
Any chance this will be supported in the future?

@fehguy : Your answer on Stackoverflow suggested 

> ...it may be fairly easy to implement.

**Comment by chrisinmtown** [comment]
I understand that Swagger cannot read my mind for the multi-value map.  But I'd be glad to add arguments to the annotation, whatever helps.  Is this simply a dead-end road?  Those of us with flexible search interfaces still would like to document them ..

**Comment by webron** [comment]
@chrisinmtown Swagger/OpenAPI 2.0 does not support that, however, OAS3 might be able to. Would suggest filing a new ticket for it.

**Comment by chrisinmtown** [comment]
Please forgive my ignorance, what's OAS 3.0 and where would I file that new ticket?

**Comment by webron** [comment]
OAS3 is OpenAPI 3.0, the new version of the spec. And you would file the new ticket on this repo, with an explanation of what you'd like to achieve.

**Comment by chrisinmtown** [comment]
@webron I followed your suggestion and opened #2721
