### ISSUE TITLE
Parameters array of objects BUG

### ISSUE THREAD

**Issue by ivansky** [swagger-api/swagger-core#1723]
**How to use fully JSON multi depth object in request?**

```yaml
swagger: '2.0'
info:
  title: Bug array of objects
  description: 'Example: Parameters array of objects BUG'
  version: "1.0.0"
consumes:
  - application/json
produces:
  - application/json
paths:
  /someurl:
    post:
      parameters:
        - name: objects
          in: formData
          description: Array of questions @todo Array of objects
          required: true
          type: array
          items:
            type: object
            properties:
              title:
                type: string
      responses:
        200:
          description: An array of survey
```
Not a valid parameter definition

![7b8ef23248](https://cloud.githubusercontent.com/assets/3938372/13978617/f6b98d94-f0eb-11e5-9422-d25a2d565a37.jpg)

**Comment by webron** [comment]
There's no support in the spec for complex objects in formData parameters.

**Comment by ivansky** [comment]
Useless tool then...

**Comment by fehguy** [comment]
Huh?  Ok, feel free to file a ticket against the [specification](https://github.com/OAI/OpenAPI-Specification/issues).  Beats just complaining.
