### ISSUE TITLE
swagger.json not generated (but swagger.yaml is)

### ISSUE THREAD

**Issue by lwojtysiak** [swagger-api/swagger-core#1726]
Hi 

I have a problem with swagger 2. I have configured in both ways:
- Swagger2Feature in CXF with Spring
- basic configuration of Swagger with Spring

The problem is that I can open correctly generated file swagger.yaml, but when I try to open swagger.json -> I get HTTP 404.

Could you please provide any tips - what could be wrong. 

I'm using the same version of CXF and Swagger in other project (with CDI, not Spring), and everything works great.

There is no any errors/exceptions while starting application. This behaviour is really weird (yaml is ok, json no).

**Comment by lwojtysiak** [comment]
I figured out that version 1.5.8 did some unexpected behaviour.

When I changed verison to 1.5.7 json and yaml are generated.


What I found with verisn 1.5.8:
1. when using:
 <bean id="apiListingResourceJSON" class="io.swagger.jaxrs.listing.ApiListingResource"/>

only /swagger.yaml works (no /swagger and no /swagger.json)

2. when using 
 <bean id="apiListingResourceJSON" class="io.swagger.jaxrs.listing.AcceptHeaderApiListingResource"/>

only /swagger.json and /swagger works (no /swagger.yaml)

Is it really what you wanted? As I read:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/LzWEoAW_m4k


It shouldn't work like this...

**Comment by tomzo** [comment]
I think you have misconfigured BeanConfig when using 1.5.8. See release notes https://github.com/swagger-api/swagger-core/releases/tag/v1.5.8

**Comment by lwojtysiak** [comment]
Could you please provide more information?

**Comment by tomzo** [comment]
I too had *undefined* behavior when I used `io.swagger.jersey.listing` instead of new `io.swagger.jaxrs.listing` in package scanning. I am using swagger and jersey2 and spring and I a can access both `/swagger.json` and `/swagger.yaml`

Here is how I configure it:
```java
public class JerseyConfig extends ResourceConfig {

    public JerseyConfig() {
        // https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#using-swaggers-beanconfig
        BeanConfig config = new BeanConfig();
        config.setResourcePackage("my.package");
        config.setVersion("0.1.0");
        config.setTitle("MyTitle");
        config.setScan(true);

        // create a resource config that scans for JAX-RS resources and providers
        // in com.ai_traders.gpd.api package
        String[] packages = {"my.package", "io.swagger.jaxrs.listing"};

        packages(packages);
        property("contextConfig", new AnnotationConfigApplicationContext(SpringAnnotationConfig.class));

        register(MultiPartFeature.class);
        register(RequestContextFilter.class);
        register(LoggingFilter.class);
    }
}
```

I only meant that I doubt there is a bug in 1.5.8. But usage has changed.
