### ISSUE TITLE
怎么生成swagger的html文档

### ISSUE THREAD

**Issue by mingkaili** [swagger-api/swagger-core#1727]
1.swagger core 安装完成
2.接口的注解加入完成
3.怎么生成API文档

我的英语不是很好，请大家帮帮忙。

**Comment by mingkaili** [comment]
How to generate swagger html document

1.swagger core installation is complete
2. The addition was complete annotation interface
3. how to generate API documentation

My English is not very good, please help.

**Comment by mingkaili** [comment]
sad

**Comment by wing328** [comment]
After you generate the swagger spec, you can load it to editor.swagger.io and generate click on the menu to generate the HTML documentations (or API clients in different langauges)
