### ISSUE TITLE
$ref: internal vs relative determination

### ISSUE THREAD

**Issue by crankydillo** [swagger-api/swagger-core#1730]
Shouldn't you require that internal references require a '#'?  I'm thinking most expect this:

``` code
$ref: "Pet.json"
```

to refer to a file relative to the current document.  The OpenAPI spec has [one example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-separate/spec/swagger.json#L48) of that.

**Comment by webron** [comment]
Some context? Where do you see a different behavior?

**Comment by crankydillo** [comment]
Sorry, I thought I linked to [the relevant code](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/refs/GenericRef.java#L91).

**Comment by fehguy** [comment]
This was only a backwards compatibility support.  Please prefix with `#/definitions`.

**Comment by crankydillo** [comment]
`#/definitions` is not relevant in my case.  I would like this library to treat `$ref: ./Pet.json` as equivalent to `$ref: Pet.json`.  It seems you are saying the behavior of `$ref: Pet.json` as an internal ref is to maintain this (arguably) erroneous behavior across new releases.

If that's correct, hopefully this will one day be fixed.
