### ISSUE TITLE
 Swagger duplicating parameters in json output.

### ISSUE THREAD

**Issue by kennywk** [swagger-api/swagger-core#1731]
Swagger seems to be reading both the method parameters and the annotations and outputing duplicates within the json specification. What is strange is that it doesnt do it every where, but it also does not do it consistently to where i can identify any commonality. Here is an example configuration.

```
    @GET
    @Path("/{entityId}")
    @ApiOperation(
            value = "Retrieves the calendars for the specified entity.",
            notes = "Requires the ROLE_USER, ROLE_ADMIN or CALENDAR_READ permissions.",
            response = Calendar.class,
            responseContainer = "List")
    @ApiImplicitParams({
        @ApiImplicitParam(name = "entityId", dataType = "string", paramType = "path", required = true, value = "The entity calendars to retrieve. If value is ME, then the calendars for the currently authenticated user will be returned."),
        @ApiImplicitParam(name = "page", dataType = "integer", paramType = "query", required = true, value = "The page number to retrieve."),
        @ApiImplicitParam(name = "size", dataType = "integer", paramType = "query", required = true, value = "The number of items to include within the page retrieved."),})
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed({"ROLE_USER", "ROLE_ADMIN", "CALENDAR_READ"})
    public Response getCalendars(@Context HttpServletRequest request, @PathParam("entityId") String entityId, @QueryParam("page") Integer page, @QueryParam("size") Integer size)
```
```
My environment
Java 1.8
Swagger 1.5.8
Jersey 2.22.1
Jackson 2.6.2
Spring 4.2.2

I've attached a screenshot of swagger-ui to show what it is doing... perhaps i'm just overlooking something but when i checked the json output (swagger.json) it is indeed duplicated, so i don't believe it's the ui.

Screen Shot:
https://cloud.githubusercontent.com/assets/5767992/14062930/02124ec4-f3b2-11e5-8e6e-fcee023cb37d.png

**Comment by kennywk** [comment]
I just tried version 1.5.7 and it still occurs.

**Comment by webron** [comment]
It's behaving as expected. Swagger-core will automatically add JAX-RS parameters as parameters to the operation. You can add additional details to them using `@ApiParam`. 

swagger-core will also parse `@ApiImplicitParam` as-is and will not do additional processing, and so you can get duplicated parameters. The intent for this annotation in a JAX-RS environment is to add additional parameters that are preprocessed by other layers in the application.

If for some reason you require to use `@ApiImplicitParam` to add already-defined parameters, you'd have to hide those parameters explicitly using `@ApiParam(hidden=true)`.

**Comment by kennywk** [comment]
Understand, I am migrating from version 1.3, where i have all the method parameters mapped to @ApiImplicitParam. Migrating to the new version will require that i move all of those to the method or add an additional param to the method.

Also the method level parameters muddy up the source where as the @ApiImplicitParam looks cleaner and easier to mantain imo.

So migrating to the newest version seems as if it will be more of a task then expected. I suppose i'll have to wait. 

Thanks.
