### ISSUE TITLE
How integrated swagger-core and swagger-ui?

### ISSUE THREAD

**Issue by mingkaili** [swagger-api/swagger-core#1733]
hello,everybody:
      i am a chinses Java engineer. my english is just so-so. now i have some problems.
      1.swagger-core is used to generate integrated with java jar package.
         After swagger-core integrated with java, it is not able to generate API document of the type of json ?
      2.How to use swagger-ui display API document of the type of json?
      3.how to integrate swagger-core with java? I can`t understand the Guide that swagger-core integrate java in GIthut . please tell detail(adv) me ! thank you very very very much. :）
      4.what is the difference Between Swagger-Core and swagger-springmvc？

above problem, who can help me ? please tell me, I'm going crazy！！
Thank everybody to help me very very very much. 

happy everyday to you!

**Comment by mingkaili** [comment]
please help me! please ! please !
please help me! please ! please !
please help me! please ! please !
please help me! please ! please !
please help me! please ! please !
please help me! please ! please !

**Comment by mingkaili** [comment]
sad!!!!

**Comment by fehguy** [comment]
see the guides in http://swagger.io!
