### ISSUE TITLE
enum is legal JSON-Schema, but fails (in Amazon API Gateway)

### ISSUE THREAD

**Issue by Pluggables** [swagger-api/swagger-core#1736]
I am not sure if this is specific to the Amazon AWS API Gateway implementation or whether it speaks to an issue in Swagger-Core.

json-schema advanced example: http://json-schema.org/example2.html uses an enum in the constraints section.  Search "enum": [ "ext3", "ext4", "btrfs" ]

When an enum is used in a model on AWS API Gateway, an exception is thrown that makes it look as though the property name is the issue.  

I am not sure if this is regression or not, but it may be related to https://github.com/swagger-api/swagger-ui/issues/2050

**Comment by webron** [comment]
If the problem is with AWS API Gateway, why are you opening the ticket here?

**Comment by Pluggables** [comment]
Webron: If you read my original content, you'll see that I said I wasn't sure if it was specific to Amazon API Gateway.  That was the very first line.

**Comment by fehguy** [comment]
@Pluggables can you share the exception?  There is an open parser issue around enums, and I think the AWS gateway is using the parser under the hood.

**Comment by fehguy** [comment]
I think (actually, I'm _sure_) this is working now in gateway.
