### ISSUE TITLE
io.swagger.util.PropertyDeserializer fails to deserialize property with type=number and format=decimal

### ISSUE THREAD

**Issue by cipresso** [swagger-api/swagger-core#1739]
Hi. I'm having the an issue in version 1.5.8 (current stable) which also occurs in version 1.5.3M1. The io.swagger.util.PropertyDeserializer class, which is used to deserialize existing JSON schemas, fails to deserialize the following "exampletag" definition, causing it to appear as "exampletag":null in the definitions section of the serialized Swagger doc.  If I change multipleOf to 1.0, deserialization works, but of course min/max look like 9999999.0, which is incorrect.

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "exampletag": {
      "type": "number",
      "format": "decimal",
      "multipleOf": 1,
      "maximum": 9999999,
      "minimum": -9999999
    }
  }
}
```

**Comment by fehguy** [comment]
Hmm, that's weird.  Can you please give more information on this?  How are you generating the property?

**Comment by cipresso** [comment]
Hi. The tool that generates format=decimal is doing it to retain some information about the mainframe data structure member the property represents.  Are there any help topics on how to customize the stock  swagger-core PropertyDeserializer? For example, DecimalProperty.isType(node) will return false if the format is set to anything but null.  I would like DecimalProperty.isType(node) to return if format is null _or_ "decimal".  Is that possible? Thanks for your help!

**Comment by fehguy** [comment]
This shouldn't be an issue anymore.  Please reopen if you're still having a problem
