### ISSUE TITLE
allowableValues not respected for boolean fields in ApiModelProperty, unable to override default

### ISSUE THREAD

**Issue by enlait** [swagger-api/swagger-core#1743]
Good day.

I have an `ApiModel` with a boolean field which is **always** true; however, `allowableValues="true"` is not respected in any way, and `"default":false` is generated in schema. Also, I was unable to find a way to somehow override that default.

Is there any workaround I have overlooked? Thank you.

**Comment by webron** [comment]
This specific case may not be supported, will have to look into it.
But out of curiosity, if it's always true, why even send it?

**Comment by enlait** [comment]
Our API always responds with status code `200` and json response body with `success` boolean. Except for some common values like `success`, models for successful and erroneous responses are completely different. So it turns out that one response model always has `true` for `success` and another has `false`.

We can't map two different response models for the same code, but that's another problem.
