### ISSUE TITLE
io.swagger.models.Model - "type" attribute - getter

### ISSUE THREAD

**Issue by pakkk** [swagger-api/swagger-core#1750]
Hello,

I was wondering if you could add a new interface method getType in the class "io.swagger.models.Model" for the attribute "type", because I would want to parse the value of this attribute with my application.

Nowadays, the only way to get the value is using "casting" over the ModelImpl class and I think it is not a good idea.

Thank you :)

Regards,
Paco.

**Comment by fehguy** [comment]
Model encapsulates primitives and Arrays.  The array doesn't have a type so it's not in the interface.
