### ISSUE TITLE
io.swagger.models.parameters.Parameter - "type" attribute - getter

### ISSUE THREAD

**Issue by pakkk** [swagger-api/swagger-core#1751]
Hello,

I was wondering if you could add a new interface method getType in the class "io.swagger.models.parameters.Parameter" for the attribute "type", because I would want to parse the value of this attribute with my application.

Nowadays, the only way to get the value is using "casting" over the PathParameter class and I think it is not a good idea.

Thank you :)

Regards,
Paco.

**Comment by adetlefsen-rms** [comment]
+1

**Comment by fehguy** [comment]
Please use `instanceOf` or consider a PR.
