### ISSUE TITLE
Swagger ignores the @JsonSerialize annotation

### ISSUE THREAD

**Issue by fogasjanos** [swagger-api/swagger-core#1753]
**Description** 
It would be nice if the Swagger could recognize the @JsonSerialize annotation or I can annotate another annotation with it.

**Use case**
I am working on a Rest API and the model id's should serialize as String (JS Numbers can overflow if not). To fix the documentation I have to add the @ApiModelProperty annotation to every place.

```
public class MyModel {
    @ApiModelProperty(dataType = "java.lang.String")
    @JsonSerialize(using = ToStringSerializer.class) 
    private Long id;
    ...
}
```

**Fix proposal**
- Swagger should recognize the @JsonSerialize annotation so the developers can skip the @ApiModelProperty to add every place
- or @ApiModelProperty should allowed for classes.

```
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
public @interface ApiModelProperty {}
```

In that case I can write a custom annotation to wrap up the others:

```
@Target(FIELD)
@Retention(RUNTIME)
@Documented
@JacksonAnnotationsInside
@JsonSerialize(using = ToStringSerializer.class)
@ApiModelProperty(dataType = "java.lang.String")
public @interface AsString {
    // empty
}

public class MyModel {
    @AsString
    private Long id;
    ...
}
```

**Comment by andyskw** [comment]
+1

**Comment by fehguy** [comment]
Yea, that's a nice behavior.  If you feel like adding a PR that'd be great.

**Comment by twan-ewx** [comment]
This would be very nice to have implemented. Is there any progress on this? Or is there a known work-around?

**Comment by fehguy** [comment]
you can use the `dataType` with classes.
