### ISSUE TITLE
Scanning Operations with Custom Java Annotations

### ISSUE THREAD

**Issue by HaloFour** [swagger-api/swagger-core#1755]
I have a large Jersey project with about 550 operations.  We use a number of custom Java annotations in order to affect how Jersey processes the operations and in a couple of cases we would like to add information about the effect of these annotations to our generated Swagger in the form of vendor extensions.  Using `BeanConfig` I'm not finding any way to interject some additional scanning logic that can take the Java `Method` instances as they are being scanned and then amend the generated Swagger `Operation` model instances.  The meat of the logic seems tucked into `private` methods of the `Reader` class.  I know that we can use `@Extension` annotations to add vendor extensions but we *really* don't want to have to double-annotate the operations.  Are there any options for customizing the operation parsing/scanning process to allow something like this?

**Comment by fehguy** [comment]
Hi, this is certainly supported.  Please look here for an example:

https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jersey2-jaxrs

Essentially you can plug in an extension for scanning your own annotations.  That's how the jersey2 module works.

**Comment by HaloFour** [comment]
@fehguy 

... where?

I'm failing to see anything in `io.swagger.jaxrs.Reader` that respects any kind of extension for scanning my own annotations during the resource scanning operations.  The only extension I see is `ReaderListener` which can only post-process the already-generated `Swagger` model but there's nothing that allows me to then correlate the `Operation` models back to the parsed Java resource methods.  And aside the top-level `Reader::read(Set<Class<?>>)` method called by `BeanConfig` there are no other useful `public` or `protected` methods that are called that I could intercept, assuming I would go so far as to overwrite `BeanConfig.reader`.

**Comment by fehguy** [comment]
Steps:

1) Add a value to the `META-INF/services` like [such](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jersey2-jaxrs/src/main/resources/META-INF/services)

2) Implement [SwaggerExtension](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ext/SwaggerExtension.java) or extend [AbstractSwaggerExtension](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ext/AbstractSwaggerExtension.java) like [this](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java#L33)

**Comment by HaloFour** [comment]
@fehguy 

Yep, looked there too.  The `SwaggerExtension::extractOperationMethod` at least gets me the Java method, but the `ApiOperation` instance is immutable (as annotations are) so I couldn't modify the vendor extensions that might be applied there anyway.  But I'm not trying to modify the operation's verb or the list of parameters, I need to add vendor extensions directly to the `Operation` model.

**Comment by fehguy** [comment]
OK looks like that's currently not supported then.  You can certainly follow this structure, add a new method to the SwaggerExtension and tie into the `Reader` class to call the extension.

**Comment by HaloFour** [comment]
@fehguy Okie dokie, I'll look into doing that.  Thanks.

**Comment by scsynergy** [comment]
I tried everything described in this issue but it just will not work. I am trying to use Swagger for documenting our WebDav interface which, naturally, uses HTTP methods PROPFIND, PROPPATCH, MKCOL, LOCK, UNLOCK, COPY and MOVE (http://www.webdav.org/specs/rfc4918.html). Seems like I will have to resort to WADL instead because Swagger is missing the ability to have its list of HTTP methods extended.

**Comment by HaloFour** [comment]
Looks like PR #1513 already covers my use case.

**Comment by fehguy** [comment]
@scsynergy just FYI, those HTTP methods are simply not supported in the [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object)

**Comment by scsynergy** [comment]
Yes, thank you for pointing that out even if I had understood that before. :-) 
I simply was under the impression that swagger was aiming at being extendable enough to be useful for documenting WebDav - which is just REST with some additional HTTP methods. But, WADL does its job well enough - I only hate the XML it produces.

**Comment by frantuma** [comment]
Closing this as it is covered in #1513
