### ISSUE TITLE
SwaggerSpecFilter with removingUnreferencedDefinitions, removes definitions within containers (List/Map)

### ISSUE THREAD

**Issue by mtraynham** [swagger-api/swagger-core#1757]
The example condition is at (but there are other lines just like it):
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/core/filter/SpecFilter.java#L140
```
if (response.getSchema() != null && response.getSchema() instanceof RefProperty) {
```

As an example:
```
public List<Foobar> getAll() {
    ...
}
```
Will filter out the `FooBar` definition, as the operation's response is an `ArrayProperty` which does not extend `RefProperty`.
```
public Foobar getAll() {
    ...
}
```
Retains this property correctly...

**Comment by fehguy** [comment]
@mtraynham can you please send a PR with a test case?  Would help a lot.

**Comment by mtraynham** [comment]
@fehguy No problem, should be available shortly.
