### ISSUE TITLE
HTTP Method REPORT not supported

### ISSUE THREAD

**Issue by aparvis** [swagger-api/swagger-core#1760]
Hi
According to [http://www.iana.org/assignments/http-methods/http-methods.xhtml](http://www.iana.org/assignments/http-methods/http-methods.xhtml) REPORT is a valid HTTP method. It's not supported by Swagger, probably because it's less known method. Will future swagger releases support it?

REPORT is similar to GET method because it's safe and idempontent. More importantly it fully supports parameters in request body. Such paramaters aren't recommended in GET requests (response caching) and parameters in URI have their limitations (e.g. request-line length).

**Comment by wing328** [comment]
@aparvis I would suggest you to report it in https://github.com/OAI/OpenAPI-Specification similar to this one: 

https://github.com/OAI/OpenAPI-Specification/issues/325

**Comment by bikerunner** [comment]
As I see the REPORT method is registered in the HTTP method registry. The usage of the REPORT method is limited to RFC 3253 (Versioning Extensions to WebDAV) which is not a general HTTP spec. Needs swagger support for this kind of methods?

**Comment by webron** [comment]
Closing as not supported by the spec. If it gets added in a future version, we'll add support to it.

**Comment by malcolmsparks** [comment]
I can't see how swagger can call itself RESTful and not allow additional methods.

**Comment by Mejari** [comment]
I'm also in need of support for other methods, specifically COPY.

**Comment by webron** [comment]
Well, the spec doesn't allow it, so we can't support it.
If you'd like to see additional methods added in the future, file a ticket against the [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/).
