### ISSUE TITLE
@ApiOperation does not support multiple "consumes"/"produces"

### ISSUE THREAD

**Issue by carlspring** [swagger-api/swagger-core#1761]
If a method is annotated with on of the following:

    @Consumes({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
    ...
    @Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })

Then there is no way to actually translate this into swagger annotations, as the following is not supported:

    @ApiOperation(consumes = {MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON},
                  ... or ...
                  produces = {MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})

Is there a known way around this?

**Comment by webron** [comment]
It takes a comma-separated string, not an array of strings. If you already annotate the method with `@Consumes` and `@Produces` you shouldn't need to declare it in the `@ApiOperation` as well.

**Comment by carlspring** [comment]
@webron,

Thanks for clearing this out! I hadn't noticed! Much appreciated! :)
