### ISSUE TITLE
Swagger ignores @Api annotation

### ISSUE THREAD

**Issue by dandronchik** [swagger-api/swagger-core#1763]
Documentation says that "Only classes that are annotated with @Api will be scanned by Swagger."
But BeanConfig loads only classes with annotation Path and SwaggerDefinition.

`Set<Class<?>> classes = reflections.getTypesAnnotatedWith(javax.ws.rs.Path.class);
 classes.addAll(reflections.getTypesAnnotatedWith(SwaggerDefinition.class));`

**Comment by gaeljw** [comment]
I disagree with you on what documentation says. Have you looked at https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X ?

**Comment by dandronchik** [comment]
Thanks. I guess I checked old version

**Comment by frantuma** [comment]
As mentioned by @gaeljw annotation is in sync with latest version behaviour, closing.
