### ISSUE TITLE
java.lang.ClassCastException: io.swagger.models.Swagger cannot be cast to io.swagger.models.Swagger

### ISSUE THREAD

**Issue by sdragoff** [swagger-api/swagger-core#1766]
Having configured Swagger for servicemix cxf jax-rs service got 

*java.lang.ClassCastException: io.swagger.models.Swagger cannot be cast to io.swagger.models.Swagger*

on 
`value = (Swagger) sc.getServletContext().getAttribute("swagger");`

Possible steps to reproduce:

- apache-servicemix-7.0.0.M1 installed. 
- feature:install swagger (swagger-2.11)
- cxf jax-rs app. maven: 
```xml```
<packaging>bundle</packaging>
...
<properties>
    <cxf.version>3.1.5</cxf.version>
    <swagger-version>1.5.8</swagger-version>
...
</properties>
             ...
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                      <Import-Package>
                            ...
                            io.swagger.*,
                            javax.servlet,
                            ...
                      <Embed-Dependency>
                            swagger-core,
                            swagger-models,
                            swagger-annotations,
                            swagger-jaxrs,
                            swagger-jersey-jaxrs,
                            javax.servlet-api,
                            commons-lang3,
                            jackson-dataformat-yaml

```
- META-INF.spring/beans.xml
```xml```
<bean id="beanConfig" class="io.swagger.jaxrs.config.BeanConfig">
        <property name="title" value="Title"/>
        <property name="version" value="1.0.0" />
        <property name="schemes" value="http" />
        <property name="host" value="localhost:8181/cxf"/>
        <property name="basePath" value="/"/>
        <property name="resourcePackage" value="${serviceBeansPath}"/>
        <property name="scan" value="true"/>
</bean>
```
```xml```
<jaxrs:server id="myService" address="/" 
    basePackages="${serviceBeansPath},io.swagger.jaxrs.listing">
...
```
- http://localhost:8181/cxf/swagger.json

**Comment by fehguy** [comment]
Sounds like you have a dependency issue.  I think you need to look at the provided dependencies in your project to sort this out.

**Comment by sdragoff** [comment]
@fehguy , thanks, I'm going to create my project from scratch and add all dependencies for both my project and swagger one by one in order to figure out what's wrong with it. 
For now, I just added service requests interceptor and put there 
context.setAttribute("swagger", null);
Now I can see swagger json but without  my service docks. I debugged solution and found out that there is no possible way to scan service beans with javax.ws.rs.Path having "bundle://" URL.

**Comment by bikerunner** [comment]
Hi, it sound more like a conflict of class loading. The class in the application ( part "(Swagger)" )is loaded by another classloader as the instance "sc.getServletContext().getAttribute("swagger")" to cast.

Please try:

- before the cast save the "sc.getServletContext().getAttribute("swagger")" to an object
- get the class from the instance and the class loader and display the hash code
- next use "Swagger.class.getClassloader().getHashCode()" from the internal class and compare both class loaders

It looks like one of the classes is loaded by a class loader from the application server and the second one from a class loader of the web application. Each (mostly) web application uses an own class loader to isolate for security. You need to remove the "swagger" JAR files from the web application if these exist already within the context of the application server.

**Comment by sdragoff** [comment]
Guys, thanks for your responses. 
I used to work with swagger on regular and already implemented applications, but now it's osgi cxf jax-rs. I'm going to close this "issue".
