### ISSUE TITLE
Does/will swagger backend together with UI support password fields ?

### ISSUE THREAD

**Issue by to-kra** [swagger-api/swagger-core#1769]
In our web application we use a swagger JAXRS with swagger-ui to document our APIs. We do also have sesssion API for login/logout, however password fields are just a normal text field. Is swagger-core supporting password field (maybe some annotation) feature so when you would type password in UI it would be hidden by characters *** ?

**Comment by webron** [comment]
This will be covered by #469.

**Comment by to-kra** [comment]
how can i get that correction ? just checkout latest swagger-ui code ? or was it / will be part of some release ? thx

**Comment by webron** [comment]
It wasn't fixed yet...

**Comment by to-kra** [comment]
@webron then why it was closed ?

**Comment by webron** [comment]
Because of https://github.com/swagger-api/swagger-core/issues/1769#issuecomment-214189309.
