### ISSUE TITLE
PropertyDeserializer omits vendor extensions for RefModel properties

### ISSUE THREAD

**Issue by nbruno** [swagger-api/swagger-core#1770]
Example:
```
definitions:
  pet:
    properties:
      id:
        type: string
  taggedPet:
    properties:
      pet:
        $ref: '#/definitions/pet'
        x-vendor-ext: example
```
x-vendor-ext will be omitted from the resulting `Property` object produced from the deserializer.

**Comment by webron** [comment]
Yup, works as designed. JSON References don't support additional properties alongside them.

**Comment by nbruno** [comment]
@webron - If Swagger was abiding by the spec for a JSON Reference exactly, then it would stand to reason by the same logic, title and description shouldn't be supported either, yet they are. From [the spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03):

> Any members other than "$ref" in a JSON Reference object SHALL be ignored.

But the members "title" and "description" aren't ignored. It also introduces inconsistencies:

1. Only a `RefModel` doesn't support vendor extensions, while (all?) of the rest do.
2. The RefModel POJO inherits the vendor extensions field and associated methods, alluding to it being supported, yet trying to use it results in it never containing any values.

**Comment by webron** [comment]
If they aren't ignored, then to me that's a bug. That doesn't mean we need to introduce additional ones.

**Comment by nbruno** [comment]
I'll leave the Swagger team to properly address the inconsistencies mentioned in my previous post. I also found this related request that would handle this correctly: https://github.com/OAI/OpenAPI-Specification/issues/556
