### ISSUE TITLE
Unrecognized Type

### ISSUE THREAD

**Issue by mibrahim-skios** [swagger-api/swagger-core#1773]
Hello,
I am using Liberty 8.5.5.9 with apiDiscovery-1.0 feature to discover my REST services.
but i got this error when i try to open the REST document throw swagger-ui

**java.lang.ClassNotFoundException: com.skios.model.Tag cannot be found by com.ibm.ws.io.swagger.core**

**java.lang.IllegalArgumentException: Unrecognized Type: [null]**

So how i can use my class as a data type with @ApiModelProperty annotation
now i am using >> **dataType = "List[com.skios.model.Tag]"** that throw the exception

**Comment by fehguy** [comment]
Can you please add a PR with a test case?
