### ISSUE TITLE
Customization of Types

### ISSUE THREAD

**Issue by cjolif** [swagger-api/swagger-core#1777]
I know this project is meant to support the spec but in my case I would like to leverage it with some custom things in mind. In particular additional types. Unfortunately it seems to source code is such that you can't really register additional types "from the outside". An example being `ProprertyBuilder.build` which build a property from a list of types contained in a private enum (`Processor`) without any means to register additional types.
1. am I missing something and there is a way to do that?
2. if not, is that something you could imagine adding?

**Comment by webron** [comment]
Well, no, I can't imagine adding support to it. Not sure why you'd need additional types too, considering you can use `format` to fine-tune type specification if needed.

**Comment by cjolif** [comment]
My use-case is arbitrary JSON I know that's not Swagger focus. But I do have some APIs that return arbitray JSON (type-less type basically ;)). So ideally I like to have either type: "json" or no type at all (but with no type at all the parser is stripping out entirely the info).

**Comment by webron** [comment]
But if you want an arbitrary JSON, why don't you set the type to be object? That's pretty much it.

**Comment by cjolif** [comment]
@webron ok, sorry maybe I was not clear enough, what I had in mind is not arbitrary JSON but arbitrary JSON value. So not necessarily an `object` but maybe a `string` etc... A particular API call is very generic, and can take any JSON value thus my issue. That said maybe I should still go with `object` even if that did not seem to me like the correct option. Opinion?

**Comment by webron** [comment]
So you're not looking to support additional types, you're wanting something that accepts *any* type?

**Comment by cjolif** [comment]
Basically yes.

**Comment by fehguy** [comment]
You can fork this project and add any support you like.  But this is outside the spec.
