### ISSUE TITLE
minProperties and maxProperties for type object not supported

### ISSUE THREAD

**Issue by ebelanger** [swagger-api/swagger-core#1778]
io.swagger.models.properties.PropertyBuilder.java defines on line 85 and 86 the PropertyId for minProperties and maxProperties but these are not taken into account when generating one of the Property implementations.

Those properties should be stored in ObjectProperty and MapProperty since they can be quite useful when defining constraints on the size of the map.

The reason I am asking for this is that we are generating our beans from the swagger definition file.  I was able to generate a mapping of some json schema validations to HibernateValidator but unfortunately cannot generate map validations because of this.

Thanks

**Comment by frantuma** [comment]
@ebelanger #1781 is merged, can you check if this issue can be closed?

**Comment by ebelanger** [comment]
Everything seems in order.  Thank you very much :)
