### ISSUE TITLE
reflections library license issue

### ISSUE THREAD

**Issue by afkham** [swagger-api/swagger-core#1779]
The following dependency is used in swagger-jaxrs
        &lt;dependency&gt;
            &lt;groupId&gt;org.reflections&lt;/groupId&gt;
            &lt;artifactId&gt;reflections&lt;/artifactId&gt;
        &lt;/dependency&gt;

However, that library is licensed under WTFPL which is not an OSI approved license. So even though the the Swagger libraries are under Apache Software License, there is a legal grey area because the transitive reflections dependency. Please let us know the legal implications of using reflections library.

**Comment by wing328** [comment]
@afkham thanks for reviewing the license of the dependencies Are you aware of any alternatives we can use to replace it? 

Disclaimer: I'm not expert in software licensing.

**Comment by afkham** [comment]
What I was thinking is, since WTFPL allows you to do what you want, it may be possible to make a copy of that code into the swagger-jaxrs repo, and then license the code under Apache Software License. 

I have also raised an issue in the reflections project https://github.com/ronmamo/reflections/issues/134

Let's wait & see what they have to say.

**Comment by afkham** [comment]
This has been fixed with https://github.com/ronmamo/reflections/pull/107

**Comment by wing328** [comment]
@afkham thanks for the follow up.

**Comment by kcooney** [comment]
The issue hasn't been fixed; https://github.com/ronmamo/reflections/pull/107 has not been merged

**Comment by afkham** [comment]
Is there any issue with merging that PR?

On Tue, May 31, 2016 at 8:43 AM, Kevin Cooney <notifications@github.com>
wrote:

> The issue hasn't been fixed; ronmamo/reflections#107
> <https://github.com/ronmamo/reflections/pull/107> has not been merged
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1779#issuecomment-222583471>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACiBtaFM0QgsqmYEd1ZsKQWLRQ-64cupks5qG6dbgaJpZM4IW2gw>
> .
>



-- 
*Afkham Azeez*
Director of Architecture; WSO2, Inc.; http://wso2.com
Member; Apache Software Foundation; http://www.apache.org/
* <http://www.apache.org/>*
*email: **azeez@wso2.com* <azeez@wso2.com>
* cell: +94 77 3320919blog: **http://blog.afkham.org*
<http://blog.afkham.org>
*twitter: **http://twitter.com/afkham_azeez*
<http://twitter.com/afkham_azeez>
*linked-in: **http://lk.linkedin.com/in/afkhamazeez
<http://lk.linkedin.com/in/afkhamazeez>*

*Lean . Enterprise . Middleware*

**Comment by kcooney** [comment]
@afkham I am not a maintainer.for Reflections so I can't merge pull requests

**Comment by afkham** [comment]
Sorry that PR wasn't merged :(
