### ISSUE TITLE
How to do Indentation in generated HTML from swagger UI 

### ISSUE THREAD

**Issue by sgaikwad16** [swagger-api/swagger-core#1786]
HI,

I have generated HTML page by running below command on JSON generated from swagger UI.

"java -jar "C:\swagger_codegen.jar" generate -i "C:\MyJSONFile.json" -l html -o "C:\ MyHTMLFile.html"

And I have generatedJSON data by running below base URL of swagger and saved that JSON data in "MyJSONFile.json" file.

http://<host>:<port>/plan/api/plan/api-docs/V1
where - 
plan/api/plan -- is 'swagger.api.basepath' path configured in web.xml
V1                --  is base root path configured in .java file as below-
                        @Api(value= "/V1", description="APIs designed module XYZ.")

My problem is --
I have long description for method parameter and method description which includes html <li> tags for bulletins and indentation (as shown in below, for e.g.- ) -

@ApiParam(value="optional map of attributes to match. The implied boolean operator is AND. The match algorithm works as follows: <ul> <li>determine the list of all projects</li> for each project, evaluate if all query attributes match: /li><li>return array of handles of matched projects</li></ul><p> If the attributeMap parameter is not specified, all current projects that the client has read security permissions for are returned. " , 
                       required = false) 

 But, when I hit URL - http://<host>:<port>/plan/api/plan/api-docs/V1 and generate static HTML page then it not consider indentation and HTML tag or \n \r etc.

So is there any way to do indentation or bulletins(or at least new line , tab etc)  when you have very long text within swagger annotations @ApiParam or @ApiOperation  ??

Please suggest.

**Comment by fehguy** [comment]
Use markdown
