### ISSUE TITLE
Is scanner set to the ScannerFactory obsolete

### ISSUE THREAD

**Issue by maggu2810** [swagger-api/swagger-core#1788]
I am using third party code that uses: <code>ScannerFactory.setScanner( ... );</code>

If my reading of the recent SwaggerContextService is correct the getScanner() functions returns
- SwaggerScannerLocator.getInstance().getScanner(scannerIdKey) is the result is not null
- otherwise ScannerFactory.getScanner();

The getScanner function of the SwaggerScannerLocator is implemented this way:

``` java
    public Scanner getScanner(String id) {
        Scanner value = map.get(id);
        if (value != null) {
            return value;
        }
        return new DefaultJaxrsScanner();
    }
```

so it returns never null.

Isn't the usage of the ScannerFactory then obsolete?

**Comment by maggu2810** [comment]
I have compared v1.5.5 to v1.5.7:

The previous call to the factory has been changed:
swagger-api/swagger-core@v1.5.5...v1.5.7#diff-5b72a0a48c0069409834b1cd6ce38282L48

The getScanner function uses the ScannerFactory only if the value is null.
swagger-api/swagger-core@v1.5.5...v1.5.7#diff-55650387ef7908bb46e3b090ee8460b7R232

But SwaggerScannerLocator will create a default scanner if there is no one defined and never returns null.
swagger-api/swagger-core@v1.5.5...v1.5.7#diff-fc757da4002c12bba84c73f26e1be755R29

**Comment by fehguy** [comment]
Please give details of what you expect.

**Comment by maggu2810** [comment]
Hm, I could try to rephrase my question:
The scanner set by the ScannerFactory.setScanner method is not (has not been on v1.5.7) used anymore (see explanation in the previous two comments).
So, code that relies on the fact the the scanner set by `setScanner` is used if there is no one for the given scanner id has been broken with the linked changes.
If the scanner set by the resp. method is not used and the behaviour has been changed, too, wouldn't it be better to remove the function so third party code knows, that this method to force a special default scanner does not work anymore?
