### ISSUE TITLE
Need to generate 2 swagger.json for 1 java resource class

### ISSUE THREAD

**Issue by catchaag** [swagger-api/swagger-core#1803]
HI,

I have a requirement to generate 2 swagger.json out of 1 java resource. First swagger.json should have all the apis listed in the resource and other one should have just selected apis. Could you please let me know how we can achieve this.

Thanks in advance.

**Comment by catchaag** [comment]
Can anyone here help me out with this?

**Comment by fehguy** [comment]
Hi, you've asked in many places.  What you're describing is not a normal request, and therefore not part of the current tooling.  I believe I've given you some other pointers on how to do this.
