### ISSUE TITLE
swagger-jaxrs formparam File not correct

### ISSUE THREAD

**Issue by peterkendlbacher** [swagger-api/swagger-core#1804]
I am using swagger-jaxrs 1.5.8/1.5.9 (both same result).

@ApiParam(value = "File", required = true) @FormParam("file") File file)

In the swagger.json I get the following for this: {"name":"warfile","in":"formData","description":"Java war File","required":true,"type":"string"}]

As a result of this in the swagger ui I get no button "choose file"

Type string is definitly not correct. I used the old api 1.3.something before and there it was working correctly.

Could someone please fix this.

Thanks

Peter

**Comment by fehguy** [comment]
What dependency are you using?

**Comment by peterkendlbacher** [comment]
Dear Tony!

I am using this dependency:

<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-jaxrs</artifactId>
    <version>1.5.8</version>
</dependency>

Also Version 1.5.9 is not working.

I moved now back to this dependency and everything works fine.

<dependency>
    <groupId>com.wordnik</groupId>
    <artifactId>swagger-jaxrs_2.10</artifactId>
    <version>1.3.13</version>
</dependency>

Regards

Peter
Am 24.05.2016 18:41 schrieb "Tony Tam" <notifications@github.com>:

**Comment by fehguy** [comment]
File support requires the jersey dependency:

```
<!-- http://mvnrepository.com/artifact/io.swagger/swagger-jersey-jaxrs -->
<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-jersey-jaxrs</artifactId>
    <version>1.5.9</version>
</dependency>
```

**Comment by peterkendlbacher** [comment]
I am using ibm liberty profile as application server and have never used the jersey framework, as all of the jax-rs stuff is provided from liberty. Do you see a problem, if I combine the swagger-jersey-jaxrs framework with this?

Thanks

Peter

**Comment by fehguy** [comment]
I'm not familiar enough with how liberty works with jaxrs to say.

**Comment by webron** [comment]
Liberty uses Wink as the underlying implementation and so the jersey dependency won't help. You'd have to write your own extension to support file upload with Wink as we don't provide it out of the box.
