### ISSUE TITLE
Swagger @ApiParam not working for QueryParam 

### ISSUE THREAD

**Issue by shruthipodduturi** [swagger-api/swagger-core#1808]
Hi

I am using swagger @ApiParam annotation for JAX-RS Query Param.
But Query Params are not recognized in Swagger UI.In Swagger UI all the Query Params are coming as body parameters. We have an interface and implementation class for our REST API's. If i remove interface class its working...Ideally interface should nt create any problem.....Any help would be appreciated.

**Comment by fehguy** [comment]
Please share more details if you're still having an issue.

**Comment by lvabarajithan** [comment]
Yes, this issue still exists. 
Query Params are not recognized in Swagger UI.
The QueryParams are coming as body. 
Using ApiParam also doesn't get it fixed.
