### ISSUE TITLE
How to do Indentation for attribute value of Swagger UI annotation's

### ISSUE THREAD

**Issue by sgaikwad16** [swagger-api/swagger-core#1811]
When I put long multi-lined description in "value" ,"notes" attributes of "@ApiOperation" annotation with **\n \t Or \n \t Or separating two lines with actually hitting Enter key** (as shown below e.g.)-

_@ApiOperation(value="API desc line 1. **\n**" +
" <ul>API desc bullets points starts here with  line 2.  **\n** " +
     **START of HTML tag**  Sub Point 1  **END of HTML tag**" +
    **START of HTML tag**  Sub Point 2 **END of HTML tag**" +
    **START of HTML tag**  Sub Point 3 **END of HTML tag**" +
"**START of HTML tag** **\t** API desc line 3.**END of HTML tag** **\n**" +
"API desc line4. **\n**", 
notes="Fetches the attribute map of the object instance given by the specified handle. i.e. returns AttributeMap of zero or more attributes", 
httpMethod="GET", 
response=MultiTypeMap.class)_ 

 In above e.g. code- I have used \n \t and HTML order listing tag "<li>" but still It does not displayed the effect of these indentation characters in generated HTML output. 

We are using swagger base URL JSON data to generate HTML UI with below command-
"java -jar "**swagger_codegen.jar**" generate -i "**MyJSONFile.json**" -l html -o " **MyHTMLFile.html**"

When HTML UI generated out of above swagger annotations in .java file , it looks like all text without any indention, for e.g. information given in Value attribute will be look like-->

_"API desc line 1. **\n** **START of HTML tag** API desc bullets points starts here with  line 2.  **\n**  **START of HTML tag**  Sub Point 1 **END of HTML tag** **START of HTML tag**  Sub Point 2 **END of HTML tag**  **START of HTML tag**  Sub Point 3 **END of HTML tag** **START of HTML tag** **\t** API desc line 3.**END of HTML tag****\n**API desc line4. **\n**"_

So my question is for readability point of view how can i do indention in generated HTML ? where should I put \n \t ? 
Or is there any option available while generating HTML UI by running **_java -jar "**swagger_codegen.jar_*\* command ?

**Comment by fehguy** [comment]
Hi, this is a codegen issue.  There are measures to avoid code injections by escaping newlines.
