### ISSUE TITLE
Jersey2 Jaxrs Import org.glassfish.jersey.media.multipart

### ISSUE THREAD

**Issue by stfanbrg** [swagger-api/swagger-core#1817]
Hi,

I set the parameter   library to "Jersey core 2" for code generator but each  time I have to  replace (in my XyzApiService and XyzApi)

import com.sun.jersey.multipart.FormDataParam;
import com.sun.jersey.core.header.FormDataContentDisposition;

with 

import org.glassfish.jersey.media.multipart.FormDataContentDisposition;
import org.glassfish.jersey.media.multipart.FormDataParam;

for start my project on Tomcat 7.

Is it a issue or do I have to do something different ?

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-codegen#3157
