### ISSUE TITLE
Map support in swagger

### ISSUE THREAD

**Issue by kishoretangudu** [swagger-api/swagger-core#1818]
I have input to my rest API below:

{
"a":"value",
"resources": {"key1":"value1",
                     "key2":"value2" }
}
When I am doing 

class MyModelClass {
@XmlElement(name = "resources")
	@ApiModelProperty(value = "resources")
	Map<String, MYClass> resources= new HashMap<String,MyClass>();

//Setters and getters for resource object.
}

Now

public class MyClass{
	
	@XmlTransient
	JSONObject pushnotificationResources = new JSONObject();

	public JSONObject getPushnotificationResources() {
		return pushnotificationResources;
	}
	public void setPushnotificationResources(JSONObject pushnotificationResources) {
		this.pushnotificationResources = pushnotificationResources;
	}
}

when I am loading my application I am getting the below error:
Can not instantiate value of type [simple type, class packagename.MYClass] from String value; no single-String constructor/factory method (through reference chain: com.tycoon.auth.idm.identity.model.MYModelClass["resources"])
	

Please help me to accept a json object with key value pairs as part of an attribute value?
like below 
{"resource": {"k1":"v1","k2","v2"}}

**Comment by fehguy** [comment]
Simply override the `dataType` for your `JSONObject` value like such:

```java
public class MyModel {
  @ApiModelProperty(value="dummyAttrib", dataType = "java.util.Map")
  public JsonNode getDummyAttrib() {
    return null;
  };
  public void setDummyAttrib(JsonNode node) {}
}
```

Then your definition looks like it accepts a `Map<String, Object>`:

```json
{
  "MyModel" : {
    "type" : "object",
    "properties" : {
      "dummyAttrib" : {
        "type" : "object",
        "description" : "dummy",
        "additionalProperties" : {
          "type" : "object"
        }
      }
    }
  }
}
```

**Comment by kishoretangudu** [comment]
hi
Thank you for the reply.
Now I have one more Question.
class MyModelClass {

String name;
String address;
@XmlElement <https://github.com/XmlElement>(name = "resources")
@ApiModelProperty(value = "resources")
Map<String,String> resources= new HashMap<String,String>();
//settters and getters of "resource" Map
//setter andd getter for name and address
}

Now when we load our application in swagger my input JSON shows exactly
below .For map this is the default behavior that shows by swagger I guess.

{
"name":"",
"address":"",
"resource":"Map[String,String]"
}

Now I need the above map like below::
{
"name":"",
"address":"",
"resource":{SOmecontent which I can enter as K:V}
}

What is the configuration I am missing to get the above JSON like that??

Please help me.




*Regards,*
*Kishore Tangudu*
* Banglore.*

Think twice before take a print. Save trees.

**Comment by fehguy** [comment]
Please look at my example above again.  You're missing the `dataType` annotation above

`@ApiModelProperty(value="dummyAttrib", dataType = "java.util.Map")`

**Comment by kishoretangudu** [comment]
Hi Tony,
Very good morning. Hope you are doing good. I have a question.

When I am updating swagger com.wordnik(1.3.12) to *io.swagger *API's as
show below.

<dependency>

    <groupId>io.swagger</groupId>

    <artifactId>swagger-*jaxrs*</artifactId>

    <version>1.5.0</version>

</dependency>


<dependency>

    <groupId>io.swagger</groupId>

    <artifactId>swagger-jersey2-*jaxrs*</artifactId>

    <version>1.5.9</version>

</dependency>

*web.xml*:

 <servlet>
    <servlet-name>Authentication and Authorization Web
Service</servlet-name>

<servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
      <param-name>javax.ws.rs.Application</param-name>
      <param-value>mypackage.name.classname.*MyJaxRsApplication*
</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>Authentication and Authorization Web
Service</servlet-name>
    <url-pattern>/auth/*</url-pattern>
  </servlet-mapping>
  
  <servlet>
        <servlet-name>Jersey2Config</servlet-name>

<servlet-class>io.swagger.jersey.config.JerseyJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <init-param>
            <param-name>swagger.api.basepath</param-name>
              <param-value>/*Abcde*/auth</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>

*MyJaxRsApplication*:

public class AnAJaxRsApplication extends ResourceConfig {
public AnAJaxRsApplication() {
packages( "*io.swagger.jaxrs.listing*;different.Packages.ofmyproject;");
register(JacksonFeature.class);
register(AppExceptionMapper.class);
register(GenericExceptionMapper.class);
register(MultiPartFeature.class);
register(SecurityInterceptor.class);
}

This is the configuration I made in my project. While loading the
application URL I am getting the following Error message:  Can't read
swagger JSON from http://localhost:8081/Abcde/auth/api-docs

Can you please let me know where I am doing wrong??  Please help me to come
out of this problem.

*Regards,*
*Kishore Tangudu*
* Banglore.*

Think twice before take a print. Save trees.

**Comment by fehguy** [comment]
Hi, please take a look at the swagger-samples project for integration examples.
