### ISSUE TITLE
Generated Swagger API spec does not match original spec

### ISSUE THREAD

**Issue by mikehwang** [swagger-api/swagger-core#1820]
Craft a Swagger API spec using the live Swagger editor, generate a JAX-RS, run the generated service, query the `/swagger.yaml` endpoint for the spec.  The resulting spec does not match the original.  The differences are not just formatting differences and details that have moved from one level to another (e.g. produces and consumes from top level to endpoint level) but pieces of the spec are just missing.  The loss of information is to be concerned about.

Consider the steps of generating the JAX-RS server, building and running the service, and querying as a composed function, the function is **not invertible**.

**Comment by fehguy** [comment]
Hi, I suggest being specific about what is missing.  To be clear, the generated java server is _not_ simply coping the swagger definition specification and regurgitating it when called.  The code being generated is using annotations and will "reproduce" the spec from the source code itself.  It is not supposed to create the exact same file.

Regardless, if you're seeing structural, functional issues, please open a ticket in the swagger-codegen project, which is where the java servers are produced.
