### ISSUE TITLE
Swagger shows as string when using org.joda.time.LocalDateTime for date fields

### ISSUE THREAD

**Issue by shantisattiraju** [swagger-api/swagger-core#1822]
Team,

We have below issue the way swagger is reflecting in the generated docs.

For Ex in my Java class I have

import org.joda.time.LocalDate;

@ApiModelProperty(value = "Dateate of birth, e.g., 1965-09-26")
private LocalDate dateOfBirth;

Then in the documentation,I see

dateOfBirth(string,...).

What can be done to see dateOfBirth(LocalDate,...)?Any pointers on this is appreciated.

Link to original issue

https://groups.google.com/forum/embed/?place=forum/swagger-swaggersocket&theme=default&fragments=true&showsearch=false&showtabs=true&hideforumtitle=true&hidesubject=true&parenturl=http%3A%2F%2Fswagger.io%2Fforum%2F#!topic/swagger-swaggersocket/iypn3ouOhpo

**Comment by webron** [comment]
As said in the linked topic, it's going to be `string` because that's the right data type.
