### ISSUE TITLE
Add GSON support

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#1826]
Currently swagger-core is jackson-only, many users want to support GSON.  Need to see how feasible this is, but it would be nice if user-selectable.

**Comment by cleankod** [comment]
Any news on this one?

**Comment by caipivara** [comment]
Any update on this?

**Comment by webron** [comment]
It's not really on our radar.

**Comment by hptvl** [comment]
any update? We need Gson in swagger.

**Comment by Larkenx** [comment]
PLEASE ADD SUPPORT

**Comment by softboy99** [comment]
+1

**Comment by RUANHAOANDROID** [comment]
+1

**Comment by albertocavalcante** [comment]
@webron should we expect this feature request to enter the radar anytime soon? Thank you

**Comment by jiangxiaoqiang** [comment]
please add the gson support.

**Comment by jiangxiaoqiang** [comment]
> Currently swagger-core is jackson-only, many users want to support GSON. Need to see how feasible this is, but it would be nice if user-selectable.

how did you solve this problem?

**Comment by ChristianCiach** [comment]
I wonder if this is still worth the effort. I was one of the people who upvoted this issue years ago, but a lot has changed since then. We've moved away from gson completely. Even Google has mostly ceased development of gson. See the README of the gson project:

> Gson is currently in maintenance mode; existing bugs will be fixed, but large new features will likely not be added.

This begs the question: Is it worth the time and effort to support a library that is even barely kept alive by its maintainers?

**Comment by jiangxiaoqiang** [comment]
I am trying to remove the gson from my project, it take me too much time to solve this imcompatible problem.

**Comment by hubefonseca** [comment]
+1

**Comment by bcb44** [comment]
My company still uses gson pretty heavily and we're going to work on supporting it inside this project. The goal is to add gson support by treating gson annotations as their corresponding Jackson annotations (SerializedName -> JsonProperty etc) in the AnnotationIntrospector. 
We can then extend some key classes to use a custom ObjectMapper that uses the custom AnnotationIntrospector. Here's the repo where I'm working on it https://github.com/bcb44/gson-swagger-core/, still very much in the infancy stages but would love to work with others on implementing more of this!

**Comment by frantuma** [comment]
Support of GSON is not currently part of the roadmap for Swagger Core, main reason is the tight coupling with Jackson library
