### ISSUE TITLE
 @ApiModelProperty - example property doesn't work properly

### ISSUE THREAD

**Issue by naumanaftab** [swagger-api/swagger-core#1835]
I have a property representing a collection as below:

```
@ApiModelProperty(
            value = "Collection of IP's",
            example = "[1.1.1.0]"
    )
    public List<String> getIps() {
        return ips;
    } 

```

The swagger-ui is showing me the result as below:

```
"properties": {
    ...
    "ips":  "[1.1.1.0]",
    ...
}

```

However, i want to see the result as below, is there a way to achieve that? 

```
"properties": {
    ...
    "ips": ["1.1.1.0"],
    ...
}

```

**Comment by fehguy** [comment]
This is a known limitation of the example property in the annotation.  No current work-around, so let's keep this issue open.

**Comment by fehguy** [comment]
see #1107
