### ISSUE TITLE
@ApiResponse : support for multidimensional list as response type

### ISSUE THREAD

**Issue by gnanasundar** [swagger-api/swagger-core#1837]
Hi,

Not sure this is the right forum to post this question. I'm using swagger-core (1.5.8). My resource end point returns List<List<CustomClass>>. How to specify this in the annotation:

@ApiResponse(message = "Okay", code = 200, response = CustomClass.class, responseContainer = "List")

Thanks,
-Gnana

**Comment by fehguy** [comment]
Hi, this is a good place to post issues, but I think you're asking a question.  What you described above looks like an accurate way to return a List<CustomClass>.
