### ISSUE TITLE
<contextroot>/swagger.json displays BeanConfig properties as json strings in browser

### ISSUE THREAD

**Issue by syparth** [swagger-api/swagger-core#1838]
I have used below maven dependency ,

```
<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.5.6</version>
</dependency>
```

And the BeanConfig code is shown as below ,

```
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.2");
        beanConfig.setSchemes(new String[] { "http" });
        beanConfig.setHost("localhost:8080");
        beanConfig.setBasePath("/rest");
        beanConfig.setResourcePackage("abc.xyz.efg");
        beanConfig.setPrettyPrint(true);
        beanConfig.setScan(true);
```

This is my normal url to access any rest resource in my project
`http://localhost:8080/myrest/rest/adress`
and for accessing swagger i use the below url
`http://localhost:8080/myrest/rest/swagger.json`
but it shows the BeanConfig properties in the browser.
I dont know what is more to be configured to see the Swagger ui and documentation.

**Comment by webron** [comment]
The UI is not part of swagger-core. It's a separate project that can be found at https://github.com/swagger-api/swagger-ui. You'd need to manually add it to your project for it to be deployed.
