### ISSUE TITLE
FileUpload not working with Jersey/Java

### ISSUE THREAD

**Issue by gaffa** [swagger-api/swagger-core#184]
I have the following service-method:

``` java
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation("submit")
    public Response uploadTranslation(
            @ApiParam(required = false) @FormDataParam("comment") String comment,
            @ApiParam @FormDataParam("translation") Translation translation,
            @ApiParam @FormDataParam("sourceDocument") InputStream sourceDocument,
            @ApiParam @FormDataParam("additionalContent") InputStream additionalContent) {
        return null;
    }
```

it results in swagger-ui not rendering the file-inputs as file-chooser but text-fields. Same counts for spring. I spent all day trying and trying and I really think its a bug. Unfortunately I dont know the least of scala. Anyone has any idea why this would not work? 

toni tam has posted this code on the mailing-list and it was confirmed working:

``` scala
  @POST
  @Path("/uploadImage")
  @Consumes(Array(MediaType.MULTIPART_FORM_DATA))
  @ApiOperation(value = "uploads an image")
  def uploadFile(
    @ApiParam(value = "String to pass during submit") @FormDataParam("test") testString: String,
    @ApiParam(value = "file to upload") @FormDataParam("file") inputStream: InputStream,
    @ApiParam(value = "file detail") @FormDataParam("file") fileDetail: FormDataContentDisposition) = {
    println("testString: " + testString)
    val uploadedFileLocation = "./" + fileDetail.getFileName
    IOUtils.copy(inputStream, new FileOutputStream(uploadedFileLocation))
    val msg = "File uploaded to " + uploadedFileLocation + ", " + (new java.io.File(uploadedFileLocation)).length + " bytes"
    val output = new com.wordnik.swagger.sample.model.ApiResponse(200, msg)
    Response.status(200).entity(output).build()
  }
```

I of course have the latest versions of both ui- and jersey-code. When I do something like this:

``` java

@ApiParamsImplicit(@ApiParamImplicit(dataType = "file", name = "file", paramType = "body"))
```

I get a file chooser but I dont know where to go from there. I also need a solution which will still keep the api clean and easily usable by coded clients...

Thinkink of this point.. is it really necessary to bind the service to translation.json instead of just translation?

**Comment by Naga** [comment]
what is the status of this issue. any reference to the bug created ? I am using swagger-annotation 1.5.3. I am not able to use both FormParam and FormDataParam.
