### ISSUE TITLE
Parameter type changes depending on amount of parameters

### ISSUE THREAD

**Issue by jivimberg** [swagger-api/swagger-core#1842]
I've notice that if I write this:

```java
@POST @Path("{spaceId}/projects/deploy")
    @Consumes({ MediaType.MULTIPART_FORM_DATA })
    @ApiOperation(value = "Deploys the latest published version of the specified project")
    Response deployProject2(
                           @NotNull @PathParam("spaceId") String spaceId,
                           @NotNull @ApiParam(required = true) RestDeployConfig deployConfig);
```

The `deployConfig` param is **treated as body**

![screen shot 2016-07-01 at 3 15 45 pm](https://cloud.githubusercontent.com/assets/248488/16535733/a005be30-3f9e-11e6-94dc-561c2badbae2.png)

But if I add one more PathParam like this:

```java
@POST @Path("{spaceId}/projects/deploy")
    @Consumes({ MediaType.MULTIPART_FORM_DATA })
    @ApiOperation(value = "Deploys the latest published version of the specified project")
    Response deployProject2(
                           @NotNull @PathParam("spaceId") String spaceId,
                           @NotNull @PathParam("projectId") String projectId,
                           @NotNull @ApiParam(required = true) RestDeployConfig deployConfig);
```

Then it starts **treating the deployConfig param as formData**

![screen shot 2016-07-01 at 3 18 40 pm](https://cloud.githubusercontent.com/assets/248488/16535764/f411abf6-3f9e-11e6-989f-64af57e10877.png)

Is this a bug?

**Comment by webron** [comment]
You didn't mention which version of swagger-core you use, but yeah, it does seem like a bug. My guess is that it's because you're adding a `@PathParam` for a parameter that doesn't exist in the path `{spaceId}/projects/deploy` and that potentially drives the processing slightly insane. Since there can't be more than one body parameter... well, you get the idea.

**Comment by jivimberg** [comment]
Hi Ron! I'm using swagger-core version 1.5.9 . You're right about the annotated path param that doesn't exist in the path, I completely missed that. I'll give it another try with that parameter in the path to check if it's still reproducible and post the results. Thanks!

**Comment by jivimberg** [comment]
You were completely right, adding the correct amount of variables in the path fixed the issue for me. Thanks for your help!
