### ISSUE TITLE
How to send the Default value through body in Swagger 2.0

### ISSUE THREAD

**Issue by jeevanhr7** [swagger-api/swagger-core#1844]
Hi i am trying to send the Default values through body parameters but its Not taking while Submitting. can anybody please help me on this issue. Here is my code and i am trying to send the default name parameter through body

```
swagger: '2.0'
info:
  version: 1.0.0
  title: PetStore on Heroku
  description: |
    **This example has a working backend hosted in Heroku**

    You can try all HTTP operation described in this Swagger spec.

    Find source code of this API [here](https://github.com/mohsen1/petstore-api)
host: petstore-api.herokuapp.com
basePath: /pet
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /:
    get:
      parameters:
        - name: limit
          in: query
          description: number of pets to return
          type: integer
          default: 0
      responses:
        200:
          description:  List all pets
          schema:
            title: Pets
            type: array
            items:
              $ref: '#/definitions/Pet'
    post:
      parameters:
        - name: pet
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Make a new pet
    put:
      parameters:
        - name: pet
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Updates the pet
  /{petId}:
    get:
      parameters:
        - name: petId
          in: path
          type: string
          description: ID of the pet
          required: true
      responses:
        200:
          description: Sends the pet with pet Id

definitions:
  Pet:
    type: object
    properties:
      name:
        type: string
        default : "xxxxxxx"
      birthday:
        type: integer
        format: int32
```

**Comment by webron** [comment]
How is this issue related to swagger-core?

Also, I think you're missing the point of the default value. The default value is one that's assumed by the receiving end (either the server or the client) if the sender does not provide a value for it - it's not what automatically should be filled.

**Comment by marcellodesales** [comment]
Is this related to https://github.com/springfox/springfox/issues/1345#issuecomment-245782111? The authors of SpringFox claim that the reason why their Swagger UI integration does not take default body is that your API is not taking the default body. 

@jeevanhr7 Is this related to your issue?

@webron Can you please confirm that? For the case of Swagger UI, wouldn't we need to have the support for default values?

**Comment by webron** [comment]
There's nothing in this ticket to even suggest it's related to java, let alone swagger-core specifically.

Regarding the general question - body parameters can have default values. The Schema Object has a `default` field in it.

**Comment by dilipkrish** [comment]
@webron I think the problem is that [`BodyParameter`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/parameters/BodyParameter.java#L9) doesn't support setting the default value.

**Comment by webron** [comment]
@dilipkrish the `BodyParameter` has a `default` under the `schema`, as the spec describes - https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java#L31, it's not supposed to be directly under the parameter itself. Let me know if you think something is missing. Right now, it looks like potentially accessors are missing from [`Model`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Model.java).

**Comment by marcellodesales** [comment]
@webron thanks for checking this... 

@dilipkrish Could you verify what @webron was referring to about the Model? The body to our API is a complex type that it is very hard to produce... That's why I need to get an instance of the payload built and injected through SpringFox... 

Thank you guys!

**Comment by Alin-Barsan** [comment]
I'm also having somewhat of an issue using the "default" value for a Body Parameter.  I have editor.swagger.io confirming that the setup is valid, and I included the "default" value under "schema" like @webron recommended.

However, the "default" field does not seem to be populated in the text field in the web view of the API.  Every other "default" value properly populates for non-body parameters.  @webron is this issue what you were referring to when you mentioned "potentially accessors are missing from Model."?

**Comment by webron** [comment]
@Alin-Barsan I'm not really sure what you mean by 'web view' - don't know which project you're referring to. However, by the sound of what you're describing, again, this is not related to swagger-core. Please open a ticket on whichever project you experience the issue with.

**Comment by Alin-Barsan** [comment]
@webron Hi Ron, thanks for the response!  By 'web view' I meant the Swagger UI, I'll go ahead and search for a relevant ticket (or open a new one if none exists) on that project.

**Comment by webron** [comment]
@Alin-Barsan - thanks.

@marcellodesales - I'm afraid I don't see the source of confusion.

**Comment by SafalTammewar** [comment]
@jeevanhr7 In swagger 2.0 for body parameters default value is set by "example" keyword
