### ISSUE TITLE
Feature request: JAX-RS Ignore @Consumes annotations for GET method handlers

### ISSUE THREAD

**Issue by defnull** [swagger-api/swagger-core#1845]
I like to define ``@Produces`` and ``@Consumes`` at class level instead of repeating myself on each method, but ``@Consumes`` makes no sense for HTTP methods that do not allow a request entity (e.g. GET or DELETE). It would be nice if swagger-jaxrs could just filter out the ``consumes`` field if the HTTP method is does not allow a request entity.

**Comment by defnull** [comment]
Never mind, it is really easy to do with a ReaderListener:

	public void afterScan(Reader reader, Swagger swagger) {
		for(Path path: swagger.getPaths().values()) {
			for(Entry<HttpMethod, Operation> operation: path.getOperationMap().entrySet()) {
				switch(operation.getKey()) {
				case GET:
				case HEAD:
				case DELETE:
				case OPTIONS:
					operation.getValue().setConsumes(null);
				}
			}
		}
	}

This issue can be closed I think.

**Comment by webron** [comment]
Yeah, it's actually not technically impossible to have body payloads for such operations, so we can't just assume that and not produce it. Of course, you found the way to do it for your case, which is great.
