### ISSUE TITLE
Expose APIOperation code in Operation Model

### ISSUE THREAD

**Issue by frojasg** [swagger-api/swagger-core#1846]
@APIOperation [has a code attribute](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiOperation.java#L176), which isn't exposed in the [Operation model](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Operation.java).

does that make sense? I'm willing to add it if make sense.

**Comment by webron** [comment]
@frojasg It makes sense, perhaps the documentation isn't clear enough.

Since you can specify the `response` of the operation in the annotation, that ones is generally meant as the 'successful' response. It's assumed to be `200` by default, but in some cases users may choose a different code. This just affects that. It ends up being translated to the key value of the response at https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Operation.java#L22.

**Comment by frojasg** [comment]
If I define severals responses. How can I know what's the 'successful' of the @APIOperation?

**Comment by webron** [comment]
I assume you have only one 'successful' response in general? In any case, you can describe all the responses using `@ApiResponse`.

**Comment by frojasg** [comment]
you only have one "successful" response, but you can have severals to describe different kinds of errors. 

Let's use this example: 
```java
@POST
    @ApiOperation(value = "User",
                  notes = "Blah",
                  code = 201,
                  response = User.class,
                  nickname = "createUser")
    @ApiResponses(value = {@ApiResponse(code = 201,
                                        message = "user created",
                                        response = UserRequest.class),
            @ApiResponse(code = 400,
                         message = "blah1",
                         response = ErrorResponse.class)},
                  @ApiResponse(code = 422,
                               message = "blah2",
                               response = ErrorResponse.class) })
```

Operation's responses will return a map with three entries. How can I know which one is the "successful" response?

**Comment by webron** [comment]
In this case, you have 201 responses, and one will just clobber the other. Anything that's 2XX will be considered the successful response.

**Comment by frojasg** [comment]
That's something the client of the Operation class has to assume. what if My API returns a 3XX as "successful". 

I think it would be nice to have a way to specify the "successful" response in the @APIOperation annotation.

**Comment by webron** [comment]
That's a spec issue, not swagger-core's. There's a standard way of interpreting 1XX, 2XX, 3XX, 4XX and 5XX responses, we're not looking to reinvent anything.

**Comment by frojasg** [comment]
As API designer I want to use swagger to explain to my clients how to use my API. For some endpoints a success status will be a 2xx, for some other a 3xx.

 The current swagger implementation just list possible responses.  You're delegating the reposability of knowing what's a success status to the client. 

I was wondering if it make sense allow to the API designer to specify what's the success status of an endpoint

**Comment by webron** [comment]
That's an issue for the spec, not for swagger-core. As far as I recall we decided to not support it (because those values have predefined meaning), but you're welcome to open a ticket about it and try to change that.

**Comment by frojasg** [comment]
got it. Thanks!

**Comment by frojasg** [comment]
BTW: [this is the Ticket I created in the spec](https://github.com/OAI/OpenAPI-Specification/issues/725)
