### ISSUE TITLE
Swagger customization for JSON API specification

### ISSUE THREAD

**Issue by kotak25krishna** [swagger-api/swagger-core#1849]
I am trying to generate swagger documentation to match the standards specified by JSON API specification. However I couldn't see a way to get this done. Does swagger supports json api spcecification as mentioned in jsonapi.org. If needs to be customized what would be best way to customize the swagger definition/documentation as per the needs.

**Comment by webron** [comment]
Swagger wasn't written in mind of supporting one paradigm or another. Some things can be described, some can't - and that applies to JSON API as well.

**Comment by kotak25krishna** [comment]
Thanks. What would be the way to customize or extend swagger behavior. Looking if there is a way to customize to meet the specification

**Comment by kotak25krishna** [comment]
Are there any annotations or document generator can be extended?

**Comment by webron** [comment]
There's a limit to what you can extend. You can use 'vendor extensions' at various parts in the spec but - a. the tools don't necessarily support it, and b. I still believe you won't be able to describe parts of JSON API with vendor extensions.
