### ISSUE TITLE
Uploading files with RestEasy - wrong parameter deffinition

### ISSUE THREAD

**Issue by Romanow88** [swagger-api/swagger-core#1851]
When using RestEasy for file uploads the defined way is to have a org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataInput as a parameter that will contain all of the files uploaded. Yet Swagger does not resolve this to the file type as it should, instead it generates the schema based on the inner properties of the MultipartFormDataInput . 

Example definition:

> public Response uploadFile(MultipartFormDataInput input, @Context HttpServletRequest req)
> {
>       final Map<String, List<InputPart>> formDataMap = input.getFormDataMap();
>       final byte[] bytes = formDataMap.get("file").get(0).getBody(byte[].class, null);
>       final String fileName = formDataMap.get("filename").get(0).getBodyAsString();
>       return Response.ok().build();
> }

As a workaround I'm hiding the  MultipartFormDataInput  with the swagger hidden flag and using an implicit param annotation to generate the correct definition so that the Swagger UI actualy shown a file picker (which throws a java.lang.ClassNotFoundException: file on runtime)

> @ApiImplicitParams(
>       @ApiImplicitParam(dataType = "file", name = "file", value="File to be uploaded", paramType = "formData")
>   )

It would be awesome if swagger could except "file" as the dataType without exceptions and could understand the MultipartFormDataInput as a file upload for RestEasy.

**Comment by webron** [comment]
Right now, swagger-core has explicit support for file uploads for Jersey and Jersey 2 only. The good news is that you can easily add support for RESTEasy by adding your own extension. https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java shows the Jersey 2 extension that does that logic.
