### ISSUE TITLE
ApiModelProperty doesn't support example for arrays / Lists

### ISSUE THREAD

**Issue by m-radzikowski** [swagger-api/swagger-core#1855]
By default array or List of integers is generated in UI with example:

```
"eventTypes": [0],
```

I've tried to add "example" property, but that:

``` java
@ApiModelProperty(required = true, example = "[2, 3]")
private int[] lorem;
```

generates example values as string:

```
"eventTypes": "[2, 3]",
```

Other options like `"2, 3"` don't work neither. In result to have valid json in example it has to have only one value, zero.

**Comment by kellerassel007** [comment]
+1

**Comment by smalik2043** [comment]
+1

**Comment by nandana** [comment]
+1

**Comment by Satyricon** [comment]
+1

**Comment by QuasiSoDo** [comment]
+1

**Comment by webron** [comment]
It looks like a lot of people are looking for this feature. This is great. If anyone wants to try and submit a PR to add the functionality, that would be appreciated.

**Comment by SIDSSIDS** [comment]
+1

**Comment by overrid3R** [comment]
+1

**Comment by bricem** [comment]
+1

**Comment by yana2301** [comment]
+1

**Comment by timstegeman** [comment]
+1

**Comment by fehguy** [comment]
This takes a major refactoring of the models, which is on the way.

**Comment by euclidean** [comment]
+1

**Comment by kusan-thana** [comment]
+1 : it's quite bothering since arrays are pretty common in REST API...

**Comment by modulo-** [comment]
+1

**Comment by jonherrmann** [comment]
+1

**Comment by fehguy** [comment]
Will be supported in 3.0.0 support, please see the feature/3.0.0-rc2 branch for details.

**Comment by sarojkv** [comment]
+1

**Comment by sarojkv** [comment]
When is the release due for this version?

**Comment by zinaliev** [comment]
+1

**Comment by Gatoke** [comment]
+1

**Comment by Mihail74** [comment]
+1

**Comment by trorvillelim** [comment]
+1

**Comment by aszkiladzsoftwarehut** [comment]
+1

**Comment by zookotic** [comment]
+1

**Comment by nmsakos** [comment]
@fehguy What should I see on branch feature/3.0.0-rc2 regarding this? I can't find any related commit.
Thanks!

**Comment by Sjworks** [comment]
+1

**Comment by justforadblock** [comment]
![image](https://user-images.githubusercontent.com/33308682/33546551-418fd91c-d91c-11e7-80b6-b1397a8c46dc.png)

it's work

**Comment by americk0** [comment]
+1

**Comment by Treppenhouse** [comment]
+1

**Comment by eugenemiretsky** [comment]
+1

**Comment by shendrix** [comment]
+1

**Comment by Kotsyubinsky** [comment]
+1

**Comment by SariAlalem** [comment]
+1

**Comment by webron** [comment]
A lot of +1's, and rightfully so. Changing this at the moment may cause issues as it's potentially a breaking change.

That said, I'm not scared of breaking changes if they make sense. If anyone wants to try and work out a PR to add the functionality, we'd be happy to review. You can take a look at how this is supported in swagger-core 2.0.

**Comment by biniama** [comment]
A working solution:
```
@ApiModelProperty(value = "Address", name = "addLines", dataType = "List",
    example = "[AddLine1,AddLine2,AddLine3,AddLine4]")
```
When I render the swagger page, I get the following output:

```
"addLines": [
      "AddLine1",
      "AddLine2",
      "AddLine3",
      "AddLine4"
    ],
```

Credit @dane_griffiths https://stackoverflow.com/a/50132642/2245264

**Comment by martinKosturkov** [comment]
@biniama, can you please send your swagger version, because i tried the above solution, and it doesn't work for me.

**Comment by biniama** [comment]
> @biniama, can you please send your swagger version, because i tried the above solution, and it doesn't work for me.

 
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>

        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.9.2</version>
        </dependency>

        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
            <version>2.9.2</version>
        </dependency>

**Comment by martinKosturkov** [comment]
> > @biniama, can you please send your swagger version, because i tried the above solution, and it doesn't work for me.
> 
> Here are the maven dependencies I used.
> 
> ```
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-swagger2</artifactId>
>         <version>2.9.2</version>
>     </dependency>
> 
>     
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-swagger-ui</artifactId>
>         <version>2.9.2</version>
>     </dependency>
> 
>     
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-bean-validators</artifactId>
>         <version>2.9.2</version>
>     </dependency>
> ```

Thanks. Unfortunately, we are still not using Spring, but will try this once, we switch to it.

**Comment by martinKosturkov** [comment]
> > @biniama, can you please send your swagger version, because i tried the above solution, and it doesn't work for me.
> 
> Here are the maven dependencies I used.
> 
> ```
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-swagger2</artifactId>
>         <version>2.9.2</version>
>     </dependency>
> 
>     
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-swagger-ui</artifactId>
>         <version>2.9.2</version>
>     </dependency>
> 
>     
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-bean-validators</artifactId>
>         <version>2.9.2</version>
>     </dependency>
> ```

Thanks.

**Comment by ypzhuang** [comment]
> A working solution:
> 
> ```
> @ApiModelProperty(value = "Address", name = "addLines", dataType = "List",
>     example = "[AddLine1,AddLine2,AddLine3,AddLine4]")
> ```
> 
> When I render the swagger page, I get the following output:
> 
> ```
> "addLines": [
>       "AddLine1",
>       "AddLine2",
>       "AddLine3",
>       "AddLine4"
>     ],
> ```
> 
> Credit @dane_griffiths https://stackoverflow.com/a/50132642/2245264

It doesn't work for me.  Result is "[AddLine1,AddLine2,AddLine3,AddLine4]" , it's a string,not a list.

**Comment by kamaci** [comment]
Is there any progress on this issue?

**Comment by honza-zidek** [comment]
@fehguy You closed the issue, but it is not solved! See https://github.com/swagger-api/swagger-core/issues/3863.

**Comment by toby2** [comment]
+1

**Comment by liyuntao** [comment]
Waste a lot of time on this, can't get it done, and give up finally.

I would suggest migrating to [springdoc](https://springdoc.org/#migrating-from-springfox
) to get a smooth and intuitive experience


```java
    @Schema(description = "stock codes, in array",
            type = "List",
            example = "[\"TSLA\", \"AAPL\"]")
    private List<String> codes;
```

**Comment by dims12** [comment]
Doesn't work with `@Schema` too

**Comment by honza-zidek** [comment]
Please reopen and **solve** this issue.
