### ISSUE TITLE
Auto-discovery "required" in model from @NotNull annotation not work for composed annotations

### ISSUE THREAD

**Issue by m-radzikowski** [swagger-api/swagger-core#1856]
With `@NotNull` annotation on property in model Swagger automatically marks that property as required, which is great. But if we use other annotation that is composed from `@NotNull`, like `org.hibernate.validator.constraints.NotEmpty`, the `required` parameter is not set.

**Comment by webron** [comment]
Well, `@NotEmpty` is slightly more than just `required`, but would be great to support it.

**Comment by gjong** [comment]
As it stands this 'bug' makes swagger less useful to us in our code as the documentation that is generated is incorrect and misleading to the consumer of the API. They expect the fields annotated with any composed annotation extending @NotNull (like @NotBlank) to be optional when in truth the application server will return an exception that the field is required.

**Comment by fehguy** [comment]
We've made a very handy mechanism for you to add your own support for extensions using SPI.  Take a look at the https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-hibernate-validations module.  You can even send a PR to add that support :)

**Comment by m-radzikowski** [comment]
Well, adding support for own / third-party validation annotations is surely great possibility. But it would require adding support for each own annotation.

Wouldn't you be interested in recursive mechanism that processes each annotations' annotations? We could take annotation and check it's annotations if they have `@Constraint` annotation. If so, we would apply their validation rules, and so on.

Of course the performance would decrese as we would have to make annotations' reflections. On the other hand annotations such as `org.hibernate.validator.constraints.NotEmpty` or own composite annotations, that use standard (already supported) constraint annotations, would be supported without additional developer effort.

@fehguy please write what do you think about this. If you would be interested I could work on some PR with that feature.

**Comment by fehguy** [comment]
@m-radzikowski did you look at how the extension mechanism works?  You can make a single extension and handle as many annotation types as you like.  You can decide if you want to pass the processing on to the next extension or abandon.  Please let me know what's missing there.

**Comment by m-radzikowski** [comment]
@fehguy yes, I've checked this out. That solves the problem but requires much work and discipline with creating new compound constraints. I'll try to clarify.

Let's say I've that custom constraint:

```java
@NotNull
@Size(min = 8)
@ReportAsSingleViolation
@Constraint(validatedBy = {})
@Target({METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface Password {
    String message() default "password must be not null and minimum 8 characters long";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

Now to support it in Swagger I've to create `Validator` that implements `ModelConverter`, like this:

```java
public class OwnConstraintsValidator extends AbstractModelConverter implements ModelConverter {
    public OwnConstraintsValidator() {
        super(Json.mapper());
    }

    @Override
    public Property resolveProperty(Type type, ModelConverterContext context, Annotation[] annotations, Iterator<ModelConverter> chain) {
        Map<String, Annotation> annos = new HashMap<String, Annotation>();
        if (annotations != null) {
            for (Annotation anno : annotations) {
                annos.put(anno.annotationType().getName(), anno);
            }
        }
        Property property = null;

        if (chain.hasNext()) {
            property = chain.next().resolveProperty(type, context, annotations, chain);
        }
        if (property != null) {
            if (annos.containsKey("com.example.Password")) {
                property.setRequired(true);
                if (property instanceof StringProperty) {
                    ((StringProperty) property).minLength(8);
                }
            }
            return property;
        }
        return super.resolveProperty(type, context, annotations, chain);
    }
}
```

Right?

Now when some developer creates, for example, `@Hex` constraint, that is also only a compound validator, without own logic:

```java
@Pattern(regexp = "([0-9a-fA-F]{2})*")
@ReportAsSingleViolation
@Constraint(validatedBy = {})
@Target({METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface Hex {
    String message() default "should be even number of [0-9a-fA-F] characters";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

he has to add next `if` clause to our `OwnConstraintsValidator` class. And so on, and so on. It doesn't seem to be a big problem, but sooner or later somebody will create new constraint and forgot to add Swagger condition for it. As @gjong noticed, it leads to generating invalid API.

But, all of those annotations, `@NotNull`, `@Size`, `@Pattern` and more are already supported by Swagger, so why bother with manual rewriting their logic? The [ModelResolver#applyBeanValidatorAnnotations()](https://github.com/swagger-api/swagger-core/blob/208335a08cae610d3b5eaea75f5552efaf15477b/modules/swagger-core/src/main/java/io/swagger/jackson/ModelResolver.java#L750) method already knows them.

My idea was to modify that method. It takes actual property annotations as argument. We could reflect those annotations to discover compound (known) constraints and put them into `annos` map. Then do regular job with applying `Property`'s properties.

This way both my upper cases, with `@Password` and `@Hex` constraints, would work as expected without defining `OwnConstraintsValidator` class and logic for each of those constraints. This should not be hard to implement and I could make a PR, if you agree.

-----

Bigger problem would be to support own, custom constraints in the same way. For example there is `BeanValidator` for Hibernate or another one custom implementation of `ModelConverter` that provides support for custom constraints. I can't find a solution how those custom constraints could be supported in compund constraints. For example that:

```java
@Pattern(regex = ".*@gmail.com")
@Email
@ReportAsSingleViolation
@Constraint(validatedBy = {})
@Target({METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface GmailEmail {
    String message() default "must be an email addres in gmail.com domain";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

would result in `@Email` constraint still not handled by Swagger. The annotations list passed to `ModelResolver#applyBeanValidatorAnnotations()` can't be altered by other `ModelConverters` so even dirty hacks are not an option. I think it would be required to modify constraint annotations processing. Maybe behaviours for each constraint could be registered, so we could both manage annotations discovering (resolving compound annotations) and support custom constraints like it is now.

-----

But that's the bigger, more complex problem, so maybe firstly let's discuss about the first part of my post. What do you think about my proposition about out of the box support for compound constraint annotations? Do you agree?

**Comment by sandello-alkr** [comment]
Hi @m-radzikowski @fehguy I have similar problem with `javax.validation.constraints.NotEmpty` annotation. How could I make it required?
