### ISSUE TITLE
swagger-models - refs named http<something> incorrectly treated as RefFormat.URL instead of RefFormat.INTERNAL

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-core#1858]
I discovered this issue when using swagger-parser however I believe this is an issue with the swagger-models API.  My swagger definition has models with names like "httpOptions", "httpHeaders", "httpAuthentication", etc.  After parsing the swagger, the corresponding RefProperty objects all have RefFormat.URL instead of RefFormat.INTERNAL.  This becomes painfully obvious if I try to serialize the swagger model back to JSON/YAML.

I believe the issue is with io.swagger.models.refs.GenericRef.computeRefFormat(String) incorreclty assumes a ref starting with "http" is a URL.  Instead, perhaps it should check if the ref starts with "http:" or "https:" instead of "http".

Please observe this JUnit snippet that demonstrates the problem:

```
        ObjectMapper mapper = Yaml.mapper();

        // this is totally expected:
        RefProperty refProperty = new RefProperty("foobar");
        assertEquals(RefFormat.INTERNAL, refProperty.getRefFormat());
        StringWriter sw = new StringWriter();
        mapper.writeValue(sw, refProperty);
        assertEquals("---\n$ref: \"#/definitions/foobar\"\n", sw.toString());

        // here is the problem:
        refProperty = new RefProperty("httpSomething");
        // should be INTERNAL, not a URL!!!!
        assertEquals(RefFormat.URL, refProperty.getRefFormat());
        sw = new StringWriter();
        mapper.writeValue(sw, refProperty);
        // should be #/definitions/httpSomething
        assertEquals("---\n$ref: \"httpSomething\"\n", sw.toString());
```

This is an issue for me because I must be able to correctly deserialize Swagger 1.2/2.0 documents to the Swagger model and marshall the model back out as needed.  To workaround this, I have to post process the model after deserialization, manually fixing up RefProperty/RefModel objects afterward.

**Comment by fehguy** [comment]
Please try latest, I believe this has been fixed.

**Comment by benken-parasoft** [comment]
Can this issue please be re-opened?  I see no changes in the mentioned behavior in the current version (1.5.12).  Please let me know if something in my original description is unclear.  If this helps, I also verified that the code snippet in the original problem description still demonstrates the issue.

GenericRef.computeRefFormat() still seems to have the same flaw.  Just because a ref starts with "http" does not mean it is a URL.  I think it should be checking if the ref starts with "http:" (with a colon) or "https:" (with a colon).

**Comment by fehguy** [comment]
@benken-parasoft sure thing, but can you please provide a test case in a PR?

**Comment by benken-parasoft** [comment]
Thank you for your quick reply.  I can submit a PR, just don't know how soon I'll be able to do this.  Perhaps, GenericRefTest could have a couple extra assertions for refs starting with "http" but not "http:" or "https:"

**Comment by benken-parasoft** [comment]
Just created https://github.com/swagger-api/swagger-core/pull/2108

**Comment by fehguy** [comment]
Thank you
