### ISSUE TITLE
Upgrade Jackson version to 2.7.5

### ISSUE THREAD

**Issue by adamzr** [swagger-api/swagger-core#1859]
I'm having Jackson version conflicts in my project. Please update Swagger to use the latest version of Jackson.

**Comment by webron** [comment]
Just exclude it from the dependency.

**Comment by benken-parasoft** [comment]
Let maven's dependency management mechanism (not swagger-core) control the version of Jackson you want your projects to depends on.  Use this to manage "jar hell": https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management

Even if your project depends on swagger-core, you can specify a newer version of Jackson in dependency management, provided that it its API is compatible.  Jackson doesn't break their API with minor version updates.  In this case, updating to a newer Jackson 2.x should be safe (at your own risk, do you own testing).

However, I am not saying that updating swagger-core's Jackson dependency is necessarily a bad thing either.  Jackson 2.4.5 is a bit behind.

**Comment by adamzr** [comment]
@benken-parasoft I used dependency management to fix a conflict with Jackson 5. So, this is not an immediate blocking problem for me. But, I feel that it's best to stay up to date with all dependency versions which is why I opened this ticket.

**Comment by fehguy** [comment]
Jackson is pretty good about being forward compatible. Going too far can cause issues for others but yes we will consider the update. 

Btw I saw "Jackson 5" in your comment and smiled

**Comment by fehguy** [comment]
Done in latest to 2.8.4
