### ISSUE TITLE
generated swagger.json does not show things from resource class

### ISSUE THREAD

**Issue by bodycombathuang** [swagger-api/swagger-core#1861]
I did the steps in https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5
I have a resource class
package resource;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

```
@Path("/hello")
public class MyResource {

    @GET
    @Produces("text/plain")
    @Path("/path1")
    public String getHello() {
        return "Hello World!";
    }
    @POST
    @Consumes("text/plain")
    @Produces("text/plain")
    @Path("/path2")
    public Response post(String str) {
   return Response
           .status(200)
           .entity(str+"bodyattack").build();
    }
}
```

and this is my Application class
   BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.2");
        beanConfig.setSchemes(new String[]{"http"});
        beanConfig.setHost("localhost:8080");
        beanConfig.setBasePath("/jerseyproject");
        beanConfig.setResourcePackage("resource");
        beanConfig.setScan(true);

here is my web.xml

<web-app version="2.5" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd">
    <servlet>
        <servlet-name>testservlet</servlet-name>
        <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
        <init-param>
            <param-name>javax.ws.rs.Application</param-name>
            <param-value>jerseyproject.MyApplication</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>

```
    <servlet>
    <servlet-name>Jersey2Config</servlet-name>
    <servlet-class>io.swagger.jersey.config.JerseyJaxrsConfig</servlet-class>
    <init-param>
        <param-name>api.version</param-name>
        <param-value>1.0.0</param-value>
    </init-param>
    <init-param>
        <param-name>swagger.api.basepath</param-name>
        <param-value>http://localhost:8080/jerseyproject</param-value>
    </init-param>
    <load-on-startup>2</load-on-startup>
</servlet>
<servlet-mapping>
    <servlet-name>testservlet</servlet-name>
    <url-pattern>/*</url-pattern>
</servlet-mapping>
```

</web-app>

my project is running in tomcat, I can use http://host:8080/jerseyproject/hello/path1 to invoke that GET method

but http://localhost:8080/jerseyproject/swagger.json only shows  
{"swagger":"2.0","info":{"version":"1.0.2"},"host":"localhost:8080","basePath":"/jerseyproject","schemes":["http"]}

it should shows things in MyResource class ,

**Comment by webron** [comment]
You need to add the [annotations](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X) for it to pick up the resources.

**Comment by bodycombathuang** [comment]
I added the annotation, but still cannot see resource in the generated swagger.json, have uploaded the project zip through email

**Comment by webron** [comment]
The project structure you sent is somewhat odd and is difficult to follow. Can't really find any usage of the annotations in it.

Check out the many sample projects that are available at https://github.com/swagger-api/swagger-samples and pick up what's needed from there.

**Comment by mashkurm** [comment]
Hello Ron,

I am not able to see any POST, PUT or PATCH request in my swagger.json after setting up the jetty server..

What can be the cause, I tried the solution given above, but it didn't work..

I am using the code from here - https://github.com/swagger-api/swagger-samples/tree/master/java/java-resteasy-filter

Thanks in advance..
-Mashkur

**Comment by sunsus** [comment]
What was the solution?
