### ISSUE TITLE
How to use selected fields from a class to each request

### ISSUE THREAD

**Issue by spyninja** [swagger-api/swagger-core#1863]
Hello! I am having a problem using @Example annotation (or at least I believe I have to use this).

I am having a class like this:

`class Source{
    String url;
    String category;
    String label;
    ...
}`

I am currently using @ApiImplicitParam to set the dataType to Source.class, but I am having multiple POST requests that get a JSON as a body parameter with, lets say, a single variable of those, for example:

`{"label": "labelA"}`

Because of the dataType set previously, the example value displayed by the Swagger UI is a whole Source.class, something like this:

`{"url": "string", "category": "string", "label": "string", ... }`

Could I somehow chop the example value displayed by the Swagger UI for every single request of those? I mean that the getSourceFromUrl() request should get a JSON that contains only a url field, and the example should display exactly this and not the full Source.class JSON.

Thank you all in advance!

**Comment by ahasall** [comment]
I am also in desperate need of this feature.

**Comment by webron** [comment]
For now the only way to do it is by using different classes for the different cases.

**Comment by spyninja** [comment]
Yes, I've come to that conclusion, it just felt bad. Thank you for the response.
