### ISSUE TITLE
Something like `root` option for @ImplicitApiParams

### ISSUE THREAD

**Issue by dsounded** [swagger-api/swagger-core#1864]
Just for now it gets only @ImplicitApiParam values but if you have nested resources in request, let's say JSON:

`{"person": {"name": "John"}}` it will be good to have option `root` for specification that `person` root namespace. I do believe It will help to generate proper calls for `swagger-ui`

```java
@ApiImplicitParams(Array(
`new ApiImplicitParam(name = "person[name]", value = "Person's name", required = true, dataType = "String", paramType = "body")
))
```

 doesn't work

**Comment by webron** [comment]
So you want to expose partial fields of a model for some parameters? The code example you provided doesn't really translate to the JSON example you provided (not that it's supported, it just logically doesn't translate).

**Comment by dsounded** [comment]
Basically I just need to declare my @ImplicitApiParam the way it could work with such a Json representation. I know that my example looks more than query string, I've just tried couple of declaration ways.

**Comment by fehguy** [comment]
I don't think this is supported by this library.  If you can make a more clear goal, it may be doable.
