### ISSUE TITLE
Use of .properties files with annotations for documentation

### ISSUE THREAD

**Issue by krystofurr** [swagger-api/swagger-core#1866]
Hello,

This isn't so much an issue, but I request to see if this exists.  I have started using SpringFox and was wondering if it's possible to use properties defined within a .properties file and use them with the swagger annotations?  This way you could have different documentation for different locale's if you wished.  An example might be like this:

```
@Api(value="{myApi.value}", description="{myApi.description}")
@RestController
@RequestMapping("/")
public class MyController {
    
    @ApiOperation(value="{myApi.myApiMethod}")
    @RequestMapping(method = RequestMethod.GET)
    public MyObject myApiMethod(@ApiParam(name="id", value="{myApi.myApiMethod.id}", required=true) 
                        @PathVariable("id") Integer id) {
        .....
    } 
```

**Comment by webron** [comment]
This should be opened on [Springfox](https://github.com/springfox/springfox/).
