### ISSUE TITLE
io.swagger.servlet.config.WebXMLReader shouldn't default to Scheme.HTTP

### ISSUE THREAD

**Issue by DerEineDa** [swagger-api/swagger-core#1870]
Using swagger-core 1.5.9:

The WebXMLReader for Servlets shouldn't default to Scheme.HTTP;

`private Scheme scheme = Scheme.HTTP;`

I use a relative basePath without a host and scheme. This is valid according to the current swagger specification. In this case, the scheme and host should default to the scheme and host that were used to access the swagger specification.

Unfortunately, even if I define the Scheme to HTTPS using a `@SwaggerDefinition`-Annotation, the default Schema.HTTP of the WebXMLReader will still be included in the generated swagger spec.

I think the correct way to handle this is to just default to `null` inside the WebXMLReader class.

**Comment by fehguy** [comment]
That indeed is valid.  I just looked at the `WebXMLReader` and it will leave `schemes` as null if not set.  This may have changed since you filed the issue, so please reopen if you are having trouble still.
