### ISSUE TITLE
Resource/SubResource Implementations Are Not Properly Picked Up

### ISSUE THREAD

**Issue by battags** [swagger-api/swagger-core#1872]
I have the following structure (which is needed by the way we split out interfaces and service implementation):
- Interfaces with JAX-RS annotations
- Implementations that extend the interfaces and add additional Swagger annotations

This works fine when I'm only using resources.  However, if one of those is a sub-resource, I run into problems.  So, my actual structure:
- Interface (Resource) with JAX-RS annotation (@Path) and method that references SubResource (method has @Path )
- Interface (SubResource) with no JAX-RS annotation (@Path) but appropriate @GET, etc.
- Implementation of Resource that has Swagger annotations
- Implementation of SubResource that has Swagger annotations

I encountered two problems:
1. For some reason if I don't copy the @Path to the implementing method that returns the SubResource, the SubResource isn't recognized (I would have thought it should get that from the parent?
2. Because the method returns the SubResource interface instead of the specific implementation, the Swagger annotations for the SubResource are never found.  Overriding the response value of @ApiOperation to point to the implementation doesn't seem to do anything.

Is there a way to accomplish the above by keeping the Swagger annotations on implementations?
(note: I'm using Swagger 1.5.9)

Thanks
Scott

**Comment by fehguy** [comment]
Please try the latest.  A lot of work has gone in to support interfaces, generics, and subclasses.
