### ISSUE TITLE
@ApiImplicitParam paramType="path" and dataType=PrimitiveType produces wrong JSON

### ISSUE THREAD

**Issue by djivko** [swagger-api/swagger-core#1873]
If we have implicit param with primitive type e.g.
`@ApiImplicitParams(value = {
      @ApiImplicitParam(name = "id", dataType = "long", paramType = "path", required = true)
  })`

the produced json is:
`{  
  "name":"id",
  "in":"path",
  "required":true,
  "type":"long"
}`

while it should be:
`{  
  "name":"id",
  "in":"path",
  "required":true,
  "type":"integer",
  "format":"int64"
}`

**Comment by webron** [comment]
Which version of swagger-core have you tested with? Can you try with `Long`?

**Comment by djivko** [comment]
ver. 1.5.9. I tried with Long, java.lang.Long, int64 - it has the same result. The type in the json response is exactly the same as the one in dataType and there is no 'format' property.

**Comment by oakesk** [comment]
The described behaviour is also observed for `paramType = "query"`. However `paramType="body"` produces the expected output. 

Perhaps the conversion from the common type name to the expected data type + format performed [here](https://github.com/swagger-api/swagger-core/blob/0d72a72c33021e03a9876dc45d2656d11604037e/modules/swagger-core/src/main/java/io/swagger/util/ParameterProcessor.java#L175) should also be invoked in the other parameter processing call paths?

**Comment by cretz** [comment]
This occurs for me too. It should be noted the wiki at https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#apiimplicitparam-apiimplicitparams specifically says it does to the `integer`/`int64` thing instead of what it actually does (as this issue shows).

**Comment by fehguy** [comment]
As of https://github.com/swagger-api/swagger-core/commit/9e8b2c6bff639598df077465b9a78ebb854f0b83, the preferred mechanism to override is by using `type` and `format` but we can merge this specific case anyway.

**Comment by djivko** [comment]
As there is a way now to provide a `format` when overriding I do not think there is a need to merge this specific case. It's up to you to decide that. Thanks.

**Comment by fehguy** [comment]
This should be fixed now, and can be overridden by https://github.com/swagger-api/swagger-core/commit/9e8b2c6bff639598df077465b9a78ebb854f0b83
