### ISSUE TITLE
Swagger UI integration issue

### ISSUE THREAD

**Issue by sandipmangale** [swagger-api/swagger-core#1874]
- swagger-ui version **v2.1.4**
- a swagger file reproducing the issue -index.html

**Brief description for problem.**
 I am using swagger.io's  _swagger-jaxrs - 1.5.9_

I am trying to integrate Swagger UI for Rest easy API. I am able to see swagger.json at http://localhost:8080/SwaggerRestAPI/rest/swagger.json. I have copied dist folder in WEB-INF folder and changed the url in index.html to http://localhost:8080/SwaggerRestAPI/rest/swagger.json and tried to fetch UI by using URL http://localhost:8080/SwaggerRestAPI but it is returning 404 response. Can anybody help me?

**Comment by fehguy** [comment]
I think this belongs in swagger-ui.
