### ISSUE TITLE
Override both type and format in annotation

### ISSUE THREAD

**Issue by ralfstuckert** [swagger-api/swagger-core#1875]
Sometimes the type and/or format generated by swagger bindings is inappropriate (due to issues or fuzzy spec). It would be very helpful, if one could override the type and format in `@ApiModelProperty` annotation, to match its needs. Currently you can specify an alternative type in the `dataType` attribute. But this does not help, if there is no adequate alternative.

So, is there currently a way to override theses attributes, or would that be a desirable feature?

**Comment by fehguy** [comment]
This has been added in https://github.com/swagger-api/swagger-core/commit/9e8b2c6bff639598df077465b9a78ebb854f0b83
