### ISSUE TITLE
ApiReponse configuration for file download

### ISSUE THREAD

**Issue by vhochstein** [swagger-api/swagger-core#1876]
Hi,

may I configure ApiResponse to receive the following swagger specification:
responses:
200:
description: Returns PDF
schema:
type: file

These two variations do not work:
@ApiResponse(code = 200, message = "Returns PDF")
@ApiResponse(code = 200, message = "Returns PDF", response = File.class)

**Comment by jelaby** [comment]
I think that this is a duplicate of #1290. The answer appears to be "no" at the moment.

**Comment by fehguy** [comment]
Use `response=byte.class` to properly represent a file download, and set the `@Produces` appropriately.
