### ISSUE TITLE
datatype not working in @ApiImplicitParam

### ISSUE THREAD

**Issue by dev-spirit** [swagger-api/swagger-core#1879]
When I used datatype = "packageName.objectName.caseClassName", like
ApiImplicitParam(name = "bannerJson", required = true, dataType+ "**packageName.objectName.caseClassName**" , paramType = "body", value = "")

It is not working but went I put my case class out side the object its working fine (in package). So, there is any solution for it. 

Thanks.....

**Comment by fehguy** [comment]
You may have trouble with scala classes if they are objects with inner classes.

**Comment by dev-spirit** [comment]
object NetworksDataModel {
  case class VideoWithAttributes(video: Video, attributes: Map[String, String], playlistId: Option[Long])
  case class PlaylistWithAttributes(playlist: Playlist, attributes: Map[String, String], grouplistId: Option[Long])
  case class GrouplistWithAttributes(grouplist: Grouplist, attributes: Map[String, String])
  case class StreamDetailsWithVideoId(stream: StreamDetails, videoId: Option[Long])
  case class CategoryData(category: Category, categoryGenres: List[CategoryGenre], categoryAttributes: List[CategoryAttributes], entityCategory: EntityCategory)
  case class CodeData(name: String, code: String)
  case class ClientBanner(id: Long, webImageUrl: String, mobileImageUrl: String, sourceType: String, sourceSubType: String, overlayText: String, targetURL: String, uploadDate: Timestamp, isActive: Boolean = true, langCodes: String, tenantIds: List[Long], whoColumns: WhoColumns)
  case class ClientGeoFilter(contentType: Long, contentId: Long, filterType: Long, countryCodes: String)
}

I want to access ClientBanner, which is presented in package com.adminserver.dto

**Comment by fehguy** [comment]
You should probably open this in the swagger-scala-module project.  But as I said, I don't think you can reference inner classes inside scala objects
