### ISSUE TITLE
Model of all methods annotated with responseContainer = "List" incorrectly begins with Inline Model [ Inline Model 1 ]

### ISSUE THREAD

**Issue by pgodzin** [swagger-api/swagger-core#1880]
This issue comes up for every method annotated with responseContainer = "List"

For instance, we have this getOrgs method and corresponding generated model:
```
@GET
@Path("/orgs")
@ApiOperation(value = "Lists all Orgs.", response = Org.class, responseContainer = "List", position = 1)
@ApiResponses(value = {@ApiResponse(code = 500, message = Constants.BASE_PATH_NOT_FOUND) })
public List<Org> getOrgs() throws ServiceException;
```
```
Inline Model [
    Inline Model 1
]
Inline Model 1 {
    id (string, optional),
    batches (Array[Batch], optional)
}
Batch {
    id (integer, optional),
}
```
Instead of Inline Model 1, we expect it to say Org, as annotated by the response property. The swagger.json correctly states that the response is a collection of Orgs: 

`"summary":"Lists all Orgs.","description":"","operationId":"getOrgs","parameters":[],"responses":{"200":{"description":"successful operation","schema":{"type":"array","items":{"$ref":"#/definitions/Org"}}}`

Instead, we get the following schema:

Before updating to swagger-core and swagger-jaxrs 1.5.9, we were on version 1.3 and the model for getOrgs was: 
```
Org {
     id (string, optional),
     batches (array[Batch], optional)
}
Batch {
    id (integer, optional),
}
```

All methods returning a single Org are displayed properly with no inline methods. The Org model class has no annotations on it. Is this a known Swagger issue with responseContainer = "List" methods or is there something we are missing that has changed in the new versions of Swagger?

**Comment by webron** [comment]
Okay, so it looks like you cross-posted. The underlying issue is with swagger-ui, but I gave you a potential solution using swagger-core over in the other ticket.
