### ISSUE TITLE
How to show only required parametrs in Swagger-UI "Value" field

### ISSUE THREAD

**Issue by yami12376** [swagger-api/swagger-core#1881]
Can you help me with that matter:
http://stackoverflow.com/questions/38920935/how-to-show-only-required-parametrs-in-swagger-ui-value-field/38921490?noredirect=1

**Comment by yami12376** [comment]
If it is not possible - could you make it possible?
You have got information in swagger what is optional and what not so i think it is doable.

**Comment by webron** [comment]
looks like you got an answer from @fehguy in SO.
