### ISSUE TITLE
Generating a swagger.json during compile time using a Maven plugin

### ISSUE THREAD

**Issue by tofflos** [swagger-api/swagger-core#1883]
I've written a Maven plugin that generates a Swagger.json during compile time. Basically all it does is

```
Set<Class<?>> classes = reflections.getTypesAnnotatedWith(Path.class);
new Reader(swagger, new DefaultReaderConfig()).read(classes);
objectMapper.writeValueAsString(swagger);

```

Would  there any interest in such a pull request? For me the upside was fewer runtime dependencies (only swagger-annotations) and less dependency conflict resolution related to Jackson. But mostly I wrote the plugin because I was skeptical of including third-party services in my application just to provide a static file.

There are a handful of other projects that seem to be driven by similar concerns. But it would be nice to have something backed by you.

**Comment by webron** [comment]
You mean something like https://github.com/kongchen/swagger-maven-plugin?

**Comment by tofflos** [comment]
Very similar.

My plugin uses your Reader whereas that plugin provides its' own implementation. So my plugin produces the same output as your JAX-RS based solution whereas that plugin does not. Otherwise I would say that the maven-swagger-plugin is better at pretty much everything. It provides more features, it supports more frameworks and has had more testing. I just happened to run into some problems with their Reader and decided to write a plugin that utilizes your Reader instead.

I could see my plugin as being interesting for you if you want to offer a provide time solution without much of an initial effort followed by continuous minimal effort for maintenance. It's a single-page-of-code-wrapper around your existing work and will therefor automatically benefit from the improvements you make to your core product.

Anyway. Let me know and I'll zip you my project and send it to you. I do believe that many users will appreciate a build time solution.

**Comment by fehguy** [comment]
Hi, since this project is really for run-time integration, it doesn't make sense to add it in here.

**Comment by lalpert** [comment]
@tofflos I could really use this! Any chance you still have this plugin that you could share?

**Comment by tofflos** [comment]
@lalpert I couldn't find it but it seems someone has created something similar at https://github.com/openapi-tools/swagger-maven-plugin.

**Comment by lalpert** [comment]
@tofflos Thanks, I'll check it out!
