### ISSUE TITLE
Is it possible to break up Swagger 2 spec swagger.json into multiple resources?

### ISSUE THREAD

**Issue by rdiehl** [swagger-api/swagger-core#1885]
With Swagger 1 spec, there was a Swagger resource at /api-docs, which loads all endpoints.  You could also go to endpoints one at a time via /api-docs/animals or /api-docs/cars.  This is useful for us because we have a giant API with 70+ endpoints and 1500+ methods.

The upgrade to the Swagger 2 spec generates a single swagger.json by default.  I know that you can break things up using refs.

We are using BeanConfig with scan=true and ApiListingResource to generate our swagger.json file.  Is there any way to configure it so that it generates multiple files?

**Comment by webron** [comment]
Not OOTB.

**Comment by rdiehl** [comment]
OK thanks, I'm going to close this, it's not necessarily a feature request or anything, we were just using that as a workaround for issues in swagger-ui with huge apis.
