### ISSUE TITLE
Configuration not applied after upgrading to 1.5.7

### ISSUE THREAD

**Issue by fdelsert** [swagger-api/swagger-core#1886]
Hello,

I'm using _jersey-core 1.5.5_ and I need to upgrade to  >= 1.5.7 in order to fix ObjectMapper issue  #1604 (my JSON date formatting is incorrect).

It works fine but now I have a problem with the swagger.json, my configuration is not applied :

`{"swagger":"2.0","info":{"version":"Swagger Server","title":""},"tags": ...`

The rest of the document is correct, I can use it in Swagger-UI but I can't call my API because host / basePath are not set in the document.
My configuration is defined like in this post (to define contextPath as basePath) : http://stackoverflow.com/a/35905415/1001248

I'm using _swagger-jersey-jaxrs_ in a _Glassfish  3.1.2.2_  environnement.

**Comment by webron** [comment]
Since in many cases 'like' is not 'exactly like', can you please share your configuration including your web.xml and any class you use to bootstrap swagger-core? Which version of Jersey do you use?

**Comment by fdelsert** [comment]
I understand.

I pushed a sample maven project to reproduce the issue :
https://github.com/fdelsert/swagger-issue-1886

I excluded Jersey dependencies 1.13 of swagger-jersey-jaxrs because I use Jersey 1.11 provided by Glassfish server. Maybe the problem came from an incompatibility with the Jersey version.

I must admit that I don't understand the different way to configurate swagger-core. 

Direct links : 
- [pom.xml](https://github.com/fdelsert/swagger-issue-1886/blob/master/pom.xml)
- [web.xml](https://github.com/fdelsert/swagger-issue-1886/blob/master/src/main/webapp/WEB-INF/web.xml)
- [configuration class](https://github.com/fdelsert/swagger-issue-1886/blob/master/src/main/java/com/foo/bar/rest/SwaggerConfigReader.java)
- [endpoint](https://github.com/fdelsert/swagger-issue-1886/blob/master/src/main/java/com/foo/bar/rest/Endpoint.java)

**Comment by fdelsert** [comment]
The exclusions in the pom.xml are useless because ClassLoader avoid overriding of embedded packages (https://jersey.java.net/nonav/documentation/1.13/glassfish.html#d4e1938).

Upgrading Jersey to 1.13 in Glassfish give the same result.

**Comment by lemoncolly** [comment]
I am seeing the same issue when using the JAX-RS bundle, in this case **swagger-jaxrs:1.5.10**

**Comment by fdelsert** [comment]
@lemoncolly It works like a charm. But you are right, it's not the most convenient way.

**Comment by fehguy** [comment]
OK, the `BeanConfig` is used for programmatic configuration without needing web.xml.  The web.xml configuration will not trigger scanning in BeanConfig.  So you have two choices:

1) Use web.xml through the `DefaultJaxrsConfig`.  You don't need to subclass it, and doing so the way you did isn't going to work.  Use the fields that are supported in that class, including host and basepath.

2) Use a programmatic configuration.  You can follow a pattern like this:

https://github.com/swagger-api/swagger-samples/tree/master/java/java-jaxrs

Where a web.xml configures _most_ of the application, and a custom servlet does the rest.
