### ISSUE TITLE
how to hide properties from swagger doc

### ISSUE THREAD

**Issue by raghala** [swagger-api/swagger-core#1892]
Hi,

I am using swagger doc to describe our rest services, In the entities I want to hide some property, I used @JsonIgnore and @ApiModelProperty(hidden=true). It is not working. Could anyone please help?

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by raghala** [comment]
Version 1.5.8

**Comment by fehguy** [comment]
Hidden=true is certainly working and is well tested.  Consider sending a PR showing a test that is failing and we can look into it.
