### ISSUE TITLE
@ApiImplicitParams should target ANNOTATION_TYPE too

### ISSUE THREAD

**Issue by vtorosyan** [swagger-api/swagger-core#1899]
Currently `@ApiImplicitParams` annotation is supported only in `METHOD` context, so that you are able to describe implicit parameters only on top of method declaration. 

When having implicit parameters (such as request headers) common to more than one resource it's really inconvenient to describe the same params for each and every resource along other annotations.

`@ApiImplicitParams` could target also `ANNOTATION_TYPE` so that it will be possible to create combined annotations and reuse them elsewhere.

For example when using Spring MVC

```
@RequestMapping(
            value = "/test"
            produces = MimeTypeUtils.APPLICATION_JSON_VALUE + ";charset=UTF-8",
            method = RequestMethod.GET)
@ResponseBody
@ApiImplicitParams({@ApiImplicitParam(name = "name", value = "desc", required = false, dataType = "string", paramType = "header")})
```

I'd like to have instead custom combined annotation in the following way

```
@RequestMapping(
        produces = MimeTypeUtils.APPLICATION_JSON_VALUE + ";charset=UTF-8",
        method = RequestMethod.GET)
@ResponseBody
@ResponseStatus(HttpStatus.OK)
@ApiImplicitParams({@ApiImplicitParam(name = "name", value = "desc", required = false, dataType = "string", paramType = "header")})
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface Get {

    @AliasFor(annotation = RequestMapping.class, attribute = "value")
    String[] value() default {};

}
```

 So that `@Get` could be used instead of describing `@ApiImplicitParams` explicitly everywhere.

**Comment by JamieMagee** [comment]
Looks like #1867 fixes this. It's been open for a few months now.
