### ISSUE TITLE
specifying variable keys in response object

### ISSUE THREAD

**Issue by someGuy132** [swagger-api/swagger-core#1902]
Hi, 

I'm trying to model a response object that looks like this: 
{
    "0123122ec9bebab2ee":
    ["d625d00f-93bc-475f-85be-239ae551f7f2"]
}

where the key is variable.  Is there a way to do this in swagger?  

I tried this, but it produces a weird output: 

``` json
  TaskDelete_R:
    type: object
    properties: 
      {dev_id}:
        description: device ID
        type: array
        items: 
          type: string
```

Any help would be greatly appreciated.

Cheers, 
Nelson.

**Comment by fehguy** [comment]
This just isn't supported in the specification.
