### ISSUE TITLE
Provide instructions or update example for multi-servlet application using beanConfig.

### ISSUE THREAD

**Issue by pixels4nickels** [swagger-api/swagger-core#1903]
Work was done in https://github.com/swagger-api/swagger-core/issues/1514 which allows you to `set swagger.config.id` and `swagger.scanner.id` as init-params in web.xml to allow swagger to distinguish configurations. 

I am still not sure if multiple apis using BeanConfig work because there is no example of how to apply these property values. Please provide information on how to use the BeanConfig to do the same thing as the web.xml does for this approach to multiple APIs in a single application.

**Comment by fehguy** [comment]
See the examples in the swagger-samples project.

**Comment by matevarga** [comment]
Note: a link to the sample that demonstrates the answer would have been nice - I went through the samples but I could not find anything that looks completely related.

**Comment by dsunjka** [comment]
@matevarga I couldn't find a relevant example as well. Luckily, in Issue #1514 in the last comment there is an example how to do it without a web.xml (defining own webservices which then use BeanConfig).
