### ISSUE TITLE
Misspelled names in annotations.SecurityDefinition

### ISSUE THREAD

**Issue by scop** [swagger-api/swagger-core#1908]
annotations.SecurityDefinition contains two misspelled method names:
- apiKeyAuthDefintions should be apiKeyAuthDefinitions
- basicAuthDefinions should be basicAuthDefinitions

**Comment by fehguy** [comment]
Yikes.  If you have time, please send a PR that _adds_ the new methods and deprecates (but leaves present) the old.  We'll have to make some adjustments in the `Reader` to ensure that the annotation values are both considered.

This will ensure it's address in the next major version

**Comment by scop** [comment]
Ok, see #1919 (untested)
