### ISSUE TITLE
@ApiImplicitParam for Map<String, String> objects

### ISSUE THREAD

**Issue by UPADHYA28** [swagger-api/swagger-core#1909]
I have a API which accepts One string, and One MAP as the input.

`public ModelClass getMyApi(String inparm, Map<String, String> myValues)`
I am wondering how can i capture MAP input in swagger document using 

> @ApiImplicitParams
> @ApiImplicitParam 

annotations.

I have tried with like this
 ```
@ApiImplicitParam(name="myValues", value="Validation Values Map", required =
         true, dataType = "Map", paramType = "query")
```
But no luck.

Note: Am using Swagger-servlet Module.

Thanks.

**Comment by realXuJiang** [comment]
Hi , Has this issue been resolved？
