### ISSUE TITLE
Collections/Lists of FormDataBodyPart elements not filtered out by SwaggerJersey2Jaxrs

### ISSUE THREAD

**Issue by dastoikov** [swagger-api/swagger-core#1911]
When processing @FormDataParam-annotated parameters, the SwaggerJersey2Jaxrs extension filters out parameters of type FormDataContentDisposition or FormDataBodyPart. However, collections or lists of the former types are not filtered out.

Here is what the Jersey2 apidocs have to say about the @FormDataParam annotation (cite):

> The type T of the annotated parameter must be one of the following:
> 1. FormDataBodyPart.
> 2. A List or Collection of FormDataBodyPart.
> 3. FormDataContentDisposition.
> 4. A List or Collection of FormDataContentDisposition.

If you think collections and lists of these types should be filtered out too, I would be happy to submit a pull request.

**Comment by fehguy** [comment]
Can you please give an example of what you are trying to get documented by swagger?

**Comment by dastoikov** [comment]
Here is a simplified example:
```
... post(@FormDataParam("propertyName") Collection<FormDataBodyPart> propertyNames,
            @FormDataParam("propertyValue") Collection<FormDataBodyPart> propertyValues) {}

```
where each individual propertyName or propertyValue can be obtained by calling getValue() on the respective form-data-body-part instance.

When enriched with Swagger Annotations, the example would become:
```
@ApiImplicitParams(value={
  @ApiImplicitParam(value="Name of the property to store", name="propertyName", paramType="form", dataType="string", required=true, allowMultiple=true),
  @ApiImplicitParam(value="Value of the property to store", name="propertyValue", paramType="form", dataType="string", required=true, allowMultiple=true)
})
... post(@FormDataParam("propertyName") Collection<FormDataBodyPart> propertyNames,
            @FormDataParam("propertyValue") Collection<FormDataBodyPart> propertyValues) {}

```
At this time, the Jersey2 extension will not skip the collection-typed parameters and a Swagger model will be generated for the type FormDataBodyPart, and referenced from within individual parameter descriptions.

**Comment by dastoikov** [comment]
Also, parameters of type `org.glassfish.jersey.media.multipart.MultiPart` are not filtered out.
A service method like this:
```
@POST
public void post(MultiPart body) {
}
```
would result in a Swagger definition like this:
```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0",
    "title" : "A multipart example"
  },
  "tags" : [ {
    "name" : "Multipart Resource"
  } ],
  "paths" : {
    "/multipart" : {
      "post" : {
        "tags" : [ "Multipart Resource" ],
        "operationId" : "post",
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/MultiPart"
          }
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    }
  },
  "definitions" : {
...
   "MultiPart" : {
      "type" : "object",
      "properties" : {
        "contentDisposition" : {
          "$ref" : "#/definitions/ContentDisposition"
        },
        "entity" : {
          "type" : "object"
        },
        "headers" : {
          "type" : "object",
          "additionalProperties" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        },
        "mediaType" : {
          "$ref" : "#/definitions/MediaType"
        },
        "messageBodyWorkers" : {
          "$ref" : "#/definitions/MessageBodyWorkers"
        },
        "parent" : {
          "$ref" : "#/definitions/MultiPart"
        },
        "providers" : {
          "$ref" : "#/definitions/Providers"
        },
        "bodyParts" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/BodyPart"
          }
        },
        "parameterizedHeaders" : {
          "type" : "object",
          "additionalProperties" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/definitions/ParameterizedHeader"
            }
          }
        }
      }
    }
...
}
```

I would suggest that MultiPart parameters are filtered out. Authors wishing to detail the structure of the multipart could use `@ApiImplicitParam` annotations on the method.
What do you think?

Cheers,
Dimitar

**Comment by fehguy** [comment]
This should be supported in 1.5.11.

**Comment by umangkedia** [comment]
@dastoikov I am using the same construct. But after taking input from swagger, I am not getting a list of values in Collection<FormDataBodyPart>. Any idea how to solve this?

**Comment by dastoikov** [comment]
@umangkedia I remember installing a Swagger Jersey2 extension. These are custom processors that can be plugged in.
Sorry for not providing links: I am on a holiday and will be back on Tuesday.

**Comment by umangkedia** [comment]
@dastoikov Sure. Can you post the links once you are back? It's working fine from Postman but not working from Swagger.

**Comment by dastoikov** [comment]
@umangkedia On a second thought, I seemingly misunderstood your post.
Anyway, please find below links to the swagger extensions I was talking about:
1. The contract for extensions:
https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ext

2.The stock Swagger Jersey2 extension that the library ships with:
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/java/io/swagger/jersey/SwaggerJersey2Jaxrs.java

To solve my problem, I installed an extension that assumes control before [2], and handles the case of MultiPart and collections of FormDataBodyPart parameters.

Hope this helps!
