### ISSUE TITLE
ReaderListener not considered during output generation 

### ISSUE THREAD

**Issue by objectbakery** [swagger-api/swagger-core#1912]
Hi,

we need to customize the generated json output. Therefore we implemented a custom ReaderListener class (following these instructions http://swagger.io/customizing-your-auto-generated-swagger-definitions-in-1-5-x/) but it seems the class is not used. 

I put the class inside the same package as our actual resource files are located. I added and removed the @SwaggerDefinition annotation. Nothing shows any effect. The beforeScan method is not called.

We are using swagger-jersey-jaxrs 1.5.10. The BeanConfig object is provided by a Spring configuration. 

What else could be wrong? 

Any help is appreciated.

Kind regards,
Sebastian

**Comment by fehguy** [comment]
Hmm I believe it's possible that the `BeanConfig` will wipe out the `@SwaggerDefinition` annotations.  Can you possibly share a sample configuration?

**Comment by s-metzger** [comment]
Had the same issue, it worked once I added @Path and @Api annotation to the class that implements ReaderListener (albeit Jersey will complain with a warning if that class does not specify an endpoint).

**Comment by sabika-24** [comment]
Hi @objectbakery , 
Did u find any concrete solution to your problem , I am facing same issue .

**Comment by objectbakery** [comment]
Sorry to tell, but I never investigated any further into that issue.

**Comment by sabi-24** [comment]
No Problem , Thanks for your response
