### ISSUE TITLE
@ApiModelProperty example property does not support Map data types

### ISSUE THREAD

**Issue by BicycleK** [swagger-api/swagger-core#1914]
When the @ApiModelProperty.dataType = "Map", the JSON output of the example is invalid

For example:
```java
@ApiModelProperty(
            value = "IdP-to-SP attributes mapping. A string map of key/value pairs with keys corresponding to IdP attributes as the source " +
                    "and values corresponding to SP attributes as target.  May be omitted or partially-defined to use default mapping.",
            example =   "{'firstName': 'fname', 'lastName' : 'lname'}",
           dataType = "Map[String,String]",
            required = false)
    public Map<String, String> getAttributeMapping();
```
Produces:
```
  "attributeMapping": "{'firstName': 'fname', 'lastName' : 'lname'}"
```

However it should produce:
```
  "attributeMapping": {'firstName': 'fname', 'lastName' : 'lname'}
```

The attributeMapping field is incorrectly treated like a string and quoted.

**Comment by AngryPirate** [comment]
+1

**Comment by fehguy** [comment]
Follow #1107

**Comment by JessieGit** [comment]
Hi, I am also experiencing the similar problem. I'd like to show a list of string in the example, but it is not working. If dataType is changed to "List" or "List[String]", all APIs will completely disappear from Swagger UI.  
@ApiModelProperty(required = true, dataType = "List[String]", example = "[\"type0\",\"type1\"]")
private List<String> entityTypes;
From the definition of example, it only supports string type. Then it is supposed to allow json input as shown above. 
Does anyone fix this problem?

**Comment by mejmo** [comment]
Was it solved?
