### ISSUE TITLE
Same resource path

### ISSUE THREAD

**Issue by UPADHYA28** [swagger-api/swagger-core#1915]
Is there any way i can have document two method with same name but with different input parameter?

I am having a situation where i need to document the resources which all are hosted on a same path (kind of micro services in `MyProjects/get?Parameters`) but each micro-service has a same name but different input parameters.

When i annotate my Java source code it generates the paths. But Shen i feed this json to swaggerUI it gives me only one micro-service (i believe this is because same resource path ``MyProjects/get`)

**Comment by fehguy** [comment]
No, that's just not supported by the swagger specification.
