### ISSUE TITLE
How do you set securityDefinition for dropwizard?

### ISSUE THREAD

**Issue by sunshineo** [swagger-api/swagger-core#1920]
Like the one at the root level of
http://petstore.swagger.io/v2/swagger.json

I searched there https://github.com/swagger-api/swagger-samples/search?p=1&q=securityDefinition&type=Code&utf8=%E2%9C%93 and saw securityDefinition settings but not in the dropwizard project.

There is for this on the BeanConfig https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java

I also searched the annotations at https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X but found nothing.

**Comment by fehguy** [comment]
Try using https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/SwaggerDefinition.java
