### ISSUE TITLE
[NewFeatureRequest] add api change log

### ISSUE THREAD

**Issue by sdw2332** [swagger-api/swagger-core#1922]
i'm a backgound programmer, while i was co-working with client developers. i found it's too hard to point out api changes for client developers. and if i forget to tell them what i had done, they could not know the api had been changed even many days passed. but listing all changes is too hard, even i'm the author... so i think if swagger could provide api changelog like diff utils in svn to resolve this problem. really thanks. :)

for example: i rename a property in request params(oldFoo -> newFoo)

<pre>
class InputParameters {                     ---->              class InputParameters {
@ApiModelProperty("foo property")           ---->              @ApiModelProperty("still foo")
private Integer oldFoo;                     ---->              private Integer oldFoo;
}                                           ---->              }
</pre>

after next project building at 2016-08-25, i could see this change at swagger ui like this:

<pre>
<b>changelog at 2016-08-25:</b>
-- /path_to_request
   input model
   - property: Integer oldFoo (foo property)
   + property: Integer newFoo (still foo)
</pre>

client developers will clearly know how to modify after read this, but not read the complete document to find out the changes.

**Comment by Misiu** [comment]
@sdw2332 I was just looking for same thing. As You wrote sometimes it is hard to list all changes, especially those small one.
Having this build-in would be a lifesaver!
