### ISSUE TITLE
How to set schemes of my api in swagger 2.0

### ISSUE THREAD

**Issue by lucas-dehandschutter** [swagger-api/swagger-core#1927]
Hi,

I've added swagger 2 to my spring boot app which is exposing rest apis.

The only thing i did is addind the following code in a configuration class:

`@Configuration
@EnableSwagger2
public class SwaggerConfig {
    @Bean
    public Docket api() {
            
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(Predicates.not(PathSelectors.regex("/error.*")))
                .build();
    }
}`

How can I set to schemes programatically?
I want my api to be reached with http even if the swagger-ui.html is exposed with https .

The @SwaggerDefinition seems to be no longuer valid in swagger 2.0 because i've added the following annotation on a spring controller with no success:

`@SwaggerDefinition(
        info = @Info(
                description = "My API",
                version = "V1.0",
                title = "List of services exposed by my API",
                contact = @Contact(name = "Lucas Dehandschutter", email = "****@*****.**", url = "http://swagger.io")),
        consumes = {"application/json" },
        produces = {"application/json" },
        schemes = {SwaggerDefinition.Scheme.HTTP}
)`

**Comment by webron** [comment]
You're looking for [Springfox](https://github.com/springfox/springfox/).
