### ISSUE TITLE
Swagger does not shown a List of Enum's in the modelview

### ISSUE THREAD

**Issue by martijnburger** [swagger-api/swagger-core#1928]
I have the following code in an Abstract `@ApiModel` class:

```
@ApiModelProperty(required = false)
private List<V> requestedCovers;
```

Where `V` is a Generic Type, defined as  `V extends Enum<V> & CoverType`. I have various classes that extend this Abstract class for different implementations.

In the Swagger UI Model, it shows as follows:

```
requestedCovers (Array[string], optional)
```

Why are the enum options for this implementation not shown?

For comparison, I have also a List of Objects with an enum value in the object which works fine in the same structure:

```
@ApiModelProperty(required = false)
private List<OwnRisk<U>> ownRisks;
```

Where `U` is `U extends Enum<U> & ORType`. There the Swagger UI Model shows:

```
ownRisks (Array[OwnRiskHearingAidORType], optional)
```

and

```
OwnRiskHearingAidORType {
    type (string, optional): The type. = ['GENERIC'],
    value (number, optional): The value.
}
```

So here I see the enum value that are present for this (in this case hearing aid implementeation)

X-Posted from: http://stackoverflow.com/questions/39386157/swagger-does-not-shown-a-list-of-enums-in-the-modelview

**Comment by martijnburger** [comment]
BUMP

**Comment by martijnburger** [comment]
BUMP

**Comment by martijnburger** [comment]
BUMP BUMP

**Comment by fehguy** [comment]
Please send a PR for a test case.

**Comment by martijnburger** [comment]
Working on it!
