### ISSUE TITLE
JsonIgnore appears in model vs Two separate RESTs

### ISSUE THREAD

**Issue by kret11** [swagger-api/swagger-core#1932]
Currently developing Java EE application: 
.ear:
1.api.jar
2.rest1.war
3.rest2.war
Rest objects are located in api.jar, which is dependency of both rest1 and rest2. Swagger is enabled on both of rest projects so there are two separate swagger.json generated. The problem is: if I put swagger-jaxrs as dependency of api.jar - both of swagger.jsons displays same data (the first loaded) and by the other hand if I put swagger-jaxrs dependencies in rest projects - @JsonIgnore on object annotation is ignored by scanner.
1.5.10

**Comment by fehguy** [comment]
Look at the swagger-samples project on using multiple war files in a single JVM.
