### ISSUE TITLE
Remove unnecessary UTF-8 encoding+decoding from `SwaggerSerializers`

### ISSUE THREAD

**Issue by cowtowncoder** [swagger-api/swagger-core#1936]
In `SwaggerSerializers` there are 4 cases of this anti-pattern:

``` java
                out.write(Json.pretty().writeValueAsString(data).getBytes("utf-8"));
```

which unnecessarily first creates output as Java String, then encodes separately.
Simpler straight mechanism is to just use:

``` java
                out.write(Json.pretty().writeValue(out, data)l
```

which combines output serialization and UTF-8 encoding, without any buffering (as opposed to 2 full serializations in memory, first as String, then as byte[]).

Alternatively, if there is value in buffering contents just once (perhaps to catch any exceptions):

``` java
                out.write(Json.pretty().writeValueAsBytes(data));
```

which produces intermediate UTF-8 encoding.

Anyway: fixing this will result in fewer copies in memory, lower trash-generation and bit faster operation. Nothing earth-shattering but there's no need to add unnecessary processing.

**Comment by fehguy** [comment]
added in #2052
