### ISSUE TITLE
Consider upgrade to a later Jackson version (from 2.4)

### ISSUE THREAD

**Issue by cowtowncoder** [swagger-api/swagger-core#1937]
Looks like swagger-core uses Jackson 2.4.5. It would be nice to use a later, supported version.
Safest bets might be 2.5.5 (minor bump), or 2.7.7. Upgrade minor version by minor version may be the safest way to go; using latest patch from minor version.

I have tried to work with framework authors on jackson dependencies, and my current goal is to get as many as possible up to at least 2.7 (latest stable is 2.8, but 2.7 branch is still open and is bit more mature).

**Comment by fehguy** [comment]
Definitely would like to.  We had issues with 2.7.0 but looks like all issues with this project have been resolved in 2.7.1 and greater.

**Comment by pjfanning** [comment]
@cowtowncoder would someone in the Jackson team be able to look at the issue in https://github.com/pjfanning/JacksonTest ? If you think this is a bug, I can log an issue for it.
This appears to be the only remaining issue with upgrading to Jackson 2.7.8 or 2.8.5 (https://github.com/swagger-api/swagger-core/issues/1998 addresses most of the issues)

**Comment by eoftedal** [comment]
As pointed out in #2023 jackson-dataformat-xml 2.4.5 has a known security vulnerability. It would be nice to get rid of that.

**Comment by webron** [comment]
We want to make this update soon, but obviously this requires extensive testing and that requires time, so difficult to give an ETA.

**Comment by cowtowncoder** [comment]
@pjfanning unless there's a self-contained test, it's highly unlikely anyone has time on short term. Or even just a code snippet to show what the suspected problem is. At this point there are no known type-resolution issues with 2.7.8 (but a few have been fixed since 2.7.0), so typically remaining issues are with usage of `TypeFactory`.

**Comment by pjfanning** [comment]
@cowtowncoder https://github.com/pjfanning/JacksonTest does have a self-contained test case.

**Comment by cowtowncoder** [comment]
@pjfanning What I meant was a unit test to point out exact discrepancy. Printing out things isn't the same as it requires more knowledge of what the problem is.

**Comment by pjfanning** [comment]
Thanks @cowtowncoder based on your feedback - I have a solution in https://github.com/swagger-api/swagger-core/pull/2044 .
I think there is more work to do, to take the swagger code and make more use of the annotated type classes in jackson-databind but this is a start and all existing tests in swagger-core work.
