### ISSUE TITLE
@ApiModelProperty   no useful

### ISSUE THREAD

**Issue by waterWang** [swagger-api/swagger-core#1938]
i set position and required in @ApiModelProperty ,but it not working??? 
**ApiModelProperty 1.5.3**
**spring boot 1.4**

code is

`
import javax.validation.constraints.Size;
import io.swagger.annotations.ApiModelProperty;

public class ScheduleDTO {

	@ApiModelProperty(position = 1 ,value = "触发器类型（SimpleTrigger 还是 CronTrigger）", required = true)
	private String triggerType;

	@Size(min = 1, max = 255)
	@ApiModelProperty(position = 2 , value = "job名称", required = true)
	private String jobName;

	@Size(min = 1, max = 255 )
	@ApiModelProperty(position = 3 ,value = "job分组", required = true)
	private String jobGroup;
	
}`

result is

`{
  "jobGroup": "string",
  "jobName": "string",
  "triggerType": "string"
}`

**Comment by webron** [comment]
Please read the javadocs (and any of the other related tickets) - `position` is deprecated.

As for `required` - what JSON you shared is not a Swagger spec, I don't know what it is.
