### ISSUE TITLE
Duplicate operationId when using inheritance

### ISSUE THREAD

**Issue by dasevilla** [swagger-api/swagger-core#1939]
Here's a simple demo:

```
public abstract class BaseClass {
 /**
  * Get some strings
  */
 @GET
 public List<String> getStrings()  {
 return Arrays.asList("somestring", "someotherstring");
 }
}

@Api
@Path("/subclass1")
public class SubClass1 extends BaseClass {}

@Api
@Path("/subclass2")
public class SubClass2 extends BaseClass {}
```

The GET methods for each path will have the same `operationId` fields.

Taken from https://groups.google.com/forum/#!topic/swagger-swaggersocket/5AxQfc9g9rs

Similar to swagger-api/swagger-codegen#1822

[This seems to be the relevant code](https://github.com/swagger-api/swagger-core/blob/73d87ce31c556d95673620fa446e9713ab66d9d5/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L764-L776)

**Comment by HugoMario** [comment]
This [Pull Request](https://github.com/swagger-api/swagger-core/pull/1959) has been created in order to fix the issue. It checks for operationIds related to inherited method and renamed if it finds the operationId is duplicated.

**Comment by fehguy** [comment]
Thanks @HugoMario!  @dasevilla could you please try the PR and see if it addresses your issue?

**Comment by dasevilla** [comment]
I'll give it a try early next week

**Comment by cen1** [comment]
Opening a dead issue here but this fix is not really that great. It appends a counter which means on each deploy, depending on classloader? order it will add the counter to a different method than previous deploy, giving the same method a different name depending on deploy, causing clients needing refactor. It would be much better to first try and use operationId of SubClass2_methodName and only use counter as last resort.
