### ISSUE TITLE
swagger.json is not getting generated

### ISSUE THREAD

**Issue by anshu8792** [swagger-api/swagger-core#1943]
I have multiple addresses

```
<jaxrs:server id="OmsServices" address="/oms">
<jaxrs:server id="OmsExchangeServices" address="/exchange">
```

with multiple services it it.
context-root is abc-oms-service with port 7030

**web.xml**

```
<servlet>
        <display-name>OMS-Service</display-name>
        <servlet-name>OmsService</servlet-name>
        <servlet-class>org.apache.cxf.transport.servlet.CXFServlet</servlet-class>
        <!-- set the base path for the swagger application -->
        <init-param>
            <param-name>swagger.api.basepath</param-name>
            <param-value>http://localhost:7030/abc-oms-service</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>OmsService</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>

```

BeanConfig initialisation

```
<bean id="beanConfig" class="io.swagger.jaxrs.config.BeanConfig" >
        <property name="title" value="Swagger Sample App"/>
        <property name="version" value="1.0.0" />
        <property name="schemes" value="http" />
        <property name="host" value="localhost:8002" />
        <property name="basePath" value="/oms"/>
        <property name="resourcePackage" value="com.abc.oms.service"/>
        <property name="scan" value="true"/>
    </bean>
```

I am trying to hit http://localhost:7030/abc-oms-service/swagger.json
Its giving me 404.

My service api calls look like
http://localhost:7030/abc-oms-service/oms/order/getOrder/1
http://localhost:7030/abc-oms-service/exchange/getExchange/1

I have @Api notations on service class.
My BeanConfig is initialised for sure because I got one exception which I solved.
I am using cxf, spring framework, tomcat server 7

**Comment by webron** [comment]
You're potentially missing the two beans that are required to actually expose the swagger.json. Take a look at the following two bean declarations in the CXF sample:

https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs-cxf/src/main/resources/applicationContext.xml#L32

https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs-cxf/src/main/resources/applicationContext.xml#L17

**Comment by anshu8792** [comment]
Thanks for answering.

I had defined both the beans but did not include anywhere.

<bean id="apiListingResourceJSON"
class="io.swagger.jaxrs.listing.ApiListingResource"/>
<bean id="apiDeclarationProvider"
class="io.swagger.jaxrs.listing.SwaggerSerializers"/>

I have added them in serviceBeans and providers

<jaxrs:serviceBeans>
<ref bean="orderService" />
<ref bean="apiListingResourceJSON" />
</jaxrs:serviceBeans>

<jaxrs:providers>
<ref bean="jaxbProvider"/>
<ref bean="jsonProvider"/>
<ref bean="omsAuthenticationHandler"/>
<ref bean="apiDeclarationProvider" />
</jaxrs:providers>

But still giving me 404 while I execute command
curl -H "Authorization: Basic YTpi"  "
http://localhost:7030/abc-oms-service/swagger.json" -v

**Comment by webron** [comment]
Well, try to look at the sample and check for other differences. I ran it earlier today and it works as expected. It's difficult trying to reproduce this without more details.

**Comment by drewtul** [comment]
I've noticed upgrade from swagger 1.5.6 to 1.5.10 my JSON generation broke and it seems this commit https://github.com/swagger-api/swagger-core/commit/f8c69c89e6fee93076241e031f9ea98c375e725e#diff-5b72a0a48c0069409834b1cd6ce38282 changed compatibility with CXF and CXF no-longer sees ```ApiListingResource``` as valid for ```PATH/swagger.json``` , it seems to be checking for ```/swagger``` , which does not match the template regex ```/swagger\.(json|yaml)(/.*)?``` that is generated for ```ApiListingResource```.

This all occurs in the JAXRSUtils#selectResourceClass method

**Comment by fehguy** [comment]
Please read the [release notes](https://github.com/swagger-api/swagger-core/releases/tag/v1.5.7).  Most likely you're missing a JSON serializer or affected by [this change](https://github.com/swagger-api/swagger-core/releases/tag/v1.5.8)

**Comment by drewtul** [comment]
@fehguy Apologies, that is correct, I didn't see anything from that commit jumping to that being an intended breaking change.
