### ISSUE TITLE
Can somone please explain this to me

### ISSUE THREAD

**Issue by Tandolf** [swagger-api/swagger-core#1946]
Im sitting in an old WLS application running jersey 1.19. Trying to implement swagger, followed the tutorial using a beanConfig.

[https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup-1.5](Turorial)

initilizing with a web.xml and trying to get the resource from http://localhost:7001/member/v1/swagger.json

"member/v1" beeing the context root. My context root is correct because i can reach my endpoints at GET member/v1/user

looking at the examples at:
[https://github.com/swagger-api/swagger-samples/blob/master/java/java-jersey-jaxrs/src/main/java/io/swagger/sample/Bootstrap.java](https://github.com/swagger-api/swagger-samples/blob/master/java/java-jersey-jaxrs/src/main/java/io/swagger/sample/Bootstrap.java)

they are completly different from the tutorial.

swagger-core 1.5.10
swagger-jaxrs 1.5.10
swagger-jersey-jaxrs 1.5.10
swagger-models 1.5.10

what is the correct way to implement it, by the example, or by the tutorial?

**Comment by lemoncolly** [comment]
This is not the correct place for this kind of question.
I would post any questions in the swagger Google group.
https://groups.google.com/forum/#!forum/swagger-swaggersocket
