### ISSUE TITLE
operations in JSON not rendered as JSON array

### ISSUE THREAD

**Issue by rrjp** [swagger-api/swagger-core#195]
When I look at the PetStore sample JSON, operations are rendered as arrays. For example:

```
   "apis":[
      {
         "path":"/pet.{format}/{petId}",
         "description":"Operations about pets",
         "operations":[
            {
               "httpMethod":"GET",  ...
            }
         ]
```
when I look at what is being generated from my API, operations is not coming as an array but as an object in the JSON (http://localhost:8080/api/api-docs.json/api):

```
   "apis":[
      {
         "description":"Endpoint for api",
         "operations":{
            "httpMethod":"GET",
            "nickname":"getConfiguration",
            "responseClass":"ArrayResponse",
            "summary":"Returns the server configuration details."
         },
         "path":"/api/configuration"
      },
```

I'm using Jersey / Java and the basic outline of the code is like:

```
@Path("/")
@Api(value = "/api", description = "Endpoint for api")
@Produces({"application/json"})
public class api {
...
	@GET
	@Path("/configuration")	
	@ApiOperation(value = "Returns the server configuration details.", responseClass = "com.whatever.ArrayResponse")
	@Produces(MediaType.APPLICATION_JSON)
	public Response getConfiguration() {
		return new MyResponseBuilder(AdapterFactory.getConfiguration(), null).build();
	}
}
```

From what I've read here in the spec, the JSON being returned should always return operations as an array, even if it only contains one item. Seems like a bug, so raising it here.

I think this is what is causing the problems I'm having with swagger-ui.

**Comment by webron** [comment]
We're not really going to write migration docs for that anymore, so no longer an issue. However, there's #902 for the future.
