### ISSUE TITLE
Does it make sense to deprecate @ApiParam's "required" parameter?

### ISSUE THREAD

**Issue by coldserenity** [swagger-api/swagger-core#1950]
Correct me if I'm wrong but it seems that it's possible to identify if the parameter is required from @RequestBody and @RequestParam annotations (@PathParam is always required).

More over by default for @RequestBody and @RequestParam required=true
While for @ApiParam default is false which makes it somewhat inconsistent with REST specification.

Am I missing something?

https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#apiparam

**Comment by webron** [comment]
You're thinking about Springfox and Spring-MVC - Springfox uses our annotations, but the annotations serve this project as well which covers JAX-RS, and the behavior is different (in JAX-RS, for example, parameters are _not_ required by default).
