### ISSUE TITLE
Specifying the request.class type similar to request.class

### ISSUE THREAD

**Issue by lloyd31** [swagger-api/swagger-core#1953]
For the below function type, i cannot specify the class format for the input\request parameters as we can for the response types. I know the class format which the request parameter is represented and want to show the same in the API documentation, but actually i am using the InputStream as to read the data.
Expecting something similar to how "response = User.class" behaves

Explored @ApiParam, but no suitable option found.

@ApiOperation(value = "save a user", response = User.class)
@POST
 public Response saveUser(InputStream message){...}

**Comment by webron** [comment]
That's true, you cannot (and this is intentional).
You'd have to hide that parameter, and re-add it as an `@ApiImplicitParam`.

**Comment by lloyd31** [comment]
The schema type does not refer the dataType specified. it always points to be a string. Which is a bug i guess. Refereed the [issue](https://github.com/swagger-api/swagger-core/issues/1559) which points to the same behavior.

@POST
@ApiOperation(value = "save a user", response = User.class)
@ApiImplicitParams({
		@ApiImplicitParam(name="inputObj", value="Input param", dataType="MyObj")
	})
public Response saveUser( @ApiParam(hidden=true) InputStream message){...}

**Comment by fehguy** [comment]
as long as `MyObj` can be resolved, it'll be resolved and added correctly.
