### ISSUE TITLE
SpecFilter does not retain "deprecated":true properties of operations 

### ISSUE THREAD

**Issue by dastoikov** [swagger-api/swagger-core#1954]
Hi,

A deprecated operation marked as such in the original Swagger definition, will lose the deprecated flag when filtered through the SpecFilter.

I have a fix readily available.
Please let me know if you are interested in a PR.

Cheers,
Dimitar
P.S.
The fix contains a unit test I somehow missed to include in pull request #1949.

**Comment by fehguy** [comment]
Yes please

**Comment by dastoikov** [comment]
It should be PR #1955

**Comment by fehguy** [comment]
Thanks!  Merged.
