### ISSUE TITLE
Different @ApiResponse contain same response object class using JAX-RS server

### ISSUE THREAD

**Issue by ilaanzi** [swagger-api/swagger-core#1956]
I defined in Swagger Editor an API REST with this responses:

    responses:
        '200':
	  description: OK.
         schema:
         	$ref: '#/definitions/OK'
        '400':
          description: Validation Error.
          schema:
            $ref: '#/definitions/ValidationError'
        '404':
          description: Generic error.
          schema:
            $ref: '#/definitions/GenericError'

When i generated server in JAX-RS, Swagger created this code:

```java
@io.swagger.annotations.ApiResponses(value = { 
     
     @io.swagger.annotations.ApiResponse(code = 200, message = "OK.", response = OK.class),
       
     @io.swagger.annotations.ApiResponse(code = 400, message = "Validation Error.", response = OK.class),
        
     @io.swagger.annotations.ApiResponse(code = 404, message = "Generic Error.", response = OK.class })
```
Is this the correct way to implement it or is it a bug?

Any help is appreciated.

**Comment by webron** [comment]
No, the error responses are not mapped to the right classes. However, this is not an issue with swagger-core but with [swagger-codegen](https://github.com/swagger-api/swagger-codegen) so please open the ticket there.
