### ISSUE TITLE
Superclass annotation for method prevails in swagger

### ISSUE THREAD

**Issue by lloyd31** [swagger-api/swagger-core#1960]
I have the below code. The method getDetails is over-ridden in Class B and thus is not available as a web-service. But Swagger still documents it as a valid service. Any idea why does this happen and how to avoid this behavior in Class B?

Note: I cannot hide the operation in class A as this would be needed by other sub-classes.

Class A{

@Path("/details")
String getDetails(){....}
}

@Path("/path1")
Class B extends A{

@Override
String getDetails(){....}
}

**Comment by lloyd31** [comment]
Well using the @ApiOperation(hidden=true) with the Override method hides it in the documentation. But @Override disables the API-end-point. so as a suggestion, swagger should not skip such end-points.

**Comment by fehguy** [comment]
Please retest using the latest master.  I believe this has been fixed.
