### ISSUE TITLE
In the swagger demo, how the ids fields are removed when getting the example value  

### ISSUE THREAD

**Issue by christor54** [swagger-api/swagger-core#1963]
Hello,

On [Add Pet](http://petstore.swagger.io/#!/pet/addPet), when you click on the example value, you generate a json example without the ids fields on the body. 

I don't understand how to make this behavior, can you help ? 

Thanks.

**Comment by webron** [comment]
I can't dive into it right now, but https://github.com/swagger-api/swagger-samples/tree/master/java/java-jersey-jaxrs is the source of the demo, it may help you find the info.
