### ISSUE TITLE
Problem with Typescript client when parameter name is an array

### ISSUE THREAD

**Issue by GimpBoy** [swagger-api/swagger-core#1965]
My API uses a path parameter named Where[position] which is working when I create the javascript client but when I create the Typescript client it attempts to make a public function with where[position]? : number as a variable. Jetbrains doesn't like this. Also, when this typescript is converted to javascript it comes out as 
        if (where === void 0) { where = [position] ?  : number; }

Is there something I'm missing? Is there a better way to have the Where clause an array of key=>value pairs without giving it an explicit array name?

**Comment by fehguy** [comment]
I believe this should be opened on swagger-codegen.
