### ISSUE TITLE
JSON model property naming issues

### ISSUE THREAD

**Issue by xunnanxu** [swagger-api/swagger-core#1967]
Per swagger spec, the json property naming uses camel case: http://swagger.io/specification/

However there are cases where applications use snake case and it's normally done via changing the jackson json mapper like: `Json.mapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE)`. This way, all the model namings will be changed to `foo_bar` style without extra annotations. The corresponding util in swagger is `io.swagger.util.Json`.

However this would affect the swagger spec model as well:

e.g.
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/models/Swagger.java

`basePath` would thus become `base_path` and in turn break swagger-ui.

My proposal is to add `@JsonNaming` to those classes and thus override the global setting. Does this make sense?

**Comment by silas** [comment]
I got something basic working by adding a ModelConverter, probably doesn't work for a lot of people, but worked for me.

https://gist.github.com/silas/3b41e6ed4031c11f919767a74829ffea

Not proposing this as a solution, just leaving it here for other people trying to solve the same problem.

**Comment by fehguy** [comment]
It's too hard to add this as a general solution.

**Comment by xunnanxu** [comment]
@fehguy I'm sorry but what do you mean by "It's too hard to add this as a general solution."? What specifically are you talking about? What's the alternative solution if I want to output all models in snake case?

**Comment by WesternGun** [comment]
Check here: https://github.com/swagger-api/swagger-core/issues/826#issuecomment-461460771
