### ISSUE TITLE
Swagger documentation erroneously consumes application/json

### ISSUE THREAD

**Issue by richmeyer7** [swagger-api/swagger-core#1972]
When our code annotates a PATCH with @ApiOperation and sets consumes = "application/merge-patch+json", the Swagger 2.5.0 HTML documentation erroneously shows that the method consumes both "application/json" and "application/merge-patch+json". And worse, the erroneous "application/json" choice is the first and default one in the drop-down.

I traced the behavior in the debugger, and this is apparently caused by springfox.documentation.spring.web.scanners.MediaTypeReader being first in DocumentationPluginsManager's operationBuilderPlugins, and because the consumesList is empty at that time, its method apply(OperationContext) adds MediaType.APPLICATION_JSON_VALUE.

Later, SwaggerMediaTypeReader calls method springfox.documentation.swagger.readers.operation.SwaggerMediaTypes.apply(OperationContext), which adds "application/merge-patch+json" to the OperationBuilder's consumes Set, which already contains MediaTypeReader's erroneous first entry.

It seems that if the plugin SwaggerMediaTypeReader could be applied *before* plugin MediaTypeReader, then MediaTypeReader would not see an empty consumesList and thus would not add "application/json".

**Comment by webron** [comment]
This should be opened on.... [Springfox](https://github.com/springfox/springfox/).
