### ISSUE TITLE
RefProperty.TYPE is private

### ISSUE THREAD

**Issue by kolianbolo** [swagger-api/swagger-core#1973]
In swagger-core/modules/swagger-models/src/main/java/io/swagger/models/properties/RefProperty.java.

RefProperty.TYPE is private. In other Property classes .TYPE is public. May be it is typo missing ?

One more question - IntegerProperty.FORMAT, LongProperty.FORMAT is private. May be it replace to public too?

Sorry for my bad english

**Comment by fehguy** [comment]
Sure I see no reason why they are private.  Feel free to send a PR to make them public

**Comment by kolianbolo** [comment]
Thank you. I promise sending patch request today or tomorrow.

**Comment by fehguy** [comment]
I believe this was implemented.
