### ISSUE TITLE
How to define role/permission security in Swagger?

### ISSUE THREAD

**Issue by atdiff** [swagger-api/swagger-core#1974]
In my API documentation, I would like to define the security necessary for each API endpoint. The project has defined roles and permissions that determine which users can access the APIs. What is the best way in Swagger to document this information? Is there a best practice or recommendation on how to show this detail?

This what I tried out using securityDefinitions and a self-defined variable for the roles, but that information (x-role-names) didn't get copied over into the documentation when I ran it through swagger2markup or using swagger-ui.

```
    "securityDefinitions": {
    "baseUserSecurity": {
          "type": "basic",
          "x-role-names": "test"
       }
    }
```
What's the best way to document the role and permission information per endpoint?

**Comment by fehguy** [comment]
Please read here:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject

You create the necessary `securityDefinition`s then add a `security` object to either the top-level of the API or individually to each operation.

**Comment by atdiff** [comment]
@fehguy Is it possible using the basic security type or does it have to be oauth2?

**Comment by fehguy** [comment]
if you look at the supported types in the link I posted, you'll see basic auth, api key, oauth

**Comment by atdiff** [comment]
@fehguy  After looking over the specs, I'm still not sure how to accomplish the ability to display the user roles/permissions required for an API and have that info appear in the resulting Swagger documentation.  My ideal is for each path could indicate the user role and permissions required to access it.  Basically something very roughly along the lines of "api/someCall" roles: ["admin","specialist"] and permissions: ["view_screen", "edit_screen"].

There are 2 avenues I've tried at the moment:
- **Description field.**  Just listing the roles in the description field (not ideal and in some markup only gets displayed at the security section in the bottom)
```
"securityDefinitions": {
        "baseUserSecurity": {
          "type": "basic",
          "description": "Roles required: Admin",
        }
    },
```
Description rendered:
![image](https://cloud.githubusercontent.com/assets/16138266/19660908/3b8fec42-99f7-11e6-8f84-6deef98571da.png)


- **Scope.** Providing a scope for the security object.  It's not allowed in the spec and throws an error in the editor, but swagger2markup still allows and parses it.
`"security": [{"baseUserSecurity": ["Admin", "MarketSpecialist"]}],`

Scope rendered: 
![image](https://cloud.githubusercontent.com/assets/16138266/19660911/4151623c-99f7-11e6-9bd6-54d5723f69db.png)

Scope seems to fit better to some degree, but it goes against the spec which doesn't seem like a good idea overall.  So I'm not sure how this would best be documented.

**Comment by banuiliuta** [comment]
> @fehguy After looking over the specs, I'm still not sure how to accomplish the ability to display the user roles/permissions required for an API and have that info appear in the resulting Swagger documentation. My ideal is for each path could indicate the user role and permissions required to access it. Basically something very roughly along the lines of "api/someCall" roles: ["admin","specialist"] and permissions: ["view_screen", "edit_screen"].
> 
> There are 2 avenues I've tried at the moment:
> 
> * **Description field.**  Just listing the roles in the description field (not ideal and in some markup only gets displayed at the security section in the bottom)
> 
> ```
> "securityDefinitions": {
>         "baseUserSecurity": {
>           "type": "basic",
>           "description": "Roles required: Admin, Specialist",
>         }
>     },
> ```
> 
> Description rendered:
> ![image](https://cloud.githubusercontent.com/assets/16138266/19660908/3b8fec42-99f7-11e6-8f84-6deef98571da.png)
> 
> * **Scope.** Providing a scope for the security object.  It's not allowed in the spec and throws an error in the editor, but swagger2markup still allows and parses it.
>   `"security": [{"baseUserSecurity": ["Admin", "MarketSpecialist"]}],`
> 
> Scope rendered:
> ![image](https://cloud.githubusercontent.com/assets/16138266/19660911/4151623c-99f7-11e6-9bd6-54d5723f69db.png)
> 
> Scope seems to fit better to some degree, but it goes against the spec which doesn't seem like a good idea overall. So I'm not sure how this would best be documented.

Hi, in the and what was the solution?

**Comment by akongnwi02** [comment]
Hi. How did you go about this issue?

**Comment by daniel78uk** [comment]
Not sure if it's useful but I've created a plugin for this:
https://www.npmjs.com/package/express-swagger-rbac

**Comment by jholovacs** [comment]
I don't feel like this should be closed. Swashbuckle is nifty because it auto-documents our api endpoints... endpoint security is certainly something that should be documented, but it seems to be ignored everywhere.

**Comment by Mallikanand** [comment]
I don't see a way to do this in OPEN API Spec v3 .. 
Having this feature helps understand and document the APIs more precisely.
