### ISSUE TITLE
Non-String x-examples

### ISSUE THREAD

**Issue by gilbode** [swagger-api/swagger-core#1983]
We have some swagger documents that define x-examples fields as objects and not strings in body parameters.  Seems that the code merged to resolve #1500 adds specific handling for x-examples field and assumes the value is a string.  We cannot parse our swagger files (which are valid according to the spec since x-* values should be allowed to be any type).  They blow up with a deserialization error like below:

```
java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.swagger.models.parameters.BodyParameter["x-examples"]->java.util.LinkedHashMap["application/json"])
```

Would be useful to allow x-examples to be any type.

**Comment by fehguy** [comment]
Follow #1107
