### ISSUE TITLE
How to force a method parameter to have parameter type as formData rather than body ?

### ISSUE THREAD

**Issue by JaspreetKaur16** [swagger-api/swagger-core#1987]
Hello,

I have integrated swagger with my spring framework based application.
I have following two issues -
Issue 1. How to force method parameters with custom annotation to have parameter type as formData in json output via ../v2/api-docs

For example, there exists an API in my custom controller

public AttributeInfoList createAttributes(@WebSerializedParam("attributeinfolist") AttributeInfoList attributeInfoList){
.........
}

The problem is that Parameter Type for attributeInfoList is of type body in JSON output of request ../v2/api-docs
I expect parameterType to be formData as i will have a URL like 
....../service/admin/attributes?attributeinfolist=<attributeInfoList><attributeInfo><name>Is publish ready 3333</name></attributeInfo></attributeInfoList>

Issue 2. The REST request parameter name should be same as annotation value. 
Such that the parameter name should be attributeinfolist and not attributeInfoList(i.e. camelCase)

Thanks,
Jaspreet

**Comment by fehguy** [comment]
For your first question, there is an extension model in swagger-core to do your own processing.  See how https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-hibernate-validations works for example.

For issue #2, If you're using custom annotations, it's kinda impossible for swagger-core to do that.
