### ISSUE TITLE
APIs missing in the JSON output

### ISSUE THREAD

**Issue by JaspreetKaur16** [swagger-api/swagger-core#1988]
I have integrated swagger with my Spring Framework based application.
There are controllers where in I am using Spring annotations and some custom annotations.

When I execute the request http://jkaur2k12:61400/rest/v2/api-docs there is a JSON output, but few APIs are not documented in the JSON output. For instance the following API is missing from the JSON output. Can you please help me in figuring out the reason why some of the APIs are missing from the JSON output seeing the below sample...

@RequestMapping(method = RequestMethod.GET, value = "/{assetId}")
	@WebReturnType(value = "xmlView")
	public AssetInfo getAsset(@PathVariable("assetId") long assetId, @RequestParam(value = "majorversion", required = false) Long majorVersion,
			@RequestParam(value = "minorversion", required = false) Long minorVersion,
			@WebArrayParam("attributes") String[] attributes,
			@RequestParam(value = "includechildren", defaultValue = "false") boolean includeChildren,
			@RequestParam(value = "includeparents", defaultValue = "false") boolean includeParents,
			@WebArrayParam("relationtypes") String[] relationTypes,
			@RequestParam(value = "rendition", required = false) String renditionType,
			@RequestParam(value = "layout", required = false) Integer layoutNumber,
			@RequestParam(value = "page", required = false) Integer pageNumber, @RequestParam(value = "draft", required = false) boolean draft,
			HttpServletResponse httpResponse,
			@RequestParam(value = "contentDisposition", required = false) String contentDisposition)
			throws AssetNotFoundException, QppServiceException, StreamingException, IOException {............................

Thanks,
Jaspreet

**Comment by fehguy** [comment]
Please look at the samples [here](https://github.com/swagger-api/swagger-samples/tree/master/java) for getting started
