### ISSUE TITLE
HTTP Status 404 - /rest/swagger-resources/configuration/ui error on executing request http://host:61400/rest/swagger-ui.html

### ISSUE THREAD

**Issue by JaspreetKaur16** [swagger-api/swagger-core#1989]
Hello
I have integrated Swagger with my Spring Framework based application.

There exists a webapp with REST APIs exposed using the following servlet mapping -
	<servlet-mapping>
		<servlet-name>rest</servlet-name>
		<url-pattern>/service/*</url-pattern>
	</servlet-mapping>

Such that the URLs are of format like
localhost:61400/rest/service/admin/users/John

I have integrated with swagger in order to generate documentation for the the REST APIs.
But I have observed that with such a servlet mapping I get the error - HTTP Status 404 - /rest/swagger-resources/configuration/ui error on executing request http://host:61400/rest/swagger-ui.html

Can you please suggest a solution for this ?
I cannot afford to change my web apps servlet mapping as its a legacy pattern being followed, difficult to be changed. 

Thanks,
Jaspreet

**Comment by fehguy** [comment]
Please look at the samples [here](https://github.com/swagger-api/swagger-samples/tree/master/java) for getting started with configuration.
