### ISSUE TITLE
Swagger Annotations for v1.2 doesn't generate "info" in JSON

### ISSUE THREAD

**Issue by rishabgarg** [swagger-api/swagger-core#1992]
So there is no way we can generate info object with annotations for v1.2 although it is supported by v1.2 specification.

FYI, I am using Swagger-play2 1.3.12 for Play 2.3 framework.

Refer to this link: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#513-info-object

**Comment by fehguy** [comment]
With annotations?  No.  Please try to upgrade to the 1.5.x code for Swagger Support, we stopped development on the 1.3.x some time ago.
