### ISSUE TITLE
How to set ApiModelProperty optional for specific requests

### ISSUE THREAD

**Issue by LucasHCruz** [swagger-api/swagger-core#1993]
How can I set an attribute optional for specific requests?

Like:

**required**:

doPost()
```
{
    "key": 123,
    "data": "data" //required
}

```

**optional**:

doDelete()
```
{
    "key": 123,
    "data": "data" //optional
}

```

**Comment by fehguy** [comment]
The only way is to have two different models, one with required, one with optional.
