### ISSUE TITLE
Store swagger output in variable

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-core#1995]
How to store swagger output in variable? I want to do some manipulations on the output.

**Comment by fehguy** [comment]
Please look at this example which modifies the specification as a POJO dynamically.

https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-generator

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-generator/src/main/java/io/swagger/generator/DynamicSwaggerConfig.java
