### ISSUE TITLE
missing operation in swagger-ui

### ISSUE THREAD

**Issue by suryajena** [swagger-api/swagger-core#1996]
I have a spring boot application, And i have configured swagger with   following configuration
@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select()
				.apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any())
				.build();
	}

Now in my controller i have many end points , but intrestingly i see random behavior in swagger-ui, some endpoints are missing, 

Issue : out of below 3 endpoints , i see  only1 of them at once and restarting server shows changes behavior and i only see 1 of 3 endpoints.

1>
@RequestMapping(value = "/users/{userId}/addresses/{addressid}", method = RequestMethod.POST, params = "action=register")

2>
@RequestMapping(value = "/users/{userId}/addresses/{addressid}", method = RequestMethod.POST, params = "action=unregister")

3>
@RequestMapping(value = "/users/{userId}/addresses/{addressid}", method = RequestMethod.POST, params = "action=deactivateAddress")

**Comment by webron** [comment]
Please open the ticket on Springfox.
