### ISSUE TITLE
A bug of  Integration 1.5.X annotations in Wiki

### ISSUE THREAD

**Issue by yaobaobao** [swagger-api/swagger-core#2007]
![image](https://cloud.githubusercontent.com/assets/21192423/20426960/7d297424-adbc-11e6-864f-787a1810addc.png)
 
Maybe lack of `@` before ApiImplicitParam

**Comment by fehguy** [comment]
Yes that looks like a bug

**Comment by fehguy** [comment]
Updated the wiki
