### ISSUE TITLE
Possible to use $ref in security and securityDefinitions?

### ISSUE THREAD

**Issue by atdiff** [swagger-api/swagger-core#2010]
For large API structures, it makes sense to have API and definitions split out into multiple files for reuse and readability.  Both security and securityDefinitions seem like properties that would benefit from leveraging the use of $ref.  This way security info can be shared across multiple swagger files for one application.
Is it currently possible and are there examples of how to do it?  I've tried multiple ways of defining the structure and nothing seems to work/get validated.

**Comment by webron** [comment]
I'm afraid the spec itself doesn't support $ref's there. If you'd like to see this changed, please check out the tickets on [the spec](https://github.com/OAI/OpenAPI-Specification/).

**Comment by atdiff** [comment]
Thanks!
