### ISSUE TITLE
1.5.11 Release?

### ISSUE THREAD

**Issue by jplock** [swagger-api/swagger-core#2012]
Any idea when 1.5.11 will be released which fixes https://github.com/swagger-api/swagger-core/pull/1910 ?

**Comment by ganeshs** [comment]
I'm waiting for this as well. Any update on the next release?

**Comment by webron** [comment]
We don't have an ETA for the release, but you can use the SNAPSHOT in the meantime.

**Comment by jplock** [comment]
This release has been pending for quite some time.  There are downstream dependent libraries that I'd rather not deploy to Maven Central referencing snapshot builds of swagger-core (not even sure if that's possible).   Is there a list of open issues that you are waiting to address before the next release?  This is only a patch release we're talking about here, not a minor version bump.

**Comment by webron** [comment]
No, you shouldn't be able to push something to central that depends on a SNAPSHOT. There's at least one change we're looking to make before making the release. It's a small change, but requires extensive testing. If we can't get it done soon, I'll try to push a release.

**Comment by jplock** [comment]
Thank for the update

**Comment by jplock** [comment]
I see the Jackson upgrade landed.  Are there any other large changes currently blocking a release?

**Comment by fehguy** [comment]
I'm doing testing and should be releasing this weekend
