### ISSUE TITLE
PropertyBuilder.PropertyId.EXAMPLE value from ModelConverter is cleared if @ApiModelProperty us not set

### ISSUE THREAD

**Issue by lexa411** [swagger-api/swagger-core#2014]
Hello,
I trying to write ModelConverter-s  for specific types in my project without using any @ApiModelProperty annotations.
```
public class UTCDateTimeConverter implements ModelConverter {

    @Override
    public Property resolveProperty(Type type, ModelConverterContext context, Annotation[] annotations,
                                    Iterator<ModelConverter> chain) {
        final JavaType jType = Json.mapper().constructType(type);
        if (jType != null) {
            final Class<?> cls = jType.getRawClass();
            if (cls.equals(UTCDateTime.class)) {
                HashMap<PropertyBuilder.PropertyId, Object> map = new HashMap<>();
                map.put(PropertyBuilder.PropertyId.TYPE, "string");
                map.put(PropertyBuilder.PropertyId.EXAMPLE, "2020-01-01T00:00:00.00Z");
                return PropertyBuilder.build("string", "", map);
            } else {
                return chain.next().resolveProperty(type, context, annotations, chain);
            }
        } else {
            return null;
        }
    }

    @Override
    public Model resolve(Type type, ModelConverterContext context, Iterator<ModelConverter> chain) {
        return chain.next().resolve(type, context, chain);
    }
}

```
I want to receive good example of model in Swagger UI, but example "2020-01-01T00:00:00.00Z" isn't showed in example model. As I understand, in method io.swagger.jackson.ModelResolver#resolve#368 field example for Property object is overrided by value from @ApiModelProperty annotation, which is null. Can anybody explain this behavior or fix it, if it is wrong?

**Comment by fehguy** [comment]
It seems like you're trying to reproduce some behavior of swagger-core without using swagger-core.  If that's the case, I wouldn't open an issue here, but ask general questions in the google group.

**Comment by Hervian** [comment]
@lexa411 Did you find a solution to the missing example values?
