### ISSUE TITLE
Please consider using LinkedHashMap as a default Map implementation

### ISSUE THREAD

**Issue by constint** [swagger-api/swagger-core#2021]
Currently the maps default implementations are a mix of HashMap and LinkedHashMap, this is not consistent, especially considering the keys order.

I'm aware that json objects provide no expectation of order.
However, having a somewhat consistent order is not only esthetically pleasing but also practical to :
- write deterministic tests (HashMap spec does not preclude iteration order changes across java versions)
- version swagger definitions nicely (adding an entry to an HashMap can completely reshuffle the iteration order, which makes diffing a pain)

If there are no outstanding reasons to prefer the HashMap implementation, I would change the remaining HashMaps to LinkedHashMap.

**Comment by fehguy** [comment]
This has been added
