### ISSUE TITLE
Add support for semi required parameters

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-core#2024]
We have a dto
```
class AuthenticationDto {
    public String email;
    public String password;

    public String socialNetwork;
    public String accessToken;
}
```

And we have 2 ways to autheticate
```
POST /sessions
{"email": "user1@domain.com", "password":"12345678"}
```
```
POST /sessions
{"social_network": "facebok", "access_token":"qqqwwweeerrtt"}
```

At the moment all fields are optional, but this not reflect that, if email is provided then password is required. 
Proposal is to make password semi-required, this will indicate that is required in context, something like
```
AuthenticationDto {
    email (string, optional),
    password (string, semi-required{email}),
    social_network (string, optional),
    access_token (string, semi-required{social_network})
}

```
Or even better Swagger can show 2 models
```
AuthenticationDto {
    email (string),
    password (string)
}
```
```
AuthenticationDto {
    social_network (string),
    access_token (string)
}
```

**Comment by webron** [comment]
The spec itself doesn't allow interdependent requirements, so we can't really implement it. The next version of the spec should have some support for it, but until then it can't be done.

**Comment by raderio** [comment]
Where can I find information about interdependent requirements,?

**Comment by raderio** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/256
