### ISSUE TITLE
List<Map<String, Object>> body parameter produces Array[undefined] data type on Swagger UI

### ISSUE THREAD

**Issue by s101d1** [swagger-api/swagger-core#2026]
I have HTTP POST API method like this:

```
@POST
public Response postFoo(@NotNull List<Map<String, Object>> foos) {
    ...
}
```

On the generated swagger UI, the body Data Type is showing `Array[undefined]`.

I have tried adding `@ApiParam` to the `foos` param with `example` property set but the body data type is still showing `Array[undefined]`.

Is there a way to override the body's data type on the swagger UI?

**Comment by fehguy** [comment]
Please open this on swagger-ui
