### ISSUE TITLE
`additionalProperties: true` should be disallowed, flagged as a warning

### ISSUE THREAD

**Issue by tedepstein** [swagger-api/swagger-core#2030]
#174 has a somewhat broad-ranging discussion about various `allOf` and `additionalProperties` limitations that SwagEdit should be aware of, and should help with by adding validations and helpful messages.

One of these is simple, and should not get lost in the overall discussion, so I'm adding it here as a separate issue:

**`additionalProperties: true` and `false` are meaningless in Swagger 2.0, and should not be allowed.**

Note that this is allowed, according to the Swagger specification, and according to the standard JSON Schema for Swagger.  Ron Ratovsky [says here](https://github.com/swagger-api/swagger-core/issues/1437#issuecomment-226647555) that this was an oversight in the specification.  It wasn't supposed to have been supported.  But I think we have to go by the spec, not by after-the-fact comments. 

The reason for the warning is because it's totally ignored by the Swagger core libraries.  There's nothing downstream of the editor that will recognize a value of `true`.

**Comment by fehguy** [comment]
OK, but swagger-core models don't allow `additionalProperties: true`.  I think this would belong in the `swagger-parser`.

**Comment by fehguy** [comment]
Track https://github.com/swagger-api/swagger-parser/issues/366 for further updates on this.

**Comment by tedepstein** [comment]
@fehguy , sorry, I meant to post this issue in [SwagEdit](https://github.com/reprezen/swagedit).  But yes, it would be good for Swagger-Parser to disallow it.
