### ISSUE TITLE
unable to get download file

### ISSUE THREAD

**Issue by ssahni30** [swagger-api/swagger-core#2040]
```java
public void getLabel(@QueryParam("orderItemsId") String orderItemsId,HttpServletRequest httpServletRequest,HttpServletResponse response) {
        String dataDirectory = httpServletRequest.getSession().getServletContext().getRealPath("/WEB-INF/files/label.pdf");
        Path file = Paths.get(dataDirectory);
        if (Files.exists(file))
        {
            response.setContentType("application/pdf");
            response.addHeader("Content-Disposition", "attachment; filename=\"label.pdf\"");
            try
            {
                Files.copy(file, response.getOutputStream());
                response.getOutputStream().flush();
            }
            catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }`
```

i am using `@ApiResponses(value = {
            @ApiResponse(code = 200, message = "Perfect") })`

without content-Disposition header swagger is unable to sync output file and whereas is with this header is get a link in ResponseBody which also corrupts my file.

I am not sure what i am missing ?

**Comment by fehguy** [comment]
You're not declaring what the response will be.  You need to add a `@Produces` annotation like such:

```
@Produces("application/pdf")
```
to your method.  Also specify your response type:

```
@ApiResponses(value = { @ApiResponse(code = 200, message = "Perfect", response = byte.class) })
```

Right now, you're saying "nothing is returned", so swagger-ui doesn't know what to do.

**Comment by ssahni30** [comment]
`@RequestMapping(value = "/orders/labels", method = RequestMethod.GET, produces = MediaType.APPLICATION_OCTET_STREAM)`

I am already using octet_stream. just have added response = byte.class . Still i am receiving corrupted pdf file. Also tried `@Produces("application/pdf")` even this didn't worked. 

[application-pdf-labels-orderItemsId=ff-blob-http---localhost-8080-f1e0b4e0-7b63-439b-8eeb-1a281524bfa1.pdf](https://github.com/swagger-api/swagger-core/files/664160/application-pdf-labels-orderItemsId.ff-blob-http---localhost-8080-f1e0b4e0-7b63-439b-8eeb-1a281524bfa1.pdf)

![screen shot 2016-12-20 at 9 38 54 pm](https://cloud.githubusercontent.com/assets/16645148/21357845/cf8cd5e0-c6fc-11e6-8eb8-5b0dd10bf781.png)

**Comment by fehguy** [comment]
OK if you submit an issue again, please give all the details the first time.

Sounds to me like you need to open this on swagger-ui but to confirm, what version are you using?

**Comment by ssahni30** [comment]
I am using springfox-swagger2 - version 2.5.0 with springfox-swagger-ui - version 2.5.0.

**Comment by fehguy** [comment]
I think you'll have to open the issue in the springfox repo--it's not clear what version 2.5.0 maps to.  You can test using http://petstore.swagger.io and load your URL to see if the version is the issue.

**Comment by ssahni30** [comment]
it points to swagger-annotation version 1.5.9 and yes just tried using petstore.swagger.io

![screen shot 2016-12-20 at 11 15 24 pm](https://cloud.githubusercontent.com/assets/16645148/21361500/4a8eb184-c70a-11e6-9312-6c19ff7d0ec7.png)

**Comment by webron** [comment]
The question is about the swagger-ui version, not swagger-annotation.

**Comment by ssahni30** [comment]
Iissue persist if i populate my swagger.json in http://petstore.swagger.io (Not sure which version petsore link uses). Above screenshot was taken with petstore only.  Moreover springfox 2.5.0 uses swagger-ui version 2.2.6 (just confirmed)

PS - I have started shifting to swagger ui. I am also working to fix this issue

**Comment by ssahni30** [comment]
Any way around this ?
