### ISSUE TITLE
Issue with ModelResolver. Not producing the correct json representation for attributes annotated with XmlElementWrapper annotation

### ISSUE THREAD

**Issue by ritesh-garg** [swagger-api/swagger-core#2047]
Unless I am totally missing something, there is a bug in the model resolution logic in ModelResolver, JAXBAnnotationsHelper java files.

According to [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#xml-object); to represent an xml structure like below:

```
<animals>
    <animal>value</animal>
    <animal>value</animal>
    <animal>value</animal>
</animals>
```

for a java entity as:
```
{
.
.
        @XmlElementWrapper(name = "animals")
        @XmlElement(name = "animal")
        public List<String> animals;
.
.
 }
```

the following definition can be used:

```
{
   .
   .
      "animals":{
         "type":"array",
         "xml":{
            "wrapped":true
         },
         "items":{
            "type":"string"
            "xml":{
              "name":"animal"
            }
         }
      }
  .
  .
    }
```
    
However, the definition generated by Swagger is:

```
    {
      .
      .
      "animals":{
         "type":"array",
         "xml":{
            "name":"animal",
            "wrapped":true
         },
         "items":{
            "type":"string" 
         }
      }
      .
      .
    }
```

This definition is going to result in the following xml:

```
    <animal>
        <animal>value</animal>
        <animal>value</animal>
        <animal>value</animal>
    </animal>
```
 
Key points:

1.  Xml name for the wrapper element should be set to "animals"
2. Xml name for the items should be set to "animal" in order to generate the xml tag for the array elements as "animal"

I checked the code in the test class XMLInfoTest.java to cross-check this and it seems like the test is also expecting the element at wrong place. Please let me know if more details are needed.

**Comment by fehguy** [comment]
PR merged
