### ISSUE TITLE
access="x" on a property in a model doesn't get picked up by the SwaggerSpecFilter

### ISSUE THREAD

**Issue by lukecampbell999** [swagger-api/swagger-core#2067]
We we have a class with a property that looks like this :-

```java
public class MyLovelyClass {

@JsonView(Views.Internal.class)
@ApiModelProperty(required = false, readOnly = true, access = "private")
private String apiKey;

.....etc....

}
```
We use JsonView to hide this when the code is being generated, and we are also extending a SwaggerSpecFilter to allow us to hide certain methods. That works very well, and I'm happy enough with it.

However -- the access= *doesn't* work with properties of models, so far as I can see.

At the moment, when we use a SwaggerSpecFilter, the property access *always* comes back as null, therefore although it's marked as ignored in the view that we generate in the output when the call is made, in the spec itself, the field shows up.

The best we can do for right now is to use readOnly or a combination of required and readOnly, which isn't ideal.

I gather the fix was applied in v2.0 but not applied in 1.5, is this correct? 

Thanks in advance!

**Comment by lukecampbell999** [comment]
1.5.10 - it definitely doesn't work for me.

**Comment by lukecampbell999** [comment]
From our POM file

<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jaxrs</artifactId>
			<version>1.5.10</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.10</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.5.10</version>
		</dependency>

**Comment by lukecampbell999** [comment]
From our POM 

`<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jaxrs</artifactId>
			<version>1.5.10</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.10</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.5.10</version>
		</dependency>`

**Comment by fehguy** [comment]
Please retest with 1.5.12

**Comment by lukecampbell999** [comment]
Confirmed - this works with 1.5.12. Thanks for the help and advice!
