### ISSUE TITLE
Swagger-UI shows more information on the model window than the one that is being send

### ISSUE THREAD

**Issue by TorrentBeast** [swagger-api/swagger-core#2069]
Hello, i using swagger to produce documentation for my spring Rest API, i am using json MixIn and JsonView to choose which data my domain objects should send to the client.

Everything seems to work fine except for the model and example value showed by the swagger UI which shows all the information of my domain object instead of showing only the filtered information done my JsonView.

Image of the model and example value and the response body send by the server in the swagger UI
![modelandresponse](https://cloud.githubusercontent.com/assets/11476328/21547598/078bdcf0-cddf-11e6-8e4a-338a33d51cf8.PNG)

My controller method
![controllermethod](https://cloud.githubusercontent.com/assets/11476328/21547645/57b2ff2e-cddf-11e6-9638-027b59583080.PNG)

My MixIn class to filter domain information:
![mixin](https://cloud.githubusercontent.com/assets/11476328/21547690/86152842-cddf-11e6-8ad4-debc198103f4.PNG)

How can i manage the data showed in the model and example value window to show the same amount of information as my response body ?

Note: in the example i not showing the Order domain object.

My swagger version is 2.6.1

**Comment by webron** [comment]
You opened the ticket on the wrong project. It looks like you're using spring mvc, so I'm guessing you're using Springfox.
