### ISSUE TITLE
[Suggestion] New parameter on @ApiParam to specify parameter type

### ISSUE THREAD

**Issue by s101d1** [swagger-api/swagger-core#2070]
I have a GET action method like this in dropwizard framework:

```
  @Path("/{id}")
  @GET
  public Response getFoo(@ApiParam(value = "Foo Id", required = true) @PathParam("id") IntParam id) {
    ...
  }
```

IntParam is a dropwizard helper class that encapsulates the parameter type parser, so if user provides a value that can't be converted to integer for the id,  Bad Request (400) response will be returned.

The problem by using this IntParam class is swagger will generate the parameter type in swagger.json as a string rather than integer since IntParam class is not understandable by the swagger parser.

```
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "Foo Id",
          "required" : true,
          "type" : "string"
        } ],
```

I could change the type of id to int/Integer in the action method but I will lose the benefit of IntParam.

So my suggestion is to add new parameter for @ApiParam that let developer to set or override the parameter type, maybe something like `dataType` parameter in @ApiImplicitParam.

```
  @Path("/{id}")
  @GET
  public Response getFoo(@ApiParam(value = "Foo Id", required = true, dataType = "int") @PathParam("id") IntParam id) {
    ...
  }
```

**Comment by fehguy** [comment]
As of 1.5.12 you can specify `type` and `format` to override datatypes for support like this.

**Comment by s101d1** [comment]
I can't find `type` and `format` on the documentation of ApiParam: http://docs.swagger.io/swagger-core/current/apidocs/index.html?io/swagger/annotations/ApiParam.html

Is the documentation not updated yet?

**Comment by webron** [comment]
It's updated now.

**Comment by s101d1** [comment]
Thanks. The documentation needs to be improved, like the explanation of the `type` field should provide the list of possible values. When I tried the `type`, I have to guess what is the correct value for the integer parameter. I tried set it to `"Integer"` at first, it didn't work, then tried `"int"`, it didn't work too, then finally got the correct value which is `"integer"` (all lower case).

**Comment by webron** [comment]
PRs are welcome.
