### ISSUE TITLE
Support contract-first workflow, using the provided Swagger spec

### ISSUE THREAD

**Issue by tedepstein** [swagger-api/swagger-core#2075]
Our users have noticed a problem in the way their Java services, built from Swagger-codegen stubs as the starting point, provide Swagger-UI documentation at runtime.  We'd like to get some perspective from the community, and see if there are known solutions or relevant discussions we may have missed.

Our solution provides a contract-first workflow for Swagger YAML, with an editing environment, real-time views, mocking, testing, and code gen. 

Many of the Swagger-Codegen output templates take advantage of code-first Swagger integrations at runtime. The generated code includes annotations and project configurations (e.g. using swagger-core), so the running service dynamically generates Swagger and provides a Swagger-UI web page. 

But we don't think this is an ideal solution, for a couple of reasons: 

* It entails an unnecessary "round trip" from the Swagger spec to annotated code at design time, and from code back to Swagger at runtime. Information can get lost or mangled in this round trip. Some of our users have had difficulty getting a correct and complete Swagger-UI at runtime. 
* It invites developers to edit the API descriptions directly in the generated code.  This is expected for a code-first workflow. But with a contract-first workflow, we want _all_ edits to be made in the Swagger source spec, and the code re-generated from this. Ideally, development teams will treat the Swagger spec as part of the source code, and code generation as part of the automated build.

So we don't want dynamic generation of the Swagger spec from code. However, these runtime Swagger integrations also perform some important functions that we don't want to lose:

* They provide a web page with Swagger-UI pre-configured.
* They serve this web page through a designated URL, usually /docs.
* They also expose the dynamically assembled Swagger JSON and/or YAML through another URL.
* They dynamically configure the Base URL in the generated Swagger, so it points to the running service instance.  This is important, as it ensures that the "Try it out" sandbox feature works correctly, directing requests to the running instance, without any need for deployment-dependent pre-configuration of the Swagger spec.

Our users want to provide a Swagger-UI (or other documentation format) from their services. But they'd just like to use their original Swagger spec, not have it assembled dynamically at runtime.  It seems reasonable to think that this should be an option, but we don't see a straightforward way to do this with the available components.

In particular:

* Swagger-UI doesn't have a constructor param to override the base path for the "try it out" button; it uses the base path specified in the Swagger spec. If we want to dynamically set that to the base URL of the running service, we need to pre-process the Swagger spec before passing it into Swagger-UI.
* Swagger-core doesn't seem to have an option to serve the Swagger-UI page using a static, pre-defined Swagger spec. AFAICT, it always assembles the Swagger spec from reflection, and uses this as the input to Swagger-UI.
* Swagger-codegen doesn't seem to have any standard configuration options to serve a web page with Swagger-UI based on the original Swagger spec. The implementations are platform-specific, and AFAIK all of the Java stub generators rely on Swagger-core to serve the Swagger-UI page at runtime.

Of course our users can write their own code to serve a web page with Swagger-UI, configured to use their original Swagger spec, pre-processed to have the correct base URL.  It's not terribly challenging, but it's not trivial.  And everything in the Swagger component stack seems to be steering them towards dynamic Swagger.

This seems like a curious oversight.  Swagger has matured from a pure code-first solution to the industry standard OpenAPI description language, with robust support for contract-first workflows.  Are we missing something here?

We're experimenting with this, prototyping some possible solutions.  We may consider releasing an open source component that solves this problem for Java (or JVM) services.  But then we'd want to try to make Swagger-codegen (at least the Java stub generators) aware of this, and able to generate code that uses our component instead of Swagger-core. 

I don't know if the maintainers of those generators would want to make a change like this.  I'm sure they'd prefer it if Swagger-core and Swagger-UI had their own, native options to work with a pre-defined Swagger spec, and they could just re-tool their generators to support those options.

Thoughts?

**Comment by fehguy** [comment]
Hi @tedepstein, we have many implementations that do just what you're describing.  For example:

* [swagger-inflector](https://github.com/swagger-api/swagger-inflector) for Java services.
* [swagger-node](https://github.com/swagger-api/swagger-node) for Node services.
* [connexion](https://github.com/zalando/connexion) for Python (this is a 3rd party tool).

Have you seen those?  Is that different from what you're looking for?

**Comment by tedepstein** [comment]
Hi @fehguy.  If I understand correctly, swagger-inflector, swagger-node and (I assume) connexion dynamically interpret the Swagger spec at runtime to drive method dispatch, etc.  Which is cool.

But not everyone wants to use these, especially in the Java space. We have some users working with Jersey, some with Spring, etc., and they want to continue working with generated, idiomatic code for their framework of choice. 

They _also_ want their service to provide Swagger-UI through a `/docs` URL at runtime, with a "try it out" button that directs to the running API instance, and with other URLs to retrieve the Swagger spec in YAML or JSON form. So far so good, swagger-core accommodates these needs nicely.

But they _don't_ want, or need, their carefully crafted Swagger spec to be "encoded" as annotations in the generated source code, then "decoded" by reflecting over the code and re-constituting he Swagger spec at runtime.  This round trip is causing some issues, and steering developers away from Swagger contract-first, back towards code-first (making direct edits to generated code).

We're trying to start down a path that would require some changes to Swagger-Codegen (which we're happy to make, at least in the Java generator modules), but would also be easiest to do if there were direct support in Swagger-Core, which is why I started the conversation here.

**Comment by fehguy** [comment]
Got it.  So essentially still going down a code generation model, but divorcing the implementation from the specification.  It seems to me like that ends up still being a swagger-codegen project, but that upon generation, the code that creates the routes, etc is not annotated at all, and there is a static route to a _copy_ of the swagger definition.

Unless that's incorrect, I suggest this move to the codegen project, and that there are either new templates or new options for the existing templates to avoid writing the annotations and just expect that the swagger definition (and possibly the ui itself) are just static assets in the webapp.

**Comment by tedepstein** [comment]
> that ends up still being a swagger-codegen project, but that upon generation, the code that creates the routes, etc is not annotated at all, and there is a static route to a copy of the swagger definition.
...
> there are either new templates or new options for the existing templates to avoid writing the annotations and just expect that the swagger definition (and possibly the ui itself) are just static assets in the webapp.

Yes, that's the idea.  Happy to move this to Swagger-Codegen.  I think there are some tweaks to Swagger-UI and Swagger-Core that would make this cleaner, but I can open those as separate, lower-level issues.

My first priority was to make sure there wasn't already a strategy for this, being implemented or discussed somewhere.  It sounds like the answer is no, so I'll take that as a green light to open a broader discussion in Swagger-Codegen.  :-)

@fehguy, thanks for your input.
