### ISSUE TITLE
Unable to parse List<Object> into except json

### ISSUE THREAD

**Issue by yaobaobao** [swagger-api/swagger-core#2088]
```
@ApiModel
public class RegisterUsers {

    @ApiModelProperty(required = false)
    private List<UserInfo> users;

    public List<UserInfo> getUsers() {
        return users;
    }
}
```
```
 @ApiImplicitParam(name = "body",
                    required = true,
                    dataType = "org.xxx.xxx.RegisterUsers",
                    paramType = "body")
```

It produce json model like:
```
{
  "users": [
    {
      "username": "string",
      "password": "string"
    }
  ]
}
```
 But I want to show like:
```
[
  {
    "username": "string",
    "password": "string"
  }
]
```

**Comment by fehguy** [comment]
Then your model is incorrect.  You really want an object with `username` and `password`, not an array of them.  The model should be one username + password instance, and the body would be like this:

```
schema:
  type: array
  items:
    $ref: '#/definitions/User'
```

In java as an array:

https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs/src/main/java/io/swagger/sample/resource/UserResource.java#L48

and as a list:

https://github.com/swagger-api/swagger-samples/blob/master/java/java-jaxrs/src/main/java/io/swagger/sample/resource/UserResource.java#L59

**Comment by yaobaobao** [comment]
Thanks for your reply! But I don't have actual field, so I use @ApiImplicitParam to solve it. In the case, How do I do?
