### ISSUE TITLE
Class with duplicate JsonProperty values throws exception

### ISSUE THREAD

**Issue by banderberg** [swagger-api/swagger-core#2091]
I use a third party API that for whatever reason has two properties in the same class each of which has the same JsonProperty value, which is causing Swagger to fail.  Is there a way to override this in the Swagger config?

**Comment by fehguy** [comment]
Please submit a pull request with a failing test case so we can see what it's doing

**Comment by banderberg** [comment]
I meant to put this in the domaindrivendev Swashbuckle forum.
