### ISSUE TITLE
Definition Property with multiple types are ignored

### ISSUE THREAD

**Issue by mnahkies** [swagger-api/swagger-core#2097]
**The issue:**
Definitions with properties that can take multiple types are ignored by PropertyDeserializer

Languages such as typescript offer an easy way to declare properties of a union type. For example:
```
class Foo {
    bar: string | number;
}
```

In other languages that don't have this facility it is conceivable that a wrapper object of some description could be generated to allow expression. Eg: (very rough example)
```
class StringOrNumber {
    public String asString()
    public int asInt()
}

class Foo {
    StringOrNumber bar;
}
```

However, there is no opportunity to represent these properties when generating a swagger client in the swagger-codegen project, because the PropertyDeserializer#propertyFromNode method assumes that type will be a string not an array. This causes it to return null, ultimately resulting in the property being omitted from the swagger-parser output, and thus not accessible to the swagger-codegen project.

See: https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/util/PropertyDeserializer.java#L206

I encountered this issue whilst attempting to use the code gen for a private api that seems to express a lot of it's models properties as nullable by having a type of `["string", "null"]` or similar. My workaround is to pre-process the swagger json to replace such union types with the primary type, however this is losing information that could be useful to api consumers.

**From Specifications:**
http://swagger.io/specification/#schemaObject

> The following properties are taken directly from the JSON Schema definition and follow the same specifications:
> ...
> type

http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.21

> The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.

**Example JSON:**

```
    "definitions": {
        "MyEntity": {
            "type": "object",
            "properties": {
                "entity_id": {
                    "type": [
                        "string",
                        "number"
                    ]
                },
                "entity_name": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            }
        }
    }
```

**Comment by webron** [comment]
This is a common issue that's brought up, but it's actually a wording issue in the spec. The spec does not support multi-types - i.e. `type` must always be a single type and cannot be an array. We'll improve the wording in the next version of the spec, but we cannot add support to it in swagger-core and subsequent projects.
