### ISSUE TITLE
Swagger Response falsely auto-populate with 200

### ISSUE THREAD

**Issue by catspirit** [swagger-api/swagger-core#2101]
``` scala
  @ApiOperation(
    value = "Create new user record",
    notes = "",
    httpMethod = "POST",
    consumes = "application/json",
    produces = "application/json"
  )
  @ApiImplicitParams(Array(
    new ApiImplicitParam(
      name = "payload",
      value = "Json data for create new user",
      dataType = "User",
      required = true,
      paramType = "body"
    )
  ))
  @ApiResponse(code = 201, message = "Return created user", response = classOf[User])
  @ApiResponses(Array(
    new ApiResponse(code = 201, message = "Return created user", response = classOf[User]),
    new ApiResponse(code = 500, message = "Internal server error")
  ))
```

The generated response auto populated 200, which is not the expected response from the api.
Is there anyway we can disable the auto populate of 200 status? Thanks in ad!

```json
  "/user" : {
    "post" : {
      "tags" : [ " Jobs" ],
      "summary" : "Create new user record",
      "description" : "",
      "operationId" : "createuser",
      "consumes" : [ "application/json" ],
      "produces" : [ "application/json" ],
      "parameters" : [ {
        "in" : "body",
        "name" : "payload",
        "description" : "Json data for create new user",
        "required" : true,
        "schema" : {
          "$ref" : "#/definitions/user"
        }
      } ],
      "responses" : {
        "200" : {
          "description" : "successful operation",
          "schema" : {
            "$ref" : "#/definitions/Function1RequestContextFutureRouteResult"
          }
        },
        "201" : {
          "description" : "Return created user",
          "schema" : {
            "$ref" : "#/definitions/user"
          }
        },
        "500" : {
          "description" : "Internal server error"
        }
      }
    }
  }
```

I'm using scala and swagger-akka-http to generate the swagger json. 
After reached out to author,  he has mentioned that "swagger-akka-http is just a very thin wrapper.
The swagger annotations don't appear to have support for explicitly saying what the default response code is. The models are generated using the swagger-core and swagger-jaxrs jars"

Let me know if there is a way I can fix this. Thanks in ad!

Related Problem: https://github.com/swagger-akka-http/swagger-akka-http/issues/31

**Comment by webron** [comment]
It looks like swagger-akka-http is based on spray, which as far as I know is not a jax-rs implementation. I'm not really sure how it works, and whether it uses our jax-rs Reader or implements its own. Something in the annotations is off, because you specify the `httpMethod` which is not supported in jax-rs. The artifact of the generated 200 response doesn't seem to come from swagger-core, but from whatever Reader implementation is being used.

**Comment by catspirit** [comment]
@pjfanning has found the solution. @ApiOperation(code=201) 
This behavior is defined in ApiOperation instead of ApiResponse. 

Here's the correct configuration that would fix the problem.
```scala
  @ApiOperation(
    value = "Create new user record",
    notes = "",
    code = 201,
    httpMethod = "POST",
    consumes = "application/json",
    produces = "application/json"
  )
```

Thanks a lot and have a nice evening!
