### ISSUE TITLE
Incorrect swagger-core wiki content for ApiParam output

### ISSUE THREAD

**Issue by ahartoto** [swagger-api/swagger-core#2117]
The current wiki on `Annotations-1.5.X` says

> Here we have two parameters. The first, `username` which is a part of the path. The second is the body, in this case a User object. Note that both parameters have the `required` property set to `true`. For the @PathParam, this is redundant as it is mandatory by default and cannot be overridden.
> 
> The output would be:
> ```js
>  "parameters": [
>   {
>     "name": "username",
>     "in": "path",
>     "description": "name that need to be deleted",
>     "required": true,
>     "type": "string"
>   },
>   {
>     "in": "body",
>     "name": "body",
>     "description": "Updated user object",
>     "required": false,
>     "schema": {
>       "$ref": "#/definitions/User"
>     }
>   }
> ]
> ```

It should have been:

Here we have two parameters. The first, `username` which is a part of the path. The second is the body, in this case a User object. Note that both parameters have the `required` property set to `true`. For the @PathParam, this is redundant as it is mandatory by default and cannot be overridden.

The output would be:
```js
 "parameters": [
  {
    "name": "username",
    "in": "path",
    "description": "name that need to be deleted",
    "required": true,
    "type": "string"
  },
  {
    "in": "body",
    "name": "body",
    "description": "Updated user object",
    "required": true,
    "schema": {
      "$ref": "#/definitions/User"
    }
  }
]
```

**NOTE:** The value of `required` key for `user` parameter should have been `true`.

Here is the updated content:
https://github.com/ahartoto/swagger-core-wiki/commit/6ee69e818cba478f6ddc2bc678cada48a2ac6f5b

**Comment by webron** [comment]
Sharp eyes! Fixed, thanks!
