### ISSUE TITLE
No differentiation between inner class names

### ISSUE THREAD

**Issue by mhaefele** [swagger-api/swagger-core#2121]
We use a lot of static inner classes as a way of grouping together similar, but not identical dtos.
For example:

```
public class CustomerDto {
  public static class In {
    // fields for saving a new customer
  }
  public static class Out {
    // fields returned when querying a customer.
  }
}
```

```
  public class Address {
    public static class In {
      //...
    }

    public static class Out {
      //...
    }
  }

```

In this case, it looks like the swagger.json is including only one of the In classes (with the reference "#/definitions/In") and one of the Out classes.

This makes it fairly unusable since the apis using the other In/Out classes have the wrong model.

At the least, could the generation fail if it gets naming conflicts?  Right now it's just silently referencing the wrong model.

I'm using Jersey to generate the swagger.json if that helps/makes a difference.

Thanks.

**Comment by mhaefele** [comment]
Looks like the name is coming out of TypeNameResolver, which uses .getSimpleName().
Not sure how to make it use a different TypeNameResolver.

I can probably also use @ApiModel to override the generated names.

My biggest worry is that it's failing silently when there are name conflicts, so it's really easy for a dev to not realize they have to provide a specific name.

I'm assuming you'd have the same issue if you had classes with the same name in two different packages.

**Comment by PavelJ** [comment]
I have just encountered this behaviour and was really suprised because I would assume that this would be a serious issue. For example I have one User model and have multiple request and response classes for multiple operations with User - each containing only a subset of User's attributes. 

For example I have class CreateUserRequest (in one package) annotated with @JsonRootName(value = "user") and another class UpdateUsersStateRequest (may be even in the same package) again with annotation @JsonRootName(value = "user"). Swagger definition has only one of those definitions and ignoring others so basically most of the generated examples which I see in swagger UI are wrong.

I would assume that swagger would have different definition for each REST method, am I missing something? It is extremely important to be able to define same object with different attributes in different API methods.

**Comment by seanmmills** [comment]
I have a problem where two DTOs have the same name, but different package names.  As @mhaefele noted above, the TypeNameResolver uses Class.getSimpleName(), which makes resolution ambiguous and sometimes nondeterministic between swagger-core versions.  Using the @ApiModel has been our solution thus far, however it seems that simply changing the TypeNameResolver to use Class.getName() will solve both problems.

With this change, assuming the CustomerDTO above is in the ```test``` package, the definition names would resolve to:
```
test.CustomerDTO$In
test.CustomerDTO$Out
```

I've tested this change locally: 
```
smills@smills-mac:~/Development/src/swagger-core (master *)$ git diff
diff --git a/modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java b/modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java
index c1dfdd2f..adafffef 100644
--- a/modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java
+++ b/modules/swagger-core/src/main/java/io/swagger/jackson/TypeNameResolver.java
@@ -41,11 +41,11 @@ public class TypeNameResolver {
 
     protected String nameForClass(Class<?> cls, Set<Options> options) {
         if (options.contains(Options.SKIP_API_MODEL)) {
-            return cls.getSimpleName();
+            return cls.getName();
         }
         final ApiModel model = cls.getAnnotation(ApiModel.class);
         final String modelName = model == null ? null : StringUtils.trimToNull(model.value());
-        return modelName == null ? cls.getSimpleName() : modelName;
+        return modelName == null ? cls.getName() : modelName;
     }
 
     protected String nameForGenericType(JavaType type, Set<Options> options) {
smills@smills-mac:~/Development/src/swagger-core (master *)$ 
```
This change seems to work in my functional application testing, however I had to build with skipTests=true because this change breaks several unit tests.  An official PR would need to resolve the tests as well.  I can submit a PR if this is an approved change.

**Comment by masc3d** [comment]
confirming this issue. using `simpleName` in this context looks defective to me. `@ApiModel` can be applied as a workaround.

**Comment by arzath** [comment]
Can you provide example on @ApiModel workaround?
My current issue is the model comes from imported jar library, hence I cannot apply @ApiModel on the class name that needs to be changed.

**Comment by seanmmills** [comment]
@arzath, `@io.swagger.annotations.ApiModel` only supports TYPE targets so you won't be able to use it.

**Comment by arzath** [comment]
Thanks @seanmmills, do you know if any fix is on its way/projected in the future?

**Comment by p4ali** [comment]
There is one limitation for above PR based on the snakeyaml - the key length of a map cannot be longer than 128, so in the **definitions** map, if a schema name longer than 128, it will generate an invalid swagger.json. 

Can any snakeyaml maintainers shed any light?

**Comment by frantuma** [comment]
A solution for this issue has been implemented in #2797, check out [this comment](https://github.com/swagger-api/swagger-core/pull/2691#issuecomment-386611105) and related test case, to  be able to customize name resolving

**Comment by yashodhan1211** [comment]
https://github.com/swagger-api/swagger-core/issues/2121#issuecomment-285109628

I am aslo facing same issue like @PavelJ as mention in above link ,please do helpful to solve to this issue.
Thank you in advance. 
I am attaching files of block of code for reference,please refer it.
![UserDetails2](https://user-images.githubusercontent.com/54977431/64410939-bcf90e80-d0a9-11e9-93ad-603a5f053707.png)
![UserOperationResponse](https://user-images.githubusercontent.com/54977431/64410945-bec2d200-d0a9-11e9-809d-a83c2a68ac49.png)
![API](https://user-images.githubusercontent.com/54977431/64410986-d732ec80-d0a9-11e9-9a8b-b77122423834.png)
![SwaggerUI](https://user-images.githubusercontent.com/54977431/64411081-15c8a700-d0aa-11e9-9f8d-870463d116d9.png)

**Comment by sgc109** [comment]
This issue still exists in `org.springdoc:springdoc-openapi-ui:1.6.8`.

**Comment by youngminz** [comment]
This issue can be mitigated by setting the following configuration:

```kotlin
import com.fasterxml.jackson.databind.ObjectMapper
import io.swagger.v3.core.converter.ModelConverters
import io.swagger.v3.core.jackson.ModelResolver
import io.swagger.v3.core.jackson.TypeNameResolver
import org.springframework.context.annotation.Configuration
import javax.annotation.PostConstruct

@Configuration
class SwaggerConfiguration(private val objectMapper: ObjectMapper) {

    @PostConstruct
    fun initialize() {
        val innerClassAwareTypeNameResolver = object : TypeNameResolver() {
            override fun getNameOfClass(cls: Class<*>): String {
                return cls.name
                    .substringAfterLast(".")
                    .replace("$", "")
            }
        }

        ModelConverters
            .getInstance()
            .addConverter(ModelResolver(objectMapper, innerClassAwareTypeNameResolver))
    }
}

```

If you proceed with the above setting, you will be able to have the following schema name. So the names are no longer duplicates.
* `In` -> `CustomerDtoIn`
* `Out` -> `CustomerDtoOut`
* `In` -> `AddressIn`
* `Out` -> `AddressOut`

Tested on the Spring Boot 2.7.3, `org.springdoc:springdoc-openapi-ui:1.6.11`.

**Comment by ev43** [comment]
In my case, `springdoc.use-fqn: true` solved the problem.

**Comment by emouty** [comment]
For those who doesn't uses springdoc but swagger-maven-plugin, you can use a custom ModelResolver with custom Reader

```xml
<plugin>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-maven-plugin-jakarta</artifactId>
      <configuration>
          <readerClass>
              com.custom.CustomResourceReader
          </readerClass>
      </configuration>
    	....
 </plugin>
```

```java
public  class CustomResourceReader extends Reader {

    static {
        ModelConverters instance = ModelConverters.getInstance();
        instance.addConverter(new CustomModelResolver(Json.mapper()));
    }
}
```

```java 
public class CustomModelResolver extends ModelResolver {

    private static final TypeNameResolver typeNameResolver = TypeNameResolver.std;

    static {
        typeNameResolver.setUseFqn(true);
    }

```
