### ISSUE TITLE
Snake case support, without malforming fields like 'basePath'

### ISSUE THREAD

**Issue by adhesivee** [swagger-api/swagger-core#2131]
For my JAX-RS application I would like to convert camelCase properties to snake_case for swagger.json.
It is possible to configure this from a central point: `Json.mapper().setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);` 

This however will change things like `basePath` to `base_path`, this is not what I want. It looks like the only way to this properly is to add `@ApiModelProperty` for **every** property, which doesn't seem very flexible to me. 
How can I resolve this?

**Comment by fehguy** [comment]
You can write your own extension or model converter to do so.  We don't honor the json mapper naming strategy in core--it's probably doable but needs to be a community contribution.
