### ISSUE TITLE
Howto add resource description using 1.5 @Api annotation

### ISSUE THREAD

**Issue by dpr-rec** [swagger-api/swagger-core#2137]
I'm currently in the process of updating from 1.3 to 1.5. 

While most things are working now, I was unable to figure out how to set the description of a resource using the `@Api` annotation in 1.5. With 1.3 I was using 

```
@Api(value = "My Swagger Resource", description = "Meaningful stuff in here")
```

For 1.5 I modified this to

```
@Api(tags = { "My Swagger Resource" }, description = "Meaningful stuff in here")
```

But the description attribute is deprecated and obviously not used anymore. I already tried to find examples on how to set this using the `tags` but was unable to find any resources on this.

I assume adding a resource description is still possible in 1.5, but how?

**Comment by webron** [comment]
Take a look at https://github.com/swagger-api/swagger-samples/blob/master/java/java-jersey-jaxrs/src/main/java/io/swagger/sample/Bootstrap.java#L37-L47.

Alternatively, you can also use https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#swaggerdefinition.

**Comment by dpr-rec** [comment]
Ah, now I figured out how this is working. This would be the 1.5 equivalent of an 1.3 `@Api` annotation with description.

```
@Api(tags = { "My Swagger Resource" })
@SwaggerDefinition(tags = { @Tag(name = "My Swagger Resource", description = "Meaningful stuff in here") })
```

I think this definitively should be mentioned in the migration guide!

**Comment by Nileshsachin10** [comment]
On trying to use the @ApiAnnotation or anything related to @api annotation , i am being asked to create it . how do i do that could you help me with that ?

**Comment by umi523** [comment]
![capture](https://user-images.githubusercontent.com/26435903/47010465-6fee1000-d158-11e8-8408-4479876a4c97.PNG)
How to add in this can anyone help me ?
