### ISSUE TITLE
1.5.13 release

### ISSUE THREAD

**Issue by pjfanning** [swagger-api/swagger-core#2139]
Would it be possible to do a 1.5.13 release? I'd quite like to get a released version with https://github.com/swagger-api/swagger-core/pull/2068 in it.

**Comment by fehguy** [comment]
Hi, yes we can do so.

**Comment by fehguy** [comment]
https://github.com/swagger-api/swagger-core/pull/2145/commits/80ae5f6ab7c0e652b7374d3b578833bd16dae45e
