### ISSUE TITLE
swagger-jaxrs does not generate securityDefinitions while using BeanConfig in an Application class

### ISSUE THREAD

**Issue by H3npi** [swagger-api/swagger-core#2140]
Hello together,

i am developing an api with resteasy. For documentation i am using swagger.
Currently it is implemented via maven:

```
<dependency>
  <groupId>io.swagger</groupId>
  <artifactId>swagger-jaxrs</artifactId>
  <version>1.5.10</version>
</dependency>
```

and Beanconfig

  
```
BeanConfig beanConfig = new BeanConfig();

Swagger swagger = new Swagger();
swagger.securityDefinition("apiKey", new ApiKeyAuthDefinition("X-AUTH-TOKEN", In.HEADER));
beanConfig.setScan(true);
```

My Resource Endpoint is Annotated with:
```
@ApiOperation(
  value = "get a list of Persons",
  authorizations = {
    @Authorization(
      value="apiKey"
    )
  }
)
```

the generated swagger.json does not provide any securityDefinitions.

**Comment by fehguy** [comment]
That's because you're creating a Swagger object which is not a static or a singleton in your app.  Try using the `@SecurityDefinition` annotation.
