### ISSUE TITLE
@ApiImplicitParam class dataType only works with matching @RequestBody

### ISSUE THREAD

**Issue by charliepeep** [swagger-api/swagger-core#2149]
I am trying to create a model for a Request Body where I only need one parameter. What I’ve found is that the @ApiImplicitParam datatype shows as a string in the Swagger UI when the @ApiModel is not the same as the class specified in the @RequestBody. I have tried using the fully qualified name as well. It does however work if the @ApiModel specified in the datatype is for the same as the class in the @RequestBody. 

Is there perhaps a workaround for this?

**Comment by webron** [comment]
This is the wrong project. You're looking for [Springfox](https://github.com/springfox/springfox/).
