### ISSUE TITLE
Model with constructor annotated with @JsonCreator translates incorrectly in swagger spec

### ISSUE THREAD

**Issue by iyogi** [swagger-api/swagger-core#2169]
For immutable model classes (no setters), which are deserialised from json using @JsonCreator annotation on constructor, the translation goes wrong in following ways:

- The @JsonProperty annotating constructor parameter is ignored in favour of class property name
-  If I try to fix above issue my adding a redundant @JsonProperty on the class property (or on the getter method), the translated property in swagger spec incorrectly shows the property as readOnly. The plugin expects a setter method, but there aren't any. But that does not make the property readOnly - since the property is set in the constructor

It appears that the bug is in io.swagger.jackson.ModelResolver (in cohort with io.swagger.models.properties.AbstractProperty) sets the readOnly attribute to true. The readOnly attribute _always_ set to true when there is no setter in the model for that property. As explained above, absence of setter should not automatically make the property readOnly - since the property can be set in the constructor during deserialisation.

Example:

Exhibit 1: The Model 
(note class property "**name**" and json property "**Name**".
Valid incoming JSON: `{"Name": "X", "Age": 20}` )

    public final class User  {

    private final String name;
    private final int age;

    @JsonCreator
    public User(@JsonProperty(value = "Name", required = true) String name,
        @JsonProperty(value = "Age", required = true) int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }
    public int getAge() {
        return age;
    }

}`

Output 1: The generated swagger spec (with incorrect property name instead of Name. Also "**required**" attribute missing)

    User:
	type: "object"
	properties:
		name:
			type: "string"
		age:
			type: "integer"
        	        format: "int32"

Exhibit 2: The Model (added redundant @JsonProperty on getters)

    public final class User {

    private final String name;
    private final int age;

    @JsonCreator
    public User(@JsonProperty(value = "Name", required = true) String name,
        @JsonProperty(value = "Age", required = true) int age) {
        this.name = name;
        this.age = age;
    }

    @JsonProperty(value = "Name", required = true)
    public String getName() {
        return name;
    }

    @JsonProperty(value = "Age", required = true)
    public int getAge() {
        return age;
    }
    
}
`
Output 2: The generated swagger spec - correct property name but now incorrectly marked as readOnly

    User:
    type: "object"
    required:
    - "Age"
    - "Name"
    properties:
      Name:
        type: "string"
        readOnly: true
      Age:
        type: "integer"
        format: "int32"
        readOnly: true

**Comment by rtomsick** [comment]
There is at least a workaround.

Since `@JsonCreator` takes precedence over `@JsonSetter`, you can add dummy no-op setters and annotate them accordingly.  That will make swagger see the properties as mutable and act accordingly.

Dumb?  You bet.  But at least it's a way to avoid too much model damage while getting the API spec built correctly.

**Comment by sergeijakovlev** [comment]
This does seem to be broken in my case as well. The behavior I see currently using Jackson annotations:

1. private field, getter, no annotations - not read only (OK)
2. private field, getter, setter, no annotations - not read only (OK)
3. private field, getter, @JsonProperty on field - read only (in my opinion NOK)
4. private field, getter, @JsonProperty on field with access=READ_WRITE - read only (NOK)
5. private field, getter, @JsonProperty on field with access=READ_WRITE and @ApiModelProperty on field with readOnly=false - read only (very much NOK)
6. private field, getter, @ApiModelProperty on field with readOnly=false, constructor with @JsonCreator with an argument marked @JsonProperty with name="fieldName" and access=READ_WRITE - read only (NOK)

This makes it very inconvenient to  use immutable objects with Swagger Core.

Related issues:
https://github.com/kongchen/swagger-maven-plugin/issues/379
https://github.com/kongchen/swagger-maven-plugin/issues/458
https://github.com/swagger-api/swagger-core/issues/1161 (maybe)

**Comment by alexwei** [comment]
These properties should not be treated as read-only, as you can always instantiate a new instance of the object by passing modified properties to it. Please fix this.

@rtomsick The workaround doesn't seem to work when the constructor parameters are annotated with `@JsonProperty`.

**Comment by rtomsick** [comment]
It does for me...

Could it be dependent on the version of Jackson?  I've used it in production on a project built w/ Jackson 2.9.0 and it worked fine.

**Comment by rtomsick** [comment]
Addendum: I don't quite do the same thing that @iyogi is doing.

Instead, I'm doing `@JsonCreator` on the constructor (static or real) with `@JsonProperty` to name the constructor params, but then I'm simply doing `@JsonGetter` on the accessors, *not* `@JsonProperty` like in the original report.

I haven't tested to see if the workaround works if you're doing `@JsonProperty` on your existing getters, but I can imagine that it might not.  @alexwei : did you try using `@JsonGetter` instead of `@JsonProperty` on your accessors?

**Comment by rtomsick** [comment]
@frantuma 

Well `accessMode` certainly addresses the broken behavior of `readOnly`, but I'm not sure it's really a good solution for this.  After taking a look at the `accessMode` changes, I don't really see anything that would really fix the behavior in this bug report.

Sort of by definition, we have enough information to be able to infer that a property is read/write based on the presence of `@JsonCreator` and `@JsonProperty`.  If we have a property that's exposed in the spec *and* if there exists a `@JsonProperty` annotation with the same property name for a `@JsonCreator`, then the property's "access mode" is R/W.  It would seem to be pretty poor form to force developers to re-declare that intent when it would be trivial to infer.

Apologies if I'm misunderstanding the semantics of `accessMode`.

**Comment by frantuma** [comment]
@rtomsick 
I have referenced above comment as it is (also) related to the issue described here, providing a workaround possibly better than others suggested, but this ticket is kept open; as you pointed out it is not fully addressed by the change in recent PR, and a further code update is needed to support it and is planned. Of course PRs are more than welcome..

**Comment by frantuma** [comment]
logic updated and reworked, with readonly/writeonly support in #2695. Closing ticket, please reopen if you're still experiencing issues
