### ISSUE TITLE
Petstore no longer honouring explicit HTTPS scheme, and using HTTP instead?

### ISSUE THREAD

**Issue by alzadude** [swagger-api/swagger-core#2171]
A recent change to the Petstore seems to have broken the explicit HTTPS api call behaviour.

Steps to reproduce:
1. Go to http://petstore.swagger.io 
2. Enter swagger url for the api, using HTTPS (e.g. for one of our api calls, use `https://imin-platform-api.imin.co/v1/swagger.json`)
3. Specify scheme `HTTPS`
4. Enter required api parameters (e.g. for one of our api calls, use `GET` `/v1/search/sessions`)
5. Click `Execute`

Expected:
Petstore executes api call using HTTPS as specified.

Actual:
Petstore appears to execute api call using HTTP (which for our api, doesn't work unfortunately), and Swagger then shows `TypeError: NetworkError when attempting to fetch resource.`

Would someone be able to investigate this issue to determine why making the HTTPS scheme explicit isn't working, and why HTTP is being used instead?

Thanks :)

**Comment by webron** [comment]
This issue was moved to swagger-api/swagger-ui#2906
