### ISSUE TITLE
Can we add a new field to operation, to indicate whether it was implemented or not?

### ISSUE THREAD

**Issue by tminglei** [swagger-api/swagger-core#2174]
I just added `mock response` support to [binder-swagger-java](https://github.com/tminglei/binder-swagger-java), which will auto generate mock response w/ fake data for unimplemented operation.

To make it more convenient, I have a suggestion:
Can we add a new field to operation, with related ui support, to indicate whether an operation was implemented or not?

I noticed that Swagger Spec hasn't provided a mechanism for this. I'd like to listen to your thought.

Thanks,
Minglei Tu

**Comment by webron** [comment]
That's where extensions come in. It doesn't make sense for the spec itself to describe it.

**Comment by tminglei** [comment]
Yeah, you're right.
But can swagger ui do some support for this?

**Comment by webron** [comment]
The new swagger-ui is extensible. You can write plugins to do pretty much anything you want.

**Comment by tminglei** [comment]
Got it. Thanks!
