### ISSUE TITLE
Consider renaming v3 annotations

### ISSUE THREAD

**Issue by arthurdm** [swagger-api/swagger-core#2185]
Currently all the annotations in the v3 branch start with "OAS".   This was done to avoid having to fully quality conflicting annotation names, for example, between io.swagger.annotations.responses.Response and javax.ws.rs.core.Response.   

However, upon looking at the JAXRS and Spring annotations (which are the most likely ones to be used together with Swagger annotations), it seems that only Link and Response are conflicting.  

Other annotations such as Server and Schema may conflict with other frameworks, but the question is: how likely is that someone would specify Swagger's Server annotation in the same class as another framework's Server annotation/class?   If someone can provide concrete examples of common usage where this collision happens, I will be grateful.  

Assuming that this is not a common, one can easily fully qualify either of the colliding annotations, given it would be a rare occasion.  

I propose we change the packages to io.swagger.annotations.oas and remove the "OAS" prefix from the annotation names.

**Comment by fehguy** [comment]
@dilipkrish would love your input on this, and on the annotations for v3 as a whole...

**Comment by fehguy** [comment]
I really hate typing `OAS` in the names also.  Also, putting the version in the models (not that you were saying that) feels bad.

Adding `oas` in the package feels a little weird too.  @webron what do you think?

**Comment by webron** [comment]
I guess the only issue is with `@Response` and using a fully qualified name for that would make very ugly code because it'd be used commonly enough. Not a big fan of putting `oas` in the package as well. We can drop the `OAS` prefix and just keep that or `Swagger` or the old `Api` as a prefix for `@Response`.

**Comment by arthurdm** [comment]
@OpenApiResponse? =)

**Comment by dilipkrish** [comment]
Whats motivating the rename? I quite like the existing annoations.

**Comment by arthurdm** [comment]
They're functional, but it's redundant to have to type OAS for every annotation.   When you have a method with 5+ of them it becomes kindda awkward to see so many OAS.

**Comment by fehguy** [comment]
OK I suggest that we add the `oas` package separator and for the `@Response`, we can add `@ApiResponse` or something like that.  I agree that typing `OAS*` over and over is giving me a headache.

**Comment by arthurdm** [comment]
I agree with that suggestion.

**Comment by frantuma** [comment]
this has been changed according to comments above
