### ISSUE TITLE
JaxRs BaseApiListingResource broke compatibility for CXF, basePath can not be updated anymore

### ISSUE THREAD

**Issue by QuasiSoDo** [swagger-api/swagger-core#2197]
Swagger 1.5.13 broke compatibility to the newest CXF release. Reason being: the BaseApiListingResource no longer returns the Swagger object but directly converts it to JSON and returns it as a String.

With this change cxf can no longer modify fields like the basePath of the Swagger object, which in turn leaves the basePath empty for swagger.json.

What is the advised way of modifying the Swagger object in the new release now that the object itself is not returned anymore?

**Comment by webron** [comment]
Sounds like using the `ReaderListener.afterScan(...)` would be a better approach.

**Comment by QuasiSoDo** [comment]
just stumbled back on this issue, afaik this was fixed on the  CXF side. I'll close the issue
