### ISSUE TITLE
how to set response business exception code

### ISSUE THREAD

**Issue by silvermoonhy** [swagger-api/swagger-core#2200]
now, i use swagger 2.x .
i want to set controller's response code,but i just can set code with httpstatus code.
if i set the response code with a business exception code,the project can't be Compiled.
this is my code

`	@ApiOperation(notes = "reserve",value = "Reserve")
	@RequestMapping(value = "/booking",method = {RequestMethod.POST})
	@ResponseBody
	@ApiResponses(value={@ApiResponse(code = 8025, message = "success"), 
			@ApiResponse(code = 8026, message = "aaaaaa"), 
			@ApiResponse(code = 8027, message = "bbbbbb")})
	public BaseResponse booking(@ApiParam("reserve info")@RequestBody BookingReq req)`

**Comment by webron** [comment]
This is not an issue. You're describing a REST API, so HTTP codes are the codes that are being used. If you'd like to describe internal error codes, do that either as the response you're returning, or as part of the description of the error itself.
