### ISSUE TITLE
how to use @Example。Why I use @Example no effect

### ISSUE THREAD

**Issue by rim-wood** [swagger-api/swagger-core#2203]
![_20170512160802](https://cloud.githubusercontent.com/assets/13330165/25989811/26cb28f4-3730-11e7-9e32-9c0926fecc23.png)

i copy this code in https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/test/java/io/swagger/resources/ClassWithExamplePost.java
but no effect

![_20170512160835](https://cloud.githubusercontent.com/assets/13330165/25989814/293dda28-3730-11e7-83ea-726d334be9c7.png)

**Comment by webron** [comment]
@rim-wood can you share the swagger.json you're getting?

**Comment by rim-wood** [comment]
@webron 
![Uploading 微信截图_20170518092006.png…]()
this is part of my swagger.json

**Comment by rim-wood** [comment]
@webron 
this is part of my swagger.json

>  "/surviveevent/external/info": {
            "post": {
                "tags": [
                    "surviveevent"
                ],
                "summary": "test",
                "description": "",
                "operationId": "postTest",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "test",
                        "description": "test",
                        "required": false,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "x-examples": {
                            "application/json": "[\"a\",\"b\"]"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            }
        },

**Comment by webron** [comment]
Right. The current version of swagger-ui doesn't support the `x-example/s` extensions.  It should work if you provide the example through the model itself.

**Comment by rim-wood** [comment]
@webron 
yes,if i provide the example through the model,this is work.
but you know,
The add and modified is different，add method may be need more param.
if i use `@ApiModelProperty` , That means add and modified show the some param in swagger-ui.
for example，
the model hava 4 param in add method,and is required in addition to `facilityCode`.
![_20170519092541](https://cloud.githubusercontent.com/assets/13330165/26229611/b306476e-3c75-11e7-99eb-335267f58ca4.png)
![_20170519095322](https://cloud.githubusercontent.com/assets/13330165/26230105/0e26c3dc-3c79-11e7-80bd-d4ad9b90fa60.png)
but in edit method, `facilityCode` is required,the other is not.
![_20170519094042](https://cloud.githubusercontent.com/assets/13330165/26229871/4e1af9ba-3c77-11e7-9003-d29484fc699c.png)
![_20170519094331](https://cloud.githubusercontent.com/assets/13330165/26229912/ad870c72-3c77-11e7-9f90-574e29d9f173.png)
I do not know whether you understand what I mean，if you hava solution，please tell me

**Comment by webron** [comment]
Yeah, I understand. However, when it comes to Swagger, there's no simple solution to it because of how JSON Schema works. Effectively you'd need to create two different classes where in one the field is required and in the other it is not. Those classes can of course inherit from each other.

**Comment by rim-wood** [comment]
@webron  ok，i see， thank you very much

**Comment by TopDstar** [comment]
@webron I meet the same issue. I don't want to show the model schema because of to large. I try to use @example annotation but not work.
swagger-jersey2-jaxrs:1.5.16
swaggerUI:3.3.2
swagger.json generated by annotation:
<img width="687" alt="wx20171024-134902 2x" src="https://user-images.githubusercontent.com/12229551/31926594-20a6e6b6-b8c2-11e7-8240-2d78ad81a647.png">
code:
`public Response registerApp(@HeaderParam("X-Auth-Token")String token, @PathParam("registeredSystem") RegisteredSystem registeredSystem,
                                 @ApiParam(value = "request",
                                        examples = @Example(value = {
                                                @ExampleProperty(mediaType="application/json", value="[\"a\",\"b\"]")
                                        })) ApplicationRegistrationCreateRequest request) {...}`

**Comment by liqiaolin520** [comment]
请问下有什么解决方案没有

Would you please tell me what the solution under no
