### ISSUE TITLE
JAX-RS2 Reader for OAS 3.0

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#2208]
Working off of https://github.com/swagger-api/swagger-core/tree/feature/3.0.0-rc1.

Create a [Reader](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java) class to scan the annotations and build the spec model tree. 

Scanning should depend on JAX-RS2 annotations and our own. If there's a conflict between our annotations and JAX-RS's, our annotations take precedence. 

There's no need to handle class modeling for now, only the operations, parameters, security, responses and so on.

**Comment by frantuma** [comment]
implemented (currently in https://github.com/swagger-api/swagger-core/tree/2.0)
