### ISSUE TITLE
Concurrentmodification exception in ModelResolver.java

### ISSUE THREAD

**Issue by iyerkm** [swagger-api/swagger-core#2217]
Hi
I get a concurrentmodification exception when executing beanconfig.setscan(true). I traced it back to a code snippet in ModelResolver.java
Line 863-869
//remove shared properties defined in the parent
Line 868 : subTypeProps.remove(entry.getKey())

With this swagger ui does not scan API resource class and getting error "no operation defined in spec"

**Comment by pjfanning** [comment]
@iyerkm code you provide a unit test that demonstrates the issue?

I suspect we need to check that subtypeProps and baseProps are not the same object instance.

```
                if (baseProps != null && subtypeProps != null && subtypeProps != baseProps) {
                    for (Map.Entry<String, Property> entry : baseProps.entrySet()) {
                        if (entry.getValue().equals(subtypeProps.get(entry.getKey()))) {
                            subtypeProps.remove(entry.getKey());
                        }
                    }
                }
```

**Comment by iyerkm** [comment]
I got this issue resolved. It was something to do with configuring REST security correctly.
