### ISSUE TITLE
Prevent Some Generic Java Class From Being Expanded

### ISSUE THREAD

**Issue by sagar-suri** [swagger-api/swagger-core#2218]
Hi Guys,

I am having a problem related to ModelConverters. My /swagger.json contains a generic class in the expanded form like below:

"JsonNode": {
"type": "object",
"properties": {
"floatingPointNumber": {
"type": "boolean",
"default": false
},
"valueNode": {
"type": "boolean",
"default": false
},
"bigInteger": {
"type": "boolean",
"default": false
},
"textual": {
"type": "boolean",
"default": false
},
"boolean": {
"type": "boolean",
"default": false
},
"containerNode": {
"type": "boolean",
"default": false
},
"missingNode": {
"type": "boolean",
"default": false
},
"object": {
"type": "boolean",
"default": false
},
"pojo": {
"type": "boolean",
"default": false
},
"number": {
"type": "boolean",
"default": false
},
"integralNumber": {
"type": "boolean",
"default": false
},
"short": {
"type": "boolean",
"default": false
},
"int": {
"type": "boolean",
"default": false
},
"long": {
"type": "boolean",
"default": false
},
"double": {
"type": "boolean",
"default": false
},
"bigDecimal": {
"type": "boolean",
"default": false
},
"float": {
"type": "boolean",
"default": false
},
"nodeType": {
"type": "string",
"enum": [
"ARRAY",
"BINARY",
"BOOLEAN",
"MISSING",
"NULL",
"NUMBER",
"OBJECT",
"POJO",
"STRING"
]
},
"binary": {
"type": "boolean",
"default": false
},
"array": {
"type": "boolean",
"default": false
},
"null": {
"type": "boolean",
"default": false
}
}
}

Now this is definitely what I don't want. In fact what I want is to prevent this specific class (com.fasterxml.jackson.databind.JsonNode) (and any other of my choice) to be ever expanded. So in order to do this I used the inbuilt function provided in the io.swagger.converter.ModelConverters class shown below:

public void addClassToSkip(String cls) {
LOGGER.warn("skipping class " + cls);
this.skippedClasses.add(cls);
}

Now having done this I can't seem to figure out where to actually inject the ModelConverters class, as I tried to add it to list of providers along with others but to no result. Can someone please help me with this. I have been looking for the answer for almost 3 days now.

I am using CXF with Swagger.

**Comment by sagar-suri** [comment]
@fehguy @webron 
Guys this is not a singular issue, there is another issue with this class as well: 
https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html. 
See the screenshots below.
(https://cloud.githubusercontent.com/assets/19852816/26483708/ffe3a982-420b-11e7-93e3-8f1589b36f89.jpg).
These generic classes shouldn't be drilled down or expanded at all. Need input from you.

**Comment by dantran** [comment]
with latest swagger-core, ZoneDateTime generated definition now becomes  string type, and 'date-time' format

**Comment by sagar-suri** [comment]
Thanks @dantran, which version would that be as I am already on 1.5.8. Also would you know anything about handling the JsonNode Class in any way ?

**Comment by dantran** [comment]
swagger-core 1.5.9 has it.  I have no idea about JsonNode

**Comment by fehguy** [comment]
Hi, there are two ways to add custom handling for a class.

First, you can create a custom model converter, where you can return a special schema for a specific class.  See here for an example:

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/ModelConverterTest.java#L184
```
ModelConverters.getInstance().addConverter(asMapConverter);
```

Next, if you want to _skip_ a class (which is what you were originally asking), you can do this:

```
ModelConverters.getInstance().addClassToSkip(JsonNode.class);
```

However, if you skip the class, you may not have a reasonable output in your definition.  Thus, it's best to look at your API to see _why_ you're returning `JsonNode.class` and consider returning something appropriate for that case.
