### ISSUE TITLE
NPE at io.swagger.jackson.ModelResolver.handleUnwrapped() - swagger-core 1.5.11+

### ISSUE THREAD

**Issue by dantran** [swagger-api/swagger-core#2222]
swagger-core 1.5.11 introduces handling for @JsonUnwrapped which also throws NPE for the following scenarios

1. When @ApiOperation and @ApiReponse's  response field is  generic class with @JsonUnwrapped field, such as Spring Hateoas's Resource.class .  The following sample sets innerModel to null

    @path("/{id}")
    @ApiOperation(value = "Get ClusterStatus by id", httpMethod = "POST", produces = "application/json", response = Resource.class)
    @ApiResponses(value = { @ApiOperation(code = 201") })
    public void create(@PathVariable String id) {
        
    }

2. When @ApiOperation and @ApiReponse has no 'response' field and the implementation returns a Resource<SomeClass>.  innerModel is set to null

    @Path("/{id}")
    @ApiOperation(value = "Get ClusterStatus by id", httpMethod = "POST", produces = "application/json")
    @ApiResponses(value = { @ApiResponses(code = 201) })
    public Resource<Pojo> create(@PathVariable  String id) {
        return null;
    }

3. When the model has no property ( ie empty class) which should ever happen
innerModel.getProperties() is empty, but InnerModel.getProperties().values() is null

Initial discussion is at https://groups.google.com/forum/#!topic/swagger-swaggersocket/Ax2mb2cKdvw

relate to #2214

**Comment by jochenhebbrecht** [comment]
I created a pull request for this problem: https://github.com/swagger-api/swagger-core/pull/2346

**Comment by dlandis** [comment]
Is there any workaround for this issue?

**Comment by dantran** [comment]
for my case, replace generic class with String class   ( one size fix all)

**Comment by frantuma** [comment]
closing as merged #2346

**Comment by jochenhebbrecht** [comment]
Thanks, it works :-)
