### ISSUE TITLE
does swagger 2.0 allow endpoint positioning?

### ISSUE THREAD

**Issue by jb08** [swagger-api/swagger-core#2225]
I've seen references to positioning, such in this [issue](https://github.com/swagger-api/swagger-core/issues/1050), but found no references to it in the [swagger specification](http://swagger.io/specification/)

**Comment by webron** [comment]
There's no ordering of operations in the spec. Any display ordering can/should be handled by the rendering tools.

**Comment by Wattos** [comment]
This seems like a bug in the spec. Rendering tools do not have the sufficient information to render the items in the right order. How would a tool know what order makes logically sense?

Now it just looks random which does not make sense:

![selection_999 137](https://user-images.githubusercontent.com/724759/29114043-41ef2dc0-7cf3-11e7-857c-b8652f7eb957.png)
