### ISSUE TITLE
Expose metadata about the promised SLA for services

### ISSUE THREAD

**Issue by petemounce** [swagger-api/swagger-core#223]
We tend to write an API contract that indicates to callers the SLA of the service.

For example `GET /menus/{restaurant}/morning` will
- respond within 50ms 90% of the time
- respond within 250ms 99% of the time
- limit individual callers to 100 requests per second

It would be great to add something like that to the specification.

**Comment by araghavaram** [comment]
hi, can someone help me in defining SLA for the REST operations in the swagger documents that we created. I am trying to open the links mentioned in this page but nothing opens. We are using swagger 2.0. Could you please help me defining this
