### ISSUE TITLE
Link Object has a Server Object in the Spec but not in the model - has a LinkParameter Object that has been replaced in the Spec by a String map

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-core#2235]
@fehguy 

Link Object has a Server Object in the Spec but not in the model - has a LinkParameter Object that has been replaced in the Spec by a String Map

Spec: https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#link-object

Model: https://github.com/swagger-api/swagger-core/blob/feature/3.0.0-rc1/modules/swagger-models/src/main/java/io/swagger/oas/models/links/Link.java#L35
Link Parameter Object and no Server Object

**Comment by fehguy** [comment]
This should be fixed by #2236
