### ISSUE TITLE
No discriminator Object, or method in the schema object

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-core#2238]
Spec: https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#discriminator-object
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#schema-object
@fehguy

**Comment by gracekarina** [comment]
I found the discriminator object only in the AllOfShema, should it be only there or also in the OneOfSchema and AnyOfSchema? @fehguy

**Comment by frantuma** [comment]
closing as not relevant anymore
