### ISSUE TITLE
Tag Object description not respecting multi-line literals in swagger-editor

### ISSUE THREAD

**Issue by derekdecesare** [swagger-api/swagger-core#2240]
We cannot incorporate line breaks into the description field for tags.  All other description fields respect markdown and multi-line literals.  This is really hampering readability of our tags for the APIs.

Example:

tags:
  - name: item
    description: | 
      To Do - Create a tag for each resource in your api and tag the operations that relate to that resource. 
      Provide the documentation for the resource in the description of the tag.  
      The following views are supported by this resource. 
      - complete, includes all fields.
      - summary, includes only id, descriptor, name and description. 
      - otherView, includes only id, primaryCategory and secondaryCategories.
  - name: comment
    description: To Do - Create a tag for each subresource. In this example, each item has a subresource that is a collection of comments.

**Comment by fehguy** [comment]
Could you please open this issue in the swagger-editor project unless it's an issue with swagger-core?  And if it's swagger-core, please share more details.

**Comment by derekdecesare** [comment]
https://github.com/swagger-api/swagger-editor/issues/1356
