### ISSUE TITLE
No Reference Class 3.0

### ISSUE THREAD

**Issue by gracekarina** [swagger-api/swagger-core#2245]
@fehguy  
Some Objects can be interchangeables with a Reference Object, when trying to do that, I can´t find a Class that support that Reference.

**Comment by arturdzm** [comment]
I was just going to open same issue.
I have though maybe appropriate models can be extended from ReferenceObject that contains $ref attribute. This will allow using same model classes to represent Reference Object and appropriate model. So either we populate $ref or we populate actually model fields if it is inline.
