### ISSUE TITLE
Array fields inside annotations should have empty array as their default value

### ISSUE THREAD

**Issue by navidsh** [swagger-api/swagger-core#2272]
Default value of array fields such as `servers` in `@Operation` are arrays with empty objects which is a bit confusing. An empty array `{}` might be a better default value. 

@Operation: `Server[] servers() default @Server();`

Also fields like `io.swagger.oas.annotations.Operation.externalDocs` also don't need to have a default value.

**Comment by frantuma** [comment]
implemented in #2394
