### ISSUE TITLE
Update jackson-version to 2.8.9

### ISSUE THREAD

**Issue by msymons** [swagger-api/swagger-core#2274]
swagger-core currently (v1.5.15) uses jackson-databind v2.8.7.  Update this by incrementing jackson-version to 2.8.9.

Addresses Jackson Deserializer security vulnerability:

FasterXML/jackson-databind#1599
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.9

**Comment by melloware** [comment]
Looks like FasterXML has more CVE Security issues:

https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-34008/Fasterxml-Jackson.html

https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

Even affects the latest version 2.9.8 available by internet.

**Comment by frantuma** [comment]
obsolete
