### ISSUE TITLE
implementation of AnyOf, OneOf, AllOf, (Not) support (models + core)

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-core#2277]
ticket is about implementing 3.0 `AnyOf`, `OneOf`, `AllOf` and `Not` Json schema field in `swagger-model`s and `swagger-core` modules, in terms of deserialization and resolving, and related impact on annotations, swagger-jaxrs2 and swagger-parser.

This would make use of the 3,0 `@Schema` annotation, which replaces `@ApiModel` and its parent/child/subtypes field; the swagger-core library should also read Jackson annotations (as done in 2.0) such as  `@JsonTypeInfo` and `@JsonSubtypes` to reconstruct the allOfSchema.

A possible open question is is related to the case where we have e.g both `allOf` and `anyOf` annotation for same class (or `allOf` and `anyOf` JSON schema properties defined for same schema object); currently in swagger-models we have `AllOfSchema` and `AnyOfSchema`, but not a kind of "ComposedSchema" (or e.g. extended `ObjectSchema`) with both `allOf` and `anyOf` properties (and/or `oneOf`)

An initial list of implementation tasks would include:

- implement any missing model annotations if needed    
- implement/update missing model schemas (e.g. ComposedSchema or ObjectSchema)
- implement deserialization of oneOf, anyOf, allOf, Not
- (implement in case SwaggerAnnotationIntrospector)
- implement resolving @Schema annotations in model resolution  
- implement resolving @Json.. annotations in model resolution  
- implement resolving any interface declared as anyOf

- check impact on jaxrs project
- check impact on parser 
- related tests  (serialization + resolving)

also depending on outcome of discussion about open question above, effort estimation could be some 4-6 days

**Comment by frantuma** [comment]
related to open question above about concurrent allOf, anyOf, oneOf support, as discussed with @webron 3.0 in such case java implementation will deserialize/resolve a single property/annotation in the following order: `allOf`, `anyOf`, `oneOf`

**Comment by frantuma** [comment]
implemented

**Comment by Frontrider** [comment]
What happened with this?
