### ISSUE TITLE
[3.0] Multiple consumes / produces

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#2287]
Looks like supporting multiple consumes or produces defaults to `*/*` rather than the concrete types:

```java
@POST
@Operation(summary = "Create user",
  description = "This can only be done by the logged in user.")
@Consumes({"application/json", "application/xml"})
public Response createUser(
    @Parameter(description = "Created user object", required = true) User user) {
  userData.addUser(user);
  return Response.ok().entity("").build();
}
```

Returns this:

![image](https://user-images.githubusercontent.com/249413/27721980-2cd7dd1e-5d19-11e7-8404-964f423bd566.png)

the `content` key should be `application/json` _and_ `application/xml`

**Comment by webron** [comment]
Resolved by #2290.
