### ISSUE TITLE
java.util.ConcurrentModificationException in ModelResolver when you have both baseTypes and subTypes

### ISSUE THREAD

**Issue by bidisha-c** [swagger-api/swagger-core#2289]
We were migrating our swagger version from 1.5.9 to 1.5.12 and observed we are getting a ConcurrentModificationException for our classes which has both JsonType and JsonSubtypes defined. 
The annotations are like: 
`
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME, `
       ` property = "version",`
       `include = JsonTypeInfo.As.EXISTING_PROPERTY,`
        `defaultImpl = Blah.class,`
        `visible = true)`
`@JsonSubTypes({`
        `@JsonSubTypes.Type(value = Blah.class),`
        `@JsonSubTypes.Type(value = BlahBlah.class)`
`})`

The issue is in the same loop while iterating over the same map and elements are getting resumed. I have marked the code segment which is causing this issue.

**Comment by eddified** [comment]
I'm seeing this as well.

**Comment by sjelen** [comment]
I'm also seeing this, had to downgrade to 1.5.9 from 1.5.16. Any updates on a fix?

**Comment by arysin** [comment]
I'm seeing this with swagger-core 2.0.9

**Comment by frantuma** [comment]
@arysin this seems not to be reproducible with latest swagger-core 2.x version, if you're still experiencing the issue, please provide a complete scenario

**Comment by arysin** [comment]
I can confirm this problem is not present in 2.1.4, thanks!
