### ISSUE TITLE
$$ref field shows up on referenced json objects

### ISSUE THREAD

**Issue by jchoeShareCare** [swagger-api/swagger-core#2305]
I'm not sure if this is the right repo to report this problem. But when I'm referencing a json object for my examples, let's say for my body:

```
parameters:
  - name: body
    required: true
    in: body
    schema:
      $ref: '#/definitions/model.myModel'
      example:
        $ref: /public/javascripts/request.json
```

my `request.json` is a json object. But when it renders, I get an extra `"$$ref"` field that points to the original value. Like so:

```
{
  "foo1": "bar1",
  "foo2":"bar2",
  "$$ref": "/public/javascripts/request.json" // this field shouldn't exist in my original json object. 
}
```
I see this happening in my swaggerUI. So I'm not sure if it's a swaggerUI issue or the editor. Also, I'm not sure if this is supposed to be intended behavior.

**Comment by webron** [comment]
That snippet is not valid. You can't add additional properties alongside a `$ref` and the spec doesn't support referencing examples.

Regardless, this is not the right repo, it should be opened on swagger-ui.
