### ISSUE TITLE
Will swagger-core support kotlin class?

### ISSUE THREAD

**Issue by runjia1987** [swagger-api/swagger-core#2315]
This is an expected feature, not a issue ^_^
I expect swagger annotations(typically @ApiModel, @ApiModelProperty) could be used with kotlin class, currently these annotations are not compatible with kotlin class, many properties could not be recognized.
I'm wondering if there is any plan for this?

**Comment by fehguy** [comment]
It's hard to say without more details. I suggest looking at the 3.0.0-rc2 branch and reporting what doesn't work

**Comment by runjia1987** [comment]
Hi, thanks for reply.
It is my mistake, I defined both @ApiModel(value = "xxx"), where xxx is identical in both classes. after modifying the value, the swagger output is fine.
you may close this issue.
