### ISSUE TITLE
Top level server annotation in v3

### ISSUE THREAD

**Issue by arthurdm** [swagger-api/swagger-core#2317]
There is no top-level OpenAPI annotation (should we?), so it's not clear how to define the top level array of @Server annotations.

**Comment by frantuma** [comment]
@arthurdm This possibly includes other top level metadata, as tags in #2268 and maybe other;

I guess the only options are either 

1. adding an annotation similar to 2.0 `@SwaggerDefinition` (and implement related code in jaxrs reader)

or 

2. relying solely on filter and/or bootstrapping to include such info.

Possibly 2. is enough, and it would provide a single consistent way to provide such data.

@webron @fehguy any thought on this?

**Comment by arthurdm** [comment]
I think having something similar to @SwaggerDefinition would be better, so that we can claim the annotation set is complete (ie: you don't *need* to use bootstrapping or filter if you don't want to).

**Comment by frantuma** [comment]
implemented in #2470 and #2490
