### ISSUE TITLE
ApiListingResource doesn't respect pretty print support

### ISSUE THREAD

**Issue by alexandrebrasil** [swagger-api/swagger-core#2320]
I configured Swagger using `BeanConfig` on my `Application` start up to use pretty print, but when I retrieve the API from `swagger.json` endpoint it's all on a single line.

I've tracked the issue down to the [ApiListingResource](https://github.com/swagger-api/swagger-core/blob/222ef109c83c56a287e59207eb7f6dc794e6ae9d/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java#L1). When this resource processes the API, it doesn't return a Swagger object on the Response (that would be then converted by [SwaggerSerializers](https://github.com/swagger-api/swagger-core/blob/222ef109c83c56a287e59207eb7f6dc794e6ae9d/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/SwaggerSerializers.java)), but returns a text string instead.

If `ApiListingResource` responds with the Swagger object instead, the serialization works fine and respect the pretty print request. Could the `getListing()` code be changed from 

``` java
        if (StringUtils.isNotBlank(type) && type.trim().equalsIgnoreCase("yaml")) {
            return getListingYamlResponse(app, context, sc, headers, uriInfo);
        } else {
            return getListingJsonResponse(app, context, sc, headers, uriInfo);
        }
```

to 

``` java
		Swagger swagger = process(app, context, sc, headers, uriInfo);
		if(swagger == null) {
			return Response.status(Status.NOT_FOUND).build();
		} else {
			return Response.ok(swagger, "json".equals(type) ? MediaType.APPLICATION_JSON_TYPE : new MediaType("application", "yaml")).build();
		}
```
or would it affect some functionality I'm not aware of?

**Comment by ChristianCiach** [comment]
I can confirm this using Swagger 1.5.16. As `BaseApiListingResource.java` calls `Json.mapper().writeValueAsString(swagger)` directly, there is absolutely no point in registering `SwaggerSerializers.class` to the JAX-RS implementation, as `SwaggerSerializers` isn't used anyway.

**Comment by ChristianCiach** [comment]
I now use my own listing resource instead of ApiListingResource as a workaround:

```
/**
 *
 * Hack-class to use until https://github.com/swagger-api/swagger-core/issues/2320 is fixed.
 *
 * @author christianc
 *
 */
@Path("/swagger.{type:json|yaml}")
public class HackApiListingResource extends BaseApiListingResource {

	@Context
	ServletContext context;

	@GET
	@Produces({ MediaType.APPLICATION_JSON, "application/yaml" })
	@ApiOperation(value = "The swagger definition in either JSON or YAML", hidden = true)
	public Response getListing(@Context Application app, @Context ServletConfig sc, @Context HttpHeaders headers,
			@Context UriInfo uriInfo, @PathParam("type") String type) throws JsonProcessingException {
		Swagger swagger = process(app, context, sc, headers, uriInfo);
		if (swagger == null) {
			return Response.status(Status.NOT_FOUND).build();
		}
		if ("json".equals(type)) {
			return Response.ok(swagger, MediaType.APPLICATION_JSON).build();
		}
		if ("yaml".equals(type)) {
			return Response.ok(swagger, "application/yaml").build();
		}
		return Response.status(Status.NOT_FOUND).build();
	}
}

```

I propose this as a fix for the current ApiListingResource.java. Of course, this only works if `SwaggerSerializers` is also registered as a JAX-RS resource, but according to the [official documentation](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5) this needs to be done anyway (but wasn't necessary before because of this bug).

**Comment by ChristianCiach** [comment]
Wtf is this anyway?

```
                String yaml = Yaml.mapper().writeValueAsString(swagger);
                StringBuilder b = new StringBuilder();
                String[] parts = yaml.split("\n");
                for (String part : parts) {
                    b.append(part);
                    b.append("\n");
                }
                return Response.ok().entity(b.toString()).type("application/yaml").build();
```

Why first split the yaml and then reconstruct it again?

**Comment by ChristianCiach** [comment]
The bug of this issue has been introduced with 3ad759596f321ffb195256e045ec5803c00ee53c. I propose a complete revert of this commit, as I don't see the point of it. The commit message is "use custom object mapper to serialize json in order to avoid null values", but I don't see any null handling that would differ from the current implementation of `SwaggerSerializers.java`. Please revert this commit!
