### ISSUE TITLE
Unused Parameters annotations

### ISSUE THREAD

**Issue by arthurdm** [swagger-api/swagger-core#2322]
In the v3 branch there's an annotation called "Parameters", which is not really used except for a containment reference from "Parameter".  I believe this annotation can be deleted, since we're just using an array (ie: Parameter[]) to denote the list of parameters.

**Comment by arthurdm** [comment]
Similarly, the "ArraySchema" annotation can be deleted if its 3 methods are transferred into Schema, and the "array" reference from Parameter is deleted.

**Comment by frantuma** [comment]
Parameters container annotation is supported at method level, closing ticket
