### ISSUE TITLE
Returning different objects

### ISSUE THREAD

**Issue by raderio** [swagger-api/swagger-core#2329]
In our application user can register as personal or as business account, like on ebay https://reg.ebay.com/reg/PartialReg

We should have an endpoint in API to retrieve info about logged user, for example "GET /me". As user can be or personal or business, we should be able to return different objects. 

How this should be in Swagger?

**Comment by fehguy** [comment]
You have two choices.  Use "allOf" and a discriminator, which allows a base class to be returned, and one-or-more subclasses of the base class.  Or wait for the 3.0 specification, which is due out next week.  This repository supports that new specification in the feature/3.0.0-rc2 branch.

**Comment by raderio** [comment]
Thanks. In v3.0 it will be something different from "allOf"?

**Comment by fehguy** [comment]
You can use `allOf` but in v3 there is `oneOf` or `anyOf` which is easier for most cases.

**Comment by raderio** [comment]
Ok, thanks.
