### ISSUE TITLE
Header parameter with default value

### ISSUE THREAD

**Issue by sapit** [swagger-api/swagger-core#2341]
I would like to add a header parameter to the client which has a constant value. I wish for the parameter not to appear in the java method prototype of the API, since it will break other people's code if they choose to use the new version of the configuration. 

I am using java feign. 

Foo:
    name: foo
    in: header
    description: Description description description
    required: true
    type: string
    enum:
      - bar

Now it becomes:
`testApi.v1TestGet( param1, param2, foo )`

I want it to stay:
`testApi.v1TestGet( param1, param2 )`
And have the default value of the header parameter foo

```
"Content-Type: application/json",
"Accept: application/json",
"foo: bar"
```

I assumed, that if a constant value is set to the parameter, it will not be included in the Java method prototype. Is this expected behaviour? Is there a way to achieve this?

**Comment by MugdhaB** [comment]
@sapit did you get an answer to this?

**Comment by sapit** [comment]
No, it wasn't resolved, I ended up doing something different. It was a while ago, I don't remember anymore, unfortunately.
