### ISSUE TITLE
Swagger UI not work after deployment into remote server

### ISSUE THREAD

**Issue by JessieGit** [swagger-api/swagger-core#2359]
I am using Liberty (17.0.0.2) support for swagger. Now I got problems. The API displays perfectly from my local machine(i.e., http://localhost:9080/api/explorer/), but when it is deployed into our remote server, it got a couple of issues. 
(1). It takes over 12 hours to complete the scanning before showing the API list from the url. (2). After the API list shown, try it out button immediately returns no content without actual execution.  (3). @ApiParam seems not work because the default input value of each API is missing. Locally, they are all there. (4). @Swaggerdefinition seems not work, because the title remains unchanged after I use @Swaggerdefinition. IS there any way to limit the scanning only to a specific war file?

Current attempts: (1). Disabling all other non-swagger application. But I don't think this is the reason because locally I also have other applications the same as remote server running, still the APIs load almost immediately. 
(2). \<apiDiscovery swaggerDefinition='/***/api-ls'>
       \<webModuleDoc contextRoot='/a/a' enable='false' />
       \<webModuleDoc contextRoot='/b/b' enable='false' />
       \<webModuleDoc contextRoot='/c/c' enable='false' />
    \</apiDiscovery> to point out the master war file for scanning and disable others.
(3). use 
\<cors domain='/***/api-ls'
      allowedOrigins='https://wrkp.***.com:8443'
      allowedMethods='GET, DELETE, POST, PUT'
      allowedHeaders='\*'
      allowCredentials='true'
      maxAge='3600' />
So far, still no luck. This has been haunting the team for a long time. Thank you very much for your help.

**Comment by arthurdm** [comment]
Closing this as it relates to a particular vendor.  Please open a PMR with IBM.
