### ISSUE TITLE
bugfix/reader-annotations-improvement

### ISSUE THREAD

**Issue by ralphdoe** [swagger-api/swagger-core#2395]
- [x] In Links (operationId - operationRef): 
 - operationId and operationRef are mutually exclusive.
 - in case the operationId and operationRef are both filled, the operationId has the priority.

- [x] Schema annotation: 
 - The maximum is not being treated. 
 - The minimum is not being treated. 
 - The value must be ignored if it's empty or it's not a number, considering the field is a String. 

- [x] Parameter annotation:
 - The schema, content and arraySchema must be mutually exclusive.
 - In case they are all filled, the priority must be the next: content > array > schema.

- [x] ArraSchema in Parameter annotation:
 - The ArraySchema Annotation hasn't been implemented yet.
 - Adding some tests about this. 

- [x] Contents updates:
 - Method getContents deleted. 
 - Method getContent improved, solving this issue: #2403. 
-  applyProduces replaced by applyMediaType (now receives String arrays)

Everything solved in this PR: https://github.com/swagger-api/swagger-core/pull/2404

**Comment by frantuma** [comment]
closing as implemented in related PRs
