### ISSUE TITLE
@Content annotation should have array=@ArraySchema attribute to enable array type in responses/requestBody

### ISSUE THREAD

**Issue by arturdzm** [swagger-api/swagger-core#2397]
just like `@Parameter` annotation has array=`@ArraySchema` I think `@Content' should have one too

**Comment by pawsaw** [comment]
It have been a while... any updates on this?

Regards, Pawel

**Comment by frantuma** [comment]
`ArraySchema` support added to `Content` annotation in #2501 (in `2.0` branch) and will be part of next release.
