### ISSUE TITLE
Do you plan on supporting the 1.5.x branch?

### ISSUE THREAD

**Issue by edrevo** [swagger-api/swagger-core#2399]
I am interested in seeing some bugs fixed in the 1.5.x branch (I am happy to provide the fixes if needed), but first I'd like to know whether swagger 2.0 support is going to continue or it the plan going forward is to only support swagger 3.0

**Comment by webron** [comment]
@edrevo Apologies for the much delayed reply, and it's a very fair question.

While we are focused on OAS3 support, we plan on maintaining the 1.5.X branch for a while. It's a bit of a challenge keeping the balance between the two versions, but we realize there are still issues that need to be addressed in 1.5 and we do not expect people to migrate to 2.0 quickly. Of course, at some point we won't push out new versions  for 1.5, but we're not there yet.

Feel free to submit PRs for issues that are relevant to you, and we'll do our best to review in a timely manner (not like this ticket) and when there's enough sum of things to release, will push out a new version.
