### ISSUE TITLE
@RequestBody should be populated with @Consumes from method or class when mediaType is not specified

### ISSUE THREAD

**Issue by arturdzm** [swagger-api/swagger-core#2403]
Since the RequestBody, ApiResponse and Parameter all have content
I think we can have 1 method called 
getContent(Content[] content, String[] mediaTypes) 
so each type can pass in value() of @Consumes or @Produces
or null if no mediaTypes  specified. 
if mediaTypes is null set it to `*/*`

**Comment by ralphdoe** [comment]
You're totally right, @arturdzm. I have solved this here: https://github.com/swagger-api/swagger-core/pull/2404

**Comment by frantuma** [comment]
closing as implemented in related PRs
