### ISSUE TITLE
Improve ApiResponse generation

### ISSUE THREAD

**Issue by arturdzm** [swagger-api/swagger-core#2410]
Right now when user doesn't specify responses in `@Operation` 
mediaType is always */*. It should use methodProduces and classProduces fields to populate it if they are present.
Also If `Response.class` is used as return it still possible to generate empty response code without content field to create valid documents, as per spec responses shouldn't be empty

**Comment by frantuma** [comment]
Default response is created for non annotated class/methods. Fix to resolve media type in case of non annotated return type added in #2513.
