### ISSUE TITLE
Serializing OAS3 models with 'extensions' produce wrong documents

### ISSUE THREAD

**Issue by navidsh** [swagger-api/swagger-core#2411]
Now that OAS3 models don't have `@JsonAnyGetter` and `@JsonAnySetter` annotations, serializing models produces incorrect documents.

Part of a serialized doc through `io.swagger.util.ObjectMapperFactory`:
```
"extensions" : {  <-- This is extra
    "x-abc-xyz_2" : "value_2",
    "x-abc-xyz_1" : "value_1"
}
```

**Comment by frantuma** [comment]
fixed in #2459
