### ISSUE TITLE
Datatype is undefined with swagger version change

### ISSUE THREAD

**Issue by VladSergeev** [swagger-api/swagger-core#2419]
Hello.
I found a bug,as i understand it.
Here is simple java code:

    @PostMapping("/test")
    @ApiOperation(value = "preview", authorizations = {@Authorization(value = "basicAuth")})
    @ApiImplicitParams({
            @ApiImplicitParam(name = "file", dataType = "file", paramType = "form",
                    value = "File types are csv,tsv,xlsx")
    })
    public List<String> test(@RequestParam("file") MultipartFile file) {
                ....
    }

If i use swagger annotations version 2.6.0,then i get correct result of data type
![image](https://user-images.githubusercontent.com/18330170/30065320-110ae346-925d-11e7-9954-d7f15d3e63a6.png)

If i update it to 2.7.0 i get undefined result:
![image](https://user-images.githubusercontent.com/18330170/30065345-25a4b732-925d-11e7-9647-ec98cd3d163c.png)

**Comment by webron** [comment]
This is Springfox - please file the ticket with them.
