### ISSUE TITLE
Swagger 2.0 ModelConverter support for required/not required items

### ISSUE THREAD

**Issue by pjfanning** [swagger-api/swagger-core#2420]
With the Required field having moved to the parent property ([example](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore.json)), I'm wondering how to get swagger-scala-module ModelConverter to be able to control which items in a case class are marked as required. The `resolve` method doesn't appear to expose the parent property. Is there another way to do this, or do we need to change the ModelConverter resolve to allow access to the parent property?

**Comment by pjfanning** [comment]
@webron @frantuma would either of you know the answer to this question? I have a partially working port of the swagger-scala-module to use io.swagger.v3.core but I haven't found a solution for this.

**Comment by frantuma** [comment]
@pjfanning I am not sure I understand what you mean; can you provide some more details about your case?

**Comment by pjfanning** [comment]
https://github.com/swagger-api/swagger-scala-module/blob/develop/src/main/scala/io/swagger/scala/converter/SwaggerScalaModelConverter.scala#L65

The setRequired(boolean) method is no longer supported in swagger-core v2.0.0. As far as I can work out, the code will need to call setRequired(Collection<String>) on the parent model. I'm not sure how this can be achieved in the ModelConverter and it does not seem to provide access to parent models.

**Comment by frantuma** [comment]
There is an ongoing effort to rationalize converter/resolver code tracked in #2593, with just merged PR #2594 implementing a first phase which can help with scala converter issue, as it adds parent resolved schema as parameter of ModelConverter `Schema resolveAnnotatedType` method (equivalent to `resolveProperty` method in 1.5). 

Let me know if this can help, also added a note in #2593 to keep track of any further changes affecting / involving updates of scala converter project.

**Comment by pjfanning** [comment]
Closed due to https://github.com/swagger-api/swagger-core/issues/2593

**Comment by pjfanning** [comment]
@frantuma I had a look after the swagger-core 2.0.0 release but still can't work out a way to rewrite the swagger-scala-module ModelConverter to properly support optional properties. Would you be able to review my comment from Dec 18?

**Comment by pjfanning** [comment]
@frantuma @webron would it be possible to some pointers on how I might solve this issue?
If I got this solved, I think I'll be in a position to release a swagger 2.0 based version of swagger-akka-http (which contains a copy of swagger-scala-module).

**Comment by frantuma** [comment]
@pjfanning the name of the field is resolved (if not passed in `annotatedType` param) in `resolveAnnotatedType` method; not sure how is your code organized, (e.g. if you're extending ModelResolver or such), currently e.g. overriding protected String `decorateModelName(AnnotatedType type, String originalName)` to store the name somewhere could be an option, I would need some more details about your code.

**Comment by pjfanning** [comment]
@frantuma thanks for your suggestions
The class is https://github.com/swagger-api/swagger-scala-module/blob/develop/src/main/scala/io/swagger/scala/converter/SwaggerScalaModelConverter.scala

My partial rewrite for swagger 2.0.0 is https://github.com/pjfanning/swagger-scala-module/blob/swagger-core-2.0.0/src/main/scala/io/swagger/scala/converter/SwaggerScalaModelConverter.scala

**Comment by frantuma** [comment]
@pjfanning not sure if this helps in all cases, however #2909 adds propName to annotatedType, try to give it a go.

**Comment by pjfanning** [comment]
Closing because @frantuma 's has helped me to progress my scala solution
