### ISSUE TITLE
OperationId value

### ISSUE THREAD

**Issue by cunhazera** [swagger-api/swagger-core#2425]
Is there any way to generate a custom operationId in runtime?

**Comment by webron** [comment]
You mean not specify it as part of the annotation? Can you explain the use case?

**Comment by cunhazera** [comment]
@webron yes, without having to add `nickname` to `@ApiOperation`.
I want that in the moment when swagger.json is being generated I can intercept the generation to put some custom operationId (just a random string). Because I'm facing a problem: when there are two methods with same name (even in different classes) it uses the method name as operationId, and it causes conflicts in the file.

**Comment by webron** [comment]
That sounds like the issue is with the generated operationId's rather than with allowing users to dynamically set those at runtime.

**Comment by cunhazera** [comment]
I think I used the wrong term. It should be in compile time, when swagger scan classes to make the swagger.json file.

**Comment by webron** [comment]
But that's exactly what the `nickname` is for. Again, if the problem is that it generates conflicting operationId's, that's a different issue.

**Comment by cunhazera** [comment]
Is there any chance to adopt another generation strategy?

**Comment by webron** [comment]
Of course, but a test case demonstrating the issue would help.

**Comment by cunhazera** [comment]
I created another issue: https://github.com/swagger-api/swagger-core/issues/2433

if you need anything else just tell me.
