### ISSUE TITLE
"Bearer" was not authenticated. Failure message: "No token found."

### ISSUE THREAD

**Issue by nukec** [swagger-api/swagger-core#2430]
I am using swagger with .net core api.

I am using identityserver 4 for authentication. Everything worked for months initially well, today I started api and tried to access docs. path is localhost/docs.

I can see swagger title but it just stucks loading forever and error below is connected with bearer token? Why, I thought It should be public access to those docs.

> Application version: 1.0.0.0
> AspNetCoreEnvironment: Development
> AuthenticationScheme: Bearer
> Client IP address: ::1
> DeveloperMode: true
> Event time: 16/09/2017 13:42:02
> EventId: 1208422962
> FailureMessage: No token found.
> LogLevel: Information
> Message: "Bearer" was not authenticated. Failure message: "No token found."
> MessageTemplate: {AuthenticationScheme} was not authenticated. Failure message: {FailureMessage}
> Node name: DESKTOP-NOBHIJ3
> Operation ID: 0U0whLiv7og=
> Operation name: GET /docs/lib/jquery-1.8.0.min.js
> RequestId: 0HL7T12PIEUD4
> RequestPath: /docs/lib/jquery-1.8.0.min.js
> Role instance: DESKTOP-NOBHIJ3
> SDK version: dotnet:2.2.0-54036
> Severity level: Information
> SourceContext: IdentityServer4.AccessTokenValidation.Infrastructure.NopAuthenticationMiddleware
>

**Comment by webron** [comment]
This is the repo for the Java implementation. Please open the ticket on the relevant project.

**Comment by CN-jaycee** [comment]
I have the same problem.
