### ISSUE TITLE
Support Maps

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#244]
Supporting maps with arbitrary key types would make swagger codegen very complicated but supporting a Map[String, Object] would be very useful.

**Comment by hasnen** [comment]
When In Spring rest api has @requestParameter Map<String ,String> then we can not validate Map's Parameter !!
Any solution for swagger model schema to get Map parameter to validate ??
![screenshot from 2016-01-02 13 59 29](https://cloud.githubusercontent.com/assets/13870488/12073821/37526c54-b159-11e5-9e24-f666cd3dde35.png)
