### ISSUE TITLE
Integrate swagger with jersey2, guice but got 404 error

### ISSUE THREAD

**Issue by iamfuzi** [swagger-api/swagger-core#2462]
Hi,
I have a project use jersey 2 and use guice as DI. I have followed the instructions in the wiki page. But when startup my application and input the url, got a 404 error. I will post the code below. Thanks for your help.

1. Not use maven to manage the dependencies, I use apache ivy.
   In ivy.xml, I add the code below:
`<dependency org="io.swagger" name="swagger-jersey2-jaxrs" rev="1.5.9" conf="webinflibs->default"/>`

2. In ResourceConfig
public class GuiceResourceConfig extends ResourceConfig {
	@Inject
	public GuiceResourceConfig(ServiceLocator serviceLocator, ServletContext servletContext) {
		log.info("Try to bridge guice and jersey resource...");
		Injector injector = (Injector) servletContext.getAttribute(Injector.class.getName());
        GuiceBridge.getGuiceBridge().initializeGuiceBridge(serviceLocator);
        GuiceIntoHK2Bridge g2h = serviceLocator.getService(GuiceIntoHK2Bridge.class);
        g2h.bridgeGuiceInjector(injector);
        
        configureSwagger();
	}
	
	private void configureSwagger() {
	    register(ApiListingResource.class);
	    register(SwaggerSerializers.class);
	    BeanConfig config = new BeanConfig();
	    config.setSchemes(new String[]{"http"});
	    config.setBasePath("http://localhost:8888/api");
	    config.setResourcePackage("com.test.server.service.resources");
	    config.setPrettyPrint(true);
	    config.setScan(true);
	  }
}

3. In servlet module
            final Map<String, String> params = new HashMap<>();
    		params.put(ServletProperties.JAXRS_APPLICATION_CLASS, GuiceResourceConfig.class.getCanonicalName());
    		params.put(ServerProperties.PROVIDER_PACKAGES, "com.test.server.service.resources");

    		bind(ServletContainer.class).in(Scopes.SINGLETON);
		serve("/gmx/rest/*").with(ServletContainer.class, params);
			
                bind(SwaggerFilter.class).in(Scopes.SINGLETON);
                filter("/api/*").through(SwaggerFilter.class);

 4. SwaggerFilter
public class SwaggerFilter implements javax.servlet.Filter {
    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        HttpServletResponse res = (HttpServletResponse) response;
        res.addHeader("Access-Control-Allow-Origin", "*");
        res.addHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT");
        res.addHeader("Access-Control-Allow-Headers", "Content-Type");
        chain.doFilter(request, response);
    }

    @Override
    public void destroy() {
    }

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
    }
}

After startup my application and open this URL: http://localhost:8888/api/swagger.json, the browser shows: 
Error Occurs

Please contact system administrator!

I click F12 to check the error. It shows 404, not found.

Thanks for your help.

**Comment by iamfuzi** [comment]
I resolve this issue by using servlet.

**Comment by abdulroufabu** [comment]
@iamfuzi 

I am facing the same issue on integration of swagger with jersey APIs, could you please help me with the solution used to solve this issue. Thanks
