### ISSUE TITLE
List<String> in @BeanParam results in array of type "object" in generated JSON/YAML

### ISSUE THREAD

**Issue by ChristianCiach** [swagger-api/swagger-core#2466]
This bug has been introduces by commit 26f9572a6a92cd2375ef876baabe8667dbbf9dcd, which wrongfully replaced `.getGenericType()` by `.getRawType()`, even if "`.getType()`" would have been the correct non-deprecated replacement.

Pull-Request incoming.

**Comment by ChristianCiach** [comment]
Pull requests for master and 2.0 are ready. Please merge at your earliest convenience.

**Comment by frantuma** [comment]
implemented in #2548
