### ISSUE TITLE
RequestBody parameter missing from openApi.json - swagger 2.0.0-RC1

### ISSUE THREAD

**Issue by crizo23** [swagger-api/swagger-core#2473]
I am not seeing the requestBody in the resulting openApi.json.

Below is a method in my java class with gradle swagger dependency: io.swagger:swagger-jaxrs2:2.0.0-rc1

No matter what I try I don't get the resulting RequestBody structure as detailed in the documentation. It's documenting the NewPerson param in the parameters array instead. It is interesting that in rc1, the Operation takes a RequestBody, but in rc2 they dropped that. Confusing. 

The resulting openApi.json:
```
"post": { 
    "parameters": [
     {
        "schema": {
        "$ref": "#/components/schemas/NewPerson"
        }
}],
"responses": {
"200": {
"content":
...
}
}
}
```

The code:
```
import io.swagger.oas.annotations.Operation;
import io.swagger.oas.annotations.media.Content;
import io.swagger.oas.annotations.media.Schema;
import io.swagger.oas.annotations.parameters.RequestBody;
import io.swagger.oas.annotations.responses.ApiResponse;

 @POST 
 @Produces({MediaType.APPLICATION_JSON})
 @Consumes(MediaType.APPLICATION_JSON)  
 @Operation()
    public Response post(        
        @RequestBody(description = "New Person", required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = NewPerson.class)))  NewPerson np
    )
    {}
```

**Comment by frantuma** [comment]
@crizo23 Thanks for reporting this

Your example should work (almost) ok in rc2, with a resource like:

```
@Path("/")
public class Issue2473Resource {

	@POST
	@Produces({MediaType.APPLICATION_JSON})
	@Consumes(MediaType.APPLICATION_JSON)
	@Operation()
	public Response post(
			@RequestBody(description = "New Person", required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = Pet.class))) Pet np
	) {
		return Response.ok().entity("ok").build();
	}
}
```
the resolved spec is:

```
openapi: 3.0.0
paths:
  /:
    post:
      operationId: post
      requestBody:
        description: New Person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        default:
          description: no description
```

Still `required` is not correctly resolved, will be fixed in next rc/release. 

Unfortunately in RCs annotations are still not fully stable, as you mentioned for `@RequestBody`; the structure should be finalized in next rc/release.

**Comment by crizo23** [comment]
Thanks...I'll wait to try it in RC2. I'm waiting on a gradle/jax-rs dependency issue before I can move to rc2

**Comment by frantuma** [comment]
closing as implemented in RC2
