### ISSUE TITLE
`ApiModelProperty` annotation generates automatically `example` for `Boolean`

### ISSUE THREAD

**Issue by lhauspie** [swagger-api/swagger-core#2484]
I'm working in Scala.
I defined my case class as follow:
```Scala
import io.swagger.annotations.{ApiModel, ApiModelProperty}

@ApiModel(value = "TokenIntrospectionResponse")
case class TokenIntrospectionResponse(@(ApiModelProperty@field) @BeanProperty val active: Boolean)
```

When I read the generated schema, I see:
```JSON
"definitions": {
   "TokenIntrospectionResponse": {
      "type": "object",
      "properties": {
        "active": {
            "type": "boolean",
            "example": false
         }
      }
   }
}
```

If I replace the type of `active` property from `Boolean` to `String`, the result of the Swagger doc generation is:
```JSON
"definitions": {
   "TokenIntrospectionResponse": {
      "type": "object",
      "properties": {
         "active": {
            "type": "string"
         }
      }
   }
}
```

If I remove the `ApiModelProperty` annotation, the `example` is not generated for type `Boolean`:
```JSON
"definitions": {
   "TokenIntrospectionResponse": {
      "type": "object",
      "properties": {
         "active": {
            "type": "boolean"
         }
      }
   }
}
```

- Is it a bug ?
- Is there a way to keep this `ApiModelProperty` annotation and delete this `example` property for boolean property ?
- If not, is there an existing workarround ?

For your information, I need this annotation to specify this property is required.
I need to erase this `example` property because Amazon API Gateway is not supporting this one ([source](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html)):
> - API Gateway supports most of the Swagger specification, with the following exceptions:
>    - [...]
>   - **The __example__ tag is not supported.**

Thanks in advance.

**Comment by lhauspie** [comment]
is there someone to help me please ?

**Comment by simonamc** [comment]
@lhauspie Yeah I think this is a bug too, `ApiModelProperty` defaults example to the empty string, for all numeric `Properties` this is being mapped to null as parse is throwing `NumberFormatException` and not modifying the null example.  However `Boolean#parseBoolean` behaves differently parsing the empty string (and null) as false.  I believe that `BooleanProperty#setExample` needs to treat these as special cases.

**Comment by simonamc** [comment]
I've created the following pull request
https://github.com/swagger-api/swagger-core/pull/2561
