### ISSUE TITLE
io.swagger.models.Info should have a function public void setVendorExtension(Map<String, Object>)

### ISSUE THREAD

**Issue by GLOBE1984** [swagger-api/swagger-core#2486]
As the swagger-ui will report error when the vendorextensions is in the info json object, I think the  io.swagger.models.Info should have a function setVendorExtension(Map<String, Object>), which provides the functionality to set the vendorExtensions to null, to avoid mapping vendorExtensions to the json.

**Comment by ymohdriz** [comment]
Method name should be **setVendorExtensions**. We have a similar method in AbstractParameter.java

**Comment by frantuma** [comment]
implemented in #2530
