### ISSUE TITLE
@ApplicationPath not considered

### ISSUE THREAD

**Issue by pawsaw** [swagger-api/swagger-core#2489]
The javax.ws.rs.ApplicationPath is not considered while constructing URLs.

**Comment by webron** [comment]
In which version?

**Comment by pawsaw** [comment]
In version 2.0.0-rc2

Having a resource...

```
@Path("/persons")
class PersonResource { ... }
```
and

```
@ApplicationPath("/api")
class JerseyConfig extends ResourceConfig {
    public JerseyConfig() {
        super();
        register(PersonResource.class);
        // ...
    }
}
```

... I would expect the URIs for each GET, POST, ... annotated method to be /api/persons
 
Best regards, Pawel

**Comment by frantuma** [comment]
`@ApplicatiionPath` support added in #2493; it's currently in `2.0` branch and will be part of next rc
