### ISSUE TITLE
Fields not specific to body parameter should be in AbstractSerializableParameter

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-core#2492]
Hi team,

In general, fields which are not specific to body parameter should be in AbstractSerializableParameter and fields applicable to all parameters in AbstractParameter.

But field 'allowEmptyValue' which is not specific to body parameter should be in AbstractSerializableParameter. 

Is there any reason that it was added in AbstractParameter instead of AbstractSerializableParameter?

Thanks,
Mohammed

**Comment by frantuma** [comment]
implemented in #2686
