### ISSUE TITLE
swagger-jaxrs with Java8 LocalDateTime gives complex date/datetime fields

### ISSUE THREAD

**Issue by rpgayatri** [swagger-api/swagger-core#2499]
We use swagger-jaxrs dependency :
               
```
 <dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jaxrs</artifactId>
			<version>1.5.0</version>
		</dependency>
```

And one of the variables with Java8 LocalDateTime datatype

`private LocalDateTime created;`

The Swagger shows a complex date/datetime field as follows:

```
"created": {
    "monthValue": 1,
    "dayOfYear": 2,
    "dayOfWeek": "MONDAY",
    "dayOfMonth": 2,
    "hour": 12,
    "minute": 12,
    "second": 34,
    "year": 2017,
    "month": "JANUARY",
    "nano": 0,
    "chronology": {
      "calendarType": "string",
      "id": "string"
    }
  }
```

I want these temporal data types to be serialized to string in a simple format like "2017-02-02T12:12:34"

`@ApiModelProperty(dataType = "java.lang.String", example = "")` is not working for me. And I am not sure how to use `Docket#directModelSubstitute(LocalDateTime.class, String.class)` in Swagger JAX-RS

Please help me how to change this representation in Swagger JAX-RS.

**Comment by webron** [comment]
You're using a very old version. Try using the latest 1.5.x.

**Comment by rpgayatri** [comment]
Thanks a lot @webron 
It worked with the latest version.
