### ISSUE TITLE
@ApiModelProperty in Annotations-2.X?

### ISSUE THREAD

**Issue by davidmerrick** [swagger-api/swagger-core#2503]
Looking at [the docs](https://github.com/swagger-api/swagger-core/wiki/Annotations-2.X) for Annotations 2.X, there's a reference to \@ ApiModelProperty. However, this annotation doesn't exist in the [source](https://github.com/swagger-api/swagger-core/tree/feature/3.0.0-rc2/modules/swagger-annotations/src/main/java/io/swagger/oas/annotations). Is the documentation incorrect? Or is the source incorrect? In which case, was it removed intentionally, or is it planned to be added later?

**Comment by davidmerrick** [comment]
Ah, I see it now. Most of what used to be under ApiModelProperty now lives under Schema.

**Comment by stiancognite** [comment]
What does that mean, exactly? [The docs](https://github.com/swagger-api/swagger-core/wiki/Annotations-2.X#schema) shows this:
```
@ApiModelProperty(description = "pet status in the store", allowableValues =  {"available","pending","sold"})
  public String getStatus() {
    return status;
  }
```
But that annotation doesn't exist in 2.0.0-rc2. How should I document fields in my class?

**Comment by ralphdoe** [comment]
You both are right. The ApiModelProperty doesn't exist in the new version. Everything related with the models is now handled with the @Schema annotation. We updated the wiki with this: 

And/Or a schema property:

``` @Schema(description = "pet status in the store", allowableValues =  {"available","pending","sold"})
  public String getStatus() {
    return status;
  }```
