### ISSUE TITLE
Hide resource class using io.swagger.core.v3:swagger-jaxrs2:2.0.0-SNAPSHOT?

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2526]
Previously I could use the class-level annotation `@Api` like this to hide everything in a resource class from appearing in `swagger.json`: `@Api(hidden = true)`. Is it possible to hide everything in a resource class from appearing in `openapi.json` in a similar manner?

**Comment by frantuma** [comment]
yeah, such mechanism has been in todo for a while, just added in #2526 support for `@Hidden` annotation at class or operation level, available in latest snaphsot. pls use `@Hidden` as `@Api(hidden = true)` in 1.x

**Comment by stiancognite** [comment]
Thank you again very much! :)
