### ISSUE TITLE
Is it possible to store the generated openapi.json to a file as a build step? (Using io.swagger.core.v3:swagger-jaxrs2:2.0.0)

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2527]
This might be out of scope for swagger-core, but: Is it possible to store the generated openapi.json to a file as a build step? (Using io.swagger.core.v3:swagger-jaxrs2:2.0.0)

**Comment by frantuma** [comment]
yes at the moment is out of scope for swagger-core; a separate project https://github.com/kongchen/swagger-maven-plugin provides such feature for maven environment, we don't know when/if it will be updated to support 2.x; Alternatively you can provide your own code and execute during buid lifecycle via exec, and task or equivalent; the following would be an example of such class:

```
Class ...
    public static void main(String[] args)  {
        SwaggerConfiguration oasConfig = new SwaggerConfiguration()
                .prettyPrint(true)
                .resourcePackages(Stream.of("io.swagger.sample.resource").collect(Collectors.toSet()));

        try {
            OpenApiContext ctx = new JaxrsOpenApiContextBuilder()
                    .openApiConfiguration(oasConfig)
                    .buildContext(true);
            String yaml = Yaml.pretty(ctx.read());
            System.out.println(yaml); // save to file, etc..

        } catch (OpenApiConfigurationException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
    }
```

**Comment by stiancognite** [comment]
Thank you for the suggestion! I see that my resource classes aren't found by the call to `ctx.read()`. Do you know why that could be? At first I thought it was because I had the code you posted before I eventually started the server (`org.eclipse.jetty.server.start()`), but I have the same problem when I'm sure to have your code after the server has started. Do you have any pointers on how I can make sure to do this in a way that'll include my resource classes?

**Comment by frantuma** [comment]
As in the example above, one option to provide resources is specifying them in configuration, either as list of classes, or packages:

```
SwaggerConfiguration oasConfig = new SwaggerConfiguration()
                .prettyPrint(true)
                .resourcePackages(Stream.of("io.swagger.sample.resource").collect(Collectors.toSet()));
```

Did you replace the `resourcePackages` values above with the ones for your project?

**Comment by stiancognite** [comment]
I didn't specify the resources actually, because calling /openapi.json found them automatically. I thought then that they should be found automatically when I called `ctx.read()` manually. But explicitly adding the package worked :) Thank you again!
