### ISSUE TITLE
@Schema.example only works for Strings

### ISSUE THREAD

**Issue by davidmerrick** [swagger-api/swagger-core#2529]
I'm using annotations 2.X. I've got this annotation for a class:

```
    public static class Foo {
        @Schema(example = "myExampleSessionId")
        @JsonProperty("session_id")
        private EntityId sessionId;

        @Schema(example = "myExampleString")
        private String myString;
    }
```
It renders to this JSON:

```
EntityId": {
"type": "object",
"properties": {
"bytes": {
"type": "array",
"items": {
"type": "string",
"format": "byte"
}
},
"created": {
"type": "integer",
"format": "int64"
}
}
},

Foo": {
"type": "object",
"properties": {
"session_id": {
"$ref": "#/components/schemas/EntityId"
},
"myString": {
"type": "string",
"example": "myExampleString"
}
}
}
```

Notice that there's no "example" parameter associated with "session_id." But the example for the String parameter worked fine.

What I would expect would be this:
```
Foo": {
"type": "object",
"properties": {
"session_id": {
"$ref": "#/components/schemas/EntityId",
"example": "myExampleSessionId"
},
"myString": {
"type": "string",
"example": "myExampleString"
}
}
}
```

Is this a bug, or is there something I need to do differently with my annotations?

**Comment by webron** [comment]
Can't work that way, because that's not a valid definition. You can't add additional properties alongside a `$ref`.

**Comment by davidmerrick** [comment]
The thing is, the properties aren't parsing within the ref, either. i.e. there's no "example" parameter inside the Foo object. Is there something I need to do to get those to parse correctly?

**Comment by davidmerrick** [comment]
Or is there another way to define an example for a `$ref`?

**Comment by webron** [comment]
Did you define the example inside `EntityId`?

**Comment by davidmerrick** [comment]
I didn't. Will give that a try.

**Comment by davidmerrick** [comment]
That worked! Thanks.

**Comment by webron** [comment]
Great. Is there anything else or can we close the ticket?
