### ISSUE TITLE
How to document path params in a resource-class-level @Path annotation? (swagger.core.v3)

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2532]
I have this class:
```
@Path("/api/{version}/projects/{project}/")
public class SomethingResource {
  public Response getSomething1() {}
  public Response getSomething2() {}
  public Response getSomething3() {}
  ...
  public Response getSomethingN() {}
}
```
Is there a way to document the two path parameters without having to document them in each `getSomething` resource method in the class?

**Comment by frantuma** [comment]
in compliance with jax-rs spec, you can use field or constructor params, which will be added to parameters of each operation in the class; an example here: https://github.com/swagger-api/swagger-core/blob/2.0/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/ResourceWithKnownInjections.java

**Comment by stiancognite** [comment]
Thank you!
