### ISSUE TITLE
Set tags at a resource class-level? As @Api(value="tagName") did before. (swagger.core.v3)

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2534]
Is there a way to set tag names at a resource class level? As one could do with `@Api("tagName")` before? I would like to avoid setting the same tag on all operations in a resource class.

**Comment by frantuma** [comment]
you can specify them as class level:
```
@Tag(name = "mytag")
public class MyClass {
```
if you provide a name only, the tag will be added to operation only; if you also provide additional fields, like `description` or `externalDocs` the Tag will also be added to `openAPI.tags` field.

A full example here: https://github.com/swagger-api/swagger-core/blob/2.0/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/TagsResource.java

**Comment by stiancognite** [comment]
Thank you!
