### ISSUE TITLE
[ swagger-jaxrs2] No @Servers annotation to define servers globally

### ISSUE THREAD

**Issue by redmitry** [swagger-api/swagger-core#2540]
Hello,
I can't find a way to define servers globally in swagger-jaxrs2 RC2.
Could this annotation to be added?

Dmitry

**Comment by frantuma** [comment]
Hi,

An `OpenAPIDefinition` annotation is available in current snapshot version (`io.swagger.core.v3:swagger-jaxrs2:2.0.0-SNAPSHOT`, please notice the groupId change) available on sonatype, or in oncoming rc. By annotating a resource with `@OpenAPIDefinition`, the defined fields will be resolved into the [OpenAPI Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#oasObject); this includes servers.

Alternatively (available also in `rc2`) you can provide such data in the `openAPI` property of the configuration (either with config file or code).

**Comment by redmitry** [comment]
Great!
I see there are many changes in annotations since RC2 ;-).

It works.

Thank you very much.

D.
