### ISSUE TITLE
Set security at a resource class level? As `@Api(authorizations = ..)` did before. (swagger.core.v3)

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2547]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Request
| Which Swagger-Core version?       | io.swagger.core.v3
| Which Java version?               | 8
| Which JAX-RS framework & version? |  Glassfish, Jersey, 2.25.1
 
Previously I could set security on a resource class level (example: `@Api(authorizations = ...)`). Would it be possible to add this capability with swagger core v3? Instead of having to set it in each `@Operation(security = ..)`.

**Comment by frantuma** [comment]
Hi,

In current snapshot version (io.swagger.core.v3:swagger-jaxrs2:2.0.0-SNAPSHOT, please notice the groupId change) available on sonatype, or in oncoming rc, you can annotate your resource class with one or more `@SecurityRequirement` to have them added to operation; see https://github.com/swagger-api/swagger-core/blob/2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/security/SecurityRequirement.java#L26-L34

**Comment by stiancognite** [comment]
Fantastic! Thank you :)
