### ISSUE TITLE
Edit swagger file in while the generation

### ISSUE THREAD

**Issue by cunhazera** [swagger-api/swagger-core#2563]
| Bug or feature request?           | 
Feature

| Which Swagger-Core version?       |
1.5.16

| Which Java version?               |
JDK 8

| Which JAX-RS framework & version? |
Resteasy
 
Is there anyway to intercept and manipulate the swagger.json file generation?

I'm trying to add things to allowablevalues dynamically.

**Comment by frantuma** [comment]
you can use [ReaderListener](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#customising-the-swagger-definition) or provide your own spec-serving resource (see [default one](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/listing/ApiListingResource.java), implement your own REST method, invoking `super.process()` to obtain the resolved `Swagger` object) to further modify the resolved spec. 


Please close ticket if one of the above solves your issue.
