### ISSUE TITLE
DataTypeClass not working in ApiImplicitParam

### ISSUE THREAD

**Issue by pk1914** [swagger-api/swagger-core#2564]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | 1.5.17
| Which Java version?               | 1.8.0_131
| Which JAX-RS framework & version? | 1.19
 

I have two parameters that are shared between all methods in my interface. For that reason I have included them in my parent path (see below). In my actual method, I pass a `RequestContext` which basically holds the values of these parameters.

When generating my swagger spec, I want these parameters to be there under the method.

Here is my code:

```
@SwaggerDefinition(
        info = @Info(
                description = "blahblah",
                version = "v1",
                title = "Example API"
        )
)
@Api(value = "test")
@Produces(APPLICATION_JSON_UTF_8)
@ApiImplicitParams({
        @ApiImplicitParam(name = "language", value = "Caller's language", required = true, dataTypeClass = Language.class, paramType = "path"),
        @ApiImplicitParam(name = "country", value = "Caller's country", required = true, dataTypeClass = Country.class, paramType = "path")
})
@Path("/{language}/{country}/")
public interface ExampleAPI {

    @GET
    @Path("/example/to/path")
    Response exampleMethod(@Context RequestContext requestContext);
```

I have also tried putting the `ApiImplicitParams` above the parent path instead of the method path but it doesn't work.

My result swagger spec contains the above implicit parameters in every method (as expected) but without their type:

```
"parameters": [
  {
    "name": "language",
    "in": "path",
    "description": "Caller's language",
    "required": true
  },
  {
    "name": "country",
    "in": "path",
    "description": "Caller's country",
    "required": true
  }
]
```

Any ideas?

**Comment by pjfanning** [comment]
Have you tried setting the ApiImplicitParams annotations on the methods themselves? It's possible that they only work when they are on the method declarations,

**Comment by pk1914** [comment]
Thanks for the answer. I did, yes, and I got the same result.

**Comment by frantuma** [comment]
This is because you are defining `paramType` as `path`, which doesn't support a schema according to [spec](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/2.0.md#fixed-fields-7); either use a `body` paramType, or remove `dataTypeClass` and use instead one of `type` allowed values (e.g. `string`)

**Comment by pk1914** [comment]
That makes sense, thanks. As they are basically wrappers for strings, I entered `type="string"` instead. However, they do follow a specific pattern (for example the `Country` is a two character country code). Is there a way to show that somehow in the Swagger spec?

**Comment by webron** [comment]
Probably not in 1.5, but you'd be able to in 2.0.

**Comment by pk1914** [comment]
I see. Thanks.

I am okay with them being `type=string` I guess, but something very neat would be to somehow share these parameters between the endpoints that are using it.

Almost all of my endpoints include a `@Context RequestContext requestContext` parameter like the above. That object includes standard path parameters such as language and country.

What are the solutions available here? I tried adding the `@ApiImplicitParams` in the `RequestContext` class like this:

```
@ApiImplicitParams({
		@ApiImplicitParam(name = "language", value = "Caller's language", required = true, dataType = "string", paramType = "path"),
		@ApiImplicitParam(name = "country", value = "Caller's country", required = true, dataType = "string", paramType = "path"),
		@ApiImplicitParam(name = "platform", value = "Caller's platform", required = true, dataType = "string", paramType = "path")
})
public class RequestContext {
...
```

But it didn't read them.
