### ISSUE TITLE
No injection source found for a parameter of type public javax.ws.rs.core.Response

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2567]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | io.swagger.core.v3
| Which Java version?               | 8
| Which JAX-RS framework & version? | jaxrs2 2.0.0
 
I have read [this other issue](https://github.com/swagger-api/swagger-core/issues/507) as well as a few different stackoverflow questions regarding the same error ([#1](https://stackoverflow.com/questions/30653012/multipart-form-data-no-injection-source-found-for-a-parameter-of-type-public-ja), [#2](https://stackoverflow.com/questions/35305517/no-injection-source-found-for-a-parameter-of-type-public-javax-ws-rs-core-respon)).

This resource method:
```
  public Response postCsv(
      @FormDataParam("file")
      @RequestBody(description = "The CSV file to upload.", required = true)
          InputStream file) {
    return emptyResponse();
  }
```
fails with the error
```
[[FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response ***.HelloWorldResource.postCsv(java.io.InputStream) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[multipart/form-data], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class ***.HelloWorldResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@280fafd]}, definitionMethod=public javax.ws.rs.core.Response ***.HelloWorldResource.postCsv(java.io.InputStream), parameters=[Parameter [type=class java.io.InputStream, source=null, defaultValue=null]], responseType=class javax.ws.rs.core.Response}, nameBindings=[]}']
```
But when I remove the `@RequestBody` annotation it works as it should. I also tried using just the `@Parameter` annotation, but I get the same error then. What can I do to accomplish using swagger annotations along with `@FormDataParam`? I'm not sure if this is a mistake in Swagger or in MultiPart.

```
➜  mvn dependency:tree | grep multipart
[INFO] +- org.glassfish.jersey.media:jersey-media-multipart:jar:2.25.1:compile
```

**Comment by frantuma** [comment]
Hi, `@FormDataParam` is not yet supported (in terms of being considered while resolving request body) in latest `rc3` but will be in next version; however  I believe the error you're getting is not related to swagger, but related to [this jersey issue](https://github.com/jersey/jersey/issues/3458) and can be worked around by having `FormDataParam` as the last annotation.

**Comment by stiancognite** [comment]
Thank you! How will it be supported? Say I have this resource method:
```
@POST
@Consumes(MediaType.MULTIPART_FORM_DATA)
public Response postCsv(
  @FormDataParam("file")
  @RequestBody(description = "The CSV file to upload.", required = true)
    InputStream file
  @FormDataParam("filename")
  @Parameter(description = "The name of the file.", required = true)
) {
  return emptyResponse();
}
```
Would that (eventually) work? Or is `@Parameter` the right annotation to use for each thing?

**Comment by stiancognite** [comment]
This seems to be working with the latest snapshot version.

**Comment by NeXT405** [comment]
> Hi, `@FormDataParam` is not yet supported (in terms of being considered while resolving request body) in latest `rc3` but will be in next version; however I believe the error you're getting is not related to swagger, but related to [this jersey issue](https://github.com/jersey/jersey/issues/3458) and can be worked around by having `FormDataParam` as the last annotation.

Dead link. Issue has been moved here: https://github.com/swagger-api/swagger-core/issues/2567
