### ISSUE TITLE
Swagger should have the ability to support response object description

### ISSUE THREAD

**Issue by netroby** [swagger-api/swagger-core#2568]
We need to know what does the property means inside the response object.

```
{
"code": 0,
"msg": "a test",
"method": "get",
"value": 1.00%
}

```

we need add describe to each property 

{
"code": 0, //Return code, normal 0, otherwise >0
"msg": "a test", //Return msg, if not have, it will be empty
"method": "get", //Request method, Can be :get post PUT DELETE
"value": 1.00% //Return the cost ratio, from 1.00% to 8.00%
}

**Comment by webron** [comment]
What you're asking is not possible as JSON doesn't support comments. You can add individual descriptions to each one of the properties though, that's supported today.
