### ISSUE TITLE
Online Editor View issue - doesnt show the nested data objects that it used to show previously

### ISSUE THREAD

**Issue by B-Piyush** [swagger-api/swagger-core#2569]
Looks like the '**online swagger editor**' got some updates recently which are causing issue with the view section. The nested objects are now hidden for some cases (in object definitions and example section of i/o parameters to the methods). It used to show all objects properly in previous versions.

Attached are before and after screenshots of same yaml file.

Methods - I/O Example section - before
![before1](https://user-images.githubusercontent.com/34345576/33722606-7105c242-db38-11e7-9505-e46e6a539757.JPG)
Example section - after
![after1](https://user-images.githubusercontent.com/34345576/33722604-70ece696-db38-11e7-9f65-ad9b0aa87e13.JPG)
Models - Before
![before2](https://user-images.githubusercontent.com/34345576/33722607-71111dfe-db38-11e7-9e10-6ffaab460eed.JPG)
Models - After
![after2](https://user-images.githubusercontent.com/34345576/33722605-70f9291a-db38-11e7-9d80-fbfe08de38ee.JPG)

Please advise and fix.

**Comment by webron** [comment]
Please file the ticket on swagger-editor and follow the issue template.
