### ISSUE TITLE
How to use `@Schema(implementation = ...)` with a parameterized class?

### ISSUE THREAD

**Issue by stiancognite** [swagger-api/swagger-core#2577]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Not sure
| Which Swagger-Core version?       | 3
| Which Java version?               | 8
| Which JAX-RS framework & version? | jaxrs2
 
I have a resource that takes `Data<Something>` as a `@RequestBody` input. How can I set `@RequestBody(content = @Content(schema = @Schema(implementation = ....)))` in this case? `@RequestBody(content = @Content(schema = @Schema(implementation = Data<Something>.class)))` won't work.

Also, how should I create a `@Schema(example = ...)` of a parameterized type? Create one elsewhere, parse it to json, copy that and enter as text here?

**Comment by frantuma** [comment]
You can't use parameterized type in annotation method, but you can either have your request body param of type `Data<Something>`, e.g.:

```
public Response foo(
                @RequestBody(required = true) GenericCategory<User> user) {
```

or define your own class `SomethingData extends Something<Data>`

as for the example, you can provide the example value as a json string, which will get resolved as an object in the resolved spec

**Comment by stiancognite** [comment]
Thank you. (Sorry for responding to this so slowly.)
