### ISSUE TITLE
Question: configurable authorizationUrl (different one per environment)

### ISSUE THREAD

**Issue by nmarasoiu** [swagger-api/swagger-core#2580]
Hi,
I also asked this on the google groups forum but until now I saw no answer there.. I hope it's ok to ask you here as well:
The authorizationUrl from @SwaggerDefinition (securityDefinition) must be a compile time constant in Java/Scala, just because any value of an annotation needs to be evaluated at compilation. However, we may need for a different set of administrators and settings in each env (dev, qa, prod).
Is there a way to take it at runtime e.g. from env vars, so that we have one deployable in all envs, configurable from env vars?
I guess the question is, what alternate configuration means, other than annotations, should we use? Could part of the configuration be done in annotation, and the rest programatically (in an override manner maybe)?
Thank you,
Nicu M

**Comment by frantuma** [comment]
In swagger-core `1.x` you can customize resolved spec by providing a `ReaderListener` implementation, as detailed in https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X#customising-the-swagger-definition. Please close the ticket it this solves your issue.

**Comment by nmarasoiu** [comment]
Hi, authorizationUrl can be configured as part of swagger documentation/annotation of the endpoints (e.g. with Java/Scala annotations in the controller class). Closing.
