### ISSUE TITLE
Question: How can I get swagger to scan ApiModel and ApiModelProperty annotations in entity classes defined in separate JARs?

### ISSUE THREAD

**Issue by darylfoster** [swagger-api/swagger-core#2582]
Swagger-Core 1.5.10
Java 8
JAX-RS 2.0

I have the following two entity classes. `SampleApiEntity` is defined in the same package and JAR as the REST endpoint. `SampleModelEntity` is defined in a separate package and separate JAR. The generated Swagger documentation is not capturing the `ApiModel` and `ApiModelProperty` annotations from the class in the separate package.

The first class is `SampleApiEntity`:

    package my.company.rest;

    import io.swagger.annotations.ApiModel;
    import io.swagger.annotations.ApiModelProperty;
    import org.hibernate.annotations.Type;
    import java.io.Serializable;
    import java.sql.Timestamp;
    import java.util.UUID;
    import javax.persistence.Column;
    import javax.persistence.Entity;
    import javax.persistence.Id;

    @ApiModel (
        value       = "SampleApiEntity",
        description = "This is a sample entity from the Api package."
    )
    @Entity
    public class SampleApiEntity
            implements Serializable
    {
        public SampleApiEntity () {}

        private static final long serialVersionUID = 1L;

        @Column (nullable = false)
        @ApiModelProperty (
            value    = "level",
            required = true
        )
        private Integer   level;
    
        @Column (length = 255)
        @ApiModelProperty (
            value    = "description"
        )
        private String    description;
    
        @Column (nullable = false)
        @ApiModelProperty (
            value    = "time",
            required = true
        )
        private Timestamp time;
    
        @Id
        @Column (
            unique   = true,
            nullable = false
        )
        @Type (type = "pg-uuid")
        @ApiModelProperty (
            value    = "id",
            readOnly = true,
            dataType = "uuid",
            example  = "123e4567-e89b-12d3-a456-426655440000"
        )
        private UUID      sampleApiEntityId;

        public String getDescription ()
        {
            return this.description;
        }

        public Integer getLevel ()
        {
            return this.level;
        }

        public UUID getSampleApiEntityId ()
        {
            return this.sampleApiEntityId;
        }

        public Timestamp getTime ()
        {
            return this.time;
        }

        public void setDescription (String description)
        {
            this.description = description;
        }

        public void setLevel (Integer level)
        {
            this.level = level;
        }

        public void setSampleApiEntityId (UUID sampleApiEntityId)
        {
            this.sampleApiEntityId = sampleApiEntityId;
        }

        public void setTime (Timestamp time)
        {
            this.time = time;
        }
    }

The second class is `SampleModelEntity`:

    package my.company.model;

    import io.swagger.annotations.ApiModel;
    import io.swagger.annotations.ApiModelProperty;
    import org.hibernate.annotations.Type;
    import java.io.Serializable;
    import java.sql.Timestamp;
    import java.util.UUID;
    import javax.persistence.Column;
    import javax.persistence.Entity;
    import javax.persistence.Id;

    @ApiModel (
        value       = "SampleModelEntity",
        description = "This is a sample entity from the Model package."
    )
    @Entity
    public class SampleModelEntity
            implements Serializable
    {
        public SampleModelEntity () {}

        private static final long serialVersionUID = 1L;

        @Column (nullable = false)
        @ApiModelProperty (
            value    = "level",
            required = true
        )
        private Integer   level;
    
        @Column (length = 255)
        @ApiModelProperty (
            value    = "description"
        )
        private String    description;
    
        @Column (nullable = false)
        @ApiModelProperty (
            value    = "time",
            required = true
        )
        private Timestamp time;
    
        @Id
        @Column (
            unique   = true,
            nullable = false
        )
        @Type (type = "pg-uuid")
        @ApiModelProperty (
            value    = "id",
            readOnly = true,
            example  = "123e4567-e89b-12d3-a456-426655440000"
        )
        private UUID      sampleModelEntityId;

        public String getDescription ()
        {
            return this.description;
        }

        public Integer getLevel ()
        {
            return this.level;
        }

        public UUID getSampleModelEntityId ()
        {
            return this.sampleModelEntityId;
        }

        public Timestamp getTime ()
        {
            return this.time;
        }

        public void setDescription (String description)
        {
            this.description = description;
        }

        public void setLevel (Integer level)
        {
            this.level = level;
        }

        public void setSampleModelEntityId (UUID sampleModelEntityId)
        {
            this.sampleModelEntityId = sampleModelEntityId;
        }

        public void setTime (Timestamp time)
        {
            this.time = time;
        }
    }

The only difference between the two classes is that they are defined in separate JAR files. `SampleApiEntity` is packaged in the same JAR as the REST resource class. `SampleModelEntity` is packaged in a separate JAR with other entity classes. The `swagger.yaml` file that is generated contains both classes, but lacks information provided by the `ApiModel` and `ApiModelProperty` annotations for the `SampleModelEntity` class.

Here is what I am seeing in the generated `swagger.yaml` file:

    SampleApiEntity:
      type: "object"
      required:
      - "level"
      - "time"
      properties:
        level:
          type: "integer"
          format: "int32"
          description: "level"
        description:
          type: "string"
          description: "description"
        time:
          type: "string"
          format: "date-time"
          description: "time"
        sampleApiEntityId:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426655440000"
          description: "id"
          readOnly: true
      description: "This is a sample entity from the Api package."
    SampleModelEntity:
      type: "object"
      properties:
        level:
          type: "integer"
          format: "int32"
        description:
          type: "string"
        time:
          type: "string"
          format: "date-time"
        sampleModelEntityId:
          type: "string"
          format: "uuid"

Can someone help me understand why the `ApiModel` and `ApiModelProperty` annotations are not generating output in `swagger.yaml`?

**Comment by frantuma** [comment]
we didn't succeed in reproducing this issue, both with `1.5.10` and latest `1.5.17`, in a jersey2 env; both classes (in same and separate jar) get correctly resolved considering swagger annotation.

It would help if you could provide a test case/project reproducing the issue.

**Comment by darylfoster** [comment]
I have created a test project that reproduces the issue. It appears that the key to reproducing the issue lies in the scope of my dependency declaration in the pom file.

I have a `SampleEntityLibrary` project which defines an artifact called `Sample-model` packaged as a `jar`. This project has my `SampleModelEntity` class which has been annotated with `ApiModel` and `ApiModelProperty`.

I have a separate `SampleApi` project which defines two artifacts:

1. `Sample-rest` - defines REST endpoints for retrieving the `SampleModelEntity` type. It defines a `war` package.

1. `SampleApi-ear` - A deployment package for `Sample-rest`. It defines a deployable `ear` package.

I have included the `Sample-model` artifact as a dependency in the `SampleApi-ear` pom file. As a result, I have labeled the scope of the `Sample-model` dependency as `provided` in the pom file for `Sample-rest`. The `provided` scope seems to be causing the issue.

You can view my projects here:
[SampleEntityLibrary](https://github.com/darylfoster/SampleEntityLibrary)
[SampleApi](https://github.com/darylfoster/SampleApi)

**Comment by darylfoster** [comment]
The key issue is in this file:
[SampleApi/sampleApi/pom.xml](https://github.com/darylfoster/SampleApi/blob/master/sampleApi/pom.xml)

That file includes the following dependency:
```
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>Sample-model</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>
```
Once deployed, it produces the following yaml:
```
definitions:
  SampleModelEntity:
    type: "object"
    properties:
      level:
        type: "integer"
        format: "int32"
      description:
        type: "string"
      time:
        type: "string"
        format: "date-time"
      sampleModelEntityId:
        type: "string"
        format: "uuid"
```
However if I remove the `scope` from the dependency declaration and redeploy, I get the expected yaml:
```
definitions:
  SampleModelEntity:
    type: "object"
    required:
    - "level"
    - "time"
    properties:
      level:
        type: "integer"
        format: "int32"
        description: "level"
      description:
        type: "string"
        description: "description"
      time:
        type: "string"
        format: "date-time"
        description: "time"
      sampleModelEntityId:
        type: "string"
        format: "uuid"
        example: "123e4567-e89b-12d3-a456-426655440000"
        description: "id"
        readOnly: true
    description: "This is a sample entity from the Model package."
```

**Comment by frantuma** [comment]
I would say this is a class loading issue, in your sample it seems you have duplicated swagger-annotations in both ear and war which results in ear lib annotations loaded classes being different from the ones in the ear; adding also swagger-annotations as provided dep in war module would solve the problem:

```
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.10</version>
            <scope>provided</scope>
        </dependency>
```

Please check if this solves your issue, and close ticket if it does.

**Comment by darylfoster** [comment]
That fixed it. Thanks for the help.
