### ISSUE TITLE
Change swagger baseUrl in a microservices environment

### ISSUE THREAD

**Issue by peppa2016** [swagger-api/swagger-core#2584]
We are developing a few spring boot application conforming to microservices architecture. The gateway being used in zuul netflix. We were able to bring up the swagger page for the gateway. The issue is that we would like to change the basePath of one of the microservices application. Currently the basePath is getting picked up from the zuul routes. Something like 
zuul:
  routes:
    foo-services:
      serviceId: foo-services
      path: /foo/**
So the basePath is shown as /foo. But can I change it to only "/"
springBootVersion = '1.5.3.RELEASE'
springfoxVersion = '2.6.1'

Thanks.

**Comment by webron** [comment]
This should be opened on Springfox.
