### ISSUE TITLE
2.0.0 snapshots

### ISSUE THREAD

**Issue by pjfanning** [swagger-api/swagger-core#2589]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Feature
| Which Swagger-Core version?       | 2.0.0 snapshot
| Which Java version?               |
| Which JAX-RS framework & version? |

https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-core/ doesn't have any new 2.0.0 snapshots since Oct 24.
Would it be possible to have new snapshots pushed on a regular basis?

**Comment by frantuma** [comment]
Snapshots are indeed pushed on commit and available in https://oss.sonatype.org/content/repositories/snapshots/io/swagger/core/v3/swagger-core/ due to groupId change.

**Comment by pjfanning** [comment]
Thanks - what I had missed is the artifact group id is now `io.swagger.core.v3`
