### ISSUE TITLE
Swagger API "uses" guava causing class-space versioning issues

### ISSUE THREAD

**Issue by timothyjward** [swagger-api/swagger-core#2590]
The OSGi bundles produced by Swagger indicate that internal dependencies (such as Guava) leak out of the API. This causes a very complicated class space and version conflict issues.

It turns out, however...

Swagger was using an ancient (mid 2012) version of the maven-bundle-plugin. This uses an even older version of bnd to work out what Swagger's OSGi metadata should be. This old version of bnd uses a naive algorithm for calculating uses constraints which often overspecifies, in this case putting constraints on Jackson and Guava which are not needed. This in turn makes Swagger much harder to deploy in OSGi as Guava's versioning policy is not semantic.

Switching to a more modern maven-bundle plugin fixes this.

I originally wanted to look at ways to change 2.x to avoid these uses constraints (by changing the API if possible) when I found that the types aren't actually used in the API. It would therefore be great to see this fix back ported to 1.5.x if possible.

See Pull Request #2587 for a small and low risk fix.

**Comment by frantuma** [comment]
merged #2587, thanks!
