### ISSUE TITLE
swagger-jaxrs io.swagger.jaxrs.config.BeanConfig.setScan() throws exception in reflection of ehcache library and classes when running via -all.jar as classes are missing

### ISSUE THREAD

**Issue by sebawagner** [swagger-api/swagger-core#2597]
**Description**
If you init Swagger using BeanConfig.setScan(true) (see: https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/config/BeanConfig.java#L220) it will throw many exceptions in case you are using generated Beans as response objects. 

See exception below. It fails on those classes as it seems they are .classes_terracotta 

The issue is that certain classes are not packaged into the -all jar. I can unpack the -all jar and indeed classes are missing that are referenced in the project classpath.

**Versions:**
swagger-core version 1.5.13 (I also tried 1.5.17, had same issue, but slight different stack trace)
ehcache version is 2.10.3
CXF version is 3.1.9
 
**Ehcache:**
This error happens every time scan is invoked. 

It obviously has something to do with the way the ehcache library is using some overwrite within their rest-management-private-classpath package. 

However ehcache is a common library for caching and often you can't really prevent it. In the case of CXF if comes automatically, there is no way to exclude it.

**Exception when doing BeanConfig.setScan(true):**
```
2017-12-22 10:27:01,759 14438 WARN [main] [] o.r.Reflections - could not get type for name net.sf.ehcache.management.resource.services.CachesResourceServiceImpl from any class loader
org.reflections.ReflectionsException: could not get type for name net.sf.ehcache.management.resource.services.CachesResourceServiceImpl
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:409)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:433)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:418)
        at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:277)
        at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
        at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
        at my.company.myproject.myapi.MyapiApplication.swagger(MyapiApplication.java:115)
        at my.company.myproject.myapi.MyapiApplication.run(MyapiApplication.java:70)
        at my.company.myproject.myapi.MyapiApplication.run(MyapiApplication.java:30)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:74)
        at io.dropwizard.Application.run(Application.java:89)
        at my.company.myproject.myapi.MyapiApplication.main(MyapiApplication.java:38)
Caused by: java.lang.ClassNotFoundException: net.sf.ehcache.management.resource.services.CachesResourceServiceImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 14 common frames omitted
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        ... 14 common frames omitted
```

**Comment by sebawagner** [comment]
This is an issue with the gradle plugin packaging a fat jar not including certain classes. Not a swagger issue. Application runs fine if the correct JARs are loaded into the classpath.

Thanks for your help

**Comment by viachm** [comment]
Having the same issue, but building an application with Maven:

`INFO  [2018-01-08 20:10:00,837] org.reflections.Reflections: Reflections took 2279 ms to scan 1 urls, producing 35716 keys and 62812 values 
WARN  [2018-01-08 20:10:00,852] org.reflections.Reflections: could not get type for name javax.cache.management.CacheStatisticsMXBean from any class loader
! java.lang.ClassNotFoundException: javax.cache.management.CacheStatisticsMXBean
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
! Causing: org.reflections.ReflectionsException: could not get type for name javax.cache.management.CacheStatisticsMXBean
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
! at org.reflections.Reflections.<init>(Reflections.java:126)
! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276)
! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:287)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:66)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:33)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at com.test.server.ServerApplication.main(ServerApplication.java:84)
WARN  [2018-01-08 20:10:00,853] org.reflections.Reflections: could not get type for name org.springframework.beans.factory.FactoryBean from any class loader
! java.lang.ClassNotFoundException: org.springframework.beans.factory.FactoryBean
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
! Causing: org.reflections.ReflectionsException: could not get type for name org.springframework.beans.factory.FactoryBean
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
! at org.reflections.Reflections.<init>(Reflections.java:126)
! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276)
! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:287)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:66)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:33)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at com.test.server.ServerApplication.main(ServerApplication.java:84)
`
What is interesting, it says **could not get type for name org.springframework.beans.factory.FactoryBean** - I do not use spring at all, I'm using dropwizard.

@sebawagner Do you have some ideas?

**Comment by sebawagner** [comment]
@viachm That is a different class not found "javax.cache.management.CacheStatisticsMXBean". But it usually simply means the class is not in the classpath of your application. So just make sure the Jar and all dependencies are available to the application that runs the swagger command at runtime.

**Comment by viachm** [comment]
Yeap, but conceptually Swagger should not scan all these dependencies, since I've specified to scan only mine resources:
```
swagger:
  resourcePackage: com.test.server.resources
  enabled: true
```
I suspect there is a problem with my configuration, but can't figure out where exactly.

**Comment by sebawagner** [comment]
swagger will also inspect the input and output objects of all methods at run time. That is how it came to try to resolve that class you describe. So actually your package com.test.server.resources => It will have a reference to javax.cache.management.CacheStatisticsMXBean at runtime. It's just not so obvious as application servers enhance beans with caching and other features.

**Comment by viachm** [comment]
@sebawagner Hmm, is there are a way to force Swagger to ignore scatting such a references?

**Comment by sebawagner** [comment]
I don't think so. It is your web app that is the problem. So if any alternative (but you should really rather fix the classpath issue) is to get your Webapp to somehow not use the cached version of the bean. Maybe by simply removing the JAR altogether. But really, it is a web app configuration. Not swagger.

**Comment by viachm** [comment]
Had do downgrade org.reflections with some exclusions. Here is a pom.xml that worked for me:
```xml
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.10</version>
    <exclusions>
        <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>annotations</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.smoketurner</groupId>
    <artifactId>dropwizard-swagger</artifactId>
    <version>1.1.2-1</version>
    <exclusions>
        <exclusion>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by tyagiakhilesh** [comment]
This works for me as well.

```
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-jaxrs</artifactId>
                <version>1.5.18</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.reflections</groupId>
                        <artifactId>reflections</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.reflections</groupId>
                <artifactId>reflections</artifactId>
                <version>0.9.10</version>
            </dependency>
```

Now, I am not sure if my App is problem or reflection is ? I guess `reflection` needs some reflection now.. :-)
