### ISSUE TITLE
Repackage maven dependencies into more meaningful coordinates and document contents of the different dependencies

### ISSUE THREAD

**Issue by PixelBumper** [swagger-api/swagger-core#2610]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  feature request
| Which Swagger-Core version?       | 2.0.0-rc2 ?
| Which Java version?               | all
| Which JAX-RS framework & version? | 2.0.0
 
I have setup a jersey project with the new Swagger Core JAX RS and was struggling a bit to find which dependencies to use.

According to the [project setup tutorial](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-JAX-RS-Project-Setup-2.0.X) I only need to use:
```compile 'io.swagger:swagger-jaxrs2:2.0.0-rc2'```

But the openapi annotations were missing so I ended up adding them with an additional dependency.
```
compile 'io.swagger:swagger-jaxrs2:2.0.0-rc2'
compile 'io.swagger.core.v3:swagger-jaxrs2:2.0.0-rc3'
```
(Is this even the correct way to set it up?)

I had similar issues in the past when setting up the previous version of JAX RS swagger.

IMHO Part of the difficulties in the setup process, stem from the confusing group/artifact ids used and maybe wrong maven coordinates in the setup pages.

I would suggest to remap them to something more meaningful and along the way add a care free all you need dependency if it does not exist yet.
Example:
```
compile 'io.swagger:jax-rs2-all:<version>' // contains all dependencies to run the open api servlet + annotations
compile 'io.swagger:jax-rs2-open-api-servlet:<version>' // contains just the servlet 
compile 'io.swagger:jax-rs2-open-api-annotations:<version>' // contains just the annotations
```

While doing so it would also be nice to have just one common group id as currently it seems like there are 2, namely "io.swagger" and "io.swagger.core.v3".

Since the project is targeting to generate openapi specifications it would probably be nice to take the opportunity to unify everything under the group id "org.openapi"

Since I know this is not something that can be changed over night, it would be nice to at least get a github page, that explains what can be found in which dependency and for what it can be used.

That at least would dissolve the confusion short term.

**Comment by frantuma** [comment]
Version 2.0.0 has recently been released along with a new [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started), which covers dependencies and integration; `swagger-core` group id is now `io.swagger.core.v3` for all modules. Closing ticket, please reopen if it doesn't address your concerns.
