### ISSUE TITLE
the json data generated by  swagger-jaxrs2 lib  always include the models of swagger itself, like Info, Contact, Shema, ..

### ISSUE THREAD

**Issue by lipgnick2017** [swagger-api/swagger-core#2626]
the json data generated by  swagger-jaxrs2 lib  always include the models of swagger itself, like Info, Contact, Shema, ..
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | 2.0.0-rc3
| Which Java version?               | jdk 1.8
| Which JAX-RS framework & version? | jax-rs 2.0
 

the json data generated by  swagger-jaxrs2 lib  always include the models of swagger itself, like Info Object, Contact Object, Shema Object, and so on, all the models for swagger sepecification itself.

But I don't want these model to be shown on my swagger UI page,   I just want my own model to be displayed in the model section of swagger UI, is there a way to hide those swagger models on my swagger UI page?  thanks.

**Comment by lipgnick2017** [comment]
The way to tell swagger which resource class to be scanned is : I pass the instance of my jax-rs Application sub class to BaseOpenApiResource.getOpenApi  method,  so swagger will get all my resource class from the Application instance.

**Comment by lipgnick2017** [comment]
Previously, I was using swagger-jaxrs2 2.0.0-rc1 , it did not any of models of swagger itslef.

**Comment by frantuma** [comment]
Such models shouldn't be resolved, would be resolved only if a registered resource references them.
Can you detail a bit more your setup/environment, and specifically how you bootstrap app and swagger?

There are also quite some fixes in latest `2.0.0-SNAPSHOT` version available in sonatype, which will be included in oncoming release, please switch to that version and see if it changes

**Comment by lipgnick2017** [comment]
Hi , 
 Thank you for the quick reply, following the key classes to bootstrap swagger.
========Application : ===============================
@ApplicationPath("/restapi")
public class RestApplicationv1 extends Application {
    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new HashSet<Class<?>>();

        resources.add(MyTestOpenApiResource.class);
        resources.add(TestResource.class);
        return resources;
    }
=========================================
=====MyTestOpenApiResource=================
@Path("/apidocdata.{type:json|yaml}")
public class MyTestOpenApiResource extends BaseOpenApiResource {
    private static GbmsLogger logger = GbmsLogger.getLogger(GbmsOpenApiResource.class);

    //

    @GET
    @Produces({ MediaType.APPLICATION_JSON, "application/yaml" })
    @Hidden
    public Response getOpenApi(@Context Application app, @Context HttpHeaders headers,
            @Context UriInfo uriInfo, @PathParam("type") String type) throws Exception {
        //generate my own open api by java
        this.setOpenApiConfiguration(Constant.geOASConfig(version));
      //<servletConfig > , I created an inner implementation of ServletConfig interface to pass 
      //my api version as serverlet name,  also provided init param value
        return super.getOpenApi(headers,  <servletConfig >, app, uriInfo, type);
    }
=========================

**Comment by lipgnick2017** [comment]
all the libs for swagger are runtime  dependencies of  swagger-jaxrs2-2.0.0-rc3.jar


animal-sniffer-annotations-1.14.jar
aopalliance-repackaged-2.5.0-b32.jar
commons-lang3-3.6.jar
error_prone_annotations-2.0.18.jar
guava-23.0.jar
j2objc-annotations-1.1.jar
jackson-annotations-2.9.1.jar
jackson-core-2.9.1.jar
jackson-databind-2.9.1.jar
jackson-dataformat-yaml-2.9.1.jar
jsr305-1.3.9.jar
osgi-resource-locator-1.0.1.jar
reflections-0.9.11.jar
slf4j-api-1.7.25.jar
slf4j-log4j12-1.7.22.jar
snakeyaml-1.18.jar
swagger-annotations-2.0.0-rc3.jar
swagger-core-2.0.0-rc3.jar
swagger-integration-2.0.0-rc3.jar
swagger-jaxrs2-2.0.0-rc3.jar
swagger-models-2.0.0-rc3.jar
validation-api-1.1.0.Final.jar

**Comment by frantuma** [comment]
at first look there seems to be nothing wrong, before digging further, can you try with `2.0.0-SNAPSHOT`?

**Comment by lipgnick2017** [comment]
ok, thanks,  I'll try,  let you know the result once it's done.

**Comment by lipgnick2017** [comment]
tried 2.0.0-SNAPSHOT version,  the problem still exists, 
if I roll back to 2.0.0-rc1, the problem dispears

**Comment by frantuma** [comment]
Ok, adding `@Hidden` at class level in `MyTestOpenApiResource` should fix it; API Definition-exposing resources provided by Swagger are excluded by default (by package name), this is not the case for used defined ones, therefore you need to hide from Swagger resolver. Please lmk/close ticket if issue solved

**Comment by lipgnick2017** [comment]
Actually, I tried that before reaching for help,  add the @Hidden to MyTestOpenApiResource ,  originally, the path for the MyTestOpenApiResource  will be displayed on swagger UI, after adding the @Hidden, the path for MyTestOpenApiResource   is hidden, but models for swagger specification still are there. 
Currently, I rolled back to 2.0.0-rc1 in this project,  I'll create another test project to test 2.0.0-rc3 again, will let you know once I get any result, thank you very much,

**Comment by frantuma** [comment]
I have tried to reproduce the issue, but it works ok with latest `2.0.0-SNAPSHOT`, and having `@io.swagger.v3.oas.annotations.Hidden` at class level, like:

```
@Path("/apidocdata.{type:json|yaml}")
@Hidden
public class MyTestOpenApiResource extends BaseOpenApiResource {

    @GET
    @Produces({MediaType.APPLICATION_JSON, "application/yaml"})
    public Response getOpenApi(@Context ServletConfig config, @Context Application app, @Context HttpHeaders headers,
                               @Context UriInfo uriInfo, @PathParam("type") String type) throws Exception {
              
        return super.getOpenApi(headers, config, app, uriInfo, type);
    }
}
```

with the same application subclass in a jersey2 environment.

Possibly if not already done, use `2.0.0-SNAPSHOT` with `Hidden` at class level

(also not sure if maybe you're updating openApi via the config in `this.setOpenApiConfiguration(Constant.geOASConfig(version));`, I guess not)

**Comment by lipgnick2017** [comment]
I tried again in a new teset project with 2.0.0-rc3 +@Hidden,  yes, it works,  thank you very much,
