### ISSUE TITLE
@XmlElement(name="myName") not honored for fields starting with "is"

### ISSUE THREAD

**Issue by Treppenhouse** [swagger-api/swagger-core#2635]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       |  1.5.13, 2.0.0-rc2
| Which Java version?               | 1.8
| Which JAX-RS framework & version? | Jersey 2.25.1
 

I have a model object that looks like this (unrelated parts are left out):

```
@XmlAccessorType(XmlAccessType.FIELD)
public class MySuperClass {

}

class MyClass extends MySuperClass {

  @XmlElement(name="beerDrink")
  private String isotonicDrink;

  @XmlElement(name="sugarDrink")
  private String softDrink;

}

```
I believe the class hierarchy is not important but I'll include it here anyway. 
My variable is named ```isotonicDrink``` but when e.g. serializing it to JSON or when looking at my model via swagger UI I would like it to be displayed as ```beerDrink```. 

Now, serializing to JSON works perfectly (I am using Jackson).
However, when looking at this model in my swagger.json or in the "Model" tab in the Swagger UI, the variable is still named ```isotonicDrink```. Renaming ```softDrink``` to ```sugarDrink``` is not a problem though! None of my other fields made any problems, only isotonicDrink. And I didn't even use a fancy format (like underscore). That is when I got really confused.

Now, after some debugging I found the issue #415 where the following hack (d183d8cd0f735fc18f5a50dcd52e2076da69b5df) was introduced in the class ```ModelResolver#resolve(JavaType, ModelConverterContext, Iterator)```:
```
            // hack to avoid clobbering properties with get/is names
            // it's ugly but gets around https://github.com/swagger-api/swagger-core/issues/415
            if (propDef.getPrimaryMember() != null) {
                java.lang.reflect.Member member = propDef.getPrimaryMember().getMember();
                if (member != null) {
                    String altName = member.getName();
                    if (altName != null) {
                        final int length = altName.length();
                        for (String prefix : Arrays.asList("get", "is")) {
                            final int offset = prefix.length();
                            if (altName.startsWith(prefix) && length > offset
                                    && !Character.isUpperCase(altName.charAt(offset))) {
                                propName = altName;
                                break;
                            }
                        }
                    }
                }
            }
```

After setting a breakpoint to the last line, I realized that this "hack" actually reverts my renaming and sets the propName from ```beerDrink``` (which was correct!) back to ```isotonicDrink```! All just because my variable starts with the prefix "is".

Please note, that I explicitly set the ```@XmlAccessorType(XmlAccessType.FIELD)```.

Furthermore, it seems there is even another open issue that showed some shortcomings with this hack: #2332 so it would be very helpful if you were to revise this code section.

**Comment by JohneDoe** [comment]
@XmlElement(name = "MyPrOperTyName")
@XmlAttribute(name = "MyPrOperTyName")

should work like
@Schema(name="MyPrOperTyName")

**Comment by frantuma** [comment]
At the moment support for such a case requires providing a `@JsonProperty("name")` (updated in #2730 and #2731) or `@ApiModelProperty(name = "name")` (or equivalent `@Schema` in 2.0), as inferring the name solely from JAXB annotations and env would require quite complex changes. See also [related tests](https://github.com/swagger-api/swagger-core/pull/2731/files#diff-60138ce8088446f0f83e3063f53d2a99R9)
