### ISSUE TITLE
$ref property is missing in callback.java (Open API 3.0)

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-core#2638]
Hi team,

Unable to refer a callback which is available in the component because $ref property is missing in the callback.java.

All the other models in the components like schema, ApiResponse, Link etc contains $ref.

Expected Behavior:
$ref should be added

Thanks,
Mohammed

**Comment by ymohdriz** [comment]
Hi team,

Raised a PR for this issue - https://github.com/swagger-api/swagger-core/pull/2834

Thanks,
Mohammed

**Comment by frantuma** [comment]
implemented in #2882
