### ISSUE TITLE
Not able to add a newline to swagger output

### ISSUE THREAD

**Issue by supercr7** [swagger-api/swagger-core#2642]
Hi,  I am using `swagger-jersey2-jaxrs` version `1.5.15`. I added a description to a header using `@SwaggerDefinition` annotation and tags (as the description parameter is now deprecated). 

The code goes like:
```
@Api(tags = { "Hello World" }) 
@SwaggerDefinition(tags = { @Tag(name = "Hello World", 
                            description = "Description about world: " + "  \n" +    
                             "1. Hello " + "\n" +     
                             "2. World " + "<br>"   )})
```

By using this, I was able to add a description to the "Hello World" header. 

My question is how should I add a newline for every point. I tried the following but failed:

1. Adding `"\n"` or `"<br>"` to string. \n" doesn't reflect a newline while `"<br>"` just adds the string `"<br>"` to the string that is rendered.
2. I tried to use System.lineSeparator() and System.getProperty("line.separator") as well but that gives the error `The value for annotation attribute Tag.description must be a constant expression`.

Swagger shows a newline when the Point 1 above is used when using the notes parameter for the other annotations (doesn't work with @Api), any workaround to using that instead to get the newline?

Any suggestion is welcome, thanks in advance! :)

(From my SO question: https://stackoverflow.com/questions/48536934/add-a-newline-to-swagger-output)

**Comment by webron** [comment]
You're not able to see the new line where?

**Comment by supercr7** [comment]
Hi @webron, thanks for the reply. I was not able to see a newline in the description. It's probably a swagger-ui version issue, as pointed out in the SO thread as well. I am using an earlier version and this issue might be because of that.
