### ISSUE TITLE
Central maven release is out of sync with GitHub Wiki documentation

### ISSUE THREAD

**Issue by FuweiChin** [swagger-api/swagger-core#2648]
The latest swagger version in central maven repository is 2.0.0-rc2, but the latest wiki swagger 2.x documentation is written for swagger 2.0.0-rc4.

The problem is that v2.0.0-rc4 and 2.0.0-rc2 use different annotation APIs, I cannot get started due to lack of old documentation/new release.

I'm trying to checkout project swagger-core v2.0.0-rc4 but actually it's a SNAPSHOT, so is there a documentation revision for 2.0.0-rc2, or any plan to release 2.0.0-rc4 to central maven repository?

**Comment by frantuma** [comment]
Actually it's more the other way around: while rc2 is not released to maven repo, 2.0.0-rc4 is:  
https://search.maven.org/#artifactdetails%7Cio.swagger.core.v3%7Cswagger-core%7C2.0.0-rc4%7Cbundle

as for the wiki, it's indeed targeting rc2 and still a bit outdated, but differences with rc4 aren'tmajor; it' currently being updated and will be online soon.

**Comment by FuweiChin** [comment]
Sorry, it my fault. Now the problem is gone.
I didn't realized that groupId of artifact `swagger-jaxrs2` was changed from `io.swagger` to `io.swagger.core.v3` since version `2.0.0-rc3`.
