### ISSUE TITLE
@ApiModel's properties 'value' on different Class must be unique ?

### ISSUE THREAD

**Issue by misselvexu** [swagger-api/swagger-core#2657]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Bug?
| Which Swagger-Core version?       | 2.6.1
| Which Java version?               | 1.8.0_91
| Which JAX-RS framework & version? | SpringBoot 1.5.9.RELEASE
 
Example: 

```java
/**
     * Example Module One
     */
    @ApiModel(
            value = "MyModule",
            description = "ModuleOne"
    )
    public static class ModuleOne {
        // ....
    }

    /**
     * Example Module Two
     */
    @ApiModel(
            value = "MyModule",
            description = "ModuleTwo"
    )
    public static class ModuleTwo {

    }


    // ----------- Controller ----------
    @ApiOperation(value = "/post" ,httpMethod = "POST")
    @PostMapping(value = "post")
    public String post(
            @ApiParam(value = "Request Body")
            @RequestBody
            ModuleTwo request
    ) {

        return null;
    }

```

Swagger Web

> Parameters `request` reference to Module -> `ModuleOne` class

Why ??

But when use different `value` on `@ApiModel` , then will be right .

-EOF-

**Comment by webron** [comment]
You're not using swagger-core, you're using springfox. Please file the ticket on that project.
