### ISSUE TITLE
@ApiParam example and examples have no effect on swagger-ui

### ISSUE THREAD

**Issue by dominicE** [swagger-api/swagger-core#2658]
We are using latest swagger jaxrs 1.5.18 (with Java 8)  and latest swagger-ui 3.10.0 for our documentation.

We need examples in our documentation for parameters but it looks like that swagger-core generates only x-example params in documentation which swagger-ui is not able to read at the moment.

We tried example and examples in @ApiParam but none of them generates example params.

Is there any bug, are we doing something wrong or is swagger-core not able to generate example values for parameters?

In #2203 there was a similar problem

Thank you

**Comment by webron** [comment]
This is not implemented in Swagger-UI 3.X. See https://github.com/swagger-api/swagger-ui/issues/2874.
