### ISSUE TITLE
@ApiOperation with responseClass as List<T>

### ISSUE THREAD

**Issue by CeccoCQ** [swagger-api/swagger-core#266]
Hi,

how can I set responseType attribute of @ApiOperation annotation as List of objects?

**Comment by vvicario** [comment]
Hi, I'm using  responseContainer = "List", but on swagger UI is showing List[$ObjectDesc]. any suggestion? the same case when I tried to use responseContainer="Array"

**Comment by webron** [comment]
@vvicario - please open a separate issue if you have a problem.
