### ISSUE TITLE
Bug: Cannot access YAML: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by denny99** [swagger-api/swagger-core#2661]
I am trying to use swagger-core for my JAX RS API, but when trying to access the openapi.yaml file (In my case http://localhost:8080/api/openapi.yaml) i'm getting the following error: 
`java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;`
The API itself is working as expected. Am i missing something or is this a bug?

**Technology**
JEE 8
Glassfish 5
JAX-RS 2.26
Swagger-jaxrs2 2.0.0-rc4

**Stacktrace**
[stacktrace.txt](https://github.com/swagger-api/swagger-core/files/1720588/stacktrace.txt)
**POM.xml**
[pom.txt](https://github.com/swagger-api/swagger-core/files/1720585/pom.txt)
**web.xml**
[web.txt](https://github.com/swagger-api/swagger-core/files/1720598/web.txt)

**Comment by denny99** [comment]
I finally found the solution.
Glassfish has its own Guava Version which is not compatible with Swagger.

To fix it:
Create an glassfish-web.xml
And add <class-loader delegate="false"/>

**Comment by peteclark3** [comment]
@denny99 add what?  Seeing this issue too...

**Comment by denny99** [comment]
Weird. It seems i've forgot to add the xml code or it got deleted?
The Glassfish xml should contain this option:
`<glassfish-web-app>
    <class-loader delegate="false"/>
</glassfish-web-app>`

**Comment by vikrantk365** [comment]
I'm using spring boot with jersey.
I got the same error with the latest version of guava.
I could see that older version was clearly not getting added to the classpath.
So I tried multiple versions of guava. And the version that worked was `com.google.guava:guava:24.1-jre` ( `<= 24.1-jre`).
