### ISSUE TITLE
swagger-models 2.0.0 exports wrong packages

### ISSUE THREAD

**Issue by RosenbeF** [swagger-api/swagger-core#2663]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | 2.0.0
| Which Java version?               | n/a
| Which JAX-RS framework & version? | n/a
 

In the `swagger-core/modules/swagger-models/pom.xml` the `maven-bundle-plugin` exports the packages `io.swagger.oas.models...`, yet the actual packages are named `io.swagger.v3.oas.models...` (the **.v3** is missing fom the pom). 
This produces wrong bundle information and makes the bundle unusable in an OSGi runtime.

**Comment by frantuma** [comment]
Thanks for reporting this; it should be fixed in #2664 and `2.0.0-SNAPSHOT` available in sonatype and in oncoming release. Please reopen if you're still experiencing issues.
