### ISSUE TITLE
ApiListingResource.getListing method is not recognized as valid Java method annotated with @HttpMethod.

### ISSUE THREAD

**Issue by roxanaghenea** [swagger-api/swagger-core#2673]
Hi, 
I'm using Swagger with Jersey Jax-RS and I'm receiving the following error when I try to deploy the application:

:com.sun.jersey.api.container.ContainerException:Method, public javax.ws.rs.core.Response io.swagger.jaxrs.listing.ApiListingResource.getListing(javax.ws.rs.core.Application,javax.servlet.ServletConfig,javax.ws.rs.core.HttpHeaders,javax.ws.rs.core.UriInfo,java.lang.String), annotated with GET of resource, class io.swagger.jaxrs.listing.ApiListingResource, is not recognized as valid Java method annotated with @HttpMethod.

Do you know what the fix might be for this issue?

I'm using swagger-jaxrs-1.5.6,   as our Jersey version is 1.1.x.  
Could it be that the fix for the problem was merged in a later version?

I've followed the steps on this page for setting up Swagger: https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-1.X-Project-Setup-1.5#using-a-custom-application-subclass

Thank you!

**Comment by webron** [comment]
Try updating to 1.5.18 first.

**Comment by roxanaghenea** [comment]
Thanks! I tried using this version but it seems our compiler is too old to support it.

**Comment by webron** [comment]
Which Java version do you use?

**Comment by roxanaghenea** [comment]
I'm using Java 7.

**Comment by roxanaghenea** [comment]
When I try to deploy the application the following error comes up: 
       Caused By: java.lang.UnsupportedClassVersionError: io/swagger/jaxrs/config/DefaultJaxrsConfig : Unsupported major.minor version 51.0.

**Comment by webron** [comment]
Hmm, that shouldn't be the case. 1.5.6 is fairly old though, can you try any of the newer versions first?

**Comment by roxanaghenea** [comment]
Sorry, I just checked again and we are using Java version 1.6..
I tried with all the swagger versions from 1.5.11 upward and the problem is the same.

While for versions 1.5.6 - 1.5.10 the initial problem appears, with the getListing method.

I suppose in this case we have to wait until we upgrade to a newer Java version?

**Comment by webron** [comment]
1.6 has been EOL'ed years ago. So has 1.7. We don't officially support 1.6 anymore, and version 2.0 of swagger-core supports Java 1.8 and above only.

**Comment by roxanaghenea** [comment]
Ok, thank you.
