### ISSUE TITLE
Incorrect date format when in response object 

### ISSUE THREAD

**Issue by ghsatpute** [swagger-api/swagger-core#2680]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Bug
| Which Swagger-Core version?       | 2
| Which Java version?               | 8.0

 ### Demonstration API definition
From my API I'm returning a DTO which looks like below 

```
class ResponseDTO  {
     Date CreatedOn;
     Date ModifiedOn;
}
```

If I look on the swagger UI, I see this
![image](https://user-images.githubusercontent.com/3480767/36438714-b692e96e-1690-11e8-869e-1d6867285bb1.png)

Here, the actual response sent by the server is in long format (number of milliseconds since 1970). But the swagger is showing Date format as `"ModifiedOn": "2018-02-20T17:23:58.907Z"`. Which is kind of misleading. 

### Expected Behavior
`"ModifiedOn": "1519147559685"`
Or something like this

**Comment by webron** [comment]
That's what 'date' is defined as. If you need it to be in a `long` format, you need to specify it using the annotations.

**Comment by ghsatpute** [comment]
I tried that using writing annotations
```
	@ApiModelProperty(value = "Start time of launch", required=true, dataType = "long")
	private Date createdOn;
```
I'm getting the same output as above.

Am I missing something?

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by thiagoarrais** [comment]
Bump: this is also showing up in the [`java-jersey2-resourceinit` sample][link_to_branch] (2.0 branch).

## Steps to reproduce

1. Run said sample as per instructions
2. Go to Swagger-UI at http://localhost:8002
3. Check example value for route `GET /sample/store/order/{orderId}`:

![Captura de tela de 2019-05-29 15-27-23](https://user-images.githubusercontent.com/3014/58581677-8435d780-8226-11e9-8681-f06be2d41f08.png)

4. Check that schema says that the type for `shipDate` is a date-time string:

![Captura de tela de 2019-05-29 15-27-37](https://user-images.githubusercontent.com/3014/58581694-8bf57c00-8226-11e9-95fd-b390c02a41c6.png)

5. Make a sample request for order 1
6. The API returns a long value for `shipDate`, breaking spec:

![Captura de tela de 2019-05-29 15-28-16](https://user-images.githubusercontent.com/3014/58581710-91eb5d00-8226-11e9-9a3c-f9ff002e5f92.png)

[link_to_branch]: https://github.com/swagger-api/swagger-samples/tree/2.0/java/java-jersey2-resourceinit

## Suggested fix

In my opinion, either `java.util.Date` should be mapped to `int64` on the spec or it should somehow be output in RFC 3339 format to be [spec compatible][date_spec].

[date_spec]: https://swagger.io/docs/specification/data-models/data-types/#string

**Comment by frantuma** [comment]
in Swagger Core 2.x there are a few alternatives (sample has been updated with option 3):

1. annotate your property with `@Schema(type = "integer", format = "int64")`
2. customize swagger by adding the following in any bootstrap code

```
PrimitiveType.customExcludedClasses().add(Date.class.getName());
PrimitiveType.customClasses().put(Date.class.getName(), PrimitiveType.LONG);
```

3. depending on the environment, configure its serialization of requests and responses not to use timestamps, e.g. in jersey2:

```
@Provider
    public class ObjectMapperContextResolver implements ContextResolver<ObjectMapper> {

        private final ObjectMapper mapper;

        public ObjectMapperContextResolver() {
            this.mapper = createObjectMapper();
        }

        @Override
        public ObjectMapper getContext(Class<?> type) {
            return mapper;
        }

        private ObjectMapper createObjectMapper() {
            ObjectMapper mapper = new ObjectMapper();
            mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
            return mapper;
        }
    }
```

```
register(new ObjectMapperContextResolver());
```

closing ticket, please reopen if you're still experiencing issues

**Comment by thiagoarrais** [comment]
Thanks! Please consider making that default behaviour.
