### ISSUE TITLE
@ApiParam inheritance is not working

### ISSUE THREAD

**Issue by thomaszbz** [swagger-api/swagger-core#2690]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           | Could be both. Decide for yourself.
| Which Swagger-Core version?       | Springfox 2.7.0, Swagger 1.5.13 
| Which Java version?               | 8

I have an interface which a controller implementation inherits from. The interface looks like this:

```
	ResponseEntity<SomeDto> createInstance(
			UriComponentsBuilder uri,
			@ApiParam(value = "MyDescription", required = true)
			@PathVariable("id") Integer theId);
```

However, the ApiParam does not make it into swagger-ui. More precisely, "MyDescription" is not shown in swagger-ui unless I put that into the controller. Shouldn't this be fixed in 1.5.10 already via #1746 ?

**Comment by webron** [comment]
If you're using Springfox, the ticket should be opened there.
