### ISSUE TITLE
allow access to swagger.json file to specific users

### ISSUE THREAD

**Issue by tpruthi** [swagger-api/swagger-core#2701]
Hi Team,
I am using swagger 2 with jersey 2 .
Is there any way to restrict access to swagger.json file for specific users. Currently the swagger.json file is accessible publicly.

**Comment by webron** [comment]
The swagger.json is exposed via a regular jax-rs endpoint. You can write and/or apply any security filter on top of that to control access.

**Comment by tpruthi** [comment]
Thanks @webron . that solved the issue.
