### ISSUE TITLE
Importing Swagger definition problem in Ready API

### ISSUE THREAD

**Issue by tpruthi** [swagger-api/swagger-core#2714]
Dear Team

i am using hashmap as one of APIModelProperty. Following swagger definition is generated for the same
"metaData": {
		      "type": "object",
		      "additionalProperties": {
						"type": "string"
					}
			}
But when i import the swagger json file in Ready API, it shows the following request 
{
    "metaData" : {
      "key" : "key",
      "value" : "string"
    }
  } 
instead it should show the following
{
    "metaData" : {
      "key" : "value"
    }
  } 

What could be reason for this

**Comment by webron** [comment]
@tpruthi - this is specific to Ready!API - please contact their support to get assistance with this issue.
