### ISSUE TITLE
[2.0.0] Support of @Extension and @ExtensionProperty

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-core#2720]
In the [@Extension section](https://github.com/swagger-api/swagger-core/wiki/Annotations-2.X#extension) of wiki page _Annotations 2.X_ I could read that `@Extension` and `@ExtensionProperty` are not supported by `2.0.0-rc3`.

I did following experiment with the [`/java/java-jersey2-minimal`](https://github.com/swagger-api/swagger-samples/tree/2.0/java/java-jersey2-minimal) example from the `swagger-samples` repository (on the `2.0` branch). I added this code on the `getPetById` method :

```
  @GET
  @Path("/{petId}")
  @Operation(
          summary = "Find pet by ID",
          description = "Some description ...",
          extensions = {
                  @Extension(properties = {
                          @ExtensionProperty(name = "custom-extension", value = "xxx")
                  })
          },
          responses = {
                  @ApiResponse(description = "returns the corresponding Pet", content = @Content(schema = @Schema(implementation = Pet.class))),
                  @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
                  @ApiResponse(responseCode = "404", description = "Order not found")
          }
  )
  public Pet getPetById(@PathParam("petId") Long petId) throws io.swagger.sample.exception.NotFoundException {
    //...
  }
```

With this annotation in the code, when I asked for the corresponding spec using `http://localhost:8002/sample/openapi.yaml`, I get the expected result:

```
  /sample/pet/{petId}:
    get:
      summary: Find pet by ID
      description: Some description ...
      operationId: getPetById
      parameters:
      - name: petId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: returns the corresponding Pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
        400:
          description: Invalid ID supplied
        404:
          description: Order not found
      x-custom-extension: xxx

```

The example is currently using `io.swagger.core.v3:swagger-annotations:2.0.0-SNAPSHOT`.

This means that `@Extension` are now supported. Or did I miss something?

**Comment by frantuma** [comment]
Extensions are indeed supported in latest `2.0.0-SNAPSHOT` available in sonatype and coming soon release (along with new wiki)

**Comment by jmini** [comment]
Nice to know. Thank you.
