### ISSUE TITLE
Wrong value type in @ExtensionProperty

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-core#2723]
Version 3.0.1 specify the type of vendor extensions that can be used ([Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#specificationExtensions)):

> The value can be `null`, a primitive, an array or an object. Can have any valid JSON format value.

For the moment, the java annotation `@io.swagger.v3.oas.annotations.extensions.ExtensionProperty` supports only `String` type value.

---

My use case is to store an array of string as value:

This is well supported by the Swagger Editor. Yaml input example:
```
paths:
  /sample/pet:
    get:
      operationId: updatePet
      responses:
        default:
          description: default response
      x-custom: 
         - xxx
         - yyy
```

Preview:

<img width="419" alt="Extensions preview in Swagger Editor" src="https://user-images.githubusercontent.com/1222165/37815384-dff33138-2e6e-11e8-95ba-b00477b597a0.png">

An other example can be seen in the Stripe specification [spec3.json](https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json):

```
        "x-expandableFields": [
          "business_logo",
          "decline_charge_on",
          "external_accounts",
          "legal_entity",
          "payout_schedule",
          "tos_acceptance",
          "verification"
        ],
```

---

What do you think?

Could `value()` type be changed to `Object` in `@ExtensionProperty`

**Comment by frantuma** [comment]
Annotations don't support `Object` as field type, however #2725 introduces support for `parseValue` boolean field of `@ExtensionProperty` allowing to achieve what you need. It's available in latest `2.0.0-SNAPSHOT` (on sonatype) and in coming soon release.

For your use case you would do something like:

```
@Operation(extensions = {
    @Extension(properties = {
            @ExtensionProperty(name = "custom", value = "[\"xxx\", \"yyy\"]", parseValue = true)
    })
})
public Response updatePet() {...}
```

**Comment by jmini** [comment]
Thank you for the link to the PR. 

I have searched only for issues mentionning `ExtensionProperty` I could have looked in the PR as well.

**Comment by frantuma** [comment]
Actually PR has been triggered by your ticket, you wouldn't have found it before..

**Comment by donaltuohy** [comment]
Hello @frantuma I have been looking at this problem for some time and just came across this issue. I'm just wondering would it be possible to add this code change to the 1.6 version which supports v2 OpenAPI. We need the parseValue functionality but it's only available for the v3 OpenAPI: https://github.com/swagger-api/swagger-core/blob/v1.6.0/modules/swagger-annotations/src/main/java/io/swagger/annotations/ExtensionProperty.java
