### ISSUE TITLE
@FormParam produces invalid output

### ISSUE THREAD

**Issue by taroquu** [swagger-api/swagger-core#2728]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | 2.0.0-rc2
| Which Java version?               |1.8u152
| Which JAX-RS framework & version? | jax-rs2 2.0.0-rc2
 
When using @FormParam in a method, the generated spec produces an "in" value of "form"
```
	@POST
	@Operation
	SomeResponse doSomething(@FormParam("someInput") String someInput);
```
Would produce parameters in the generated spec that looks like this:
```
"parameters":[
               {
                  "name":"someInput",
                  "in":"form",
                  "schema":{
                     "type":"string"
                  }
               }]
```

Which fails when using the spec in swagger editor with the following:

```
should be equal to one of the allowed values
allowedValues: path, query, header, cookie```

**Comment by frantuma** [comment]
`@FormParam` support has been fixed in latest `2.0.0-SNAPSHOT` available on Sonatype and in coming soon release; please notice the naming/package change since `rc2` (see #2485).

The outcome of your example would look like:

```yaml
...
post:
      operationId: doSomething
      requestBody:
        content:
          '*/*':
            schema:
              type: object
              properties:
                someInput:
                  type: string
...
```

Closing ticket, please reopen if you are still experiencing issues
