### ISSUE TITLE
Different @JsonSetter vs @JsonGetter breaks Swagger example model

### ISSUE THREAD

**Issue by iKrushYou** [swagger-api/swagger-core#2733]
Swagger version 2.7.0
Java 1.8.0

I currently have an API mapping:

```
    @RequestMapping(value = "/test", method = RequestMethod.GET)
    public List<TestObject> reportsTest() {
        return new ArrayList<>();
    }
```

and TestObject is defined as:
```
    public class TestObject {

        private String var1;

        public TestObject() {
        }

        @JsonGetter("var")
        public String getVar1() {
            return var1;
        }

        @JsonSetter("var")
        public void setVar1(String var1) {
            this.var1 = var1;
        }
    }
```

Everything works as expected, the Swagger UI docs example model looks good:

![image](https://user-images.githubusercontent.com/1500721/38048493-84e20d22-3293-11e8-973e-da2f6d521594.png)

Now, if I change the @JsonGetter to something else (not matching the @JsonSetter) because I want the serialization to be mapped differently than the input like so:
```
    public class TestObject {

        private String var1;

        public TestObject() {
        }

        @JsonGetter("var")
        public String getVar1() {
            return var1;
        }

        @JsonSetter("newvar") // <-- change made here
        public void setVar1(String var1) {
            this.var1 = var1;
        }
    }
```

The example model no longer works and I'm stuck with this:
![image](https://user-images.githubusercontent.com/1500721/38048623-e2c768d8-3293-11e8-825f-c40fd16e9e35.png)

Is there a workaround for this? I've tried setting @JsonProperty on the variable definition but that didn't work either..

**Comment by webron** [comment]
You're using springfox, not swagger-core. Please file the ticket there.
