### ISSUE TITLE
decorateOperation is never called

### ISSUE THREAD

**Issue by taroquu** [swagger-api/swagger-core#2748]
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  Bug
| Which Swagger-Core version?       | 2.0.1-SNAPSHOT
| Which Java version?               | 8 u161
| Which JAX-RS framework & version? |  2.1 - resteasy 3.5.0
 
I've been trying to create an extension this morning for a couple of custom annotations. I've noteced however that decorateOperation() from io.swagger.v3.jaxrs2.ext.OpenAPIExtension is never being called. 

An ealier version of Reader https://github.com/swagger-api/swagger-core/blob/f19529d630514f829f0a492568625f8c9c9171f5/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L999 used to call it. But this no longer seems to exist for 2.0.1

**Comment by frantuma** [comment]
OpenAPIExtension support has been reintroduced in #2759 (`2.0.1-SNAPSHOT` available in sontype); however possibly you can achieve the same result by using a [filter](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters)
