### ISSUE TITLE
Please update Wiki guide

### ISSUE THREAD

**Issue by kimtiago** [swagger-api/swagger-core#2749]
Hi, there's a wiki error in following guide

https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-configuration

**WRONG**
For example, adding **io.swagger.jaxrs2.integration.resources** to Jersey 2 container servlet/filter jersey.config.server.provider.packages init param is by itself sufficient to integrate Swagger and have it scan and expose resolved spec.

**RIGHT**
For example, adding **io.swagger.v3.jaxrs2.integration.resources** to Jersey 2 container servlet/filter jersey.config.server.provider.packages init param is by itself sufficient to integrate Swagger and have it scan and expose resolved spec.

**Comment by frantuma** [comment]
Thanks for reporting this! fixed in latest version.
