### ISSUE TITLE
Swagger reader (i guess) merges valid jax-rs paths together

### ISSUE THREAD

**Issue by soberich** [swagger-api/swagger-core#2751]
Hi,

I have a Application class and jax-rs endpoints
```
@ApplicationPath("rest")
```
endpoints
```
@Path("user")
```
which is a valid way to get resulting path as "rest/user" according to jax-rs docs
unfortunately
the resulting .yaml file states ''/restuser/...'  everywhere
NO configuration done to swagger at all, just 2 dependencies added (initializer and jaxrs2)
and after scanning the result is that.

**Comment by webron** [comment]
This is using which version of swagger-core?

**Comment by frantuma** [comment]
fixed in #2758 (including and replacing #2746)
