### ISSUE TITLE
[Wiki| Link not correct

### ISSUE THREAD

**Issue by Foso** [swagger-api/swagger-core#2760]
Hi,
on [https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#where-to-start](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#where-to-start) the link to swagger-codegen is not correct because it's ending with an "]"

**Comment by frantuma** [comment]
Thanks for reporting this! Should be fixed now
