### ISSUE TITLE
Example value in ApiModelProperty not showing the string value with quotes

### ISSUE THREAD

**Issue by ouya2** [swagger-api/swagger-core#2772]
Hello,
We are using swagger-core, jaxrs. version 1.5.14 @example have issues when it is defined example of a model property that is only digits, e.g:

`@ApiModelProperty(example = "484799")
 private String bsb;`

Produces:

`"bsb": 484799,`

is it possible to make it produce this:

`"bsb": "484799",`

Following are what I have tried so far:

1. Put the escape character for double quote (example = "\\"484799\\"")
2. Use dataType = "java.lang.String" with example parameter
3. Leave extra space in the example value, since it adds double quotes when i insert a alpheric character in the example.

Thanks in advance

 
| Q                                 | A
| --------------------------------- | -------
| Bug or feature request?           |  bug
| Which Swagger-Core version?       | 1.5.14
| Which Java version?               | 1.8
| Which JAX-RS framework & version? |

**Comment by Tejansh** [comment]
To add to this issue, I can see that you are using Jackson for deserialization which is identifying the data type based on the value. However, we would have expected perhaps another property to denote the data type explicitly that we expect in the sample response or if you can allocate the value based on the data type of the variable (ideal), the annotation is used upon.

**Comment by ouya2** [comment]
So what exactly should i do to work around this? The dataType parameter seems being ignored.

**Comment by d0x** [comment]
Even if it is an Springfox issue, you can fix it by annotating the example value with `'` **within** the string.
![image](https://user-images.githubusercontent.com/2202723/125479488-8b8d19ad-5e12-4f1c-a264-55784f27bce9.png)

This will render a proper string in the swagger ui:

![image](https://user-images.githubusercontent.com/2202723/125479667-21098e49-d8ca-4673-90de-10c80ab56e6a.png)
