### ISSUE TITLE
I use a @PathVariable but set required is false in SpringMVC,at the time I post a request by swagger ui and don't set the parameter,the server got a "undefined" string value.

### ISSUE THREAD

**Issue by chenqimiao** [swagger-api/swagger-core#2776]
Q | A
-- | --
Bug or feature request? | Bug
Which Swagger-Core version? | 1.5.14
Which Java version? | 8
Which JAX-RS framework & version? | -

I use a @PathVariable but set required is false in SpringMVC,at the time I post a request by swagger ui and don't set the parameter,the server got a "undefined" string value.

eg.

<pre><code>
    @GetMapping("/test/{id}")
    @ApiOperation("test")
    @ApiImplicitParams({@ApiImplicitParam(name = "id", value = "test_id", paramType = "path")})
    public String test(@PathVariable(required = false) String id) {
        return id;
    }
</code></pre>

<p>when I use swaager ui post request and don't set the "id" value, I got the request url which is "https://localhost:8443/api/v1.0/monitor/test/undefined"。I hope to get the url is "https://localhost:8443/api/v1.0/monitor/test"</p>

**Comment by webron** [comment]
This is technically an issue that should be opened with Springfox. However, the specification itself doesn't support optional path parameters, so your API cannot be represented with the spec.
