### ISSUE TITLE
Add @NotBlank @NotEmpty support for generated API definition (Bean Validation 2.0)

### ISSUE THREAD

**Issue by soberich** [swagger-api/swagger-core#2778]
..so, these to be treated as @NotNull treated now -> like those annotated params REQUIRED.

Otherwise it is a bit annoying and a performance overhead to add both 
```
@NotNull
@NotEmpty
String s;
```
on all `String`s let's say.

**Comment by eduzol** [comment]
hi @frantuma  is there a workaround?

**Comment by frantuma** [comment]
support for `NotEmpty` and `NotBlank` added in #2876. Closing ticket, please reopen if you're still experiencing issues

**Comment by DavidTomic** [comment]
Hi, I am using the version 2.9.2 and `@NotBlank` and `@NotEmpty` doesn't work.

`@NotNull` does work.

```
	implementation 'io.springfox:springfox-swagger2:2.9.2'
	implementation 'io.springfox:springfox-swagger-ui:2.9.2'
	implementation 'io.springfox:springfox-bean-validators:2.9.2'
```

**Comment by nikolaiev** [comment]
As a fix add next component to your Spring context 
`import com.google.common.annotations.VisibleForTesting;
import com.google.common.base.Optional;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import springfox.bean.validators.plugins.Validators;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.schema.ModelPropertyBuilderPlugin;
import springfox.documentation.spi.schema.contexts.ModelPropertyContext;

import javax.validation.constraints.NotBlank;

import static springfox.bean.validators.plugins.Validators.annotationFromBean;
import static springfox.bean.validators.plugins.Validators.annotationFromField;

@Component
@Order(Validators.BEAN_VALIDATOR_PLUGIN_ORDER)
public class ExpandedParameterNotBlankAnnotationPlugin implements ModelPropertyBuilderPlugin {

    @Override
    public boolean supports(DocumentationType delimiter) {
        // we simply support all documentationTypes!
        return true;
    }

    @Override
    public void apply(ModelPropertyContext context) {
        Optional<NotBlank> notBlank = extractAnnotation(context);
        if (notBlank.isPresent()) {
            context.getBuilder().required(true);
        }
    }

    @VisibleForTesting
    Optional<NotBlank> extractAnnotation(ModelPropertyContext context) {
        return annotationFromBean(context, NotBlank.class).or(annotationFromField(context, NotBlank.class));
    }
}`

**Comment by pavan2017** [comment]
any plans to fix this in swagger2.0?
