### ISSUE TITLE
Issue in displaying multiple examples

### ISSUE THREAD

**Issue by SomeshVerma** [swagger-api/swagger-core#2788]
I want to provide multiple examples in request body and want that end user can view all of them and choose one of them.
I have tried out various alternative approach to add examples but not got desired output. 

I am attaching a json file
It contains 2 methods in ms.categories:
1)post:
In its requestBody I have removed reference of schema and I am not able to see data in an external link 
"requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "type": "object"
                  }
                }
              },
              "examples": {
                "jsonObject": {
                  "summary": "A sample object",
                  "externalValue": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/product_data.json",
                  "description": "Structure of the item to be added is detailed below"
                }
              }
            }
          },
          "description": "Structure of the item to be added is detailed below"
        }

The output screen shows only:
{
  "data": {}
}

2) put:
 Only the schema gets displayed int the frontend not the examples when I try
"requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "allOf": [
                      {
                        "type": "object",
                        "properties": {
                          "_id": {
                            "type": "string"
                          }
                        }
                      },
                      {
                        "$ref": "#/components/schemas/ms.categories_field"
                      }
                    ]
                  }
                }
              },
              "examples": {
                "jsonObject": {
                  "summary": "A sample object",
                  "externalValue": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/product_data.json",
                  "description": "Structure of the item to be added is detailed below"
                }
              }
            }
          }

The front end shows:
{
  "data": {
    "_id": "string",
    "name": "string",
    "alias": "string",
    "description": "string",
    "images": [
      {}
    ],
    "fields": [
      {}
    ],
    "parent": "string",
    "count": "string",
    "SEO": {
      "title": "string",
      "description": "string",
      "keywords": "string",
      "canonical_url": "string",
      "sitemap_priority": "string"
    },
    "metafield_sets": [
      "string"
    ],
    "publish": "string",
    "attributes": [
      "string"
    ],
    "default_sort_order": "string",
    "widget": "string"
  }
}

It contains 2 methods in ms.products tag:

1) post: In its requestBody, I have supplied url of 2 json files, 
"requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": [
                  {
                    "$ref": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/product_data.json"
                  },
                  {
                    "$ref": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/categories_data.json"
                  }
                ]
              }
            }
          },
          "description": "Structure of the item to be added is detailed below"
        }

 but it is displaying an array of responses like this .Now it is not giving a choice to use any one of them rather it changed the structure of my request body

[
{ "_id": "558efa4358ae3b30020bcbf7", "_metadata": { "i18n": { "EN": {} } }, "metafields": { "one": "two" }, "images": [ { "tags": "florist in bangalore, flower delivery in bangalore, send flowers to bangalore, roses to bangalore, bouquets to bangalore", "image": "ms.products/558efa4358ae3b30020bcbf7/images/558efa4358ae3b30020bcbf8/558ef88fc17ed8460cfcb588/558ef88fc17ed8460cfcb588.jpg", "caption": "200 Roses Bouquet", "_metadata": { "image": { "_id": "558ef88fc17ed8460cfcb588", "name": "BB_DOTD_200ROS.jpg", "size": 86809, "type": "image/jpeg" } }, "_id": "558efa4358ae3b30020bcbf8" } ], "categories": [ "deal-of-the-day" ], "publish": "1", "dimension": {}, "inventory_management": "none", "inventory_low_stock_quantity": "5", "options": [], "SEO": { "title": "Send a Bouquet of 200 Roses in Bangalore, Order Flowers Online in Bangalore", "description": "Send a bunch of 200 roses in Bangalore at ₹ 2499/- Same day delivery in Bangalore. Bangalore Blooms is one of the oldest florist in Bangalore to 'Send Flowers in Bangalore' and to 'Order Cakes in Bangalore'", "keywords": "Exotic flowers, florists in bangalore, flower delivery bangalore, send flowers to bangalore, local florist in bangalore, florist bangalore" }, "attributes": [], "features": [], "description": "EXCLUSIVE DEAL OF THE DAY..!!!<br />\n<br />\nSend this exotic <u><strong>Bouquet of 200 Red Roses</strong></u> in Bangalore <span style=\"line-height: 20.7999992370605px;\">at an Unbelievable Price of<br />\nRs. 2499/- Only.</span>&nbsp;<strong>Free Delivery within City Limits of Bangalore</strong>.&nbsp;<br />\n<br />\n&nbsp;", "name": "200 Red Roses Bouquet", "alias": "200-red-roses-bouquet", "price": 2499, "compare_price": 4999, "sku": "BB_DOTD_200ROS", "weight": "1000", "available": 1, "sort_order": 235, "created_on": "2015-06-27T19:32:23.986Z", "_created_by": "5532747b389e154972ee6bb9", "updated_on": "2015-07-02T04:37:21.357Z", "_updated_by": "54858e54e681db2741900f5d", "option_set": "554a0a9a1bfdb5ce3f11fe38", "$$ref": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/product_data.json" 
}, 
{ "SEO": {}, "alias": "test-category", "default_sort_order": "-created_on", "description": "test category", "images": [], "name": "test category", "publish": 1, "$$ref": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/categories_data.json" 
} 
]

2) put:

in this method if i give a reference to schema then examples are not visible
  "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "type": "object",
                    "$ref": "#/components/schemas/ms.products_field",
     "example": [
                  {
                    "$ref": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/product_data.json"
                  },
                  {
                    "$ref": "http://cdn.storehippo.com/s/5a4b1c226fd323242ee426c4/ms.files/categories_data.json"
                  }
                ]
                  }
                }
              }
            }
          },
          "description": "Structure of the item to be added is detailed below"
        }
Now the schema gets displayed
{ "name": "string", "alias": "string", "description": "string", "images": [ {} ], "media": [ {} ], "price": 0, "compare_price": 0, "mrp_discount": 0, "collections": [ "string" ], "uniquesku": "string", "brand": "string", "sku": "string", "barcode": "string", "isbn": "string", "hsn": "string", "sac": "string", "upc": "string", "categories": [ "string" ], "avg_rating": "string", "num_reviews": 0, "weight": 0, "dimension": { "length": 0, "width": 0, "helght": 0 }, "inventory_management": "string", "inventory_allow_out_of_stock": "string", "inventory_quantity": 0, "inventory_low_stock_quantity": 0, "option_set": "string", "options": [ {} ], "variants": "string", "tax_rule": "string", "attributes": [ {} ], "features": [ "string" ], "channel_categories": "string", "SEO": { "title": "string", "description": "string", "keywords": "string", "canonical_url": "string", "sitemap_priority": "string" }, "tax": "string", "publish": "string", "sort_order": 0, "allow_custom_pricing": "string", "min_limit_to_buy_this_product": 0, "max_limit_to_buy_this_product": 0, "files": [ {} ], "shipping_cost": "string", "tag": "string", "is_catalog": "string" }

[swagger_issue.txt](https://github.com/swagger-api/swagger-core/files/1963821/swagger_issue.txt)

**Comment by webron** [comment]
This is an issue for swagger-ui and not swagger-core. However, we currently don't support displaying multiple examples but it is on our roadmap.
