### ISSUE TITLE
Spec filter loses ordering of operations

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#279]
Ordering using the `position` attribiute in @ApiOperation annotations is lost after applying spec filters

**Comment by webron** [comment]
Is this also relevant to 1.5?

**Comment by blueketchup** [comment]
I don't know. I haven't worked with this code in almost two years. Sorry.

**Comment by webron** [comment]
No problem, I was actually asking @fehguy  ;)

**Comment by fehguy** [comment]
@webron i don't think so.  feel free to close it

**Comment by webron** [comment]
Great. Closing out.

**Comment by blueketchup** [comment]
Ah that's weird. The email made it look like it was a message to me.
