### ISSUE TITLE
PropertyModelConverter in Swagger Core v1.5.19 does not map StringProperty#getEnum to ModelImpl#setEnum

### ISSUE THREAD

**Issue by bronogard** [swagger-api/swagger-core#2790]
Q | A
-- | --
Bug or feature request? | Bug
Which Swagger-Core version? | 1.5.19
Which Java version? | 1.8u162
Which JAX-RS framework & version? | Jersey 2.22.1 with JAX-RS 2.0

Due to changes made in [#2583](https://github.com/swagger-api/swagger-core/pull/2583) the following classes:
- [Response.java](https://github.com/swagger-api/swagger-core/commit/8b97df3667559fca1783da845607afc30e550b83#diff-b784df91296044012e055c7953196837) and
- [PropertyModelConverter.java](https://github.com/swagger-api/swagger-core/commit/8b97df3667559fca1783da845607afc30e550b83#diff-f61c3013f8d001c54188da718737ea54)

now behave differently during the serialization of the property [io.swagger.models.Response#getResponseSchema](https://github.com/swagger-api/swagger-core/commit/8b97df3667559fca1783da845607afc30e550b83#diff-b784df91296044012e055c7953196837R74) by applying the [ResponseSchemaMixin.java](https://github.com/swagger-api/swagger-core/commit/8b97df3667559fca1783da845607afc30e550b83#diff-58c27954db290a19d4fadbfe34b0bbf3).

Therefore, the method call to [io.swagger.models.utils.PropertyModelConverter#propertyToModel](https://github.com/swagger-api/swagger-core/commit/8b97df3667559fca1783da845607afc30e550b83#diff-f61c3013f8d001c54188da718737ea54R147) does not map the [io.swagger.models.properties.StringProperty#getEnum](https://github.com/swagger-api/swagger-core/blob/v1.5.19/modules/swagger-models/src/main/java/io/swagger/models/properties/StringProperty.java#L120) to the [io.swagger.models.ModelImpl#setEnum](https://github.com/swagger-api/swagger-core/blob/v1.5.19/modules/swagger-models/src/main/java/io/swagger/models/ModelImpl.java#L55).

**Comment by frantuma** [comment]
Thanks for reporting this; missing enum fixed in #2791, available in `1.5.20-SNAPSHOT` version on sonatype. Closing ticket, please reopen if you're still experiencing issues.
