### ISSUE TITLE
Support JsonTypeInfo and JsonSubTypes annotations

### ISSUE THREAD

**Issue by mthyman** [swagger-api/swagger-core#280]
When using polymorphism and only the parent class is referenced in the API operations its subclasses aren't added to the model.

Jackson discovers the inheritance model with the annotations JsonTypeInfo and JsonSubTypes.

I think it would be useful if Swagger could pick up the classes listed in JsonSubTypes and add them to the model. I also think it would be nice if Swagger could pick up the discriminator property from JsonTypeInfo and add the parameter to the model as adding the property to the subclasses makes Jackson write the property twice.

**Comment by Martin-Wegner** [comment]
It seems not to be working if the property 'type' (for the example property="type") is not a bean property (only used by Jackson for transportation).

**Comment by mukulb90** [comment]
@fehguy Has this been fixed ? Does it work if type is not a bean property?
On 1.5.21 branch, It isn't working for me.
```
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = A.class, name = "a"),
  @JsonSubTypes.Type(value = B.class, name = "b"),
})
public interface C {
  String getId();
}
```

Generated swagger.json:- 
```
"C" : {
      "type" : "object",
      "discriminator" : "type",
      "properties" : {
        "id" : {
          "type" : "string"
        }
      }
    }
```
property "type" is missing in properties as well as required(since it is discriminator) which is leading to wrong code generation. Any thoughts on this ?

**Comment by christophercolumbusdog** [comment]
Any update since @mukulb90 's comment? This thread seems only but it still doesn't seem to work, even on 2.0.8...

**Comment by webron** [comment]
Please file a new ticket for further investigation.
