### ISSUE TITLE
Extensions field getting emitted causing spec violation 

### ISSUE THREAD

**Issue by shankarganesh1234** [swagger-api/swagger-core#2808]
# Problem Statement

While generating  OpenAPI 3.0 contracts with 'x-' extensions at the Response level using swagger-parser (2.0.0-rc0), the 'extensions' field is getting emitted which breaks the specification. Here is a snippet (the full sample contract is also included below)

description: "some text"
extensions:
            x-response-codes:

This is also correctly flagged by the editor which shows the following error -

```
should NOT have additional properties
additionalProperty: extensions

```
# Proposed Solution

The root cause of the issue is the presence of 'extensions' container in the contract, which is violating the specification.
The fix involves editing **io.swagger.v3.oas.models.responses.ApiResponse**, and adding
**@JsonAnyGetter** to the getExtensions method

```
@JsonAnyGetter
public java.util.Map<String, Object> getExtensions() {
        return extensions;
 }

```
I can raise as PR if you could point me to the right branch. We are using swagger-parser 2.0.0-rc0 which points to swagger-models 2.0.0-rc1

Here's the full sample OAS v3 contract, which is generated by swagger-parser(version - 2.0.0-rc0) and particularly note the '400' response container, under responses  -
```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        '400':
          description: Bad Request
          extensions:
            x-response-codes:
              errors:
                '62002':
                  domain: API_TAXONOMY
                  category: REQUEST
                  description: Missing marketplace ID.
                '62003':
                  domain: API_TAXONOMY
                  category: REQUEST
                  description: The specified marketplace ID was not found.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

**Comment by frantuma** [comment]
I am not sure what you mean by `While generating OpenAPI 3.0 contracts with 'x-' extensions at the Response level using swagger-parser`; swagger-parser doesn't "generate" any serialized spec, as its work is to parse a spec in yaml/json format, by first desrializing it and then resolving refs etc. The outcome is a `OpenAPI` POJO (from `swagger-model`).

This POJO can indeed be then serialized as json/yaml string, and possibly it's this part you're referring to? in this case, it's possible that you're not using `swagger-core` [Json](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/Json.java) or [Yaml](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/Yaml.java) objects; these guys basically wrap a customized `ObjectMapper`, among the other things registering [ExtensionsMixin](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/mixin/ExtensionsMixin.java) which is providing the `@jsonanygetter` you mentioned.

You would use them e.g by calling `Yaml.pretty(openAPI)`.

Please let me know if this solves your issue.

**Comment by frantuma** [comment]
closing ticket, please reopen if still experiencing issues
