### ISSUE TITLE
Swagger core 1.5 does not allow spec filtering of definitions

### ISSUE THREAD

**Issue by shauera** [swagger-api/swagger-core#2809]
We have a use case in which we want to produce different swagger docs derived from the same API. Implementing the `AbstractSpecFilter` is what we need. However, it lacks the hook for filtering specific definitions. Using ` isRemovingUnreferencedDefinitions` is too broad for our use case.

We suggest add an ` isDefinitionAllowed` method to address this use case.

**Comment by frantuma** [comment]
implemented in #2820
