### ISSUE TITLE
reference to global response from APIResponse 

### ISSUE THREAD

**Issue by jmilkiewicz** [swagger-api/swagger-core#2829]
I am using swagger.core.v3 in version 2.0.2 
I am struggling to reference "global/reusable responses (these inside Components/responses)" from `@Operation` or `ApiResponse` annotations 

According to OPENAPI 3.0 i shall be able to define "reusable responses" within components as specified in[https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#components-object](url)
It works as a charm by:
```
OpenAPI oas = new OpenAPI()
                .info(info)
                .components(new Components().("invalidJWT", new ApiResponse().description("when JWT token invalid/expired")));
```

Now i would like to reference `invalidJWT`  response from `@APIResponse`, sth like:
```
@Operation(
            summary = "Generate list of foobars",
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "returns list of foobar",
                            content = @Content(schema = @Schema(implementation = FooBar.class))
                    ),
                    @ApiResponse(responseCode = "403", description = "when principal has no access to foo bar "),
                    @ApiResponse(responseCode = "404", description = "when foo bar")
            },
                    @ApiResponse(responseCode = "401", how to reference invalidJWT response here ???)
    )
```

Looking at java doc i can see that `@Scheme` enables references so i tried:
```
                    @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(ref = "#/components/responses/invalidJWT")))
```

but the output is wrong being:
```
 "401" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/responses/invalidJWT"
                }
              }
            }
          }
```
instead of (I expect it shall be  like that )
```
 "401" : {
                "$ref" : "#/components/responses/invalidJWT"
                }                       
```

How should one reference "global responses" from individual operations ?

**Comment by frantuma** [comment]
[ref](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/responses/ApiResponse.java#L97) field added to annotation in #2838. Closing ticket, please reopen if you're still experiencing issues.
