### ISSUE TITLE
ApiInfo seems to be not working

### ISSUE THREAD

**Issue by aradosz79** [swagger-api/swagger-core#2832]
We have developed quite complex web application that we want to document using swagger. In the process we have found an issue. It seems that ApiInfo Builder does not work. We are not sure if it is missconfiguration of our application or it is swagger bug. 

Following you will find SwaggerConfig class which is used to configure Swagger.

`
package com.intrasoft.mc2.gui.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

/**
 * Created by stanislaw.starek on 12.09.2017.
 */
@Configuration
@EnableSwagger2
public class SwaggerConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage("com.intrasoft.mc2.gui.rest"))
                .paths(PathSelectors.any())
                .build().apiInfo(apiInfo());
    }
    @Bean
    ApiInfo apiInfo() {
        final ApiInfoBuilder builder = new ApiInfoBuilder();
        builder.title("MC2 Spring Boot API").version("1.0").license("(C) Copyright IntraSoft TSI")
                .description("List of all endpoints used in API");
        return builder.build();
    }
}
`

The problem is that our apiInfo configuration is ignored by the swagger. Here is part of output from http://localhost:8101/v2/api-docs

`

swagger | "2.0"
-- | --
info |  
description | "Api Documentation"
version | "1.0"
title | "Api Documentation"
termsOfService | "urn:tos"
contact |  
license |  
name | "Apache 2.0"
url | "http://www.apache.org/licenses/LICENSE-2.0"
host | "localhost:8101"

`

**Comment by strausd** [comment]
I am having the same issue. I have tried both the ApiInfoBuilder as well as just the plain ApiInfo class shown in this tutorial:
https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api

Has anybody found a fix?

**Comment by lochichuen** [comment]
I have same problem,

**Comment by frantuma** [comment]
This doesn't seem to be related to swagger-core project, from the code snippets it seems springfox, please open the issue in the related repo.
