### ISSUE TITLE
Property requestBody should be of type String instead of RequestBody in Links.java (OAS 3.0)

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-core#2833]
Hi team,

In Links.java, property requestBody should be of type String instead of RequestBody as it's clearly mentioned as below in https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#linkObject

requestBody | Any \| {expression} | A literal value or {expression} to use as a request body when calling the target operation.
-- | -- | --

Note: We used Map<String, **String**> for parameters field in Links.java

Thanks,
Mohammed

**Comment by frantuma** [comment]
fixed in #2877
