### ISSUE TITLE
io.swagger.v3.oas.annotations.enums.ParameterIn does not support Form parameters

### ISSUE THREAD

**Issue by sdnakhla** [swagger-api/swagger-core#2840]
The io.swagger.v3.oas.annotations.enums.ParameterIn class only supports the following parameter types:
 
- DEFAULT(""),
- HEADER("header"),
- QUERY("query"),
- PATH("path"),
- COOKIE("cookie")

It should also include the ability to define form parameters

**Comment by ymohdriz** [comment]
Hi @sdnkhla,

This is expected as form parameters are replaced with request body in OAI 3.0.

Thanks,
Mohammed
