### ISSUE TITLE
Swagger 3 with Spring Boot

### ISSUE THREAD

**Issue by GuruTom** [swagger-api/swagger-core#2841]
Hi All,

Just wondered if someone could point me in the direction of a tutorial for setting up swagger 3 + UI with Spring Boot? 

Cheers In advance

**Comment by parameshjava** [comment]
Even I am interested in it. @GuruTom Can you please post the reason for the closer.

**Comment by buster** [comment]
Same here. The documentation doesn't mention spring anywhere. Is spring not supported anymore?
