### ISSUE TITLE
SecurityParser returns package private class

### ISSUE THREAD

**Issue by jameskleeh** [swagger-api/swagger-core#2846]
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/SecurityParser.java

The public method `getSecurityScheme` returns an optional with a package private class. Either the method should be package private, or the class it returns should be public.

Thanks!

**Comment by frantuma** [comment]
thanks for reporting this! fixed in #2932
