### ISSUE TITLE
A property of type of "array" e.g. one with ArraySchema can not be marked as required

### ISSUE THREAD

**Issue by kostya-lnk-ms** [swagger-api/swagger-core#2848]
I'm using core v3 2.0.2
The following is repro (in Kotlin)

 @Path("/")
    class Api {
        @GET
        fun getter() : Town = Town(listOf())
    }

   data class Town(
            @get:[ ArraySchema( arraySchema = Schema(required = true), schema = Schema(required = true), minItems = 1,uniqueItems = true ) ]
            val streets: List<String>
    )

    @Test
    fun tst() {
        val api = Reader().read(Api::class.java)
        val json = ObjectMapper().setSerializationInclusion(JsonInclude.Include.NON_NULL)
                    .writerWithDefaultPrettyPrinter().writeValueAsString(api)
        json.contains("required")
    }

I expect that there should a way of saying that the "streets" property is required
That yields the following json model:

`
{
  "openapi" : "3.0.1",
  "paths" : {
    "/" : {
      "get" : {
        "operationId" : "getter",
        "responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Town"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Town" : {
        "type" : "object",
        "properties" : {
          "streets" : {
            "minItems" : 1,
            "uniqueItems" : true,
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}
`

**Comment by frantuma** [comment]
Thanks for reporting this, fixed in #2867. in your case you would use

`@get:[ ArraySchema( schema = Schema(required = true), minItems = 1,uniqueItems = true ) ]`

Closing ticket, please reopen if still experiencing issues
