### ISSUE TITLE
Error in the documentation (wiki) of the core resolvers

### ISSUE THREAD

**Issue by Treppenhouse** [swagger-api/swagger-core#2850]
In the wiki you describe how to extend core resolvers: https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver

In the example of the `ModelResolver` it says that in order to register one you have to use: 

`ModelConverters.getInstance().addConverter(new MyCustomResolver());`

However, the class `MyCustomResolver` that you presented does not have a no-argument constructor. Therefore, the example as you provided it will not compile. 

It would be great if that could be fixed.

**Comment by frantuma** [comment]
fixed
