### ISSUE TITLE
Inheritance info from "allOf" not shown in the generated model!!!

### ISSUE THREAD

**Issue by duckladydinh** [swagger-api/swagger-core#2860]
Dear,

I cannot seem to find anyway to make the information from "allOf" on the left the appear in the models on the right. Is this a bug? Otherwise, what is the use of allOf then if it does not appear in the generated documentation?

![image](https://user-images.githubusercontent.com/22922064/42095722-aeaaca54-7bb3-11e8-980c-25a69edd8a8b.png)

**Comment by frantuma** [comment]
this seems related to `swagger-ui`, if that is the case, please open the ticket in related repo https://github.com/swagger-api/swagger-ui
