### ISSUE TITLE
Does Swagger intend to support classes of the same name but different packages?

### ISSUE THREAD

**Issue by duckladydinh** [swagger-api/swagger-core#2864]
Dear all,

I believe it is necessary since it is not difficult to encounter classes of the same name in a big project of thousands of classes. I tried to used Swagger for this by building the OpenAPI object but unfortunately, when I add too classes of the same name to the component schema, the later will overwrite the former.

Is there anyway to fix that? Thank you.

**Comment by frantuma** [comment]
This seems like a duplicate of your other ticket #2861..
