### ISSUE TITLE
models: extensions on ServerVariables?

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-core#2885]
The `ServerVariables` has support for extensions:

https://github.com/swagger-api/swagger-core/blob/110ae2bae21b7f2e64aff3691953c11a533a14c9/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/servers/ServerVariables.java#L57-L78

But I do not see where in the Spec is mentioned that the map <variable-name, server-variable> can contains extensions.

Of course these extensions can be defined at:

* [server-object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#server-object) 
* [server-variable-object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#server-variable-object)

But not on the map...

**Comment by frantuma** [comment]
Thanks for reporting this, extensions deprecated in #2931, will be eventually removed
