### ISSUE TITLE
Schem.AccessMode documentation is not correct

### ISSUE THREAD

**Issue by MarvGilb** [swagger-api/swagger-core#2887]
Documentation for AccessMode READ_ONLY & WRITE_ONLY is the same.

https://github.com/swagger-api/swagger-core/blob/110ae2bae21b7f2e64aff3691953c11a533a14c9/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java#L247

**Comment by dmarmugi** [comment]
```
* AccessMode.READ_ONLY: value will only be written to during a request but not returned during a response.
```
should probably read something like 
```
* AccessMode.READ_ONLY: value will not be written to during a request but may be returned during a response.
```

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java#L237-L247

zooming in: 

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/media/Schema.java#L240-L241
