### ISSUE TITLE
Handling of XmlAccessorType.NONE is too restrictive in Jackson model resolver

### ISSUE THREAD

**Issue by svella** [swagger-api/swagger-core#2907]
We have DTO objects annotated with both Jackson and JAXB annotations (for backward compatibility with XML based REST) and we always use XmlAccessorType.NONE because we want explicit control of serialization. What we end up with is only properties annotated with @XmlElement are showing up in the swagger model. Properties annotated with @XmlAttribute and @XmlElementRef are being excluded, even though they are also annotated with both @ApiModelProperty and @JsonProperty and all we really care about in our swagger document is JSON.

**Comment by svella** [comment]
Looks like the @XmlAttribute  part of this was fixed by #1847, but because 2.x development renamed all the packages before that merge never happened into that line.

**Comment by svella** [comment]
working on a set of PR's for 1.5 and 2.x branches

**Comment by frantuma** [comment]
merged #2920 and #2921, thanks!
