### ISSUE TITLE
About  Apiparams  a little suggest  of swagger

### ISSUE THREAD

**Issue by poppycokey** [swagger-api/swagger-core#2922]
Sometime,When I define an interface parameter.I found that some fields of the entity class are not required.like this ↓
 `@RequestMapping(value = "/update", produces = {"application/json;charset=UTF-8"})
   public void update(@RequestBody Book param) {}`
But I only need a few fields in the entity,How do I hide the other fields.Do I have to define a new entity? That's a hassle.

**Comment by frantuma** [comment]
I believe you could be using [springfox](https://github.com/springfox/springfox). If this is the case please open ticket there and close this one.
