### ISSUE TITLE
apiKey in @SecurityScheme not working when upgrading

### ISSUE THREAD

**Issue by markusdemetz** [swagger-api/swagger-core#2923]
I use swagger-annotations to generate my openapi.json file.

When upgrading from _2.0.0_ to _2.0.x_ I have the following issue:
The JSON in the _securityScheme_ section is beeing rendered differently. The _name_ attribute is missing.
The Swagger UI then renders an "**undefined**" instead of an "**apiKey**":
I.e.:

`curl -X GET "http://localhost:8080/api/v1/myResource?pageNr=0&size=20" -H "accept: application/json" -H "undefined: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJrdXNAZGVtZXR6LmV1IiwiZXhwIjoxNTM0OTM3MDc1LCJ1c2VySWQiOiIyIiwiaWF0IjoxNTM0OTMzNDc1fQ.mUpT3nGichUHY0HIJNkpG8TS6K6DTH7bczsvf91rjjgY70oAfe2oKE9NK2zyWHGxtV9RB9GTxJSfy4tJScgtVQ"`

Is this a _swagger-annotations_ issue or a _Swagger UI_ issue?

**Comment by frantuma** [comment]
Can you share an example of what are you trying to achieve, along with swagger-core version and actual vs expected result?

**Comment by markusdemetz** [comment]
I extend from `org.glassfish.jersey.server.ResourceConfig` and annotate my class as follows:

```@ApplicationPath("/api/v1")
@Path("/")
@OpenAPIDefinition(
  info = @Info(title = "MyTitle", version = "v1", description = "My Description"),
  security = @SecurityRequirement(name = "apiKey"))
@SecurityScheme(type = SecuritySchemeType.APIKEY, name = "apiKey", in = securitySchemeIn.HEADER)
public class MyApplication extends ResourceConfig {
	public MyApplication() {
		ResourceConfig resourceConfig = packages("com.mypackage.resources");
		register(resourceConfig.getClasses());
		register(OpenApiResource.class);
	}
}
```
So I can make a call to `http://localhost:8080/api/v1/openapi.json` and the JSON OpenAPI spec is produced.
Using `swagger-core-2.0.0 (swagger-annotations-2.0.0)` everything works fine. The relevant part produced is:
```
"securitySchemes": {
  "apiKey": {
    "type":"apiKey",
    "name":"apiKey",
    "in":"header"
   }
}
```
Loading the JSON into _Swagger UI_ lets me make an API call.

![swaggeruiok](https://user-images.githubusercontent.com/30077873/44518305-348c1380-a6ca-11e8-96a1-6489b0ce0e9f.jpg)

When upgrading to a newer version (2.0.1, 2.0.2 or 2.0.3), the JSON regarding securitySchemes is missing the `name` attribute:
```
"securitySchemes": {
  "apiKey": {
    "type":"apiKey",
    "in":"header"
   }
}
```
Using _Swagger UI_ to make an API call is not working, because the header name for the apiKey is undefined.
![swaggeruiundefined](https://user-images.githubusercontent.com/30077873/44518056-90a26800-a6c9-11e8-9f38-e104eade8b39.jpg)

Thanks!

**Comment by markusdemetz** [comment]
It solved the issue, thank you!
