### ISSUE TITLE
Swagger UI renders double brackets when array is used in request body of a post method

### ISSUE THREAD

**Issue by pmallu** [swagger-api/swagger-core#2934]
Please find the attached screenshots for the code. As mentioned, swagger UI generates two brackets for the example array.

![screen shot 2018-08-28 at 2 33 32 pm](https://user-images.githubusercontent.com/42786921/44752539-283ff600-aad0-11e8-8fc8-30bbb4ca3883.png)
![screen shot 2018-08-28 at 2 37 51 pm](https://user-images.githubusercontent.com/42786921/44752567-41e13d80-aad0-11e8-9b25-474c7a2ace88.png)

**Comment by frantuma** [comment]
as this is related to swagger-ui, please move this ticket there
