### ISSUE TITLE
Can't use Schema generated from return type when using explicit response content schemas

### ISSUE THREAD

**Issue by hosswald** [swagger-api/swagger-core#2937]
Consider the following route definition in kotlin
```kotlin
@GET fun get(): Container<MyType>
```
This would make Swagger generate a nice OpenAPI definition looking approximately like this:
```json
{
  "openapi" : "3.0.1",
  "paths" : {
    "/" : {
      "get" : {
        "operationId" : "get",
        "responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ContainerMyType"
                }
              }
            }
          }
        }
      }
    }
```
`$ref` is set automatically from the method return type.
As soon as I add custom `@ApiResponses`, I can no longer profit from this, since **only** [If no @ApiResponse is provided at method level or in the @Operation annotation, a default response will be generated](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#apiresponse).
```kotlin
@ApiResponses(ApiResponse(responseCode = "400", description = "bad request")
@GET fun get(): Container<MyType>
```
openapi.json:
```json
{
  "openapi" : "3.0.1",
  "paths" : {
    "/" : {
      "get" : {
        "operationId" : "get",
        "responses" : {
          "400" : {
            "description" : "bad request"
          }
      }
    }
}
```
I cannot reference the return type explicitly, since it is a generic type and `@Schema(implementation = X.class)` takes only classes.
My workaround is to reference the auto-generated schema by name, which is very suboptimal and would break as soon as I refactor any class names:
```kotlin
@ApiResponses(ApiResponse(responseCode = "200", content = [Content(schema = Schema(ref = "#/components/schemas/ContainerMyType"))]),
              ApiResponse(responseCode = "400", description = "bad request")
@GET fun get(): Container<MyType>
```
I understand that it is necessary to ditch the auto-generated response content as soon as there are any explicit `@ApiResponses`, but I see two easy ways to improve the current behaviour:

1. If either `content` or `content.schema` isn't set, use the auto-generated schema instead or
2. provide a simple and context-independent way to reference the schema generated from the return type, e.g. `@ApiResponses(ApiResponse(responseCode = "200",
                              content = [Content.METHOD_RETURN_TYPE])`

**Comment by hosswald** [comment]
The reason for the current behaviour is [this line](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java#L956).

**Comment by hosswald** [comment]
Created a pull request #2937 that should fix the problem.

**Comment by khojir** [comment]
I need this feature too. Is there any other solution?

**Comment by frantuma** [comment]
solution is using `ApiResponse(responseCode = "400", description = "bad request", useReturnTypeSchema = true)`
