### ISSUE TITLE
Update jackson library to latest stable

### ISSUE THREAD

**Issue by scadgek** [swagger-api/swagger-core#2940]
I see the 1.5.x stable version currently uses jackson version 2.9.5. Shouldn't there be any issues with updating it to 2.9.6 and producing a release to Maven Central? Specifically I need this to avoid dependency version mismatch in my project.

**Comment by frantuma** [comment]
we could and will update, but you can declare the dependency to 2.9.6 at top level, and that will be picked up

**Comment by scadgek** [comment]
I'm aware of the workarounds, but ideally I'd like to avoid them. Having version 2.9.6 in the swagger-core itself will provide a better guarantee that it's an acceptable version for proper work of the library. Although I understand that it's not an issue in this specific case (where the version mismatch is 2.9.5. vs 2.9.6).

**Comment by frantuma** [comment]
implemented in #3123  and #3091
