### ISSUE TITLE
Mixin ignored with jersey 

### ISSUE THREAD

**Issue by devMls** [swagger-api/swagger-core#2950]
Hi

I Just add swagger api to my project and it, generate schema like a Magic.

But mixin annotations @jsonignore not are processed by the framework and the swagger schema show it.

Is mixins supported by swagger?

My config:
```

@ApplicationPath("/")
public class MyApplication extends ResourceConfig {

    public MyApplication() {

        register(JacksonFeature.class);

        register(JacksonObjectMapperProvider.class);

        register(PreFilter.class);

        register(PosFilter.class);
        
        OpenApiResource openApiResource = new OpenApiResource();

        
        register(openApiResource);
    }
```

And the object mapper definition (JacksonObjectMapperProvider)

`public class JacksonObjectMapperProvider implements ContextResolver<ObjectMapper> {

    final ObjectMapper defaultObjectMapper;

    public JacksonObjectMapperProvider() {
        defaultObjectMapper = createDefaultMapper();
    }

    @Override
    public ObjectMapper getContext(Class<?> type) {
        return defaultObjectMapper;
    }

    public static ObjectMapper createDefaultMapper() {

        final ObjectMapper jackson = new ObjectMapper();
       
        jackson.addMixIn(Model.class, ModelMixin.class);
        
        return jackson;

    }

}`

**Comment by frantuma** [comment]
please apply mixins to object mapper in use by `swagger-core`, which is obtained e.g. via `Json.mapper().addMixIn(Model.class, ModelMixin.class)`, as code above is applying them to the mapper used by the JAX-RS framework; this should solve your issue; closing ticket, please reopen if you're still experiencing issues
