### ISSUE TITLE
Implement Oauth bearer token authantication

### ISSUE THREAD

**Issue by SenthilkumarRasan** [swagger-api/swagger-core#2964]
Our web API uses OAUTH bearer token authentication. I am trying to implement with swagger UI
Tried the following config 
config.EnableSwagger(c =>
                {
                       .Flow("application")
                       .TokenUrl("http://localhost/v1.0/APIname/token")
                       .Description(
                           "An AccessToken object is the authorization token issued by the API when valid authentication is submitted.")
                                          .Scopes(scopes =>
                        {
                            scopes.Add("read", "Read access to protected resources");
                            scopes.Add("write", "Write access to protected resources");
                        });

                    c.OperationFilter<AssignOAuth2SecurityRequirements>();
                .EnableSwaggerUi(c =>
                {
                    c.DocumentTitle("Compare API");
                    c.EnableOAuth2Support("implicitclient", "secret", "test", "Swagger UI");

                    //           c.DisableValidator();
                });

I am getting No response from server. How do i implement OAUTH bearer token and configure swagger to use as bearer token for all endpoints in web API. Appreciate your support. Thanks

**Comment by frantuma** [comment]
this seems to be related to [swagger-ui project](https://github.com/swagger-api/swagger-ui), if this is the case please move this ticket there. thx
