### ISSUE TITLE
Caching of open api context is broken in jaxrs2 OpenApiResource

### ISSUE THREAD

**Issue by aharin** [swagger-api/swagger-core#2977]

**Comment by aharin** [comment]
When JaxrsOpenApiContextBuilder creates XmlWebOpenApiContext, it should set ctxId. It is used as a key for OpenApiContext caching. As it currently stands, the code in JaxrsOpenApiContextBuilder is using ctxId derived from the servlet name to lookup OpenApiContext, while XmlWebOpenApiContext created by the builder always cached under a default context id.

**Comment by jlw0** [comment]
I ran into the same problem.  If a context id is not provided, it should default to use the value from ServletConfigContextUtils.getContextIdFromServletConfig(servletConfig).  This default value will allow it to work with OpenApiResource and AcceptHeaderOpenApiResource.  This will also allow the context id to be set as a servlet init parameter.

**Comment by frantuma** [comment]
Thanks for spotting and addressing this! Fixed in #2990 which includes and replaces #2987
