### ISSUE TITLE
Documenting multipart/form-data JAX-RS endpoint triggers jersey validation error

### ISSUE THREAD

**Issue by zsoltherpai** [swagger-api/swagger-core#3009]
I use jersey (2.27) and implemented a file upload using multipart/form-data. I use swagger jax-rs2  (2.0.5) to document it. 

The documentation of InputStream and FormDataBodyPart reveals the objects internals by default, so I used @Parameter to override the schema, eg:
@Parameter(schema = @Schema(type = "string", format = "binary", description = "blob"))

This triggers a validation error at jersey start on either  InputStream or FormDataBodyPart parameter: 
[[FATAL] No injection source found for a parameter of type ....
Very weirdly the issue is not completely deterministic, but a few clean / builds / test trigger it.

If I remove the @Parameter(schema = ...) annotation, jersey initialization is solid again. Apparently swagger's @Parameter annotation interferes with Jersey.

As a workaround I annotated the parameters with @Parameter(hidden = true) and documented the parameters in the @Operation annotation, that doesn't seem to cause any issues.

**Comment by frantuma** [comment]
This is possibly similar to #2567 and is probably not related to swagger, but related to [this jersey issue](https://github.com/jersey/jersey/issues/3458) and can be worked around by having `FormDataParam` as the last annotation.
Please give it a go, and close ticket if it solves your issue

**Comment by zsoltherpai** [comment]
I've always had @FormDataParam as the last annotation - although only accidentally through a convention of doc annotations first.. 

But a similar jersey bug might be the culprit. I keep my workaround for a while and keep an eye on the related jersey issues, thanks.
