### ISSUE TITLE
swagger-maven-plugin does not set ctxId of JaxrsOpenApiContextBuilder

### ISSUE THREAD

**Issue by MarvGilb** [swagger-api/swagger-core#3013]
Hey,

I have a project with several sub-projects, that share some code. Within these sub-projects I am using the swagger-maven-plugin to generate a swagger file.
During the creation, the JaxrsOpenApiContextBuilder creates/uses only the OpenApiContext.OPENAPI_CONTEXT_ID_DEFAULT as ctxId. This way it is not possible to create different context files in a single build (Every run uses the context of the first module.)

-----
## Setup
```
<groupId>io.swagger.core.v3</groupId>
<artifactId>swagger-maven-plugin</artifactId>
<version>2.0.5</version>
```

**Comment by frantuma** [comment]
Thanks for reporting this and pointing to code! #3014 adds `contextId` param (defaulting to `${project.artifactId}`), available in latest snapshot. Closing ticket, please reopen if you're still experiencing issues

**Comment by MarvGilb** [comment]
Thanks for the fast reply. When is a new release planed?

**Comment by frantuma** [comment]
no fixed ETA, but within few weeks
