### ISSUE TITLE
Descriptions for object properties are mixed-up

### ISSUE THREAD

**Issue by pdiam** [swagger-api/swagger-core#3035]
Consider the following java code:
```java
public class Issue1Response {
	
	@Schema(description = "Property1")
	private Issue1Object property1;
	
	@Schema(description = "Property2")
	private Issue1Object property2;

	public Issue1Response(Issue1Object property1, Issue1Object property2) {
		this.property1 = property1;
		this.property2 = property2;
	}

	public Issue1Object getProperty1() {
		return property1;
	}

	public void setProperty1(Issue1Object property1) {
		this.property1 = property1;
	}

	public Issue1Object getProperty2() {
		return property2;
	}

	public void setProperty2(Issue1Object property2) {
		this.property2 = property2;
	}
}
```

The output of this (with swagger v.2.0.6) is:
```javascript
Issue1Object: {
	required: [
		"property"
	],
	type: "object",
	properties: {
		property: {
			type: "string"
		}
	},
	description: "Property2"
},
Issue1Response: {
	type: "object",
	properties: {
		property1: {
			$ref: "#/components/schemas/Issue1Object"
		},
		property2: {
			$ref: "#/components/schemas/Issue1Object"
		}
	}
}
```
As you can see the object's description is "Property2" which is the description assigned to the second property. The description from the first property is discarded.

Since the OpenAPI Reference object does not support a description property (which is still a debated issue [#556](https://github.com/OAI/OpenAPI-Specification/issues/556) on the OpenAPI spec project), the only proposed solution is to use an allOf construct like:
```javascript
Issue1Response: {
	type: "object",
	properties: {
		property1: {
			allOf: [{
				$ref: "#/components/schemas/Issue1Object"
			}],
			description: "Property1"
		},
		property2: {
			allOf: [{
				$ref: "#/components/schemas/Issue1Object"
			}],
			description: "Property2"
		}
	}
}
```

So, until this is resolved in the spec, is it possible to have swagger generate the proposed workaround?

**Comment by frantuma** [comment]
this has been addressed implementing new config property and annotation as detailed in [wiki](https://github.com/swagger-api/swagger-core/wiki/OpenAPI-3.0-Schema-Resolution)
