### ISSUE TITLE
DataTypeClass not working in ApiImplicitParam

### ISSUE THREAD

**Issue by gorokhmn** [swagger-api/swagger-core#3057]
| Q | A |
| -- |:--:|
| Bug or feature request? | Bug |
| Which Swagger-Core version? | 2.9.2 |
| Which Java version? | 1.8.0_192 |

Code to demo the issue:
```
@RequestMapping(value="getData")
@ResponseBody
@ApiOperation(value="Get data", notes="Returns data", response=MyResponseDto.class)
@ApiImplicitParam(name="jsonRequest", value="Query", required=true,
   dataTypeClass=MyRequestDto.class, paramType="body")
public String getData(@RequestBody String jsonRequest) {
  . . .
}
```
The Swagger annotation `@ApiOperation` is working nicely for response `MyResponseDto.class` and fails for annotation `@ApiImplicitParam` - returns `String` instead of `MyRequestDto.class` 
Seems to be annotation parameters are declared as required.

**Comment by pjfanning** [comment]
There is no swagger-core 2.9.2 - 2.06 is the latest release. The code snippet appears to be for swagger-core 1.5.x though.

**Comment by gorokhmn** [comment]
My pom.xml declares
 ~~~~
<dependency>
   <groupId>io.springfox</groupId>
     <artifactId>springfox-swagger2</artifactId>
   <version>2.9.2</version>
</dependency>
~~~~

**Comment by Vendelieu** [comment]
![изображение](https://user-images.githubusercontent.com/3987067/71723179-bd799a00-2e3c-11ea-8819-9073b0f70383.png)

![изображение](https://user-images.githubusercontent.com/3987067/71723195-d2562d80-2e3c-11ea-9e87-6cf1ec0a3dba.png)

i got similar reaction for ApiImplicitParam and datatypeclass

**Comment by webron** [comment]
This issue relates to Springfox, not swagger-core. Please file the issue with that project.
