### ISSUE TITLE
Failed to load filter

### ISSUE THREAD

**Issue by ethan92429** [swagger-api/swagger-core#3066]
Using the default openApiResource, the filter fails to load unless explicitly stated within the passed in configuration. The problem seems to be in the [filter logic here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/resources/BaseOpenApiResource.java#L56). The  issue is that the default is never loaded because it is not present within ctx.getOpenApiConfiguration().getFilterClass(). That returns null when no configuration is defined.

**Comment by frantuma** [comment]
I am not sure I understand, which filter fails to load? can you share your config and possibly a test case?
