### ISSUE TITLE
Broken link in gradle plugin registry

### ISSUE THREAD

**Issue by julie-sullivan** [swagger-api/swagger-core#3073]
On this page:

https://plugins.gradle.org/plugin/io.swagger.core.v3.swagger-gradle-plugin

The URL goes to:

https://github.com/swagger-api/swagger-core/modules/swagger-gradle-plugin

Instead of the correct GitHub URL:

https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-gradle-plugin

Thanks! :)

**Comment by frantuma** [comment]
Thanks for spotting this; fixed in #3077 will be part of next release
