### ISSUE TITLE
Can't ignore the type returned from method

### ISSUE THREAD

**Issue by arinal** [swagger-api/swagger-core#3074]
Oftentimes, operation method returns wrapper classes which is not really important and should be filtered in the output swagger json/yaml. The example below uses scala `akka-http` and it's very common to return `ToResponseMarshallable` in every operation. This class is only a wrapper value to serialise the object its contain.

```scala
@GET 
@ApiResponse(responseCode = "200", /* details is omitted */ classOf[Employee])
def getEmployee(id: String): ToResponseMarshallable =
   ToResponseMarshallable(Employee("Michael Suyama"))

case class Employee(name: String)
```

The expected swagger output `components.schemas` is `Employee` without `ToResponseMarshallable`.

Executing `ModelConverters.getInstance().addClassToSkip("ToResponseMarshallable")` won't work since it only filters annotated type, while `ToResponseMarshallable` is deducted from method's type return value.

Has been analysing [Reader.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java#L966), seems like the filter logic is pretty much hard coded.

**Comment by frantuma** [comment]
Thanks for reporting and working on this! implemented in #3107
