### ISSUE TITLE
SecurityScheme type property should be written in lower case.

### ISSUE THREAD

**Issue by tdudgeon** [swagger-api/swagger-core#3076]
According to the spec [1] the valid values for the `type` property of the `Security Scheme` object are:
"apiKey", "http", "oauth2", "openIdConnect"

Then using `swagger-models` to generate an OpenAPI definition with code like this:
```
openApi.getComponents()
                .addSecuritySchemes("OIDC", new SecurityScheme()
                        .type(SecurityScheme.Type.OPENIDCONNECT)
                        .openIdConnectUrl("http://somewhere.com/foo/bar"))
``` 
You end up with YAML like this:
```
  securitySchemes:
    OIDC:
      type: "OPENIDCONNECT"
      openIdConnectUrl: "http://somewhere.com/foo/bar"
```

Note that the type property is in upper case. The same also applies when using the other values of the `SecurityScheme.Type` enum. 
If you use this YAML in the swagger editor [2] it is noted as being invalid, and the scheme does not recognised by swagger-ui when try to authorize.

As it seems that this value can only be specified using one of the `SecurityScheme.Type` enum values there seems to be no easy workaround.

It seems that the enum value needs to be written correctly. Note that this cannot be just converting to lower case as one of the values is `openIdConnect`.

[1] https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#security-scheme-object
[2] https://editor.swagger.io/

**Comment by frantuma** [comment]
The probable reason for this is not using a configured object mapper for serialization to YAML (best option would be the provided [Yaml class](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/Yaml.java), e.g. via `Yaml.prettyPrint(openApi)`. Closing ticket, please reopen if you're still experiencing issues.

**Comment by tdudgeon** [comment]
Yes, that is right. If I use the Yaml class rather than a standard Jackson ObjectMapper I get the correct yaml. Thanks.

**Comment by magnayn** [comment]
For anyone passing by this way:
Make sure you import the correct, v3 Yaml !

```java
import io.swagger.v3.core.util.Yaml;
```
