### ISSUE TITLE
Document Hashmap with @Schema

### ISSUE THREAD

**Issue by yntelectual** [swagger-api/swagger-core#3080]
hi,

how would one describe an api response, that returns `Map<String, List<ComplexObject>>` using the v2 annotations? Or `Map<String, ComplexObject>`? 

According to OA3 schema it is possible to model like this, using additionalProperties:
```
openapi: "3.0.0"
info:
  title: Swagger Petstore
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /petGroups:
    get:
      operationId: listPetGroups
      tags:
        - pets
      responses:
        '200':
          description: Pets grouped by Ownername
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/MapResponse"

 
components:
  schemas:
    MapResponse:        # <---- dictionary<String,Array<Pet>>
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Pets'
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
   
```

But I do not see a way, how to describe this structure on the server side using java annotations, as `@Schema` does not have `additionalProperties`. 

(end goal is to generate schema from server code, or at least to validate, that the server code matches the schema above)
Thanks

**Comment by frantuma** [comment]
one way to achieve what you want is having your resource method return e.g. `Map<String, List<Pet>>` which would result in a spec with a response to the one above:

```
        @GET
        @Path("/path")
        public Map<String, List<Pet>> simpleGet(String data) {
            return null;
        }
```

a more "invasive" alternative would be defining a class extending e.g. `HashMap<String, Pet>` to be used in `implementation` field of `@Content` annotation within `@Response`:

```
class MyModel extends HashMap<String, Pet> {}
```

```
@Operation(responses = {
  @ApiResponse(
    responseCode = "200",
    content = @Content(
      mediaType = "application/json", 
      schema = @Schema(implementation = MyModel.class)))
  }
)
@GET
@Path("/path")
public Whatever simpleGet(String data) {
      return null;
}
```

**Comment by clounie** [comment]
It seems like something that should be automatically introspected and applied, especially for `Map<String, XXX>`.

**Comment by ndtreviv** [comment]
Something like this would be great:

```
content = @Content(map = @MapSchema(key = @Schema(implementation = String.class), value = @Schema(implementation = XXX.class)))
```

And so would produce the following in swagger ui:
```
{
  "key": XXX > { ... }
}
```

**Comment by mchmielarz** [comment]
Hi! @frantuma How's the progress with this one?

**Comment by MansSandberg** [comment]
Any update on this? @frantuma 
I encountered this problem this week when I implemented an API that returns a HashMap.

**Comment by atulkumarr123** [comment]
I also stumbled upon this today, Does anyone know the status on this?

**Comment by Plonk42** [comment]
Hey @frantuma , any update on this one? Thanks!

**Comment by amccourt** [comment]
Also looking for an update on this @frantuma

**Comment by frantuma** [comment]
#4475 adds support for `additionalPropertiesArraySchema` in `@Content` annotation which should cover all use cases mentioned in this ticket related to `additionalProperties`. [This test](https://github.com/swagger-api/swagger-core/pull/4475/files#diff-4b24df32d9e96fcd3533b20993e197d322e2fa604e36639b26003eab9a769fc8R3016) and related [resource class](https://github.com/swagger-api/swagger-core/pull/4475/files#diff-6a6839a8b5f57c964f61bf461be49730368579534d7c270298e0cd9688477b16R15) demonstrates usage in various scenarios.

Closing ticket, will monitor for any comment/feedback

**Comment by nahmias22** [comment]
Is there somewhere an example on how a map should be described based on the new changes?

**Comment by alexlitovsky** [comment]
> #4475 adds support for `additionalPropertiesArraySchema` in `@Content` annotation which should cover all use cases mentioned in this ticket related to `additionalProperties`. [This test](https://github.com/swagger-api/swagger-core/pull/4475/files#diff-4b24df32d9e96fcd3533b20993e197d322e2fa604e36639b26003eab9a769fc8R3016) and related [resource class](https://github.com/swagger-api/swagger-core/pull/4475/files#diff-6a6839a8b5f57c964f61bf461be49730368579534d7c270298e0cd9688477b16R15) demonstrates usage in various scenarios.
> 
> Closing ticket, will monitor for any comment/feedback

I am still not seeing how this can be used to document a Map (key type, value type) using the provided examples. It should be much more obvious.
