### ISSUE TITLE
Models should not be equal if they have different properties

### ISSUE THREAD

**Issue by nzolotova** [swagger-api/swagger-core#3084]
Good day everyone,
we faced with an issue while generating an openApi with the version 1.5. 

Two models, that have different properties, occurred to be equal, but shouldn't be. 

I created a test in Kotlin to compare two models with properties, that have different nested properties, and it failed:
```
@Test
	fun `should compare two models with different properties`(){

		val model1 = givenModel("order")
		val model2 = givenModel("attributes")

		then(model1 == model2).isFalse()
	}

	private fun givenModel(subPropertyName: String): ModelImpl {
		val model = ModelImpl()
		model.properties = givenProperties(subPropertyName)

		return model
	}

	private fun givenProperties(subPropertyName: String): Map<String, ObjectProperty> {
		return mapOf("_links" to givenProperty(), "page" to givenProperty(), "_embedded" to givenProperty(mapOf(subPropertyName to givenProperty())))
	}

	private fun givenProperty(properties: Map<String, ObjectProperty> ? = emptyMap()): ObjectProperty {
		return ObjectProperty(properties)
	}
```
For me it looks like the issue happens, because ```ObjectProperty``` does not overwrite ```equals()``` method from ```AbstractProperty```, that's why map with nested properties defined only in the class ```ObjectProperty```  is not compared. 

Kind Regards,
Natalia Zolotova

**Comment by frantuma** [comment]
implemented in #3085
