### ISSUE TITLE
Performance degrades in such pattern when using swagger API for rest document

### ISSUE THREAD

**Issue by Ramprabu1983** [swagger-api/swagger-core#3093]
Hi All,
We have swagger enabled in our Spring Boot Microservice project. It really works great. During performance testing we have identified one of request at every 30 seconds takes 8 times higher then the actual time. For instance our API takes usally 30 to 50 ms (milli seconds) to process the request, but the request comes at 30th second will take around 450 ms. We are using routing and load balancer components like Zuul, Eureka, Ribbon and thought some of these components might impact the performance, after removing all these 3 components we still had that performance issue.

We never had a thought about Swagger, but at last we removed the Swagger completely and gained all the performance back, like all request takes only 30 to 50 ms only. We don't know what Swagger is trying to do at every 30th second, even don't have any idea how disable that or atleast extend the 30th second to some other number.

We understand that 450 ms at 30th second costs less only, but we are having millions of requests everyday so we have to fix that.

So did anyone had this problem before or know anything about this issue, please let me know.

Thanks for your time to read this.

**Comment by frantuma** [comment]
Difficult to say, there should be nothing in swagger-core v1 or v2 to cause this behaviour; which project/maven artifact and version are you using? (e.g. `io.swagger:swagger-jaxrs:1.5.21` , `io.swagger.core.v3:swagger-jaxrs2:2.0.6`), and how is that configured?

**Comment by frantuma** [comment]
Ok, so you are Springfox which is a different project, please post this issue in [related project](https://github.com/springfox/springfox)

**Comment by Ramprabu1983** [comment]
Thanks for the right direction.
