### ISSUE TITLE
Schema subclasses contain duplicate fields

### ISSUE THREAD

**Issue by padamstx** [swagger-api/swagger-core#3094]
The way in which the various Schema subclasses (e.g. ArraySchema, StringSchema, etc.) are defined means that they are duplicating certain fields.   For example, StringSchema is defined like this:
```
public class StringSchema extends Schema<String> {
    private String type = "string";
...
}
```
This causes StringSchema to have a DIFFERENT type field than is found in Schema<T>.

To alleviate this, I'm proposing a slight change to Schema like this to introduce a ctor:
```
public class Schema<T> {
    ...
    public Schema(String type, String format) {
        this.type = type;
        this.format = format;
    }
    ...
}
```
and then StringSchema could be changed like this to use this new ctor:
```
public class StringSchema extends Schema<String> {

    public StringSchema() {
        super("string", null);
    }
    ...
}
```
Then BinarySchema could be changed like this:
```
public class BinarySchema extends Schema<byte[]> {

    public BinarySchema() {
        super("string", "binary");
    }
    ...
}
```
And ByteArraySchema could be changed like this:
```
public class ByteArraySchema extends Schema<byte[]> {

    public ByteArraySchema() {
        super("string", "byte");
    }
    ...
}
```
and most of the other Schema subclasses could be changed in a similar way.

Before I submit a PR for these changes, I just wanted to introduce the issue and see if there is general agreement on the solution.   I don't think this will make any functional difference in the classes but would make things a little easier when debugging and would just make good "java sense" I think.
Comments?
cc: @wing328

**Comment by frantuma** [comment]
Thanks for reporting and addressing this! it's indeed an issue which should be addressed, possibly  similarly to your suggestion but slightly different, to maintain existing compatibility specifically for fluent interface.

This would basically mean:
* remove `private` modifier in Schema `type` and `format` members
* remove `type` and `format` members in all subclasses along with getter and setter, keeping fluent setter
* add a public no arg ctor in all subclasses like:

```
    public IntegerSchema() {
        type = "integer";
        format = "int32";
    }
```
* adjust equals, hashcode, and print, removing `type` and `format`

**Comment by padamstx** [comment]
@frantuma Thanks for replying...   I have some local changes that are basically what you've suggested above.   I'll submit a PR soon for this.
