### ISSUE TITLE
Swagger gradle plugin, swagger converter not working

### ISSUE THREAD

**Issue by vikrantk365** [swagger-api/swagger-core#3106]
I'm usign swagger gradle plugin for generating the yaml doc.
I'm able to generate the doc but when I use my custom model converter which converts the plain model into [jsonapi](https://jsonapi.org/) format, it doesn't get reflected in the schemas generated in the yaml file.
I can see that my custom code is getting invoked from the logs.
When I tried the same converter in swagger core unit tests https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/ModelPropertyOverrideTest.java, it works and I can see my custom schema being generated in the unit test.
Could you advice what might be wrong in this case?

**Comment by frantuma** [comment]
A custom model converter, defined in `modelConverterClasses` [parameter](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-gradle-plugin#parameters) of task should work ok, can you share some more details about your config and possibly a test case?

**Comment by vikrantk365** [comment]
Found the cause. I was using `super.resolve` in my converter for resolving part of the model which I think marks processed types and hence my code wasn't working. 
I replaced that part with new instance of `ModelConverterContextImpl` and it started working.
Thanks for such a quick response. Really apprecite it!
