### ISSUE TITLE
Some primitive types in @ApiResponse.content are reported incorrectly

### ISSUE THREAD

**Issue by stauvel** [swagger-api/swagger-core#3111]
Swagger version : 2.0.7-SNAPSHOT

Reproduction :

    @Operation(
        ...
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", 
                content = @Content(schema = @Schema(implementation = Long.class))),
            ....
            }
    ...
    )

Result : 

    ...
    responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: long

Expected :

    ...
    responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int64

**Comment by frantuma** [comment]
for primitive types you wouldn't use `@Schema.implementation`, as they are mapped to OpenAPI types, therefore the following will resolve into expected result:

@Operation(
    ...
    responses = {
        @ApiResponse(responseCode = "200", description = "OK", 
            content = @Content(schema = @Schema(type = "integer", format = "int64"))),
        ....
        }
...
)

**Comment by stauvel** [comment]
So why in are the following lines for, in AnnotationUtils.java ?

    if (schemaImplementation.getName().startsWith("java.lang")) {
                schemaObject.setType(schemaImplementation.getSimpleName().toLowerCase());

**Comment by stauvel** [comment]
OK. I'm going to apply same logic on `resolveSchemaFromType` and to add some tests for String and Objects types.
But I've currently broken my local `swagger-jaxrs2` module for implementing the springBoot module which I need (#3058).
Maybe I could edit ReaderTest later ?

**Comment by stauvel** [comment]
Well @frantuma, I did it : #3112 

I also suggested you to mix implementation with format attribute : #3114

**Comment by frantuma** [comment]
Thanks a lot! eventually merged #3468 which includes and replaces #3112 and #3114
