### ISSUE TITLE
Documentation for the swagger-gradle-plugin appears to give incorrect artifact path

### ISSUE THREAD

**Issue by mjparme** [swagger-api/swagger-core#3115]
The documentation (https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-gradle-plugin) says to use:

`classpath "gradle.plugin.io.swagger.core.v3.swagger-gradle-plugin:2.0.7-SNAPSHOT"`

However, that can't be found:

Could not find gradle.plugin.io.swagger.core.v3.swagger-gradle-plugin:2.0.7-SNAPSHOT

**Comment by bronogard** [comment]
A PR to fix this is available here: https://github.com/swagger-api/swagger-core/pull/3186

**Comment by bronogard** [comment]
Thank you @frantuma for merging into master: https://github.com/swagger-api/swagger-core/commit/afba79c6b2d0d79f9299b58bf6573f06560cc3aa

**Comment by bronogard** [comment]
@mjparme please have a look at the latest release with the proper G(roup)A(rtifact)V(ersion) coordinate.

**Comment by bronogard** [comment]
@frantuma this issue can be seen as resolved
