### ISSUE TITLE
Feature Request: Swagger Maven Plugin should be able to read Swagger config

### ISSUE THREAD

**Issue by patrickfav** [swagger-api/swagger-core#3133]
Currently the maven plugin allows for reading a `openapiFilePath` which expects the file to have the `openApi` element as root, like so:

```
info:
  version: '1.0.0'
  title: REST API
  description: 'The REST API description.'
  contact:
    email: mail@mail.com
  license:
    name: All Rights Reserved
    url: https://license.com
  x-logo:
    url: https://logo.svg
    backgroundColor: "#FFFFFF"
externalDocs:
  description: Docs
  url: 'http://docs/Glossar'
```

However, if one already uses Swagger to dynamically serve the doc over a e.g. Servlet, one usually has a Swagger configuration file with this scheme:

```
resourcePackages:
  - my.package
prettyPrint: false
cacheTTL: 0
openAPI:
  info:
    version: '1.0.0'
    title: REST API
    description: 'The REST API description.'
    contact:
      email: mail@mail.com
    license:
      name: All Rights Reserved
      url: https://license.com
    x-logo:
      url: https://logo.svg
      backgroundColor: "#FFFFFF"
  externalDocs:
    description: Docs
    url: 'http://docs/Glossar'
```

As there is no trivial way to include yaml in yaml, I now would have to maintain 2 openApi configs.

**My suggestion is therefore this:**
Provide a new config named `configurationFilePath` ~swaggerConfigurationFilePath~ which accepts a path to a configuration file as described in https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-file. This file would be parsed before the other configs and has less precedence as a maven plugin defined config. E.g. if provided a `resourcePackages` defined config in maven pom would have higher precedence of the same config defined in the swagger yaml config.

-----------------

Is the team interested in such a feature? I am willing to provide a PR for this.

**Comment by frantuma** [comment]
This sound very good indeed, and it is for sure interesting, possibly applicable also to gradle-plugin. Maybe the config name could be `configurationFilePath`

**Comment by patrickfav** [comment]
Alright, then Id prepare the PR in the next couple of days. I would start with the maven plugin. If we agree on the exact requirement and behaviour, this can then be ported to the Gradle plugin.

> Maybe the config name could be `configurationFilePath`

You are right, this is probably better.

**Comment by frantuma** [comment]
excellent thx!

**Comment by frantuma** [comment]
#3150 merged, thanks!

**Comment by ahoehma** [comment]
@patrickfav can you please check #4647  I think the change from this issue here cause the effects for multiple runs in multimodule projects or multiple executions of the plugin.
