### ISSUE TITLE
Could you add an automatic module name?

### ISSUE THREAD

**Issue by mtdowling** [swagger-api/swagger-core#3138]
Would it be possible to add an automatic module name to https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/pom.xml? This would be useful when trying to use these packages with modular Java 9+ projects. It looks like the inferred module name is "swagger.models".

See: http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by frantuma** [comment]
Thanks for reporting this! implemented in #3139
