### ISSUE TITLE
filter class not loaded

### ISSUE THREAD

**Issue by vikrantk365** [swagger-api/swagger-core#3144]
I'm using swagger gradle plugin to generate openapi spec from jax rs.
As part of it, I have extended the ResolveTask
```java
    @TaskAction
    def generateDoc() {
        def modelConverter = ["my.EntityConverter"] as LinkedHashSet
        setModelConverterClasses(modelConverter)
        setFilterClass("my.ApiOperationFilter")
        println "Model converter classes ${getModelConverterClasses()}, ${getModelConverterClasses()?.size()}"
        println "Filter class ${getFilterClass()}"
        super.resolve()
    }
```
Everything works except filter class doesn't get invoked.
When I use this in a gradle task, I can see that filter class is getting added to the Resolve Task
but anything I print in the filter class simply doesn't get invoked.
Any idea what might be wrong.

Here is filter class
```java
public class ApiOperationFilter extends AbstractSpecFilter {
  private static Logger LOGGER = LoggerFactory.getLogger(ApiOperationFilter.class);

  @Override
  public Optional<OpenAPI> filterOpenAPI(
      OpenAPI openAPI,
      Map<String, List<String>> params,
      Map<String, String> cookies,
      Map<String, List<String>> headers) {
    LOGGER.info("Adding common schemas");
    System.out.println(">>Adding common schemas");
    //  some processing
    return super.filterOpenAPI(openAPI, params, cookies, headers);
  }

  @Override
  public Optional<io.swagger.v3.oas.models.Operation> filterOperation(
      Operation operation,
      ApiDescription api,
      Map<String, List<String>> params,
      Map<String, String> cookies,
      Map<String, List<String>> headers) {
    LOGGER.info("Adding common responses");
    System.out.println(">>Adding common responses");
   // some processing
    return Optional.of(operation);
  }

}
```

**Comment by soberich** [comment]
Hi, maintainers, any update on this? Seems critical. I was able to manually add to sources of gradle plugin  filter invocation by just coping it from another single place where it gets invoked and use local jar, but thought that it will be addressed fast.

**Comment by soberich** [comment]
@frantuma just a ping. Thank you.

**Comment by frantuma** [comment]
Thanks for reporting this! #3183 adds support for filter to maven and gradle plugins; this is available in latest snapshot and upcoming release. Closing ticket, please reopen if you're still experiencing issues
