### ISSUE TITLE
filterClass not executed in swagger-maven-plugin

### ISSUE THREAD

**Issue by manoswerts** [swagger-api/swagger-core#3148]
# Steps to reproduce
1. Create a simple filter class
```
public class SpecFilter extends AbstractSpecFilter {

    @Override
    public Optional<Operation> filterOperation(Operation operation, ApiDescription api, Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
        System.out.println("Filtering operation");

        return super.filterOperation(operation, api, params, cookies, headers);
    }
}
```
2. Specify filter class in plugin configuration
```
<plugin>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-maven-plugin</artifactId>
      <version>2.0.7</version>
      <executions>
          <execution>
              <phase>compile</phase>
              <goals>
                  <goal>resolve</goal>
              </goals>
          </execution>
      </executions>
      <configuration>
          <outputPath>${project.build.directory}</outputPath>
          <outputFileName>openapi</outputFileName>
          <outputFormat>JSON</outputFormat>
          <prettyPrint>true</prettyPrint>

          <resourcePackages>
              <package>com.application.rest</package>
          </resourcePackages>

          <openapiFilePath>${project.basedir}/openapi.json</openapiFilePath>

          <filterClass>com.application.SpecFilter</filterClass>
    </configuration>
</plugin>
```
3. Execute Maven plugin
```
mvn swagger:resolve
```

# Expected result
Filter class is invoked.

# Actual result
Filter class is not invoked. Looking into the source code, the filter class only seems to be invoked in the `ResolveTask` class, which is part of the Gradle plugin.

**Comment by soberich** [comment]
@manoswerts no, doesn't work in Gradle either. Where you've find in source files it works??

**Comment by mtraynham** [comment]
I've encountered this as well.  I think the only place SpecFilter is used is on the API Resource when serving from your own Jaxrs ReST API.

The BaseOpenAPIResource performs the filter [here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/resources/BaseOpenApiResource.java#L55-L66).  I believe the code should instead be moved into the GenericOpenApiContext.read method or even further down into the reader or core classes themselves so the functionality is shared.

**Comment by frantuma** [comment]
Thanks for reporting this! #3183 adds support for filter to maven and gradle plugins; this is available in latest snapshot and upcoming release. Closing ticket, please reopen if you're still experiencing issues
