### ISSUE TITLE
Update Maven Wrapper Distribution

### ISSUE THREAD

**Issue by patrickfav** [swagger-api/swagger-core#3151]
Currently the project uses a quite outdated version of maven wrapper (0.1.2). Current version is 0.5.3 (includes fixes for proxies, basic auth etc), see: https://github.com/takari/maven-wrapper

It is quiet easy to update, just execute:

`mvn -N io.takari:maven:wrapper`

**Comment by frantuma** [comment]
Thanks! PR merged
