### ISSUE TITLE
byte[] not correctly handled by openapi converter

### ISSUE THREAD

**Issue by andreas-eternach** [swagger-api/swagger-core#3154]
I tried to generate an OpenApi-Definition from a java-class.

I run into problems with byte-arrays. Those are generated as openapi-arrays, but the openapi-tools create java-lists for openapi-arrays. 

The OpenApi-Generator should instead generate a string with format binary according to the swagger-spec  (https://swagger.io/docs/specification/data-models/data-types/, section strings)

Please find the sample code in the attachted [openapi-byte-array.zip](https://github.com/swagger-api/swagger-core/files/2969994/openapi-byte-array.zip)

It contains also a maven-pom-template for configuring the maven-swagger-plugin.

I ran the plugin from command line with
```cmd 
mvn io.swagger.core.v3:swagger-maven-plugin:2.0.7:resolve
```

The expected openapi-output for a byte[] is:

```json
        "binaryContent" : {
          "type" : "string",
          "format": "byte", 
          "description" : "base64 encoded binary content."
        }
```
This would would work with the openapi-generator-plugin [https://github.com/OpenAPITools/]:
```xml
    <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>3.3.3</version>
        <executions>
          <execution>
            <id>8djh-jom-client</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/openapi/openapi.json</inputSpec>
              <generateDirectory>${project.build.directory}/generated-sources</generateDirectory>
              <generatorName>java</generatorName>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              
              <configOptions>
                <sourceFolder>test-rest-client</sourceFolder>
                <apiPackage>test.api</apiPackage>
                <modelPackage>test.model</modelPackage>
                <library>resttemplate</library>
                <dateLibrary>java8</dateLibrary>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>

```

do i miss something? Do i need to register a converter ?

**Comment by andreas-eternach** [comment]
There exists an annotation for doing such stuff, check my issue in the other project: 
https://github.com/openapi-tools/swagger-maven-plugin/issues/22

**Comment by LexxZone** [comment]
Do we have the same solution for swagger-gradle-plugin?

**Comment by Shmarkus** [comment]
I'm using swagger-gradle-plugin. For me the workaround is to annotate byte[] field with
```java
import io.swagger.v3.oas.annotations.media.Schema;

public class MyDTO {
    @Schema(type = "string", format = "byte")
    private byte[] content;
}
```
