### ISSUE TITLE
Unable to use custom ModelConverter for custom typename resolving

### ISSUE THREAD

**Issue by poornimap** [swagger-api/swagger-core#3157]
Hi,
I'm using swagger-jaxrs2 to generate the open api spec and I'm ran into the use case where swagger doesn't understand multiple classes with the same name present in different packages, As per PR #2797, this can be fixed using custom typename resolving . 

However, I don't understand how to inject a custom model converter because:

1) io.swagger.v3.jaxrs2.Reader class in swagger-jaxrs2, internally calls io.swagger.v3.core.util.ParameterProcessor to process parameters into Schema objects, but there is no way to inject a custom model converter (similar to the example shown in CustomResolverTest) here. ParameterProcesser uses the default model converter.

2) io.swagger.v3.jaxrs2.Reader class in swagger-jaxrs2 also uses the default ModelConverter to parse the response object into Schema and here too, there is no way to inject a custom model converter.

Is there a way to get around this?

**Comment by frantuma** [comment]
Both Reader and ParameterProcessor make use of converters via `ModelConverters.getInstance()` therefore allowing to inject a custom converter; #2797 is related to 1.x line (1.5 branch), while I assume you are using 2.x/master; in this case please check [#2798](https://github.com/swagger-api/swagger-core/pull/2798/files#diff-63ba5a2bff7f7c6c77c740d01ceed0c3R42) instead; custom converters can be added via [config](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties) (see `modelConverterClasses` field) or [programmatically](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver) 

please close ticket if it answers your question.

**Comment by poornimap** [comment]
Hello,
Thank you for the prompt response. This answers my question. Closing the ticket.
