### ISSUE TITLE
Update Dropwizard instructions to use an external configuration

### ISSUE THREAD

**Issue by matthewbryancurtis** [swagger-api/swagger-core#3159]
Hey there! Love using Swagger, so thanks a bunch.

I spent most of the afternoon beating my head on how to use an external config with Dropwizard, maybe there can be an example somewhere that uses `configLocation`?

What ended up working for me was:

``` Java
environment.jersey().register(new OpenApiResource()
    .configLocation("/openapi.yaml"));
```

Since descriptions can be kinda long, it seems to make more sense than the [provided example](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#dropwizard) (though I realize that example is meant to highlight doing it programmatically).

The docs seem to suggest that all that is needed is to install the dependency and create a config file, but that didn't really work for me. Is there a way to submit a PR for the wiki?

**Comment by frantuma** [comment]
Any enhancement is welcome! one way to do it (no PRs on wiki, sorry) is to clone the wiki repo https://github.com/swagger-api/swagger-core.wiki.git and fork it and update on fork, we would then merge with main repo.

However an example using `configLocation` as in your snippet is provided as commented code in the example you shared and in linked [dropwizard sample](https://github.com/swagger-api/swagger-samples/blob/2.0/java/java-dropwizard/src/main/java/io/swagger/sample/SwaggerSampleApplication.java#L75).

`The docs seem to suggest that all that is needed is to install the dependency and create a config file` : as mentioned in wiki, this is true in scenarios where the environment (e.g. standard jersey) allows to define resources (e.g. via init param), which would include `OpenAPIResource`; in dropwizard `OpenAPIResource` (or any [alternative](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#exposing-openapi-definition)) must be registered, as you mention.

**Comment by matthewbryancurtis** [comment]
Thank you for clarifying! I must be braindead this week, can't believe I missed those other examples. That's good to know, thank you.
