### ISSUE TITLE
Make default method in ObjectMapperProcessor

### ISSUE THREAD

**Issue by soberich** [swagger-api/swagger-core#3163]
The suggestion is to make no-op method default, since now warning is issued and linters are aware of this deprecated override.
https://github.com/swagger-api/swagger-core/blob/cefc0b4816a96d09642d204cce4427d72cec7cc7/modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/ObjectMapperProcessor.java#L17
so it would become
```java

  
package io.swagger.v3.oas.integration.api;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * @since 2.0.6
 */
public interface ObjectMapperProcessor {

    void processJsonObjectMapper(ObjectMapper mapper);

    /**
     * @deprecated since 2.0.7, as no-op
     *
     */
    @Deprecated
    default void processYamlObjectMapper(ObjectMapper mapper) {
        // no-op
    }
}
```

**Comment by frantuma** [comment]
it sounds like an excellent solution, would you be able to add a PR maybe?

**Comment by soberich** [comment]
Implemented in https://github.com/swagger-api/swagger-core/commit/2fc7f6063e5868e63e3dc1d1c41caab247309278
