### ISSUE TITLE
SpecFilter uses non-filtered OpenAPI to copy some fields

### ISSUE THREAD

**Issue by kokorin** [swagger-api/swagger-core#3173]
io.swagger.v3.core.filter.SpecFilter#filter()
```
OpenAPI clone = new OpenAPI();
clone.info(filteredOpenAPI.getInfo());
clone.openapi(filteredOpenAPI.getOpenapi());
clone.setExtensions(openAPI.getExtensions());
clone.setExternalDocs(openAPI.getExternalDocs());
clone.setSecurity(openAPI.getSecurity());
clone.setServers(openAPI.getServers());
clone.tags(filteredOpenAPI.getTags() == null ? null : new ArrayList<>(openAPI.getTags()));
...
for (String resourcePath : openAPI.getPaths().keySet()) {
```

Notice that for some properties filteredOpenAPI is used to copy, but for others non-filtered openAPI is used.

As a workaround we update original OpenAPI  passed to OpenAPISpecFilter

**Comment by frantuma** [comment]
Thanks for reporting this! fixed in #3176

**Comment by kokorin** [comment]
@frantuma for loop is still based on no filtered `OpenApi`.
I believe it should also use `filteredOpenAPI`

`for (String resourcePath : filteredOpenAPI.getPaths().keySet()) {`

**Comment by kokorin** [comment]
Also, may be it's better to replace above mentioned key-based loop with entrySet-based loop

**Comment by frantuma** [comment]
you're right, updated in #3177; as we use path key downstream, keeping key based loop as is
