### ISSUE TITLE
swagger-maven-plugin combines specs in multi-module project

### ISSUE THREAD

**Issue by cjmaloof** [swagger-api/swagger-core#3179]
I'm trying to build a multi-module project defined as below. When I build the subprojects individually, they both build correct Swagger specs. When I build the parent project, the first module builds correctly, but the second module builds a spec with the combined APIs from both modules.

Note that both projects have identically-named resource packages. I've tried setting different `contextId` values within a configuration for each subproject, but it didn't seem to help.

This is version 2.0.7 of the plugin.

```
<modules>
    <module>api-1</module>
    <module>api-2</module>
</modules>

<build>
    <resources>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>2.0.7</version>
                <configuration>
                    <outputFileName>${project.artifactId}-swagger</outputFileName>
                    <outputPath>${project.build.directory}/swagger</outputPath>
                    <openapiFilePath>${project.build.outputDirectory}/openapi-info.json</openapiFilePath>
                    <outputFormat>JSONANDYAML</outputFormat>
                    <prettyPrint>TRUE</prettyPrint>
                    <resourcePackages>
                        <package>com.mycompany.api.resource</package>
                    </resourcePackages>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
```

**Comment by frantuma** [comment]
setting different `contextId` is the way to go, how are you configuring that? each module would need to have its own configuration

**Comment by ChristianLutz** [comment]
Hello,

I am having the same problem. I configured it like this

    <plugin>
        <groupId>io.swagger.core.v3</groupId>
        <artifactId>swagger-maven-plugin</artifactId>
        <version>${swagger.version}</version>
        <executions>
            <execution>
                <id>complete-web-api</id>
                <phase>compile</phase>
                <goals>
                    <goal>resolve</goal>
                </goals>
                <configuration>
                    
                </configuration>
            </execution>
            <execution>
                <id>custom-web-api-only</id>
                <phase>compile</phase>
                <goals>
                    <goal>resolve</goal>
                </goals>
                <configuration>
                    
                </configuration>
            </execution>
        </executions>
    </plugin>

I will try the contextId

**Comment by ChristianLutz** [comment]
Yes adding the `contextId` fixes it for me. Thanks.

**Comment by qianlong** [comment]
I have the same problem, tried with `contextId` but still no luck. I've configured it in a profile in children's pom.xml. I can't configure it in parent pom because some sub-module are not swagger resolvable.
