### ISSUE TITLE
Ordering endpoints

### ISSUE THREAD

**Issue by Khyme** [swagger-api/swagger-core#3191]
Is there a way to order the endpoints in the generated .json ? Example :

```
	@GET
	@Path("/list")
...
	@GET
	@Path("/findOne")
...
	@POST
	@Path("/create")
```

is generated as

```
"paths" : {
    "/findOne" : {
      "post" : {
...
    },
    "/create" : {
      "post" : {
...
    },
    "/list" : {
      "get" : {
...
      }
    },
```

when keeping the same order would be more logical

**Comment by Khyme** [comment]
I got an answer 

>  if you want to control the display, you need to do it in the rendering engine.

**Comment by tGuichin** [comment]
What does that mean?  Can you elaborate what it's meant by "do it in the rendering engine"?

**Comment by Khyme** [comment]
@tGuichin in my case I used this openapi spec to display it on a webpage. multiple projects exist for this. I forked one and added the desired order for the display (I.e. a logical CRUD order by endpoint domain)
