### ISSUE TITLE
JAXRS Application#getClasses() seems to be ignored by swagger JAXRS processor

### ISSUE THREAD

**Issue by tosix1988** [swagger-api/swagger-core#3195]
I have a question related to swagger JAX-RS integration. 

Suppose I have an instance of javax.ws.rs.core.Application subclass in my module, and in its #getClasses() method I explicitly list all the REST endpoints the JAX-RS application should deploy. Now the JAX-RS specification says that whenever this method returns non-empty collection, it should consider only these classes for deployment.

However, when I add the swagger-jaxrs integration and check the contents of the generated swagger.json file, it contains also the endpoints I have not listed in javax.ws.rs.core.Application subclass. 

An example project is here: [swagger-maven-plugin-sample-project2.zip](https://github.com/swagger-api/swagger-core/files/3120558/swagger-maven-plugin-sample-project2.zip). When hitting /api/openapi.json, the file contains the description of a resource on /api/anothertest/something, however, no such endpoint exist in the deployed application. 

I know I can list the endpoint as hidden, but shouldn't the swagger-jaxrs integration consider this when scanning the classpath (Application#getClasses())?

**Comment by frantuma** [comment]
As mentioned in https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-configuration#resource-scanning, you can provide a different scanner implementation to configuration, in your case `io.swagger.v3.jaxrs2.integration.JaxrsApplicationScanner` would achieve what you need; please close ticket if this answers your question

**Comment by tosix1988** [comment]
Hi @frantuma, thanks for a quick response. I think that this is what I needed, I somehow missed it in the spec. Thanks.
