### ISSUE TITLE
Jackson dependencie causing failure

### ISSUE THREAD

**Issue by Maxima078** [swagger-api/swagger-core#3203]
Hi,

I'm using 2.0.8 to generate openapi.json at build time but facing [this issue](https://github.com/swagger-api/swagger-core/issues/1801).
Jackson is 2.9.8, Jersey 2.28 and I had to add jersey-hk2 after Jersey upgrade. Any way to workaround this?
Note that downgrading Jackson to 2.5.4 did not help.

Thanks

**Comment by frantuma** [comment]
assuming you are returning `ObjectNode` as described in linked ticket, and you want to resolve `ObjectNode` as a free-form Object, this would map to a schema of type object in OpenAPI, and you can achieve it by providing a custom converter. The same would apply If you need to resolve it to something different.

e.g.


```
public class ObjectNodeConverter implements ModelConverter {

    @Override
    public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
        JavaType _type = Json.mapper().constructType(type.getType());
        if (_type != null) {
            Class<?> cls = _type.getRawClass();
            if (ObjectNode.class.isAssignableFrom(cls)) {
                return new ObjectSchema();
            }
        }
        if (chain.hasNext()) {
            return chain.next().resolve(type, context, chain);
        } else {
            return null;
        }
    }
}
```

depending on your scenario, you would configure the custom converter either via [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration) using `modelConverterClasses` property, or [programmatically](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver)

Please close ticket if this answers your question

**Comment by Maxima078** [comment]
Indeed it fixed it. Many thanks!
