### ISSUE TITLE
Reference values are not set as required

### ISSUE THREAD

**Issue by ChristianLutz** [swagger-api/swagger-core#3218]
Hello,

I do have this simple model

    @Schema
    @XmlRootElement(name = "a")
    @XmlAccessorType(XmlAccessType.FIELD)
    public class A {
        @Schema(description = "value", required=true)
        @XmlElement
        private B refValue;
    }
    
    @Schema
    @XmlRootElement(name = "b")
    @XmlAccessorType(XmlAccessType.FIELD)
    public class B {
        @XmlElement
        private String b;
    }

creating the openapi.json file with the current version (2.0.8) creates the following output

    "a" : {
      "type" : "object",
      "properties" : {
        "refValue" : {
          "$ref" : "#/components/schemas/b"
        }
      }
    },
    "b" : {
      "type" : "object",
      "properties" : {
        "b" : {
          "type" : "string"
        }
      },
      "description" : "value"
    }

The problem is within in type `a` the `required` field is missing. It should look like

    "a" : {
      "required": [ "refValue" ],
      "type" : "object",
      "properties" : {
        "refValue" : {
          "$ref" : "#/components/schemas/b"
        }
      },
      "xml" : {
        "name" : "a"
      }
    }

otherwise the required `refValue` from class `A` isn't required anymore. I tested it with codegen angular. If I add the required attribute by hand, the created ts model require model `b` if not. It is an optional field and this is wrong.

kind regards

**Comment by THyyy** [comment]
When I use Swagger versions 2.7.1 and 2.9.1, like this：  

    @GetMapping("/customers/{custId}")
    @ApiOperation(value = "根据客户号查找客户信息")
    @ApiImplicitParam(name = "custId", value = "客户号", required = true, dataType = "Integer")  
    public ResultVO searchById(@PathVariable Integer custId){}
  
And I use swagger-ui to try it out, set custId = 15. It will cause the error, like this:    

![image](https://user-images.githubusercontent.com/25731496/59973328-31570200-95d1-11e9-938a-328a2925688d.png)
  
But when I delete `required = true` , it run as I expected. 

What is the cause of this problem?

**Comment by ChristianLutz** [comment]
Hello @THyyy,
I don't know. I guess this is question you should ask in SO. And it isn't related to my provided topic. Sorry.

**Comment by THyyy** [comment]
Oh, I should pose a new issue. Sorry!

**Comment by ChristianLutz** [comment]
I'll close this in favor of. #3259
