### ISSUE TITLE
will the swagger-servlet module see 3.0 spec support?

### ISSUE THREAD

**Issue by datagitlies** [swagger-api/swagger-core#3239]
The current version of `swagger-servlet` is only compatible with the 2.0 spec. What is the future of this module? Long-term, I'm wanting 3.0 spec support since I currently use it. I'd be willing to work on a pull request but before I go that route I'm wondering if I'm missing something... like if there was a good reason `swagger-servlet` was excluded from the 2.X releases and I should be looking for an alternative.

**Comment by datagitlies** [comment]
Bump?

**Comment by frantuma** [comment]
no specific reason other than focus on JAX-RS support, and a PR adding a "ServletReader" support is welcome!

**Comment by datagitlies** [comment]
@frantuma After looking over the available options, I believe I'll be able to use [`swagger-jaxrs2`](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jaxrs2) but I may need to extend the [`Reader`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/Reader.java).  I've hit a small snag with that approach but I'll open a new issue & PR for that.  As for this issue, I'm going to go ahead and close it as it doesn't appear I will be needing the `swagger-servlet` module after all.
