### ISSUE TITLE
ObjectMapperProcessor doesn't work with swagger-maven-plugin

### ISSUE THREAD

**Issue by seanf** [swagger-api/swagger-core#3247]
The attached project has a JAX-RS end-point which returns a Java 8 `Stream` of `String`. It configures swagger-maven-plugin with the parameter `objectMapperProcessorClass` to provide an `ObjectMapperProcessor` which registers Jackson's Java 8 module. 

```xml
                <configuration>
                    <outputPath>${basedir}/target</outputPath>
                    <outputFileName>swagger</outputFileName>
                    <outputFormat>JSON</outputFormat>
                    <objectMapperProcessorClass>org.example.objectmappertest.ObjectMapperProcessor</objectMapperProcessorClass>
                    <resourcePackages>
                        <package>org.example</package>
                    </resourcePackages>
                    <prettyPrint>true</prettyPrint>
                </configuration>
```

The log message during the build shows that the `ObjectMapperProcessor` _is_ being called, but it seems to make no difference to the generated `swagger.json`.

The project: [objectmappertest.zip](https://github.com/swagger-api/swagger-core/files/3390691/objectmappertest.zip)

`mvn clean package; cat target/swagger.json`:

```json
{
  "openapi" : "3.0.1",
  "paths" : {
    "/api/greetings" : {
      "get" : {
        "operationId" : "greetings",
        "responses" : {
          "default" : {
            "description" : "default response",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "parallel" : {
                      "type" : "boolean"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

The response type for `/api/greetings` should be an `array` of `string`, but instead it is an `object` with a single `boolean` property `parallel`.

I've noticed a similar effect with swagger-jaxrs2-servlet-initializer - it appears that the `ObjectMapperProcessor` (or its customised ObjectMapper) is used at runtime when _invoking_ the REST API, but the `swagger.json` which is generated at runtime by the swagger-jaxrs2-servlet looks like the one generated by swagger-maven-plugin (ie it doesn't map `Stream` to an `array`).

See also this comment about the gradle plugin, which sounds like it might be the same problem: https://github.com/swagger-api/swagger-core/issues/2828#issuecomment-499561964

**Comment by frantuma** [comment]
This doesn't seem to be an issue with the `objectMapperProcessor`, it's related to the resolving mechanism, which is applied to the return type (for example). Additionally, in this case I believe no Type Modifier for `Stream` class are provided by `JDK8Module`.

To achieve what you need, you can either annotate the method with `@Response` specifying the schema to use (like `@ArraySchema(@Schema(type="string"))` or handle this globally by adding a custom converter like:


```java
public class StreamConverter implements ModelConverter {

    @Override
    public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
        final JavaType jType = Json.mapper().constructType(type.getType());
        if (jType != null) {
            final Class<?> cls = jType.getRawClass();
            if (cls.equals(Stream.class)) {
                return new ArraySchema().items(new StringSchema());
            } else {
                return chain.next().resolve(type, context, chain);
            }
        } else {
            return null;
        }
    }
}
```

and applying it by providing `<modelConverterClasses>foo.bar.StreamConverter</modelConverterClasses>` in the plugin config.

Closing ticket, please reopen if you're still experiencing issues
