### ISSUE TITLE
@ArraySchema annotation doesn't override item schema properly

### ISSUE THREAD

**Issue by morhei** [swagger-api/swagger-core#3255]
Hi,

I try to create a file in OpenAPI format with the following Java code:

```
import javax.mail.internet.InternetAddress;

{...}

@JsonProperty("mails")
@JsonSerialize(contentUsing = ToStringSerializer.class)
@ArraySchema(arraySchema = @Schema(description = "the email addresses"),
   schema = @Schema(example = "user@mail.de", type = "string"))
public Collection<InternetAddress> getMailss() {
        return m_mails;
}
```

which results in:

```
"mails" : {
 "type" : "string",
 "example" : "user@mail.de"
}
```

whereas I would expect:

```
"mails" : {
 "type" : "array",
 "description" : "the email addresses",
 "example" : "user@mail.de"
 "items" : {
  "type" : "string"
 }
}
```

Without the schema = @Schema(example = "user@mail.de", type = "string") I get

```
"mails" : {
 "type" : "array",
 "items" : {
  "type" : "object",
  "properties" : {
   "address" : {
    "type" : "string"
   },
   "personal" : {
    "type" : "string"
   },
   "group" : {
    "type" : "boolean"
   },
   "type" : {
    "type" : "string"
   }
  }
 }
}
```

However, they will be represented as simple strings to make it easier for usage.
Am I doing something wrong?
The swagger annotations artifact we use is version 2.0.8

Thanks,
morhei

**Comment by webron** [comment]
You've mentioned swagger annotations specifically. Are you using swagger-core to generate your documentation or a different library?

**Comment by morhei** [comment]
Yes, we use swagger-core to generate the documentation.

**Comment by StephenOTT** [comment]
seeing similar issue with 2.0.4

arraySchema = Schema(description = "some description") never gets applied to the generated yml

**Comment by frantuma** [comment]
This doesn't seem to be reproducible with latest version, code as in example resolves correctly into:

```
mails:
      type: array
      description: the email addresses
      items:
        type: string
        example: user@mail.de
```

also `arraySchema = Schema(description = "some description")` results in correct code.

Closing ticket, please reopen if you're still experiencing issues (please provide the version, environment and full annotated code)
