### ISSUE TITLE
Use swagger with Spring 5 Functional Web Framework with Java

### ISSUE THREAD

**Issue by hichmo** [swagger-api/swagger-core#3265]
Hi All,

I try to use swagger with swagger with Spring 5 Functional Web Framework and Java.

An example, I have this router class and I want to generate the swagger specification.
Is this functionality exists in latest version ?

    @Configuration
    public class Routes {

    @Autowired
    private CyclistHandler cyclistHandler;

    @Bean
    public RouterFunction<ServerResponse> routerCyclist() {
        return route(GET("/cyclists"), cyclistHandler::handleFindAll)
                .andRoute(GET("/cyclists/{id}"), cyclistHandler::handleFindById)
                .andRoute(POST("/cyclists"), cyclistHandler::handleCreate)
                .andRoute(PUT("/cyclists/{id}"), cyclistHandler::handleUpdate)
                .andRoute(DELETE("/cyclists/{id}"), cyclistHandler::handleDelete);
    }
}
Thanks for the help.

**Comment by webron** [comment]
Swagger-core is not intended to be used with Spring but rather JAX-RS. Please take a look at [Springfox](https://github.com/springfox/springfox).
