### ISSUE TITLE
Use Swagger-SpringMVC and Request Controller Resources and Got an 404 error

### ISSUE THREAD

**Issue by yyconstantine** [swagger-api/swagger-core#3267]
Hi, I'm working for a project version like this:
spring: 3.2.5.RELEASE
swagger-springmvc: 1.0.2.RELEASE

Now i can enter the swagger-ui(or index.html), but the request the cotroller resources return an 404  error for all the controllers, so there's no api.

From the swagger-ui.js, I find thr absolutePath is error with my web.xml add an suffix ’.do'
eg:
the wrong request url: http://localhost:8080/project/api-docs.do/default/some-controller
the right request url: http://localhost:8080/project/api-docs/default/some-controller.do
I send the right url and get the info like appversion,method,summary etc.

**Comment by webron** [comment]
I'm sorry, but swagger-springmvc is not one of our projects and is unrelated to swagger-core. You'd need to post the issue in their project.
