### ISSUE TITLE
Cannot get OpenAPIDefinition annotation to work with "Extend BaseOpenApiResource" approach

### ISSUE THREAD

**Issue by jbraga** [swagger-api/swagger-core#3268]
I'm building a Jax-Rs API on a JEE application that runs on Wildfly.

I'm considering swagger (OpenAPI) annotations as the documentation mechanism. However, I can't even get the @OpenAPIDefinition annotation to work (a bit frustrating, to be honest). It's worth mentioning that I'd much prefer this approach over the definition file or the web.xml setup.

Here's part of my application class:

```
@OpenAPIDefinition(
    info = @Info(
        title = "Account API",
        version = ApiConstants.API_VERSION,
        termsOfService = "#",
        contact = @Contact(
            name = "Support Team",
            url = "https://worldnettps.com/contact/",
            email = "support@worldnettps.com"),
        license = @License(
            name = "Use and Distribution License",
            url = "#"),
        description = "description")
    )
@ApplicationPath("api/account")
public class AccountApi extends Application {

    /*
     * (non-Javadoc)
     * @see javax.ws.rs.core.Application#getClasses()
     */
    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> classes = super.getClasses();
        classes.add(ApiDocsController.class);
        classes.add(AuthController.class);
        return classes;
    }
}
```

And here's the custom resource class which extends BaseOpenApiResource:

```
@Path("/api-docs")
public class ApiDocsController extends BaseOpenApiResource {

    @Context
    ServletConfig config;

    @Context
    Application application;

    @GET
    @Produces({ APPLICATION_JSON })
    @Operation(hidden = true)
    public Response getOpenApiJson(@Context HttpHeaders headers,
        @Context UriInfo uriInfo) throws Exception {

        return super.getOpenApi(headers, config, application, uriInfo, "json");
    }

    @GET
    @Produces({ "application/yaml" })
    @Operation(hidden = true)
    public Response getOpenApiYaml(@Context HttpHeaders headers,
        @Context UriInfo uriInfo) throws Exception {

        return super.getOpenApi(headers, config, application, uriInfo, "yaml");
    }
}
```

I've added a Operation annotation on the method in AuthController to test and it works fine, but the OpenAPIDefinition has no effect at all in the response below:

```
{
    "openapi": "3.0.1",
    "paths": {
        "/api/account/authenticate": {
            "get": {
                "tags": [
                    "authenticate"
                ],
                "description": "Retrieves an authentication JWT token with the API permissions/claims, to be used as the request Authentication Key of all the other services of the REST APIs.",
                "operationId": "authenticate",
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "default": {
                        "description": "default response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        }
   }
    // Components
}
```

Am I missing something, guys?

**Comment by lgoltz** [comment]
We have nearly the same problem. The only difference is that we create the OpenAPIDefinition programmatically as in the example https://github.com/swagger-api/swagger-samples/blob/2.0/java/java-jersey2-resourceinit/src/main/java/io/swagger/sample/MyApplication.java 

It seems that the custom resource class extending the BaseOpenApiResource does not use the OpenAPIDefinition created programmatically or by annotation. 
Removing this resource leads to the expected result: the information from the OpenAPIDefinition appears in the response. Otherwise they are missing.

@jbraga Did you find a solution or at least a workaround or this?

**Comment by jbraga** [comment]
Hi @lgoltz, we've decided to put the definition (Info, Tags and Security Schemes) in a yaml file.

I've followed this approach: https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#your-own-configuration

**Comment by lgoltz** [comment]
Great you find a solution! 
This is not a way for us as the content of the OpeanAPIDefinition is dynamic. 
Does anyone else has an idea? We are using Swagger 2.1.0.

**Comment by frantuma** [comment]
@lgoltz This should work ok, can you share how are configuring and registering swagger config and resource?

**Comment by lgoltz** [comment]
@frantuma Thanks for your reply. 

The resource was not registered. We added: 
```
        MyOpenApi openApiResource = new MyOpenApi();
        openApiResource.setOpenApiConfiguration(oasConfig);
        register(openApiResource);
```
And it works fine now!
