### ISSUE TITLE
Swagger ignores custom ModelConverter

### ISSUE THREAD

**Issue by esscue23** [swagger-api/swagger-core#3277]
Following the example [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver), I implemented and registered a custom model converter in order to override the standard conversion. 

Unfortunately, my custom converter is ignored and the standard conversion is performed.

When I look in a debugger at the ModelConverters Singleton, I realized that my custom converter is placed at position 0 in the list:
![image](https://user-images.githubusercontent.com/32244195/63536299-9a94bc00-c513-11e9-8a0b-1376d19c9ad0.png)

Position 0 of the list "converters" contains my custom converter CatalogLoader$SamplePropertyConverter. Position 1 of the list contains the ModelResolver for jackson annotations.

The behavior is logical, when I look at the [code](https://github.com/swagger-api/swagger-core/blob/9aed89e247cac228cc0ebd6d4f69ad0de0494d61/modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverters.java#L38). The "addConverter" method adds the element to position 0.

Looking at the code inside the [ModelConverterContextImpl](https://github.com/swagger-api/swagger-core/blob/9aed89e247cac228cc0ebd6d4f69ad0de0494d61/modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverterContextImpl.java#L90) it seems that the last model converter in the list always wins.

Is this behavior intended? Is the [test case](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/CustomConverterTest.java) really working?

I'm using version 2.0.8 of swagger.

**Comment by frantuma** [comment]
this is intended behaviour and should work ok (test case is working..). 

^^ `it seems that the last model converter in the list always wins.` 

is the other way around, first converter found is invoked, it would be any custom converter added via `addConverter`; such custom converter invokes next converter in the chain for cases it doesn't handles (`return chain.next().resolve(type, context, chain);` - if needed, as usually the case where specific scenarios are handled by custom converter and the rest left for `ModelResolver`)

If you're still experiencing issues, please share the custom converter and config

**Comment by esscue23** [comment]
Thank you @frantuma  for you quick answer. 

This is my converter:
```Java
	public class SamplePropertyConverter implements ModelConverter {

	    @Override
	    public io.swagger.v3.oas.models.media.Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
	        if (type.isSchemaProperty()) {
	            JavaType _type = Json.mapper().constructType(type.getType());
	            if (_type != null) {
	                Class<?> cls = _type.getRawClass();
	                if (cls.equals(com.allianz.kb.Catalog.class)) {
	                	io.swagger.v3.oas.models.media.Schema<com.allianz.kb.Catalog> schema = new io.swagger.v3.oas.models.media.Schema<com.allianz.kb.Catalog>();
	                	io.swagger.v3.oas.models.media.Schema<Object> name_schema = new io.swagger.v3.oas.models.media.Schema<>();
	                	schema.setName("Catalog");
	                	schema.setType("object");
	                	XML xml_attribute = new XML();
	                	xml_attribute.setAttribute(true);
	                	name_schema.setXml(xml_attribute);
	                	name_schema.setType("string");
	                	schema.addProperties("name", name_schema);
	                	return schema;
	                	//return null;
	                }
	            }
	        }
	        if (chain.hasNext()) {
	            return chain.next().resolve(type, context, chain);
	        } else {
	            return null;
	        }
	    }
	}
```

and this is how I register him

```Java
		SamplePropertyConverter converter = new SamplePropertyConverter();
		ModelConverters.getInstance().addConverter(converter);
```

When I run in debug mode, I can verify that my custom converter is really invoked.

I understand the logic of the converter chain and you are right, then the first one would win. What confuses me is the code in the [ModelConverterContextImp](https://github.com/swagger-api/swagger-core/blob/9aed89e247cac228cc0ebd6d4f69ad0de0494d61/modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverterContextImpl.java#L90) which also iterates through all the converters. Wouldn't this lead to the last converter winning?

**Comment by frantuma** [comment]
that code doesn't iterate, it picks the first one (`if (converters.hasNext()) `, not `while`)

if I get it right, your converter gets correctly invoked, please close thicket if that's the case

**Comment by esscue23** [comment]
Sorry, you are right. My fault, I missed that it's only an `if` statement.

I just wanted to say that my converter gets invoked, but the result in the swagger documentation is not my conversion, but the default one. I continue to investigate, what's happening in my case.

**Comment by esscue23** [comment]
Now I found the issue. The example provided [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver) only works for properties of the response type, but not in case I want to override the conversion of the response type itself. After removing the check `type.isSchemaProperty()` it works as expected.
