### ISSUE TITLE
@JsonSerialize support in 2.0

### ISSUE THREAD

**Issue by kingcowman** [swagger-api/swagger-core#3288]
A feature to support @JsonSerialize(as = x.class) annotations was added as part of release 1.5.14
https://github.com/swagger-api/swagger-core/releases/tag/v1.5.14

However as part of the 2.0 rewrite this feature was removed. Would it be possible to add back in?

**Original Issue** #2084
**Original PR That Resolved Issue**  https://github.com/swagger-api/swagger-core/pull/2147
**Most Recent PR in 1.5** #3264

**Comment by jimmycob** [comment]
any update ?

thanks

**Comment by frantuma** [comment]
Thanks for reporting this. Also see #3042, implemented in #3043 .
