### ISSUE TITLE
Producing allOf with $ref and additional properties using @Schema annotations?

### ISSUE THREAD

**Issue by DSW-PS** [swagger-api/swagger-core#3290]
I'm trying to figure out if it is possible to produce something like

    w307BetrBeg:
      title: 'Betrag'
      description: 'BETRAG BEGUENSTIGTER'
      allOf:
        - $ref: '#/components/schemas/Betrag'

using the ```@Schema``` annotation.

I thought that the following use should produce what I want:

    @Schema(name = "w307BetrBeg", description = "BETRAG BEGUENSTIGTER ", 
    allOf = { com.diesoftware.services.utils.Betrag.class }, required = true)
    public void setW307BetrBeg(final Betrag w307BetrBeg) {
      this.w307BetrBeg = w307BetrBeg;
    }

But instead I end up with:

    w307BetrBeg:
      $ref: '#/components/schemas/Betrag'

According to [this commont](https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-192007034) on the related issue on the OpenAPI-Spec itself, it is valid in the API and it seems like the suggested way to do if you are writing the API by hand.

Is this a parser/annotation issue or am I using the annotation wrong?

**Comment by Kadams64** [comment]
I have exactly the same question.  I'm using Swagger 2.0.9, and use of the _allOf_ property of _@Schema_ as described by the original poster doesn't seem to produce the expected OpenAPI.json output

- I had originally raised a related issue regarding Swagger UI not rendering descriptions for nested entities, and was given the guidance to use the 'allOf' construct...=> https://github.com/swagger-api/swagger-ui/issues/5139
- I waited until we had completed an upgrade to Swagger 2.0.9 and the OpenApi V3 specification on the assumption that this would (should) work

Thoughts or help appreciated.

**Comment by kochn** [comment]
Hi, I have the same issue. Here my concrete example:

```
@Data
public class Measurement {

    @Schema(description = "Description Value A")
    private TimedValue valueA;

    @Schema(description = "Description Value B")
    private TimedValue valueB;

}

```
```
@Data
public class TimedValue {
    private BigDecimal value;
    private Instant measuredValue;
}
```

The workaround above describes, to use `allOf` to solve this conflict. Nevertheless this is not applicable in Java:
```yaml

          allOf:
            - "$ref": "#/components/schemas/TimedValue"
            - description: "Description Value B"

```
The reason is, that `@Schema` needs Java implementation classes. Am I the only one, who needs to describe attributes with same base object but different descriptions?

**Comment by frantuma** [comment]
this has been addressed implementing new config property and annotation as detailed in [wiki](https://github.com/swagger-api/swagger-core/wiki/OpenAPI-3.0-Schema-Resolution)
