### ISSUE TITLE
Swagger Description

### ISSUE THREAD

**Issue by satishpatro44** [swagger-api/swagger-core#3297]
In spring boot

    @Api(value = "Employee Management System", description = "ABCD")
    public class UserController {

the description is deprecated. I tried tag but it is not able to replace description.

What is the alternative

Question is related to #1476

**Comment by webron** [comment]
Which version of swagger-core do you use? Are you using swagger-core directly or Springfox?

**Comment by satishpatro44** [comment]
implementation group: 'io.springfox', name: 'springfox-swagger2', version: '2.9.2'
    implementation group: 'io.springfox', name: 'springfox-swagger-ui', version: '2.9.2'
isn't it internally uses swaggger-core ?

**Comment by webron** [comment]
It uses the annotations, but that's it. Please file the issue with Springfox as they may have a solution for it.

**Comment by satishpatro44** [comment]
I need to understand one thing


`String io.swagger.annotations.Api.description() : ""

@Deprecated

Not used in 1.5.X, kept for legacy support.
Returns:a longer description about this API, no longer used.`

if it is of swagger io depreciation, why should I raise query to spring fox?
