### ISSUE TITLE
$refs within items don't get added to list of schemas when `isRemovingUnreferencedDefinitions`

### ISSUE THREAD

**Issue by ethan92429** [swagger-api/swagger-core#3303]
When the schema has an arraySchema that has items that are in turn a $ref, that ref doesn't get followed to add all of its children refs. In fact, I think this happens anytime there are refs of refs. This logic only goes one ref level deep. I was able to work around this in a PR I will post and link to this issue.

**Comment by ethan92429** [comment]
Tried to make the PR through GH's online edit tool, but it got mangled. Trying again now through git.

**Comment by ethan92429** [comment]
OK, I changed the branch to adhere to the contribution guidelines and cleaned up the code. Hopefully it'll pass now!

**Comment by ethan92429** [comment]
Please let me know if I am missing anything in the way of style or logic!

**Comment by frantuma** [comment]
Thanks for reporting this, fixed in #3317 (which includes #3305)

**Comment by ethan92429** [comment]
@frantuma thanks for taking care of this so quickly! And thanks for helping with a great product 😄
