### ISSUE TITLE
Problem with extensions

### ISSUE THREAD

**Issue by andres1899** [swagger-api/swagger-core#3325]
Hi,
I am using swagger models (2.0.7) to generate dynamically a openapi (v3.0.1) string, then it is showed with swagger ui embeded in my web page. 

For the documentation, I need to generate the body, indicating its attributes in json format. This is the result for the body:

![Captura](https://user-images.githubusercontent.com/8743862/66584344-5610be80-eb5b-11e9-8727-9d5d982478be.PNG)

And in swagger ui, its looks like this:

![Captura2](https://user-images.githubusercontent.com/8743862/66584741-11395780-eb5c-11e9-83f8-7ea9eff56f49.PNG)

In conclusion, the service in this example, receives a json as input parameter with a CANTLINEAS attribute:

![Captura3](https://user-images.githubusercontent.com/8743862/66584940-5cec0100-eb5c-11e9-9980-7e20fb03603c.PNG)

CANTLINEAS is created like a schema, NumberSchema(). CANTLINEAS can be a numeric with decimals places, so i can't use the native attribute MaxLength (its fails in Try it Out, because count all de characters, not decimals per separate). So, my only chance is to add extensions to the documentation parameter, to indicate that it can have a "MaxLength", and a "Decimals" places.

In Java, with swagger models, i can do that:
`schema = new NumberSchema();`
`schema.format("double");`
`Map<String, Object> extensions = new LinkedHashMap<>();`
`extensions.put("MaxLength", parameter.getLength());`
`extensions.put("Decimals", parameter.getDecimals());`
`schema.setExtensions(extensions);`

And the resulting openapi string, is the string showed in the first picture.

Finally, what is the problem?

If i put the generated string in my embeded swagger ui, its looks fine (picture 2 and 3)
BUT if i put it, in https://editor.swagger.io, i get an structural error

Structural error .....
should NOT have additional properties
additionalProperty: extensions

So, am I wrong in the way of creating the body parameters?

Exactly the same happens if instead of adding extensions to a body parameter, I add it to the Info tag, or other.

Something similar occurs here, but the answer is not clear
#2808

(Sorry for my spanenglish/google traductor).

Thanks

Andrés.

**Comment by andres1899** [comment]
Problem solved. Json.pretty() solved it. I was using a generic objectmapper, and then, the resulted string was different.

**Comment by cristina-balan** [comment]
Hi! I am having the same issue. Could you please elaborate on how you used pretty json for solving it? Thanks!

**Comment by andres1899** [comment]
> Hi! I am having the same issue. Could you please elaborate on how you used pretty json for solving it? Thanks!

Basically, before, I had defined mi objectMapper in this way:
```
import com.fasterxml.jackson.databind.ObjectMapper;
...
ObjectMapper objectMapper = new ObjectMapper();
String jsonResult = objectMapper.writer(new DefaultPrettyPrinter()).writeValueAsString(object);
```


Then, I changed de implementation to:
```
import io.swagger.v3.core.util.Json;
...
ObjectMapper objectMapper = Json.mapper();
String jsonResult = Json.pretty(object);	
...

```
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/Json.java


After that, works fine in my case.
