### ISSUE TITLE
Include schemas mentioned in discriminator when filtering and removingUnfreferencedDefinitions

### ISSUE THREAD

**Issue by ethan92429** [swagger-api/swagger-core#3345]
Currently Schemas are filtered out if they are only included in the discriminator mapping. I propose including them in this case, as they are officially 'referenced' even though it is impossible to actually use them because they aren't included compositionally.

**Comment by ethan92429** [comment]
@fehguy @frantuma just wondering what you think of this change?

**Comment by ethan92429** [comment]
Just wondering if there is any action here? Thanks @fehguy and @frantuma!

**Comment by frantuma** [comment]
Thanks for reporting and for the PR! it has been included and replaced by #3381 (minor fix and test update)
