### ISSUE TITLE
Object Fields missing

### ISSUE THREAD

**Issue by rozzamozza** [swagger-api/swagger-core#3348]
Fields Properties Missing from Schema when they are more than one "object" fields.
E.g. Schema model for  data class Between<C>(val from: C, val to: C) is incorrect.

from is ignored due to the way ModelResolver.java works out if it can use the same property as before or not.

This issue is in the use of "cloning" (rather than using standard immutable object pattern)

ModelResolver.java
```
if (!"object".equals(property.getType()) || (property instanceof MapSchema)) {
   try {
    String cloneName = property.getName();
    property = Json.mapper().readValue(Json.pretty(property), Schema.class);
    property.setName(cloneName);
  } catch (IOException e) {
       LOGGER.error("Could not clone property, e");
   }
 }
```

Example failing kotlin test:
 
```
  @Test
  fun `should model both parameters for Between`() {
    val models = ModelConverters().readAll(Between::class.java)
    val properties = models["Between"]?.properties
    assertThat(properties?.size, equalTo(2))
  }
  data class Between<C>(val from: C, val to: C)
```

**Comment by frantuma** [comment]
Thanks for reporting this and for the PR! fixed in #3351 (includes and replaced #3349)
