### ISSUE TITLE
How do I provide examples of Date type?

### ISSUE THREAD

**Issue by estroykov** [swagger-api/swagger-core#3363]
I am generating Open API specification for my Java code using annotations. And I am experiencing some issues.

Suggest I have such method in my Java code:

```
@GET
@Path("/")
@Operation
@Produces("application/json")
@ApiResponses(
        @ApiResponse(responseCode = "200", description = "200", content = @Content(schema = @Schema(implementation = LocalDateTime.class), examples = @ExampleObject(value = "2018-12-01T02:15:00")))
)
public String operation() {
    return "Hello, world!";
}
```

With help of swagger-maven-plugin I get this Open API specification:

```
openapi: 3.0.1
info:
  title: API Title
  description: API description
  version: API version
paths:
  /:
    get:
      operationId: operation
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: string
                format: date-time
              example: 2018-12-01T02:15:00

```

When I paste this specification in editor.swagger.io, I expect to see `2018-12-01T02:15:00` as an example. But I see `{}` instead.

So, here is the question: is this Open API specification valid? If yes, probably editor.swagger.io has to be able to render it correctly. If not, probably swagger-maven-plugin has to generate valid one.

A similar issue takes place for example provided in Model class (via `ModelConverter` implementation). Let's suggest we have such Open API specification:

```
openapi: 3.0.1
info:
  title: API Title
  description: API description
  version: API version
paths:
  /:
    get:
      operationId: operation
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Request:
      type: object
      properties:
        localDateTime:
          type: string
          format: date-time
          example: 2018-12-01T02:15:00
```

On editor.swagger.io one can see `OrderedMap {}` as an example instead of `2018-12-01T02:15:00`.

**Comment by webron** [comment]
@estroykov note that `date-time` includes timezone information (or offset), so if you set your example to `2018-12-01T02:15:00Z0` it will render correctly.

**Comment by estroykov** [comment]
@webron thank you! I believed that `date-time` did not include timezone information. It was my bad.
