### ISSUE TITLE
Swagger JAX-RS Reader and path building

### ISSUE THREAD

**Issue by maggu2810** [swagger-api/swagger-core#3367]
Hi,

I created two modules that allows me to generate the description using the OSGi JAX-RS Whiteboard mechanism to detect the resources. One module for Swagger 1.5 and one for the current OpenAPI one.

I realized that your readers (for 1.5 the one in the module swagger-jaxrs, for the master the one in the module swagger-jaxrs2) handles the path building differently.

As fair as I understand the `@Path` documentation it does not matter if a path starts with `/` or ends with `/`. It should be the same and if necessary the `/` are added on path building.

This is working for swagger-jaxrs2's Reader but not for swagger-jaxrs's one.

See: https://github.com/swagger-api/swagger-core/blob/01c4272/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L744-L756

If the parent path ends with '/' that character is removed. After that the class path is added. It does not check if the class path begins with a '/' and does not add it if missing. If the method's path is added after the class path has been added the check is done.
So, as long as the classes path annotation value does not begin with a `/` the concatenation between parent path and class path will be without an `/` as it is removed from the ending of the parent path (if present).
For my use case, I need to use the parent path for the application's path.

The swagger-jaxrs2 reader handles the path concatenation more generic and checks for missing `/` all the time.

Do you agree that this could be changed in the 1.5 branch? I can try to come up with a PR.

**Comment by frantuma** [comment]
Thanks for reporting and investigating this; and yes I agree that this should b changed in 1.5 branch, a PR is more than welcome!

**Comment by maggu2810** [comment]
A PR has been submitted (#3385).

**Comment by maggu2810** [comment]
@frantuma friendly ping :wink:

**Comment by maggu2810** [comment]
Are you still waiting for something from my side?

**Comment by frantuma** [comment]
nope, merged eventually PR, thanks a lot!
