### ISSUE TITLE
Add description on ArrayChema

### ISSUE THREAD

**Issue by Pantelispanka** [swagger-api/swagger-core#3371]
For example " @ArraySchema(schema = @Schema(implementation = User.class)  "
cannot take description as it should 
eg @ArraySchema(schema = @Schema(implementation = User.class, description="description")

**Comment by jochenberger** [comment]
I have the same issue. Why did you close this @Pantelispanka ?

**Comment by Pantelispanka** [comment]
@jochenberger it has been 5 years ! I cannot remember the specifics !! Now days inwoukd asj github copilot..
