### ISSUE TITLE
@Api(hidden = true) failed

### ISSUE THREAD

**Issue by w350727743** [swagger-api/swagger-core#3391]
@Api(hidden = true) decorate controller unsuccessful
`<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.7.0</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.7.0</version>
		</dependency>`

**Comment by webron** [comment]
That's Springfox, not Swagger Core. Please file an issue with them.
