### ISSUE TITLE
Question: Is there a sample test code I can refer to for using @RequestBody feature ?

### ISSUE THREAD

**Issue by Andrew3431** [swagger-api/swagger-core#3397]
I am using springdoc-openapi to use swagger for spring mvc. I want different set of parameters for Request and Response for POST methods. Using @JSONViews seemed to work for displaying different request and response for swagger. However if I use @requestbody from spring framework (org.springframework.web.bind.annotation.RequestBody) , the JSONView output is not working as expected
The test code mentioned here works well with @requestbody provided by swagger (io.swagger.v3.oas.annotations.parameters.RequestBody). However trying the swagger @requestbody , does not read the inputs and provides them with null values.

```java
import io.swagger.v3.oas.annotations.parameters.RequestBody;
.
.
@Operation(security = { @SecurityRequirement(name = "api_key")}, summary = "Adds new user.")
@ApiResponses(value = {@ApiResponse(responseCode = "201", description = "the user was created"),
          @ApiResponse(responseCode = "409", description = "the user exists already", content = @Content) })
@RequestMapping(method = RequestMethod.POST}, produces = {APPLICATION_JSON_VALUE})
@ResponseStatus(HttpStatus.CREATED)
@ResponseBody
@JsonView(Views.ReadOnly.class)
    public User create( @Parameter(description = "user information")
            @JsonView(Views.Request.class)
            @RequestBody User user)
             { . .... }
```
where user returns null for variables. Working with @requestbody from Spring returns the user object with values given during request. Am I doing something wrong here ? How do I use `@RequestBody` annotation  ?

**Comment by webron** [comment]
I'm afraid we're not going to be able to help with that. In general, swagger-core does not support Spring. Other libraries like Springfox and springdoc-openapi use our annotations, but we don't what's their process of parsing these annotations and how they may affect the code. For better support, please file an issue with the respective project.
