### ISSUE TITLE
Change javax to jakarta artifact dependencies

### ISSUE THREAD

**Issue by mohanaraosv** [swagger-api/swagger-core#3399]
Use the jakarta maven co-ordinates 

https://wiki.eclipse.org/New_Maven_Coordinates

Ref : https://www.eclipse.org/lists/jakartaee-platform-dev/msg00029.html

**Comment by webron** [comment]
That seems only relevant if we update to the latest version, isn't it?

**Comment by mohanaraosv** [comment]
Yes, I will raise PR if you agree on [cxf Jakarta adoption](https://github.com/apache/cxf/pull/500/files)

**Comment by reta** [comment]
In the same vein, it would be probably good to update Bean Validation to 2.0 (1.1 is still used), since there are no Jakarta artifacts for Bean Validation 1.1 released (and very unlikely will be in a future). I am wondering @webron if there are reasons to support Bean Validation 1.1? Thank you!

**Comment by frantuma** [comment]
Thanks for reporting and working on this! implemented in #3467
