### ISSUE TITLE
Regarding Open-API 3.0 Swagger Specification

### ISSUE THREAD

**Issue by neha-pednekar** [swagger-api/swagger-core#3400]
```
@Operation(summary = "Get the quantities for a product")
	@GetMapping(value = "api/products/{key}/quantities/")
	public ResponseEntity<QuantityResponse> getQuantities(
@PathVariable @NotBlank String key,	
@RequestParam @NotBlank String requestor, 
@Parameter(example = example, style = ParameterStyle.DEEPOBJECT, name ="options")DeepObjectMap selections) {
		//TODO:Get qty logic
		return new ResponseEntity<QuantityResponse>.ok();
		
}
```
Why is it that on swagger-ui for the above pasted endpoint, I see the options parameter(the one for which the ParameterStyle is DEEPOBJECT) as **required (*)** in the OPEN-API Document even though its required attribute is set to false by default within the @Parameter annotation(in my Java code). Though this field accepts an empty input on the UI, it still looks misleading to the users of the endpoint when they see it marked as ***required**. 

I tried using @RequestParam(required = false) along with @Parameter annotation(WHICH SOLVES THE SWAGGER-UI ISSUE) but then options is set to null. Has anyone tried using @RequestParam together with @Parameter annotation for DEEPCOPYing? 

Can someone please help me with this issue?

**Comment by webron** [comment]
@neha-pednekar Since you're referencing `@RequestParam`, it's clear you're using Spring for your rest service. Swagger Core does not support Spring, but Springfox does, which I assume is what you use. While they use our annotations, we don't control how they parse them. Please file an issue with Springfox instead.
