### ISSUE TITLE
Question: Is there a way to allow @JsonIgnoreProperties( allowGetters = true) to allow the variable to be present in response example values , instead of avoiding it ?

### ISSUE THREAD

**Issue by Andrew3431** [swagger-api/swagger-core#3410]
The @JsonIgnoreProperties hides the variables from appearing in the swagger document, which is expected. But in cases where the variable has allowGetters = true property set, shouldn't the variable be displayed in response example values ?
NOTE: @JsonIgnoreProperties was added not for swagger purposes in my code , but for functional use (to avoid deserialization) , therefore I cant use @JSONVIEW instead of @JsonIgnoreProperties..

Can this feature be supported ?

**Comment by HaruhiSuzumiyah** [comment]
I know it's been a few years, but I'm also experiencing this issue.

**Comment by frantuma** [comment]
this has been addressed in https://github.com/swagger-api/swagger-core/pull/4418
