### ISSUE TITLE
`swagger-jaxrs2-servlet-initializer` contains classes from `swagger-jaxrs2`

### ISSUE THREAD

**Issue by zregvart** [swagger-api/swagger-core#3412]
Seems that some classes are duplicated from `swagger-jaxrs2` to `swagger-jaxrs2-servlet-initializer`:

```
io.swagger.v3.jaxrs2.integration.JaxrsAnnotationScanner
io.swagger.v3.jaxrs2.integration.JaxrsApplicationAndAnnotationScanner
io.swagger.v3.jaxrs2.integration.JaxrsApplicationAndResourcePackagesAnnotationScanner
io.swagger.v3.jaxrs2.integration.JaxrsApplicationScanner
io.swagger.v3.jaxrs2.integration.JaxrsOpenApiContext
io.swagger.v3.jaxrs2.integration.JaxrsOpenApiContextBuilder
io.swagger.v3.jaxrs2.integration.OpenApiServlet
io.swagger.v3.jaxrs2.integration.ServletConfigContextUtils
io.swagger.v3.jaxrs2.integration.ServletOpenApiConfigurationLoader
io.swagger.v3.jaxrs2.integration.ServletOpenApiContextBuilder
io.swagger.v3.jaxrs2.integration.ServletPathConfigurationLoader
io.swagger.v3.jaxrs2.integration.SwaggerLoader
io.swagger.v3.jaxrs2.integration.XmlWebOpenApiContext
```

I don't see any configuration of shading or jarjar-ing in [/modules/swagger-jaxrs2-servlet-initializer/pom.xml](https://github.com/swagger-api/swagger-core/blob/d964eba5a0c6695bd5b4623de2b68d40b2c02450/modules/swagger-jaxrs2-servlet-initializer/pom.xml) and there the sources for this are missing in the `swagger-jaxrs2-servlet-initializer-2.1.1-sources.jar` so that makes me thing this was done manually.

Any explanation as to why was this done and what purpose does it serve?

**Comment by frantuma** [comment]
Thanks a lot for reporting this! Unfortunately this is related to an issue with the same package used within `swagger-jaxrs2` and `swagger-jaxrs2-servlet-initializer`, and it's impact in an OSGi env: the same package `io.swagger.v3.jaxrs2.integration` is exported by both bundle (the "split-package" issue in OSGi), which means that depending on the order of bundle loading in an OSGI env, one or the other will be picked up by client bundles.

If I am not mistaken, this means that we cannot unfortunately fix this (by removing the duplicated classes, currently they are added by the`maven-bundle-plugin`) in a minor version, as the duplication ensures the classes will be available in OSGi env.

For this reason #3412 deprecates `swagger-jaxrs2-servlet-initializer` and adds `swagger-jaxrs2-servlet-initializer-v2` which changes the package to `io.swagger.v3.jaxrs2.integration.servlet`

The deprecated module will be eventually removed in next major version.

Closing ticket, please reopen if you're still experiencing issues.
