### ISSUE TITLE
ModelResolver.enumsAsRef behavior broken

### ISSUE THREAD

**Issue by daniel-frak** [swagger-api/swagger-core#3414]
There is an if-statement in ModelResolver:324:
```java
if (type.isEnumType() &&
                    (resolvedSchemaAnnotation != null && resolvedSchemaAnnotation.enumAsRef()) ||
                    ModelResolver.enumsAsRef
            ) {
```

I believe the way it should be written is:
```java
if (type.isEnumType() &&
                    ((resolvedSchemaAnnotation != null && resolvedSchemaAnnotation.enumAsRef()) ||
                    ModelResolver.enumsAsRef)
            ) {
```

The way it is now seems to attempt to resolve every type as an enum if `ModelResolver.enumsAsRef == true`, resulting in NPEs with `context.defineModel(name, model, annotatedType, null);` passing a `name` that is NULL:
```
java.lang.NullPointerException: null
	at java.base/java.util.TreeMap.put(TreeMap.java:561) ~[na:na]
	at io.swagger.v3.core.converter.ModelConverterContextImpl.defineModel(ModelConverterContextImpl.java:58) ~[swagger-core-2.1.0.jar:2.1.0]
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:329) ~[swagger-core-2.1.0.jar:2.1.0]
```

Am I correct or am I misinterpreting the purpose of the `enumsAsRef` property?

**Comment by frantuma** [comment]
Thanks for spotting and reporting this! you are definitively right, would you maybe be able to add a PR with the fix (possibly with a related unit test)?

**Comment by daniel-frak** [comment]
I have created #3415 for this issue.
Not sure why it isn't showing up here, I thought it would automatically link up?
