### ISSUE TITLE
Generating description with $ref

### ISSUE THREAD

**Issue by avantipande1** [swagger-api/swagger-core#3419]
```yaml
Home:
      type: object
      properties:
        home_address:
                 description: "its the home address"
                 $ref: '#/components/schemas/Address'
Office:
      type: object
      properties:
        office_address:
                 description: "its the office address"
                 $ref: '#/components/schemas/Address'
```

This is a kind of swagger I want to generate with annotations, where I can have specific descriptions for home and office addresses.  
Is there anyway swagger-ui will read this description for $ref?

https://github.com/swagger-api/swagger-editor/issues/1184#issuecomment-422044132

This is one of the solution I found but there is no way to generate it with annotations.
Thanks

**Comment by webron** [comment]
Currently, the OpenAPI specification does not support any additional attributes alongside a $ref, so there's nothing we can do about it. The next version of the spec will support it, but that's months away.

**Comment by avantipande1** [comment]
> Currently, the OpenAPI specification does not support any additional attributes alongside a $ref, so there's nothing we can do about it. The next version of the spec will support it, but that's months away.

Thanks Ron for the update.

**Comment by webron** [comment]
Going to close this as there's nothing we can do about it.

**Comment by DepickereSven** [comment]
It's supported in OpenAPI 3.1.0 https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#externalDocumentationObject

**Comment by m1ks** [comment]
Hi, should we open this issue again since the feature is now supported in  OpenAPI 3.1.0?

**Comment by yehor-manzhula** [comment]
@m1ks Here is the new issue https://github.com/swagger-api/swagger-core/issues/4013
