### ISSUE TITLE
Operation IDs suffixed due to invalid detection of overridden methods

### ISSUE THREAD

**Issue by UKreher** [swagger-api/swagger-core#3426]
Consider the following example classes (the original ones are more complex and the inheritance is reasonable):
```
public class Parent<T> {
  public T get(String input) {
    return null;
  }
}
```
```
@Path("/inheritExample")
public class Resource extends Parent<String> {
  @Override
  @GET
  @Path("/{input}")
  public String get(@PathParam("input") String input) {
    return super.get(input);
  }
}
```
OpenAPI generates the rather ugly operation ID `get_1` for this method. This is due to the Java compiler (at least JDK 8 from Oracle, Eclipse compiles differently and does not have the problem) generating the method twice within the `Resource` class. These methods only differ in the return value (`String` and `Object`) and `ReflectionUtils.isOverriddenMethod()` fails to detect overriding due to not checking methods within the same class.
The OpenAPI generation later somehow finds these methods to be duplicates and skips one of them. However, the ugly operation ID remains.

I fixed this by iterating the methods of the current class. But I am not sure whether the condition for the overridden method is correct. At least it works for the example classes above.

**Comment by frantuma** [comment]
thanks for reporting this! should be fixed in #3795, closing ticket, please reopen if you're still experiencing issues
