### ISSUE TITLE
https://stackoverflow.com/questions/59967447/how-to-globally-ignore-api-of-spring-boot-from-open-api-3-specification?noredirect=1#comment106052889_59967447

### ISSUE THREAD

**Issue by javaHelper** [swagger-api/swagger-core#3432]
https://stackoverflow.com/questions/59967447/how-to-globally-ignore-api-of-spring-boot-from-open-api-3-specification?noredirect=1#comment106052889_59967447

**Comment by webron** [comment]
This is not constructive.
