### ISSUE TITLE
@Schema does not provide a property for: `Properties[] properties` 

### ISSUE THREAD

**Issue by stefan-huettemann** [swagger-api/swagger-core#3433]
Hi. 

I am using `swagger-annotations:2.1.1`.

According to [swagger.io specs](https://swagger.io/docs/specification/describing-request-body/file-upload/) a configuration for a multipart file-upload would be:
```json
"requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file_a": {
                    "type": "string",
                    "format": "binary"
                  },
                  "file_b": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
```
This - in fact - would work and shows two file upload buttons in swagger-ui and sends a correct multipart-request to my server.

I cannot find any property in `@Schema` annotation to provide a `properties` section. What I came up with so far is:

```java
@Operation(
            requestBody = @RequestBody(
                    content = @Content(
                            mediaType = MediaType.MULTIPART_FORM_DATA_VALUE,
                            schema = @Schema(
                                    type = "object"
                                    // -> properties[] is missing !!!
                            )
                    ))
    )
```

Why does `@Schema` not provide any means to add the `properties` section?

Best,
-Stefan

**Comment by Wizzercn** [comment]
Same question . Now Form parameters cannot be defined.

**Comment by frantuma** [comment]
#4129 introduces support to define Schema properties via annotations. Please see [this](https://github.com/swagger-api/swagger-core/blob/1da7289edabb83f1f9b9f19615b63c5a361efab7/modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/AnnotatedPet.java) and [this](https://github.com/swagger-api/swagger-core/blob/158a57a180d98b1413309a4fd6096c5f7f54bff7/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/SchemaPropertiesResource.java) examples for usage scenarios.
