### ISSUE TITLE
Swagger CSS not loading properly.

### ISSUE THREAD

**Issue by emrecakmak** [swagger-api/swagger-core#3441]
Hi guys, 

When I enter "swagger project edit" command, style problem occurs on my project.

<img width="1679" alt="Screen Shot 2020-02-10 at 11 40 05" src="https://user-images.githubusercontent.com/16281631/74135868-1ee01600-4bfe-11ea-9ad9-f349ef5b0f05.png">

It should be like this.
<img width="1669" alt="Screen Shot 2020-02-10 at 11 40 32" src="https://user-images.githubusercontent.com/16281631/74136046-75e5eb00-4bfe-11ea-9842-afb9687d1a23.png">

How can I solve this?

Thanks.

**Comment by webron** [comment]
This is an issue related to swagger-node, not swagger-core. At the moment, it's not updated to the latest version of the Editor. Best solution is to use the editor externally.
