### ISSUE TITLE
@JsonIgnoreProperties on field is ignored when generating Open API definition

### ISSUE THREAD

**Issue by qianlong** [swagger-api/swagger-core#3442]
Considering a class has one field annotated with JsonIgnoreProperties :
```java
public class Customer{
    private String name;
    @JsonIgnoreProperties({ "doorPassword"})
    private Address address;
}
```
In the generated definition, `address` property in `Customer` schema should not reference the `Address` schema, but a new schema in considering the `@JsonIgnoreProperties` declaring on the field.

**Comment by Jojoooo1** [comment]
any new on that ?

**Comment by frantuma** [comment]
This is partially addressed in #3649, please see comment in PR and related test about limitations.

Closing this ticket as it duplicates #2845, further work will be done in scope of that ticket.

**Comment by monika1009** [comment]
@frantuma  - Can you please suggest for  @jsonIgnore marked properties , openAPI document can be generated ?

**Comment by SushmitaGoswami** [comment]
Any update on this?
