### ISSUE TITLE
Question: Adding documentation via external package

### ISSUE THREAD

**Issue by kceb** [swagger-api/swagger-core#3450]
I'm creating an external package for my node server and I was wondering if there was a way to, in my package, detect if swagger is being used by the consumer, and if so, dynamically add a route to the YAML file in the consumer's swagger docs. 

Let's say my external api is some sort of middleware that adds routes to a server. I'd like it to automatically document those routes in the consuming server's swagger docs as well instead of manually adding the routes to my server swagger docs. (I am not using swagger codegen)

**Comment by webron** [comment]
You're trying to add node based APIs to a Java based project?

**Comment by kceb** [comment]
I realized that I may have meant to post this in the swagger-ui repo
