### ISSUE TITLE
access stored swagger document for particular api (support)

### ISSUE THREAD

**Issue by RAHULRAJSONU** [swagger-api/swagger-core#3462]
Is it possible to access the documents generated by swagger inside the spring boot app, eg;

I have four APIs in an application

    GET /api/read-api
    
    PATCH /api/update-api
    
    DELETE /api/delete-api
    
    POST /api/create-api

and I have swagger configured in the application.

I have another class in the same project where I wanted to access the document for a particular input URL

    public class SwaggerDocument{
    
        Map<String, Document>getDocument(String url){
    
           //I wanted to search generated document for input url
    
        }
    
    }

Any help would be highly appreciated.

**Comment by webron** [comment]
Do you use swagger-core or springfox?

**Comment by RAHULRAJSONU** [comment]
Hey @webron ,
Yes, I can see the springfox-core:2.9.2 in the dependency tree because I have included these dependencies in my pom.
```
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger2</artifactId>
      <version>2.9.2</version>
    </dependency>
    <dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-swagger-ui</artifactId>
      <version>2.9.2</version>
    </dependency>
```

**Comment by webron** [comment]
Then you should be filing the issue with Springfox. While it uses some of our libraries, its parsing is different and not something we can address.
