### ISSUE TITLE
how do i customise additionalProp1, additionalProp2, additionalProp3 in map?

### ISSUE THREAD

**Issue by pdaenkhan** [swagger-api/swagger-core#3473]
For example

`protected Map<String, Double> makeup = new HashMap<>();
`
```
          "makeup": {
            "additionalProp1": 0,
            "additionalProp2": 0,
            "additionalProp3": 0
          },
```

it is shown like this in the swagger-ui.
 
instead of additionalProp, i want the example to be like

```
          "makeup": {
            "beauty": 0,
            "hair": 0,
            "skin": 0
          },
```

I'm using dropwizard-swagger 1.3.4-1 i.e swagger-core 1.5.22

**Comment by mazzock** [comment]
Any news?

**Comment by R70YNS** [comment]
```example: "\r\n{\r\n  \"beauty\": 0,\r\n  \"hair\": 0,\r\n  \"skin\": 0\r\n}"``` on your makeup object. 

See: https://github.com/swagger-api/swagger-ui/issues/5240
