### ISSUE TITLE
swagger-gradle-plugin generates empty file

### ISSUE THREAD

**Issue by eugenekainara** [swagger-api/swagger-core#3480]
I'm on the way of migrating to spring boot 2.2 and found that springfox is not working for me.
So I'm switch to springdoc-openapi backed by swagger-core 2.1.1
I'm use swagger-gradle-plugin v2.1.1
my build.gradle looks like 

```
plugins {
    id "io.swagger.core.v3.swagger-gradle-plugin" version "2.1.1"
}
resolve {
    outputFileName = 'swagger'
    outputFormat = 'JSONANDYAML'
    prettyPrint = 'TRUE'
    classpath = sourceSets.main.output + configurations.compileClasspath
    resourceClasses = ['com.example.TestController']
    outputPath = file("${project.buildDir}")
}
```

Output for json is 
```
{
  "openapi" : "3.0.1"
}
``` 
and for yaml 
`openapi: 3.0.1`

I've created a repo where my issue reproduces - https://github.com/eugenekainara/swagger-gradle-plugin-repro
p.s. when I'm starting my app with `./gradlew bootRun` - api-docs is accessible via http://localhost:8080/v3/api-docs

**Comment by mijailr** [comment]
I have the same problem. Do you solved? @eugenekainara

**Comment by tspoeri** [comment]
I'm facing the same issue, any news on this?

**Comment by kisdaniel** [comment]
> @mijailr still facing empty file. Will work on it on next week

Have you found any solution?

**Comment by frantuma** [comment]
`swagger-gradle-plugins` relies on [swagger-jaxrs2](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jaxrs2) to resolve openapi specification from **JAX-RS** resources, not Spring Resources/Controller. As you mentioned Spring resolution is provided by springfox or springdoc-openapi, which I believe rely on Swagger Core to provide POJO to Schema resolution. I am not sure if they provide gradle plugins to resolve at build time
