### ISSUE TITLE
Invalid date format

### ISSUE THREAD

**Issue by 1448376744** [swagger-api/swagger-core#3487]
## UI
Request body
Example Value
Schema
{
  "id": 0,
  "customerId": 0,
  "cardId": 0,
  "cardNo": "string",
  "canUseCount": 0,
  "notes": "string",
  "orderStatus": 0,
  "aftersaleId": 0,
  "expectKeepTime": "2020-03-30T05:45:13.930Z",
  "useCount": 0,
  "orderPrice": 0
}
## startUp
``` C#
//asp.net core 3.1
services.AddControllers()
.AddJsonOptions(a=>a.JsonSerializerOptions.Converters.Add(new DatetimeJsonConverter("yyyy-MM-dd HH:mm:ss")))
```

**Comment by frantuma** [comment]
Closing ticket as it doesn't provide understandable context and issue
