### ISSUE TITLE
How to set JSON date format options on the swagger UI

### ISSUE THREAD

**Issue by 1448376744** [swagger-api/swagger-core#3488]
````C#
// on asp.net core 3.1 Startup.ConfigureServices
services.AddControllers()
.AddJsonOptions(a => a.JsonSerializerOptions.Converters.Add(new DatetimeJsonConverter("yyyy/MM/dd HH:mm:ss")));
````
'datetimejsonconverter' is a date conversion defined by me.
But the date format in the swagger UI example is still the default '2020-03-30t08:14:49.693z'.
How do I set up the JSON serializer options for the sample on swaggerui?

**Comment by frantuma** [comment]
related to #3487; I still don't understand the context, the environment, what is the library used to generate the spec (is this a spec generation service even?), what is the code from which spec is generated. In any case I doubt this has something to do with [swagger-core](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#what-is-it-about)

**Comment by 1448376744** [comment]
> 与[＃3487](https://github.com/swagger-api/swagger-core/issues/3487)相关; 我仍然不了解上下文，环境，用于生成规范的库是什么（甚至是规范生成服务？），从中生成规范的代码是什么。无论如何，我怀疑这与[招摇核心有关](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#what-is-it-about)

I set up jsonserializer for ASP. Network core. But this does not change the API sample parameters of the swagger UI

**Comment by frantuma** [comment]
As mentioned swagger-core has nothing to do with ASP / .NET code, if you are experiencing issues with some ASP/ .NET related library, you should check for help in their doc/issues

**Comment by 1448376744** [comment]
> As mentioned swagger-core has nothing to do with ASP / .NET code, if you are experiencing issues with some ASP/ .NET related library, you should check for help in their doc/issues

How to customize JSON serialization options of swaggerui sample parameters?
