### ISSUE TITLE
Published version

### ISSUE THREAD

**Issue by sofialunkes** [swagger-api/swagger-core#3495]
Hi everyone, i would like you guys to make sure that the new version is published.. i tried to insert this
```
plugins {
  id "io.swagger.core.v3.swagger-gradle-plugin" version "2.1.3-SNAPSHOT"
}
```
but i get an error. So i've tried to go directly to the gradle URL that consults and this version is not published yet.

**Comment by frantuma** [comment]
snapshots are not published, you would use latest `2.1.2` https://plugins.gradle.org/plugin/io.swagger.core.v3.swagger-gradle-plugin
