### ISSUE TITLE
How to add curl example?

### ISSUE THREAD

**Issue by AkshayIyer12** [swagger-api/swagger-core#3502]
Hi,

I have been going through docs and examples for sometime but I was unable to find how to add a curl example using annotations? 
I have looked up resources from stackoverflow and swagger-wiki specifically (https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations). 
I'm not sure if there was any chat forum like discord or irc for swagger.

Can anyone point me to the correct resource? Or is annotation the right way to go about it.

Thanks!

**Comment by AkshayIyer12** [comment]
Below are the dependencies I'm using for swagger.          
  <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>2.9.2</version>
            </dependency>

            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>1.6.0</version>
            </dependency>

            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>2.9.2</version>
            </dependency>

**Comment by webron** [comment]
@AkshayIyer12 - You're using Springfox and should be asking in that project how to do what you're looking for. While they use our annotations, they may have additional mechanism that swagger core does not offer.

Swagger UI, alternatively, generates a curl command when you try out an API call.
