### ISSUE TITLE
Swagger generates ArraySchema instead of StringSchema for byte array.

### ISSUE THREAD

**Issue by Birthright50** [swagger-api/swagger-core#3511]
I use latest swagger 2.1.2, springdoc 1.3.1, spring boot 2.2.6 (MVC stack)
For example, one endpoint from my controller:
```
    @PostMapping(Routes.Item.External.ITEM_BY_ID_PHOTO)
    public ActionResult<Long> uploadImage(
            @PathVariable("id") @Min(1) long itemId,
            @AuthenticationPrincipal User principal,
            @RequestBody @Validated Base64ImageRequest req
    ) {
        final Long sellerId = principal.getCurrentAgent().isSeller() ? principal.getCurrentSellerId() : null;
        return ActionResult.ok(this.imageService.createImage(itemId, sellerId, req));
    }
```
Request model `Base64ImageRequest`:
```
public class Base64ImageRequest {
    private short order;
    @NotNull
    private byte[] image;
}
```
An example of a valid request:
```
{
"order": 5,
"image":  "someBase64Image"
}
```

It was expected that the generated specification with such a structure for this request:
```
      "Base64ImageRequest": {
        "required": [
          "image"
        ],
        "type": "object",
        "properties": {
          "order": {
            "type": "integer",
            "format": "int32"
          },
          "image": {
            "type": "string"
          }
        }
      }
```
But at the output, it turns out that the image field is interpreted as an array of strings.

```
      "Base64ImageRequest": {
        "required": [
          "image"
        ],
        "type": "object",
        "properties": {
          "order": {
            "type": "integer",
            "format": "int32"
          },
          "image": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "byte"
            }
          }
        }
      }
```

[The problem is here](https://github.com/swagger-api/swagger-core/blob/a78875c8e24db082105d3dc3b34cb40d6513d471/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L655)
This line returns for field `image` `io.swagger.v3.oas.models.media.ArraySchema` instead of `io.swagger.v3.oas.models.media.StringSchema`

**Comment by webron** [comment]
If you're using springddoc, you need to file an issue with them. They may use our annotations, but the way they parse the annotations is up to them.

**Comment by Birthright50** [comment]
> If you're using springddoc, you need to file an issue with them. They may use our annotations, but the way they parse the annotations is up to them.


I don’t really understand what springdoc has to do with it, because the `Schema` was generated by `ModelConverterContextImpl`. This class is written by this lib, , and not by the guys from springdoc.

**Comment by webron** [comment]
Normally when other projects use swagger-core, they only rely on swagger-annotations and not our processors (because for the most part it doesn't make sense). If for some reason springdoc does use our processors, we'd ask for an example in a JAX-RS context that reproduces it. 

Ideally, you could provide a PR with a failing test that we'd need to fix.

**Comment by lscorcia** [comment]
Would issue https://github.com/swagger-api/swagger-core/issues/3944 be a meaningful repro in a JAX-RS context of this problem?
