### ISSUE TITLE
application path missing

### ISSUE THREAD

**Issue by wernerdaehn** [swagger-api/swagger-core#3523]
I am using swagger.core.v3 with version 2.1.0 in a java project and the web application's path is missing in the service descriptor. It returns /rest/service1 and not /mywebapp/rest/service1.

A JAXRS service is annotated with 

    @Path("/rest/service1")

and the openapi.json returns 

    {"openapi":"3.0.1","paths":{"/rest/service1":{"get":{...

The actual URL to call the service via postman is http://localhost/mywebapp/rest/service1

As a result, **swagger-ui** says returns 404 because the webapplication name _mywebapp_ is missing. Swagger-ui calls:

    curl http://localhost/rest/service1

When searching in swagger-ui, consens seems to be that openapi.json should expose the locations relative to the server, hence expecting /mywebapp/rest/service1. But I am not sure.

 Activation of Swagger is done via the JAXRS Application annotation:

    @ApplicationPath("/rest")
    public class WebIDEApplication extends ResourceConfig{
        public WebIDEApplication() {
            super();
            register(JacksonFeature.class);
            register(RolesAllowedDynamicFeature2.class);
            register(new OpenApiResource());
        }
    }

I tried many things, basePath (Not available in v3), openapi.yaml (Works but has no path/server component or it gets ignored). I spent now 3 hours on that xxxxx issue. :sight:
Can anybody point me into the proper direction, please?

**Comment by wernerdaehn** [comment]
I would still believe the default OpenApiResource() should include the WebApp's home directory by default. 

However, the first tip I got was "Servers" are the way to resolve that. So now it was the question on how I get the servers array populated. It is harder than you think!
But the solution was Annotations to above class.
https://github.com/swagger-api/swagger-core/issues/3524

I leave that issue open if somebody from the professionals happens to agree with adding the webapp home path by default. If not, closing it is just fine.

**Comment by frantuma** [comment]
Thanks for documenting this! 

You can also provide an openApi instance within your configuration defining the servers there, to be merged with the resolved one, see [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties).

Web app "home directory" or "base path" or "application path" can be defined in many different ways in many different environments, it probably doesn't make sense / it's not feasible to try resolving it differently than current handling of JAX-RS `applicationPath`
