### ISSUE TITLE
ApplicationPath should appear in server not in the Resource

### ISSUE THREAD

**Issue by Macs75** [swagger-api/swagger-core#3545]
I found out that when I configure my Jersey application with swagger 2.0.6 that 
the server part specified in the configuration does not influence in any way the path returned in resources.
So if I specify:

  "servers" : [ {
    "url" : "http://serverdom.com/api/v1"
  } ],

and I have an @ApplicationPath("api/v1") as root for my application
and then a resource with @Path("/foo")
the result is that in the openapi.json will have a path url = "api/v1/foo".

This makes really difficult to configure multiple version of the api in the same application.
There should be a way to specify in the configuration to ignore the "api/v1" part because
we specified already in the server part. 
The resource is "/foo" the "api/v1" is not part of of the resource but instead is part of the base address of the api. I find it incorrect to see it repeated for all the resource of the application.
It have made more sense if if no server configuration was provided to put it like
  "servers" : [ {
    "url" : "api/v1"
  } ],

**Comment by frantuma** [comment]
Generally, as mentioned in https://github.com/swagger-api/swagger-core/issues/3523#issuecomment-650571106 with reference to a similar scenario, Web app "home directory" or "base path" or "application path" can be defined in many different ways in many different environments.

The "default" way in case an `@ApplicationPath` is present, is to perpend it to paths. In your case or in other scenarios this might be not desired, the two easiest ways to customize this behaviour is either [extending Reader]() or [using a filter]()

You would for example override `resolveApplicationPath()` returning an empty string, or adding a filter and updating all keys of openAPI.getPaths(). 

Related tickets for reference:

* https://github.com/swagger-api/swagger-core/issues/3903
* https://github.com/swagger-api/swagger-core/issues/3545
* https://github.com/swagger-api/swagger-core/issues/3025
* https://github.com/swagger-api/swagger-core/issues/3523
* https://github.com/swagger-api/swagger-core/issues/3524

Closing ticket, please reopen if you're still experiencing issues
