### ISSUE TITLE
How to use @Schema with Properties for OAS? No examples, which annotation to use?

### ISSUE THREAD

**Issue by antonalechnovic** [swagger-api/swagger-core#3547]
How to represent properties in the link below?

https://swagger.io/docs/specification/data-models/data-types/#object 

I am looking through openspec java annotations , nothing to help with properties, totally lost, what I am supposed to do here?

`responses = {@ApiResponse( description = "Accepted", content = @Content(mediaType = "application/json", schema = @Schema(type = "object",  properties = THIS_PROPERTIES_PROPERTY_IS_MISSING )))}`

**Comment by antonalechnovic** [comment]
there is a class ref as param everywhere , but as soon as I put it just adds component ref, how is this supposed to work?

**Comment by agustisanchez** [comment]
With the `Schema` class, it is possible to define nested properties this way:

```java
        new Schema().type("object")
                .addProperties("prop1",
                        new Schema().type("string"))
                .addProperties("prop2", 
                        new Schema().type("boolean"));
```

Apparently there's no way to achieve the same with the related `@Schema` annotation which forces to define classes only to generate documentation, which is not a good practice.

We need to be able to define (nested) properties in `@Schema` annotation, too.

**Comment by antonalechnovic** [comment]
> With the `Schema` class, it is possible to define nested properties this way:
> 
> ```java
>         new Schema().type("object")
>                 .addProperties("prop1",
>                         new Schema().type("string"))
>                 .addProperties("prop2", 
>                         new Schema().type("boolean"));
> ```
> 
> Apparently there's no way to achieve the same with the related `@Schema` annotation which forces to define classes only to generate documentation, which is not a good practice.
> 
> We need to be able to define (nested) properties in `@Schema` annotation, too.

This is becoming severe issue to stop using Swagger via java and spring openspec together, because there is no escape route for things which hard to represent with autogeneration.

How to use this raw code in @RestController ?

**Comment by rwe17** [comment]
I'm running into the same issue and just want to add documentation to properties of a request model class.
It seems impossible to add just a description to a property without generation a new superfluous schema. Is there really no solution for that common problem?

**Comment by frantuma** [comment]
#4129 introduces support to define Schema properties via annotations. Please see [this](https://github.com/swagger-api/swagger-core/blob/1da7289edabb83f1f9b9f19615b63c5a361efab7/modules/swagger-core/src/test/java/io/swagger/v3/core/resolving/v31/model/AnnotatedPet.java) and [this](https://github.com/swagger-api/swagger-core/blob/158a57a180d98b1413309a4fd6096c5f7f54bff7/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/resources/SchemaPropertiesResource.java) examples for usage scenarios.
