### ISSUE TITLE
Show only specific controller's operations in OpenAPI

### ISSUE THREAD

**Issue by JollyGoodHolly** [swagger-api/swagger-core#3562]
Say I have three controllers: My own, A, as well as X and Y, inherited from a dependency (for use with RESTEasy, etc.). I now want to document only A's operations in my OpenAPI spec. Since I cannot annotate X and Y with @Hidden, I need an inverse of it (e.g. @Only), so that _all but_ A are ignored. Is this possible?

**Comment by frantuma** [comment]
you can [specify]](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#your-own-configuration) your resource package(s) or classes  and/or use [your own scanner](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#resource-scanning).

Please close ticket if this answers your question

**Comment by frantuma** [comment]
Closing ticket, please reopen if you're still experiencing issues

**Comment by JollyGoodHolly** [comment]
Forgot to reply. Indeed, specifying the class to be used for my project worked. Thanks for the help!
