### ISSUE TITLE
Type 'ResolveTask': setter method 'setOutputPath()' should not be annotated with: @Internal

### ISSUE THREAD

**Issue by natros** [swagger-api/swagger-core#3563]
Type 'ResolveTask': setter method 'setOutputPath()' should not be annotated with: @Internal. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.4.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

Gradle 6.4.1
Java 11

**Comment by rpr13** [comment]
May this be related to problem with something kind a cache?

I removed previous config.
But I cannot generate new file.
It says `UP-TO-DATE`... even if there is no old file, just removed it. :smile:

**Comment by frantuma** [comment]
`@internal` annotation removed in #3630
