### ISSUE TITLE
XmlRootElement with duplicate names only one will be modelled.

### ISSUE THREAD

**Issue by Solverj** [swagger-api/swagger-core#3568]
If I have these two java classes:

```
@XmlRootElement(name = "Result")
class ApiResult {
  // some content A
}

@XmlRootElement
class SomeOtherClass {
 // Some content B
  static class Result {
     // some content C
  }
}
```

Then when swagger is modelling it will "pick" one of the two "A" or "C" and if that's "A" that will be the content of the modelling of "SomeOtherClass.Result" i.e., "C" will show "A" or vica verca. Can this be fixed by having conflicts like this instead use fully qualified names, i.e., package mapping?

**Comment by Solverj** [comment]
Ping pong, anyone?

**Comment by perluqing** [comment]
I have the same issues

**Comment by frantuma** [comment]
this seems to duplicate #2861, please see comment there and PR #3542 
Closing as duplicate.
