### ISSUE TITLE
Question: How to create and serialize OpenAPI specification programmatically?

### ISSUE THREAD

**Issue by stefan-ka** [swagger-api/swagger-core#3570]
Hi there

Can someone tell me how I have to use the Swagger API to create, validate, and serialize an OpenAPI 3.0 specification? Or point me to an example, I did not find that in the wiki.?

I simply want to create a spec. in a Java program and then serialize it (YAML and JSON). Ideally I also want to validate it so that the generated output validates in the Swagger editor.

```java
public class OpenAPISpecCreation {
    public static void main(String[] args) {
        
        // create the specification:
        OpenAPI oas = new OpenAPI();
        oas.info(new Info().title("My Test API"));
        // and so on ....
        
        // how to validate the model ??
        // validate(oas) ??

        // how to serialize the model ??
        // serialize(oas, YAML) 
    }
}
```

Would be nice to have an example how you guys would recommend to do that.

Thanks and best regards,
Stefan

**Comment by stefan-ka** [comment]
I found out that I could for example serialize as follows:

```java
public static void main(String[] args) {

    OpenAPI oas = new OpenAPI()
            .info(new Info()
                    .title("My Test API")
                    .contact(new Contact().email("this is not an email address")));
    Yaml.prettyPrint(oas); // just use pretty(oas) to get it as String
}
```

The produced output is:

```yaml
openapi: 3.0.1
info:
  title: My Test API
  contact:
    email: this is not mail address
```

If I copy this into the Swagger editor, I get three errors:

```txt
Structural error at 
should have required property 'paths'
missingProperty: paths
Jump to line 0

Structural error at info
should have required property 'version'
missingProperty: version
Jump to line 2

Structural error at info.contact.email
should match format "email"
format: email
Jump to line 5
```

... which makes sense, but I would like to get the errors programmatically, so that I can throw an exception and already know that the model is not valid.

Thanks for the help.

**Comment by frantuma** [comment]
one way to do it is to use [swagger-parser](https://github.com/swagger-api/swagger-parser) which provides validation, and use it like:

```
List<String> validationMessages =  new OpenAPIV3Parser().readContents(Yaml.pretty(oas)).getMessages();

if (!validationMessages.isEmpty()) {
...
}
```

The validation results will be slightly different from the editor ones, as they use different validation code. 

Please close ticket if this answers your question

**Comment by stefan-ka** [comment]
Thanks @frantuma! That should do it for my use case.
