### ISSUE TITLE
Can't hide property using @Schema(hidden = true) or @Hidden

### ISSUE THREAD

**Issue by gerrit-hohl** [swagger-api/swagger-core#3586]
Hello everyone,

I have a model `UserEntity` (extract):
```java
@JsonPropertyOrder({ "password" })
@Schema(title ="User", description = "The user.")
public class UserEntity {

    private String password;

    public UserEntity() {
        super();
    }

    @JsonProperty("password")
    @Schema(title = "Password", description = "The password of the user.", hidden = true)
    @Hidden
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}
```
In the openapi.json generated by the swagger-maven-plugin I get the following (extract):
```json
{
    "openapi": "3.0.1",
    "components": {
        "schemas": {
            "UserEntity": {
                "title": "User",
                "type": "object",
                "properties": {
                    "password": {
                        "type": "string",
                        "writeOnly": true
                    }
                },
                "description": "The user."
            }
        }
    }
}
```

Honestly I would have expected that the password property won't be written to the file. Seems I totally misunderstood the meaning of `hidden = true` as well as `@Hidden`. 🤔

Is there any way to "hide" a property, so it isn't written to the file?
Or is this a bug and one of my approach should have done the magic?

**Comment by frantuma** [comment]
This is due to the presence of `@JsonProperty("password")` which and a non hidden ` public void setPassword(String password) {` which makes swagger/jackson think we want to resolve into a writeOnly property; adding `@Hidden` also to the setter  would hide the property.

Please close ticket if this answers your question

**Comment by gerrit-hohl** [comment]
Thanks @frantuma , that was the missing piece. 🙂
If I hide the getter and the setter it works: The property is removed from the OpenAPI file. 👍

Seems @Schema(hidden = true) and @Hidden are interchangeable with each other. 🤔
If I put @Hidden on the getter and setter, the property is hidden. If I put @Schema(hidden = true) on both, the property is also hidden.
