### ISSUE TITLE
How to make enum's definition conforming to the rules of Jackson's @JsonValue annotation

### ISSUE THREAD

**Issue by devxleo** [swagger-api/swagger-core#3593]
I have a class like this

```java
public enum CourseType {

    ENGLISH('english'), MATH('math');

    private String name;

    CourseType(String name) { this.name = name; }    

    @JsonValue
    String stringValue() {
        return name;
    }
}
```

I get swagger schema definition like this

```
CourseType: {
    type: "string"
    enum: ["ENGLISH", "MATH"]
}
```

but I expect to get following, which is consistent with Jackson's serialization result

```
CourseType: {
    type: "string"
    enum: ["english", "math"]
}
```

**Comment by frantuma** [comment]
this duplicates #3552 and should be solved by #3553, available in latest snapshot and next release.

Closing ticket, please reopen if you have further comments or questions
