### ISSUE TITLE
Javadoc accessMode READ_ONLY not correct

### ISSUE THREAD

**Issue by mattiasclaesson** [swagger-api/swagger-core#3596]
https://javadoc.io/doc/io.swagger.core.v3/swagger-annotations/latest/io/swagger/v3/oas/annotations/media/Schema.html#accessMode--

Allows to specify the access mode (AccessMode.READ_ONLY, READ_WRITE)
AccessMode.READ_ONLY: value will only be written to during a request but not returned during a response. 
AccessMode.WRITE_ONLY: value will only be written to during a request but not returned during a response.
AccessMode.READ_WRITE: value will be written to during a request and returned during a response.

READ_ONLY description is wrong, its not the same as WRITE_ONLY.

Should be something like:
"value will not be written to during a request but only returned during a response. "

**Comment by frantuma** [comment]
this is implemented in #3537
