### ISSUE TITLE
What is an alternative to hardcoding server URL in @Server annotation?

### ISSUE THREAD

**Issue by ArtemZubenko** [swagger-api/swagger-core#3597]
Hello swagger-api team, 

Assuming that servers URL values can be different in different environments. What is an alternative to hardcoding URL value in @Server annotation in Spring Boot application?

@OpenAPIDefinition(
        info = @Info(
                title = "Test application",
                version = "0.1",
                description = "This is just a test application"
        )
        , servers = @Server(url = "https://blah.com") // HOW TO NOT HARDCODE?
)

Looking forward to your response. 

Cheers,

**Comment by frantuma** [comment]
You can use a [filter](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters) or [listener](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#reader-listeners) provide a pre-processed (e.g. with dynamic servers)  openAPi instance via [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties)

**Comment by debargharoy** [comment]
@frantuma an example on how it can be done with filter would would help a lot.
