### ISSUE TITLE
using swagger-jaxrs2 and running from IDE or as Tomcat war fails to generate openapi.json

### ISSUE THREAD

**Issue by tGuichin** [swagger-api/swagger-core#3598]
I tried making my Jersey/Spring Boot application user swagger-jaxrs2 to generate a swagger-ui and it works if I use "java -jar application.jar" after using "mvn clean package".  If I were to run it from the IDE or deploy it on tomcat as a war package it will show the following error:

tools: swagger-jaxrs2 2.1.2, spring-boot-starter-parent 2.3.0.RELEASE, 

![image](https://user-images.githubusercontent.com/17357603/85592496-3a2f4900-b614-11ea-82e2-bd5ee7826b4a.png)

What am I missing, or is this a bug?

**Comment by tGuichin** [comment]
I resolved my issue.  It was a java.lang.OutOfMemoryError: Java heap space.   Adding -Xmx600m resolves the issue, but I don't think it's the best way to go about it.  If anyone has a better recommendation I'm all ears.

**Comment by parameshjava** [comment]
Do we need to pass `-Xmx600m` through JVM parameter?

**Comment by pioto** [comment]
Yes, I've also seen that this component uses excessive amounts of memory. It appears to be related to how it scans the classpath. Some hprof files I've gathered seem to imply classgraph is at fault here?

I'm looking to figure out how I can avoid having it scan my whole classpath, because I only have a handful of JAX-RS resources that I want it to scan under one package, and the rest of my rather large codebase just isn't going to have anything relevant in it.

**Comment by parameshjava** [comment]
Still I am facing the issue, after passing `-Xmx2048m`.

**Comment by parameshjava** [comment]
I am using context path other than just `/`. It's an issue to me. Is there a way to prefix context path for `/v2/api-docs` ?

**Comment by tGuichin** [comment]
@parameshjava after building your project and getting your jar, if you run your jar in command prompt with "java -jar jarfile.jar" then go to your swagger in the browser and wait for it to load, do you get "java.lang.OutOfMemoryError: Java heap space" in the command prompt?  If so, then you need to add -Xmx600m, or maybe higher but 600 is what worked perfectly for me. ("java -Xmx600m -jar jarfile.jar").

**Comment by frantuma** [comment]
specific packages or classes can be provided via [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration) to limit scanning to specific resources, alternatively a [custom scanner](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#resource-scanning) can be also provided.

Closing ticket, please reopen if you're still experiencing issues.
