### ISSUE TITLE
Support overriding enum values for branch 1.5

### ISSUE THREAD

**Issue by hhat42** [swagger-api/swagger-core#3616]
I am using the 1.x.x version of the swagger-maven-plugin to generate OpenAPI v2 specification from my annotated model classes. Unfortunately, switching to OpenAPI v3 is not an option at the moment.

I need to generate enum values that have spaces or other special characters. This is currently not possible with the 1.x.x version. The generator always picks the name of the enum from the Java class, which has limits from the java language syntax. The latest release of the 2.x.x. swagger-api had an enhancement for that problem (issue #3552). This enhancement allows to annotate the enum values with `@JsonProperty` or a getter method with `@JsonValue`.

It would be nice, if this feature would also be available when generating OpenAPI v2 specs with the 1.x.x version.

**Comment by frantuma** [comment]
Thanks for reporting and PR! implemented in #3617
