### ISSUE TITLE
What is the replacement for this declaringClass that is Deprecated

### ISSUE THREAD

**Issue by zxiaozhou** [swagger-api/swagger-core#3618]
What is the replacement for this declaringClass that is Deprecated,Nothing in the source code is clear
![image](https://user-images.githubusercontent.com/62740686/86557549-0f84af00-bf89-11ea-8719-3100b3e286ca.png)
Because I need to scan multiple packages and scan those packages myself
This kind of indefinable explanation is really annoying to watch
So the user really can not see whether there is an alternative, how to replace??

**Comment by frantuma** [comment]
This is not related to `swagger-core` (probably springfox?). Closing
