### ISSUE TITLE
$ref does not appear on .json file but does appear on .yaml file

### ISSUE THREAD

**Issue by canserkanuren** [swagger-api/swagger-core#3622]
Hello everyone. 
I have been using swagger-core for a day and I tried to set some `ApiResponse` on my function. 
So I set it up like this :

```
@Operation(
  method = "GET",
  description = "Get all applications by trigram",
  tags = {"applications"},
  responses = {
    @ApiResponse(
      responseCode = "200",
      description = "All applications have been fetched",
      content = @Content(array = @ArraySchema(schema = @Schema(implementation = ApplicationDto.class)))
    ),
    @ApiResponse(responseCode = "204", description = "No application has been found with trigram")
  }
)
```

But when I try to display it with `springdocs`, I do have this error :
![Capture](https://user-images.githubusercontent.com/22659909/87060330-ae6c0e00-c20a-11ea-814c-082661b9fd4d.PNG)

After investigating a little further, I have found this differences between my JSON and YAML swagger.

Here's the JSON structured Swagger :
```
"/infocentre_api/applications": {
  "get": {
    "tags": ["applications"],
    "description": "Get all applications by trigram",
    "operationId": "getApplications",
    "parameters": [
      {
        "name": "trigram",
        "in": "query",
        "description": "Given application trigram in order to perform search",
        "schema": { "type": "string" },
        "example": "ABC"
      }
    ],
    "responses": {
      "200": {
        "description": "All applications have been fetched",
        "content": { "application/json": { "schema": { "type": "array" } } }
      },
      "204": { "description": "No application has been found with trigram" }
    }
  }
},
```
Here's the YAML structured Swagger :
```
  /infocentre_api/applications:
    get:
      tags:
      - applications
      description: Get all applications by trigram
      operationId: getApplications
      parameters:
      - name: trigram
        in: query
        description: Given application trigram in order to perform search
        schema:
          type: string
        example: ABC
      responses:
        "200":
          description: All applications have been fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Application"
        "204":
          description: No application has been found with trigram
```

Here is my `pom.xml` :
```
<dependency>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-annotations</artifactId>
  <version>2.1.3</version>
</dependency>
<dependency>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-core</artifactId>
  <version>2.1.3</version>
</dependency>
<dependency>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-jaxrs2</artifactId>
  <version>2.1.3</version>
  <exclusions>
    <exclusion>
      <groupId>io.github.classgraph</groupId>
      <artifactId>classgraph</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-ui</artifactId>
  <version>1.2.18</version>
</dependency>
```
The difference between theses two are the `$ref` attribute that is not set for the JSON file, but is set for the YAML file..
Am I doing something wrong ? Is it a bug on your end or did I just miss something ?
Thank you for your answers.

**Comment by frantuma** [comment]
Possibly wrong repo, if you're using springdoc, you need to file an issue with them. In a "pure" `swagger-core` JAX-RS environment this is not reproducible (both Json and Yaml provide the same outcome)

**Comment by canserkanuren** [comment]
I can remove springdoc if you want, and I will surely get the same problem without it, so I think it really is a problem with swagger-core.

I’ll find a way to fix it if you can’t find me one. 
Thank you.

**Comment by frantuma** [comment]
As mentioned, I have tested your example code with swagger-core, using:

```
@Path("test")
public class Ticket3622Resource {

    @Operation(
            method = "GET",
            description = "Get all applications by trigram",
            tags = {"applications"},
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "All applications have been fetched",
                            content = @Content(array = @ArraySchema(schema = @Schema(implementation = ApplicationDto.class)))
                    ),
                    @ApiResponse(responseCode = "204", description = "No application has been found with trigram")
            }
    )
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public void schemaImpl() {
    }

    static class ApplicationDto {
        public String foo;
    }
}
```

(therefore adding the JAX-RS `@GET` and `@Produces` annotation and the ApplicationDto implementation)

testing via:

```
        Reader reader = new Reader(new OpenAPI());

        OpenAPI openAPI = reader.read(Ticket3622Resource.class);
        Json.prettyPrint(openAPI);
        Yaml.prettyPrint(openAPI);
```

which is the [code](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/resources/BaseOpenApiResource.java) used to serialize into JSON and YAML in a JAX-RS environment using resources provided by swagger-core.

I am not really familiar with springdoc codebase but I would think they have their own way to expose and serialize the OpenApi definition, possibly involving different jackson mapper configurations, or even completely different json/yaml libraries for what I know. I also suspect they will be using their own code/resources/controller processors, so... but I might be wrong indeed! And:

> I can remove springdoc if you want, and I will surely get the same problem without it, so I think it really is a problem with swagger-core.

yes, it would greatly help to have a reproducible test code and config with swagger-core "directly", this facilitates things a lot!


> I’ll find a way to fix it if you can’t find me one. 

I usually add a note in the comment when I am closing tickets, asking the developer to comment if having further issues or questions, this time I forgot, silly me..

**Comment by canserkanuren** [comment]
Hello, 

I may have found the problem.
So the first Swagger, generated by `OpenApiResource` is doing great.
What I did is that I overrided this class by creating a `SpecificOpenApiResource`, so that I can perform some operations on the Swagger. Here's the code :

```
@Path("/openapi.{type:json|yaml}")
public class SpecificOpenApiResource extends BaseOpenApiResource {
    @Context
    ServletConfig config;
    @Context
    Application app;

    @GET
    @Produces({"application/json", "application/yaml"})
    @Operation(
            hidden = true
    )
    public Response getOpenApi(@Context HttpHeaders headers, @Context UriInfo uriInfo, @PathParam("type") String type) throws Exception {
        Response response = super.getOpenApi(headers, this.config, this.app, uriInfo, type);

        ObjectMapper mapper = new ObjectMapper();
        // --> this next line fails !!! Even though we agree that in the super.getOpenApi, we use OpenAPI class...
        OpenAPI oas = mapper.readValue(response.getEntity().toString(), OpenAPI.class);
        return response;
    }
}
```

As you can see, the line `mapper.readValue` fails because : 

`Unrecognized field "items" (class io.swagger.v3.oas.models.media.Schema)`.
I overpassed it by adding `mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);`, but then I am missing my `$ref` in my swagger.

I don't know what I can do here. Should I stop performing specific operations and use directly `OpenApiResource` class ?
I also created a GitHub repository so that you can check it out ! 
https://github.com/canserkanuren/swagger-core-example

Thank you for your help and your time !

**Comment by frantuma** [comment]
You are using an unconfigured ObjectMapper, which doesn't know how to handle fully (de)serialization, use instead `Json.mapper()`.

On the side, if you have to post process the outcome, a possible better alternative could be [filters](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters) or [listeners](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#reader-listeners)

**Comment by canserkanuren** [comment]
Thanks for your help, the 'Json.mapper()' did help me a lot. 
Thank you again for your time.
