### ISSUE TITLE
Property which is a reference to the same data type is not added to the contract

### ISSUE THREAD

**Issue by ishaigor** [swagger-api/swagger-core#3624]
I have an example that does not work as expected when generating OpenApi contract from a Java annotated sources https://github.com/ishaigor/open-api-annotation-example
The Model class has an optional parent property that is missing in the generated contract.
In this small example, I am able to force the property to appear if I annotate it with @Schema annotation. In my real-life. application, the workaround does not work all the time that I painfully discovered after implementing swagger diff tests. I am happy to contribute a fix, but at this point debugging the code did not shed light as to why the property is missing.

**Comment by frantuma** [comment]
Thanks for reporting this! Fixed in #3627
