### ISSUE TITLE
@RequestBody from Swagger v3 conflict with @RequestBody from the Spring Library

### ISSUE THREAD

**Issue by debargharoy** [swagger-api/swagger-core#3628]
Consider the below piece of code
```java
    public User createUser(@io.swagger.v3.oas.annotations.parameters.RequestBody(description = "Create the User") @RequestBody User user) {
        return userService.createUser(user);
    }
```
Isn't it a bad idea to have the same name `@RequestBody` for the annotation that belongs to Spring library as well? Because in the end, the Swagger's `@RequestBody` doesn't server the same purpose as that of the one from the Spring (the object is initialized to empty with all it's field set to `null` when using the annotation from Swagger alone), and we end up having fully qualified names for either of them which is discouraged.

**Comment by mariem-89** [comment]
These are two different annotations. You can combine them if needed.
Your issue seems just irrelevant.

**Comment by debargharoy** [comment]
I'm well aware that they both are different. Can you assist me on how we can combine them?

**Comment by Sarthak8696** [comment]
If you want to use both the annotations with the same name then you can write the swagger requestBody annotation like this - @io.swagger.v3.oas.annotations.parameters.RequestBody()
and write the spring requestBody annotation normally like @requestBody()

**Comment by debargharoy** [comment]
> 
> 
> If you want to use both the annotations with the same name then you can write the swagger requestBody annotation like this - @io.swagger.v3.oas.annotations.parameters.RequestBody()
> and write the spring requestBody annotation normally like @requestbody()

I was asking if it is possible to combine both of them, rather than using two of them. And maybe these conflicts should be avoided in the next major of swagger-core release

**Comment by frantuma** [comment]
I am not sure what you mean by "combine both of them", also please notice that `swagger-core` targets JAX-RS REST endpoints/code, and doesn't e.g. resolve Spring MVC endpoints (there are other projects providing this). Generally while trying to avoid duplicating annotation names, and because of the above, there are no plans to rename such annotation. I would close this ticket if this answers your question

**Comment by debargharoy** [comment]
@gcwiak, it's nice to put it that way. Unfortunately, as you already said we'll still have to use both the annotations. As already highlighted by @frantuma, the issue stems from the fact that Swagger-Core is built around JAX-RS (which does not have it's own `RequestBody`), and Springdoc is built around Swagger-Core while also Spring having its own `RequestBody` annotation. 

@frantuma, by the below phrase 

> I was asking if it is possible to combine both of them, rather than using two of them. And maybe these conflicts should be avoided in the next major of swagger-core release

what I meant to ask was, if there's a way to create a single annotation in our project that'll do the task of both the annotations together. But having explored that, it doesn't look like it's a feasible solution. So we'll have to continue using both the annotations together.

**Comment by marosivanco** [comment]
Could swagger at least use the type information from param marked with `@org.springframework.web.bind.annotation.RequestBody`  when no explicit `@io.swagger.v3.oas.annotations.parameters.RequestBody` is provided?
That would lower code pollution by swagger annotations...
