### ISSUE TITLE
Java: Add support for fluent APIs

### ISSUE THREAD

**Issue by flexguse** [swagger-api/swagger-core#3640]
In my company when we create code in Java we always use a fluent api, mostly using Project Lombok.

```
@lombok.Data
@lombok.experimental.Accessors(fluent=true)
public class Person{
  
     private String name;

}
```

lombok creates the accessors
```
    public String name()

    public void name(String name)
```
for us.

In our current setup:

```
    spring-boot 2.3.1 with webmvc and tomcat
    springdoc-openapi-ui 1.4.2
    swaggerApiVersion = '2.1.3'
```
the OpenAPI 3 Description does not contain name at all, I suppose it is looked for the getName() method which does not exist.

Please add the support of recognize getter / setter methods without the prefixes get/set as it is already implemented in the [micronaut-openapi](https://github.com/micronaut-projects/micronaut-openapi/issues/19) project.

If the addition of this feature is too much effort, please give me a hint which class in springdoc-openapi needs to be extended.

**Comment by Gungrave223** [comment]
wow mid 2020 and no response....thing it's save to say this will not be supported.... tragic.

**Comment by Avinm** [comment]
When using Swagger-Core-2.1.12 with jackson, adding `@JsonProperty` annotation on the fluent attribute seems to fix this

**Comment by sukerberk1** [comment]
Hey, if someone still encounters this issue and needs a fix working for a whole class (for all fields), setting up `@JsonAutoDetect` worked for me. 
Example:
```java
@Data
@Accessors(fluent = true)
@NoArgsConstructor
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
public final class Example {
    private @NonNull UserId userId;
    private @NonNull String name;
    private String email;
}
```

**Comment by micryc** [comment]
Hi @sukerberk1 thank you for providing solution, I am closing this ticket for now, If anyone will still have any issues around that, feel free to reopen
