### ISSUE TITLE
[Jaxrs2] Cannot Define Serialisation Rules For Form UrlEncoded Body

### ISSUE THREAD

**Issue by BenjaminHetzjelli** [swagger-api/swagger-core#3643]
According to the spec, one should be able to define serialisation rules for application/x-www-form-urlencoded body parameters. In practice though, it is not possible at this time through either using @FormParams individually or by combining them into an @BeanParam due to the way they are converted into the request body.

In practice, this means that if one's API does not take parameters in the default way, then requests generated using the spec will not work. This is especially egregious since it seems swagger-js (used by swagger-ui) doesn't serialise form params properly by default (at least when compared to [https://swagger.io/docs/specification/describing-request-body/](this documentation).

**Comment by frantuma** [comment]
Thanks for reporting this! Should be addressed by #3696, closing ticket please reopen if still experiencing issues (see also comment in [this question](https://community.smartbear.com/t5/Swagger-Open-Source-Tools/Specifying-Encoding-For-Form-Data-Parameters/m-p/206091#M1362))
