### ISSUE TITLE
swagger-jaxrs2 duplicates endpoints if you use subresource

### ISSUE THREAD

**Issue by tGuichin** [swagger-api/swagger-core#3678]
I have a jaxrs resource class which is the main controller and multiple subresources that are mapped on ```@Path("x/x")``` where x is a path.  When using subresources, the swagger documentation will duplicate endpoints if a ```@Path()``` annotation exists in the subresource.  Any advice on how to go around this issue, or what, if anything, I'm doing wrong?

Main resource class. 

```
@Path("/mainResource")
public class XResource{

    @Path("{studentId}/student")
    public StudentAccountService getStudentAccountService(){
        return new StudentAccountService();
    }
}
```  

```
@Path("/")
public class StudentAccountService{
    
    @GET
    @Produces({MediaType.APPLICATION_JSON})
    @Path("name")
    public Response lookup(){
        //return name
    }
}
```

This will produce swagger documentation with endpoints / and mainResource/{studentId}/student for ```@Path("/")```, mainResource/{studentId}/student/name and /name for ```@Path("/name")``` where expected result of swagger doc should be only one endpoint for each.

I am using the latest of swagger-jaxrs2 v 2.1.4.

**Comment by tGuichin** [comment]
My issue was having registered my subresources in multiple places.

**Comment by Santobert** [comment]
@tGuichin how could you solve your issue? Where exactly have you registered your subresource? According to the documentation, it is not wrong to reuse subresources.
