### ISSUE TITLE
JSR-303 annotations ignored with @JsonUnwrapped

### ISSUE THREAD

**Issue by miloszszyrner** [swagger-api/swagger-core#3683]
I have reported an [issue](https://github.com/springdoc/springdoc-openapi/issues/832) where I was redirected to post it here
Working with Spring Doc version 1.4.4 found issue with @JsonUnwrapped

Code to reproduce
```java
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Base

@NotBlank
private String id;

@Valid
@JsonUnwrapped
private UnwrappedObject unwrappedObject


@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UnwrappedObject 

@Schema(required = true)
@NotBlank(message = "Property cannot be blank")
private String property;
```

In generate documentation, id is marked as required whereas property is not

**Comment by frantuma** [comment]
see also #3879, fixed in #3880
