### ISSUE TITLE
AbstractSpecFilter implementation not being picked up as docs suggest.

### ISSUE THREAD

**Issue by ndtreviv** [swagger-api/swagger-core#3687]
According to the documentation:

> When relying on provided JAX-RS resources to expose the API (since version 2.0.8 also using maven or gradle plugin), this filter will be applied automatically

(https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters)

I am including dependency `io.swagger.core.v3:swagger-jaxrs2-servlet-initializer-v2:2.1.4` and including the relevant packages in my servlet filter init params:

```
        <init-param>
            <param-name>jersey.config.server.provider.packages</param-name>
            <param-value>my.packages,io.swagger.v3.jaxrs2.integration.resources</param-value>
        </init-param>
```

But when I fetch the OpenAPI spec by uri: `/openapi`, the filter class is not used.

**Comment by frantuma** [comment]
as mentioned in [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters) filter must be specified in [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-configuration#configuration); The sentence you mention was indeed misleading and has been updated to make clear that filter must be defined in configuration or programmatically.

Closing ticket, please reopen if you're still experiencing issues
