### ISSUE TITLE
Why no support for external parameter reference?

### ISSUE THREAD

**Issue by hpl002** [swagger-api/swagger-core#3690]
**Why arent external parameter references supported?**

>Error:
Semantic error at paths./accounts/{accountID}
Declared path parameter "accountID" needs to be defined as a path parameter at either the path or operation level

I have to declare the parameter in a root object, and then i can reference a external schema for its type, but what i would reeeeally like is to rather reference the complete external object directly. In a similar manner to that which is allowed with responses..
___ 
Lets elaborate: 
``` yaml 
openapi: "3.0.0"
info:
  title: Example API
  description: An Example of how to set up the API Gateway.
  version: v1
  contact:
    email: flow@stacc.com
servers:
  - url: http://localhost:3010/api
    description: Sandbox
x-flow-proxies:
  flow-service-proxy:
    target: http://localhost:3020
tags:
  - name: Account Service
paths:
  /accounts/{accountID}:
    x-flow-proxy: flow-service-proxy
    get:
      tags:
        - Account Service
      summary: Gets a specific account by id
      parameters:
        - $ref: "#/components/parameters/accountID" #Legal, but forces reference to a local parameter object 
        - $ref: "service-schemas/mock-account-service.yaml#/parameters/accountID" #Illegal reference
      responses:
        "200":
          $ref: "service-schemas/mock-account-service.yaml#/responses/get.200.account" #legal reference
components:
  parameters:
    accountID: #Why cant this entire object be moved out?
      name: accountID
      in: path
      required: true
      description: ID of account
      schema:
        $ref: "service-schemas/mock-account-service.yaml#/parameters/id"
```

Would appreciate any feedback that could explain the reasoning behind this 👍 

Thanks!

**Comment by frantuma** [comment]
@hpl002 can you clarify in which scenario you're getting the mentioned error (e.g in swagger-editor? using parser? etc) and provide the whole set of involved specification files?

**Comment by hpl002** [comment]
I think i might have confused an issue with swagger fore with one that was rather intended for the swagger editor.
I will reopen this issue if i run into it again at a later point.

> Solved it on my end by using a config bundler before validating.

Think the validator might have accepted external references for responses, but not for parameters. My thinking was that if one is allowed then why not both?

For future readers: have a look at https://www.npmjs.com/package/@apidevtools/swagger-parser
