### ISSUE TITLE
Wrapped object is not shown correctly in swagger documentation: Java

### ISSUE THREAD

**Issue by DeepakPatankar** [swagger-api/swagger-core#3699]
I have a java class which contains @JsonTypeInfo(use = NAME, include = WRAPPER_OBJECT) annotation to specify that the class will have a wrapper field connector

```
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
@JsonTypeInfo(use = NAME, include = WRAPPER_OBJECT)
@JsonTypeName("connector")
public class ConnectorDTO {
  String name;
  String identifier;
  String description;
}
```
I tried serializing and deserializing this class with the input and both works fine.

```
{
    "connector":{
        "name": "Test-again",
        "description": "test",
    }
}   
``` 
I am facing problem with the swagger documentation, the documentation shown is

![image](https://user-images.githubusercontent.com/51910413/93334016-d8acfe00-f841-11ea-90bb-0b1f89042dcf.png)

But the JSON input should have a connector wrapper. How I can achieve this?

**Comment by frantuma** [comment]
fixed in #4211
