### ISSUE TITLE
exampleSetFlag leaks in json output produced by ObjectMapper

### ISSUE THREAD

**Issue by fstaudt** [swagger-api/swagger-core#3702]
Since 2.1.4, the field `exampleSetFlag` appears in json produced with [ObjectMapper#writeValue(File, Object)](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L1615) when serializing an object of type [OpenApi](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/OpenAPI.java).

Using swagger-core 2.1.3 (OK) :
``` json
{
  "openapi" : "3.0.1",
  "paths" : {
    "/api/some" : {
      "get" : {
        "operationId" : "get-some",
        "responses" : {
          "400" : {
            "description" : "error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "error" : {
        "type" : "object",
        "properties" : {
          "returnCode" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

Since swagger-core 2.1.4 (not OK):
``` json
{
  "openapi" : "3.0.1",
  "paths" : {
    "/api/some" : {
      "get" : {
        "operationId" : "get-some",
        "responses" : {
          "400" : {
            "description" : "error",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/error",
                  "exampleSetFlag" : false
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "error" : {
        "type" : "object",
        "properties" : {
          "returnCode" : {
            "type" : "string",
            "exampleSetFlag" : false
          }
        },
        "exampleSetFlag" : false
      }
    }
  }
}
```

It seems to me that the field exampleSetFlag is internal and should be ignored by jackson object mapper.

Could you update the class Schema to add annotation `@JsonIgnore` on field `exampleSetFlag`, like it is already done for field `name` ?

I can submit a PR if you're OK with it.

**Comment by frantuma** [comment]
thanks for reporting this, please see [this comment](https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287) about using the correctly configured object mapper.

closing ticket, please reopen if you're still experiencing issues

**Comment by fstaudt** [comment]
@frantuma 

thanks for pointing to this comment.

As you suggested, I added a MixIn class to my ObjectMapper to ignore the new field in JSON serialization.

**Comment by alebastrov** [comment]
This is not enough solution, see https://github.com/swagger-api/swagger-core/issues/4381

**Comment by TeemuKurki** [comment]
If anyone else is having this issue make sure you have imported ObjectMapper from io.swagger.v3.core.util.Json and not from io.swagger.util.Json.

Both have similar interfaces, but only io.swagger.v3.core.util.Json excludes exampleSetFlag
