### ISSUE TITLE
Handling of Optionals versus explicit schema type

### ISSUE THREAD

**Issue by frensjan** [swagger-api/swagger-core#3703]
I am under the impression that https://github.com/swagger-api/swagger-core/issues/3624 (to solve https://github.com/swagger-api/swagger-core/issues/3624) causes an issue with a model such as:
```java
import at.favre.lib.bytes.Bytes;

...

@Schema(type = "string", format = "byte")
@JsonSerialize(converter = BytesConverter.ToArray.class)
@JsonDeserialize(converter = BytesConverter.FromArray.class)
public Optional<Bytes> getBytes() {
    ...
}
```
This used to yield:
```yaml
      properties:
        bytes:
          type: string
          format: byte
```
but now it yields:
```yaml
      properties:
        bytes:
          $ref: '#/components/schemas/Bytes'

...

    Bytes:
      type: object
      properties:
        empty:
          type: boolean
        readOnly:
          type: boolean
        mutable:
          type: boolean
      format: byte
```

The change was introduced in swagger-core 2.1.4 (the issue is not present when generating a schema with 2.1.3).

I'm not 100% sure where the exact difference is, but while debugging I noticed that in `ModelResolver.java` on [line 263](https://github.com/swagger-api/swagger-core/blob/0144bff2df1aba025412678a64c7e60f515d0b88/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L263), the previous version would enter an `if` block to define a `primitiveType`. Whereas in 2.1.4 it does not, because `annotatedType.isSkipOverride()` is `true` instead of `false`.

Is this an expected change? Is there a work around? I understand that it is difficult for swagger-core to determine the desired schema, hence the `@Schema(type = "string", format = "byte")` annotation to 'nudge' the schema. I expected this to work in 2.1.4 as well.

If more details are required or if I can help out in any other way: let me know.

**Comment by frantuma** [comment]
Thanks for reporting this and for the analysis! 

Fixed in #3706
