### ISSUE TITLE
Spec generated by annotations completely ignores inherited generic field

### ISSUE THREAD

**Issue by chriskessel** [swagger-api/swagger-core#3710]
I have a class structure that looks like this. I've stripped down and swapped out a bunch of names, so please ignore if a typo left a brace unmatched somewhere.
```
public class MyResource {
   @Operation( responses = {
                 @ApiResponse(content = @Content(schema = @Schema(implementation = MySpecificResponse.class))
              })
  @Path blah blah
  public Response doThing() {
     ...
  }
}

public class MySpecificResponse extends MyAbstractDomainResponse<MySpecificDomainThing> {
    public String foo;
}

public abstract class MyAbstractDomainResponse<T> {
    public T domainThing;
    public ErrorCodes errors;
}
```

When I generate the OpenApi3 spec via the OpenApiResource endpoint, it doesn't generate the `domainThing` field at all. It does generate the `foo` and `errors` field, so it's looking up the inheritance tree to find fields, but it's ignoring the `domainThing` field.

```
{
  "MySpecificResponse": {
    "type": "object",
    "properties": {
      "error": {
        "$ref": "#/components/schemas/ErrorCodes"
      },
      "foo" : {
        "type" : "string"
      }
    }
  }
  ErrorCodes schema stuff down here...
}
```

I am guessing this is because that inherited field is based on a generics value? Type erasure is causing it to fail to determine that type? Is there an annotation feature I can use to get it to understand how to generate `domainThing`?

**Comment by chriskessel** [comment]
Of course, after spending 3 hours working on this, the moment I create the issue I figure out what I've done wrong...

**Comment by shawank17** [comment]
Hi @chriskessel , I'm facing the similar issue. How did you resolve it? TIA
