### ISSUE TITLE
BaseOpenApiResource not honoring resourcePackages

### ISSUE THREAD

**Issue by chriskessel** [swagger-api/swagger-core#3711]
I have multiple REST endpoint classes, each representing a different service. I've created a subclass of BaseOpenApiResource for each so they only serve their own specification. I've taken OpenApiResource as an example and then extended it to try to scope to just the REST packages I want it to spit out swagger for, so I've done this:
```
        OpenAPI oas = new OpenAPI().info(new Info().title(title));
        SwaggerConfiguration oasConfig = new SwaggerConfiguration()
                .openAPI(oas)
                .prettyPrint(true)
                .readAllResources(false)
                .resourcePackages(resourcePackages); // do I need both this and the one below? Neither seem to have an effect.
        setResourcePackages(resourcePackages);
        setOpenApiConfiguration(oasConfig);
        return super.getOpenApi(headers, config, app, uriInfo, type);
```

However, each endpoint returns ALL of the paths/components for all of the BaseOpenApiResource implementations. It's ignoring the resourcePackages scope.

Unless I've misunderstood how to configure it? In which case, this issue then would be "Please tell me how to scope the BaseOpenApiResource correctly so I can have different ones return different specs" :)

**Comment by frantuma** [comment]
thanks for reporting this. Up to latest `2.1.5` version, `BaseOpenApiResource` does not allow to define a [contextId](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#context) which is the way to allow different contexts to coexist within a single application. Up to `2.1.5` you would need to use the underlying [context mechanism](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#context) to resolve the specification, and expose it in your own resources.

Since `2.1.5`, you can instead use multiple `BaseOpenApiResource` subclasses similarly to your example, e.g.:

```
@Path("/resource1/openapi.{type:json|yaml}")
public class Res1 extends BaseOpenApiResource {
    @Context
    ServletConfig config;

    @Context
    Application app;

    @GET
    @Produces({MediaType.APPLICATION_JSON, "application/yaml"})
    @Operation(hidden = true)
    public Response getOpenApi(@Context HttpHeaders headers,
                               @Context UriInfo uriInfo,
                               @PathParam("type") String type) throws Exception {

        OpenAPI oas = new OpenAPI().info(new Info().title("res1"));
        SwaggerConfiguration oasConfig = new SwaggerConfiguration()
                .openAPI(oas)
                .prettyPrint(true)
                .readAllResources(false)
                // scanner implementation only considering defined resourcePackages and classes
                // and ignoring resource packages and classes defined in JAX-RS Application
                .scannerClass(JaxrsAnnotationScanner.class.getName())
                .resourcePackages(Stream.of("io.swagger.sample.resource1").collect(Collectors.toSet()));

        setOpenApiConfiguration(oasConfig);

        return super.getOpenApi(headers, config, app, uriInfo, type);
    }

    // define the unique contextId to be used for this resource
    @Override
    protected String getContextId(ServletConfig config) {
        return "resource1-context-id"; // whatever unique string
    }
}
```

and

```
@Path("/resource2/openapi.{type:json|yaml}")
public class Res2 extends BaseOpenApiResource {
    @Context
    ServletConfig config;

    @Context
    Application app;

    @GET
    @Produces({MediaType.APPLICATION_JSON, "application/yaml"})
    @Operation(hidden = true)
    public Response getOpenApi(@Context HttpHeaders headers,
                               @Context UriInfo uriInfo,
                               @PathParam("type") String type) throws Exception {

        OpenAPI oas = new OpenAPI().info(new Info().title("res2"));
        SwaggerConfiguration oasConfig = new SwaggerConfiguration()
                .openAPI(oas)
                .prettyPrint(true)
                .readAllResources(false)
                // scanner implementation only considering defined resourcePackages and classes
                // and ignoring resource packages and classes defined in JAX-RS Application
                .scannerClass(JaxrsAnnotationScanner.class.getName())
                .resourcePackages(Stream.of("io.swagger.sample.resource2").collect(Collectors.toSet()));

        setOpenApiConfiguration(oasConfig);

        return super.getOpenApi(headers, config, app, uriInfo, type);
    }

    // define the unique contextId to be used for this resource
    @Override
    protected String getContextId(ServletConfig config) {
        return "resource2-context-id"; // whatever unique string
    }
}
```

Please notice that `JaxrsAnnotationScanner` (or custom [scanner](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-configuration#resource-scanning)) must be used, as the default scanner would pick anyway all classes defined in JAX-RS Application, which in your case is the same for all endpoints

Closing ticket, please reopen if you're still experiencing issues or have any comment/question.

**Comment by chriskessel** [comment]
Oh, you pushed 2.1.5 last night just for this? Much appreciated, thanks! 

I had tracked it down to that context-id and Scanner implementation late last night and was thinking I'd have to bulk copy the BaseOpenApiResource to hack in my own per-spec context-id, so this is great!

**Comment by frantuma** [comment]
hehe, wasn't specifically for this, but 2.1.5 was planned for today and it made sense getting this in
