### ISSUE TITLE
How to override model with swagger 2.X

### ISSUE THREAD

**Issue by Nufirdy** [swagger-api/swagger-core#3718]
I'm using swagger-jaxrs2 in my project and I'm having trouble with object schema for a class from 3d party library.
To be specific my API accepts as parameter a string which then is parsed into `ObjectId` from mongodb java driver. It is used as path parameter and in most other schemas.
Problem is that swagger converts it into an object with two properties which is incorrect in my case.
```json
"ObjectId": {
	"type": "object",
	"properties": {
		"timestamp": {
			"type": "integer",
			"format": "int32"
		},
		"date": {
			"type": "string",
			"format": "date-time"
		}
	}
}
```
I want to override schema for `ObjectId` so it would be a simple string but haven't found a simple way to do so.

**Comment by frantuma** [comment]
not sure in which scenario you're experiencing this, please share test code in case; depending if dealing with parameters, POJO properties or response, you can override via annotations, e.g. `ApiParam.type`, or `ApiModelProperty.dataType`

**Comment by Nufirdy** [comment]
I rely on automatic generation of openapi.json provided by swagger. Here's an example of method in my API
```java
@PUT
@Path("{fileId: [a-f0-9]{24}}")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public Response update(@PathParam("fileId") ObjectId id,
                           FileData fileData)
```
```java
public class FileData {

    @BsonId
    private ObjectId id;

//other fields and methods
}
```
It accepts `ObjectId` as path parameter and `FileData` as json in request body which also has `ObjectId`. My API accepts string where `ObjectId` is required and then Jersey parses it from string.

Problem is that swagger generated documentation shows `ObjectId` as an object rather that string. Here's how `FileData` schema looks like in swagger-ui
![image](https://user-images.githubusercontent.com/21147244/95364652-c3c00980-08d9-11eb-84da-89ed87f6a738.png)

I want to override this `ObjectId` schema and get it to show as simple string type, ideally with pattern [a-f0-9]{24}

**Comment by frantuma** [comment]
I believe something like the example below would fit what you need, please close ticket if this answers your question:

```java
@Api
@Path("/")
public class Resource3718 {
    @PUT
    @Path("{fileId: [a-f0-9]{24}}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response update(@PathParam("fileId") ObjectId id,
                           FileData fileData) {
        return null;
    }

    public static class FileData {
        //@BsonId
        @ApiModelProperty(dataType = "string")
        @JsonDeserialize(using = ObjectIdDeserializer.class)
        public ObjectId id;
        //other fields and methods
    }

    public static class ObjectId {
        public ObjectId(String id) { this.id = id; }
        public String id;
        //other fields and methods
    }
    
    // not sure how FileData is deserialized otherwise..
    public static class ObjectIdDeserializer extends JsonDeserializer<ObjectId> {

        @Override
        public ObjectId deserialize(JsonParser p, DeserializationContext ctx)
                throws IOException {
            return new ObjectId(p.getText());
        }
    }
}
```

which resolves into:

```yaml
swagger: "2.0"
paths:
  /{fileId}:
    put:
      operationId: "update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "fileId"
        in: "path"
        required: true
        type: "string"
        pattern: "[a-f0-9]{24}"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/FileData"
      responses:
        default:
          description: "successful operation"
definitions:
  FileData:
    type: "object"
    properties:
      id:
        type: "string"

```

**Comment by Nufirdy** [comment]
I guess I confused you a little. First I think we're talking about different versions of swagger. I'm using [Swagger 2.X](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started)
Here's my maven dependency
```xml
<dependency>
         <groupId>io.swagger.core.v3</groupId>
         <artifactId>swagger-jaxrs2</artifactId>
         <version>2.1.2</version>
</dependency>
```
And I don't have annotations that you provided in your example. Also I don't see why I need a custom deserializer for `ObjectId` in this situation.
Secondly my example with `FileData` is one specific case. I want to change the way swagger resolves `ObjectId` for the whole documentation. I do know that I can do something like this for methods
```java
@Parameter(name = "fileId",
        in = ParameterIn.PATH,
        schema = @Schema(type = "string",
                pattern = "[a-f0-9]{24}"))
@PUT
@Path("{fileId: [a-f0-9]{24}}")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public Response update(@PathParam("fileId") ObjectId id,
                           FileData fileData)
```
and something like that on object fields 
```java
@Schema(type = "string")
@BsonId
private ObjectId id;
```
But that would require me to make this changes to all the model classes I have and all methods that parse `ObjectId` from parameter string. I'm looking for a way to make change in a single place. And also `ObjectId` is a class from 3d party library so I can't put any annotations on it directly.

**Comment by frantuma** [comment]
Right, for some reason I thought you meant Swagger/OpenAPI 2.0 and not swagger-core 2.x 

To handle it consistently across the project you can provide a [custom converter](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver), e.g.:


```java
    public static class ObjectIdAwareConverter implements ModelConverter {

        @Override
        public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
                JavaType _type = Json.mapper().constructType(type.getType());
                if (_type != null) {
                    Class<?> cls = _type.getRawClass();
                    if (ObjectId.class.isAssignableFrom(cls)) {
                        return new StringSchema().pattern("[a-f0-9]{24}}");
                    }
                }
            if (chain.hasNext()) {
                return chain.next().resolve(type, context, chain);
            } else {
                return null;
            }
        }
    }
```

and register it with its fully qualified name as `modelConverterClasses` property of [Configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties) or - if you're doing things programmatically - by calling `ModelConverters.getInstance().addConverter(new ObjectIdAwareConverter());` in your bootstrap.

**Comment by Nufirdy** [comment]
Perfect! That's exactly what I needed. Great thanks

**Comment by 0x7162** [comment]
@Nufirdy 
what import did you use for `@Schema`? (i.e. for swagger v2)

I found it just for v3:
```
import io.swagger.v3.oas.annotations.media.Schema;
```
