### ISSUE TITLE
Invalid references to enumAsRef-enums when TypeNameResolver is configured with useFqn=true 

### ISSUE THREAD

**Issue by gsson** [swagger-api/swagger-core#3727]
I have a project containing enums annotated with `@Schema(..., enumAsRef=true)`. I also have some classes with the same "simple name". To avoid schema name I have set the `TypeNameResolver` `useFqn` flag to `true`, but that causes references to enums to be generated without the leading `#/components/schemas/`, making the doc parsers ever so confused.

From what I can tell, this is what is going on;

1. [ModelResolver.resolve(...)](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L122) is invoked
   1. In one of several places,
        1. [AbstractModelConverter._typeName(...)](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/AbstractModelConverter.java#L62) is invoked
           1. [AbstractModelConverter._findTypeName(..)](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/AbstractModelConverter.java#L72) is invoked
              1. [TypeNameResolver. nameForType(...)](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/TypeNameResolver.java#L30) is invoked, and returns the fully qualified name `com.foo.MyEnum`
   1. On [this line](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L343); `model = new Schema().$ref(name);` (with `name` == `"com.foo.MyEnum"`)
      1. [Schema.$ref(...)](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L616) is invoked, with the fqn of my enum
         1. [Schema.set$ref(...)](https://github.com/swagger-api/swagger-core/blob/25fb0d5761346b61a42cec1b982eb31822c28733/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L609) is invoked with the fqn
            1. This statement `if ($ref != null && ($ref.indexOf('.') == -1 && $ref.indexOf('/') == -1)) {` does not match the fqn of my enum since it contains a `.`, causing the `#/components/schemas/` prefix to be omitted.

This means the `$ref` field in the generated doc will not contain the necessary prefix to make it a "fragment" reference.

I'm not sure if the correct approach would be to make `TypeNameResolver. getNameOfClass(...)` return a somehow quoted name (around _1.i.a.a_), `$ref(constructRef(name))` in _1.ii_, update the condition in _1.ii.a.a.a_ or something else...

**Comment by frantuma** [comment]
Thanks for investigating and reporting this! fixed in #3728 by going for explicit prefix in 1.ii
