### ISSUE TITLE
Missing public pgp key from version 2.1.4

### ISSUE THREAD

**Issue by slawekjaranowski** [swagger-api/swagger-core#3750]
From version `2.1.4` new pgp key is used to signing maven artifacts. 

New key has fingerprint: 

`0x3E61D8C230332482009D7F0EDB901B24CAD38BC4` 

but is not available on public key servers so verification of signature is not possible.

Please upload corresponding pgp key to public key servers.

We can check:

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=io.swagger.core.v3:swagger-core:2.1.3

```

but for newer version is not possible due to missing key

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=io.swagger.core.v3:swagger-core:2.1.5

```

**Comment by frantuma** [comment]
Thanks for reporting this! key should be correctly up now, closing ticket, please reopen if you're still experiencing issues
