### ISSUE TITLE
additionalProperties does not have to be "either a Boolean or a Schema instance"

### ISSUE THREAD

**Issue by MosheElisha** [swagger-api/swagger-core#3850]
Currently, [the code](https://github.com/swagger-api/swagger-core/blob/9b80abf67fea35171277dc197779b6303a1b3a52/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Schema.java#L552) enforces that "additionalProperties must be either a Boolean or a Schema instance".

According to https://swagger.io/docs/specification/data-models/dictionaries/ and https://github.com/OAI/OpenAPI-Specification/issues/668#issuecomment-755415337, the following structure is also valid:

```
type: object
additionalProperties:
  type: string
```

This is the openapi that represents (and is generated) when the model is a Map of string and string (`Map<String, String>`).

**Comment by frantuma** [comment]
The enforced behaviour/structure does not seem contradictory to me:

```
 additionalProperties:
  type: string
```

is implemented/deserialized in `swagger-core` with `additionalProperties` being a `Schema` with `type = "string"` (`StringSchema`)

**Comment by frantuma** [comment]
I am not sure how you are deserializing and in which scenario, but from your logs it looks like you're using some possibly not configured `ObjectMapper`; `swagger-core` provides helper class [Json](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/Json.java) (and similar [Yaml](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/Yaml.java)) giving access to a correctly configured mapper which - depending on scenario - you would use e.g. like:

`Json.mapper().readValue(openApiAsString, OpenAPI.class);`

Please close ticket if this answers your question

**Comment by MosheElisha** [comment]
@frantuma Perfect. Thank you. I was using a default ObjectMapper. Using `io.swagger.v3.core.util.Json` it worked properly.

**Comment by michaelwangwangwang** [comment]
good

**Comment by GeniusDP** [comment]
Works

**Comment by mynameiswangyang** [comment]
nice

**Comment by aditambi** [comment]
working
