### ISSUE TITLE
type information for response schema

### ISSUE THREAD

**Issue by judos** [swagger-api/swagger-core#3851]
How do I provide type information to a response schema?

When a service method has the following response type: `ResponseEntity<PageDto<CustomerDto>>` swagger correctly displays all type information I want to see.

However when I have multiple possible responses I would like to provide the same details via annotation and there I don't know how to provide the type information of the PageDto<T>:
```
@ApiResponses(value = [
  ApiResponse(responseCode = "200", content = [Content(
    schema = Schema(implementation = PageDto::class))]),
  ApiResponse(responseCode = "400",
    content = [Content(schema = Schema(implementation = ErrorDto::class))])
])
fun getAll(): ResponseEntity<Any> {
  if (...) {
    return ResponseEntity.badRequest().body(ErrorDto("ERROR KEY"))
  }
  return ResponseEntity.ok(PageDto(result))
}
```

Swagger obviously doesnt know what type T the PageDto<T> class contains. How do I provide this information such that the documentation is generated with better details?

Thanks for your help!

**Comment by frantuma** [comment]
#4129 addresses this by introducing field  `@ApiResponse.useReturnTypeSchema`, which allows to mark a response to use the return type for its schema. Please see comment in PR for an example
