### ISSUE TITLE
allOf refs are broken when using fully qualified model names

### ISSUE THREAD

**Issue by haakonmt** [swagger-api/swagger-core#3853]
I am using Swagger (2.1.6) through `springdoc-openapi` (1.5.2) to generate json schemas for my Spring Boot services. Due to having name clashes, I have to set the `TypeNameResolver#useFqn` flag to true. This leads to allOf-refs (subtypes) being broken, as they are not prefixed with `#/components/schemas/`. It looks very similar to [this issue](https://github.com/swagger-api/swagger-core/issues/3727). [This line](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L1352) looks like it _might_ be the culprit, but haven't had the time do dig into the code properly.

**Comment by frantuma** [comment]
Thanks for reporting this. Can you possibly add a test code reproducing the issue?

**Comment by frantuma** [comment]
Thanks for reporting and investigating this! fixed in #4146
