### ISSUE TITLE
PrettyPrint configuration is not picked up from config file

### ISSUE THREAD

**Issue by mjaggard** [swagger-api/swagger-core#3868]
The documentation here: https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-maven-plugin
states that `prettyPrint` can be set in the configuration file but it is actually ignored and must be set in the `pom.xml` file.

This line reads directly from the Maven config rather than the parsed configuration file:
https://github.com/swagger-api/swagger-core/blob/f1fcdc233aeab4bc0beab35284c59c6d4f64df6d/modules/swagger-maven-plugin/src/main/java/io/swagger/v3/plugin/maven/SwaggerMojo.java#L101

**Comment by frantuma** [comment]
Thanks for reporting this and investigating! fixed in #3874
