### ISSUE TITLE
Gradle plugin fails randomly

### ISSUE THREAD

**Issue by patrickpichler** [swagger-api/swagger-core#3876]
Hi,

I'm experiencing a strange issue. For some reason the `resolve` task fails for some people but 
not for others. 

We narrowed the issue down that it has to be somehow classpath ordering related, as we have 
two conflicting versions of `swagger-core` in our classpath. This is an issue of its own but we 
never noticed, as the build never failed. 

I guess the reason we experiencing this, is that the resolve task uses an `Set` to filter out 
duplicated urls [here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java#L338).
As this set then gets transformed to an array the ordering is not stable. Which means that
for some of my colleagues the wrong version is earlier in the resulting url classpath causing
the build to fail.

**Comment by patrickpichler** [comment]
This is fixed by #3877

**Comment by frantuma** [comment]
Thanks for reporting and providing the fix! merged #3877
