### ISSUE TITLE
Sorting Parameter examples? on swagger-annotations-2.0.6

### ISSUE THREAD

**Issue by drewhagen** [swagger-api/swagger-core#3902]
My team and I have been creating Swagger documentation for our API, and we want to provide examples for the parameters In this case, we have "filter" and "sort" parameters over a GET all records method.
We'd like a blank example to be selected by default, so that when a doc user clicks "Try it Out", the "filter" and "sort" fields are not populated with other examples that might then get sent in the request and filter the response.

How does one either set an ExampleObject to be the default selected, or sort the Parameter's examples so that a desired example shows first (and thus is selected by default?)
![image](https://user-images.githubusercontent.com/2896571/108776814-82e32d00-7528-11eb-815b-9be2335caab2.png)

The example dropdown options are not populated in the order we've written them in source code. It also doesn't seem like it alpha sorts by the "name" or "summary".

**Comment by frantuma** [comment]
Is this related to Swagger Core? With `we've written them in source code` do you mean java code or the spec itself? if it's indeed a Swagger Core Java issue, can you provide a test case? if not, issue should be probably moved to Swagger UI
