### ISSUE TITLE
ApplicationPath Concadinated in ResourcePath in generated openapi.json.

### ISSUE THREAD

**Issue by ChaitanyaBabar** [swagger-api/swagger-core#3903]
### Problem :- For Generated _openapi.json_ the _resourcePath_ contain the basePath as well.

Generated the openapi.json defination contains the **_resourcePath_** **prefixed** with **_basePath_**.

### Code Sample
**Application File**
```
@ApplicationPath("/petstore-basepath")
@ApplicationScoped
public class MyApplication extends Application {
	 public MyApplication(@Context ServletConfig servletConfig) {
               super();
               OpenAPI oas = new OpenAPI();
		   ...		
	 }
}
```

**Resources File**
```
@Path("/store")
@Produces({"application/json", "application/xml"})
public class PetStoreResource {

  @GET
  @Path("/order/{orderId}")
  @Operation(
          summary = "Find purchase order by ID",
          description = "For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions",
          responses = {
                  @ApiResponse(content = @Content(schema = @Schema(implementation = Order.class))),
                  @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
                  @ApiResponse(responseCode = "404", description = "Order not found")
          }
  )
  public Response getOrderById(){

  }

}
```

### Generated _openapi.json_ 

**Actual Behavior**
```
{
  "openapi": "3.0.1",
  "servers": [
    {
      "url": "http://pet-domain/gsbc/MOCK_GSBC_FOR_ALL_GSBCS/tci/petstore-basepath",
      "description": "server 1"
    }
  ],
  "paths": {
    "/petstore-basepath/pet/{petId}": {
     }
  }
}
```

**Output Required**
```
{
  "openapi": "3.0.1",
  "servers": [
    {
      "url": "http://pet-domain/gsbc/MOCK_GSBC_FOR_ALL_GSBCS/tci/petstore-basepath",
      "description": "server 1"
    }
  ],
  "paths": {
    "/pet/{petId}": {
     }
  }
}
```

The Path specified in _**@ApplicationPath**_ is getting concatenated in ResourcePath specified by _@Path_.
So is there any way where we can **avoid the concatenation** of _ApplicationPath_ in _ResourcePath_.

### Library Used.

```
		<dependency>
		    <groupId>io.swagger.core.v3</groupId>
		    <artifactId>swagger-jaxrs2</artifactId>
		    <version>2.0.1</version>
		</dependency>
```

**Comment by frantuma** [comment]
Generally, as mentioned in https://github.com/swagger-api/swagger-core/issues/3523#issuecomment-650571106 with reference to a similar scenario, Web app "home directory" or "base path" or "application path" can be defined in many different ways in many different environments.

The "default" way in case an `@ApplicationPath` is present, is to perpend it to paths. In your case or in other scenarios this might be not desired, the two easiest ways to customize this behaviour is either [extending Reader]() or [using a filter]()

You would for example override `resolveApplicationPath()` returning an empty string, or adding a filter and updating all keys of openAPI.getPaths(). 

Another option in your case is not adding that path to your server URL.

Also you would possibly use latest version as `2.0.1` is pretty old, even if it doesn't make a difference for application path resolving

Related tickets for reference:

* https://github.com/swagger-api/swagger-core/issues/3903
* https://github.com/swagger-api/swagger-core/issues/3545
* https://github.com/swagger-api/swagger-core/issues/3025
* https://github.com/swagger-api/swagger-core/issues/3523
* https://github.com/swagger-api/swagger-core/issues/3524

Closing ticket, please reopen if you're still experiencing issues
