### ISSUE TITLE
@Schema annotation is not picked up when using @JsonValue from Jackson

### ISSUE THREAD

**Issue by martin-tarjanyi** [swagger-api/swagger-core#3904]
See: https://github.com/springdoc/springdoc-openapi/issues/1077

I debugged the code and I found the issue at the following place:

https://github.com/swagger-api/swagger-core/blob/438230d79d4597d6b703437a03c32cdbf8a28ba5/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L371-L379

Unlike in [other places](https://github.com/swagger-api/swagger-core/blob/438230d79d4597d6b703437a03c32cdbf8a28ba5/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L409), at this point the `.ctxAnnotations(schemaAnnotations)` method is not called which results in the loss of data coming from `@Schema` annotation.

**Comment by frantuma** [comment]
Thanks for reporting and investigating! Fixed in #3930

**Comment by osmantassdelen** [comment]
Hello,

When I use @JsonValue annotation, @Shema annotation is not seen. Example code is below:

public class Student {

  @Schema(description = "Student name")
  private final String value;
  
  private Student (String value){
     this.value = value;
  }
  @JsonValue
  public String getValue() {
     return value;
  }
}

Expected:
   Student:
      description: Student name,
      type: string

but actual,
Description is not seen.
