### ISSUE TITLE
What's the correct/swagger way to document the request body of a POST method that posts a complex object?

### ISSUE THREAD

**Issue by mikemil** [swagger-api/swagger-core#391]
We are using Swagger but writing the JSON manually (for now - will get automated later).   We have some resources that use POST and the post body is a complex object representation in either XML or JSON.

I have tried the following - but haven't really seen any good examples.  I have the paramType of body and the dataType as Customer.  Is this how you intended this?

The demo project only shows GET requests and really doesn't include a good set of sample coverage of the different parameter types, etc.

partial snippet:
{
     "path": "/v1/customers",
      "operations": [
        {
          "method": "POST",
          "summary": "Creates a new customer",
          "notes": "Creates a new customer using the given customer object.",
          "responseClass": "Customer",
          "nickname": "",
          "produces": [
            "application/json",
            "application/xml"
          ],
          "parameters": [
            {
              "name": "body",
              "description": "Customer object",
              "required": true,
              "allowMultiple": false,
              "dataType": "Customer",
              "paramType": "body"
            }
          ],
         "errorResponses": [
            {
              "code": 400,
              "message": "Bad Request. Customer was not created."
            }
          ]
        }
        ]
    }

**Comment by AntonTutuka** [comment]
@fehguy Hello, I want to describe XML-RPC API using swagger. 
On your screenshot the body showed as xml. How can I achieve the same?
```
swagger: '2.0'
info:
  title: Tutuka Companion API
  description: Description goes here
  version: "1.0.0"
# the domain of the service
host: api.tutuka.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1

paths:
  /LinkCard:
    post:
      description: LinkCard desc goes here
      
      consumes:
        - application/xml
      produces:
        - application/xml
      
      parameters:
        - name: request
          in: body
          description: links card
          required: true
          schema:
            $ref: "#/definitions/LinkCardResponse"
            
  
      
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/LinkCardResponse"
    
  
definitions:
  LinkCardResponse:
    properties:
      resultCode:
        type: integer
      result:
        type: string
    
```

result: http://joxi.ru/GrqxB0vt7D8RAz

**Comment by fehguy** [comment]
Swagger is geared towards REST, not RPC, so you can do it but it may be difficult

**Comment by AlwaysAbhl001** [comment]
![post](https://cloud.githubusercontent.com/assets/26591838/24243828/79d76ba4-0fe2-11e7-8c1f-37507874ca4f.JPG)

{
    "swagger": "2.0",
    "info": {
        "title": "Sample Employee Api Docmentation",
        "version": "v1"
    },
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json",
        "application/xml"
    ],
    "produces": [
        "application/json",
        "application/xml"
    ],
    "host": "localhost/SwaggerTest",
    "paths": {
        "/api/DeleteEmployee/{id}": {
            "delete": {
                "summary": "Delete an Employee",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "An employee record deleted based on Id",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee Deleted Sucessfully"
                    }
                }
            }
        },
        "/api/EmployeebyID/{Id}": {
            "get": {
                "operationId": "FindEmployeebyId",
                "summary": "Get Employee based on Id",
                "parameters": [
                    {
                        "name": "Id",
                        "in": "path",
                        "description": "EmpId is an integer of format int32",
                        "required": true,
                        "type": "integer",
                        "format": "int32"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucessfull",
                        "schema": {
                            "$ref": "#/definitions/Employees"
                        }
                    }
                }
            }
        },
        "/api/Employees": {
            "get": {
                "summary": "Get All Employees.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Employees"
                            }
                        }
                    }
                }
            }
        },
        "/api/Employeebyage/{Age}": {
            "get": {
                "description": "Return the Employee based on Id",
                "summary": "Get Employee based on age.",
                "operationId": "FindEmployeebyage",
                "parameters": [
                    {
                        "name": "Age",
                        "in": "path",
                        "description": "age is an integer of format int32",
                        "required": true,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucessfull",
                        "schema": {
                            "$ref": "#/definitions/Employees"
                        }
                    }
                }
            }
        },
        "/api/AddEmployee": {
            "post": {
                "summary": "Add an Employee",
                "description": "Adds a new Employee to the employees list.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "type": "Employee",
                        "required": true,
                        "description": "An Employee to create.",
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee Added Sucessfully"
                    }
                }
            }
        },
        "/api/UpdateEmployee": {
            "post": {
                "summary": "Update an Employee",
                "description": "Updates an exist employee",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "description": "An Employee to be updated.",
                        "schema": {
                            "$ref": "#/definitions/Employees"
                        }

                    }
                ],
                "responses": {
                    "200": {
                        "description": "Employee Added Sucessfully"
                    }
                }
            }
        }

    },
    "definitions": {
        "Employees": {
            "type": "object",
            "properties": {
                "EmpId": {
                    "type": "integer",
                    "format": "int32"
                },
                "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                }
            }
        },
        "Employee": {
            "Type":"Employee", 
            "required": [
                "FirstName",
                "LastName",
                "age"
            ],
            "properties": {
                "FirstName": {
                    "type": "string"
                },
                "LastName": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                }
            }
        }
    }
}

@fehguy   for both PUT and POST unable to carry parameters to controller, what would be the mistake ?
