### ISSUE TITLE
Feature Request: OpenAPI Spec 3.1

### ISSUE THREAD

**Issue by xiaoxiangmoe** [swagger-api/swagger-core#3913]
OAS 3.1 was released, can we support OpenAPI Spec 3.1?
OSA 3,1 has some new feature, such as [namedEnum](https://github.com/OAI/OpenAPI-Specification/issues/681) and so on.

**Comment by rk3rn3r** [comment]
+1 Would be great to have `patternProperties` from that JSON Schema draft 2020-12 extension which is part of OAS3.1.

**Comment by DepickereSven** [comment]
Then could this issue be fixed to https://github.com/swagger-api/swagger-core/issues/3900

**Comment by daltontc** [comment]
+1 The ability to do `explode` for `multipart/form-data` arrays would be a great feature.

**Comment by frantuma** [comment]
#4129 introduces support for OAS 3.1 representation (swagger-models), serialization and deserialization. code first resolution of OAS 3.1 spec in `ModelResolver` and JAXRS Reader (both via conversion and additional annotations resolution) is on the way

**Comment by Xbloud** [comment]
The referenced short term roadmap is 1.5 years old and the current version still does not support OpenAPI 3.1 fully. I am especially interested in a feature allowing addition any sibling properties next to $ref in object schema (generating OpenAPI spec from java annotations). Can you, please, provide refined roadmap?

**Comment by Fares-Harri** [comment]
is there any update about supporting OpenAPI 3.1?

**Comment by frantuma** [comment]
Swagger Core does support OAS 3.1 in terms of representation, (de)serializaization and resolving. Please see [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---OpenAPI-3.1) for details
