### ISSUE TITLE
@ApplicationPath is not working?

### ISSUE THREAD

**Issue by rider87** [swagger-api/swagger-core#3935]
Hi, 

I´m currently installing Swagger, but it seems the @ApplicationPath is not working as expected.

I have the following code:
```
@ApplicationPath("/service")
@Api( tags = "docs" )
@OpenAPIDefinition(info = @Info(
        title = "My application", 
        version = "1.0.0", 

)
public class SwaggerApplicationConfig extends Application {
	
}
```

In Web.xml:
```
<servlet-mapping>
		<servlet-name>javax.ws.rs.core.Application</servlet-name>
		<url-pattern>/service/*</url-pattern>
	</servlet-mapping>
```

Example Endpoint:
```
/**
 * Customer Endpoints
 */
@Path("/customer")
@Tag(name = "Customer", description = "Returns all information for customers")
public class CustomerWebservice {

	@GET
	@Path("/")
	@Produces(MediaType.APPLICATION_JSON)
	@ApiOperation(value = "Returns all Customer", notes = "Returns Customer", response = Response.class)
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Successful, returning the value"),
			@ApiResponse(responseCode = "404", description = "Not found"),
			@ApiResponse(responseCode = "500", description = "Internal Server Error")
	})
	public Response findAllCustomers() {
		try {
				return Response.ok(customerDtoList, MediaType.APPLICATION_JSON)
					.build();

		} catch (Exception e) {
			LOGGER.error(ExceptionUtils.getFullStackTrace(e));

			ErrorMessage errorMessage = new ErrorMessage(e.getMessage(), Status.INTERNAL_SERVER_ERROR.getStatusCode());
			return Response.status(Status.INTERNAL_SERVER_ERROR).entity(errorMessage).type(MediaType.APPLICATION_JSON)
					.build();
		}
	}

I´m using those libs:
`<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2</artifactId>
			<version>2.1.8</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer-v2</artifactId>
			<version>2.1.8</version>
		</dependency>
```

The json File is generated, but the URL is only:
**http://localhost:8080/customer**

But it should be:
**http://localhost:8080/service/customer**

Here in the Swagger GUI:
![image](https://user-images.githubusercontent.com/9787533/115228144-b1891880-a111-11eb-80bb-2d328168dcc0.png)

Any idea what needs to be changed?

**Comment by frantuma** [comment]
Can you share some more details about your configuration, like a test project / scenario reproducing the issue?

**Comment by rider87** [comment]
What kind of other configuration are needed besides my first code?
Is there anything which is not correct from my first post?

**Comment by frantuma** [comment]
for example there is no clue about which JAX-RS implementation you are using, the full deps of your project, the server in use and how you launch, how resources are registered, if there is any additional config

**Comment by rider87** [comment]
Ok, thanks....

I´m using 
- Wildfly 21
- import javax.ws.rs.core.Application;
- Maven build the .war file

`		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2</artifactId>
			<version>2.1.8</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer-v2</artifactId>
			<version>2.1.8</version>
		</dependency>`


In my web.xml
`	<servlet-mapping>
		<servlet-name>javax.ws.rs.core.Application</servlet-name>
		<url-pattern>/service/*</url-pattern>
	</servlet-mapping>

	<servlet>
		<servlet-name>OpenApi</servlet-name>
		<servlet-class>io.swagger.v3.jaxrs2.integration.OpenApiServlet</servlet-class>
		<init-param>
			<param-name>openApi.configuration.resourcePackages</param-name>
			<param-value>io.swagger.sample.resource</param-value>
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>OpenApi</servlet-name>
		<url-pattern>/openapi/*</url-pattern>
	</servlet-mapping>`

My config:
`@ApplicationPath("/service")
@Api( tags = "docs" )
@OpenAPIDefinition(info = @Info(
        title = "My application", 
        version = "1.0.0", 

)
public class SwaggerApplicationConfig extends Application {
	
}`

**Comment by frantuma** [comment]
Please try with version `2.1.9` and adding init-param (or via [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration)) `alwaysResolveAppPath` like:

```
    <init-param>
        <param-name>openApi.configuration.alwaysResolveAppPath</param-name>
        <param-value>true</param-value>
    </init-param>
```

see also #3060

Please close tickets if it solves your issue

**Comment by rider87** [comment]
Thanks, but 2.1.9 is not available on maven?
Latest is 2.1.8

Please see also:
https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-jaxrs2

		```
<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2</artifactId>
			<version>2.1.9</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer-v2</artifactId>
			<version>2.1.9</version>
		</dependency>
```

**Comment by frantuma** [comment]
It takes up to a few hours for sonatype to publish release, please check again in a bit

**Comment by rider87** [comment]
Great, it´s working. Many thanks
