### ISSUE TITLE
Property description are missing

### ISSUE THREAD

**Issue by rider87** [swagger-api/swagger-core#3942]
Hello, 

First of all I´m not 100% sure if I understand it correctly:
Before you had a called "**Model**" in Swagger, here an example from an API which is available in the internet:
![image](https://user-images.githubusercontent.com/9787533/115525931-d73c2c00-a28f-11eb-9d49-e0a87ce3d81a.png)

And now it called "**Schema**" ? 
![image](https://user-images.githubusercontent.com/9787533/115526207-179baa00-a290-11eb-9ad2-ce0485a9d13f.png)

What I´m missing in the "Schema" are the "description", "possible values", "examples..." etc.

I´m trying to do this:
```
@ApiModel(value = "Customer", description = "Model for Customers")
public class CustomerDto {
	
	@ApiModelProperty(value = "Number for the customer")
	private String customerNumber;
```
I´ve tried also that:

```
@Schema(description = "Model for Customers")
public class SalutationDto {
	
	@Schema(value = "Number for the customer")
	private String customerNumber;
```

But it will be not considered in the Swagger UI / in the swagger.json....
![image](https://user-images.githubusercontent.com/9787533/115528069-fb990800-a291-11eb-9b79-93ef4132a5e7.png)

 I´m using those libs:
```
<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2</artifactId>
			<version>2.1.9</version>
		</dependency>
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-jaxrs2-servlet-initializer-v2</artifactId>
			<version>2.1.9</version>
		</dependency>
```

Any idea what is wrong?

**Comment by frantuma** [comment]
you are using Swagger Core 2.x (2.1.9) so you need 2.x Annotations (e.g. `@Schema`), please check [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations). 

Also your UI result seems to refer to a different schema (CustomerDTO) than the one annotated

**Comment by rider87** [comment]
Unfortunatelly it´s not working for me:

I´ve tried that:
```
@Schema(name="Customer",  description = "Model for Customer")
public class CustomerDto {

	@Schema(description = "Number from the customer", example = "123456")
	private String customerNumber;
```

But seems not visible:
![image](https://user-images.githubusercontent.com/9787533/115564079-6c531b00-a2b8-11eb-912f-fb55cb0492f9.png)

**Comment by rider87** [comment]
Ok, found it... I have to add it in the jax-rs function like this:

```	@GET
	@Path("/")
	@Produces(MediaType.APPLICATION_JSON)
	@Operation(summary = "Get customers", description = "Get list of customers", responses = {

			@ApiResponse(responseCode = "200", description = "Successful, returning the value", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = CustomerDto.class))),
			@ApiResponse(responseCode = "401", description = "Authentication required"),
			@ApiResponse(responseCode = "404", description = "Not found"),
			@ApiResponse(responseCode = "500", description = "Internal Server Error")
	})

	public Response findAllCustomers(@Context HttpServletRequest request,
			@HeaderParam(ConstantsWebservice.X_API_KEY) String apiKey,
			@DefaultValue(ConstantsWebservice.STARTING_AT_DEFAULT) @QueryParam(ConstantsWebservice.STARTING_AT) int startingAt,
			@DefaultValue(ConstantsWebservice.ENDING_AT_DEFAULT) @QueryParam(ConstantsWebservice.ENDING_AT) int endingAt,
			@DefaultValue(ConstantsWebservice.LIMIT_DEFAULT) @QueryParam(ConstantsWebservice.LIMIT) int limit) {
```

Thanks for your help
