### ISSUE TITLE
swagger-gradle-plugin-jakarta:2.1.9 is not working

### ISSUE THREAD

**Issue by anirtek** [swagger-api/swagger-core#3948]
I use gradle based project Jetty 11 that works only with Jakarta EE 9 namespace. According to the docs at [swagger-gradle-plugin](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-gradle-plugin/README.md) I am supposed to use `-jakarta` suffix with dependency `id "io.swagger.core.v3.swagger-gradle-plugin" version "2.1.9"`.

But when I use this as `id "io.swagger.core.v3.swagger-gradle-plugin-jakarta" version "2.1.9"` it fails. How do I fix this? 

My overall graddle looks like this - 

```
plugins {
    id 'java'
    id "io.swagger.core.v3.swagger-gradle-plugin-jakarta" version "2.1.9"
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    compile 'org.eclipse.jetty:jetty-server:11.0.0'
    compile 'org.eclipse.jetty:jetty-util:11.0.0'
//    compile 'org.apache.commons:commons-lang3:3.7'
//    compile 'io.swagger.core.v3:swagger-jaxrs2-jakarta:2.1.7'
//    compile 'jakarta.ws.rs:jakarta.ws.rs-api:3.0.0'
//    compile 'jakarta.servlet:jakarta.servlet-api:5.0.0'
}

resolve {
    outputFileName = 'HfsOpenAPI'
    outputFormat = 'YAML'
    classpath = sourceSets.main.runtimeClasspath
    buildClasspath = classpath
    resourcePackages = ['io.test']
    outputDir = file('main/resources')
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes "Main-Class": "com.example.hfs.HFS"
    }

    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

**Comment by frantuma** [comment]
Hi, the plugin itself is not providing a different artifact, but it can support jakarta NS by using the related artifacts in classpath, as mentioned in readme. `ID` remains `"io.swagger.core.v3.swagger-gradle-plugin-jakarta", please use that along with a `buildClasspath` including the `jakarta` artifacts as mentioned in readme

**Comment by anirtek** [comment]
@frantuma can you provide some example that I can refer?

**Comment by anirtek** [comment]
@frantuma so do you mean, in my gradle - 
```
id "io.swagger.core.v3.swagger-gradle-plugin" version "2.1.9"
```
and dependency section - 
```
implementation 'org.apache.commons:commons-lang3:3.7'
implementation 'io.swagger.core.v3:swagger-jaxrs2-jakarta:2.1.7'
implementation 'jakarta.ws.rs:jakarta.ws.rs-api:3.0.0'
implementation 'jakarta.servlet:jakarta.servlet-api:5.0.0'
```
and then in the tasks, I mentions buildClassPath like this? -
```
resolve {
    buildClasspath = classpath
    outputFileName = 'MyRestAPI'
    outputFormat = 'JSON'
    prettyPrint = 'TRUE'
    classpath = sourceSets.main.runtimeClasspath
    resourcePackages = ['io.test']
    outputDir = file('test')
}
```
Because, "**io.swagger.core.v3.swagger-gradle-plugin-jakarta" version "2.1.9"** is not fetching anything but "**io.swagger.core.v3.swagger-gradle-plugin" version "2.1.9"** does.

**Comment by anirtek** [comment]
Looks like this is not compatible with Jersey 3.x that I am working. I am opening another issue to track this as this seems to be a stale one and not active at the moment w.r.to others.
