### ISSUE TITLE
Is swagger-core compatible with Jersey 3.x?

### ISSUE THREAD

**Issue by anirtek** [swagger-api/swagger-core#3951]
I am using Jetty 11 that works with Jersey 3.x and does not support Jersey2-jaxrs. Is there any way I can get swagger-core integration to work?

**Comment by frantuma** [comment]
Also with reference to #3948, gradle plugin and other `jakarta` artifacts (as described in READMEs and wiki) should work ok with Jersey 3.x. This could be possibly related to some config issue with Jetty, Jersey and/or swagger but it's hard to say. We would need a test project/scenario reproducing the issue.

as an example, the following gradle config for a grizzly / jersey 3.0.2 "quickstart" project works fine:

```
plugins {
    id 'java'
    id 'application'
    id "io.swagger.core.v3.swagger-gradle-plugin" version "2.1.9"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    javaMainClass = "io.swagger.Main"
}

application {
    mainClassName = javaMainClass
}
dependencies {
    implementation platform('org.glassfish.jersey:jersey-bom:3.0.2')
    implementation 'org.glassfish.jersey.containers:jersey-container-grizzly2-http'
    implementation 'org.glassfish.jersey.inject:jersey-hk2'
    implementation 'org.glassfish.jersey.media:jersey-media-json-binding'
    implementation 'org.apache.commons:commons-lang3:3.7'
    implementation 'io.swagger.core.v3:swagger-jaxrs2-jakarta:2.1.9'
    implementation 'jakarta.ws.rs:jakarta.ws.rs-api:3.0.0'
    implementation 'jakarta.servlet:jakarta.servlet-api:5.0.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

resolve {
    outputFileName = 'MyRestAPI'
    outputFormat = 'JSON'
    prettyPrint = 'TRUE'
    classpath = sourceSets.main.runtimeClasspath
    buildClasspath = classpath
    resourcePackages = ['io.swagger']
    outputDir = file('test')
}
```

**Comment by anirtek** [comment]
@frantuma  This is my sample project: https://github.com/anirtek/jetty-jersey-swagger 
In StartHFS.java file, line#90 I am adding jersey servlet into Jetty servlet holder. Please let me know if this helps to make my question clear and understand better? 

I am using Jakarta artifacts in this project as per the previous gradle based plugin for swagger-core.

**Comment by anirtek** [comment]
@frantuma I think this really worked for me. I was able to fix the annotation when the mail-list helped me for Jersey integration. I am however, not able to generate swagger.json on the path localhost:8080/api/swagger.json. I am referring to the Jetty Swagger integration at https://gist.github.com/nosmokingpistol/302c4c3ef30f183cf70e

**Comment by frantuma** [comment]
@anirtek I am not sure I get what you are saying and what problems you are facing. Does `I think this really worked for me` mean that you have your thing working as I mentioned in comment above?
If you start the version in https://github.com/anirtek/jetty-jersey-swagger/compare/main...frantuma:main you will see that the spec is exposed on `http://localhost:8080/api/openapi.json`

> I am however, not able to generate swagger.json on the path localhost:8080/api/swagger.json

As mentioned above, configuring package `io.swagger.v3.jaxrs2.integration.resources` makes the specification available at `/api/openapi.json` and `/api/openapi.yaml`, if you need to change the name to `swagger.json` or other please read [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#extend-baseopenapiresource).

The gist you are referring to seems to be provided by the community and it refers to old version 1.x of swagger, while certain things might apply to 2.x versions, configuration in 2.x is completely different

**Comment by anirtek** [comment]
@frantuma sorry if I confused you. I parallelly also reached out to the Jersey community and learned that I need to change the annotations from spring-based `@RequestBody` to JAX-RS based `@Context` for the parameters in my API. I was able to resolve the issue by the time you replied. So yes, the problem is now solved for Jersey 3.x and Swagger-core compatibility. 

I now need to integrate swagger-ui into jetty which is the last part of the task if you can share something here. I can close the issue after this.

**Comment by anirtek** [comment]
@webron I am trying to follow [visualize-and-interact](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#visualize-and-interact) section from documentation which says that swagger-ui is easily integratable with swagger-core. Following this, I downloaded dist directory from swagger-ui latest tag and copied into /resources/webapp into my code. To take this into effect, I added this as follows into my server code:
```java
// Setup Swagger-UI static resources
String resourceBasePath = ServiceLoader.class.getResource("/webapp").toExternalForm();
servletContextHandler.setWelcomeFiles(new String[] {"index.html"});
servletContextHandler.setResourceBase(resourceBasePath);
servletContextHandler.addServlet(new ServletHolder(new DefaultServlet()), "/*");
```
But I am seeing only default petstore docs and not my apis. What integration can be wrong with me?

**Comment by anirtek** [comment]
@frantuma @webron thank you for all your support. I was able to get the swagger-ui working in Jetty environment. I copied swagger-ui/dist/ content into /webapp directory and changed the pointer to swagger.json location. Closing the issue now.
