### ISSUE TITLE
Jackson enum value is not used if @JsonValue is on an enum field or nonpublic method

### ISSUE THREAD

**Issue by mjustin** [swagger-api/swagger-core#3998]
When Jackson's [`@JsonValue`](http://fasterxml.github.io/jackson-annotations/javadoc/2.12/com/fasterxml/jackson/annotation/JsonValue.html) is used on a public enum method, the Swagger enum list properly uses this value (thanks to #3553).  However, when it is used on an enum field instead, or on a non-public enum method, the Swagger enum list does not.  This causes a discrepancy between what the REST API actually accepts (as defined by Jackson) and what the Swagger definition states it does.

A real quick way to verify this is to update the [`JacksonValueEnum`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/oas/models/JacksonValueEnum.java) in the `swagger-core` test.  The [`EnumPropertyTest.testExtractJacksonEnumFields`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/EnumPropertyTest.java#L204) test will then fail.

```java
public enum JacksonValueEnum {
    FIRST("one"),
    SECOND("two"),
    THIRD("three");

    @JsonValue
    private final String value;

    JacksonValueEnum(String value) {
        this.value = value;
    }
}
```

OR

```java
public enum JacksonValueEnum {
    FIRST("one"),
    SECOND("two"),
    THIRD("three");

    private final String value;

    JacksonValueEnum(String value) {
        this.value = value;
    }

    @JsonValue
    private String getValue() {
        return value;
    }
}
```

**Comment by jadrovski** [comment]
And also @JsonValue not used when on interface method declaration.

```java
public interface ErrorCode {
  @JsonValue
  String code();
}

public enum Code implements ErrorCode {
    SOME_ERROR_CODE("actual_error_code");

    private final String code;

    Code(String code) {
      this.code = code;
    }

    @Override
    public String code() {
      return code;
    }
  }
```

**Comment by bkahlert** [comment]
Had the same issue. Making the `@JsonValue` field / method public resolved the issue for me.

**Comment by T3rm1** [comment]
@frantuma Do you remember why you [switched](https://github.com/swagger-api/swagger-core/commit/63ab0e69d6928120160cf8b35dafc7775212561b#diff-bed6aab5e29942b1a575bded333604f9dfaeb2ef9475f1433266ece4e49f4fcbR969) to `getDeclaredMethods`?
This does not return methods on interfaces. See the example from @jadrovski.
