### ISSUE TITLE
Inherited annotations not observed

### ISSUE THREAD

**Issue by sverhagen** [swagger-api/swagger-core#400]
I'm using `com.wordnik:swagger-jaxrs_2.10:1.3.1` and I'm observing that `@Api...` annotations in parent objects are not observed.

I would like to use `@Api...` annotations on both my Java interface as well as on an (abstract) base class to be observed when the API documentation for my actual resource class is generated.

**Comment by okigan** [comment]
@fehguy @sverhagen dont think this works, @Api attribute now marked as @Inherited, but @ApiOperation, @ApiResponses are not, so methods do not show up

**Comment by webron** [comment]
@okigan - this is a bug in the current version. Feel free to open a new issue about it.

**Comment by okigan** [comment]
@webron opened  #1072
