### ISSUE TITLE
exampleSetFlag

### ISSUE THREAD

**Issue by mebigfatguy** [swagger-api/swagger-core#4019]
I've updated open swagger versions lately (now using 2.1.10), now i'm seeing lots of these errors

Structural error at components.schemas.AddAnnotationRequest.properties.pageNumber
should NOT have additional properties
additionalProperty: exampleSetFlag
Jump to line 490

Sorry i'm a noob, can anyone tell me what i should do here? I tried removing all the 

example = "..."

annotation properties, but that didn't seem to do anything.

**Comment by frantuma** [comment]
please see [this comment](https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287) about using the correctly configured object mapper.

closing ticket, please reopen if you're still experiencing issues

**Comment by alebastrov** [comment]
also you may wait till https://github.com/swagger-api/swagger-core/issues/4381 is resolved
