### ISSUE TITLE
Examples showing escape characters "\"

### ISSUE THREAD

**Issue by s-h-xsb** [swagger-api/swagger-core#4033]
I've been getting some strange behavior while defining examples. I've defined an example using annotations as follows 
```
@Operation(
            responses = {
                    @ApiResponse(responseCode = "400", description = "Invalid request", content = @Content(
                            schema = @Schema(implementation = FieldViolations.class),
                            examples = {
                                    @ExampleObject(
                                            name = "Bad input",
                                            value = EXAMPLE_VALUE
                                    )
                            }
                    )),
            }
    )
```
With `EXAMPLE_VALUE` being defined as
```
public static final String EXAMPLE_VALUE =
            "{\n" +
            "  \"priority\": \"low\"\n" +
            "}";
```
I would expect that the example output would look something like this
```
examples:
  Bad input:
    description: Bad input
    value: "{
                "priority": "low",
            }"
``` 
Instead, this is how it is defined
```
examples:
  Bad input:
    description: Bad input
    value: "{\n  \"priority\": \"low\"\n}"
```
I am using the swagger-maven-plugin version 2.1.11 to generate definition files and have the plugin defined in the POM as 
```
<plugin>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-maven-plugin</artifactId>
  <version>2.1.11</version>
  <configuration>
      <outputFileName>swagger</outputFileName>
      <outputPath>${project.build.directory}/${project.name}-${project.version}</outputPath>
      <outputFormat>JSONANDYAML</outputFormat>
      <prettyPrint>TRUE</prettyPrint>
      <configurationFilePath>${project.basedir}/src/main/resources/swagger-config.yaml</configurationFilePath>
      <alwaysResolveAppPath>true</alwaysResolveAppPath>
      <sortOutput>true</sortOutput>
  </configuration>
  <executions>
      <execution>
          <phase>compile</phase>
          <goals>
              <goal>resolve</goal>
          </goals>
      </execution>
  </executions>
</plugin>
```

Are the escape characters being in the examples intended? I tried rendering the definition file using Swagger-UI and they don't seem to handle the "\\" characters either. I'm wondering if this is intended or if there is a workaround for this.

**Comment by Great-Fred** [comment]
Hello,

So, what was the answer to this request ?

Thank you :).

**Comment by LeyDece** [comment]
The ExampleObject is taking a inline representation of a json string, so you don't need to put the newline character "\n" in it
The correct answer would be : "{" +
                "\"priority\":\"low\"" +
                "}"

**Comment by Great-Fred** [comment]
> The ExampleObject is taking an inline representation of a json string, so you don't need to put the newline character "\n" in it The correct answer would be : "{" + ""priority":"low"" + "}"

Thank you for the answer.
And sorry for taking so long to respond.

But, how do I escape the double quotes '"' in my JSON example ?
