### ISSUE TITLE
Type mismatch when using custom serializer

### ISSUE THREAD

**Issue by elDaniello** [swagger-api/swagger-core#4039]
I have 3rd party pojo that I'd like to deserialize and serialize using my own Jackson ObjectMapper, but Swagger seems to be not aware of that. Therefore generated examples and models at SwaggerUI are incorrect. Example class:
```
public thirdPartyClass() {
   private long foo;
   public long getFoo(){...};
}
```
then I register Jackson serializers using Mixin or SimpleModule, that I can treat `foo` as String from web, and
```
{
thirdPartyClass: {
    foo: "123" }
} 
```
is a valid JSON that I can get and pass to my Rest services, but Swagger keeps generating 
```
{
 thirdPartyClass: { 
    foo: 123 }
} 
```
I've already tried to pass my ObjectMapper to Swagger by setting mixins or modules on `io.swagger.util.Json.mapper()` or pass by `ModelConverters.getInstance().addConverter(new ModelResolver(myObjectMapper));` but none of these worked for me. 
I am using Apache CXF with Swagger2Feature

**Comment by frantuma** [comment]
probably the easiest way would be to annotate your member, if I get your scenario correctly:

```
public thirdPartyClass() {
   private long foo;
   @Schema (type = "string")	
   public long getFoo(){...};
}
```

Alternatively you might add your specific mixin to the ObjectMapper used by Swagger, by providing an `ObjectMapperProcessor` implementation to [Configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties)

Please close ticket if this answers your question
