### ISSUE TITLE
Check value of @JsonIgnore in ModelResolver

### ISSUE THREAD

**Issue by cpene1** [swagger-api/swagger-core#4059]
In ModelResolver there is a check for @JsonIgnore annotation, but the value is ignored:

https://github.com/swagger-api/swagger-core/blob/2f81363c21ad13d5726a07c83af8a6cd8aa99918/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L995-L997

However I think there should be an extra check on the value, since it can be annotated with @JsonIgnore(false). This can happen for example when you want to Override a @JsonIgnore annotation from a parent class. (I tested this locally and it gives the expected result)

So instead of returning true immediately, I would continue if the value is false.

**Comment by madeleine-a** [comment]
We also have this same issue I should say, and would be very happy if this could be fixed in next release.

**Comment by madeleine-a** [comment]
Hi @frantuma This one didn't go into release 2.1.13. Why not? Do you need anything from me?

**Comment by frantuma** [comment]
fixed in https://github.com/swagger-api/swagger-core/pull/4157
