### ISSUE TITLE
Update classgraph dependency

### ISSUE THREAD

**Issue by mschechter-bellese** [swagger-api/swagger-core#4104]
The `classgraph` dependency update in 2.1.12 is [labeled by that team](https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.117) as "Do not use". Please update to a more recent version.

I have found that it causes issues with the Java Security Manager. Updating to latest (currently 4.8.138) explicitly to override the dependency included with the `swagger-integration` JAR resolves the issue for me.

Thanks!

**Comment by frantuma** [comment]
classgraph updated to 4.8.138 in https://github.com/swagger-api/swagger-core/pull/4117

**Comment by mschechter-bellese** [comment]
Thanks! Any idea when this change will be released?

**Comment by frantuma** [comment]
This is already released in [2.1.13](https://github.com/swagger-api/swagger-core/releases/tag/v2.1.13)

**Comment by mschechter-bellese** [comment]
Thanks! Updating now!
