### ISSUE TITLE
BeanConfig needs some examples without Spring

### ISSUE THREAD

**Issue by rage-shadowman** [swagger-api/swagger-core#412]
BeanConfig seems to be touted as the answer to our configuration problems, allowing scanning of packages for annotated classes (see issues #173, #174 and #175).

It would be very helpful if we had some examples of how to use it. But the only examples I could find were using Spring. Please create some generic examples.

I've tried just creating a new one in the PostConstruct of a Singleton/Startup bean, but none of my resources are found, so I must be doing something wrong.

I initialize my BeanConfig like this:

``` Java
      BeanConfig beanConfig = new BeanConfig();
      beanConfig.setVersion( "1.0" );
      beanConfig.setScan( true );
      beanConfig.setResourcePackage( MyResource.class.getPackage().getName() );
      beanConfig.setBasePath( "http://localhost:9080/v1/api" );
      beanConfig.setDescription( "My RESTful resources" );
      beanConfig.setTitle( "My RESTful API" );
```

All I get on localhost:9080/v1/api/api-docs is this:

``` JSON
{"apiVersion":"1.0","swaggerVersion":"1.2"}
```

I don't get anything from MyResource (which has Api annotation on the class and ApiOperation annotation on the GET resource).

**Comment by danielflower** [comment]
I spent ages trying to bypass BeanConfig, classpath scanning, reflection, Spring, XML and anything that wasn't plain java specifying what to configure. [The result is here](http://danielflower.github.io/2016/04/01/Swagger-with-embedded-jetty-without-magic.html) in case anyone else is interested.
