### ISSUE TITLE
Bug when determining whether a property is required/mandatory

### ISSUE THREAD

**Issue by evantoli** [swagger-api/swagger-core#4143]
Do not mark a property as required if it has been annotated with both `@Null` and any of `@NotNull`, `@NotEmpty` and `@NotBlank`.

We often use validation groups to constrain whether a property is required or not for certain scenarios. 

For example, when a client must supply some value on create but is not permitted to change that value later on update.

For example we have properties defined like:
```java
  @Null(
      groups = GroupA.class,
      message = "Must not be provided in scenario A")
  @NotBlank(
      groups = GroupB.class,
      message = "Must be provided in scenario B")
  @Schema(
      description = """
          Some description of this property.
          
          Notes:
          
          - Must not be provided in scenario A
          - Must be provided in scenario B""",
      required = false)
  private String someProperty;
```

Currently, the SpringDoc tools are showing properties annotated like this to be required in the OpenAPI specs.

**Comment by evantoli** [comment]
Sorry – reported to wrong project

**Comment by T3rm1** [comment]
@evantoli Actually it is the correct project and it's still an issue. Swagger checks for certain NotNull/Blank/Empty annotations and if found marks the property as required regardless of the groups attribute.

https://github.com/swagger-api/swagger-core/blob/e8bb5950f848629423180d1fe2b932aaeff61e99/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L1564-L1571

In my opinion a property should remain optional if the groups attribute of the validation annotation is set.
Could you reopen the issue?
