### ISSUE TITLE
Play2/scala: A property named "is_persistent" gets shortened in the json to "_persistent"

### ISSUE THREAD

**Issue by kieranbenton** [swagger-api/swagger-core#415]
As the subject line says - other properties that contain _'s work correctly?

**Comment by fehguy** [comment]
Looks like this is an issue with both the internal (1.3.x) introspection and jackson as well (1.5.x).  Since the focus is on 1.5.x right now, I'm looking into a solution.

The Jackson `BeanDescription` method `findProperties()` is taking public property names like such:

`is_persistent`
`gettersAndHaters`

and mangling them to `_persistent` and `tersAndHaters`

I could use some help from @cowtowncoder on this one:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java#L172

```java
    for (BeanPropertyDefinition propDef : beanDesc.findProperties()) {
      Property property = null;
      String propName = propDef.getName();
```

Where the properties in this test class:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/models/ModelPropertyName.java

```java
public class ModelPropertyName {
  public boolean is_persistent() { return true; }
  public String isometric() { return null; }
  public String gettersAndHaters() { return null; }
}
```

emerge mangled

**Comment by cowtowncoder** [comment]
Right: `isXxx` methods are auto-detected if enabled by visibility (separately controlled as "is-getters", distinct from "regular" getters) AND return type is `boolean` or `Boolean`.
If detected, name mangling is identical to `get` methods.

Jackson 2.5 has a new `MapperFeature`, `USE_STD_BEAN_NAMING`: http://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/MapperFeature.html#USE_STD_BEAN_NAMING
which can be enabled to change it slightly (earlier `getURL` results in `Url`; with STD_BEAN_NAMING_ENABLED, remains `URL`), but I don't think it'd have effect here.

If the goal is NOT to detect these methods, it is easy enough to change by changing visibility levels.
One way is with `@JsonAutoDetect`; another with `ObjectMapper.setVisibility()`, which can either:

* Change level for specific kind of accessor (setter, getter, field, is-getter, constructor), or
* Use a fully custom `VisibilityChecker`

There is no simple overridability wrt name mangling (to perhaps avoid "is_persistent", when naming scheme would expect camel-case), although it might be possible to find overrides that work there.

So the question is just what is the desired behavior.

**Comment by fehguy** [comment]
Thanks, any way to detect as "getXxx" as a getter and not treat "getxxx" as a getter?  Likewise "isXxx" is a getter but "isxxx" or "is_xxx" is not

**Comment by fehguy** [comment]
@kieranbenton @mkantor I've addressed this in 1.3.13-SNAPSHOT.  I'm keeping this open so it can be tracked for 1.5.x

**Comment by fehguy** [comment]
It's a hack but it works:

https://github.com/swagger-api/swagger-core/commit/d183d8cd0f735fc18f5a50dcd52e2076da69b5df

Required `get` to be followed by an uppercase or uses original field name.  Same behavior for `is`.

**Comment by webron** [comment]
**Applies to https://github.com/swagger-api/swagger-core/milestones/v1.5.0-M1 as well.**

**Comment by dmn1899** [comment]
Hi guys
your decision is not clear correct
there are correct getters and setters with lower case after 'get', for example for property 'aName' getter will be named 'getaName'. intellij idea generates it and considers it is valid

your check
`!Character.isUpperCase(altName.charAt(offset)`
should replace with
`!Character.isUpperCase(offset) && !Character.isLowerCase(offset)`

special simbols ('_' for example) is not upper or lower case

best regards, hope you will fix it

**Comment by webron** [comment]
@dmn1899 commenting on an issue that was closed over two years ago is not the way to do it. If you experience an issue with the *latest* version, consider submitting a new ticket with the details.
