### ISSUE TITLE
Play2/scala: @ApiModelProperty doesn’t interpret Scala Option[] properties correctly

### ISSUE THREAD

**Issue by kieranbenton** [swagger-api/swagger-core#416]
Worse, trying to use the annotation's `dataType` property won't let you override the autogenerated `Object` value.

**Comment by ctoomey** [comment]
Found this issue after running into the problem with 1.3.12. I found that for parameters of type ```Option[T]```, ```@ApiModelProperty``` requires using ```dataType="T"```, i.e., it doesn't automatically extract the type parameter for Options. Reading through above I didn't realize I'd still need to manually specify ```dataType``` so thought I'd document it for others.
