### ISSUE TITLE
How To Show The Description Field Of @Schemas witch has a same "ref" field

### ISSUE THREAD

**Issue by Sahalaqj** [swagger-api/swagger-core#4171]
![image](https://user-images.githubusercontent.com/32122004/165875728-5d93e543-fbeb-4e88-9e82-208bcddef9cf.png)
![image](https://user-images.githubusercontent.com/32122004/165875887-c960d835-5344-4c65-8080-ed5c8e422ed2.png)

Hey! I have a question and hope someone can help!
When I user more than one @Schema with same "ref" field ,how can I show the description.
Thanks for any answers!

**Comment by robin-xyzt-ai** [comment]
Have you ever found a solution for this ? I'm bumping into the same problem.

**Comment by Sahalaqj** [comment]
> Have you ever found a solution for this ? I'm bumping into the same problem.

No solution!I think it's a bug or a scene has not been considered

**Comment by frantuma** [comment]
What you are trying to achieve is something not supported by OAS 2.0 (swagger) or 3.0 and JSON Schema Draft 4: in these versions a schema declaring a `$ref` has [all other fields ignored](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#fixed-fields-19).

Siblings alongside a defined `$ref` are part of OAS 3.1, and support for 3.1 is on its way in Swagger Core, but not yet finalized.

**Comment by Sahalaqj** [comment]
@robin-xyzt-ai 
Here's the reply, hope help u!

> What you are trying to achieve is something not supported by OAS 2.0 (swagger) or 3.0 and JSON Schema Draft 4: in these versions a schema declaring a `$ref` has [all other fields ignored](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#fixed-fields-19).
> 
> Siblings alongside a defined `$ref` are part of OAS 3.1, and support for 3.1 is on its way in Swagger Core, but not yet finalized.
