### ISSUE TITLE
Swagger 3 OAS: Objects as query params don't show up as query param

### ISSUE THREAD

**Issue by Frantch** [swagger-api/swagger-core#4177]
I have a simple SpringMVC Controller which instead of using the usual `@RequestParam` annotation to describe a params I use instead an Object that can be reused in other controllers because it has many common fields (like limit, offset etc..)

```
public String getAllUsers(@Valid GetAllUserRequest request)
```            
`GetAllUserRequest` is a simple POJO with filters (which are all query params)

```
public class GetAllUserRequest extends GenericParams {
     [...]
    @Parameter(description = "Username", required = false)
    private String username;
    [...]
}
```

```
public class GenericParams {
    [...]
    @Parameter(description = "Limit", required = false)
    protected Integer limit = 250;
    [...]
}
```

The generated swagger definition  looks like this
```
  "/my-path": {
      "get": {
        "parameters": [
          {
            "name": "getAllUsers",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/GetAllUserRequest"
            }
          }
        ],
```    

```
 "GetAllUserRequest": {
        "type": "object",
        "properties": {
          "limit": {
            "type": "integer",
            "format": "int32"
          },
```

And Swagger-UI displays this has a simple input field like it was a payload body with the whole json object which is.. quite inconvenient

Is it possible to somehow instruct Swagger to build the usual Query Param fields instead ?

**Comment by Frantch** [comment]
For people ending up here, the magic annotation is `@ParameterObject` that needs to be added before the DTO GetAllUserRequest in the controller

**Comment by tdwu** [comment]
Why can't swagger3 have the same behavior as swagger2 in this feature?
