### ISSUE TITLE
Header annotation doesn't fully support OAS 3.0

### ISSUE THREAD

**Issue by christophejan** [swagger-api/swagger-core#4196]
Currently, all  3.x.x versions of OpenAPI Specification define [Header object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#headerObject) as :

> The Header Object follows the structure of the **Parameter Object** with the following changes:
> 
> 1. `name` MUST NOT be specified, it is given in the corresponding `headers` map.
> 1. `in` MUST NOT be specified, it is implicitly in `header`.
> 1. All traits that are affected by the location MUST be applicable to a location of `header` (for example, [`style`](#parameterStyle)).

But current swagger-core [Header annotation](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/headers/Header.java) seems to have a lot of missing attributes when I compare it to [Parameter annotation](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java) :
- [allowEmptyValue](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L83)
- [style](https://github.com/swagger-api/swagger-core/blob/2e98a903d841ae7a7afffe0b76ae34d5c4c4dc55/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L90)
- [explode](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L97)
- [allowReserved](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L104)
- [array](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L118)
- [content](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java#L125)

I think all the matching [Parameter object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterObject) fields **can't be defined** currently on response header through swagger annotations, but **should**.

**Comment by christophejan** [comment]
- Note that bringing [Header annotation](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/headers/Header.java) and it's processing closer to the [Parameter annotation](https://github.com/swagger-api/swagger-core/blob/v2.2.0/modules/swagger-annotations/src/main/java/io/swagger/v3/oas/annotations/Parameter.java) could solve #2965

**Comment by micryc** [comment]
Due to [openapi spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterObject) there is no reason to add most of mentioned fields:

allowEmptyValue – valid only for query parameters

style – ‘header’ style is always set to simple, we don’t need that annotation then

allowReserved – this property only applies to parameters with “in” value of “query”, so it’s also not applicable as it’s header

We decided to take a deeper look on other missing fields like: explode, array, hidden, example, examples.

These were added by https://github.com/swagger-api/swagger-core/pull/4608
