### ISSUE TITLE
java.util.Date property type should be configurable

### ISSUE THREAD

**Issue by rage-shadowman** [swagger-api/swagger-core#420]
Date properties are always type "string" and this behavior is not modifiable (in spite of what is clamed on the wiki: https://github.com/wordnik/swagger-core/wiki/overriding-models).

The wiki entry claims that you can override models (specifically mentioning java.util.Date). While this works for most POJOs, this is not currently possible with java.util.Date. It will always be type "string" in the generated model definition. It looks like this is hard coded in the com.wordnik.swagger.model.SwaggerSerializers Scala file (and maybe elsewhere as well).

Our JSON converter (this is the RestEasy default) converts java.util.Date into a number (milliseconds past the epoch) rather than a string. So calling it a "string" is a lie.

I've tried annotating the getter with @ApiModelProperty setting dataType to "integer" or "java.util.Date" with no effect.

I've also tried creating an OverrideConverter for java.util.Date (as per the wiki entry) with no effect.

**Comment by LauraPinilla** [comment]
Hi rage-shadowman 
I have the same problem. Where I have to add this 
ModelConverters.add( SwaggerTypeMapOverrideConverter.RESTEASY_DATE_CONVERTER );
