### ISSUE TITLE
Bug in AccessMode.WRITE_ONLY?

### ISSUE THREAD

**Issue by klauss42** [swagger-api/swagger-core#4227]
After having trouble using WRITE_ONLY I looked in the code and saw the following in class [AnnotationsUtils](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java#L499):
```
// process after readOnly and writeOnly
if (schema.accessMode().equals(io.swagger.v3.oas.annotations.media.Schema.AccessMode.READ_ONLY)) {
    schemaObject.setReadOnly(true);
    schemaObject.setWriteOnly(null);
} else if (schema.accessMode().equals(io.swagger.v3.oas.annotations.media.Schema.AccessMode.WRITE_ONLY)) {
    schemaObject.setReadOnly(false);
    schemaObject.setWriteOnly(null);
```

To me the WRITE_ONLY handling looks obviously wrong, as it calls `schemaObject.setWriteOnly(null)`. Is this the correct and intended behaviour?

**Comment by frantuma** [comment]
fixed in https://github.com/swagger-api/swagger-core/pull/4441
