### ISSUE TITLE
Overridden models should expand child object models

### ISSUE THREAD

**Issue by rage-shadowman** [swagger-api/swagger-core#433]
When you override a model via the OverrideConverter:
```Java
OverrideConverter converter = new OverrideConverter();
String myModelClassname = "my.package.MyModel";
String myModelJson = "{\"id\": \"MyModel\", \"properties\": { \"child\": \"MyChildModel\" } }";
converter.add( myModelClassname, myModelJson );
ModelConverters.addConverter( converter, true );
```
...the child model never gets expanded. I've tried using the full path "my.package.MyChildModel" and lowercase "mychildmodel" but nothing seems to work. The only way I could get the child model to be included is to *not* override the parent model.

**Comment by fehguy** [comment]
Moving to M2

**Comment by fehguy** [comment]
This is almost impossible to support, but we can the facility to add models manually to the spec.

**Comment by rage-shadowman** [comment]
Why is this "almost impossible"? The data is clearly there, as adding 2 separate child elements (one with fully qualified package and classname, and one with simple classname) then 1 of them does get expanded.

**Comment by webron** [comment]
@rage-shadowman - sorry for the delay on this.

1.3.X is no longer under development. I don't know if you upgraded to 1.5.X yet and whether this issue is still relevant for you there. Can you please provide an update?
