### ISSUE TITLE
Feature Schema.RequiredMode.AUTO Should Consider Meta-Annotations

### ISSUE THREAD

**Issue by adase11** [swagger-api/swagger-core#4340]
With the changes to `@Schema` to deprecate the `required` attribute and replace it with `requiredMode` in #4286 the auto resolution accounts for annotations directly on the attribute. A nice enhancement would be to also consider any meta-annotations as well. For example:

I have the following custom annotation
```java
@Constraint(validatedBy = {})
@NotNull(message = "must be a valid verification code")
@Pattern(regexp = VERIFICATION_CODE_REGEX, message = "must be a valid verification code")
public @interface ValidVerificationCode {
...
}
```

It would be nice to have this auto resolved as not null as well by the Schema.RequiredMode.AUTO.

**Comment by kzander91** [comment]
All meta-annotations should be considered, not just to see if an attribute is required.

@adase11: Does Swagger generate a `pattern` restriction for you?

I have an annotation like this, but the generated Spec does not contain the regexp constraint.
```java
@Retention(RUNTIME)
@Constraint(validatedBy = {})
@Pattern(regexp = "^[A-Z\\d-]{1,32}/[A-Z\\d-]{4,20}$")
public @interface ValidUsername {
   ...
}
```

**Comment by adase11** [comment]
Agreed @kzander91 - I'm observing the same behavior you are.

**Comment by frantuma** [comment]
Swagger Core is relying (also) on underlying Jackson annotation processing, which supports meta annotations annotated with [`@JacksonAnnotationsInside`](https://cowtowncoder.medium.com/jackson-2-x-tips-annotation-bundles-d531c92d08b1).

The above examples would work if updated to:

```java
@Retention(RetentionPolicy.RUNTIME)
@JacksonAnnotationsInside
@Constraint(validatedBy = {})
@NotNull(message = "must be a valid verification code")
@Pattern(regexp = VERIFICATION_CODE_REGEX, message = "must be a valid verification code")
public @interface ValidVerificationCode {
...
}
```

and 

```java

@Retention(RetentionPolicy.RUNTIME)
@JacksonAnnotationsInside
@Constraint(validatedBy = {})
@Pattern(regexp = "^[A-Z\\d-]{1,32}/[A-Z\\d-]{4,20}$")
public @interface ValidUsername {
   ...
}
```

Closing ticket, please reopen if you're still experiencing issues

**Comment by kzander91** [comment]
This works, but is pretty unexpected... Adding a Jackson annotation to something that doesn't have anything to do with Jackson (from my application's point of view) is certainly an unsatisfying solution...

This also requires a compile-time dependency on `jackson-annotations`, which may not be pretty if a the custom annotations are defined in a separate module.
