### ISSUE TITLE
jakarta version of core claims wrong jakarta.validation as dependent package

### ISSUE THREAD

**Issue by juergen-albert** [swagger-api/swagger-core#4354]
The Manifest of io.swagger.v3.core states that it requires the package jakarta.validation.constraints with at least version 1.1 with a range that explicitly excludes 3.0 and above. The first jakarta version however is 3.0.

The Version jakarta Version is build using the transformer plugin together with bnd. Not sure where the issue ocures here, but maybe @bjhargrave can help here, as I have never used the transformer.

As a workaround, the following could help:
Put a bnd.bnd file next to the pom.xml of the jakarta core pom.xml with the follwing content:
```
Import-Package:\
     jakarta.validation.constraints;version="[3,4)",\
     *
```
This should cause bnd to overwrite the version requirement for you.

**Comment by frantuma** [comment]
This has been fixed in #4578 (release 2.2.20)
