### ISSUE TITLE
JSON output has tons of "exampleSetFlag: false" lines

### ISSUE THREAD

**Issue by rob-stoecklein** [swagger-api/swagger-core#4357]
When building an `OpenAPI` object, there are a number of places where we use the `Schema` class. When converting our `OpenAPI` object to a JSON string, there is an enormous number of `"exampleSetFlag": false` lines in the file.

Could we modify the code so that, when this field is not set, then it does not appear?

To do that, in `io.swagger.v3.oas.models.media.Schema`, line 71: `private boolean exampleSetFlag;`, could we change this from a primitive `boolean` to an object `Boolean`. Would that be possible?

I didn't make a pull request because, since we've just started using this library, I thought there might be something I'm missing. However, I'd be happy to make a PR if that would help.

Thanks!

**Comment by frantuma** [comment]
thanks for reporting this, please see [this comment](https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287) about using the correctly configured object mapper.

closing ticket, please reopen if you're still experiencing issues

**Comment by rob-stoecklein** [comment]
Hi Francesco, thanks for your quick response.

I checked out the discussion you linked to. The solution there appears to be "use the `Json` or `Yaml` class from `swagger-core`, which uses a custom `ObjectMapper` and a `SchemaMixin` class".

We are building an embedded OS running on a low resource single board computer. As such, we cannot add any unnecessary libraries, including `swagger-core`, which also depends on other libraries. `swagger-models` is exactly and only what we need.

It still seems, from my vantage point anyway, that changing `exampleSetFlag` from `boolean` to `Boolean` would easily solve this situation, and I'm guessing _without any ill effects to existing software_, especially since this is how all other fields in the `Schema` class work: if they are null, then they are left out of the JSON output.

Of course I could be wrong; I'm just trying to avoid having a custom branch of this code simply to redefine a single variable.

Thanks for your time and consideration.
-Rob

**Comment by frantuma** [comment]
Hi @rob-stoecklein ,

the change you suggest is probably not so easy to implement, mainly as it would break compatibility which is something we want to avoid. 

Depending on your environment - I understand it's a low-resources scenario, but not sure e.g. how are you (de)serializing , with which library, etc. - a possible way around would be to configure your serialization to discard `exampleSetFlag` field.

Again not sure about your serialization, for example a way of doing that with Jackson (in case you (can) have it in your classpath) is through MixIns adding a `@JsonIgnore`, with Gson it would involve adding a `ExclusionStrategy`

**Comment by alebastrov** [comment]
I found the solution for that
