### ISSUE TITLE
BaseOpenApiResource no longer available with Jakarta-EE

### ISSUE THREAD

**Issue by dafi** [swagger-api/swagger-core#4361]
I'm migrating my app from `javax` to `jakarta` EE and replaced my maven dependencies with 

```xml

    <properties>
        <swagger.version>2.2.8</swagger.version>
    </properties>

...
...
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
            <version>${swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-integration-jakarta</artifactId>
            <version>${swagger.version}</version>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2-jakarta</artifactId>
            <version>${swagger.version}</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2-servlet-initializer-v2-jakarta</artifactId>
            <version>${swagger.version}</version>
        </dependency>

```

but the class `io.swagger.v3.jaxrs2.integration.resources.BaseOpenApiResource` is no longer available, documentation says just need to append `jakarta` to artifactId but this doesn't work

Any hints?

**Comment by frantuma** [comment]
The class is present in the mentioned version, see https://repo1.maven.org/maven2/io/swagger/core/v3/swagger-jaxrs2-jakarta/2.2.8/, can you clarify what is your error?

**Comment by dafi** [comment]
I've created a test case available here https://github.com/unipa/SwaggerBaseOpenApiResource, after cloning just run `mvn package`

The compilation fails

`[ERROR] /Volumes/Devel/trash/SwaggerBaseOpenApiResource/src/main/java/com/example/demo/openapi/ApiListOpenApiResource.java:[3,50] package io.swagger.v3.jaxrs2.integration.resources does not exist`

the test case is simplified to reproduce the compile error and the code does nothing

Tested on my production machine with Maven 3.8.7 JDK 17.0.6

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)


On a clean machine with Maven 3.9.0 JDK 17.0.5

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)

**Comment by frantuma** [comment]
In your test case you'are declaring dep with scope `runtime` (not available at compile time). Removing the scope fixes the issue (you should also throw or catch exception in your method)

**Comment by dafi** [comment]
Please apologize me for wasting your time, you are right now everything works fine
