### ISSUE TITLE
exampleSetFlag is still presented in JSON

### ISSUE THREAD

**Issue by alebastrov** [swagger-api/swagger-core#4381]
I found the reason for that in class
**io.swagger.v3.oas.models.media.MediaType** 
That class has internal boolean field exampleSetFlag which is leaking to JSON schema definition.
 I did 2 experiments:
  - renamed the field (the json file changed and started containing renamed field)
  - added @JsonIgnore on that field ( the json file changed and irritating field disappeared)
  
  So I would suggest adding @JsonIgnore annotation on this field like below
~~~
public class MediaType {
...
  @JsonIgnore
    private boolean exampleSetFlag;
...
}
~~~

**Comment by frantuma** [comment]
`exampleSetFlag` field is correctly ignored in serialization when using correctly configured object mapper, please see [this comment](https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287) about using the correctly configured object mapper.

closing ticket, please reopen if you're still experiencing issues
