### ISSUE TITLE
Bug: swagger-core ignore description field for Reference Object

### ISSUE THREAD

**Issue by xiaoxiangmoe** [swagger-api/swagger-core#4393]
reproduction repo: https://github.com/xiaoxiangmoe/swagger-core-refs-description-is-ignored

[HelloWorldController.java](https://github.com/xiaoxiangmoe/swagger-core-refs-description-is-ignored/blob/78ee4ef33ff71fa322549f1cd42a1b55e3fc7b8e/src/main/java/com/example/demo/HelloWorldController.java#L35-L41)
```java
    @Schema(description = "Transaction")
    public class Transaction {
        @Schema(description = "trade number")
        @NotNull
        public long tradeNO;

        @Schema(description = "transaction initiator, payer")
        @NotNull
        public Account fromAccount;

        @Schema(description = "transaction receiver, payee")
        @NotNull
        public Account toAccount;
    }
```

Then it generate api docs in `/v3/api-docs`. I copy it to [`src/main/resources/static/current-api-docs.json`](https://github.com/xiaoxiangmoe/swagger-core-refs-description-is-ignored/blob/78ee4ef33ff71fa322549f1cd42a1b55e3fc7b8e/src/main/resources/static/current-api-docs.json#L67-L99) as follow:

```json
      "Transaction": {
        "type": "object",
        "properties": {
          "tradeNO": {
            "type": "integer",
            "description": "trade number",
            "format": "int64"
          },
          "fromAccount": {
            "$ref": "#/components/schemas/Account"
          },
          "toAccount": {
            "$ref": "#/components/schemas/Account"
          }
        },
        "description": "Account"
      }
```

But what I need is: [expected-api-docs.json](https://github.com/xiaoxiangmoe/swagger-core-refs-description-is-ignored/blob/78ee4ef33ff71fa322549f1cd42a1b55e3fc7b8e/src/main/resources/static/expected-api-docs.json#L67-L100)

```json
      "Transaction": {
        "type": "object",
        "properties": {
          "tradeNO": {
            "type": "integer",
            "description": "trade number",
            "format": "int64"
          },
          "fromAccount": {
            "$ref": "#/components/schemas/Account",
            "description": "transaction initiator, payer"
          },
          "toAccount": {
            "$ref": "#/components/schemas/Account",
            "description": "transaction receiver, payee"
          }
        },
        "description": "Account"
      }
```
`fromAccount` and `toAccount` should have `description` field.

**Comment by xiaoxiangmoe** [comment]
This should be supported in openapi 3.1.
But this library is not supported yet, I guess it will be supported in a few days.

**Comment by MABIY** [comment]
> 

Thank you

**Comment by xiaoxiangmoe** [comment]
@MABIY I found this is not supported. So I reopen this issue.

**Comment by xiaoxiangmoe** [comment]
It seems that this is the bug code


https://github.com/swagger-api/swagger-core/blob/d0d584dd4be18ced7ff1e71aa768be699e1a8d21/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SchemaSerializer.java#L44-L49

https://github.com/swagger-api/swagger-core/blob/d0d584dd4be18ced7ff1e71aa768be699e1a8d21/modules/swagger-core/src/main/java/io/swagger/v3/core/util/ModelDeserializer.java#L90-L92
