### ISSUE TITLE
OpenAPI 3.1 support:  Schema Objects that contain a $ref keyword.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [swagger-api/swagger-core#4398]
## Behaviour of OpenAPI 3.0.3
In OpenAPI 3.0.3. `$ref` keyword is not in allowed fields of [Schema Object](https://spec.openapis.org/oas/v3.0.3#schema-object).
The only way to use `$ref` is [Reference Object](https://spec.openapis.org/oas/v3.0.3#reference-object).

In OpenAPI 3.0.3. Reference Object cannot be extended with additional properties and any properties added SHALL be ignored.

So we have some logic like this:

https://github.com/swagger-api/swagger-core/blob/d0d584dd4be18ced7ff1e71aa768be699e1a8d21/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/SchemaSerializer.java#L44-L49

https://github.com/swagger-api/swagger-core/blob/d0d584dd4be18ced7ff1e71aa768be699e1a8d21/modules/swagger-core/src/main/java/io/swagger/v3/core/util/ModelDeserializer.java#L90-L92

If there exist a `$ref` field, all other fields **SHALL be ignored** in both serializer and deserializer.

---

## Behaviour of OpenAPI 3.1.0

In OpenAPI 3.1.0. [Schema Object](https://spec.openapis.org/oas/v3.1.0#schemaObject) is a superset of the [JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00). And it contains [`$ref` keyword](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-8.2.3.1).

In section [4.8.23 Reference Object](https://spec.openapis.org/oas/v3.1.0#reference-object), it write
> Note that this restriction on additional properties is a difference between Reference Objects and [Schema Objects](https://spec.openapis.org/oas/v3.1.0#schemaObject) that contain a $ref keyword.

So such schema is a valid schema in OpenAPI 3.1.0, but not valid schema in OpenAPI 3.0.3.

```json
{
    "openapi": "3.1.0",
    "info": {
        "title": "OpenAPI definition",
        "version": "v0"
    },
    "components": {
        "schemas": { 
            "SomeViewObject": {
                "properties": {
                    "user": {
                        "$ref": "#/components/schemas/User",
                        "description": "the user"
                    },
                    "userDeprecated": {
                        "$ref": "#/components/schemas/User",
                        "description": "deprecated field",
                        "deprecated": true
                    }
                },
                "required": [
                    "user",
                    "userDeprecated"
                ]
            },
            "User": {
                "description": "User class",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "user's name"
                    }
                },
                "required": [
                    "name"
                ]
            }
        }
    }
}
```

in OpenAPI 3.1.0. If there exist a `$ref` field, all other fields **SHOULD NOT be ignored** in both serializer and deserializer.

------

## Feature Request

Add support for  Schema Objects that contain a $ref keyword. And let such example runs well.

```java
package com.example.swagger_java_demo.controller;


import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import static io.swagger.v3.oas.annotations.media.Schema.RequiredMode.REQUIRED;

@RestController
public class HelloWorldController {
    @Operation(summary = "getSomeViewObject")
    @GetMapping("/foobar")
    public SomeViewObject getSomeViewObject() {
        return null;
    }

    public static class SomeViewObject {
        @Schema(description = "the user", requiredMode = REQUIRED)
        public User user;

        @Schema(description = "deprecated field", requiredMode = REQUIRED, deprecated = true)
        public User userDeprecated;
    }

    @Schema(description = "User class")
    public static class User {
        @Schema(description = "user's name", requiredMode = REQUIRED)
        public String name;
    }
}
```

**Comment by xiaoxiangmoe** [comment]
@frantuma @HugoMario

**Comment by frantuma** [comment]
OpenAPI 3.1 support has been added since version 2.2.0

Add an [openapi31 = true](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties) configuration property In order to achieve the behavior mentioned in example above.

Please see [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---OpenAPI-3.1) for details.
