### ISSUE TITLE
Can't generate multiple openapi with different configurations

### ISSUE THREAD

**Issue by qianlong** [swagger-api/swagger-core#4399]
I'm trying to generate openapi files with swagger-maven-plugin (version 2.2.9), the purpose is to split api's into different openapi files because in my application there is too much APIs and that slows down loading of webpage of swagger UI.
The issue is, even though I set different openapi configuration in different executions, it is always the first one which is picked and used to generate the file.
Here is my maven configuration:
```xml
<plugin>
    <groupId>io.swagger.core.v3</groupId>
     <artifactId>swagger-maven-plugin</artifactId>
     <executions>
          <execution>
          <id>openapi1</id>
          <phase>compile</phase>
          <goals>
              <goal>resolve</goal>
          </goals>
          <configuration>
          <outputFileName>openapi1</outputFileName>
          <configurationFilePath>${project.build.directory}/classes/openapi-configuration1.json</configurationFilePath>
          </configuration>
        </execution>
        <execution>
               <id>openapi2</id>
               <phase>compile</phase>
               <goals>
                   <goal>resolve</goal>
               </goals>
               <configuration>
                   <outputFileName>openapi2</outputFileName>
                   <configurationFilePath>${project.build.directory}/classes/openapi-configuration2.json</configurationFilePath>
               </configuration>
        </execution>
    </executions>
</plugin>
```
I've also tried with different `openapiFilePath`, still no luck.

Is this a bug? or I'm doing wrong?

**Comment by frantuma** [comment]
Please see one of these comments: https://github.com/swagger-api/swagger-core/issues/4300#issuecomment-1376278975, https://github.com/swagger-api/swagger-core/issues/3028#issuecomment-442923415, https://github.com/swagger-api/swagger-core/issues/3179#issuecomment-484365903

Closing ticket, please reopen if still experiencing issues
