### ISSUE TITLE
Enhancement: @JsonIgnoreProperties( allowGetters = true) properties are ignored when they shouldn't be.

### ISSUE THREAD

**Issue by HaruhiSuzumiyah** [swagger-api/swagger-core#4416]
As previously stated in https://github.com/swagger-api/swagger-core/issues/3410 allow getters should let the properties through. 

From https://github.com/swagger-api/swagger-core/pull/3649 and https://github.com/swagger-api/swagger-core/commit/8e4b8090e5a56fca364f3e2461a289799de0c82a we can see that the current behavior is to ignore everything. 

Instead the behavior should be to ignore properties where allowGetters is not true.

**Comment by frantuma** [comment]
addressed in https://github.com/swagger-api/swagger-core/pull/4418
