### ISSUE TITLE
SwaggerAnnotationIntrospector class is still using javax.bind, should be jakarta.bind

### ISSUE THREAD

**Issue by ajschutte** [swagger-api/swagger-core#4430]
The class above is causing issues at runtime, since v4 of the Jakarta XML Bind API doesn't have the javax.bind classes anymore, they've all changed to jakarta.bind. Apologies if this has already been reported and being fixed.

**Comment by frantuma** [comment]
Jakarta namespace is supported by dedicated artifacts, please see [wiki](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started#note-jakarta-namespace-support-since-version-217)
