### ISSUE TITLE
swagger-gradle-plugin 2.2.13 breaks correct schema generation for "cyclic" classes

### ISSUE THREAD

**Issue by Xnyle** [swagger-api/swagger-core#4446]
Given the following datamodel:
```
class MyPojo{
  private List<String> someStrings
  private List<MyPojo> morePojos;
  ... getter/setter...
}
```
Version 2.2.12 of the gradle plugin correctly generates an openAPI json during resolve which contains morePojos.
In version 2.2.13 morePojos is simply missing, while someStrings and all other fields are still there.

resolve looks like this:

```
resolve {
	outputFileName = 'openapi'
	outputFormat = 'JSON'
	prettyPrint = 'TRUE'
	outputDir = file(project.buildDir.canonicalPath+"/resources"+'/main'+'/swagger')
	openApiFile = new File(project.projectDir.canonicalPath+'/src/main/resources'+'/openapi-config.json')
	classpath = sourceSets.main.compileClasspath
	buildClasspath = sourceSets.main.compileClasspath
}
```
buildClasspath needed for JakartaEE
Nothing special in openapi-config.json.

**Comment by KevinCranmer** [comment]
I am having the same issue going to v2.2.13 of the maven plugin. A class `Address` has a cyclic field declared as follows that is no longer generated in the schema:
`@Valid List<Extension> extension;`
Strangely, this only happens on one of our applications, and only the first schema object in the definition. Other objects with an `extension` are generating schema fine. Even the `Extension` class - which has a List of `Extension`'s - generates all schema fields.

**Comment by frantuma** [comment]
We are not able to reproduce, please provide a test case reproducing the issue
