### ISSUE TITLE
skipResolveAppPath sets the wrong property in SwaggerConfiguration.java

### ISSUE THREAD

**Issue by IvanZhivkov-sumup** [swagger-api/swagger-core#4458]
I found a bug:
In the SwaggerConfiguration.java there is a method skipResolveAppPath which in turn calls setAlwaysResolveAppPath whereas it should be calling setSkipResolveAppPath.

[Permalink to method](https://github.com/swagger-api/swagger-core/blob/f050d0a63c5992c991ad066b15867c32ae6ded1a/modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/SwaggerConfiguration.java#L310)

So now when the method(skipResolveAppPath) is called with value false (meaning do not skip it) like `skipResolveAppPath(false)` it calls `setAlwaysResolveAppPath(false)` (meaning it will not resolve the app path).
To make things a bit worse, this method is called from some of the modules ([example](https://github.com/swagger-api/swagger-core/blob/f050d0a63c5992c991ad066b15867c32ae6ded1a/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/integration/SwaggerLoader.java#L285)). Current workaround is to tell it to skip it in order for it not to skip it.

**Comment by frantuma** [comment]
thanks for reporting this! fixed in #4459
