### ISSUE TITLE
Add support for JAX-RS @BeanParam

### ISSUE THREAD

**Issue by joscarsson** [swagger-api/swagger-core#446]
Would it be possible to add support for the @BeanParam (https://jax-rs-spec.java.net/nonav/2.0/apidocs/javax/ws/rs/BeanParam.html) from JAX-RS? Same question as answered at http://stackoverflow.com/questions/19913046/does-swagger-support-the-jax-rs-beanparam-annotation, but didn't find an issue for it here.

**Comment by swarupe04** [comment]
Has anyone tried using Swagger Core 1.5.x and Swagger UI 2.0 using Jersey2 with no web.xml

It doesn't seem to recognize API annotations within BeanParam object and also the path param pattern doesn't get replaced such as /v1/report/{report_type:[aA-zZ]+} ..when executed on UI it uses the pattern as is

**Comment by fehguy** [comment]
Hi @swarupe04 It is definitely supported.  Please take a look at this sample:

https://github.com/swagger-api/swagger-core/tree/develop_2.0/samples/java-jaxrs-no-webxml

It is a jaxrs 1.x sample but the spirit is the same.  All configuration for swagger is done in the Bootstrap.java.

**Comment by swarupe04** [comment]
Hi Tony,

It seems to be the UI side, that doesn't seem to support it. Since I can
see api documentation in the swagger.json.

Since, by using swagger 2.0 forma, we're forced to move to the new UI.
Also,  I noticed that new UI 2.0 doesn't have the "raw" link anymore.

Is master the latest for UI work, or do u think I should instead using
develop_2.0 for swagger ui too, to get the latest UI modules.

Thanks

**Comment by fehguy** [comment]
Master should be fine. Can you share the bean property?  Email is fine if its private

**Comment by swarupe04** [comment]
Please can you provide the email id to send to.

Thanks,

Swarup

**Comment by fehguy** [comment]
Tony@swagger.io

**Comment by swarupe04** [comment]
sent to your gmail..please let me know if you need more info..

also wanted to mention about the swagger.json out too

base class to support all types of Report Requests:
{

   - required:
   [
      - "active_campaigns",
      - "date_range",
      - "report_type",
      - "time_unit",
      - "view_level"
      ],


for bean class

@ApiModel(value = "base class to support all types of Report Requests")
public class ReportRequest {

shouldn't it using the class name instead?
