### ISSUE TITLE
after using jsonstringenumconverter saved enum values in database base coverts back to integer values when converts from blob to text in angular

### ISSUE THREAD

**Issue by SherdilPro** [swagger-api/swagger-core#4472]
this.gatepass.docType == GatePassType.Inward
while saving 

this.gatepass.docType value is Inward

on edit it becomes 1

on server side every thing working fine.

I found this conversion wrong when converting api httpresponse body blog to text

**Comment by frantuma** [comment]
Closing ticket as it seems not to be related to swagger-core project. Please reopen with full details in case it indeed is related
