### ISSUE TITLE
Upgrading to latest version of "Eclipse Transformer" as solution to missing `jakarta.validation.constraints` entry in `jakarta-versions.properties`

### ISSUE THREAD

**Issue by ideas-into-software** [swagger-api/swagger-core#4485]
Above mentioned missing entry for `jakarta.validation.constraints` in `jakarta-versions.properties` is root cause for problem described in issue https://github.com/swagger-api/swagger-core/issues/4354, opened close to 9 months ago. That is what I discovered when I was asked to fix this problem in a commercial project which was blocked due to this problem - i.e. transformed Swagger Jakarta EE 9 artifacts were using wrong `jakarta.validation.constraints` version, merged from original 'swagger' Java EE modules, making those impossible to use in OSGi environment.

This problem could not be fixed on Swagger project side – it needed to be addressed in "Eclipse Transformer" itself. That missing configuration for `jakarta.validation.constraints=[3.0,4.0)` was added in `jakarta-versions.properties` configuration file of transformer `0.2.0` (https://github.com/eclipse/transformer/releases/tag/0.2.0), transformer rebuild and resulting artifact used to rebuild (transform) https://github.com/swagger-api/swagger-core artifacts.

Because that problem still exists in the https://github.com/swagger-api/swagger-core project itself, we temporarily use those rebuilt (fixed) Swagger Jakarta EE9 artifacts in our commercial project.

https://github.com/swagger-api/swagger-core project is currently using old version of "Eclipse Transformer" (`org.eclipse.transformer:org.eclipse.transformer.cli:0.2.0`) - https://github.com/eclipse/transformer project itself is currently at version 0.5.0 (released) 0.6.0 (repository).

Back when `swagger-eclipse-transformer-maven-plugin` was added (https://github.com/swagger-api/swagger-core/pull/3889), as per `io.swagger.v3.oas.transformer.TransformMojo` Javadoc, it was "_Adapted from https://github.com/eclipse/transformer/blob/main/org.eclipse.transformer.maven not to add the transformed JAR as an attached artifact to the project._" and that it was "_To be replaced with Eclipse original Transformer plugin when/if optional attachment is supported._"

It looks like "Eclipse Transformer" (https://github.com/eclipse/transformer) already provides such optional attachment - i.e. `attach` configuration parameter is already present in `org.eclipse.transformer.maven.TransformerJarMojo` and documented in `maven-plugins/transformer-maven-plugin/README.md`. That version of "Eclipse Transformer" already contains `jakarta.validation.constraints` entry in its `jakarta-versions.properties` configuration file.

Are there any plans to upgrade to latest version of "Eclipse Transformer"? As it stands right now, due to https://github.com/swagger-api/swagger-core/issues/4354, Swagger Jakarta EE 9 artifacts cannot be used in OSGi environment (hence above mentioned fix was applied in our project).

**Comment by frantuma** [comment]
This has been fixed in #4578 (release 2.2.20)
