### ISSUE TITLE
Swagger parser ignores @Schema.description for reference objects 

### ISSUE THREAD

**Issue by woltariel** [swagger-api/swagger-core#4540]
When using descriptions @Schema.description for object types e.g.:
```
@field:Schema(
    description = "Total basket price",
    example = EXAMPLE_BASKET_PRICE,
)
val basketPrice: BasketPrice,
```

the generated spec completely ignores this description and example:

```
"basketPrice" : {
  "$ref" : "#/components/schemas/BasketPrice"
},
```

We are using  `swagger-core-2.2.18` and `swagger-parser-2.1.18` and the model resolver is configured to use open API 3.1. 
Considering the Open Api Spec 3.1 [allows descriptions for reference objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#reference-object) shouldn't these show up in the generated spec?

**Comment by frantuma** [comment]
@woltariel trasfered ticket to swagger-core as the described functionality is provided by Swagger Core, not Swagger Parser.

The reason of behaviour you are experiencing is the lack of the [Jackson Kotlin Module](https://github.com/FasterXML/jackson-module-kotlin) dependency and configuration; this module allows Jackson to fully introspect Kotlin classes/types, also covering your case.

You would need to add the following dependency:

```
implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.3")
```

and configure the object mapper in use (see also module home page for other ways to configure)

```kotlin

import com.fasterxml.jackson.module.kotlin.registerKotlinModule
...
private val context = ModelConverterContextImpl(ModelResolver(ObjectMapper().registerKotlinModule()).openapi31(true))
```


Closing ticket, please reopen if you are still experiencing issues
