### ISSUE TITLE
2.2.19 Some spurious System.err

### ISSUE THREAD

**Issue by cocorossello** [swagger-api/swagger-core#4547]
In this [commit](https://github.com/swagger-api/swagger-core/commit/699f70e0d8023d7c82fc25ac401cf1858a975dec) a trial System.err has been forgotten and should be removed

**Comment by Evenprime** [comment]
Any chance of this getting a release version soon? Maybe have a release just for that?

It's kind of annoying to have these additional error log lines in the latest version.

**Comment by frantuma** [comment]
included in latest 2.2.20
