### ISSUE TITLE
Missing endpoints in generated OpenAPI spec

### ISSUE THREAD

**Issue by nntzuekai** [swagger-api/swagger-core#4552]
I am trying Swagger Core on this REST API: [https://github.com/apilayer/restcountries/tree/master](url)

In the generated spec ([restcountries.json](https://github.com/swagger-api/swagger-core/files/13399368/restcountries.json)), I found these endpoints are missing: "POST /contribute", "POST /v1", "GET /v1", "POST /v2", and "GET /v2", which are defined in [https://github.com/apilayer/restcountries/blob/master/src/main/java/eu/fayder/restcountries/v2/rest/StripeRest.java](url), [https://github.com/apilayer/restcountries/blob/master/src/main/java/eu/fayder/restcountries/v1/rest/CountryRest.java](url), and [https://github.com/apilayer/restcountries/blob/master/src/main/java/eu/fayder/restcountries/v2/rest/CountryRest.java](url).

I added to the pom:

```
       <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2</artifactId>
            <version>2.2.7</version>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2-servlet-initializer-v2</artifactId>
        <version>2.2.7</version>
        </dependency> 
```

Can you check if this is a bug or me missing some configurations? Thank you!

**Comment by micryc** [comment]
Hi @nntzuekai could you share with us some more details about your project  (full project etc.) ? Unfortunately with resources you have already provided , it's hard to find out what went wrong.

**Comment by micryc** [comment]
It looks like swagger-core works properly in that case, after quick reproduction with [https://github.com/apilayer/restcountries/tree/master](https://github.com/swagger-api/swagger-core/issues/url) it generates spec with "missing" endpoints [openapi-restcountries.json](https://github.com/swagger-api/swagger-core/files/14007893/openapi-restcountries.json)
