### ISSUE TITLE
Generate undefined HEAD and OPTIONS for JAX-RS annotations [RestEasy (Wildfly) and Jersey]

### ISSUE THREAD

**Issue by deckrider** [swagger-api/swagger-core#4586]
JAX-RS implementations automatically generate HEAD and OPTIONS services when deployed into a JEE container.  For example...

```
@GET
@Path ("foo/bar")
public Response getBar()
```

...when deployed into a JEE container will automatically support HEAD and OPTIONS for the same

If there is no GET for a Path, only OPTIONS will be generated.

Therefore, I would like to request that when using the swagger-maven-plugin, if HEAD and/or OPTIONS were not already annotated for a Path, then HEAD and/or OPTIONS would be generated from the appropriate annotations that do exist and are output to the generated OpenAPI JSONANDYAML

**Comment by micryc** [comment]
Hi @deckrider Unfortunately having automatically generated HEAD/OPTIONS in OpenAPI JSON/YAML spec is not so common. We are not gonna change that, at least for now, but if you still want to achieve that I suggest you to use [filter](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters) instead. Here is a simple example which you can modify depending to your needs:

`public class AdditionalHttpMethodsFilter extends AbstractSpecFilter {

    @Override
    public Optional<PathItem> filterPathItem(PathItem pathItem, ApiDescription api, Map<String, List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
        Operation getOperation = pathItem.getGet();
        if (getOperation != null) {
            if (pathItem.getHead() == null) {
                Operation headOperation = new Operation();
                if (pathItem.getGet().getResponses() != null) {
                    headOperation.setResponses(getOperation.getResponses());

                }
                pathItem.setHead(headOperation);
            }
        }


        if (pathItem.getOptions() == null) {
            List<String> allowedMethods = new ArrayList<>();
            if (pathItem.getGet() != null) allowedMethods.add("GET");
            if (pathItem.getPost() != null) allowedMethods.add("POST");
            if (pathItem.getPut() != null) allowedMethods.add("PUT");
            if (pathItem.getDelete() != null) allowedMethods.add("DELETE");
            if (pathItem.getPatch() != null) allowedMethods.add("PATCH");
            if (pathItem.getHead() != null) allowedMethods.add("HEAD");
            if (pathItem.getOptions() != null) allowedMethods.add("OPTIONS");

            if (!allowedMethods.isEmpty()) {
                Operation optionsOperation = new Operation();
                String allowedMethodsString = String.join(",", allowedMethods);
                optionsOperation.addExtension("x-Allow-Methods", allowedMethodsString);
                pathItem.options(optionsOperation);

            }

        }
        return Optional.of(pathItem);
    }
}`
