### ISSUE TITLE
Schema objects not outputting type when used with OpenAPI 3.1

### ISSUE THREAD

**Issue by Yaytay** [swagger-api/swagger-core#4587]
When requesting openapi.json I'm getting this:
```JSON
  "components": {
    "schemas": {
      "AuthConfig": {
        "properties": {
          "name": {
            "type": "string"
          },
          "logo": {
            "type": "string"
          }
        }
      },
```

I'm expecting a type field under AuthConfig.

Putting this
```Java
logger.debug("{} {} ({} or {}): {}", schema.getClass(), schema.getName(), schema.getTypes(), schema.getType(), schema.getProperties() == null ? null : schema.getProperties().size());
```
in a ModelConverter outputs this:
```
class io.swagger.v3.oas.models.media.Schema AuthConfig (null or object): 2
```

I infer that types is null but type is set to "object".

Adding this:
```Java
schema.setTypes(ImmutableSet.builder().add("object").build());
```
 to the ModelConverter makes the output the desired:
```JSON
  "components": {
    "schemas": {
      "AuthConfig": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "logo": {
            "type": "string"
          }
        }
      },
```

Given that getType() returns the correct value I'm guessing that something in the serializer for OpenAPI 3.1 is explicitly calling getTypes and something more clever is needed to handle type vs types (set types explicitly when setType is called?).

**Comment by frantuma** [comment]
It is not clear how is the openapi obtained and how is it serialized, can you specify the original class(es), any config for swagger-core and how are you serializing it?

A common mistake is not setting the `openapi31` flag when resolving an openapi spec out of code (via integration or using directly e.g. ModelResolver), another is using `Yaml.prettyPrint()` instead of `Yaml31.prettyPrint()`

**Comment by frantuma** [comment]
closing for now, please reopen with more details if you are still experiencing issues
