### ISSUE TITLE
Tolerate JAX-RS 2.2 in swagger-core so that it can be deployed in Liberty alongside features which use 2.2

### ISSUE THREAD

**Issue by JDUNNIN** [swagger-api/swagger-core#4590]
When using a Liberty container image such as `icr.io/appcafe/websphere-liberty:23.0.0.9-full-java11-openj9-ubi` and trying to use the swagger-core library we get a conflict due to two implementations of `javax.xml.bind` being available.

The features we need to use within Liberty only supply the 2.2 implementation.

Looking at [swagger-core 2.2.9](https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core/2.2.9) we can see it has compile dependencies on `jakarta.xml.bind-api` 2.3.2 and so provides an implementation at 2.3. This then causes the conflict.

This issue is to request that swagger-core be updated in some way to change the toleration that ends up in the /META-INF/MANIFEST.MF file to be `javax.xml.bind.annotation;version="[2.2,3)"` instead of what it has today: `javax.xml.bind.annotation;version="[2.3,3)"`.

Thanks.

**Comment by micryc** [comment]
Fixed by #4595
