### ISSUE TITLE
Support jakarta.xml.bind-api for spring boot 3 apps

### ISSUE THREAD

**Issue by FoKas90** [swagger-api/swagger-core#4609]
I've recently upgraded my spring boot project to version 3.1.1, therefore it doesn't have any javax.* dependencies. Also my project has dependency from swagger libs 2.2.20 in order to generate openrpc specs.
I use ModelConverters in order to obtain ResolvedSchema. When `ModelConverters.readAllAsResolvedSchema()` is called my app fails with error `ClassNotFoundException: javax.xml.bind.annotation.XmlElement` because SwaggerAnnotationIntrospector depends on `javax.xml.bind.annotation.XmlElement` which doesn't exists in classpath.

I suggest provide support of jakarta.xml.bind-api so that swagger libs can be used within spring boot 3 apps

**Comment by frantuma** [comment]
@ivasilachi thanks for response and pointer, closing ticket
