### ISSUE TITLE
Can't get Swagger + Servlet to work. My APIs are not listed. 

### ISSUE THREAD

**Issue by HelenGao** [swagger-api/swagger-core#463]
Hi.
I followed Swagger Servlet Quickstart guide, and expected to see MyRESTServlet listed under https://localhost:8443/myServer/api-docs. But all it displays is {"apiVersion":"1.0.0","swaggerVersion":"1.2"}.

I annotated my HttpServlet as below:
@Api(value = "/myPath", description = "My REST servlet!")
public class MyRESTServlet extends HttpServlet 
{
…
I added two Swagger servlets in my Tomcat web.xml as instructed by Swagger as below, but not sure if I am supposed to make any changes. For example, what does the paramter swagger.api.basepath means when it's set to http://localhost:8002?

Here is what the Swagger instruction says https://github.com/wordnik/swagger-core/wiki/Servlet-Quickstart: Swagger scans all classes with an @Api annotation on them. Each @Api resource will appear as an Api Declaration in swagger. The annotation is done as follows:

import com.wordnik.swagger.annotations.*;
@Api(value = "/sample/users", description = "gets some data from a servlet")
public class SampleServlet extends HttpServlet {
  ...
Swagger will list your api under /sample/users as well with the description specified. 

I am not sure if this is the right venue for this type of question. Thank you in advance.

**Comment by to-kra** [comment]
Hello I have issue using reflections ClasspathHelper.forPackage for scan -> on local WLP it works fine but deployed on WAS it returns zero results... Anyone help ?

**Comment by webron** [comment]
@to-kra - can you open a new issue or even just send the question to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). It'd be difficult to track this way.

**Comment by to-kra** [comment]
@webron I found a problem in BeanConfig, which scans classes by package. Reflections ClassHelper.forPackage(..) does not count with possibility that classes can be inside of jars like in WEB-INF/lib, as our deployed app has modules compiled into jars placed into WEB-INF/lib. I extended BeanConfig and changed method classes() where i do also fallback to ClasspathHelper.forWebInfLib(..) which can find such jar-ed classes. Now everything works fine !

**Comment by webron** [comment]
@to-kra - great, thanks for the update!

**Comment by JathinSanghvi** [comment]
Facing similar issue as @HelenGao. Can you share what was the solution for it. or atleast a link to mailing thread.

**Comment by sandipmangale** [comment]
@to-kra
Could you please explain me your solution in details or share code.
