### ISSUE TITLE
OpenAPI 3.1 broken reference to child class with oneOf reference

### ISSUE THREAD

**Issue by GooDer** [swagger-api/swagger-core#4634]
Hi, I encountered another bug related to new OpenAPI 3.1 version.

When we have some object which's attribute is another object which is abstract and has at lease one implementation class it will not be rendered and error is displayed in swagger UI.

Version 3.0 output:
![image](https://github.com/swagger-api/swagger-core/assets/953850/12164d7d-6740-4e38-a3be-bcc956f20331)

Version 3.1 output:
![image](https://github.com/swagger-api/swagger-core/assets/953850/66a3db93-341d-4fc2-841d-26f50235b753)

I found out that it is caused again by change in element class from ComposedSchema to JsonSchema.

I will try to provide fix also tomorrow.

Minimalistic project to reproduce:
[swagger-core-bug.zip](https://github.com/swagger-api/swagger-core/files/14668059/swagger-core-bug.zip)

**Comment by micryc** [comment]
Thank you @GooDer for reporting issue and providing fix PR. Closing ticket.
