### ISSUE TITLE
Conflicting jars with swagger-jersey2-jaxrs_2.10

### ISSUE THREAD

**Issue by Gaffney** [swagger-api/swagger-core#464]
Refer to [StackOverflow -- NoSuchMethodError on Values.lazy](http://stackoverflow.com/questions/21742665/nosuchmethoderror-on-values-lazy-jersey-2-5-1)

It'd at least be nice to mention this potential issue in the documentation.  (Something like "If you're using Jersey version greater than X, you will need to add jersey-media-multipart as a dependency and exclude our version.")

```
		<dependency>
			<groupId>com.wordnik</groupId>
			<artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
			<version>${swagger-jersey2.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.jersey.media</groupId>
					<artifactId>jersey-media-multipart</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by fehguy** [comment]
This is fixed in 1.5.x, please see this sample:

https://github.com/swagger-api/swagger-core/tree/develop_2.0/samples/java-jersey2
