### ISSUE TITLE
Which versions of swagger-core are actively supported?

### ISSUE THREAD

**Issue by brianwarner** [swagger-api/swagger-core#4644]
Hi, hopefully this is an easy question. Is there documentation stating which versions of `swagger-core` are actively supported with security backports? For example, "only the latest v2.2 and v1.6 releases receive any type of update" or "security fixes are backported to the last `n` minor releases"?

Also, are there any published end-of-life dates for minor versions?

Thanks!

**Comment by frantuma** [comment]
Thank you for reaching out, I don't think we have this explicitly documented. 

For the Swagger Core project, we actively support and provide updates, including security backports, to the latest minor versions within both the 1.x and 2.x lines (currently 1.6 and 2.2). We do not backport security fixes to previous minor versions.

**Comment by KostadinAlmishev** [comment]
Hi, @frantuma! When will end support of 1.* versions?
