### ISSUE TITLE
`@Header.schema()` in `@ApiResponse` does not generate the `type`

### ISSUE THREAD

**Issue by emcintyre-hpe** [swagger-api/swagger-core#4668]
Hello,

We're using Swagger annotations and Maven plugin to generate our spec. I'm attempting to add some `@ApiResponse` annotations to our operations, but the `@Header` annotation is not including the `schema.type`. For instance:

```java
  @Operation(summary = "List of services for the given account",
             responses = {
                 @ApiResponse(responseCode = "200", description = "List of services for the given account"),
                 @ApiResponse(description = "User did not provide a valid auth token", responseCode = "401",
                              content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                                 schema = @Schema(implementation = ErrorMessage.class)),
                              headers = { @Header(name = "testing-headers",
                                                  description = "Flow/trace ID for traceability in the logs",
                                                  schema = @Schema(type = "string")) })
             })

```

This generates the following spec:

```yaml
    get:
      operationId: getServices
      parameters:
      - in: path
        name: accountId
        required: true
        schema:
          type:
          - string
      responses:
        "200":
          description: List of services for the given account
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: User did not provide a valid auth token
          headers:
            testing-headers:
              description: Flow/trace ID for traceability in the logs
              schema: {} # <- no `type: string` nested here 
              style: simple # <- not sure where this is coming from
      summary: List of services for the given account

```

Even if I add something like `format` to the `@Schema`:

```java
    headers = { @Header(name = "testing-headers",
                        description = "Flow/trace ID for traceability in the logs",
                        schema = @Schema(type = "string", format = "hexadecimal")) })
```

```yaml
            testing-headers:
              description: Flow/trace ID for traceability in the logs
              schema:
                format: hexadecimal
                # still no type
              style: simple
```

(Note that the motivation for adding the schema/type to the header is that linting tools complain about content/schema being required)

**Comment by micryc** [comment]
Hi @emcintyre-hpe could you share more details about your problem (e.g sample project), I tried to reproduce this bug, used exactly same annotations that you provided and  schema type appears.
`parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: List of services for the given account
        "401":
          description: User did not provide a valid auth token
          headers:
            testing-headers:
              description: Flow/trace ID for traceability in the logs
              style: simple
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'`
