### ISSUE TITLE
Requirement: hidden password for APiParam

### ISSUE THREAD

**Issue by shanling2004** [swagger-api/swagger-core#469]
Not sure currently swagger can support to hidden the password in plaintext.
Currently, we 're using swagger-annotations_2.10. For ApiParam definition, we don't see any field to support hidden param value in plaintext.

**Comment by arthurdm** [comment]
in the APIParam annotation, should we use dataType="password"?

**Comment by fehguy** [comment]
good question, i'll reopen this as a reminder to document.  `dataType` _must_ be a fully-qualified class, so I'm certain that `password` is not correct.

**Comment by to-kra** [comment]
Hello, any update on this one ? thx

**Comment by guptayash4** [comment]
<img width="215" alt="untitled" src="https://cloud.githubusercontent.com/assets/8434576/18740098/74d2cc9a-80c5-11e6-8498-d1c8d3408a95.png">

I need to integrate something like this in swagger, i.e Masking the password fields in swagger-ui.

<img width="866" alt="untitled1" src="https://cloud.githubusercontent.com/assets/8434576/18740235/4bd21ef8-80c6-11e6-8c9f-de9603b6e039.png">

My code looks like this, And the question being what should be added here to mask the "name" field?

**Comment by to-kra** [comment]
@fehguy how can i now use this hidden password in my Java APIs ?

**Comment by andreas-fey** [comment]
see #2087

**Comment by fehguy** [comment]
So #2087 is different from this issue.  To use password as a _parameter_ type, you can simply override the format like this:

```
@ApiParam(value = "your password", type = "string", format = "password") @QueryParam(/* normal stuff */)
```

**Comment by to-kra** [comment]
@fehguy is it okay if i update only swagger-annotations JAR? because seems that lots of changed in core, jaxrs & modules since 1.5.3. Do i also need to update swagger UI ? thx

**Comment by fehguy** [comment]
You cannot just update the annotations--need to do all the swagger-core, swagger-jaxrs, swagger-models.  Swagger-ui may work, depending on your version.

**Comment by to-kra** [comment]
@fehguy We cannot update swagger, because lots of changes were made since 1.5.3, and our multiple swagger instance approach is not working anymore.

**Comment by webron** [comment]
@to-kra: considering that version has a critical bug that produces invalid specs, I'd recommend you find a way to make the upgrade. If there are other issues relating to multiple instances (which should have been solved already), please raise them in separate tickets.

**Comment by fehguy** [comment]
@to-kra TBH the mechanism for multiple swaggers is now formalized, previously it was a hack that shouldn't have worked :)

**Comment by Gobliins** [comment]
Hi i am facing same issue, is this fixed?
Or ss there a ways to select between kay7value formdata with hidden password field and json body?

**Comment by bruceadowns** [comment]
I was able to use password characters with the following annotation:

`// @param secret query string false "user password" format(password)`

The annotation is processed using https://github.com/swaggo/swag.

**Comment by misbha23** [comment]
can we hide password field in swagger: 2.0?

**Comment by Rajan2212** [comment]
How to add  below lines in the json file using swagger annotation ? which annotation should be used ?

{
   "type": "string",
   "format": "password"
}

**Comment by rafaelqntn** [comment]
For java people who arrive here:
If using using DTOs, annotate your model field with `io.swagger.v3.oas.annotations.media.Schema;` as in:
`
public class DtoUserCredentials {

    @NotBlank
    private String username;
    @NotBlank
    @Schema(format = "password")
    private String password;

}
`

I didn't try but it should be possible to achieve the same using `@Schema(type = "string", format = "password")` inside of a `@Parameter` annotation at the path operation method.

It generates:
![image](https://user-images.githubusercontent.com/10837826/114117365-ea78f000-98bc-11eb-8741-202451913a42.png)

Maven dependency:
`
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-ui</artifactId>
	<version>1.5.6</version>
</dependency>
`
