### ISSUE TITLE
Parsing/Converting Swagger 2.0 spec to an OpenAPI 3.1.0 spec

### ISSUE THREAD

**Issue by garg-mudit** [swagger-api/swagger-core#4713]
I'm looking for information on the feasibility of converting Swagger 2.0/OpenAPI 3.0.X specifications to OpenAPI 3.1.0 using swagger-core and/or swagger-parser. I understand that converting Swagger 2.0 to OpenAPI 3.0.1 is possible.

Any help regarding the same is appreciated.
Thank You

**Comment by garg-mudit** [comment]
@micryc ^^

**Comment by micryc** [comment]
Hi @garg-mudit sorry for late response, actually we use internally swagger converter 2.0 -> 3.0 in parser, but we also have kind of converter at early prototype stage which can be used to convert 3.0 -> 3.1 [OpenApi30To31](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/OpenAPI30To31.java#L9)
So basically converting directly 2.0 to 3.1 is not possible but achievable in two phases 1. openapi 2.0 -> 3.0, 2. openapi 3.0 -> 3.1

**Comment by garg-mudit** [comment]
Hi @micryc,
Thanks a lot for the info, I will check it out.
