### ISSUE TITLE
Missing schema name for enum

### ISSUE THREAD

**Issue by bennelli** [swagger-api/swagger-core#4722]
https://github.com/swagger-api/swagger-core/blob/5a92e3a6b8e8218aa3243bc443e91c8a27af4401/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L307

The name of the model is resolved already in previous lines of code, but not set into the StringSchema in case of type enum.

**Comment by micryc** [comment]
Hi @bennelli when `enumAsRef` is not applied, which is the default behavior, name should not be set, and the enum should not be part of components/schemas, if you set enumAsRef to true, enum should appear as a component in generated openapi spec, is it solving your issue ? If not, please provide some details about your scenario, for now I am closing the ticket, feel free to reopen if you have any questions
