### ISSUE TITLE
2.2.23 version not published in Maven registry

### ISSUE THREAD

**Issue by VictorPascualV** [swagger-api/swagger-core#4736]
The latest version (v2.2.23) has not been released to the Maven registry: https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core

Was that intended? If so, what is the recommended way to use the latest version of `swagger-core`?

**Comment by frantuma** [comment]
2.2.23 is available on [Maven Central](https://central.sonatype.com/artifact/io.swagger.core.v3/swagger-core/2.2.23/versions)

see https://github.com/swagger-api/swagger-codegen/issues/12350#issuecomment-1970719728 for reference

btw it seems to be available also on mvnrepository: https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core/2.2.23
