### ISSUE TITLE
Swagger Core is not compatible with Jackson 2.18.x

### ISSUE THREAD

**Issue by jamesnetherton** [swagger-api/swagger-core#4755]
`ModelResolver.findJsonVauleType` references Jackson [`BeanDescription.findJsonVauleMethod`](https://github.com/swagger-api/swagger-core/blob/6c14ceb262d019bc4eec170b30d163c81f1b51b5/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L1127) which was [deprecated](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.17.2/src/main/java/com/fasterxml/jackson/databind/BeanDescription.java#L259-L260) since Jackson 2.9. It got removed in Jackson 2.18.0, hence there's the potential for runtime errors if Jackson 2.18.x is on the classpath. Or build time errors if GraalVM is used to create a native application.

**Comment by micryc** [comment]
Hi @jamesnetherton thank you for reporting, possible problem should be solved by: https://github.com/swagger-api/swagger-core/pull/4756, Closing ticket for now, If you will experience any problem, feel free to reopen

**Comment by frantuma** [comment]
fixed in #4806 4806
