### ISSUE TITLE
The 'allowMultiple' ApiParam property doesn't appear in the JSON spec any more

### ISSUE THREAD

**Issue by valdemon** [swagger-api/swagger-core#478]
Hi,
I'm using the swagger-jaxrs_2.10:1.3.2 (with swagger-core_2.10:1.3.2) and experienced missing 'allowMultiple' attribute in the generated API JSON spec, when using the ApiParam(allowMultiple=true...) annotation. 
The annotation attribute is not marked as deprecated. Is it missing in JSON by intention (eg. because being redundant as of  usage of the 'array' type) or is it a bug?

**Comment by brutuscat** [comment]
@fehguy I know that this is closed and in our project we are in the path to migrate to swagger v2 (json schema yay!), but apart from the comma-separated value format, you might also considerthe, already supported by php and ruby (and I guess more languages), `key[]=value` format.

**Comment by webron** [comment]
@brutuscat - that's a naming convention, not a value one. By default, JAX-RS will use multiple instances of the same name (so `key=X&key=Y`). If you want to end up with `key[]=value` you'd have to make sure to translate that to the parameter name as well.

**Comment by brutuscat** [comment]
@webron JAX-RS is also a naming convention, that's what are you saying right? I understand that, I was just suggesting to not forget this particular format when considering formats. TBH honest haven't read the whole thread...

Ok, but what about try to use some sort of [RFC 6570 - URI Template](https://tools.ietf.org/html/rfc6570) to specify the format? No idea if it is possible to have template "fragments" though...

**Comment by webron** [comment]
@brutuscat - this project is about Java in general and JAX-RS more specifically right now (with some support for other frameworks). It doesn't need to support conventions that don't exist here.

As for URI templating, that's an entirely different issue that's been discussed in our google groups and swagger-spec repo several times. Please try to look those up.

**Comment by brutuscat** [comment]
@webron right! I guess "core" and "spec" looks similar to me...  I'll read the discussion in the groups thanks.

**Comment by DavidBiesack** [comment]
OpenAPI 2.0 [does not support `allowMultiple`](http://swagger.io/specification/#parameterObject), nor does it allow `format: array`. However, one can set the **`type`** of a query parameter to `array` (with items being a string/enum) and set **`collectionFormat: csv`**, and Swagger UI will emit 
```
 … &param=value1,value2
```

OAS 3.0 will allow [parameter styles](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#style-values) which includes a `style: form, explore:false` style for query params which should support the same csv representation.
