### ISSUE TITLE
@ApiModelProperty and @ApiModel not respected in EJB module

### ISSUE THREAD

**Issue by Paave** [swagger-api/swagger-core#485]
Model descriptions are not read by the the Swagger when models are placed in to the EJB module of EJB in EAR project. This is likely in Swagger core According Ron R. and Tony Tam (as discussed in https://groups.google.com/forum/#!topic/swagger-swaggersocket/xVvQekBHLxo).

**Comment by kret11** [comment]
I think it deserves to be reopened and fixed.
