### ISSUE TITLE
Issue with generics model and return type

### ISSUE THREAD

**Issue by shuz** [swagger-api/swagger-core#498]
The reflection can't find proper generic model property.
```
public class ResultList<T> {
    private List<T> results;
    public List<T> getResults() {
        return results;
    }
    public void setResults(List<T> results) {
        this.results = results;
    }
}
class UserResultList extends ResultList<User> {
}
```

The reflection can find the ResultList results property, but it shows as an array of objects. To work around, I have to override the methods:
```
class OfferResultList extends ResultList<Offer> {
    @Override
    public List<Offer> getResults() {
        return super.getResults();
    }
    @Override
    public void setResults(List<Offer> results) {
        super.setResults(results);
    }
}
```

The issue also exists in the method return types. I looked at the code and seems it's not trivial to make a fix. All reflection functions are expecting a `Class[_]` rather than `Type`.

**Comment by fehguy** [comment]
For now, there is the opportunity to override datatypes with the `@ApiModelProperty` annotation, like such:  https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/1_3/models/ModelWithModelPropertyOverrides.java#L7-L18

```
public class ModelWithModelPropertyOverrides {
  @ApiModelProperty(dataType = "List[models.Children]")
  private String children;

  public String getChildren() {
    return children;
  }

  public void setChildren(String children) {
    this.children = children;
  }
}
```

where you override the datatype with whatever you like, which means generics can be expressed in any concrete class.

**Comment by fehguy** [comment]
Partial solution, moving to M2 for more investigation and more use cases.

**Comment by ovstetun** [comment]
Will there be a general solution to this problem? I am exposing an API with a general "ResultList" implementation supporting paging:

```java
public class ListResult<T> {
	public long size = 0;
	public long rangeFrom = 0;
	public long rangeSize = 0;
	public List<T> entries = Collections.emptyList();
}
```

And I should really have the `T`-type as part of my Swagger documentation.

**Comment by fehguy** [comment]
It is technically impossible to support all forms of generics.  The general solution is to manually map generics to an interface or type if runtime reflection is not possible.  There will be guidelines for M2, which we're working on.

**Comment by ovstetun** [comment]
I found a "reasonable" way for my case to give the correct output to work in swagger ui, by subclassing the return type and overriding the generic parts. Note that my private class is not used in code, only as parameter for swagger and the `@ApiOperation`-annotation.

```java
public class ListResult<T> {
	public long size = 0;
	public long rangeFrom = 0;
	public long rangeSize = 0;
	public List<T> entries = Collections.emptyList();
}

@Path("/records")
@Api(value = "/records", description = "")
public class RecordsResource {

    @GET
    @Path("inbox")
    @ApiOperation(value = "/inbox", response = RecordResultList.class)
    public Response inbox() {
      ListResult<Record> result = ListResult.create(records, RecordXTO::new);
      return Response.ok().entity(result).build();
    }
    private static class RecordResultList extends ListResult<Record> {
      public List<Record> entries;
    }
}
```

Hope this helps somebody else, for me this works as an OK workaround.

**Comment by MichaelMcClure** [comment]
+1

**Comment by tomtit** [comment]
It's impossible to pass generic type via the `@ApiOperation.response`, but we can get the right type from the return type. After the #1119 the definition below should provide the correct output:
```java
@GET
@Path("inbox")
@ApiOperation(value = "/inbox")
public ListResult<Record> inbox() {
  return ListResult.create(records, Record::new);
}
```

**Comment by webron** [comment]
@tomtit - that would work only if the method returns the type itself. The more common use case with JAX-RS is to return a `Response` that can also include the HTTP code and so on. That's actually the reason why the `response` was included in `@ApiOperation`.

**Comment by tomtit** [comment]
In this case the `response` should be of type [java.lang.reflect.Type](https://docs.oracle.com/javase/6/docs/api/java/lang/reflect/Type.html) but not [Class](https://docs.oracle.com/javase/6/docs/api/java/lang/Class.html).

**Comment by webron** [comment]
And then how would it be represented?

**Comment by tomtit** [comment]
Unfortunately there is no way to do this as [JLS](http://docs.oracle.com/javase/specs/jls/se6/html/interfaces.html#9.6) states:
>It is a compile-time error if the return type of a method declared in an annotation type is any type other than one of the following: one of the primitive types, String, Class and any invocation of Class, an enum type (§8.9), an annotation type, or an array (§10) of one of the preceding types.

**Comment by tomtit** [comment]
So, we need to use the workaround with a non-generic type (`RecordResultList`) or change method's return type from `Response` to generic type.

**Comment by webron** [comment]
Not really up to us but up to the users, but sure, we're limited with our options.

**Comment by chenjianjx** [comment]
Why is this issue closed?  Is there any new issue tracking this problem?   @ovstetun  's workaround is fine, but it may cause too many classes to be created.

**Comment by fehguy** [comment]
@chenjianjx please see my comment https://github.com/swagger-api/swagger-core/issues/498#issuecomment-73732315

**Comment by chenjianjx** [comment]
ok, thank you

**Comment by tavoda** [comment]
@fehguy sure you can not support ALL POSSIBLE forms of generic, however you can easily support at least very common patterns which can make life better. Just simple e.g. Result<T, U> and than have possibility to specify for example return type as Result<String,Person>. This is supported by many languages and doesn't require too much changes in spec.

**Comment by webron** [comment]
@tavoda @fehguy was talking about the limitations of Java with type erasure as the ability to read and retrieve the types. Changes to the spec have nothing to do with swagger-core. If you'd like to see changes there, please open a ticket on [the spec](https://github.com/OAI/OpenAPI-Specification) itself.

**Comment by tavoda** [comment]
Which limitations? Erasures are in generic type (e.g. List), in concrete type you can find it easily. This code produce:
Method getListOfStrings return java.util.List[java.lang.String]
Method getMapOfStringToSample return java.util.Map[java.lang.String, Sample]
```
public class Sample {
	public List<String> getListOfStrings() {return null;}
	public Map<String, Sample> getMapOfStringToSample() {return null;}

	public static void main(String[] args) {
		Method[] methods = Sample.class.getDeclaredMethods();
		for (Method m : methods) {
			Type returnType = m.getGenericReturnType();
			if (returnType instanceof ParameterizedType) {
				ParameterizedType pType = (ParameterizedType) returnType;
				StringBuilder params = new StringBuilder();
				String prefix = "";
				for (Type type : pType.getActualTypeArguments()) {
					params.append(prefix).append(type.getTypeName());
					prefix = ", ";
				}
				System.out.println("Method " + m.getName() + " return "
					+ pType.getRawType().getTypeName() + "[" + params + "]");
			}
		}
	}
}
```

**Comment by webron** [comment]
If you feel things can be improved, you're more than welcome to submit PRs with changes.

**Comment by tavoda** [comment]
@webron I'm still confused by spec. Maybe implementation is fine, I would like to have very simple Java return type like PagingResult:
```
class PagindResult<T> {
	int startRow, endRow, totalRows;
	T data;
}
```
And than AddressService.find method which return just PagingResult<Address>. What is correct way of specifying PagingResult in Swagger? Do I have to create specific type for each service?
I can investigate in Java all necessary types however I'm not able to write it in swagger. Is it really problem of core or spec?
Thanks for your help

**Comment by webron** [comment]
You'd need to create a specific type for each service, yes. https://github.com/OAI/OpenAPI-Specification/issues/555 covers this as a feature request for the next version as there's no easy way to define wrappers for responses.

**Comment by tavoda** [comment]
Thanks @webron, I will track that issue.

**Comment by tomtit** [comment]
@tavoda actually it depends on the way you define your resource:
```
@Path("/")
public class AddressService {

    // Here you need a specific type
    @GET
    @Path("/foo")
    @ApiOperation(value = "/foo", response = PagingResultOfAddresses.class)
    public Response foo() {
        ...
    }

    // Swagger core will handle return type
    @GET
    @Path("/boo")
    @ApiOperation(value = "/boo")
    public PagingResult<Address> foo() {
        ...
    }
}
```

**Comment by tavoda** [comment]
@tomtit nice to know, thanks

**Comment by Marvel77** [comment]
Hey, guys! Maybe it will be usefull. I had same issues with my Spring based application and I've used alternate type rules in the Swagger config:
`@Bean
    Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(paths())
                .build()
                .apiInfo(apiInfo())
                .alternateTypeRules(
                        newRule(typeResolver.resolve(DeferredResult.class,
                                typeResolver.resolve(ResponseEntity.class, WildcardType.class)),
                                typeResolver.resolve(WildcardType.class)))
                ;
    }`

This means: Swagger, if you will find DeferredResult<ResponseEntity<Something>> then use <Something> as return type for generating JSON in SwaggerUI.

Here is a controller's method signature:
`@ApiOperation(
            value = "Authenticate a user",
            notes = "..."
    )
    @RequestMapping(method = RequestMethod.POST)
    public DeferredResult<ResponseEntity<BaseResponse<AccessTokenResponse>>> authAndGetDeviceInfo(@RequestBody AuthUserRequest authReques...`

And now Swagger generates returned JSON description based on generic BaseResponse<AccessTokenResponse>.

Have a nice day!

**Comment by Marvel77** [comment]
Hey, guys! Maybe it will be usefull for someone. I had same issues with my Spring based application and I've used alternate type rules in the Swagger config:
`@Bean
    Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .paths(paths())
                .build()
                .apiInfo(apiInfo())
                .alternateTypeRules(
                        newRule(typeResolver.resolve(DeferredResult.class,
                                typeResolver.resolve(ResponseEntity.class, WildcardType.class)),
                                typeResolver.resolve(WildcardType.class)))
                ;
    }`

This means: Swagger, if you will find DeferredResult<ResponseEntity<Something>> then use <Something> as return type for generating JSON in SwaggerUI.

Here is a controller's method signature:
`@ApiOperation(
            value = "Authenticate a user",
            notes = "..."
    )
    @RequestMapping(method = RequestMethod.POST)
    public DeferredResult<ResponseEntity<BaseResponse<AccessTokenResponse>>> authAndGetDeviceInfo(@RequestBody AuthUserRequest authReques...`

And now Swagger generates returned JSON description based on generic BaseResponse<AccessTokenResponse>.

Have a nice day!

**Comment by fehguy** [comment]
@Marvel77 thank you for sharing

**Comment by lecoque** [comment]
How is this solved?

**Comment by tavoda** [comment]
It's problem of SPEC. This mean is not possible to specify real generic return type. Core is handling it fine as mentioned by @tomtit . It should be closed.
