### ISSUE TITLE
Swagger JAX-RS endpoint returning empty class leads to odd spec generation

### ISSUE THREAD

**Issue by giovannibotta** [swagger-api/swagger-core#499]
I have an endpoint that returns an empty class, say `EmptyDTO`. The reason why it's empty is because I had just added the endpoint and I wanted to quickly generate the spec and then codegen the java client to use in other parts of the projects making sure the API looked as it was supposed to. 

My `EmptyDTO` obviously looks like this:

    public class EmptyDTO {}

and the endpoint returning `EmptyDTO` led to the following spec being generated:

    {
        "path": "/newEndpoint/{id}",
        "operations": [
            {
                "method": "GET",
                "summary": "",
                "notes": "",
                "type": "com.mypackage.dto.EmptyDTO",
                "nickname": "someMethod",
                "produces": ["application/json"],
                "authorizations": {},
                "parameters": [
                    {
                        "name": "id",
                        "required": true,
                        "type": "string",
                        "paramType": "path"
                    }
                ]
            }
        ]
    }

No model gets generated and return type is set to the fully qualified class name. The codegen then complains:

    Mar 18, 2014 5:47:21 PM com.wordnik.swagger.codegen.spec.SwaggerSpecValidator validate
    WARNING: no models found for listing  www.mywebsite.com
    missing models: Set(com.mypackage.dto.EmptyDTO)

And the generated method returns the undefined `com.mypackage.dto.EmptyDTO`.

I believe this is a bug.

**Comment by fehguy** [comment]
Will test for this case for m2

**Comment by fehguy** [comment]
this has been fixed in 1.5.x.  The model, when empty however, should be more like this:

```json
{
  "type": "object"
}
```
