### ISSUE TITLE
@XmlElement not working correctly on Fields

### ISSUE THREAD

**Issue by sohailehmad** [swagger-api/swagger-core#502]
If I use @XmlElementon a Filed, it will only work if Field name is same as provided in XmlElement e.g

``` sh
@XmlRootElement(name = "Pet")
public class Pet {
  @XmlElement(name = "name")
  public String name;
}
```

But if field name is different from the one provided in XmlElement field will not appear in api docs

``` sh
@XmlRootElement(name = "Pet")
public class Pet {
  @XmlElement(name = "pet_name")
  public String name;
}
```

**Comment by feliperoos** [comment]
Hi Folks! Shouldn't this work on fields also? I'm pretty sure JAX-RS does not pose any restriction on the definition for XmlElement. Other than that, it makes difficult to have swagger working properly with project lombok.

**Comment by webron** [comment]
@feliperoos you commented on an issue from over a year ago, which is not even relevant to the current stable version. If you have an issue with the 1.5.X versions, please open a new ticket and provide details so we can try and help. Keep in mind that by default the new swagger-core doesn't support JAXB annotations but the support can be added manually.
