### ISSUE TITLE
@XmlElementWrapper not working

### ISSUE THREAD

**Issue by elisid** [swagger-api/swagger-core#505]
If you annotate a field with <code>@XmlElementWrapper</code> the model spec will be wrong.  

Examples taken from the java-jaxrs sample project:

In the model we annotate a field with <code>@XmlElementWrapper</code>:
<pre>

@XmlRootElement(name = "Pet")
public class Pet {
...
  <b>@XmlElementWrapper(name = "photoUrls")</b>
  @XmlElement(name = "photoUrl")
  public List<String> getPhotoUrls() {
    return photoUrls;
  }
...
}

</pre>

We expect the field to appear in the swagger specification of the model as <code>photoUrls</code> but instead it appears as <code>photoUrl</code>:

<pre>

{
   "apiVersion":"1.0.0",
   "swaggerVersion":"1.2",
   "basePath":"http://localhost:8002/api",
   "resourcePath":"/pet",
   "produces":[
      "application/json",
      "application/xml"
   ],
   "apis":[
...
   ],
   "models":{
...
      "Pet":{
         "id":"Pet",
         "properties":{
            "<b>photoUrl</b>":{
               "type":"array",
               "items":{
                  "type":"string"
               }
...
         }
      },
...
   }
}

</pre>

When we query the rest resource we get as expected:
<pre>

$ curl http://localhost:8002/api/pet/1
{"id":1,"category":{"id":2,"name":"Cats"},"name":"Cat 1",<b>"photoUrls"</b>:["url1","url2"],"tags":[{"id":1,"name":"tag1"},{"id":2,"name":"tag2"}],"status":"available"}

</pre>

**Comment by fehguy** [comment]
Per design in swagger-spec 2.0, the following model:

```java
@XmlRootElement(name = "monster")
public class Monster {
  public String name;

  @XmlElementWrapper()
  @XmlElement(name = "children")
  public java.util.List<String> child;
}
```

will produce the following:

```json
{
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "children" : {
      "type" : "array",
      "xml" : {
        "name" : "children",
        "wrapped" : true
      },
      "items" : {
        "type" : "string"
      }
    }
  },
  "xml" : {
    "name" : "monster"
  }
}
```

This support having different model naming conventions between json & xml, as well as supporting wrapped values in XML which are more concisely written in JSON.  See https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#xml-object for more details
