### ISSUE TITLE
Document a way to replace JerseyJaxrsConfig with some custom configuration

### ISSUE THREAD

**Issue by davidecavestro** [swagger-api/swagger-core#513]
The documentation states 
>The default configuration class is JerseyJaxrsConfig, which reads configuration values from your web.xml

but doesn't explain how the default configuration could be overridden.
i.e. I'd like to provide a custom ``swagger.api.basepath`` value took from a properties file (not from ``web.xml``) but since sources have no comments it's really hard figuring out how to obtain some custom behavior. It becomes cumbersome especially when you cannnot write Scala code.
i.e. with the following snippet I have no control on the base url for service calls from the swagger ui, but if I set the corresponding init parameter for ``JerseyJaxrsConfig`` within ``web.xml`` it works fine
```MySwaggerConfigurator.groovy
...
ConfigFactory.setConfig(new SwaggerConfig() {
    @Override
    public String getBasePath() {
        return 'my/base/path'
    }
    @Override
    public String getApiVersion() {
        return '1.0.0'
    }
})

ScannerFactory.setScanner(new DefaultJaxrsScanner())
ClassReaders.setReader (new JerseyApiReader())
...
```

UPDATE: at the end I've switched to ``com.wordnik.swagger.jaxrs.config.BeanConfig``

**Comment by fehguy** [comment]
@rjstanford in 1.5.x-M1 the `BeanConfig` supports multiple packages in a CSV string.
