### ISSUE TITLE
Support for setting format for annotations with dataType

### ISSUE THREAD

**Issue by mhamrah** [swagger-api/swagger-core#517]
The primitive types, [according to the spec](https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md#431-primitives) allow for specifying a format along with the dataType. The annotations ApiModelProperty, ApiParam, and ApiImplicitParam support a dataType field but no corresponding format field.
- Was this left out intentionally?
- Should it be added?

Thanks

**Comment by tsandall** [comment]
Per https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types the format doesn't need to be specified in the standard. Any chance of revisiting this? /cc @fehguy

**Comment by webron** [comment]
@tsandall - the issue was opened on swagger-core 1.3 which was Swagger 1.2. What do you find to be a problem though?

**Comment by tsandall** [comment]
I would like to be able to explicitly set the "format" of model properties. The current version of the ApiModelProperty annotation (https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/io/swagger/annotations/ApiModelProperty.java) doesn't allow this from what I can tell. If there's a better way of doing this let me know. Thanks!

**Comment by webron** [comment]
Can you give me an example of what you'd want to set?

**Comment by tsandall** [comment]
I want to describe the semantics of properties using the "format" field. For example, I may have string properties which represent UUIDs or IP addresses or I have may integer properties which represent TCP port numbers or VLAN IDs. I would like to set the "format" to values like "uuid", "ipv4", etc.

Simplistic example:

```
@ApiModel(description = "...")
case class WebServer(
  @(ApiModelProperty @field)(value = "...", format = "uuid") id: String,
  @(ApiModelProperty @field)(value = "...", format = "ipv4") address: String)
```

**Comment by webron** [comment]
There's something a bit tricky here. You want to add additional restrictions (which is fine) to something you define as a String. I don't see in the code itself that you restrict the data type itself more than that. So what happens if someone sends "abc" as the `address`? Will the operation throw an exception?

FWIW, we already convert `java.util.UUID` to format `uuid`.

**Comment by tsandall** [comment]
Yes, it would/should throw an exception. I'm not sure I see where the tricky bit is. Are you saying the API author should not be able to control the type and format of the properties in their models?

**Comment by webron** [comment]
Sorry, I wasn't clear. Of course you should be able to control it manually, it's just that in many cases you'd opt for a wrapping class or using standard JSR303 annotations to provide with the additional restrictions, rather than manually do the processing within the method. Feel free to open a new ticket for it with the detailed use case, and we'll see how/if we'll support it.

**Comment by abelsromero** [comment]
Sorry to bring back the topic, but how about stream data?
I have a download file service that returns an InputStreamResource, but I am unable to define the return as `type: file` or `type:string format:binary`.
Using ` @ApiResponse(response = byte[].class)` swagger generates `type:string format:byte`, which means Base64 encoded, which is not what the service responds.

**Comment by ngbalk** [comment]
Has there been more discussion around @abelsromero 's concern?  I too am not able to find a reasonable solution for autogeneration of Java client's that return stream data.

**Comment by blanorama** [comment]
@abelsromero, I have the very same situation and constellation…
Do you remember by any chance how you proceeded in your case?
Regards

**Comment by t3hk0d3** [comment]
Still not solved :(

**Comment by abelsromero** [comment]
I no longer work on content services, but for anyone interested I'd suggest to open a new story since this is closed.
