### ISSUE TITLE
JsonIgnoreProperties not considered while converting groovy class to json

### ISSUE THREAD

**Issue by iWebi** [swagger-api/swagger-core#519]
I have a Rest resource with as groovy class as response type.
I used @JsonIgnoreProperties annotation to exclude metaClass property from groovy. But still this property is listed in swagger-ui Response Class model.
http://stackoverflow.com/questions/22763820/exclude-metaclass-properties-for-groovy-model-classes-in-swagger lists the Foo instance.

com.wordnik.swagger.converter.ModelPropertyParser class does not seem to consider the JsonIgnoreProperties annotation. Is this true? How do I make swagger consider my JsonIgnoreProperties  annotation?

**Comment by webron** [comment]
@fehguy - is this still an issue for 1.5? Doesn't the Jackson parsing read these annotations now?

**Comment by fehguy** [comment]
Will add tests and close after confirming.

**Comment by fehguy** [comment]
supported and tested in 1.5.x-M1 and greater, see https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/1_3/converter/JsonIgnorePropertiesModelTest.scala
