### ISSUE TITLE
Swagger doesn't respect JAX-RS's @QueryParam's target

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#52]
According to the JAX-RS spec/code, the `@QueryParam` annotation's `@Target` is:

``` java
@Target({ElementType.PARAMETER, ElementType.METHOD, ElementType.FIELD})
```

Swagger's `@ApiParam` annotation has the following `@Target` definition:

``` java
@Target(ElementType.PARAMETER)
```

As such, there are some cases where the API cannot be fully generated using Swagger (for example, if the @QueryParam variable is defined in the class and not as the method parameter).

**Comment by shruthipodduturi** [comment]
I am using swagger @ApiParam annotation for query params. But in the swagger UI, params are listed as body params instead of queyr params.Can some one help in this.
