### ISSUE TITLE
Annotation scanning doesn't work using multiple classloaders

### ISSUE THREAD

**Issue by davidecavestro** [swagger-api/swagger-core#520]
I was trying to port the existing [maven-swagger-plugin](https://github.com/kongchen/swagger-maven-plugin/issues/52) to the gradle build system, but I'm experiencing some issues cause the gradle plugin loads ``JaxrsApiReader`` with the gradle default classloader while the scanned classes are loaded using a ``URLClassloader`` (needed to discover annotations on the classes just compiled by gradle).
Now the problem is that ``JaxrsApiReader`` uses the Java reflection package for code analysis, as supposed at [gradle forums](http://forums.gradle.org/gradle/topics/gradle_plugin_cannot_process_well_known_annotations_available_from_script_classpath_for_classes_loaded_via_urlclassloader). This causes problems if you call ``barClass.getAnnotation(Foo)`` on a ``barClass`` class instance loaded with a classloader different from the one that actually loaded ``Foo``.
The solution could be replacing java reflection calls with a bytecode-based analysis based approach.
I'd like to propose a patch using ASM, but I've never written Scala code (so far).

Also simply exposing a way to override reflection calls could be enough to easily switch from a reflection based implementation to an ASM one.

**Comment by fehguy** [comment]
I don't think this is still an issue with 1.5.x.  Please reopen if so
