### ISSUE TITLE
2 Resource types differing by @Consumes/@Produces only being lost in swagger spec generation

### ISSUE THREAD

**Issue by emilesvt** [swagger-api/swagger-core#521]
We have 2 resources that are nearly identical, with the exception of their @Produces and @Consumes.  The methods these resources define are (nearly) identical.

```java
@Path("bankThings")
@Api(value = "/bankThings", description = "Bank Thing Operations")
@Produces({"application/vnd.mycompany+v1+json"})
@Consumes({"application/vnd.mycompany+v1+json"})
public class BankThingResource  {
...
```
and the other resource:
```java
@Path("bankThings")
@Api(value = "/bankThings", description = "Bank Thing Operations")
@Produces({"application/vnd.mycompany+v2+json"})
@Consumes({"application/vnd.mycompany+v2+json"})
public class BankThingResource  {
```

When I query the Swagger servlet for the api-docs for /bankThings, sometimes I get content for the v1 version, sometimes I get the content for the v2 version.  There is no rhyme or reason as when I get what, nor do I ever get both of them.  I would expect Swagger to expose all of these as they are truly different (since the produces/consumes have different mime types).

**Comment by fehguy** [comment]
closing with no response.
