### ISSUE TITLE
swagger play framework and ebean

### ISSUE THREAD

**Issue by chenbekor** [swagger-api/swagger-core#527]
swagger is not working nicely on play framework if using ebean:

when browsing the generated json spec you can notice some Domain Models from ebean that are being added to the API documentation..

swagger should somehow skipping ebean generated wrappers/classes.

**Comment by fehguy** [comment]
Fix is in 1.3.13-SNAPSHOT

**Comment by webron** [comment]
**Applies to https://github.com/swagger-api/swagger-core/milestones/v1.5.0-M1 as well.**
