### ISSUE TITLE
Same basepath and api.version are outputted when hosting two separate version of swagger

### ISSUE THREAD

**Issue by kllam55** [swagger-api/swagger-core#539]
This happens when two instance of swaggers are hosted in the same war file.   Initially swagger will output all resources (that are annotated) under /api-docs; however, with the help of @fehguy I was able to deactivate the cache and each instance of swagger is able to output its respective resource (v1 vs v2 API).  The remaining hurdle is that properties such as api.version and swagger.api.basepath are the same for each version of swagger (despite being configured with different values in each web.xml).  The api.version is a nice to have; however swagger.api.basepath is not since the swagger-ui utilize it to access the APIs.

**Comment by webron** [comment]
@fehguy - isn't this resolved in 1.5 already?

**Comment by fehguy** [comment]
No longer an issue with 1.5.x as there is no static state.
