### ISSUE TITLE
Support custom responseContainer types

### ISSUE THREAD

**Issue by apemberton** [swagger-api/swagger-core#540]
Since many APIs return their own customized collections, it would be ideal to support custom responseContainers.

For example:

@ApiOperation(value = "Search for things", response = Thing.class, responseContainer = CollectionResponse<Thing>.class)

I realize there are issues w/type erasure, etc. but is there some way to get this done?

**Comment by perabello** [comment]
I have the same problem.
I do not find a concrete solution on 2.0 specification.
Nor has responded to issue #559

**Comment by webron** [comment]
@perabello - commenting on closed issue won't help. If you want something implemented, open a new issue and provide as many details as possible.
