### ISSUE TITLE
@BeanParam annotations should work on methods

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#543]
the update to jersey2 support does work with @BeanParam objects, however it will only find fields.  It should also treat methods correctly.  Here is the offending code:

https://github.com/wordnik/swagger-core/blob/master/modules/swagger-jaxrs/src/main/scala/com/wordnik/swagger/jaxrs/JaxrsApiReader.scala#L268

**Comment by whitlockjc** [comment]
This seems to have been completed already but the code is in master only and not the develop_2.0 branch.  The important commit was a part of pull request #547.  Can you (@fehguy) confirm this?  If so, fixing this is as simple as merging 0adb22e from `master` to `develop_2.0`.

**Comment by fehguy** [comment]
The logic is in master but it's not complete.  In addition, in master it's scala and not java so it'll need a complete redo

**Comment by whitlockjc** [comment]
Okay, I'll get started.  Thanks for clarifying.

**Comment by whitlockjc** [comment]
Pull request #843 should address this when accepted.
