### ISSUE TITLE
Avoid static state based on current classloader

### ISSUE THREAD

**Issue by davidecavestro** [swagger-api/swagger-core#557]
I could be wrong, but when doing things like ``ClassReaders.reader = Some(new DefaultJaxrsApiReader)`` we rely on defining some static state, actually based on the classloader that loaded the ``ClassReaders`` class.

This become cumbersome when using swagger into _exotic_ scenarios, like preparing a plugin for a build system like gradle. Now the swagger plugin is loaded by the build system classloader, but the built application defines some custom code overriding default swagger behavior (like adding ``ModelConverters`` for specific classes and so on): since the customization code MUST be loaded through a dedicated classloader (in order to load the classes that have just been compiled) gaining access to all the needed libraries, it needs to be in a classloader hierarchy separated from the build system one.
So every override of swagger behavior performed by the custom code is done on the class copies loaded by the separate classloader, but this way - as soon as the execution returns to the plugin - every customization is lost (as it is doesn't share the same copy of classes as the customization code).

Wouldn't it be better having a configurable swagger context that can be passed as needed? i.e. a _SwaggerContext_ populated with all the needed objects. This way you could have more that a swagger configuration per JVM/classloader and avoid duplicate static state issues

**Comment by webron** [comment]
@fehguy - isn't this part of 1.5 already?

**Comment by fehguy** [comment]
I believe this is fixed now.
