### ISSUE TITLE
Annotations of resource interfaces not read

### ISSUE THREAD

**Issue by Shwaaathi** [swagger-api/swagger-core#562]
Hi, 
We have a rest service with this structure:
com.a: ResouruceInterface1, com.b: ResouruceInterface2
I'm using JBOSS.
All the annotations are mentioned in the interface. I read that Swagger doesn't scan these annotations so I tried using ReflectiveJaxrsScanner. But, can you tell me how to use this in web.xml?
https://github.com/wordnik/swagger-core/issues/400#event-92074484

**Comment by webron** [comment]
Closing as supported. Please resubmit an bug if still an issue.

**Comment by pike1212** [comment]
The **@Inherited** annotation only applies to super classes not to Interfaces.

**Comment by webron** [comment]
If you feel there's a problem, it's better to open a new issue.
