### ISSUE TITLE
Multiple Jaxrs resources with same @Path; swagger doesnt generate Model JSON

### ISSUE THREAD

**Issue by advaittrivedi** [swagger-api/swagger-core#590]
I am having jersey Jaxrs 2.0 app. I have multiple resources with same path "/user", I have integrated swagger by following configuration at https://github.com/wordnik/swagger-core/wiki/Java-JAXRS-Quickstart and swagger generates JSON. But it doesnt generate Model info in the JSON when I have multiple resources having same @Path. Swagger libraries used - swagger-jersey2-jaxrs_2.10-1.3.5.jar, swagger-jaxrs_2.10-1.3.5.jar, swagger-core_2.10-1.3.5.jar, swagger-annotations-1.3.5.jar. When I remove @Api annotation, and leave it only on just one resource with "/user" @Path then it generates models ok. I am not adding @ApiParam and @ApiModel annotations, but also tried adding them, it doesn't help.

**Comment by jGauravGupta** [comment]
Issue is still coming for v1.3.7
