### ISSUE TITLE
Introspection bug - class is not added to the models if it's not referred to directly

### ISSUE THREAD

**Issue by slustbader** [swagger-api/swagger-core#606]
Per [this thread](https://groups.google.com/forum/#!topic/swagger-swaggersocket/BFYhTPX_w30) on the mailing list, there is an introspection bug in which a class doesn't get added to the models if it's not referred to directly (with response=MyModel.class for example).

**Comment by fehguy** [comment]
Addressed in 1.5.0-SNAPSHOT

**Comment by slustbader** [comment]
Any chance this could be back-ported to 1.3.x? Does 1.5.0 have an estimated release date yet?

**Comment by fehguy** [comment]
1.5.x should be api compatible with 1.3.x.  Can you upgrade?

Given resources (time) it's difficult to back port changes back to 1.3.x unless they're big bugs.  1.5.2-M1 has been released to maven central, with M2 a couple days away.  If you can migrate to it, I expect your life will get a lot easier

**Comment by slustbader** [comment]
We're using Play, so as you noted in another thread, we'll have to wait at least until M3 for play support - if that's really going available to be available, we can wait (and just use the "extra" API operation workaround for now).

We're also a little reluctant to use a milestone build, but if M3 is close to final (and since API documentation isn't mission critical), I think it'll be OK.
