### ISSUE TITLE
Guava's Optional<T> interpreted as array resulting in missing data type

### ISSUE THREAD

**Issue by danieljamesscott** [swagger-api/swagger-core#609]
A method accepting a @QueryParam with type Optional<String> from Guava results in invalid JSON:

public Collection<Environment.EnvironmentView> get(@QueryParam("vpnName") final Optional<String> vpnName)

Results in:

"parameters":[{"name":"vpnName","required":false,"items":{"type":"string"},"paramType":"query"}]

i.e. The data type field is missing.

Apparently, the Optional<String> is being interpreted as an array/collection. The missing data type field causes an error in the UI.

Github source:
https://github.com/danieljamesscott/swagger-guava

Google group discussion:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/i_X_mDdwIWQ

I'm afraid I don't know Scala at all, but I'll do my best to help if I can.

**Comment by JonMR** [comment]
Bump.  Any work done here?

**Comment by webron** [comment]
It's marked for M2 *and* P1, which means it's at the highest priority to enter the next milestone within a few weeks.

Of course, PRs could make it happen faster :)

**Comment by JonMR** [comment]
@webron Can you point me in the general direction of the code I should be looking at?

**Comment by fehguy** [comment]
Here's the code, based on jackson:

https://github.com/swagger-api/swagger-core/tree/develop_2.0/modules/swagger-core/src/main/java/com/wordnik/swagger/jackson

Here's a test (note it's disabled):

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/GuavaTest.scala

**Comment by JonMR** [comment]
https://github.com/swagger-api/swagger-core/pull/871 was merged. Can this be closed now?

**Comment by fehguy** [comment]
Yes this is now in 1.5.1-M1. Thanks!
