### ISSUE TITLE
Java 8 lambda compatibility

### ISSUE THREAD

**Issue by amanteaux** [swagger-api/swagger-core#612]
Swagger is not compatible with Java 8 Lambda expression.
If a lambda is used inside a web-service class, the whole resource will be ignored.

This will work:
```java
@WebMethod
@POST
@Path("/login")
@ApiOperation(value = "Log in the user")
public void login(LoginParam loginParam) {
    userService.login(loginParam.username(), loginParam.password());
}
```
This won't:
```java
@WebMethod
@POST
@Path("/login")
@ApiOperation(value = "Log in the user")
public void login(LoginParam loginParam) {
	Function<Integer, Integer> lambda = (a) -> a * 2;
	userService.login(loginParam.username(), loginParam.password());
}
```

**Comment by webron** [comment]
This should not be an issue anymore. According to https://github.com/ronmamo/reflections/issues/15#issuecomment-56786388 it is fixed in 0.9.9 which is what we currently use.
