### ISSUE TITLE
ApiParam does not support converters

### ISSUE THREAD

**Issue by osbornk** [swagger-api/swagger-core#658]
I am using UUIDs extensively in both my response model as well as part of a REST URL. So, I created the following converter. In the API, I want to treat them as strings rather than the expanded Java object with leastSignificantBits and modeSignificantBits.

`
class Converter extends ModelConverter with BaseConverter {
  def read(cls: Class[_], typeMap: Map[String, String]): Option[Model] = None
  override def typeMap = Map("uuid" -> "string")
   override def ignoredClasses: Set[String] = Set("java.util.UUID")
}
`

This worked fine for the models. So, my ID field is described as a string. But for an ApiParam, this appears to have no effect. The UUID field is still represented as a full model rather than just a primitive string.

**Comment by olensmar** [comment]
@fehguy this looks like a swagger 1.2 related issue - does it apply to 2.0 as well?

**Comment by fehguy** [comment]
@olensmar correct, this is not a 2.0 issue--it should be fixed in 1.5.x, and in the develop_2.0 branch.
