### ISSUE TITLE
Support for scan.all.resources in jersey2

### ISSUE THREAD

**Issue by jonocodes** [swagger-api/swagger-core#659]
The java-jaxrs-no-annotations sample shows that scan.all.resources can auto scan the resources for controllers and methods. I am not able to do this using swagger-jersey2-jaxrs_2.10. Tonytam said support could be added, by taking a look here:

https://github.com/wordnik/swagger-core/blob/master/modules/swagger-jersey2-jaxrs/src/main/scala/com/wordnik/swagger/jersey/JerseyApiReader.scala#L53

https://github.com/wordnik/swagger-core/blob/master/modules/swagger-jaxrs/src/main/scala/com/wordnik/swagger/jaxrs/reader/BasicJaxrsReader.scala#L31

**Comment by fehguy** [comment]
moving to m3 as m2 is getting too big.

**Comment by webron** [comment]
#797 may help with this issue eventually.

**Comment by webron** [comment]
#961 now.

**Comment by webron** [comment]
This will be solved via #978.
