### ISSUE TITLE
Compilation Error for overriden read method in Custom SwaggerSchemaConverter

### ISSUE THREAD

**Issue by dhathris** [swagger-api/swagger-core#670]
I am using Swagger 1.3.7 and am writing a custom schema converter (RulesSwaggerConverter) by extending SwaggerSchemaConverter class and overriding the 'read' method.

Here is the read method:
	@Override
	public Option<Model> read(Class<?> cls, final Map<String, String> typeMap) 
	{
		Option<Model> models = super.read(cls, typeMap);
		
		    Class<?> clazz = cls;
		    
		    while ( clazz != null )
		    {
		    	for ( Field f : clazz.getDeclaredFields( ) )
		    	{
		    		try
		    		{
		    			if ( f.isAnnotationPresent( ApiModelProperty.class ) )
		    			{
		    				String access = f.getAnnotation( ApiModelProperty.class ).access( );
		    				if ( access.isEmpty( ) == false )
		    				{
		    					models.get( ).properties( ).remove( f.getName( ) );
		    				}
		    			}
		    		}
		    		catch ( SecurityException e )
		    		{
		    			e.printStackTrace();
		    			_logger.info("Swagger ran into security exception while reading field annotations for class"+clazz.getCanonicalName());
		    		}
		    	}
		    	for (Method m : clazz.getDeclaredMethods())
		    	{
		    		try
		    		{
		    			if ( m.isAnnotationPresent( ApiModelProperty.class ) )
		    			{
		    				if ( m.getAnnotation( ApiModelProperty.class ).access( ).isEmpty( ) == false )
		    				{
		    					if ( m.getName().startsWith("is"))
		    					{
		    						models.get( ).properties( ).remove( m.getName().substring(2).toLowerCase() );
		    					}
		    					else
		    					{
		    						Option<ModelProperty> result = models.get( ).properties( ).remove( m.getName() );
		    					}
		    				}
		    			}
		    		}
		    		catch ( SecurityException e )
		    		{
		    			e.printStackTrace();
		    			_logger.info("Swagger ran into security exception while reading method annotations for class"+clazz.getCanonicalName());
		    		}		    		
		    	}
		    	clazz = clazz.getSuperclass( );
		    }
		return models;
	}

Here are the compilation errors:

        The method read(Class<?>, Map<String,String>) of type RulesSwaggerConverter must override or implement a supertype method

error at Option<Model> models = super.read(cls, typeMap);
                             ^
	RulesSwaggerConverter.java:34:0::0 The method read(Class<?>, Map<String,String>) in the type SwaggerSchemaConverter is not applicable for the arguments (Class<capture#1-of ?>, Map<String,String>)

I have this same kind of code in another service project but there I do not get any compilation errors for the same kind of code. 

I am a newbie to Swagger and appreciate any help I can get in resolving this issue.....

**Comment by fehguy** [comment]
I believe you're getting the wrong `Option` type (maybe guava vs scala?).  Regardless these signatures have changed completely in swagger 1.5.x and are pure java.  Please take a look in the develop_2.0 branch
