### ISSUE TITLE
Faulty or incomplete handling of Jersey 2 @BeanParam annotation

### ISSUE THREAD

**Issue by jayzaw** [swagger-api/swagger-core#672]
In an effort to simplify and clean the code of the REST resources, I migrated my project to Jersey 2 and migrated swagger support accordingly. The reason for the effort was - amongst other reasons - to move detailed parameter definitions out of the REST resources and into the parameter classes. 

A complex input parameter can then be reused across several methods without having to specify the single attributes/fields of the input parameter classes every time. For this, I used:
@ApiParam in the method signature
followed by @BeanParam.

Results:
Jersey 2 supported the annotation according to the specification, as I could verify with client scripts.
Swagger 1.3.7 behaves differently, depending on whether you use QueryParam or FormParam in the input parameter class:
a) use of QueryParam annotation: swagger unfolds the fields correctly in the api-docs. However, the input parameter class itself is never mentioned. Which is bad, because it will prevent clients using the api-docs to understand the reuse of one parameter class across several methods. 
b) use of FormParam annotation: swagger does not recognize the input parameter class, nor will it unfold the parameter class down to its attributes.

I understand it would be helpful for you to get code examples but I cant find the time right now to mask our code in order for you to reproduce it. It should be fairly simple anyhow. Thanks for addressing that problem, it is a real showstopper... as for now we have to write our resource code with a lot of annotations which could otherwise be capsuled away.

**Comment by fehguy** [comment]
This is fixed in 1.5.2-M1
