### ISSUE TITLE
Support for collection type variables

### ISSUE THREAD

**Issue by sathyakumars** [swagger-api/swagger-core#679]
I am trying to document a java bean (model's) collection property. 
Tried adding annotation @ApiModelProperty(dataType="List[YourClassHere]"), But JSON produced is something like 
  "children": {
          "$ref": "List[MyClass]"
 }

Ideally Collection should be treated in the same way as List.

Refer - https://groups.google.com/forum/#!topic/swagger-swaggersocket/QAOGCYE_uIE for details.

**Comment by fehguy** [comment]
added support for overriding datatypes with collections with annotations, including:

```
@ApiModelProperty(dataType = "List[models.Children]")
private String children;
```

Will resolve to:

```
  {
    "id": "ModelWithModelPropertyOverrides",
    "properties": {
      "children": {
        "type": "array",
        "items": {
          "$ref": "Children"
        }
      }
    }
  }
```

and unwrap the inner types.
