### ISSUE TITLE
Swagger core 1.3.9 - can't seem to get authentication working.

### ISSUE THREAD

**Issue by lagrwilson** [swagger-api/swagger-core#685]
I want to be able to authenticate and set permissions for each api.

I have a list of about 20 permissions.  I want to be able to pass a bearer token in the header and have my authentication manage access to specific apis.

I upgraded to Swagger core, jaxrs and annotations to version 1.3.9.

I added the following lines to my api, and it won't even compile.

```java
@POST
@Timed
@Logged
@Produces({MediaType.APPLICATION_JSON})
@ApiEndpointPermissions({
        @ApiEndpointPermission(permission = PermissionStrings.ORGANIZATION_READ,
                permissionInstancePathParam = PathParamNames.ORGANIZATION_ID),
        @ApiEndpointPermission(permission = PermissionStrings.API_KEY_CREATE)
})
@ApiOperation(value = "Create Api Keys",
        consumes = MediaType.APPLICATION_JSON,
        authorizations = Array(new Authorization(value="oauth2",
                scopes = Array(
                        new AuthorizationScope(scope = "organization:read", description = "read organization"),
                        new AuthorizationScope(scope = "apikey:create", description = "create apiKey")
                ))))
@ApiResponses(value = {
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 403, message = "Credentials are required to access this resource")
})

public ApiKeyResponse createApiKey(@PathParam(PathParamNames.ORGANIZATION_ID) OrganizationId organizationId,
                                   @Context HttpServletRequest request) {

   // Do stuff here.
    return apiKeyResponse;
}
```

My index.html in my swaggerui resource changed to so that api-key goes on header rather than query.

I have several issues:

I've checked the how to embed oauth2 blog post and that post is really old, out of date and there don't seem to be equivalent functions. So I can't pass the api-key in the header with my bearer token and have swagger connect to get the proper permissions to exercise the apis.

Please provide some guidance on authenticating my apis within swagger's documentation.
I am using Java 1.8, dropwizard.

Thank you.
Lucille Wilson

I can't seem to add annotations to the apis to document the permissions each api is allowed.

I can't seem to hook up oath2 at all.

**Comment by webron** [comment]
Can't find anything specific that requires documentation. @lagrwilson if there's anything you feel is missing, please add a comment.
