### ISSUE TITLE
How to DRY ApiResponses Annotations

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-core#690]
I have integrated Swagger into our our new Java server app and am trying to come up with a way to eliminate redundant ApiResponse values contained within ApiResponses annotations. I have tried numerous techniques w/o luck and Java does not allow subclassing an annotation, but there must be some way. As an example, returning a 404 is quite common so I'd like a simple annotation such as @ApiResponseNotFound(optionalMessage="x not found").

 For a bonus, I'd love @ApiResponseList("400, 404") or equivalent such as @ApiResponses({@ApiResponseNotFound, @ApiResponseArgument})

@ApiResponses(@ApiResponse(code = 404, message = "not found"))

or

@ApiResponses({ @ApiResponses(@ApiResponse(code = 400, message = "invalid argument"), @ApiResponse(code = 404, message = "not found") })

**Comment by fehguy** [comment]
With 1.5.x-M1, you can now plug your own annotation processors.  While documentation needs to be written, you can follow the swagger-jersey2-jaxrs module as an example, allowing you to create a simple module which is loaded via SPI.

**Comment by vhochstein** [comment]
Unfortuenetly, I did not understand your described solution.
Has anyone a link where I can see how I may define my general Response Codes such as 500, 502 which apply for all operations and use them in each operation annotation to avoid the same block of documentation for every operation ?
Thanks a lot in advance.

**Comment by todd-richmond** [comment]
an example would definitely help. Our REST API has a global exception handler that we use to catch most issues and translate to HTTP codes in a general manner. As a result, the documented responses would all share the same docs. Ideally I'd like to create a base set of responses for each HTTP command (PUT, PATCH, GET, DELETE...) and then be able to add a few per-route additions

**Comment by codenozzle** [comment]
I came across this thread as I too need a way to define our Response Codes once, and use them across the API. We have several response codes (500, 400, 200, etc.) that we don't want to copy/paste all throughout the API. Yes, I could statically define the strings for the responses, but the annotations would still need to be duplicated. 

Has anyone figured this out? I don't think I followed what @fehguy was suggesting back in March. 

Thank you very much in advance! Love using Swagger!

**Comment by jlous** [comment]
If I understand correctly, the swagger json format already supports references that would do the trick. All we need is annotation support for it.  Or am I missing something?

**Comment by ishener** [comment]
+1

**Comment by rob-k** [comment]
+1 
Would be extremely helpful if you added the full spec of the Swagger object (or at least definitions, parameters and responses) to `@SwaggerDefinition`. Alternatively, it would be sufficient to give us an option to reference global definitions in `@ApiOperation`, `@ApiParam` etc. (e.g. with a field `ref`), as one can define the global definitions by subclassing `ReaderListener` as described here: http://swagger.io/customizing-your-auto-generated-swagger-definitions-in-1-5-x/

**Comment by rhamedy** [comment]
So it is possible to create an a `Custom annotation (i.e. GroupedApiResponses)` and annotate it with `@ApiResponses` and then use the custom annotations `GroupedAPiResponses` on endpoints and works just fine. I have posted an [answer in SO](https://stackoverflow.com/questions/48634417/how-to-dry-when-using-swagger-ui-and-the-apiresponses-annotations-with-java-spri) about the same. 

It saves a lots of repetitive code.
