### ISSUE TITLE
Support for well-known discovery url

### ISSUE THREAD

**Issue by gregmac** [swagger-api/swagger-core#70]
Right now, swagger-ui (or any Swagger-compliant client) has to know the exact URL of the swagger [ResourceListing](https://github.com/wordnik/swagger-core/wiki/Resource-Listing) in order to display the results. As far as I know, every implementation does this differently.

It would be nice if you could point swagger-ui at any swagger-compliant API base path (eg, `http://api.twitter.com`) and have it "just work", regardless of who implemented the server or what language/library it was done in.

So my proposal is we add to the spec that swagger-compliant APIs always have a `/swagger.spec` or something along those lines, which implements (or redirects to) the [ResourceListing](https://github.com/wordnik/swagger-core/wiki/Resource-Listing). 

TBD: the discovery URL(s) to use, which would work across all platforms

---

Note, I think this has value being part of the spec, rather than just swagger-ui, but this could also just be a convention that swagger-ui in particular uses. But my logic is if it takes off it would become a de-facto standard anyway, so why not put it in the spec.

**Comment by Splizard** [comment]
wouldn't  /.well-known/swagger.json be suitable for this?
