### ISSUE TITLE
Any progress on supporting Map containers?

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-core#702]
In issue 183 (https://github.com/wordnik/swagger-core/issues/183), there is mention of supporting a Map class, even if it only includes string keys (which would be fine for my application). Maps are quite common returns in JSON APIs to return hashes of misc attributes that don't have a fixed keyset and where a List or Set doesn't have random access

I've been browsing docs, blogs, code... and can't seem to find any other way to do this

We need both a way to include a Map in a Model

@ApiModelProperty(value = "extra attributes", response = OtherModel.class,
        responseContainer = "Map", responseKey = String.class) // OtherModel is a String or class
@JsonInclude(Include.ALWAYS)
public Map<String, OtherModel> attributes = new TreeMap<String, OtherModel>()

and a way to return Maps in ApiResponse (contrived example)
@GET
@Path("/{id}/attributes)
@ApiOperation(value = "get attributes for id", response = ...)
@public Map<String, OtherModel> getAttributes(@PathParam("id") String id) {}

**Comment by cppexpert** [comment]
So what's the solution to defining generic response types ?

**Comment by fehguy** [comment]
Hi @cppexpert this issue is about Maps, not generic response types (I'm assuming you mean java generics).  Please take a look at the open issues on generic response types, and open a new one if it's not covering your concerns
