### ISSUE TITLE
Does Swagger have a way to tie in to javadocs?

### ISSUE THREAD

**Issue by lagrwilson** [swagger-api/swagger-core#703]
For example when I run SwaggerUI and I got to one of my rest apis, I see DataType: com.mycompany.myObject

I'd like to set up Swagger so that com.mycompany.myObject is a hypertext link to javadoc.

**Comment by fehguy** [comment]
OK the original question was about tying into javadocs, and for that, please take a look at the integrations [here](https://github.com/swagger-api/swagger-spec/blob/master/README.md#java).  In addition, I believe you can now use Enunciate to generate swagger specs from javadocs.

For the other discussion, please open a new ticket if still relevant.
