### ISSUE TITLE
Upgrade Reflections package dependency to 0.9.9 from 0.9.9-RC1

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-core#707]
swagger-core depends on reflections 0.9.9-RC1 which itself depends on very out-of-date guava. However, excluding the dependencies (org.reflections.reflections and com.google.code.findbugs.jsr305) and importing 0.9.9 (as well as 0.9.9-RC2) directly causes runtime errors in a Jersey2 app

javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forPackage(Ljava/lang/String;[Ljava/lang/ClassLoader;)Ljava/util/Set;
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:393)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)

**Comment by sandipmangale** [comment]
I am facing same issue but one of project module needs reflections.0.9.8 jar,by which if i use this jar i am getting error for "ropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'scan' threw exception; nested exception is java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forPackage(Ljava/lang/String;[Ljava/lang/ClassLoader;)Ljava/util/Collection;"

**Comment by tarpdalton** [comment]
@sandipmangale Can the other project module use a newer version of reflections?
