### ISSUE TITLE
ApiModelProperty annotation 'required' default is too restrictive

### ISSUE THREAD

**Issue by LannyRipple** [swagger-api/swagger-core#708]
I'm using swagger-annotations in a play2 project.  Since ApiModelProperty's 'required' declaration defaults to false I'm having to annotate all my case classes to declare that everything is required (as is the common case when providing a response.  If everything is optional there isn't much point to responding.)

The reader that generates the swagger spec needs some way of being informed that it should assume all ApiModelProperties are either required=true or required=false and THEN apply whatever value the annotation informs.  This would allow only having to annotate the exceptions rather than everything.

Perhaps a new attribute in ApiModel could set the default for the indicated model.

At the very least make the default for 'required' in ApiModelProperty be true.

**Comment by erdbeerschnitzel** [comment]
I have exactly the same requirement and I want to ask if there is a any workaround or if this is possible with swagger 2.x?
