### ISSUE TITLE
Mongo ObjectId mapping issue in swagger mapper

### ISSUE THREAD

**Issue by mukulgupta2507** [swagger-api/swagger-core#720]
Hi,
Swagger is not able to map Mongo ObjectId correctly. My model class looks something like this:

public class Person implements Serializable {
    @org.jongo.marshall.jackson.oid.Id
    @ObjectId
    private String id;    // internal mongo db id
...

Swagger gives me response something like this:

```
  "_id": {
    "date": 1343026573000,
    "time": 1343026573000,
    "timestamp": 1343026573,
    "new": false,
    "timeSecond": 1343026573,
    "inc": 402653369,
    "machine": 808430687
  }
```

Instead I expect something like this:
       "_id": "406b5b3de4b8dde5f3000000"

I have seen already existing issues and tried following things but nothing seems to work.
1. Using @ApiModelProperty(dataType= "string") annotation of my id field but it's not working.
2. I tried using Overriding model in my bootstrap servlet but no help.

import com.wordnik.swagger.converter.*;

String jsonString = "{" +
            " \"_id\" : \"ObjectId\" "+
            "}";
        OverrideConverter converter = new OverrideConverter();
        converter.add(ObjectId.class.getName(), jsonString);
        ModelConverters.addConverter(converter, true);

But it's not working, may be I'm doing it wrong way.
1. I also tried using Typeconverter but didn't solve the issue:
   
   ``````
     ```
     TypeConverter typeConverter = new TypeConverter();
     typeConverter.add("_id", "string");
     ModelConverters.addConverter(typeConverter, true);
     ```
   ``````

Anyone who has faced the same issue and able to find any work around for this, please revert.

Thanks

**Comment by razonrus** [comment]
Try to use OperationFilter:
`
public class SwaggerOperationFilter : IOperationFilter
    {
        private readonly IEnumerable<string> actionsWithUpload = new[]
        {
            //add your upload actions here!
            nameof(TestController.Image),
            nameof(TestController.Import),
            nameof(TestController.AnswerImage),
            nameof(TestController.ImportResults),
            nameof(AccountController.Photo),
            nameof(UserController.Photo)
        };


        private readonly IEnumerable<string> objectIdIgnoreParameters = new[]
        {
            nameof(ObjectId.Timestamp),
            nameof(ObjectId.Machine),
            nameof(ObjectId.Pid),
            nameof(ObjectId.Increment),
            nameof(ObjectId.CreationTime)
        };

        public void Apply(Operation operation, OperationFilterContext context)
        {
            operation.Parameters = operation.Parameters.Where(x =>
                x.In != "query" || objectIdIgnoreParameters.Contains(x.Name) == false
            ).ToList();

            if (actionsWithUpload.Contains(operation.OperationId))
            {
                operation.Parameters.Add(new NonBodyParameter
                {
                    Name = "uploadedFile",
                    In = "formData",
                    Description = "Upload File",
                    Required = true,
                    Type = "file"
                });
                operation.Consumes.Add("multipart/form-data");
            }
        }
    }
`

and 

`                options.OperationFilter<SwaggerOperationFilter>();
`
