### ISSUE TITLE
@ApiModel has no way to hide properties on super classes and compile time enhanced classes

### ISSUE THREAD

**Issue by bthule** [swagger-api/swagger-core#730]
@ApiModelProperty allows hiding properties that in my model class, but there is no way to hide properties brought in by super classes or compile time enhanced classes.

For instance, Ebean enhances its model classes, and when they are used as a response Class, swagger-ui shows them with an extra property "_ebean_intercept (EntityBeanIntercept, optional)", and all of its properties and sub-properties.

**Comment by fehguy** [comment]
will investiagte for m2

**Comment by fehguy** [comment]
This has been fixed as of 1.5.2-M1

**Comment by aciganj** [comment]
I probably missed something, but how is it fixed? Is it now possible to write something like bthule suggested: 

`@ApiModel(hideProperties = {"uselessAnnoyingProperty", ...})?`

I can't seem to find that feature.

**Comment by fehguy** [comment]
@aciganj use `@ApiModelProperty(hidden=true)`

**Comment by aciganj** [comment]
You mean I should add a property of the same name as the one I want to hide and then use that annotation?  I guess that would work for private properties, but what about others? Is there a way to do it without adding properties or getters to subclass?

**Comment by bthule** [comment]
@aciganj Did you try @ApiModel(properties = {@ApModelProperty(name="uselessAnnoyingProperty", hidden=true), ...})

**Comment by fehguy** [comment]
I see @aciganj, I misunderstood your question.  Please try what @bthule suggested and if it doesn't work, open a new ticket.

**Comment by aciganj** [comment]
@bthule , @fehguy 
@ApiModel doesn't have the properties option, and other options don't seem useful for this purpose. I'll create a new issue

**Comment by r3215407** [comment]
it is a very important issus for me, Please reopen the issue.

**Comment by duckladydinh** [comment]
> it is a very important issus for me, Please reopen the issue.

Hi, I think the same and I tried implementing some workaround for it in this pull request https://github.com/swagger-api/swagger-core/pull/2996, but unfortunately, Swagger team does not allow open contribution, so it will never be official. But if you do not intend to use Swagger forever, maybe it will help for now.

**Comment by wenyi189** [comment]
It is 2019 now. And this is still not supported. I'm running into the exact problem where I have multiple sub types of `APIException`. And this `APIException` extends from `RuntimeException` from java. For example, if I have a subtype called `UnexpectedException` and it extends `APIException`, everything from parent class got picked up including the fields in `Throwable.class`. Very annoying and still couldn't find a way to get it working.

**Comment by thomasmchen** [comment]
I want to second @wenyi189 , having support for this case would be exceptionally beneficial for anyone using third party libraries or who cannot access parent classes to annotate fields they would like to ignore. This definitely seems within the scope of Swagger's problem space.

**Comment by MGZero** [comment]
Same thing here, I have a common resource class with some endpoints that should not come out in swagger for a particular project, but it should for others.  I can't currently do that without overriding the endpoint methods in the one project.  I shouldn't have to do that though just for documentation purposes.

**Comment by PankajAmbekar** [comment]
I think the 'hide-superclass-fields' feature would be a good value add for documentation

**Comment by max91** [comment]
The year 2020 was ending ... I'm amazed at how much time has passed since this feature was designated as very important. And just as amazed that she still does not exist. We urgently need to reopen this task.

For example, there is such a thing Spring HATEOAS. In which resources are sometimes superfluous are all sorts of different things. Which it would be nice not to show in the documentation for the request body. So, the swagger does not provide an opportunity to customize it. This is the answer to a six-year old question as an example. And in general, to be honest, how old is the swagger and how many problems it has. It clearly doesn't look like a java library =/

**Comment by jsiddharth** [comment]
This is a very important feature. From 2 aspects
Consider basic code below 
```
class Base {
    private int uselessparameter for docs ;
}
class Inherited extends Base {
    private int usefulparameter from docs;
}
```
Case 1)
Now Base may be in my control, so I should be able to use @APIIgnore and it should work.

Case 2)
Base is a library and I want to hide it when I extend Base in Inherited. Even then I should be allowed that.

**Comment by blackwood821** [comment]
I tried annotating my super class bean property with `@Schema(hidden = true)` which didn't work, but adding it to the getter method of that property got it to no longer show up in Swagger UI.
