### ISSUE TITLE
Add ElementType.ANNOTATION_TYPE or @inherited to Params

### ISSUE THREAD

**Issue by andreicristianpetcu** [swagger-api/swagger-core#736]
Hi! Please add ElementType.ANNOTATION_TYPE or @inherited to com.wordnik.swagger.annotations.ApiImplicitParam and to com.wordnik.swagger.annotations.ApiImplicitParams so we can reuse and extend the annotations.
I want to make my code more DRY by creating a annotation that looks like this:

``` java
@ApiImplicitParams({@ApiImplicitParam(name="version", dataType = "String", paramType = "header")}
@java.lang.annotation.Target({ElementType.TYPE_USE})
@java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
public @interface MyApiImplicitParams {
}
```

And have 

``` java
@MyApiImplicitParams
public void method1(){}
```

Instead of 

``` java
@ApiImplicitParams({@ApiImplicitParam(name="version", dataType = "String", paramType = "header")}
public void method1(){}
```

Do you think this can be done? Thank you!

**Comment by txt8888** [comment]
Would you show me how this is done?  I would like to do the exact same thing. 

The links did not work.  

here is the swagger version I have in my project:



        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.6.1</version>
        </dependency>

        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.6.1</version>
        </dependency>

**Comment by xuminglang** [comment]
> Would you show me how this is done? I would like to do the exact same thing.
> 
> The links did not work.
> 
> here is the swagger version I have in my project:
> 
> ```
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-swagger-ui</artifactId>
>         <version>2.6.1</version>
>     </dependency>
> 
>     <dependency>
>         <groupId>io.springfox</groupId>
>         <artifactId>springfox-swagger2</artifactId>
>         <version>2.6.1</version>
>     </dependency>
> ```
update version to 2.7.0 or higher. 
code like this

 @ApiImplicitParams({
 @ApiImplicitParam(
     name="Authorization",
     value = "Bearer token",
     dataType = "string", 
     paramType ="header")
})
public @interface ApiOauth2 {

}
