### ISSUE TITLE
Interpret parseable @PathParam and @QueryParam parameters as strings

### ISSUE THREAD

**Issue by qualidafial** [swagger-api/swagger-core#763]
Related to #609.

In the `@QueryParam` javadoc:
> The type `T` of the annotated parameter, field or property must either:
> 
> 1. Be a primitive type
> 2. Have a constructor that accepts a single `String` argument
> 3. Have a static method named `valueOf` or `fromString`that accepts a single `String` argument (see, for example, `Integer#valueOf(String)`
> 4. Be `List<T>`, `Set<T>` or `SortedSet<T>`, where `T` satisfies 2 or 3 above. The resulting collection is read-only.

The `@PathParam` documentation is similar.

In my resource:

    @GET @Path("/users/{userId}")
    User getUser(@PathParam("userId") Id<User> userId) { ... }

At runtime, Jersey is automatically taking the {userId} string from the path, calling `Id.fromString(String)`, and passing the returned object to my getUser method.

The current behavior generates the parameter with no `type` or `dataType` parameter, which causes Swagger-UI to fail to load, with an error in the console: `TypeError: Cannot read property 'toLowerCase' of undefined` on swagger.js line 664.

To align its behavior with JSR311 (and in the absence of any overriding Swagger annotations on the Id class itself), Swagger should generate such parameters with `{ "type": "string" }`.

**Comment by fehguy** [comment]
I think that supporting `toString()` for complex, Serializable value types is just too dangerous.  I suggest making your own annotation reader with Swagger's SPI support for parsing annotations.  Take a look at swagger-jersey2-jaxrs module for example.
