### ISSUE TITLE
Problems with Interface / Implementation separation

### ISSUE THREAD

**Issue by dibog** [swagger-api/swagger-core#773]
Hi, 
I try to separate my implementation in own classes and put all REST and SWAGGER annotations onto the Interfaces. But it seems that swagger-core won't pick up the annotations on the interfaces, he acts like he only looks at the implementation classes.

Here is a small example, that is a case where all works fine, because the REST and SWAGGER annotations are directly on the class:

<pre>
<code>
@Path("/data2")
@Api(value="/data2", description="Operations for ...")
@Produces(value={MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
public class DataResource2 {
    
    @GET
    @ApiOperation(
            value = "Returns all known data",
            response = Data.class,
            responseContainer = "List",
            tags="tag1, tag2"
            )
    public List<Data> getAvailableData() {
        return Collections.singletonList(new Data("data1"));
    }
}
</code>
</pre>

If I access the api-docs URL I get the following, which looks IMHO good:

<pre>
<code>
http://localhost:8080/apid-docs
{"apiVersion":"1.0.2","swaggerVersion":"1.2","apis":[{"path":"/data2","description":"Returns all known data"}]}
</code>
</pre>

But I would like to do this:

<pre>
<code>
@Path("/data")
@Api(value="/data", description="Operations for ...")
@Produces(value={MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
public interface DataResource {
    @GET
    @ApiOperation(value="Returns all known data")
    List<Data> getAvailableData();  
}

public class DataResourceImpl implements DataResource {
    @Override
    public List<Data> getAvailableData() {
        return Collections.singletonList(new Data("data1"));
    }
}
</code>
</pre>

but then I get this:

<pre><code>{"apiVersion":"1.0.2","swaggerVersion":"1.2"}</code></pre>

The REST call to /data works fine, though.

**Comment by Bvamsikrishna** [comment]
Hi,

I am working on swagger, swagger is picking up @RequestMapping annotations classes, but it is not picking up Rest Annotations like @Path why.
