### ISSUE TITLE
RestEasy - Fail taking @annotation data from interface.

### ISSUE THREAD

**Issue by fenoloco** [swagger-api/swagger-core#785]
Is common to use RestEasy with the methods annotated on the interface, but swagger does not take the information from, and the generated metadata are not correct.

Do you think that swagger could get the information from concrete classes or interfaces?

**Comment by skelkar9794** [comment]
I am working on integrating Swagger in SpringMVC application (it's not springboot application) , can you mention the steps in detail. Also, what is the use of <mvc:default-servlet handler> 
I am getting error that package io.swagger.annotations does not exist.
Kindly Help ! Bit Urgent !
Email ID : shaileshsk94@gmail.com

**Comment by webron** [comment]
If it's a Spring MVC project, then you're looking for [springfox](https://github.com/springfox/springfox).
