### ISSUE TITLE
[develop 2.0] Add full support for properties in annotations

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#801]
The `modules/annotations` project has annotation support which is back-compatible with 1.3.x--in the 2.0 spec there are many new options for constraints on fields, etc.  The annotations need to be updated to support these additional constraints without modifying the existing values.

**Comment by fehguy** [comment]
This has been done with #580

**Comment by zyro23** [comment]
just checking if i understood the approach correctly: if we want to express constraints for the swagger spec now but we are not using bean validation, we are expected to annotate the properties with jsr-303 anyway (just for swagger purposes)?

or is it still planned that swagger annotations will be added that cover the property-related information?

thank you, zyro

**Comment by fehguy** [comment]
The plan right now is to use the jsr-303 annotations.
