### ISSUE TITLE
[develop 2.0] ensure composition support is correct

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#802]
The support for `allOf` in model definitions is partially complete--need to ensure that the support follows the design of the 2.0 spec.

See here:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/CompositionTest.scala

**Comment by tomtit** [comment]
The CompositionTest unit test is enabled now and checks the presence of the 'allOf' entry in the model definition. What else should be done to resolve the issue?

**Comment by tomtit** [comment]
The first test for the Human class seems to be incorrect as it accepts Pet as a descendant of Human:
```
"Pet" : {
    "allOf" : [ {
        "$ref" : "#/definitions/Human"
    }
```
So, here is an improvement #987 for handling subtypes stricter.
