### ISSUE TITLE
[develop 2.0] consider removing scala as test dependency

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#804]
The tests are much easier to write with scala + scalatest, but it may be friendlier to developers to remove that and move to a pure java test framework.

**Comment by fehguy** [comment]
I'm not going to do this for M1, will push to M2 and reconsider then.

**Comment by martoe** [comment]
+1 for spock - a great tool for writing simple yet expressive tests

**Comment by t1** [comment]
Spoc is nice, but it requires Groovy, which is also fine, but poses the same downside as scalatest requiring Scala.

I recently stumbled over [assertj](http://joel-costigliola.github.io/assertj/index.html) and started to use it in some of my projects. It makes writing very good assertions really easy. IMHO, using this makes a bigger difference than using TestNG of JUnit.

**Comment by webron** [comment]
Well, we decided to go with TestNG for now.

**Comment by t1** [comment]
TestNG is great, and assertj augments it nicely :-)
