### ISSUE TITLE
[develop 2.0] allow configuration of pretty-printing swagger.json

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#810]
It is only a few bytes more to pretty-print a swagger spec:

https://github.com/swagger-api/swagger-ui/issues/746

**Comment by fehguy** [comment]
you can now configure via web.xml:

```xml
    <init-param>
      <param-name>swagger.pretty.print</param-name>
      <param-value>true</param-value>
    </init-param>
```

or via BeanConfig:
```java
config.setPrettyPrint(true)
```

**Comment by webron** [comment]
:+1:

What's the default value though?

**Comment by fehguy** [comment]
Thanks for asking--default is off (compact)
