### ISSUE TITLE
 java-jaxrs-no-annotations sample

### ISSUE THREAD

**Issue by elirazBusi** [swagger-api/swagger-core#812]
Hi, I'm observing  java-jaxrs-no-annotations sample and I can see two parts:
1.  set scan.all.resources parameter in the web.xml to true
  that enables scanning of all the resources in the package regardless there is @Api annotation 
2. inside the Bootstrap logic there is a way to add AuthorizationScope . what will add "authorizations" part to the json that is generated.

my question is : Is there any way to add in the code  api declarations (Api class) that will add "apis" part to the json *without* add the scan.all.resources parameter ? something similar to adding AuthorizationScope.. ?

My purpose is to document some of my resources without writing @Api annotation in the resource itself

Thank you!

**Comment by webron** [comment]
As far as I know, there isn't.

The way authorization is defined is unique, since there's no standard to authorization, unlike to REST that there are common standards like JAX-RS, Play and so on.

It wouldn't really make sense to do what you ask, as you may just as well end up writing the spec manually for that.

**Comment by elirazBusi** [comment]
Thanks for the response.
Actually what I'm trying to do is to make Swagger play with dynamic resources.
Do you know a way that would help me do that ?

**Comment by webron** [comment]
I understand that, but we pretty much tried covering in the mailing list. I won't have any magical suggestions here ;) We may need to add some more elaborate support for it.

**Comment by elirazBusi** [comment]
I see. thanks !

**Comment by fehguy** [comment]
@elirazBusi I'm going to close this, however I'd suggest looking into the develop_2.0 project where you can mutate the swagger object based on your own business logic.  So that will allow you to make it dynamic while still using the core library.
