### ISSUE TITLE
Swagger doesn't handle case classes with same name but different package in request and response types

### ISSUE THREAD

**Issue by vbeffa** [swagger-api/swagger-core#813]
If I have an `ApiImplicitParam` with `dataType = "com.foo.in.Something"` and an `ApiResponse` with `response = classOf[com.foo.out.Something]` the generated docs will use `out.Something` for both the parameter's data type as well as the response's data type. Renaming `out.Something` to `out.OutSomething` causes the docs to generate the expected types.

**Comment by webron** [comment]
Which version of swagger-core do you use? Also, which flavor (jaxrs, play, servlet, jersey, jersey2)?

**Comment by vbeffa** [comment]
Hm, I'm not sure if this is the right version but this is what we have in build.sbt (this is a Scala project):

`"com.gettyimages" %% "spray-swagger" % "0.5.0" excludeAll(ExclusionRule(organization = "io.spray")`

**Comment by webron** [comment]
Right, so you're using the spray-swagger library which takes advantage of swagger-core's annotations but does its own processing. For this, you need to open the issue on [spray-swagger's repository](https://github.com/gettyimages/spray-swagger).

**Comment by vbeffa** [comment]
OK thanks. Sorry for the confusion.

**Comment by webron** [comment]
No worries. I'm sure the spray-swagger author could help.
