### ISSUE TITLE
[develop 2.0] swagger.json output does not contain min/max for allowableValues="range[x,y]"

### ISSUE THREAD

**Issue by javatestcase** [swagger-api/swagger-core#818]
The current trunk produces the following output:

  "minimum":"0.0","maximum":"100.0"

when the following annotation is present:

  @ApiModelProperty(allowableValues="range[0,100]")

In the petstore example - http://petstore.swagger.wordnik.com/api/api-docs/pet

However I've been working with a test project

  https://github.com/javatestcase/RestEasy/tree/RestEasyVersion2

and the current swagger.json does not seem to have the same output.

Let me know if any additional information is required.

**Comment by javatestcase** [comment]
If I may throw a tangential note in as well... It seems like most major platforms (Spring, Jersey, RESTEasy at least) support Bean Validation 1.1 (JSR-349) at this point.  It's probably an outrageous amount of work, but it would be incredible if we could scan those validations.  That would make this request (and much of the @ApiModelProperty properties obsolete.

**Comment by webron** [comment]
It's planned, but probably not for the initial release of 1.5.

**Comment by javatestcase** [comment]
Thanks Ron.  I should have guessed.  You guys are doing amazing work here.

**Comment by webron** [comment]
Heh, thanks. It's really @fehguy. I'm just here for cheap entertainment.

JSRs 303/349 are great, but there are many extensions to it that people would probably expect to be supported (hibernate validator for example). It'll be done, just a matter of priorities and capacity.

**Comment by fehguy** [comment]
@webron is so generous... the 1.5 branch has a new pluggable mechanism for adding additional annotation support so making a module to support the different flavors of bean validations (like hibernate) without bringing in the dependencies to the core project.

**Comment by webron** [comment]
Closing this one in favor of #892. Please add relevant comments there if needed.

**Comment by hiejulia** [comment]
Same problem with `swagger-jersey2-jaxrs`. Any ideas how to fix ?
