### ISSUE TITLE
[develop_2.0] Scala tests fail on Windows due to EOL issues

### ISSUE THREAD

**Issue by martoe** [swagger-api/swagger-core#820]
Some Scala tests are sensitive to the platform-specific line endings:

When cloning the repo on Windows (with `core.autocrlf=false`, which is the default and IMO recommended), the following tests will fail:

	  should read a model with required params and description(CompositionTest): "{[
	  should read a model with composition(CompositionTest): "{[
	  should convert a model(ModelConverterTest): "{[
	  should read an interface(ModelConverterTest): "{[
	  should read an inherited interface(ModelConverterTest): "{[
	  should convert a scala case class with nested models(ScalaModelTest): "{[
	  should read an interface(ScalaModelTest): "{[
  
When manually switching the line endings of those three files **from LF to CRLF**, the tests succeed.

---

One the other hand, some tests suffer from the opposite issue: When cloning with `core.autocrlf=true`, the following tests will fail:

	  should convert serialize a header key model to yaml(AuthSerializationTest): "---[
	  should serialize a with string array PathParameter(ParameterSerializationTest): "---[
	  should serialize a HeaderParameter(ParameterSerializationTest): "---[
	  should serialize a BodyParameter to yaml(ParameterSerializationTest): "---[

When manually switching the line endings of those two files **from CRLF to LF**, the tests succeed...

**Comment by fehguy** [comment]
Fixed by #831
