### ISSUE TITLE
[develop_2.0] Scan property is missing from BeanConfig

### ISSUE THREAD

**Issue by iuliamiron** [swagger-api/swagger-core#823]
Without this property been set, the Scanner will not be instantiated ever and the resources will not be scanned.

**Comment by iuliamiron** [comment]
Now i got this exception:
org.osgi.service.blueprint.container.ComponentDefinitionException: At least one Setter method has to match the type of the Getter method for property scan

Because in setScan it's used primitive type boolean instead of Boolean.

**Comment by fehguy** [comment]
Yes thank you.  I've made this change and deployed the snapshot.
