### ISSUE TITLE
Allow using ApiOperation on fields in addition to methods

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-core#825]
Hi guys,

Could you please allow using `ApiOperation` on fields in addition to methods ?

The thing is that in Spray Framework (which now became Akka-Http) it's common to define routing table via defining nested constructions (e.g. http://spray.io/documentation/1.2.2/spray-routing/#longer-example).

It would be nice if I could put `ApiOperation` on val-s.

Currently I have to create bunch of dummy classes in separate package just to annotate them,

**Comment by webron** [comment]
Do you use spray-swagger?

**Comment by cppexpert** [comment]
Yes. I'll fork and modify `spray-swagger` most likely to search for annotations on Scala val-s (currently it checks only top-level methods), but for that I'd need `ApiOperation` to have additional target.

**Comment by webron** [comment]
Actually, you don't. 

You can create your own annotation, and annotate with with `@ApiOperation`, and that should work for introspection.

I don't think it's a right step for us to add a target on fields as well. It doesn't make sense to any of the frameworks Swagger-Core supports, nor any other Java frameworks. My concern is that it'll end up confusing the users.

**Comment by fehguy** [comment]
This won't work with the jaxrs implementation.  for other uses, it is very reasonable to annotate members.
