### ISSUE TITLE
Ability to override @ApiModelProperty name to support JSON vs Java naming

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-core#826]
Java conventions have fields named abCd while JSON prefers ab_cd. This is handled automatically in models using the Jackson annotation

@JsonNaming(LowerCaseWithUnderscoresStrategy.class)

Unfortunately ApiModelProperty doesn't seem to have a way to manually override the field name so the Swagger doc maintains the Java name even though clients see JSON.

Is there any work-around for this even if it requires manually mapping the name in @ApiModelProperty?

**Comment by fehguy** [comment]
@todd-richmond I believe you can use `@XmlElement(name="a")` to override any model property name.  I do agree that overriding the name in the annotation would be good.

**Comment by todd-richmond** [comment]
Thx!. Not sure how I missed it, but yes, @JsonProperty("ab_cd") does cause the API doc to work as expected. Would still be nice to enhance @ApiModelProperty though because @JsonProperty is unnecessary otherwise.

**Comment by fehguy** [comment]
I agree and will address this in 1.5.0-M2

**Comment by iquirino88** [comment]
Hi! Guys!
this feature was implemented?
When i see the page for the API the model schema of my body doesnt change.

expected: test_name but i got testName

my code is something like that.

@ApiModel(description = "My super duper Payload")
public class Test{
@ApiModelProperty(value = "Value for test name propertie")
@XmlElement(name = "test_name")
private String testName;
.
.
. rest of the code.

**Comment by webron** [comment]
M2 wasn't released yet...

**Comment by iquirino88** [comment]
Okay

**Comment by todd-richmond** [comment]
Based on an idea from https://github.com/swagger-api/swagger-core/issues/947#issuecomment-88052282, you can use the following line to set Swagger's Object Mapper to do camel case conversion 

        com.wordnik.swagger.util.Json.mapper().setPropertyNamingStrategy(
            PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES);

**Comment by JamesDunne** [comment]
Setting the property naming strategy on the `Json.mapper()` instances causes the _entire_ swagger.json file to be generated with this naming convention which fails for properties which want to have `readOnly` set (it will be incorrectly emitted as `read_only`) or `dataType`, for instance.

This swagger library needs a native way to specify property naming conventions to align with Jackson when it's used for the API implementation without interfering with the swagger internal properties emitted to swagger.json. I have an entire API defined with Jackson's SNAKE_CASE property naming convention but I have no way to tell swagger to respect this naming convention. I have far too many properties to consider manually specifying `@JsonProperty` on them all.

**Comment by fehguy** [comment]
@JamesDunne consider submitting a PR

**Comment by shiqicao** [comment]
@fehguy, your fix seems never merged to mater. I tried to add a 'name' property, but it doesn't work. Or I didn't specify 'name' correctly?

```
 "Foo": {                                                                                             
     "properties": {
       "object_type": {                                                                                           
               "name": "object_type",                                                                      
               "readOnly": true,                                                                             
               "type": "string"                                                                  
          }                                                                                                          
      },
 }
```

**Comment by WesternGun** [comment]
The case in swagger file is affected by config in Spring. In application.properties, if you set `spring.jackson.property-naming-strategy: SNAKE_CASE` or other values, it would affect the case of json properties in swagger file. So, in Java, it is better to use `@JsonNaming` on each class instead of configuring this key in properties file, if you don't want the overlapping effect. 

And I really think Swagger-api should have a separated, independent config other than that. This is not reliable.
