### ISSUE TITLE
Is there anyway to specify http header value for the swagger API provider 

### ISSUE THREAD

**Issue by TonyWuLihu** [swagger-api/swagger-core#828]
Hi 
   I'm wondering whether the swagger could support specify http header value in the generated swagger UI ?

**Comment by webron** [comment]
Assuming you're using JAX-RS, if you have a `@HeaderParam` it would translate to a header parameter. If not, you can use `@ApiImplicitParam` and mark it as a header parameter.

**Comment by TonyWuLihu** [comment]
Oh... Thx for the useful info !!
