### ISSUE TITLE
BeanConfig incorrectly processes resourcePackage in jersey2-jaxrs module

### ISSUE THREAD

**Issue by elw00d** [swagger-api/swagger-core#830]
There are 2 problems I have found:

##### 1. If specify inner package, outer will be scanned too.

See _com.wordnik.swagger.jaxrs.config.BeanConfig#classesFromContext_ code:

```java
val config = new ConfigurationBuilder().setUrls(ClasspathHelper.forPackage(resourcePackage)).setScanners(
      new TypeAnnotationsScanner(), new SubTypesScanner())
    new Reflections(config).getTypesAnnotatedWith(classOf[Api]).asScala.toList
```

_ClasspathHelper.forPackage(resourcePackage)_ returns urls list like this:

```
file:/C:/all/my-backend/project1/target/classes/
file:/C:/all/my-backend/utils/target/classes/
```

And then search will be applied to all classes in these paths. So we can't specify package explicitly.

##### 2. Multiple packages cannot be specified over the comma.

If use this syntax (described in wiki docs) scanner will print warning:

```
given scan urls are empty. set urls in the configuration
```

The cause of problem possibly is that _classesFromContext_ method is not called in this case. Swagger calls beanConfig.classes() method instead. And classes() always returns empty list.

**Comment by fehguy** [comment]
If you can provide a unit test demonstrating this, I'd be happy to look into it more.

**Comment by elw00d** [comment]
Try this please
https://github.com/elw00d/gretty-jersey-swagger-app/tree/master

**Comment by fehguy** [comment]
Added a filter to the `BeanConfig.java` class which will avoid this.

see https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/BeanConfig.java#L145
