### ISSUE TITLE
Fix model composition ordering

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#832]
The `CompositionTest.scala` has been disabled for M1 as it keeps flickering on and off.  Need to address the root cause of the property ordering for M2.

**Comment by tomtit** [comment]
Property ordering is not the issue here, the com.fasterxml.jackson.databind.node.ObjectNode.equals(Object) doesn't take property order into account. Expected JSON is incomplete: #966.

**Comment by tomtit** [comment]
The order of items in the second test (read a model with composition) is not the same.
Here is the JSON built for the Animal class:
{"Animal":{"properties":{**"type":{"type":"string"},"name":{"type":"string"}**},"discriminator":"type"},"Human":{"allOf":[{"$ref":"#/definitions/Animal"},{"properties":{"name":{"type":"string"},"type":{"type":"string"},"firstName":{"type":"string"},"lastName":{"type":"string"}}}]},"Pet":{"allOf":[{"$ref":"#/definitions/Animal"},{"required":["isDomestic","name","type"],"properties":{"type":{"type":"string","position":1,"description":"The pet type"},"name":{"type":"string","position":2,"description":"The name of the pet"},"isDomestic":{"type":"boolean","position":3,"default":false}}}]}}
Here is the one built from the string:
{"Animal":{"properties":{**"name":{"type":"string"},"type":{"type":"string"}**},"discriminator":"type"},"Human":{"allOf":[{"$ref":"#/definitions/Animal"},{"properties":{"name":{"type":"string"},"type":{"type":"string"},"firstName":{"type":"string"},"lastName":{"type":"string"}}}]},"Pet":{"allOf":[{"$ref":"#/definitions/Animal"},{"required":["isDomestic","name","type"],"properties":{"type":{"type":"string","position":1,"description":"The pet type"},"name":{"type":"string","position":2,"description":"The name of the pet"},"isDomestic":{"type":"boolean","position":3,"default":false}}}]}}
The Animal.type property is referenced from the JsonTypeInfo annotation. Perhaps it's the reason why the property's position has been changed. I'll investigate this.

So, I'm wondering do we need an additional unit test for checking property ordering?

**Comment by tomtit** [comment]
The `java.lang.Class.getDeclaredMethods()` is JVM dependent. My local JVM (java version "1.7.0_75", OpenJDK Runtime Environment (fedora-2.5.4.2.fc20-x86_64 u75-b13), OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode) lists the methods of the Animal interface as follows:

* public abstract void models.composition.Animal.setType(java.lang.String)
* public abstract java.lang.String models.composition.Animal.getName()
* public abstract void models.composition.Animal.setName(java.lang.String)
* public abstract java.lang.String models.composition.Animal.getType()

That is why the `type` property precedes the `name` in my previous comment regardless of the order of members in the source code.
So, there is nothing we can do about property ordering here.

**Comment by fehguy** [comment]
I believe we can enforce ordering with the `@JsonPropertyOrder` annotation.  Otherwise as @tomtit stated, method ordering is not guaranteed in the JVM.

**Comment by webron** [comment]
@fehguy - how would you like to proceed here?

**Comment by fehguy** [comment]
Support the property ordering via jackson, I believe that's the only reliable way to do it.

**Comment by webron** [comment]
@tomtit - can you have a look at that then?
