### ISSUE TITLE
add composition tests

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#835]
Tests from 1.3 that cover composition & subtypes should be migrated.

- [ ] converter/JacksonSubTypeModelTest.scala
- [ ] converter/ParentChildWithParentOverrideTest.scala
- [ ] converter/SubTypeModelTest.scala
- [ ] models/ModelInheritenceTest.scala

**Comment by MDoumin** [comment]
1. JacksonSubTypeModelTest.scala had already been removed, now it is in ComposiotionTest.scala, it should "read a model with composition"

2. ParentChildWithParentOverrideTest.scala looks very strange and does not do something comprehended. Has been decided to abandon it.

3. SubTypeModelTest.scala. Looks like a test for this feature has been implemented during working on #847, see ComposiotionTest.scala, it should "create a model".

4. ModelInheritenceTest.scala. The functional has to be tested has been removed. Specification is changed and there's no need to test such a term as "extends".

**Comment by fehguy** [comment]
Can we close this @MDoumin ?

**Comment by MDoumin** [comment]
@fehguy, yep, I think this can be closed.
