### ISSUE TITLE
Support interdependencies between query parameters

### ISSUE THREAD

**Issue by cwarny** [swagger-api/swagger-core#842]
It would be great to be able to specify interdependencies between query parameters. In my app, some query parameters become "required" only when some other query parameter is present. And when conditionally required parameters are missing when the conditions are met, the API fails. Of course I can have the API reply back that some required parameter is missing, but it would be great to have that built into Swagger.

**Comment by webron** [comment]
This is not really an issue to swagger-core but rather to swagger-spec.
