### ISSUE TITLE
Fix javadocs for annotations

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#849]
The 1.3.10 javadocs for the annotations didn't get included in the 1.5.0-M1 release. Will be fixed for M2.

**Comment by fehguy** [comment]
I have no idea how they weren't included in the build.  I do see them in the source code.

**Comment by webron** [comment]
Okay, that's a separate issue. I was referring to the fact that the javadocs themselves are not up to date, not that they are not included in the build.

**Comment by fehguy** [comment]
pushed in 1.5.1-SNAPSHOT
