### ISSUE TITLE
Good documentation on applying swagger inheritance in JAX-RS endpoints.

### ISSUE THREAD

**Issue by avalon12** [swagger-api/swagger-core#851]
Initially I expected swagger to pass class binding information to the Jackson deserializer, since swagger allows for annotating all required inheritance information to be supplied. It took me quite a while to figure out that I needed to add @JsonTypeInfo annotations...

It would have saved me days of my time if there would at least have been an example for polymorphism in the PetStore examples, or anything of sorts. Judging from the amount of unanswered questions on stackoverflow, and lack of examples/implementations I could find online, im not the only one. 

Is it an idea to add some basic inheritance to the petstore example? 

Suggestion for the petstore pet model:

```
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME, // Were binding by providing a name
    include = JsonTypeInfo.As.PROPERTY, // The name is provided in a property
    property = "type", // Property name is type
    visible = true // Retain the value of type after deserialisation
)
@JsonSubTypes({//Below, we define the names and the binding classes.
    @JsonSubTypes.Type(value = CatPet.class, name = "Cat"),
    @JsonSubTypes.Type(value = DogPet.class, name = "Dog")
})
@ApiModel(value = "Pet", subTypes = {DogPet.class, CatPet.class}, discriminator = "type")
public abstract class Pet {
```

**Comment by avalon12** [comment]
Also, does swagger generate these annotations when one does codegen of yaml -> JAX-RS?

**Comment by fehguy** [comment]
This was added by https://github.com/swagger-api/swagger-samples/pull/53

**Comment by avalon12** [comment]
Thanks a lot for adding this, and for all your hard work on this project.
