### ISSUE TITLE
BeanConfig values not present in swagger.json using ResourceConfig Application

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-core#855]
I upgraded to M1 and had to change from ApiConfig to BeanConfig (M1 sample is still using deprecated ApiConfig). My docs all build correctly after a bit of dataType cleanup, but none of the values set in BeanConfig other than setResourcePackage() are present when it is used to call setScan(true). This means my basePath (critical) and other license info aren't available

I am using a ResourceConfig derived Jersey+Jackson application on Jetty 9 which means there is no ServletContext available to call setAttribute("swagger", apiConfig) on

       BeanConfig beanConfig = new BeanConfig();

        beanConfig.setBasePath("/api");
        beanConfig.setContact("support@example.com");
        beanConfig.setDescription("REST API for example.com");
        beanConfig.setLicenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html");
        beanConfig.setResourcePackage(getClass().getPackage().getName());
        beanConfig.setTermsOfServiceUrl("http://www.example.com/resources/eula");
        beanConfig.setTitle("REST API");
        beanConfig.setVersion("1.0.0");
        beanConfig.setScan(true);
        packages("com.wordnik.swagger.jaxrs.json");
        packages("com.wordnik.swagger.jersey.listing");

**Comment by fehguy** [comment]
Right you are.  Fix + tests are coming.

**Comment by fehguy** [comment]
Hi, this has been fixed and pushed to 1.5.0-SNAPSHOT.  We'll probably put this in a point release, since it's pretty major.

**Comment by todd-richmond** [comment]
confirmed fixed. Would also be good to change the 1.5 JAX-RS example to the new API since ApiConfig is now deprecated

**Comment by fehguy** [comment]
Thanks.  Which sample are you referring to?

**Comment by todd-richmond** [comment]
These samples both use ApiInfo. ApiInfo was actually nice in that it only required a single constructor. Would be nice to allow BeanConfig to have a full constructor as well

https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jersey-jaxrs/src/main/java/com/wordnik/swagger/sample/Bootstrap.java

https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jaxrs/src/main/java/com/wordnik/swagger/sample/Bootstrap.java

**Comment by fehguy** [comment]
got it.  thank you

**Comment by fehguy** [comment]
I believe there's an even easier way to do this now:

```java
    Info info = new Info()
      .version("1.0.0")
      .title("Swagger Petstore")
      .contact(new Contact()
        .name("Wordnik API Team")
        .email("foo@bar.baz")
        .url("http://swagger.io"));
```

I'll update the samples to do this

**Comment by fehguy** [comment]
ok samples updated.  thanks again

**Comment by ipeluffo** [comment]
Excuse me @fehguy , but it seems that BeanConfig doesn't work properly using an Info object.

I took a look to the BeanConfig's source code and it seems it's overriding the Info object in the `classes` method (see line 175 in [BeanConfig](https://github.com/swagger-api/swagger-core/blob/08d82b38b6bac69cfe6e929f24daabfe8e99f17c/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/config/BeanConfig.java#L175)).

I'd appreciate it any help about this issue.

**Comment by codeturner** [comment]
@ipeluffo I ran into the same problem 2+ years later.  BeanConfig.setInfo doesn't do anything.  As a workaround, you can specify an Info object manually by setting the BeanConfig's swagger object directly.  For example:

```
  BeanConfig config = new BeanConfig();
  config.getSwagger().info(new Info()
      .version("1.0.0")
      .title("Swagger Petstore")
      .contact(new Contact()
        .name("Wordnik API Team")
        .email("foo@bar.baz")
        .url("http://swagger.io")));
  config.setResourcePackage(getClass().getPackage().getName());
  config.setScan();
```
