### ISSUE TITLE
JAX-RS Liberty Profile PassivationCapable Issue

### ISSUE THREAD

**Issue by lemoncolly** [swagger-api/swagger-core#863]
Seeing the following error when running JAX-RS on Liberty Profile 8.5.5.3, with CDI enabled:

[ERROR   ] PassivationCapable bean id is not unique: MANAGER#interface javax.enterprise.inject.spi.BeanManager#@javax.enterprise.inject.Any(),@javax.enterprise.inject.Default(), bean:BeanManager, Name:null, WebBeans Type:MANAGER, API Types:[javax.enterprise.inject.spi.BeanManager,java.lang.Object], Qualifiers:[javax.enterprise.inject.Any,javax.enterprise.inject.Default]
PassivationCapable bean id is not unique: MANAGER#interface javax.enterprise.inject.spi.BeanManager#@javax.enterprise.inject.Any(),@javax.enterprise.inject.Default(), bean:BeanManager, Name:null, WebBeans Type:MANAGER, API Types:[javax.enterprise.inject.spi.BeanManager,java.lang.Object], Qualifiers:[javax.enterprise.inject.Any,javax.enterprise.inject.Default]

Setup details:
- JAX-RS 1.1 (Java 1.7, IBM JDK)
- Liberty Profile 8.5.5.3
- Swagger 1.5.0-M1

Was previously running Swagger 1.3.5 without issue on the same server.

**Comment by webron** [comment]
This is going to be fun to troubleshoot.

Do you know which JAX-RS implementation you use? I assume it's Wink but it's worth checking.

Which specific Swagger-core dependency do you use? If your application includes more than one, provide the whole set of dependencies.

**Comment by lemoncolly** [comment]
Yeah, it's wink under the hood of IBM's stuff.

Do you mean version dependency? 1.5.0-M1 is the one I am testing here.

**Comment by webron** [comment]
No, I mean the actual dependency. You're not using swagger-core directly, you're probably using swagger-jaxrs. Just trying to make sure.

**Comment by lemoncolly** [comment]
Oh sorry....yes, using swagger-jaxrs.

<dependency>
	<groupId>com.wordnik</groupId>
	<artifactId>swagger-jaxrs</artifactId>
	<version>1.5.0-M1</version>
</dependency>

**Comment by webron** [comment]
I have a feeling you're going to have to open an issue with IBM's support (I assume you're using a commercial version of the Liberty Profile).

It looks like there's an issue with the combination of the CDI and the SPI mechanism. In swagger-core 1.5.x we utilize Java's native SPI mechanism to support plugin processing, making the basic code more modular and allowing easier extensions to it.

If you look at the error itself, it is not directly on the swagger-core classes but rather Java's SPI classes. Perhaps IBM can provide more information on that.

**Comment by lemoncolly** [comment]
That's what I was worried about.

We can get a PMR open and see what they have to say.

**Comment by webron** [comment]
@fehguy may have additional input here, but I think this is a platform-dependent issue and not one that's directly related with swagger-core. You *could* try turning off CDI support (if that's possible) only to test the loading of the swagger modules, though I'm not sure that would give us more useful information.

**Comment by lemoncolly** [comment]
Yeah, I can test it out. I can throw together a REST module with no dependency injection and then turn it off on LP.

**Comment by fehguy** [comment]
Well, let's first get the basic wink example working and committed to 1.5.x and then make things more complicated with CDI, etc.

**Comment by lemoncolly** [comment]
Did some playing around with this tonight.

Stripped everything right down, but still having issues.
Seeing a 404 when attempting to get the api docs.

Questions, when loading the Swagger specific classes in my application, I used to add them like so:

Set<Class<?>> swaggerClasses = new HashSet<Class<?>>();
        swaggerClasses.add(com.wordnik.swagger.jaxrs.listing.ApiListingResource.class);
        swaggerClasses.add(com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider.class);
        swaggerClasses.add(com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON.class);
        swaggerClasses.add(com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.class);

But now, i only see the ApiListingResource class. Is this expected? Seeing contradictory guides online. As is always the problem when moving major versions.

**Comment by webron** [comment]
You're getting 404 because there's  o longer api-docs. Swagger-core produces Swagger 2.0 specs which are formatted differently and are hosted as swagger.json at the context root of your application. 

The guides are not updated to the 1.5.X release yet.

**Comment by lemoncolly** [comment]
Ok, got it.

So, using Liberty Profile I am able to get Swagger working with a bare bones setup. Hurrah!
At least it isn't core wink/LP that is the issue. Just some other feature.

**Comment by webron** [comment]
Is that with CDI enabled or without?

**Comment by lemoncolly** [comment]
I just tested out with CDI enabled, and back to the original error now.

And that is without any actual dependency injection in my code itself.

**Comment by webron** [comment]
Well, that's good and bad news. Unfortunately, I think it's time to open the PMR. IBM may be able to tell us if we're doing something completely crazy or if they have a bug.

**Comment by lemoncolly** [comment]
Thanks guys.

I just opened a PMR with them. I will keep you posted on the findings.

**Comment by fehguy** [comment]
Hi, @lemoncolly any update on this?

**Comment by lemoncolly** [comment]
I am actively working the PMR with IBM. Getting there, slowly.

**Comment by webron** [comment]
Thanks for the update. Keep us posted. It may also help future users as well.

**Comment by webron** [comment]
@lemoncolly - another ping for progress :)

**Comment by fehguy** [comment]
Moving this to M3 due to inactivity

**Comment by lemoncolly** [comment]
Sorry guys......I was on vacation there.

Update. PMR was closed. We were able to fix the passivation issue, to then find a different one.
So IBM wanted that PMR closed.

I now need to go and create ANOTHER PMR to keep triaging this.

**Comment by webron** [comment]
@lemoncolly - anything? I'm inclined to close this issue unless there are more details from IBM about it.

**Comment by webron** [comment]
Closing it for now, please reopen if still relevant.

**Comment by lemoncolly** [comment]
@fehguy @webron 

Hey guys, just an FYI.

Looks like this was all ultimately down to CDI 1.0 (and it's feature as part of Liberty Profile).
We have been testing out the latest beta version of Liberty Profile, and CDI 1.2, and have been able to get the latest version of Swagger 2.0 working.

Keep up all your great work. Thanks!

**Comment by lemoncolly** [comment]
Also able to get it working with CDI 1.0.
Seems there is an issue with Google Guava.

I upgraded the version in my dependencies and was able to get it working successfully.

<dependency>
		  <groupId>com.google.guava</groupId>
		  <artifactId>guava</artifactId>
		  <version>16.0</version>
		</dependency>
