### ISSUE TITLE
add annotations for remote refs

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#864]

**Comment by fehguy** [comment]
Since this use case is a little weird, i'm moving to M3.

In general, there will be an update to `@ApiModel` annotation to allow you to say "ignore this model definition, look elsewhere".

**Comment by olensmar** [comment]
@fehguy I can add this if you let me know what you had in mind...

**Comment by fehguy** [comment]
The idea is, you already have a model being introspected by the service.  For example, you have a `User` definition which is referenced by an operation like `GET: /users/`.  Instead of relying on the introspection of the `User` pojo or java object, we want to expose the model as a reference.

Four use cases:

1) As an operation, instead of specifying a response class in an operation like this:

```
@ApiOperation(value = "Find users", 
  response = User.class,
  authorizations = @Authorization(value = "api_key")
)
```

we _might_ do something like this:

```
@ApiOperation(value = "Find users", 
  responseReference = "http://my.company.com#/definitions/User",
  authorizations = @Authorization(value = "api_key")
)
```

I'm not saying thats exactly the best annotation, but something along those lines.  Instead of drilling into `com.mycompany.User`, I will simply (blindly) insert the remote ref in there.

2) In a pojo, we should define an annotation that will override the parsing of the model properties.  This is much more simple, but necessary:

```
@ApiModel(remoteReference = "http://my.company.com#/definitions/User")
```

3) In the `@ApiResponse` annotation, which is optionally put in an operation annotation, we should support the remote reference:

```
@ApiResponse(code = 404, message = "User not found", remoteReference = "http://my.company.com#/definitions/Error") })
```

4) in a model property, an `@ApiModelProperty` should be annotated to point to a remote reference rather than introspect into a property:

```
@ApiModelProperty(value = "Order Status", remoteReference = "http://my.company.com#/definitions/OrderStatus")
public String getStatus() {
  return status;
}
```
so a complex definition can be returned rather than a simple text string.


Again, let's work on the names for the annotation changes (@webron will probably have some good input) but this

**Comment by webron** [comment]
1+3 are the same (even if in different annotations) as they both affect the `responses` of the operation.

We can also theoretically say that `@ApiParam` can have it, but that is relevant *only* to body parameters which do not require `@ApiParam` today (iirc).

The challenge is that `remoteReference` and `dataType`/`response` are mutually exclusive, so if the user gives a value to both... We basically need to well-define the behavior here. I'd say `remoteReference` would take precedence as it's less likely to fill that by mistake.

For completeness, we should add support for it in `@ApiImpicitParam` as well.

**Comment by olensmar** [comment]
looks fine by me - I agree that the reference should take precedence over a dataType/response...

How about naming the annotation "modelReference" ?

/Ole

**Comment by webron** [comment]
If we're going to allow remote refs for different things (responses, operations, models and parameters), it's probably better to keep a common name for them all.

**Comment by fehguy** [comment]
ok @webron please choose some names so we can add support and close this?

**Comment by webron** [comment]
`remoteDefinition` is explanatory for all of them.

**Comment by olensmar** [comment]
I think having "remote" in the name will be misleading since these could be local as well

**Comment by webron** [comment]
sure, 'overridingDefinition` would be bit long though but could work.

**Comment by fehguy** [comment]
`pointer`?  @webron please just pick one.

**Comment by olensmar** [comment]
jsonReference? modelReference? reference? Ron - release us! :-)

**Comment by webron** [comment]
sure, `reference`, let's go with that. the javadocs would need to explain what it means.

**Comment by olensmar** [comment]
thanks :-)

**Comment by olensmar** [comment]
ok - initial implementation for model references is in PR at https://github.com/swagger-api/swagger-core/pull/1113

**Comment by webron** [comment]
Done in develop_2.0.
