### ISSUE TITLE
How to can I set default values on class attributes?

### ISSUE THREAD

**Issue by murkein** [swagger-api/swagger-core#866]
I want to set default values on class attributes and that those values be showed on my swagger ui. It would be wonderfull...

it is my swagger dependence content:

    <com.wordnik.swagger-jersey2-jaxrs_2.11.version>1.3.10</com.wordnik.swagger-jersey2-jaxrs_2.11.version>
    <com.wordnik.swagger-core_2.11.version>1.3.10</com.wordnik.swagger-core_2.11.version>

    
    <dependency>
        <groupId>com.wordnik</groupId>
        <artifactId>swagger-jersey2-jaxrs_2.10</artifactId>
        <scope>compile</scope>
        <version>1.3.7</version>
        <exclusions>
            <exclusion>
                <groupId>org.glassfish.jersey.media</groupId>
                <artifactId>jersey-media-multipart</artifactId>
            </exclusion>
            <exclusion>
                <groupId>org.glassfish.jersey.containers</groupId>
                <artifactId>jersey-container-servlet-core</artifactId>
            </exclusion>
            
            <exclusion>
                <groupId>javax.ws.rs</groupId>
                <artifactId>jsr311-api</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

        <plugin>
            <groupId>com.github.kongchen</groupId>
            <artifactId>swagger-maven-plugin</artifactId>
            <version>2.3.2</version>
            <configuration>
                <apiSources>
                    <apiSource>
                        
                        <locations>com.package.api</locations>
                        <apiVersion>v1</apiVersion>
                        <basePath>http://localhost:8088</basePath>
                        

                        
                        
                        <apiInfo>
                            <title>Project API Docs</title>
                            <description>Documentación de servicios RESTful para Project</description>
                        </apiInfo>
                        <overridingModels>/swagger-overriding-models.json</overridingModels>
                        

                        
                        <outputTemplate>templates/strapdown.html.mustache</outputTemplate>
                        <mustacheFileRoot>${basedir}/templates/</mustacheFileRoot>
                        <outputPath>${basedir}/generated/document.html</outputPath>
                        

                        
                        <swaggerDirectory>${project.build.directory}/${project.build.finalName}/api/1.0/</swaggerDirectory>
                        <swaggerUIDocBasePath>http://localhost:8088/api/1.0</swaggerUIDocBasePath>
                        <useOutputFlatStructure>false</useOutputFlatStructure>
                        
                        
                    </apiSource>
                </apiSources>

            </configuration>
            <executions>
                <execution>
                    <phase>compile</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

**Comment by webron** [comment]
This will probably be implemented through #819 (but would require swagger-core 1.5.X).

**Comment by webron** [comment]
@murkein - have you tested it?

**Comment by fehguy** [comment]
please reopen if needed.
