### ISSUE TITLE
Java List<T> parameters with generic parameter which is inner class are incorrectly parsed by ModelPropertyParser

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-core#867]
Just found that generic parameters which are inner classes are incorrectly parsed by [ModelPropertyParser](https://github.com/swagger-api/swagger-core/blob/a770366706d0989bfb9e805733a406377c8e49a4/modules/swagger-core/src/main/scala/com/wordnik/swagger/converter/ModelPropertyParser.scala#L208-L227).

Problem lies in following patter matcher

```scala
 val ComplexTypeMatcher = "([a-zA-Z]*)\\[([a-zA-Z\\.\\-0-9_]*)\\].*".r
```

which chokes on `paramType` like `java.util.List<com.crazyrabbit.service.json.timesheet.TimesheetProjectTaskRolesService$RoleRecord>`

as result listing json has following reference `"$ref": "List[RoleRecord]"` for which later it can't find class `RoleRecord` therefore it's not visible in model UI of swagger-ui

**Comment by todd-richmond** [comment]
I've seen the same issue with inner classes - good catch

**Comment by cppexpert** [comment]
Guys (@webron @fehguy), would it possible to merge it and push update to Maven Repo ? Thanks!

**Comment by cppexpert** [comment]
Guys (@webron @fehguy), would it possible to merge it and push update to Maven Repo ? Thanks!

**Comment by fehguy** [comment]
I'm going to review this over the next couple days to make sure we're not regressing anywhere.

**Comment by webron** [comment]
Closing as we're not going to release 1.3.13. Please upgrade to the latest version.
