### ISSUE TITLE
path params need enum support

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#875]
In 1.5.1-M1 the path parameter does not allow for enums.  It should

**Comment by zyro23** [comment]
nice! any chances for a 1.5.3-M1 containing the enum support?
thanks, zyro

**Comment by webron** [comment]
M2 is fairly close. About a week or two.

**Comment by zyro23** [comment]
ok. will have to wait then. or are maybe snapshots published somewhere? thanks for the quick reply! zyro

**Comment by webron** [comment]
You can always build a snapshot of develop_2.0 locally ;)
