### ISSUE TITLE
Swagger 2.0 doesn't generate Specs properly if we include httpMethod in @ApiOperation

### ISSUE THREAD

**Issue by arun0009** [swagger-api/swagger-core#879]
Swagger specs aren't hooking parameters, responses if we include httpMethod & showing up empty resources but works fine if we remove it from the @ApiOperation annotation.

Note: This is with swagger-jersey2-jaxrs version 1.5.1-M1

**Comment by fehguy** [comment]
The httpMethod was not doing a case insensitive match, and GET would cause empty operation types.
