### ISSUE TITLE
Supplying beanConfig.setResourcePackage a comma separated package list fails

### ISSUE THREAD

**Issue by simon-temple** [swagger-api/swagger-core#881]
Jetty 8, Jersey 2.6 and swagger-jersey2-jaxrs_2.10 1.3.12

Wiki states: "If there's more than one package, it can be a list of comma-separated packages."

I have pre-existing JAX-RS resources from a variety of packages in my server so I wish to pass a list of resource packages to swagger but this causes a runtime URL error.

My current work around is to specify our company package: "com.acme" but the reflection finds and scans a lot more JAR files than are really necessary.

**Comment by fehguy** [comment]
This is a defect for 1.5.0-M2
