### ISSUE TITLE
BeanConfig.java fields values are ignored by ApiListingResource.java

### ISSUE THREAD

**Issue by Helmsdown** [swagger-api/swagger-core#882]
I have the following code in my JAX-RS ResourceConfig class:

```
        BeanConfig swaggerBeanConfig = new BeanConfig();
        swaggerBeanConfig.setResourcePackage("com.intuit.developer.platform.api.v4.resources");
        swaggerBeanConfig.setTitle("the title");
        swaggerBeanConfig.setHost("https://api.intuit.com");
        swaggerBeanConfig.setBasePath("/quickbooks/v4");
        swaggerBeanConfig.setScan(true);

```

This should cause my /swagger.json endpoint (from ApiListingResource.java) to show this information (e.g. host and basepath)

However, ApiListingResource.java ignores this information in the scan() method:

``` java
protected synchronized void scan (Application app, ServletConfig sc) {
    Scanner scanner = ScannerFactory.getScanner();
    LOGGER.debug("using scanner " + scanner);

    if(scanner != null) {
      SwaggerSerializers.setPrettyPrint(scanner.getPrettyPrint());

      Set<Class<?>> classes = null;
      if (scanner instanceof JaxrsScanner) {
        JaxrsScanner jaxrsScanner = (JaxrsScanner)scanner;
        classes = jaxrsScanner.classesFromContext(app, sc);
      }
      else {
        /*WE GET INTO HERE, BeanConfig returns the set of classes to read from based 
         *on what I configured it to do in the above CodeSnippet
         */
        classes = scanner.classes();
      }
      if(classes != null) {
        /*At this point we construct a NEW Reader, which blows away the swagger.info data we had stored    
         * in the BeanConfig's Reader. The result is that the paths and models that are annotated   
         * show up in the /swagger.json endpoint result. But things like hostname and basePath DO NOT
        */
        Reader reader = new Reader((Swagger)context.getAttribute("swagger"));
        Swagger swagger = reader.read(classes);
        context.setAttribute("swagger", swagger);
        WebXMLReader xmlReader = (WebXMLReader)context.getAttribute("reader");
        if(xmlReader != null) {
          xmlReader.read(swagger);
        }
      }
    }
    initialized = true;
  }
```
Basically, ApiListingResource completely ignores values I set in BeanConfig.

**Comment by Helmsdown** [comment]
FYI: I am working off the develop_2.0 branch.

**Comment by fehguy** [comment]
This should be fixed now in https://github.com/swagger-api/swagger-core/blob/30a06854d972420106fc85b0450a7a9a778dc894/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/listing/ApiListingResource.java

BeanConfig and WebXMLReader are not meant to be used together.  Can you please retry from develop_2.0 and report back?

**Comment by webron** [comment]
@Helmsdown - any updates on it?

**Comment by Helmsdown** [comment]
I haven't re-synced my fork yet. Waiting on my other pull requests to be merged in before I resync.

**Comment by webron** [comment]
Which one is that?

**Comment by Helmsdown** [comment]
Swagger Codegen pull requests (didn't mean to imply that they were swagger-core pull requests, I forgot this issue was for swagger-core)
https://github.com/swagger-api/swagger-codegen/pull/417
https://github.com/swagger-api/swagger-codegen/pull/374
https://github.com/swagger-api/swagger-codegen/pull/366
https://github.com/swagger-api/swagger-codegen/pull/365

I can change my maven target to something more up to date than "com.wordnik:swagger-jaxrs:1.5.0-M1"
to try any updated version of BeanConfig and ApiListingResource.

**Comment by fehguy** [comment]
Hi @Helmsdown can you please sync with develop_2.0 for swagger-core?  They shouldn't affect the codegen PRs, which i'm getting to now.

**Comment by Helmsdown** [comment]
Sorry I was probably confusing. I am not using a fork of swagger-core. I am using "com.wordnik:swagger-jaxrs:1.5.0-M1". What maven target should I use to try out the new BeanConfig/ApiListingResource functionality.

**Comment by fehguy** [comment]
please use 1.5.3-M1-SNAPSHOT now

**Comment by Helmsdown** [comment]
1.5.3-M1-SNAPSHOT solves the problem. I think we can consider this issue closed.
