### ISSUE TITLE
Documentation for "body" is shown twice (build 1.3.19)

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-core#885]
I have following method

```java
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Path("addTimesheetEntry")
    @ApiOperation(httpMethod = "POST", response = ListResponse.TimesheetEntriesResponse.class, value = "Creates new project timesheet entries and returns ALL entries for specified timesheet")
    @ApiImplicitParams({
            @ApiImplicitParam(name = "token", required = true, dataType = "string", paramType = "query", value = "API token"),
            @ApiImplicitParam(name = "body", paramType = "body", value = "input parameters in json form")
    })
    public ListResponse<TimesheetEntryWire> addTimesheetEntry(AddTimesheetEntriesRequest request) {}
```

Despite the fact that body param named as "body" as sepcified in Swagger Doc body parameter is shown twice in generated documentation

![screenshot](http://i.snag.gy/pEuTx.jpg)

**Comment by webron** [comment]
There's no swagger-core 1.3.19...

**Comment by cppexpert** [comment]
I was in old version of "develop_scala-2.11" branch. I'll test with the latest version soon.

**Comment by fehguy** [comment]
Hi, you have a body param in your function (without annotations) and an implicit param.  That's why you see two body params.

You should annotate your method argument instead of using the ApiImplicitParam.  Those are used when there is no variable to annotate.

**Comment by cppexpert** [comment]
Oh I had no idea. Thanks!
