### ISSUE TITLE
JavaDoc compilation fails with JDK8

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-core#886]
JavaDoc compilation fails with JDK8 with multiple errors

`Invalid “self-closing element not allowed”`

Additional parameter `-Xdoclint:none` should be specified in main `pom.xml`

https://github.com/swagger-api/swagger-core/commit/33b7708ceab4b0e7819edbd32bef257d2823b8c9

**Comment by fehguy** [comment]
@webron looks like the errors are because of more strict parsing of javadoc tags.  The `@return` value needs to be set for each method or it'll fail to build on java8.  Can you please help with this one?

**Comment by webron** [comment]
I've made some fixes (not pushed yet) that caused a the javadocs generation to fail. However, I didn't encounter the issue @cppexpert encountered. How did you run the javadoc compilation? Perhaps I need to test something else that I hadn't.

**Comment by fehguy** [comment]
Make sure you have Java 8 and run mvn install

**Comment by webron** [comment]
I have. Not getting the error the OP did. Got other javadoc-related errors which I'd fixed, but definitely not `Invalid “self-closing element not allowed”`.

**Comment by cppexpert** [comment]
JFYI I've got that error under JDK8u40 under Windows 7 64bit.

**Comment by fehguy** [comment]
I fixed the self-closing element issues. https://github.com/swagger-api/swagger-core/commit/e11fb9553b273a522a1d22c38fa73ebcc62e8cb5

**Comment by webron** [comment]
@fehguy - duh, thanks for the update. I'll push the rest of the fixes.
