### ISSUE TITLE
Inherited from interface @GET @POST @DELETE annotations are not detected

### ISSUE THREAD

**Issue by sgri** [swagger-api/swagger-core#89]
When a JAX-RS method type annotation (@GET @POST @DELETE) is defined on interface, then Swagger displays error "SwaggerOperation list is missing httpMethod"

This is an artificial limitation, because Jersey detects the above annotations properly. This limitation forces the implementing class to duplicate annotations.

@Path("/library")
@Produces("application/json")
public interface LibraryResource{
    @GET
     List<Book> list();
}

**Comment by PabloEzequiel** [comment]
I have the same problem... did you find the the solution?

**Comment by webron** [comment]
@PabloEzequiel - are you using a version that was released in 2012? If so, it's time to upgrade.
