### ISSUE TITLE
range parameters in annotations not processed

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#892]
the `allowableValues` does not translate range into `minimum`, `maximum`, `exclusiveMinimum`, `exclusiveMaximum`

**Comment by webron** [comment]
I assume we'll follow the mathematical standard where `[` and `]` are inclusive and `(` and `)` are exclusive.

**Comment by webron** [comment]
I've duplicated it in #957, but since the discussion is there, I'll close this one.
