### ISSUE TITLE
Overriding javax.json.JsonObject

### ISSUE THREAD

**Issue by pradeepg-telsiz** [swagger-api/swagger-core#896]
I am passing javax.json.JsonObject as a parameter as shown below 

```java
    @POST
    @Path("{path1}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "bla bla", notes = "-----", response = Response.class)
    @ApiResponses(value = { @ApiResponse(code = 400, message = ""),
            @ApiResponse(code = 404, message = "") })
 public Response someFunction1(
            @ApiParam(value = "bla bla", required = true) JsonObject jsonParam,
            @ApiParam(value = "some_value", required = true, allowableValues = "a,b,c") @PathParam("someParam") String someParam)
```       
     
```java            
   @POST
    @Path("{path1}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(value = "bla bla", notes = "-----", response = Response.class)
    @ApiResponses(value = { @ApiResponse(code = 400, message = ""),
            @ApiResponse(code = 404, message = "") })           
 public Response someFunction2(
            @ApiParam(value = "bla bla", required = true) JsonObject jsonParam,
            @ApiParam(value = "some_value", required = true) @PathParam("someParam") String someParam) 
```

 But each JsonObject has different schema.  I am assuming that the Overing Models  (as discussed in https://github.com/swagger-api/swagger-core/wiki/overriding-models) will not work in this scenario because it will add same schema to all JsonObject occurrence. 

How can I handle this? In UI, I can see DataType as javax.json.JsonObject but I want to show proper Json schema. 

Thanks

**Comment by fehguy** [comment]
Hi for now, this scenario is simply not supported.  There is an open ticket #899 which could solve it for you.  Please watch that ticket.

In the mean time, you can ignore this property by removing the annotations and use the `@ApiImplicitParam`, which will let you specify the datatype for each operation.  Note the datatype needs to be fully qualified with the pacakge, and cannot be an inner type.

Please reopen if that's not clear.
