### ISSUE TITLE
Samples to migrate to 1.5.0-M3

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#898]
- [x] java-resteasy
- [x] java-resteasy-spring
- [ ] ~~no-server~~ <= move to `swagger-spec`
- [x] java-jersey-spring
- [ ] scala-play2
- [ ] java-play2
- [ ] java-grails2
- [ ] java-jaxrs-no-annotations
- [x] java-jaxrs-wink
- [x] java-jersey2-guice
- [x] java-mule
- [ ] scala-oauth-authorization-server
- [ ] scala-servlet

**Comment by webron** [comment]
- play2 samples are on hold
- scala samples should be migrated to the scala repo? (@fehguy)
- no annotations samples can't be done until #978
- grails sample is a bit more messy
