### ISSUE TITLE
Refactor Tags support

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#903]
The way tags are implemented now can lead to conflicts in definitions. There should be two major changes - 

- Tag descriptions should be defined at the Swagger() level. While this is possible now, the samples should reflect it.
- At the `@Api` and `@ApiOperation` levels, tags should have a name only, and could be simplified to strings instead of an annotation. Allowing the definition of the description at this level is confusing as it is not clear which one takes in case of a conflict. It should also be clear what happens when a `tags` property appears in both the `@Api` and `@ApiOperation`. It can either be added or overridden, I's suggest the latter.

This should be done as soon as possible as this is a behavioral change so we'd want to impact as little users as possible.

**Comment by webron** [comment]
It should also be clear to users what's taken as `tags` for operations in case no tags is provided (I assume it's not empty), and possibly provide the logic to completely remove the tags for a given operation if that's the case (probably tags={}).

**Comment by fehguy** [comment]
@webron all of this is possible but introduces some other considerations.

1) This would require someone to define all tags in a bootstrap to add to the `Swagger` instance.  Are you sure you want to require that?

2) What do we do if we encounter a tag string that is not defined at bootstrap?  Meaning, as it stands, we can construct tags at the top level without bootstrap

we can change the signature for tags now, but shouldn't after M2 is released.  So chime in and we can make it so.

**Comment by webron** [comment]
Neither points is relevant. Tags are not *required* to be defined at the top. They need to be defined at the top only if a user wants to add a description to a given tag. 

So for 1) - it would require that when wanting to add a description. We *could* use the @Api annotation instead, but that invites possible conflicts. For 2) we don't need to do anything. Just add the tag to the operation itself.

**Comment by fehguy** [comment]
ok got it.  so we should remove tags from `@Api`, change to String[] for `@ApiOperation` and enable setting tags w/descriptions + external docs outside the controllers.  Finally if a tag appears in the `@ApiOperation` we add it w/o a tag.  LMK if this isn't true.

**Comment by webron** [comment]
I'd say for ease-of-use for developers, we keep the tags in `@Api` which all operations under it will inherit, and those can be overridden within an individual `@ApiOperation` tags. More complicated to implement, but I believe that would be the common use case instead of having to repeat it.

Yes to String[].

>  Finally if a tag appears in the @ApiOperation we add it w/o a tag. 

I assume you mean here we add it w/o description, and then yes. But we only need to add it to the operation's tags. No need for complicated mechanism to add it to the top-level tags. It's perfectly acceptable if that list is partial. Should simplify the logic here.

**Comment by fehguy** [comment]
Renaming this ticket.  It's not improving, it's refactoring.

**Comment by webron** [comment]
@fehguy - shouldn't the `@Tag` annotation be removed now?

**Comment by fehguy** [comment]
@webron isn't this what we want?

https://github.com/swagger-api/swagger-core/blob/be191a6b7d452d19e44b174a4535eb82faa5675a/modules/swagger-jaxrs/src/test/scala/resources/Resource841.java#L13

https://github.com/swagger-api/swagger-core/blob/be191a6b7d452d19e44b174a4535eb82faa5675a/modules/swagger-jaxrs/src/test/scala/resources/Resource841.java#L20

**Comment by webron** [comment]
It is, which is why I think https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/Tag.java should be deleted, no? Or is it used elsewhere?

**Comment by fehguy** [comment]
Go ahead and delete it in a PR, if it builds, it's not needed.

**Comment by webron** [comment]
:+1:

**Comment by webron** [comment]
#938 is ready, build seems to pass.
