### ISSUE TITLE
TypeOverrider should work for path parameters as well

### ISSUE THREAD

**Issue by devshorts** [swagger-api/swagger-core#913]
Per the conversation https://groups.google.com/forum/#!topic/swagger-swaggersocket/YdQOP_rdKZU

I have a value class wrapper on top of primitives, something like

```
public class FirstName{
  public String value;

  protected FirstName(String val){
    value = val;
  }

  public static FirstName valueOf(String val){
    return new FirstName(val);
  }
}
```

And I am using this value wrapper as a path parameter in jersey 2 with a custom param converter so that I can do

```
@Path("/{firstName}")
@GET
@ApiOperation(value = "Gets the first name")
public Response getFirstName(
        @PathParam("firstName") FirstName firstName) {
     //... 
}
```

I'd like to be able to alias that path parameter as the primitive type that it actually is, since passing it a string will wrap it into a FirstName type.

What I've done in the meantime is set up two converters.

I have an override converter that sets the json property of firstName to be

```
{  
   "id":"FirstName",
   "properties":{  
      "value":{  
         "type":"string"
      }
   }
}
```

And I have a type converter that sets the id of `FirstName` to a `String` which gives me model object parents that look like this:

```
{
  "id": "Person",
  "properties": {
    "firstName": {
      "type": "string"
    }
  }
}
```

So any object that contains first name will now show it as a string.  However, I'd like for the entire type of `FirstName` to basically never exist, it should only ever show up as a `string` since thats what its aliased as.

**Comment by tomtit** [comment]
@devshorts  could you try the version1.5.3-M2-SNAPSHOT? The issue should be fixed there.

**Comment by webron** [comment]
Closing it assuming it is fixed. Please reopen if needed.

**Comment by btiernay** [comment]
Is there any chance this could be backport to 1.3?

**Comment by fehguy** [comment]
I'm sure it can technically be done, but we deprecated 1.3.x well over a year ago, so we don't plan on making changes to it.
