### ISSUE TITLE
Java Doc with Swagger

### ISSUE THREAD

**Issue by vishakMetric** [swagger-api/swagger-core#916]
Hi Swagger Team,

   1] Is it possible to have Swagger comments and the java comments to be same. Can we relate them in anyway.
2] Does Swagger provide internationalization support. If yes how can we achieve it.

Regards
Vishak

**Comment by webron** [comment]
swagger-core is a runtime library and does not have access to javadocs which are available only at compile time. Some compile time libraries such as Enunciate or the swagger-maven-plugin may be able to utilize the javadocs to generate the documentation.

There's currently no integrated support for internationalization. Feel free to follow this [issue](https://github.com/swagger-api/swagger-spec/issues/274) to see progress.
