### ISSUE TITLE
Override queryparam datatype

### ISSUE THREAD

**Issue by swarupe04** [swagger-api/swagger-core#917]
on ui it shows the queryparam datatype as CsvIntegerParameter instead of string. 
By overriding the model with converter, it doesn't seem to help in case of query param for deserialization.

If I compare to the joda datetime, it seems to be able to show it as "string". Any idea how I can achieve similarly for a custom datatype object for a query param.

I'm looking for a way where I can this below type: to be "string"
```
{
name: "testInts",
description: "test ints",
required: false,
type: "CsvIntegerParameter",
paramType: "query",
allowMultiple: false
},
```
from my bean param:
```java
@ApiModelProperty(value = "test ints", dataType = "string")
    @ApiParam(value = "test ints")
    @QueryParam("testInts")
    @JsonProperty("testInts")
    private CsvIntegerParameter testInts;
```
In post body of Model schema, it shows correctly as expected

Here's how I had done override
 String jsonString = "{" +
                "  \"id\": \"CsvIntegerParameter\"," +
                "  \"properties\": {" +
                "    \"values\": {" +
                "      \"required\": false," +
                "      \"description\": \"comma separated ints\"," +
                "      \"notes\": \"Add any notes you like here\"," +
                "      \"type\": \"string\"," +
                "      \"format\": \"int32\"" +
                "    }" +
                "  }" +
                "}";
        OverrideConverter converter = new OverrideConverter();
        converter.add("reporting.model.CsvIntegerParameter", jsonString);

**Comment by fehguy** [comment]
What version of swagger-core are you talking about?  1.3.x or 1.5.x?

**Comment by fehguy** [comment]
Looking at your sample, I suggest that you add a typeMapping:

```
override def typeMap = Map("csvintegerparameter" -> "integer")
```

or something like that.

**Comment by swarupe04** [comment]
using 1.3.12

Please can u put that in Java..not sure where it should be going.. Is it where the OverrideConverter in instantiated?

**Comment by fehguy** [comment]
If you're not using scala, can you upgrade to 1.5.x-M1?  It's pure java and the override syntax should be much cleaner.

**Comment by swarupe04** [comment]
Hi,
I upgraded the core to 1.5.2-M1.
Please can you provide the java version of the override converter.

Thanks

**Comment by fehguy** [comment]
Please look at the tests in the develop_2.0 branch. For instance:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-core/src/test/scala/com/wordnik/swagger/model/override/SamplePropertyConverter.java

**Comment by swarupe04** [comment]
Hi,
Just noticed that in my pom,
com.wordnik:swagger-jersey2-jaxrs_2.10:jar:1.3.12 still has dependency to
swagger core 1.3.

Is there a newer version of swagger-jersey2 which I couldn't find in maven
repo? Or should I be explicitly excluding it in pom?

[INFO] +- com.wordnik:swagger-jersey2-jaxrs_2.10:jar:1.3.12:compile
[INFO] |  \- com.wordnik:swagger-jaxrs_2.10:jar:1.3.12:compile
[INFO] |     +- com.wordnik:swagger-core_2.10:jar:1.3.12:compile
[INFO] |     |  +- org.json4s:json4s-ext_2.10:jar:3.2.11:compile
[INFO] |     |  |  \- org.joda:joda-convert:jar:1.6:compile
[INFO] |     |  +- org.json4s:json4s-native_2.10:jar:3.2.11:compile
[INFO] |     |  |  \- org.json4s:json4s-core_2.10:jar:3.2.11:compile
[INFO] |     |  |     +- org.json4s:json4s-ast_2.10:jar:3.2.11:compile
[INFO] |     |  |     \- org.scala-lang:scalap:jar:2.10.0:compile
[INFO] |     |  |        \- org.scala-lang:scala-compiler:jar:2.10.0:compile
[INFO] |     |  |           \-
org.scala-lang:scala-reflect:jar:2.10.0:compile
[INFO] |     |  \- org.json4s:json4s-jackson_2.10:jar:3.2.11:compile
[INFO] |     \- org.reflections:reflections:jar:0.9.9:compile
[INFO] |        \- com.google.code.findbugs:annotations:jar:2.0.1:compile

**Comment by fehguy** [comment]
Take a look at the POM here:

https://github.com/swagger-api/swagger-core/tree/develop_2.0/samples/java-jersey2

**Comment by swarupe04** [comment]
Hi,
After upgrading to 1.5, getting Http 400 error on /api-docs.
and response msg as: {"code":404,"message":"Not Found","detail":null}


   1. Request URL:
   http://localhost:8080/reporting/api-docs
   2. Request Method:
   GET
   3. Status Code:
   400 Bad Request


Appreciate any help, in debugging this issue

Here's my info

in my jersey2 application, had..

public class ReportingApplication extends ResourceConfig {

    public ReportingApplication() {
     BeanConfig beanConfig = new BeanConfig();
        beanConfig.setTitle("Reporting REST API(TM)");
        beanConfig.setDescription("A set of API's for the Reporting
subsystem");
        beanConfig.setLicenseUrl("http://corp.com/");
        beanConfig.setLicense("Contact For Licensing Terms");
        beanConfig.setVersion("1.0.2");

beanConfig.setBasePath(ReportingConfig.config().getProperty("swagger.api.basepath"));
        beanConfig.setResourcePackage("com.reporting.resource");
        beanConfig.setScan(true);
ModelConverters.getInstance().addConverter(new SamplePropertyConverter());


in pom
<dependency>
      <groupId>com.wordnik</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      
      <version>1.5.2-M1</version>
    </dependency>
    <dependency>
      <groupId>com.wordnik</groupId>
      <artifactId>swagger-core</artifactId>
      <version>1.5.2-M1</version>

Thanks

**Comment by fehguy** [comment]
it should live on /swagger.json not /api-docs now

**Comment by swarupe04** [comment]
Hmm..tried that..same error

**Comment by fehguy** [comment]
I strongly suggest walking through the samples in the develop_2.0 branch and seeing how the configuration works, and how it's different from your app.

**Comment by swarupe04** [comment]
Hi,

I got it working after registering, register(ApiListingResource.class); in
Jersey2 Application. In docs, it didn't explicitly mention this step for
BeanConfig option:
https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup#using-the-application-class

Next, it looks I need to upgrade even the swagger ui to 2.0. Is my
understanding correct. We're currently using swagger ui 1.0, and we seem to
having issue with displaying the UI content.

Thanks,

**Comment by swarupe04** [comment]
Hi,

After all the upgrade on ui side too, I'm noticing issue with parameters as
null from swagger.json which is causing the resolver.js to break for ui


   - /v1/report/{id:[0-9]+}/result:
   {
      - get: null,
      - post:
      {},
      - put: null,
      - delete: null,
      - options: null,
      - patch: null,
      - parameters: null
      },


I've compared to petstore and don't see this type of rest verb
("parameters" at this level). Could it be issue with 1.5 swagger core?

Thanks,

**Comment by fehguy** [comment]
Hi, looks to me like there's a jackson issue.  There should be no null values exposed in swagger.

I am guessing that you have multiple `@Providers` trying to write the JSON.  Are you using a web.xml?  If so, can you look at the differences between yours and this?

https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jersey2/src/main/webapp/WEB-INF/web.xml

**Comment by swarupe04** [comment]
Hi,
We're not using web.xml, and yes we're using multiple @Provider registered
in Application, but not @Providers.

I can try suppressing fields with null values from response.

Thanks,

**Comment by fehguy** [comment]
Please make sure you add this provider directly:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/listing/SwaggerSerializers.java

Then the swagger model should be serialized correctly.

**Comment by swarupe04** [comment]
Works now after adding the SwaggerSerializers.

Appreciate your quick responses.

Thanks,

**Comment by swarupe04** [comment]
Hi,

I've noticed that when we've the @BeanParam parameter, the APIParam are not
getting considered with the newer version 1.5. This was fine when we were
on 1.3

I'm not sure where to create the issue for this, but I feel this is a
critical issue for upgrade for us since we use BeanParam mostly on our apis.

Thanks

**Comment by fehguy** [comment]
Are you sure you are adding the jersey2 module?  Bean params are supported and well tested.

**Comment by swarupe04** [comment]
Hi,
Checking the swagger module swagger-jersey2-jaxrs, looks like I'm probably
missing registering
public class SwaggerJersey2Jaxrs extends AbstractSwaggerExtension implements
SwaggerExtension {

Currently I'm only registering
register(SwaggerSerializers.class); register(ApiListingResource.class);

Do u think, I could simply register this class?

**Comment by fehguy** [comment]
If it's included in your webapp's classpath, it should register automatically.  Can you please share the libraries that are pulled into your app?  At least the swagger ones.

**Comment by swarupe04** [comment]
swagger-annotations-1.5.2-M1.jar
swagger-jaxrs-1.5.2-M1.jar
swagger-models-1.5.2-M1.jar
swagger-core-1.5.2-M1.jar
swagger-jersey2-jaxrs-1.5.2-M1.jar

**Comment by swarupe04** [comment]
In your web.xml link
https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jersey2/src/main/webapp/WEB-INF/web.xml

noticed that it's registering lot more..just wandering if we need those for
non-web.xml or is it implicit?

..
com.wordnik.swagger.jersey.listing.JerseyApiDeclarationProvider,
com.wordnik.swagger.jersey.listing.JerseyResourceListingProvider
..
<servlet-name>Jersey2Config</servlet-name>

<servlet-class>com.wordnik.swagger.jersey.config.JerseyJaxrsConfig</servlet-class>

**Comment by swarupe04** [comment]
Something definitely seems to be missing. Even the path param is not
getting converted appropriately

I had path with /v1/report/{report_type:[aA-zZ]+}:

where report_type is path key

when i execute the api call on swagger ui, it doesn't replace report_type
to default value

All this was fine when we were on 1.3.x

**Comment by webron** [comment]
@swarupe04 - can you please upgrade to the latest (1.5.1-M2) and see if the issue still exists?

**Comment by swarupe04** [comment]
I have been on 1.5.1-M2 for a while now. I just tested the @defaultValue
case, and it does seem to consider the default value, but doesn't show the
enum values for the Enum Type.

As a workaround, I've been setting the APIParam allowable values to get
that working, but as you know this is redundant maintenance in my case.

**Comment by webron** [comment]
What type of parameter is the enum? It's possible it's solved in the develop_2.0 branch.

**Comment by swarupe04** [comment]
It was pathParam...Let me try a query param, which was also an issue.

**Comment by webron** [comment]
For path params - https://github.com/swagger-api/swagger-core/issues/875.

**Comment by swarupe04** [comment]
OK. Got it. It has same issue with queryParam with 1.5.1-M2. Only reason I
consider these as critical bugs since this feature was fine in 1.3.

But it's fine for now, since I've a workaround. I'll wait for the next
release.

**Comment by webron** [comment]
In that case, can we close this issue and open a new one for the enums?

**Comment by swarupe04** [comment]
Sounds good. thanks

**Comment by webron** [comment]
Could you open the issue on the enums? It's better when the user that encounters it opens the issue ;) Thanks!

**Comment by swarupe04** [comment]
https://github.com/swagger-api/swagger-core/issues/1019
