### ISSUE TITLE
Migrate play module

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#918]
Using the swagger-scala module, need to migrate play support into a new module.  This is probably best done in a new artifact, and outside of swagger-core.

**Comment by seantbrady** [comment]
+1

**Comment by joantune** [comment]
+1 please, if possible, take into account  https://github.com/swagger-api/swagger-core/issues/900

**Comment by jcranky** [comment]
Since the integration will be reworked, it would be nice if more information like path and query params could be automatically extracted, so that we don't have to use ```jax-rs```'s ```PathParam``` and ```QueryParam``` annotations. This is information is already available in the ```routes``` file.

**Comment by alpeb** [comment]
Also it seems models inside scala objects aren't properly supported.
I modified `/samples/scala-play2/app/models/Pet.scala` (using tag `v.1.3.12`) like this:
```
object Models {
  @ApiModel("Pet")
  case class Pet(
    @(ApiModelProperty @field)(position=1, value="id")id: Long,
    @(ApiModelProperty @field)(position=2)category: Category,
    @(ApiModelProperty @field)(position=3)name: String,
    @(ApiModelProperty @field)(position=4)photoUrls: List[String],
    @(ApiModelProperty @field)(position=5)tags: List[Tag],
    @(ApiModelProperty @field)(position=6)status: String
  )

  @ApiModel("Tag")
  case class Tag (
    @(ApiModelProperty @field)(position=1)id: Long,
    @(ApiModelProperty @field)(position=2)name: String)
}
```

And the `Tag` model disappeared from the json in `http://localhost:9000/api-docs/pet`

Can someone please confirm this is indeed a bug?

**Comment by fehguy** [comment]
@alpeb if you're looking at how this works in the 1.5.x version, you should look at the [swagger-scala-module](https://github.com/swagger-api/swagger-scala-module) which will support scala

**Comment by alpeb** [comment]
Are there any instructions on how to use https://github.com/swagger-api/swagger-scala-module ? All I see there is the `SwaggerScalaModelConverter` class.

I would love to make this work now, that's why I was trying with the `v.1.3.12` tag.

**Comment by fehguy** [comment]
I'll get that updated on the project, please track https://github.com/swagger-api/swagger-scala-module/issues/2

**Comment by fehguy** [comment]
ok @alpeb please take a look at the homepage for the scala module for instructions on adding it.

**Comment by alpeb** [comment]
Thanks @fehguy . I added the `swagger-scala-module` dependency into the pet store, but it doesn't build because it depends on `swagger-play2`, whose Jackson dependencies conflict with the swagger scala module. So it looks like Play support is nowhere to be found yet in 1.5?

**Comment by fehguy** [comment]
That's what this ticket is for. Scala support is in but play support is in process. Sorry, I read your comment as a general scala question not play specific

**Comment by emersonbarros** [comment]
+1

**Comment by kanuku** [comment]
+1

**Comment by orangefiredragon** [comment]
+1

**Comment by anovstrup** [comment]
Any progress on this? I might be able to help out, particularly if it means resolving some of the issues @jcranky mentioned.

**Comment by cdparra** [comment]
+1

**Comment by laguiz** [comment]
+1

**Comment by cdparra** [comment]
In the meantime, maybe [this project](https://github.com/matiwinnetou/swagger-play24) can be of help. Will try it later Today and report if it works or not with play 2.4.x

**Comment by laguiz** [comment]
@cdparra  +1

**Comment by cdparra** [comment]
Juste tested [matiwinnetou/swagger-play24](https://github.com/matiwinnetou/swagger-play24). Working just fine.

**Comment by webron** [comment]
Since we're not going to release a new version of 1.3 (for Play or otherwise), I'll link the existing Play issues here so we can make sure those are taken care of as part of the migration.

**Comment by webron** [comment]
- [ ] #944 - Swagger & java play 2 class loading problems 1.3.12
- [ ] #956 - Play Framework binders

**Comment by fcappi** [comment]
+1

**Comment by zcsongor** [comment]
+1

**Comment by ctoomey** [comment]
+1

**Comment by sebigavril** [comment]
+1

**Comment by alex-vas** [comment]
+1

**Comment by ctoomey** [comment]
Is this likely to get done any time soon, and if not, how could those of us watching potentially help get it done?

**Comment by webron** [comment]
We'd like to push it forward just like any other project, but as you can imagine, we have limited resources (and not necessarily enough experience with Play). The best way to push it forward is work together on the solution.

**Comment by anovstrup** [comment]
Is there a github repository for the new module yet? Perhaps if the existing code were migrated to its own project, the community could start working on it?

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-play

**Comment by ctoomey** [comment]
From a quick look at the repo it looks like it's the Swagger 1.2 Play module, i.e., nothing's been started yet on the migration to Swagger 2 using the swagger-scala module. Is this accurate?

I think what's needed to get folks to start helping out is an outline of the work that needs to be done, an updated build setup (Build.scala or whatever), and perhaps a stab at stubbing out the envisioned traits and classes.

**Comment by fehguy** [comment]
Hi @ctolkmit I'm going to close this out and ask that we continue in the swagger-play repo.  There are multiple efforts on Play! integration from outside the core swagger team that I'm trying to see about combining forces with.

**Comment by slustbader** [comment]
@fehguy Is there an issue or something we can follow in the swagger-play repo?

**Comment by fehguy** [comment]
@slustbader please see here:  https://github.com/swagger-api/swagger-play/issues/13
