### ISSUE TITLE
regexes in path parameters don't build correct swagger schema

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-core#922]
It is valid to have regex patters in JAXRS servers but currently they are passed as-is to the swagger.json.  Need to properly parse them.

**Comment by whitlockjc** [comment]
This originally came in from [swagger-ui/issues/1054](https://github.com/swagger-api/swagger-ui/issues/1054).

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-core/commit/994b475e3bc02e5f57a3fc90275979d942804f1c
