### ISSUE TITLE
1.5.3 Null Exception in BeanConfig.configure (Jersey2)

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-core#927]
I upgraded to 1.5.3 from 1.5.2 and am getting a NPE in BeanConfig.java. Code is using Jersey2 ResourceConfig and crashes when extracting swagger.json

            // configure Swagger
        BeanConfig beanConfig = new BeanConfig();

        beanConfig.setBasePath("/api");
        beanConfig.setContact("support@example.com");
        beanConfig.setDescription("REST API);
        beanConfig.setLicenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html");
        beanConfig.setResourcePackage("com.example");
        beanConfig.setTermsOfServiceUrl("https://www.example.com/resources/eula");
        beanConfig.setTitle("REST API");
        beanConfig.setVersion("1.0.0");
        beanConfig.setScan(true);
        packages("com.wordnik.swagger.jaxrs.json");
        packages("com.wordnik.swagger.jersey.listing");

    at com.wordnik.swagger.jaxrs.config.BeanConfig.configure(BeanConfig.java:198)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.scan(ApiListingResource.java:52)
	at com.wordnik.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by fehguy** [comment]
Are you using web.xml?

**Comment by todd-richmond** [comment]
Only enough web.xml to load the cross-origin filter and some other security constraints - the only swagger config is the lines of code above

**Comment by todd-richmond** [comment]
Also, the samples are still using old Swagger config - I took that code from help you gave me when I first migrated to 1.5

**Comment by fehguy** [comment]
Could you please share the web.xml?  It shouldn't be going into this block of code without a valid `swagger` object.

**Comment by todd-richmond** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.1" xmlns="http://xmlns.jcp.org/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
    http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
  metadata-complete="true">
  <display-name>MapR</display-name>
  <filter>
    <filter-name>gzip</filter-name>
    <filter-class>org.eclipse.jetty.servlets.GzipFilter</filter-class>
    <init-param>
      <param-name>mimeTypes</param-name>
      <param-value>application/javascript,application/json,text/css,text/html,text/plain</param-value>
    </init-param>
    <init-param>
      <param-name>minGzipSize</param-name>
      <param-value>1500</param-value>
    </init-param>
  </filter>
  <filter>
    <filter-name>shiro</filter-name>
    <filter-class>org.apache.shiro.web.servlet.ShiroFilter</filter-class>
  </filter>
  <filter>
    <filter-name>mapr-installer</filter-name>
    <filter-class>com.mapr.installer.controller.RequestFilter</filter-class>
  </filter>
  <filter-mapping>
    <filter-name>gzip</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>shiro</filter-name>
    <url-pattern>/api/*</url-pattern>
    <dispatcher>ERROR</dispatcher>
    <dispatcher>FORWARD</dispatcher>
    <dispatcher>INCLUDE</dispatcher>
    <dispatcher>REQUEST</dispatcher>
      </filter-mapping>
  <filter-mapping>
    <filter-name>mapr-installer</filter-name>
     <url-pattern>/api/*</url-pattern>
  </filter-mapping>
  <listener>
    <listener-class>org.apache.shiro.web.env.EnvironmentLoaderListener</listener-class>
    </listener>
  <servlet>
    <servlet-name>mapr-installer</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
      <param-name>javax.ws.rs.Application</param-name>
      <param-value>com.mapr.installer.InstallerApplication</param-value>
    </init-param>
  </servlet>
  <servlet>
    <servlet-name>default</servlet-name>
    <servlet-class>org.eclipse.jetty.servlet.DefaultServlet</servlet-class>
    <init-param>
      <param-name>dirAllowed</param-name>
      <param-value>false</param-value>
    </init-param>
  </servlet>
  <servlet-mapping>
    <servlet-name>mapr-installer</servlet-name>
    <url-pattern>/api/*</url-pattern>
    </servlet-mapping>
</web-app>

**Comment by fehguy** [comment]
I don't see anything wrong in here.  I'm guessing this will help:

https://github.com/swagger-api/swagger-core/tree/develop_2.0/samples/java-jaxrs-no-webxml

Specifically, my guess is we're missing these lines in your bootstrap:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jaxrs-no-webxml/src/main/java/com/wordnik/swagger/sample/Bootstrap.java#L17-L19

```java
  public void init(ServletConfig config) throws ServletException {
    ReflectiveJaxrsScanner scanner = new ReflectiveJaxrsScanner();
    scanner.setResourcePackage("com.wordnik.swagger.sample.resource");
    ScannerFactory.setScanner(scanner);
    Info info = new Info()
      .title("Swagger Sample App")
///
```

**Comment by todd-richmond** [comment]
Looks like BeanConfig does not work in 1.5.3 even after adding ReflectiveJaxrsScanner code (which wasn't required in 1.5.2). However, using ReflectiveJaxrsScanner after separately setting the Swagger Info context attribute does.

The only issue is that ServletContext is not available for an ResourceConfig derived Application constructor so I had to move setting the context value out to main (for embedded jetty). Ideally there would be some way to set the Swagger+Info class beyond just through ServletContext.setAttribute

**Comment by nkoterba** [comment]
@todd-richmond Hi...I'm trying to do exactly what you describe in this post:

- Jersey 2
- Swagger: 1.5.3-M1
- EmbeddedJetty (during development) but deployed on standalone Jetty/Tomcat in production

I followed the quickstart guide: https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5

And used the sections for an `Application`-based setup.

However, I never got a `swagger.json` or `swagger.yaml` file.

I then tried to follow the vague description above.

In my EmbeddedJetty.js `main` function I have this code:
```java
context.setContextPath("/snap");
		context.setParentLoaderPriority(true);

		_server.setHandler(context);

		Info info = new Info()
			.title("Swagger Sample App")
			.description("This is a sample server Petstore server.  You can find out more about Swagger " +
				"at <a href=\"http://swagger.io\">http://swagger.io</a> or on irc.freenode.net, #swagger.  For this sample, " +
				"you can use the api key \"special-key\" to test the authorization filters")
			.termsOfService("http://helloreverb.com/terms/")
			.contact(new Contact()
				.email("apiteam@swagger.io"))
			.license(new License()
				.name("Apache 2.0")
				.url("http://www.apache.org/licenses/LICENSE-2.0.html"));

		Swagger swagger = new Swagger().info(info);
		swagger.securityDefinition("api_key", new ApiKeyAuthDefinition("api_key", In.HEADER));
		swagger.securityDefinition("petstore_auth",
			new OAuth2Definition()
				.implicit("http://petstore.swagger.io/api/oauth/dialog")
				.scope("read:pets", "read your pets")
				.scope("write:pets", "modify pets in your account"));
		swagger.tag(new Tag()
			.name("pet")
			.description("Everything about your Pets")
			.externalDocs(new ExternalDocs("Find out more", "http://swagger.io")));
		swagger.tag(new Tag()
			.name("store")
			.description("Access to Petstore orders"));
		swagger.tag(new Tag()
			.name("user")
			.description("Operations about user")
			.externalDocs(new ExternalDocs("Find out more about our store", "http://swagger.io")));

		context.setAttribute("swagger", swagger);
```

Then in my Application.java, I have:
```java
@ApplicationPath("/rest/*")
public class MyJerseyApplication extends ResourceConfig {
	private static final Logger Log = LoggerFactory.getLogger(MyJerseyApplication.class);

	@Inject
	public MyJerseyApplication(ServiceLocator serviceLocator) {
		super(
			MyJacksonObjectMapperProvider.class,
			JacksonFeature.class,
			MultiPartFeature.class,
			RolesAllowedDynamicFeature.class,
			ApiListingResource.class,
			SwaggerSerializers.class
		);

		ReflectiveJaxrsScanner scanner = new ReflectiveJaxrsScanner();
		scanner.setResourcePackage("com");
		ScannerFactory.setScanner(scanner);

// Then other setup code
```

I get no errors when I run, but I never get a swagger.json or swagger.yaml output file...is my setup correct considering it sounds like BeanConfig does not work in `1.5.3`?

**Comment by nkoterba** [comment]
@fehguy @todd-richmond 

I just wanted to confirm that I was able to follow the instructions at: https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5

with **1.5.2** and everything worked.  However, when I simply update my gradle to use version **1.5.3** no `swagger.json` or `swagger.yaml` was created at my context path.

So something definitely changed between versions that makes bean configuration in a ResourceConfig application stop working.

For now I will use 1.5.2 until this gets resolved.

**Comment by fehguy** [comment]
Please try 1.5.2-M2-SNAPSHOT.  This should work just fine.
