### ISSUE TITLE
enum model is not getting generated

### ISSUE THREAD

**Issue by mayuranchalia** [swagger-api/swagger-core#928]
Hi, Jersey service is taking enum as query param.Swgger is not generating model for the same ,it just referring qualified class name of enum.

**Comment by webron** [comment]
it would help mentioning the version of Jersey that you use as well as the version of swagger-core.

**Comment by mayuranchalia** [comment]
I am using jersey-server-1.8.jar,jersey-core-1.8.jar and swagger-core_2.9.1-1.3.0.jar

**Comment by webron** [comment]
Well, that release is a year and a half old. I'd start by upgrading to the latest using either 1.3.12 or 1.5.3-M1.

**Comment by mayuranchalia** [comment]
Okay Ron thanks a lot for quick response...I will update the jars..and validate.

**Comment by mayuranchalia** [comment]
If I add this dependency will it work?
<dependency>
	<groupId>com.wordnik</groupId>
	<artifactId>swagger-jaxrs_2.10</artifactId>
	<version>1.3.12</version>
</dependency>

**Comment by webron** [comment]
That's what you should try, yes.
