### ISSUE TITLE
Custom Model creation

### ISSUE THREAD

**Issue by mayuranchalia** [swagger-api/swagger-core#930]
I am trying to create a custom Model for one of my class...
Json string for model is 
```js
{"id": "ArrayOfObject",
      "properties": {
        "array": {
          "type": "array",
          "items": {
            "$ref": "ArrayObj"
          }
        }
      }
   }
```
 convertor.add("com.xml.rpc.xsd.ArrayOfObject", jsonString);       ModelConverters.addConverter(convertor, true);
When I am trying to get the swagger API listing doc ...An exception is thrown...
scala.MatchError: null
	at com.wordnik.swagger.converter.ModelConverters$$anonfun$addRecursive$2.apply(ModelConverters.scala:94)
Not sure how to create model for this kind of class

**Comment by webron** [comment]
Sorry for the delayed response.

Can you provide more details? What's the class you're trying to replace? What does your converted look like (the whole code)?

**Comment by mayuranchalia** [comment]
I have given the model in above comment. Are you asking for com.xml.rpc.xsd.ArrayOfObject Java file?

**Comment by webron** [comment]
Where do you have com.xml.rpc.xsd.ArrayOfObject? As an input? output? Can you provide a sample code where it is used?

**Comment by mayuranchalia** [comment]
This a response from a function.I can also be take as a input via Body...
public class ArrayOfObject {
    protected List<Object> array;
 public List<Object> getArray() {
        if (array == null) {
            array = new ArrayList<Object>();
        }
        return this.array;
    }

}

**Comment by mayuranchalia** [comment]
OverrideConverter convertor = new OverrideConverter();
 String jsonString = "{\"id\": \"ArrayOfObject\",\"properties\": {\"array\": {\"type\": \"Array\",\"items\":{\"$ref\":\"ArrayObj\"}}}}";
 convertor.add("com.xml.rpc.xsd.ArrayOfObject",jsonString );
ModelConverters.addConverter(convertor, true);

**Comment by webron** [comment]
You created a class with the package `com.xml.rpc.xsd.ArrayOfObject`? And as said, please provide a sample of where the class is used, as request, response, including all the annotations around it.

**Comment by fehguy** [comment]
Please reopen if still an issue.
