### ISSUE TITLE
[swagger-jaxrs:1.5.3-M1] Operation without parameters is serialized as a YAML empty array

### ISSUE THREAD

**Issue by bertrand-quenin** [swagger-api/swagger-core#931]
Hi,

When using swagger-jaxrs:1.5.3-M1 `ApiListingResource`, it generates an empty YAML array entry for an operation without parameters. The Swagger editor then complains about this:

```yaml
/users:
    get:
      tags:
      - "users"
      summary: "List all users"
      description: ""
      operationId: "listUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserVo"
```

I think it's because the `Yaml.mapper()`, defined in com.wordnik.swagger.util.Yaml`, is configured with:

```java
 mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
```

Maybe setting it to `JsonInclude.Include.NON_EMPTY` would fix this issue.

Thanks,
BQ.

**Comment by webron** [comment]
This is due to an issue with the json schema we had for the swagger specification which was fixed a few minutes ago. @whitlockjc needs to release a new version of swagger-tools with the new schema, and then @mohsen1 can apply it to the editor and it will valid there as well.

**Comment by bertrand-quenin** [comment]
Ok, I'll wait for the new release then. Thanks for the prompt answer!
