### ISSUE TITLE
[swagger-jaxrs:1.5.3-M1] Leading "---" when using the ApiListingResource YAML resource

### ISSUE THREAD

**Issue by bertrand-quenin** [swagger-api/swagger-core#932]
Hi,

I'm using the `ApiListingResource` to generate a swagger description (2.0) and it works very well. However, the output starts with 3 dashes, `---` which prevents me from using the swagger parser afterhand.

For instance:
```yaml
---
swagger: "2.0"
tags:
- name: "apihooks"
- name: "certificates"
- name: "users"
paths:
  /apihooks:
    get:
      tags:
      - "apihooks"
      summary: "List all API hooks"
      description: ""
      operationId: "listApiHook"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ApiHookVo"
  ...
```

Do you know how I can get rid of these leading dashes ?

Thanks,
BQ.

**Comment by fehguy** [comment]
Hmm.  That is generated by the Jackson YAML module.  If you can look in the Yaml module settings it would help out a lot.

**Comment by webron** [comment]
The leading slashes are not really a mistake. It sounds to me that this is more of an issue with the swagger parser not being able to consume it properly.

**Comment by bquenin** [comment]
You're right, according to YAML specification http://yaml.org/spec/1.2/spec.html#id2760395 , these 3 leading dashes are expected. I'm going to file an issue on the swagger-parser project.

**Comment by bertrand-quenin** [comment]
You're right, according to YAML specification http://yaml.org/spec/1.2/spec.html#id2760395 , these 3 leading dashes are expected. I'm going to file an issue on the swagger-parser project.
