### ISSUE TITLE
[Jersey2] @Produces annotation in provider is not propagated to methods

### ISSUE THREAD

**Issue by Flamenco** [swagger-api/swagger-core#934]
```java
@Provider
@Produces("text/html")
class Foo{
 @GET
 public String bar(){
 }
}
```
Swagger treats bar() as "application/json".  It should default to the provider's settings if not explicitly set.

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by Flamenco** [comment]
I don't have that info right now.  The current from Maven Central most likely.  I am not on a dev branch.  Was this issue already addressed?

**Comment by webron** [comment]
Can't say, but we really need that information to move forward.

**Comment by Flamenco** [comment]
3.1.4

**Comment by webron** [comment]
That's a really old version. My suggestion would be to first upgrade it to 1.3.12 and see if the problem persists.

**Comment by Flamenco** [comment]
It doesn't work with 1.3.12 either.  I was using that first, and then tried 1.3.4.

**Comment by fehguy** [comment]
Please upgrade to 1.5.3-M1.  It should be fixed there and if not, it can be deployed this weekend along with 1.5.0-M2

**Comment by Flamenco** [comment]
Upgraded to latest version and api-docs JSON is no longer published (404) although my other rest resources are available.  Bootstrap and filters are all activated.

**Comment by fehguy** [comment]
The new version uses `swagger.json` as the default listing location.

**Comment by Flamenco** [comment]
@fehguy swagger.json worked and my issue (along with a bunch of other things) is now working.

Thanks :)

**Comment by fehguy** [comment]
Great news!  There will be a new release of swagger-ui any hour now, too.
