### ISSUE TITLE
[jersey2] QueryParam marked as required not working

### ISSUE THREAD

**Issue by Flamenco** [swagger-api/swagger-core#937]
PathParam parameter works:
@ApiParam(required = true) @PathParam("userId") String username

![screen shot 2015-03-28 at 7 15 31 am](https://cloud.githubusercontent.com/assets/819940/6880864/61961ec8-d51a-11e4-94a1-ecfa5ce87913.png)

QueryParam does not work:
@ApiParam(required = true) @QueryParam("username") String username
![screen shot 2015-03-28 at 7 15 56 am](https://cloud.githubusercontent.com/assets/819940/6880865/67e9da9e-d51a-11e4-8d55-0ff8f7ec04ee.png)

**Comment by webron** [comment]
Using which version of swagger-core?

**Comment by Flamenco** [comment]
1.5.2-M1

**Comment by fehguy** [comment]
I believe this is fixed in 1.5.3-M1. Can you please retest?

**Comment by Flamenco** [comment]
with 1.5.3-M1 same issue.  Also note that default values are not working.  

	@GET
	@Path("/goodbye/{name}")
	@ApiOperation(value = "goodbye")
	public String goodbye(@ApiParam(defaultValue = "the-name", required = true) @PathParam("name") String name) {
		return "<Goodbye> Goodbye " + name + " </Goodbye>";
	}

	@GET
	@Path("/goodbye2")
	@ApiOperation(value = "goodbye2")
	public String goodbye2(@ApiParam(defaultValue = "the-name", required = true) @QueryParam("name") String name) {
		return "<Goodbye> Goodbye " + name + " </Goodbye>";
	}
![screen shot 2015-03-28 at 2 43 10 pm](https://cloud.githubusercontent.com/assets/819940/6882375/26232b80-d559-11e4-9359-61664766eebf.png)

**Comment by fehguy** [comment]
Thank you for testing, will assure this is fixed

**Comment by Flamenco** [comment]
Please also notice that the default values don't appear either :(  

The @Default jax-rs annotation does work however, but the docs state that default will be used if that value is not specified.

I would fix this myself but my Scala skills need some work.  For me it's easy and fast to write, but hard to read.

**Comment by shivangshah** [comment]
+1 on "required" not working other than @PathParam
