### ISSUE TITLE
java.lang.NoSuchMethodError: com.wordnik.swagger.jaxrs.config.BeanConfig.setApiReader

### ISSUE THREAD

**Issue by hriyamaharaja** [swagger-api/swagger-core#939]
I am migrating to v1.5.2 . Does BeanConfig no longer support setApiReader and setFilterClass ?

**Comment by fehguy** [comment]
Yes, the are no longer needed.  Can you explain more what you're trying to do?

**Comment by fehguy** [comment]
Actually, you're right.  The setFilterClass is indeed missing

**Comment by hriyamaharaja** [comment]
This is my previous code for beanconfig:
 beanConfig.setApiReader("com.wordnik.swagger.jersey.JerseyApiReader");
beanConfig.setFilterClass("swagerfilter");
I am getting a no such method error for these.

**Comment by fehguy** [comment]
you can remove the setApiReader.  the setFilterClass will be pushed shortly.

**Comment by fehguy** [comment]
If you update to 1.5.4-M1-SNAPSHOT from sonatype-snapshots you will see the setFilterClass on BeanConfig.
