### ISSUE TITLE
custom filter

### ISSUE THREAD

**Issue by Flamenco** [swagger-api/swagger-core#941]
I am trying to develop a filter on the UI side.  My thoughts are to submit an LDAP filter as a query string. 
```
http://localhost:8080/api/swagger.json?filter=...
```
 Before I start implementing, is anyone opposed to:

1. Filtering client requests on the server side
2. Having a query string filter option
3. Using LDAP for the filter representation

This would require additional dependencies for the parsing, but would be quite extensible for many other purposes.

Example:  return post or put methods
```
(|(method=POST)(method=PUT))
```

Example:  return all required APIS with required parameters with name starting with set
```
(&(required=true)(name=set*))
```

Example:  return all items without a note
```
(!(note=*))
```

**Comment by webron** [comment]
@Flamenco - thank you for the suggestion. Are you looking to create a dynamic way to filter out the spec? Can you provide a use case for usage?

I imagine you know you can create a filter using the SwaggerSpecFilter.

**Comment by fehguy** [comment]
Please reopen if still an issue.
