### ISSUE TITLE
can not configure JacksonJsonProvier, especially, set PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

### ISSUE THREAD

**Issue by JunNakamura** [swagger-api/swagger-core#947]
I use swagger-jersey2-jaxrs_2.10 (version 1.3.12) with Jersey 2.2. (and I work in a legacy environment, enable jdk is only 6.)

I want to serialize Swagger's json which property name is snake_case, but I don't find such a setting.
I think  JacksonJsonProvier in swagger-jaxrs serialize json. I tried to change its config, but anything didn't work. Is there somethig way to configure JacksonJsonProvier 's mapper ?

**Comment by fehguy** [comment]
You can try rebuilding swagger-core-1.5.0-M2 with JDK6.  It *should* work.  Please report back after trying

**Comment by JunNakamura** [comment]
Thanks, it did work! 
I can configure com.wordnik.swagger.util.Json.mapper to set PropertyNamingStrategy, then property name is changed to snake_case at /swagger.json.

If not above, properties of classes I defined are still camelCase.(other properties are snake_case)

**Comment by webron** [comment]
Sounds like it worked out. Is there any other issue or can this ticket be closed?

**Comment by JunNakamura** [comment]
Please one more. 

I also use swagger-ui, its version is current master (2.1.0-M2). 
I think this version may not catch base_path cause "BASE URL" in footer is empty. Should I upgrade swagger-ui ?

**Comment by webron** [comment]
2.1.0-M2 is the latest (just released). I believe that part of the footer was removed as you can see from http://petstore.swagger.io.

**Comment by JunNakamura** [comment]
Sorry, my explain is not good.
at demo site,  swagger.json has "host" and "basePath" as below
```
"host":"petstore.swagger.io","basePath":"/v2"
```
and, swagger-ui display  [ base url: /v2 , api version: 1.0.0 ] .


On the other hand, in my case,
swagger.json have "host" and "base_path" as below.

```
"host":"localhost:8080","base_path":"/path/to"
```

swagger-ui display [ base url: , api version: 1.0.0 ] and request url is "http://localhost:8080/xxx" when pushing "Try it". (uri  must be http://localhost:8080/path/to/xxx)

I think current swagger-ui do not handle snake_case such a "base_path". ( In my local swagger-ui, http://localhost:8080/path/swagger-ui/ display the same as demo site.)

**Comment by webron** [comment]
@JunNakamura - it's not supposed to handle `base_path` because the spec states it needs to be `basePath`.

**Comment by JunNakamura** [comment]
@webron 

OK, I see. 
I want to deploy my api with swagger which is enable to try its api. I give priority to it,　I use current release version of swagger-core and swagger-ui. I want they support snake_case in the future.

It is OK to close this issue if you so. Thanks for helping!
