### ISSUE TITLE
protocols() value in @Api and @ApiOperation should change and be parsed

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#953]
Right now, `protocols()` is a string in both `@Api` and `@ApiOperation`. We should consider the following changes:

- Change the type from string to string[], to avoid having to split values (easier input). This is a breaking change since it changes the annotation, but in 1.3.X this value was never used. If we do this change, it should be done in both annotations. Another possible change - instead of array of strings, array of Scheme Enum with fixed values (HTTP, HTTPS, WS, WSS) as given by the spec. We may not want to restrict it though.
- JaxRS Reader reads the value from `@ApiOperation` but does not process the value from `@Api`. It should read the value from `@Api` and assign the value to all operations, unless explicitly overridden by `@ApiOperation`.

**Comment by webron** [comment]
Updated original topic with an alternative to `protocols()`'s value.

**Comment by webron** [comment]
FWIW, don't change the type to string[], let's keep the breaking changes for a minimum Keep it as string.

Also, make sure to provide proper tests, especially with the combination of `@Api` and `@ApiOperation`.

**Comment by fehguy** [comment]
fixed in #1014
