### ISSUE TITLE
Modifications to response declarations

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#955]
Following changes are proposed:

- Either deprecate response-related values from `@ApiOperation` or add a `code()` field to it to be able to set the HTTP status code (it's not always 200). Even if deprecated, the values will be read, it's just there to encourage people to move to `@ApiResponse` for successful responses as well.
- Add `responseContainer()` to `@ApiResponse`.

**Comment by fehguy** [comment]
I suggest the latter to maintain 1.3.x compatibility

**Comment by fehguy** [comment]
fixed in #1017
