### ISSUE TITLE
update changelog

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#959]

**Comment by webron** [comment]
What's done is done.

**Comment by testn** [comment]
but still no changelog for 1.5.x release?

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-core/releases - changelog

**Comment by testn** [comment]
Thanks. Please update the link in this page then... https://github.com/swagger-api/swagger-core

**Comment by webron** [comment]
Thanks for the feedback, updated.
