### ISSUE TITLE
@ApiModel value ignored

### ISSUE THREAD

**Issue by chasetec** [swagger-api/swagger-core#964]
I have a Jersey 1 application using swagger-jersey-jaxrs_2.11 version 1.3.12. With a simple Jackson POJO model class I am trying to change the model name/id in the generated Swagger 1.2 spec. My example is:

    import com.wordnik.swagger.annotations.ApiModel;
    import org.codehaus.jackson.map.annotate.JsonSerialize;
    
    @ApiModel(value="BOB", description="A user in the application.")
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    public class User {
        public String email;
        public String firstName;
        public String lastName;
    }

According to https://github.com/swagger-api/swagger-core/wiki/Annotations#apimodel I should see my custom value as the id of this model but I only see the description getting used.

    "User":{"id":"User","description":"A user in the application.","properties":{"email":{"type":"string"},"firstName":{"type":"string"},"lastName":{"type":"string"}}}

**Comment by fehguy** [comment]
Please upgrade to 1.5.1-M2, this should be supported now.
