### ISSUE TITLE
Is it possible to setup swagger ti cxf without spring ?

### ISSUE THREAD

**Issue by mariuszcrust** [swagger-api/swagger-core#967]
Hi
This is only a question. I am trying to integrate swagger into project. We are currently using CXF wihout  Spring (we have javax.inject). I succedd in setup uri to api etc ..., but swagger was not managed to find resource packages to scan and json contained only version and uri, without any api.

If this is possible can you please direct me to some example, tutorial or sources ?

Many thanks in advance

**Comment by webron** [comment]
For general support questions, it's better to use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). Please start a thread there and provide additional information such as the version of swagger-core and CXF you're using, plus the method you use to configure swagger-core (web.xml, BeanConfig and so on).
