### ISSUE TITLE
Annotations on interfaces require common package

### ISSUE THREAD

**Issue by pike1212** [swagger-api/swagger-core#969]
I have a resource that implements an interface and the JAX-RS annotations are on the interface.  To get swagger to work properly I have to...

1. Use ReflectiveJaxrsScanner
2. Put both my implementation and interface in the same package since the reflective scanner only allows one package
3. Put the Swagger annotations in my interface

Number 2 here is the biggest issue for me.

This is relate to issue ![#562](https://github.com/swagger-api/swagger-core/issues/562).

**Comment by webron** [comment]
Which version of swagger-core do you use?

**Comment by pike1212** [comment]
1.3.12

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-core/tree/v1.3.12/samples/java-resteasy-spring shows an example where the interfaces and implementations are in different packages and it works fine.

**Comment by pike1212** [comment]
Thanks! Changing ReflectiveJaxrsScanner to point to the package with the interfaces instead of the package with the implementations seems to have fixed the issue.
