### ISSUE TITLE
DefaultValue missing in post body of swagger.json in 1.5.3-M1

### ISSUE THREAD

**Issue by swarupe04** [swagger-api/swagger-core#970]
Sample json from 1.5.3-M1

```
{
  in: "body",
  name: "body",
  description: "report request json object",
  required: false,
  schema: {
    $ref: "#/definitions/base class to support all types of Report Requests"
  }
}
```

Same api on old 1.3 swagger:
```
{
  name: "body",
  description: "report request json object",
  defaultValue: "{}",
  required: false,
  type: "ReportRequest",
  paramType: "body",
  allowMultiple: false
},
```
Please let me know, if u need more details

**Comment by webron** [comment]
First, what part of your code generates the default value?
Second, you should try that with the latest version first - 1.5.1-M2.

**Comment by swarupe04** [comment]
Here's sample resource method that has DefaultValue set for a post json object. 
Actually we added this defaultValue as workaround since swagger ui wasn't treating it correctly if empty post body. I had created an issue for this too on ui side: https://github.com/swagger-api/swagger-ui/issues/1131

@Path("/instant")
    @JsonView(ReportResultViews.AOPSummary.class)
    @POST
    @Valid
    @ApiOperation(value = "Get report data instantly", notes = "", response = PaginatedResult.class, position = 2)
    @ApiResponses(value = {
            @ApiResponse(code = 404, message = "Report type not found"),
            @ApiResponse(code = 403, message = "No permission to access the report") })
    public PaginatedResult<ReportResult> createInstantReport (
            @BeanParam
            ReportRequest qpRequest,

            @ApiParam(value = "report request json object")
            @DefaultValue("{}")
            ReportRequest request,

            @ApiParam(value = "report id for pagination", defaultValue = "0")
            @QueryParam("reportId")
            long reportId,

            @ApiParam(value = "page offset")
            @DefaultValue("0")
            @QueryParam("offset")
            long offset,

            @ApiParam(value = "max limit rows per page")
            @DefaultValue("100")
            @QueryParam("limit")
            @Max(10000)
            long limit,

            @Context
            HttpServletRequest httpServletRequest)
            throws ServiceException

**Comment by swarupe04** [comment]
just to clarify.. is 1.5.1-M2 latest compare to 1.5.3-M1?

will try it  out..

Thanks

**Comment by webron** [comment]
It is. The point release refers to the milestone, and not the other way around.

**Comment by swarupe04** [comment]
tried with 1.5.1-M2 ..same issue

**Comment by swarupe04** [comment]
trying it with adding defaultValue to ApiParam

**Comment by webron** [comment]
Not saying the `@DefaultValue` shouldn't be read, but for now, you can try adding the default value to the `@ApiParam`:

```java
            @ApiParam(value = "report request json object", defaultValue="{}")
            ReportRequest request,
```

**Comment by webron** [comment]
oh, I missed your comment.

**Comment by swarupe04** [comment]
tried it ..no luck

**Comment by webron** [comment]
Which of the swagger-core dependencies do you use?

**Comment by swarupe04** [comment]
Actually when i moved to 1.5.1-M2, noticed that it didn't recognize
@DefaultValue in @BeanParam object. 1.5.3-M1 was fine. I believe I had this
issue earlier when 'fehguy' fixed it in 1.5.3-M1. Maybe it wasn't moved to
M2


 <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>${swagger.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-core</artifactId>
            <version>${swagger.version}</version>
        </dependency>

with swagger.version as 1.5.3-M1 and then 1.5.1-M2

**Comment by swarupe04** [comment]
Please see the conversation at the end of this issue that was related to
@DefaultValue on @BeanParam:
https://github.com/swagger-api/swagger-core/issues/917

**Comment by swarupe04** [comment]
fyi..I'm going to be on 1.5.3-M1 for now until we've both the fixes.

**Comment by webron** [comment]
Is the issue with the default value only when used within a BeanParam?

**Comment by swarupe04** [comment]
If I'm on 1.5.1-M2, it has both the issues - DefaultValue within BeanParam,
and DefaultValue on Post body json object param, not recognized
on 1.5.3-M1, only one issue: DefaultValue on Post body json object param,
not recognized

**Comment by swarupe04** [comment]
This morning hitting strange issue. DefaultValue within BeanParam seems
very inconsistent. It works sometimes and other times not. I've tried
switching between M1 and M2, and I'm verifying only the json
http://localhost:8080/reporting/swagger.json. I can see that sometimes it
shows default field and other times not.
Any idea, how this is possible?

**Comment by webron** [comment]
@whitlockjc - you handled the BeanParams in 1.5, no? Can you please check this issue?

**Comment by swarupe04** [comment]
Looks like behavior is same on M1 or M2, so using M2 since that's latest.

I'm suspecting if it's related to thread safe issue and scanning of
resources isn't happening fully.
Almost the first time, i startup the instance it seems to not show
DefaultValue, but somehow does show later. I'm not able to reproduce this
scenario, and I can see it's hard to debug if it's inconsistent.

**Comment by swarupe04** [comment]
Looks like atleast @ApiParam default value works.

**Comment by swarupe04** [comment]
Any status on this issue. Also wanted to clarify that ApiParam defaultValue doesn't work for JSON object param. This had worked in 1.3 version

Thanks

**Comment by webron** [comment]
@swarupe04 - we're working on this issue now, but "DefaultValue on Post body json" is unclear. Can you supply a sample code for it to show us exactly what isn't working?

**Comment by swarupe04** [comment]
it's basically on body param on resource method:

public void resourceMethod() {
  @ApiParam(value = "report request json object", defaultValue = "{}")
            @DefaultValue("{}")
            SummaryReportRequest request
}

**Comment by webron** [comment]
@swarupe04 - okay. We could probably provide partial support for it. It may be translated to a *string* default value and not a JSON object, which will in effect create an invalid Swagger definition.

**Comment by swarupe04** [comment]
OK. This was actually a workaround we wanted to try..since swagger ui on
post was not sending the content type as application/json when post body
was empty.

**Comment by csuich2** [comment]
I think I'm running into a similar issue, but figured I'd piggyback here until we determine it is a separate issue (in which case I'll open a separate issue).

I have an API model and am using @ApiModelProperty to indicate my model fields but haven't found a way to specify a default value. The annotation doesn't have a defaultValue field and jax-rs @DefaultValue doesn't seem to work. Am I missing some way to indicate a default value with an @ApiModelProperty?

**Comment by webron** [comment]
@csuich2 - I believe that would be supported with JSR 303 integration (#800).

**Comment by csuich2** [comment]
Thanks @webron - not sure how I missed that issue. I'll sit tight!

**Comment by webron** [comment]
Fixed in develop_2.0
