### ISSUE TITLE
@ApiOperation responseContainer 

### ISSUE THREAD

**Issue by vvicario** [swagger-api/swagger-core#976]
Hi, I'm having issues trying to set the responseContainer to List or Array. Swagger UI is displaying Model Shema tab empty and Model looks like:  List[[org.com.myapp.http.service.MyAPI$ObjectDesc]. 

I'm using:
dropwizard-swagger: 0.5.3
dropwizard: 0.7.0
Swagger API:1.3.12
Swagger UI: v2.1.4-M1 

I really appreciate if someone has any suggestion

![model](https://cloud.githubusercontent.com/assets/11353754/7093164/36c83e24-df8d-11e4-85d6-7e6409ffaa4f.png)

**Comment by fehguy** [comment]
Please share you annotation values.

**Comment by vvicario** [comment]
@fehguy This is the annotation that I'm using.
 
@ApiOperation(value = "Querying for Objects by Name",
                  response = ObjectDesc.class,
                  responseContainer = "List",
                  httpMethod = "GET")
Thanks!

**Comment by fehguy** [comment]
That sure looks correct to me. To debug this, could you please remove the httpMethod value?

**Comment by vvicario** [comment]
@fehguy  I've removed the httpMethod value but still the same issue.

**Comment by fehguy** [comment]
Is the model an inner class?  Please set debug logging for com.wordnik and paste the output.

**Comment by vvicario** [comment]
it's not an inner class, I defined it like :
 @ApiModel(value = "MyClass")
  public static class MyClass extends ObjectCore

Debug logging:

DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: validating datatype java.lang.Long against 11 keys, got java.lang.Long
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: inspecting java.lang.Long
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: validating datatype Long against 11 keys, got long
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: validating datatype long against 11 keys, got long
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: added param type java.lang.Long for field sizeEstimateBytes
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing field public java.lang.String org.genomebridge.boss.http.models.ObjectCore.ownerId
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: validating datatype java.lang.String against 11 keys, got java.lang.String
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: inspecting java.lang.String
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: validating datatype String against 11 keys, got string
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: validating datatype string against 11 keys, got string
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: added param type java.lang.String for field ownerId
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing class class java.lang.Object
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing method public final void java.lang.Object.wait() throws java.lang.InterruptedException
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing method public java.lang.String java.lang.Object.toString()
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing method public native int java.lang.Object.hashCode()
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing method public final native java.lang.Class java.lang.Object.getClass()
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: inspecting null
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: skipping class
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing method public final native void java.lang.Object.notify()
DEBUG [2015-04-10 19:55:37,439] com.wordnik.swagger.converter.ModelPropertyParser: processing method public final native void java.lang.Object.notifyAll()

Thanks

**Comment by webron** [comment]
@vvicario - it looks like your model *is* an inner class (defined under an interface, but still). Since you're contributing to swaggerizing an open-source project's API, you can simply point us to the code to easy up the debugging. 

In this case, I imagine the class we're looking at is https://github.com/broadinstitute/vault-boss/blob/vv_swaggerize_boss/boss-ws/src/main/java/org/genomebridge/boss/http/service/BossAPI.java#L16-L24 though I'm not certain what operation it is that you're describing. If you can provide that with that information, we can also test things locally.

And thank you for doing this - we're always happy to see open source projects adopt Swagger as their API documentation mechanism.

**Comment by vvicario** [comment]
@webron  Oh, you are right it's an inner class.That might be the problem. I tested it for another class and it's  working. So, is there a way to use responseContainer for inner classes? Or should I extract the inner class?

Thank you very much for your time!

**Comment by fehguy** [comment]
Is it a static public class?  Or package private?

**Comment by vvicario** [comment]
public static class

**Comment by fehguy** [comment]
This could be a classloader issue.  Is it in the same library as your resource app?  You're not using OSGi by chance?

**Comment by vvicario** [comment]
We are not currently usign OSGi, I'll try to find the classloader issue. Thank you very much for  your help :)

**Comment by kinetifex** [comment]
I'm running into this exact same issue, using inner public static class for responses with responseContainer = "List". Is there a solution besides extracting inner classes?

**Comment by webron** [comment]
@vvicario - any updates?

**Comment by vvicario** [comment]
The only way  i found was extracting inner classes. Regards.

**Comment by webron** [comment]
Thanks. In that case it looks like there's a problem. We'll investigate further.

**Comment by webron** [comment]
@vvicario - looks like swagger-dropwizard has released a new version that's based on our 1.5 version. That produced Swagger 2.0 specification files which is the latest one.

@tomtit has tested a similar use case (he's going to add the test to the code) and the output was fine. So this could very well be an issue with swagger-core 1.3.X. If you can upgrade to swagger-dropwizard 0.7.0, it should solve your problem.

@kinetifex - which library and version do you use for generating the Swagger definition?

**Comment by kinetifex** [comment]
@webron - I am using swagger-jersey2-jaxrs_2.10 on version 1.3.12

**Comment by webron** [comment]
@kinetifex - looks like you need to upgrade to 1.5 then.

**Comment by webron** [comment]
@vvicario - are you able to upgrade and see if it works? I'

**Comment by webron** [comment]
This is fixed in develop_2.0.

**Comment by vvicario** [comment]
@webron Thanks! :+1:
