### ISSUE TITLE
Add a way to filter tags in SwaggerSpecFilter

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-core#977]
Due to the separation of tag declaration from operations, there needs to be a way to filter out the tags that are added to the top level Swagger object.

Even though it ends up being an empty tag and will not appear in the UI, it will still hint users that something may be missing and that's a security concern.

This is not to filter out operations based on tags, just filter the tag names (and descriptions) from the generated Swagger definition.

**Comment by fehguy** [comment]
Please explain more.  You're saying the `tags` array at top-level will have filtered out descriptions, but the operations will exist if they reference the tag?  Or if the tag is removed, we will remove the operation?  Or make it `default`?

**Comment by webron** [comment]
It will not affect the operation at all, and the behavior would be the same as if the tag was never declared at the top level `tags` (which means, if the tag appears in an operation, it will still appear in the UI as a tag, but will have no description, for example).

While working on the migration of the samples, I noticed that when we filter the operations, we basically hide all the 'store' operations, unless accessed with the `special-key`. However, since the tags are declared elsewhere, they still appear at the top-level `tags` and it's a bit obvious that something is out of place.

Is that clearer?

**Comment by webron** [comment]
Fixed in develop_2.0.
