### ISSUE TITLE
How to add a custom JacksonAnnotationIntrospector to SwaggerSerializers?

### ISSUE THREAD

**Issue by bertramn** [swagger-api/swagger-core#982]
Hi there,

is it possible to add a feature to register a custom `JacksonAnnotationIntrospector` or provide some Jackson Modules to the `com.wordnik.swagger.jaxrs.listing.SwaggerSerializers` class? I have a use case where the POJO is annotated with an annotation that mixes in `@JsonProperty` and I use a custom annotation introspector to disable this mixin when the POJO is returned via the REST API. Unfortunately swagger does not know about this and renders the name as specified by the normally disabled mixin annotation.

What swagger says about the model:
```json
{
  "_id": "string"
}
```
What is actually returned by the REST API
```json
{
  "id": "5524d711d2b2694b8ee0a5fe"
}
```

This is the POJO:
```java
@XmlRootElement(name = "Bla")
public class Bla implements Serializable
{

    @XmlAttribute(name = "id")
    @Id
    @ObjectId
    protected String id;

    ...

}
```

`@Id` looks like this

```java
@Retention(RUNTIME)
@JacksonAnnotationsInside

@JsonProperty("_id")
public @interface Id {
}
```

and I use a `JacksonAnnotationIntrospector` like below with success only catch is, I can't add the introspector to the swagger renderer :(

```java
...
/**
 * 
 * A {@link JacksonAnnotationIntrospector} that will ensure any jongo specific
 * annotations are removed from the mapper context. This will ensure that a
 * jongo annotated object can be marshaled properly.
 * <p/>
 * 
 * Please note that if any field in the class is of type
 * {@link org.bson.types.ObjectId}, a set of serializers/deserializers must also
 * be added to the mapper context.
 *
 */
public class JongoDisablingAnnotationIntrospector extends JacksonAnnotationIntrospector {

	/**
	 * Ignore both serialisation
	 */
	@Override
	public boolean isAnnotationBundle(Annotation ann) {
		if (ann.annotationType().equals(Id.class)) {
			return false;
		} else if (ann.annotationType().equals(ObjectId.class)) {
			return false;
		} else {
			return super.isAnnotationBundle(ann);
		}
	}

	/**
	 * Remove the jongo {@link ObjectIdSerializer} if placed in the code by any
	 * other means than the {@link ObjectId} annotation.
	 */
	@Override
	public Object findSerializer(Annotated am) {
		Object serializer = super.findSerializer(am);
		if (ObjectIdSerializer.class.equals(serializer)) {
			return null;
		}
		return serializer;
	}

	/**
	 * Remove the jongo {@link ObjectIdDeserializer} if placed in the code by
	 * any other means than the {@link ObjectId} annotation. directly.
	 */
	@Override
	public Class<? extends JsonDeserializer<?>> findDeserializer(Annotated a) {
		Class<? extends JsonDeserializer<?>> deserializer = super.findDeserializer(a);
		if (ObjectIdDeserializer.class.equals(deserializer)) {
			return null;
		}
		return deserializer;
	}
}
```

**Comment by webron** [comment]
@bertramn - it's been a while since I tinkered with these things, but how would you normally register a custom JacksonAnnotationIntrospector in your own application?

**Comment by bertramn** [comment]
Normally an Introspector is set on the ObjectMapper during configuration like `mapper.setAnnotationIntrospector(introspector);` but one can also wrap this in a Jackson Module. I think all that is needed is a static function on the SwaggerSerializers like:

```java
public static void registerModule(Module module) {
	yaml.registerModule(module);
}
```

but I did actually mucked around and created a custom SwaggerSerializers with the introspector that drops the annotated field. Unfortunately is seems that your component does not use the introspector at all as the field still comes out with the wrong name. For the time being I am just adding annotation `@ApiModelProperty(name = "id")` in the model so the field name renders correctly in the documentation. I think the use case I got is just too complicated and only caused by a [minor design flaw](https://github.com/bguerout/jongo/issues/212) in the Jongo library that will be fixed in the next release. Unless you like to understand the use case in detail, I am inclined to just close the issue as edge case with viable workaround.

**Comment by webron** [comment]
That would affect the YAML generator. If you want affect the JSON, you can get the ObjectMapper using `JSON.mapper()`. So if you throw that around your application bootstrap, you can use that to register your custom introspection and it should work.

**Comment by bertramn** [comment]
Well I want to affect both JSON and YAML because the field is only called `_id` when it goes to the MongoDB but everywhere else such as in the bean, doc or out the other end through the API it should just be `id`. When you say `JSON` you refer to `com.wordnik.swagger.util.Json` right?

**Comment by webron** [comment]
Yup. Looks like extending the YAML ObjectMapper would be a tad more challenging at the moment.

**Comment by fehguy** [comment]
Hi, you should be able to call `Json.mapper()` to get access to the underlying mapper to register additional components.

**Comment by webron** [comment]
But would that affect the YAML generation as well, @fehguy? That's controlled by a different ObjectMapper created in the SwaggerSerializers which is not as easily accessible.

**Comment by fehguy** [comment]
@ron is correct.  You would need to do the same thing for YAML:

`ObjectMapper mapper = Yaml.mapper()`

If you modify this mapper, it will affect the serializers for the spec.

**Comment by webron** [comment]
@fehguy - there may be a slight issue then. It looks like `SwaggerSerializers` uses its own object mapper for YAML rather than using the `Yaml` class.

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/listing/SwaggerSerializers.java#L34-L39
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/listing/SwaggerSerializers.java#L71

Is this the intended behavior or should it be rewritten to use the Yaml class?

**Comment by fehguy** [comment]
should use the Yaml class.  that would be a bug.

**Comment by webron** [comment]
Great, I'll open an issue.

**Comment by webron** [comment]
@bertramn - any updates?

**Comment by bertramn** [comment]
Hmm I am looking at swagger-jaxrs master and nothing has really changed that would allow the ObjectMapper to be configured with an annotation introspector.

**Comment by webron** [comment]
@bertramn - it's updated in develop_2.0.

**Comment by fehguy** [comment]
Please reopen if still an issue.
