### ISSUE TITLE
Instable String comparison in BeanConfig

### ISSUE THREAD

**Issue by ctolkmit** [swagger-api/swagger-core#983]
In Version 1.5.1-M2 we find the following code around lines 159ff:

    public Set<Class<?>> classes() {
        ConfigurationBuilder config = new ConfigurationBuilder();
        Set<String> acceptablePackages = new HashSet<String>();

        if(resourcePackage != "") {
            String[] parts = resourcePackage.split(",");
            // ... rest omitted

It would be better to write `if(!"".equals(resourcePackage))` instead, and not compare by String identity.
And best check for `null` as well -> `if(resourcePacke != null && !"".equals(resourcePackage))`

**Comment by webron** [comment]
Heh, oh wow. Can you please submit a PR fixing this issue? If so, please submit against the develop_2.0 branch.

**Comment by ctolkmit** [comment]
I can try (never did that on GitHub before ;-))

**Comment by webron** [comment]
It should be fairly easy, just make sure to start off the develop_2.0 branch and submit against the develop_2.0 branch. Thanks for giving it a shot.

**Comment by ctolkmit** [comment]
i hope i did everything correctly. let me know if there are any other issues.

**Comment by webron** [comment]
Since the PR was merged, closing the issue.
