### ISSUE TITLE
Swagger 2.0 @ApiOperation annotation does not allow setting of operationId

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-core#989]
According to current master snapshot of [ApiOperation class](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiOperation.java), there is no facility for setting `operationId`.  

It would be nice to set `operationId` like so:

```
    @RequestMapping(
        value = "/books", 
        method = RequestMethod.POST, 
        consumes = MediaType.APPLICATION_JSON_VALUE,       
        produces = MediaType.APPLICATION_JSON_VALUE)
    @ApiOperation(
        value = "Create a book",
        notes = "Creates a book so that it can be managed by this api.",
        response = Book.class,
        operationId = "add_book"
    )
    public Book createBook(
        @ApiParam(value = "Book object", required = true) @RequestBody @Valid Book book) {
        return bookService.createBook(book);
    }
```

**Comment by webron** [comment]
It actually does - https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-annotations/src/main/java/com/wordnik/swagger/annotations/ApiOperation.java#L59.

**Comment by who** [comment]
I did indeed see `nickname`, but I thought the Swagger 2.0 spec did away with `nickname` and changed the `operationId` ?

The string "nickname" doesn't even exist in the [Swagger 2.0 spec definition](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md).

**Comment by webron** [comment]
We're keeping the same signature for annotations where possible and only adding new fields if needed. Since in `nickname` was changed to `operationId` between 1.2 and 2.0, and since we want to keep the migration between swagger-core 1.3 to 1.5 as simple as possible, we decided not to change the name of the field in the annotation.

**Comment by who** [comment]
Ok, got it. That makes sense. Perhaps an update to the comments regarding how operationId is populated by nickname would be worth adding.

**Comment by webron** [comment]
I'm working on a revamp to the javadocs, should make a PR with the updates soon.

**Comment by who** [comment]
Excellent.  Thank you!
