### ISSUE TITLE
Update petstore example's body parameter to required

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-core#990]
Currently, Petstore example sets the body parameter to optional (required set to false)

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L43

As discuss with @webron the body parameter should be set to required.

swagger-api/swagger-codegen#653

**Comment by webron** [comment]
This is actually due to this bug - https://github.com/swagger-api/swagger-core/issues/971 which is already fixed in develop_2.0.
