### ISSUE TITLE
Custom Formats not parsable?

### ISSUE THREAD

**Issue by RobWin** [swagger-api/swagger-core#993]
Hello, I use the swagger-parser in https://github.com/RobWin/swagger2markup.

I have added an emailAddr with format "email" to the Swagger Petstore example:

```
"Order": {
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "petId": {
                    "type": "integer",
                    "format": "int64"
                },
                "quantity": {
                    "type": "integer",
                    "format": "int32"
                },
                "shipDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "status": {
                    "type": "string",
                    "description": "Order Status"
                },
                "complete": {
                    "type": "boolean"
                },
                "emailAddr": {
                    "type": "string",
                    "format": "email"
                }
            }
```

And it seems that the Swagger parser (and core) do not add the emailAddr to the Swagger model:

![image](https://cloud.githubusercontent.com/assets/5815046/7175767/81eefd7c-e418-11e4-936b-31405225e30a.png)

If I have a Model like:
```
"Order":{
 "properties": {
                "emailAddr": {
                    "type": "string",
                    "format": "email"
                }
            }
}
```

The properties Map is null:

![image](https://cloud.githubusercontent.com/assets/5815046/7175794/cf5db68e-e418-11e4-9c1c-315040ac8a35.png)

The JsonNode in the parser is correct:

![image](https://cloud.githubusercontent.com/assets/5815046/7176242/e2cbc25c-e41c-11e4-99ef-40cbb15d22f3.png)

The PropertyDeserializer can see the field correctly

![image](https://cloud.githubusercontent.com/assets/5815046/7177789/cc81ce94-e429-11e4-9a13-7df0038e61ed.png)

The problem is in the PropertyBuilder and there in StringProperty.isType

```
  //TODO: implement additional formats
  public static boolean isType(String type, String format) {
    if("string".equals(type) && (format == null || "uri".equals(format) || "byte".equals(format)))
      return true;
    else return false;
  }
```

There should be some CustomProperty which is used then, if it's a custom format.

Thanks in advance.
Robert

**Comment by jasonh-n-austin** [comment]
+1 confirmed this issue today. This seems to violate spec (certainly in the perspective of JSON Schema), as parsers should ignore unknown custom formats:
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types
> However, the format property is an open string-valued property, and can have any value to support documentation needs. Formats such as "email", "uuid", etc., can be used even though they are not defined by this specification.

**Comment by webron** [comment]
Thanks for bringing it up. Can't guarantee a timeline here, but we'll try to look into it.

**Comment by fehguy** [comment]
There are now fallbacks for custom formats, and you won't get a NPE if you don't match specific values.  Please reopen if you're still having an issue.
