### ISSUE TITLE
"access" param handling for operations

### ISSUE THREAD

**Issue by zyro23** [swagger-api/swagger-core#996]
using swagger-core-1.5.1-M2.

feature request for adding an `access` param to `@ApiOperation`/`Operation`.

That way, all filtering methods of `SwaggerSpecFilter` could access their corresponding `access` param for the filtering decision (`isOperationAllowed`, `isParamAllowed`, `isPropertyAllowed`).

thanks, zyro

**Comment by zyro23** [comment]
i understand that this is tagged Feature for the idea of adding an `access` param to `@ApiOperation`.

however, i fail to see how the currently available `@ApiModelProperty`.`access` is supposed to be used properly if it cannot be evaluated from a `SwaggerSpecFilter`?

i would be ok with a workaround in the meantime, too. thanks, zyro

**Comment by webron** [comment]
Apologies, read the issue too quickly. Regarding `@ApiModelProperty`, you are correct. Organization-wise though, you need to pick whether this issue deals with this problem or the feature request, and open an additional issue to cover the other part. We can definitely fix the `@ApiModelProperty` issue.

**Comment by zyro23** [comment]
sure will quickly open a new one for the `@ApiModelProperty` "bug" as this one is now already tagged feature

**Comment by webron** [comment]
I can change the tags, it's no problem, but if you a new one for the bug, make sure to change the title of this one.

I'd create one for the feature request and leave this one for the bug. Up to you.
