### ISSUE TITLE
RestEasy 3.x integration

### ISSUE THREAD

**Issue by ben-manes** [swagger-api/swagger-core#997]
Due to Jersey2 not integrating cleanly with Guice, I'm using RestEasy 3.x for JAX-RS 2. The documentation only provides RestEasy 2.x and Jersey samples. I think that the Jersey2 module could be adapted, but I haven't looked into that yet.

**Comment by webron** [comment]
If you need JAX-RS 2 support with RESTEasy, use the swagger-jersey2-jaxrs module. The module adds support for jax-rs 2 and file uploads when using Jersey 2. It should work just as well for RESTEasy, only without the file upload support. If you require it, that can be resolved differently.

**Comment by ben-manes** [comment]
Yep, that's what I'm experimenting with right now.

**Comment by webron** [comment]
@ben-manes - any updates?

**Comment by ben-manes** [comment]
I only got as far as a the basics working before switching off to other tasks. What I had found was,
 *  `JerseyJaxrsConfig` has to be replaced a `ServletContextListener` supplying a `BeanConfig`.
 * The `DefaultJaxrsScanner` isn't useful because there is no `Application` bounded, so a custom scanner is needed.

That custom scanner will either pull the classes from `ResteasyProviderFactory` or walking the Guice injector mimic'ing what `ModuleProcessor` does. I haven't tried writing it yet, so that's my next task.

I integrated Guice + Jersey 1.x + Swagger 1.x a few years ago and there was a lot of quirks at the time, so I imagine there will be some unexpected issues this time around too.

**Comment by ben-manes** [comment]
It would be helpful if M2-SNAPSHOT was published as the BeanConfig in M1 does not support multiple resource packages.

**Comment by ben-manes** [comment]
Okay, here's a [gist](https://gist.github.com/ben-manes/af6ab5e857f29f55d990) that performs the integration. Feel free to adapt as you see fit.

It was easier to scan the Guice bindings than determine how to extract the resource classes from RestEasy's registry. Most likely the `DefaultJaxrsScanner` will work in a non-Guice setup.

**Comment by fehguy** [comment]
thanks @ben-manes.  There is an m2-snapshot in sonatype, fyi.

**Comment by ben-manes** [comment]
I found that there's `1.5.3-M1` on Maven Central, which has the changes needed to remove the `ResourceConfig` class. The pom on master would indicate that `1.5.1-M1` is the latest release, which is what I was using, so I'm not sure what the version history is.

**Comment by fehguy** [comment]
oh for shame.  The snapshot wasn't pushed---I've just done it:

https://oss.sonatype.org/content/repositories/snapshots/com/wordnik/swagger-core/

Sorry about that.

**Comment by ben-manes** [comment]
The version history on Maven Central is confusing if going by dates:

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.wordnik%22%20AND%20a%3A%22swagger-project%22

It indicates that `1.5.1-M2` was released after `1.5.3-M1`.

I had expected master to be a SNAPSHOT version so when looking at the code I had taken `1.5.1-M1` instead of looking at central, which caused me to pull an old BeanConfig class. I'm not sure what the release I should point to as the latest.

**Comment by webron** [comment]
`master` is stable, `develop_2.0` is snapshot.

`1.5.1-M2` is indeed newer than `1.5.3-M1`.

**Comment by natros** [comment]
I'm also using resteasy 3 with guice 4 but my configuration is a bit simpler
https://gist.github.com/natros/370c0093fa60379c3901

I'm missing file upload support.

**Comment by webron** [comment]
@natros - there's no file upload support for RESTEasy. You can easily add it on your own though by creating a `SwaggerExtension`. Check out https://github.com/swagger-api/swagger-core/pull/1023 for an example. Registering the `SwaggerExtension` is very simple as we use the standard SPI mechanism.

**Comment by webron** [comment]
@ben-manes - any updates?

**Comment by ben-manes** [comment]
No, what additional information do you expect?

**Comment by webron** [comment]
You asked which release to try and were provided with the information.

**Comment by ben-manes** [comment]
Sure, and I showed working code using a recent release. This works from my perspective.

**Comment by webron** [comment]
Thanks. I'll keep the issue open so that we may be able to provide easier integration in the future.

**Comment by lpellegr** [comment]
@ben-manes Could you please add an example for the web.xml used? a full example would be really helpful.

**Comment by ben-manes** [comment]
I didn't use a web.xml file because I prefer running Jetty as an embedded library, so everything is configured in Guice. Here's a [gist](https://gist.github.com/ben-manes/6aedde77035cd594d438) of how that's done.

**Comment by mrj365** [comment]
Hello all. I have created an example for Using Swagger 2.0 and RestEasy 3 and Spring on Jboss eap 6/Jboss 7 using a web.xml

https://github.com/mrj365/RestEasy-3.09-Spring-3.2.5-Swagger2.0

**Comment by webron** [comment]
What's the question, @mrj365?

**Comment by mrj365** [comment]
@lpellegr was looking for a web.xml example. I provided one.

**Comment by webron** [comment]
Awesome, thanks! :)

**Comment by jmrossy** [comment]
I've also got this working with a setup very similar to mrj365's example.
Are there any known issues / unsupported features with swagger 2.0 and RestEasy 3?

**Comment by webron** [comment]
@jmrossy - nope, everything should work as with other frameworks.
